// dungeons.js
//


top.dungeons = [




  {"title": "d6 This place is a...", "id":"d6thisplaceisa_elementalwaterdungeon", "roll":[
  "Sea cave.",
  "Series of flooded tunnels deep underground.",
  "Stronghold built by aquatic beings.",
  "Temple dedicated to a watery god.",
  "Palace built by a water elemental lord.",
  "Sewer gone wrong.",   ]},
   {"title": "d6 Water level The chambers in this place...", "id":"d6waterlevelthechambersinthisplace_elementalwaterdungeon", "roll":[
  "Are always flooded up to the ceiling.",
  "Are always flooded in the lower levels.",
  "Are always flooded up to the waist.",
  "Fill with water at high tide.",
  "Fill with water seasonally.",
  "Fill with water at the whim of an elemental lord.",   ]},
   {"title": "d6 Major feature You see a/an...", "id":"d6majorfeatureyouseeaan_elementalwaterdungeon", "roll":[
  "Air pocket.",
  "Altar to a watery god.",
  "Heavy chest.",
  "Rack of harpoons and/or spears.",
  "Skeleton of a drowned mortal.",
  "Teeming reef.",   ]},
   {"title": "d6 Minor feature You see a...", "id":"d6minorfeatureyouseea_elementalwaterdungeon", "roll":[
  "Little stream of bubbles.",
  "Icon of a watery god.",
  "Debris from a broken boat.",
  "School of fish.",
  "Ragged piece of cloth.",
  "Pocket of cool water.",   ]},
   {"title": "d6 NPC You meet a/an…", "id":"d6npcyoumeetaan…_elementalwaterdungeon", "roll":[
  "Smuggler’s ghost.",
  "Curious mermaid.",
  "Suspicious sea elf.",
  "Eccentric treasure hunter.",
  "Half-mad elemental cultist.",
  "Reclusive beastshifter (roll on beast table).",   ]},
   {"title": "d6 Beast You meet a/an…", "id":"d6beastyoumeetaan…_elementalwaterdungeon", "roll":[
  "Dolphin.",
  "Giant clam.",
  "Lobster.",
  "Octopus.",
  "Seal.",
  "Shark.",   ]},
   {"title": "d6 Secondary monster You come upon a/an…", "id":"d6secondarymonsteryoucomeuponaan…_elementalwaterdungeon", "roll":[
  "Aberrant sea beast (roll on beast table).",
  "Swarm of crabs or carnivorous fish.",
  "Kuo-toa.",
  "Sahuagin.",
  "Sea hag.",
  "Water elemental.",   ]},
   {"title": "d6 Primary monster This place is currently ruled by a…", "id":"d6primarymonsterthisplaceiscurrentlyruledbya…_elementalwaterdungeon", "roll":[
  "Aboleth.",
  "Blue dragon.",
  "Kraken.",
  "Maridan prince.",
  "Storm giant.",
  "Storm sorcerer.",   ]},
   {"title": "d6 Traps/hazard You must survive the…", "id":"d6trapshazardyoumustsurvivethe…_elementalwaterdungeon", "roll":[
  "Electric eels.",
  "Poisonous jellyfish.",
  "Poisoned dart trap.",
  "Flooding airlock trap.",
  "Swirling currents.",
  "Curse of rotting death.",   ]},
   {"title": "d6 Reward/treasure If you survive, you may find...", "id":"d6rewardtreasureifyousurviveyoumayfind_elementalwaterdungeon", "roll":[
  "Pirate captain’s hoard.",
  "Staff of elemental power.",
  "Ancient weapon forged of coral.",
  "Legendary gemstone lost at sea.",
  "Key to opening a portal to another realm.",
  "Captive mermaid princess.",   ]},
  

  {"title": "d6 This place is a...", "id":"d6thisplaceisa_elementalfiredungeon", "roll":[
 "Volcanic mountain.",
 "Series of geothermal vents deep underground.",
 "Stronghold built by beings of flame.",
 "Temple dedicated to a fiery god.",
 "Palace built by a fire elemental lord.",
 "Enormous forge or armory gone wrong.",   ]},
  {"title": "d6 Air quality The air in the chambers in here is…", "id":"d6airqualitytheairinthechambersinhereis…_elementalfiredungeon", "roll":[
 "Filled with choking ash.",
 "Filled with hot ash.",
 "Filled with choking smoke.",
 "Filled with dark smoke.",
 "Uncomfortably hot.",
 "Filled with poisonous gas.",   ]},
  {"title": "d6 Major feature You see a/an...", "id":"d6majorfeatureyouseeaan_elementalfiredungeon", "roll":[
 "Over-sized brazier.",
 "Large iron sculpture.",
 "Altar to a fiery god.",
 "Rack of iron spears or steel scimitars.",
 "Charred skeleton of a mortal.",
 "Fountain of smoke and flame.",   ]},
  {"title": "d6 Minor feature You notice a/an...", "id":"d6minorfeatureyounoticeaan_elementalfiredungeon", "roll":[
 "Wisp of smoke.",
 "Scent of brimstone.",
 "Icon of a fiery god.",
 "Charred wooden object.",
 "Scorch marks on the wall.",
 "Iron wall sconce with a torch.",   ]},
  {"title": "d6 NPC You meet a/an…", "id":"d6npcyoumeetaan…_elementalfiredungeon", "roll":[
 "Half-mad elemental cultist.",
 "Escaped mortal slave.",
 "Intrepid dwarvish prospector.",
 "Wayward warlock.",
 "Hermetic monk.",
 "Half-fiend scholar.",   ]},
  {"title": "d6 Beast You meet a…", "id":"d6beastyoumeeta…_elementalfiredungeon", "roll":[
 "Fire bat.",
 "Swarm of fire beetles.",
 "Flame drake.",
 "Fiendish hyena.",
 "Flame snake.",
 "Fiendish stirge.",   ]},
  {"title": "d6 Secondary monster You come upon a/an…", "id":"d6secondarymonsteryoucomeuponaan…_elementalfiredungeon", "roll":[
 "Azer.",
 "Gnoll.",
 "Fire elemental.",
 "Hell hound.",
 "Salamander.",
 "Flaming skeleton.",   ]},
  {"title": "d6 Primary monster This place is currently ruled by a/an…", "id":"d6primarymonsterthisplaceiscurrentlyruledbyaan…_elementalfiredungeon", "roll":[
 "Scheming devil.",
 "Efreet prince.",
 "Fire demon.",
 "Fire giant.",
 "Evil pyromancer.",
 "Red dragon.",   ]},
  {"title": "d6 Traps/hazard You must survive the…", "id":"d6trapshazardyoumustsurvivethe…_elementalfiredungeon", "roll":[
 "Sealing chamber that fills with poisonous gas.",
 "Sudden and sporadic walls of flame.",
 "Collapsing ceiling.",
 "Explosive bursts of fire and rock.",
 "False-floor pit trap.",
 "Whirling blades trap.",   ]},
  {"title": "d6 Reward/treasure If you survive, you may find a/an...", "id":"d6rewardtreasureifyousurviveyoumayfindaan_elementalfiredungeon", "roll":[
 "Notorious bandit’s treasure hoard.",
 "Wand of elemental power.",
 "Ancient weapon forged of fire and steel.",
 "Crystal that offers glimpses of the future.",
 "Genie bound to a lamp.",
 "Captive phoenix.",   ]},


  {"title": "d6 This place is a...", "id":"d6thisplaceisa_elementalearthdungeon", "roll":[
 "Palace built by an earth elemental lord.",
 "Temple dedicated to an earth god.",
 "Stronghold built by beings of elemental earth.",
 "Series of unstable tunnels deep below ground.",
 "Labyrinth of solid rock.",
 "Mining operation gone wrong.",   ]},
  {"title": "d6 Floor/terrain You frequently step on...", "id":"d6floorterrainyoufrequentlystepon_elementalearthdungeon", "roll":[
 "Slippery dust.",
 "Boot-sucking mud.",
 "Loose rubble.",
 "Smooth gravel.",
 "Jagged rocks.",
 "Sharp metal spikes.",   ]},
  {"title": "d6 Major feature You see a/an...", "id":"d6majorfeatureyouseeaan_elementalearthdungeon", "roll":[
 "Stone monolith.",
 "Altar to an earth god",
 "Statue of a figure made of stone or iron.",
 "Natural bridge of stone.",
 "Series of stone columns.",
 "Deep chasm.",   ]},
  {"title": "d6 Minor feature You notice a/an...", "id":"d6minorfeatureyounoticeaan_elementalearthdungeon", "roll":[
 "Small stone statue.",
 "Icon of an earth god.",
 "Stalactite.",
 "Brief tremor.",
 "Distant rumbling sound.",
 "Swirl of dust.",   ]},
  {"title": "d6 NPC You meet a/an…", "id":"d6npcyoumeetaan…_elementalearthdungeon", "roll":[
 "Ghost of an unlucky treasure hunter.",
 "Half-mad elemental cultist.",
 "Dwarvish prospector.",
 "Brooding monk.",
 "Dark elf wanderer.",
 "Inventor of a digging contraption.",   ]},
  {"title": "d6 Beast You meet a/an…", "id":"d6beastyoumeetaan…_elementalearthdungeon", "roll":[
 "Giant mole.",
 "Swarm of rats.",
 "Giant centipede.",
 "Giant ant.",
 "Giant earthworm.",
 "Sludgy ooze.",   ]},
  {"title": "d6 Secondary Monster You come upon a/an…", "id":"d6secondarymonsteryoucomeuponaan…_elementalearthdungeon", "roll":[
 "Earth elemental.",
 "Rust monster.",
 "Xorn.",
 "Galeb duhr.",
 "Zombie.",
 "Otyugh.",   ]},
  {"title": "d6 Primary monster This place is currently ruled by a/an…", "id":"d6primarymonsterthisplaceiscurrentlyruledbyaan…_elementalearthdungeon", "roll":[
 "Dao prince.",
 "Stone giant.",
 "Ancient dragon.",
 "Powerful geomancer.",
 "Lich.",
 "Grick alpha.",   ]},
  {"title": "d6 Traps/hazard You must survive the…", "id":"d6trapshazardyoumustsurvivethe…_elementalearthdungeon", "roll":[
 "Pits of stinking mud.",
 "Crushing walls trap.",
 "Kissing maidens trap.",
 "Spears-from-the-floor trap.",
 "Crumbling bridges and arches.",
 "Collapsing ceilings.",   ]},
  {"title": "d6 Reward/treasure If you survive, you may find a/an...", "id":"d6rewardtreasureifyousurviveyoumayfindaan_elementalearthdungeon", "roll":[
 "Notorious necromancer’s spellbook.",
 "Orb of elemental power.",
 "Storied vein of precious ore (gold, platinum, adamantine, or mithral).",
 "Diamond of dwarvish legend.",
 "Hammer wielded by a godlike warrior.",
 "Captive demon.",   ]},


 {"title": "d6 This place is a...", "id":"d6thisplaceisa_elementalairdungeon", "roll":[
"Palace built by an air elemental lord.",
"Series of caves in a floating earth mote.",
"Series of deep tunnels with constant, howling wind.",
"Stronghold built by beings of elemental air.",
"Temple dedicated to a wind god.",
"Maze of semi-solid clouds.",   ]},
 {"title": "d6 Ambient sounds You hear a/an...", "id":"d6ambientsoundsyouhearaan_elementalairdungeon", "roll":[
"Constant howl of wind.",
"Constant rush of air.",
"Constant monotone whistling.",
"Eerie, shifting succession of musical chords.",
"Intermittent clap of thunder.",
"Flute playing somewhere.",   ]},
 {"title": "d6 Major feature You see a/an...", "id":"d6majorfeatureyouseeaan_elementalairdungeon", "roll":[
"Intersection with swiftly shifting winds.",
"Large cloud sculpture.",
"Shimmering, eerie fog.",
"Barrel of feathered arrows.",
"Altar to a wind god.",
"Tremendous beanstalk or staircase descending far below where you stand.",   ]},
 {"title": "d6 Minor feature You notice a/an...", "id":"d6minorfeatureyounoticeaan_elementalairdungeon", "roll":[
"Small cloud shaped like an animal.",
"Floating lamp.",
"Icon of a wind god.",
"Rush of cool air.",
"Sudden shrill whistle in the distance.",
"Swirl of dust.",   ]},
 {"title": "d6 NPC You meet a/an…", "id":"d6npcyoumeetaan…_elementalairdungeon", "roll":[
"Ghost of an unfortunate explorer.",
"Half-mad elemental cultist.",
"Nervous beastshifter (roll on beast table).",
"Contemplative monk.",
"Interplanar traveler.",
"Inventor with a flying contraption.",   ]},
 {"title": "d6 Beast You meet a/an…", "id":"d6beastyoumeetaan…_elementalairdungeon", "roll":[
"Raven.",
"Bat.",
"Hawk.",
"Giant bee.",
"Pterodactyl.",
"Swarm of moths.",   ]},
 {"title": "d6 Secondary Monster You come upon a/an…", "id":"d6secondarymonsteryoucomeuponaan…_elementalairdungeon", "roll":[
"Air elemental.",
"Arrowhawk.",
"Invisible stalker.",
"Wyvern.",
"Spectre.",
"Roc.",   ]},
 {"title": "d6 Primary monster This place is currently ruled by a/an…", "id":"d6primarymonsterthisplaceiscurrentlyruledbyaan…_elementalairdungeon", "roll":[
"Djinn prince.",
"Cloud giant.",
"Giant eagle.",
"Evil entropomancer.",
"Beholder.",
"Wraith.",   ]},
 {"title": "d6 Traps/hazard You must survive the…", "id":"d6trapshazardyoumustsurvivethe…_elementalairdungeon", "roll":[
"Trap door to a tremendous fall.",
"Poisoned dart trap.",
"Magic crossbow turret trap.",
"Runes that explode in bursts of lightning.",
"Sealing chamber that turns into a vacuum.",
"Curse of listlessness.",   ]},
 {"title": "d6 Reward/treasure If you survive, you may find a/an...", "id":"d6rewardtreasureifyousurviveyoumayfindaan_elementalairdungeon", "roll":[
"Infamous giant’s treasure hoard.",
"Wreck of a legendary airship.",
"Rod of elemental power.",
"Bow that belonged to an ancient hero.",
"Powerful wizard’s lost spellbook.",
"Imprisoned dragon.",   ]},


 {"title": "d20 Air Currents", "id":"d20aircurrents_randomdugeonfeatures", "roll":[
"breeze, slight, damp.",
"breeze, gusting.",
"cold current.",
"downdraft, slight.",
"downdraft, strong.",
"still.",
"still.",
"still.",
"still.",
"still.",
"still.",
"still.",
"still, very chill.",
"still, warm (or hot).",
"updraft, slight.",
"updraft, strong.",
"wind, strong.",
"wind, strong, gusting.",
"wind, strong, moaning.",   ]},
 {"title": "d20 Odors", "id":"d20odors_randomdugeonfeatures", "roll":[
"chlorine smell.",
"dank, moldy smell.",
"dank, moldy smell.",
"dank, moldy smell.",
"dank, moldy smell.",
"dank, moldy smell.",
"dank, moldy smell.",
"earthy smell.",
"manure smell.",
"metallic smell.",
"ozone smell.",
"putrid smell.",
"rotting vegetation smell.",
"salty, wet smell.",
"smoky smell.",
"stale, fetid smell.",
"sulphurous smell.",
"urine smell.",
"dank, moldy smell.",   ]},
 {"title": "d10 Air", "id":"d10air_randomdugeonfeatures", "roll":[
"clear.",
"clear.",
"clear.",
"clear.",
"clear.",
"foggy (or steamy).",
"foggy near floor (or steamy).",
"hazy (dust).",
"misted.",   ]},
 {"title": "d100 General features", "id":"d100generalfeatures_randomdugeonfeatures", "roll":[
"ashes.",
"ashes.",
"ashes.",
"bones.",
"bones.",
"bottle, broken.",
"chain, corroded.",
"club, splintered.",
"cobwebs.",
"cobwebs.",
"cobwebs.",
"cobwebs.",
"cobwebs.",
"cobwebs.",
"cobwebs.",
"cobwebs.",
"cobwebs.",
"cobwebs.",
"coin, copper (bent).",
"cracks, ceiling.",
"cracks, ceiling.",
"cracks, floor.",
"cracks, floor.",
"cracks, wall.",
"cracks, wall.",
"dagger hilt.",
"dampness, ceiling.",
"dampness, ceiling.",
"dampness, wall.",
"dampness, wall.",
"dampness, wall.",
"dampness, wall.",
"dripping.",
"dripping.",
"dripping.",
"dripping.",
"dripping.",
"dripping.",
"dripping.",
"dried blood.",
"dung.",
"dung.",
"dung.",
"dust.",
"dust.",
"dust.",
"dust.",
"dust.",
"flask, cracked.",
"food scraps.",
"fungi, common.",
"guano.",
"guano.",
"guano.",
"hair/fur bits.",
"hammer head, cracked.",
"helmet, badly dented.",
"iron bar, bent, rusted.",
"javelin head, blunt.",
"leather boot.",
"leaves (dry) & twigs.",
"leaves (dry) & twigs.",
"leaves (dry) & twigs.",
"mold (common).",
"mold (common).",
"mold (common).",
"mold (common).",
"pick handle.",
"pole, broken.",
"pottery shards.",
"rags.",
"rags.",
"rope, rotten.",
"rubble & dirt.",
"rubble & dirt.",
"sack, torn.",
"slimy coating, ceiling.",
"slimy coating, floor.",
"slimy coating, wall.",
"spike, rusted.",
"sticks.",
"sticks.",
"stones, small.",
"straw.",
"sword blade, broken.",
"teeth/fangs, scattered.",
"torch stub.",
"torch stub.",
"wall scratchings.",
"wall scratchings.",
"water, small puddle.",
"water, small puddle.",
"water, large puddle.",
"water, large puddle.",
"water, trickle.",
"wax blob (candle stub).",
"wood pieces, rotting.",
"wood pieces, rotting.",
"wood pieces, rotting.",   ]},
 {"title": "d100 Unexplained Sounds and Strange Noises", "id":"d100unexplainedsoundsandstrangenoises_randomdugeonfeatures", "roll":[
"bang, slam.",
"bang, slam.",
"bang, slam.",
"bang, slam.",
"bellow(ing).",
"bong.",
"buzzing.",
"chanting.",
"chanting.",
"chiming.",
"chirping.",
"clanking.",
"clashing.",
"clicking.",
"coughing.",
"creaking.",
"creaking.",
"drumming.",
"footsteps (ahead).",
"footsteps (ahead).",
"footsteps (ahead).",
"footsteps (ahead).",
"footsteps (approaching).",
"footsteps (approaching).",
"footsteps (approaching).",
"footsteps (behind).",
"footsteps (behind).",
"footsteps (behind).",
"footsteps (receding).",
"footsteps (receding).",
"footsteps (side).",
"footsteps (side).",
"giggling (faint).",
"giggling (faint).",
"gong.",
"grating.",
"grating.",
"grating.",
"groaning.",
"groaning.",
"grunting.",
"hissing.",
"hissing.",
"hooting.",
"horn/trumpet sounding.",
"howling.",
"humming.",
"jingling.",
"knocking.",
"knocking.",
"knocking.",
"knocking.",
"laughter.",
"laughter.",
"moaning.",
"moaning.",
"murmuring.",
"murmuring.",
"murmuring.",
"music.",
"rattling.",
"ringing.",
"roar(ing).",
"rustling.",
"rustling.",
"rustling.",
"rustling.",
"scratching/scrabbling.",
"scratching/scrabbling.",
"scratching/scrabbling.",
"scratching/scrabbling.",
"scream(ing).",
"scream(ing).",
"scuttling.",
"scuttling.",
"scuttling.",
"shuffling.",
"slithering.",
"slithering.",
"snapping.",
"sneezing.",
"sobbing.",
"splashing.",
"splintering.",
"squeaking.",
"squeaking.",
"squealing.",
"tapping.",
"tapping.",
"thud.",
"thud.",
"thumping.",
"thumping.",
"tinkling.",
"twanging.",
"whining.",
"whispering.",
"whistling.",
"whistling.",   ]},
 {"title": "d100 Furnishing and Appointments, General", "id":"d100furnishingandappointmentsgeneral_randomdugeonfeatures", "roll":[
"armchair.",
"armoire.",
"arrows.",
"bag.",
"barrel.",
"bed.",
"bed.",
"bench.",
"blanket.",
"box (large).",
"brazier & charcoal.",
"bucket.",
"buffet.",
"bunks.",
"butt (large barrel).",
"cabinet.",
"candelabrum.",
"carpet (large).",
"cask.",
"chandelier.",
"charcoal.",
"chair.",
"chair.",
"chair, padded.",
"chair, padded, arm.",
"chest, large.",
"chest, medium.",
"chest of drawers.",
"closet (wardrobe).",
"coal.",
"couch.",
"couch.",
"crate.",
"cresset.",
"cupboard.",
"cushion.",
"desk.",
"desk.",
"fireplace & wood.",
"fireplace & wood.",
"fireplace & wood.",
"fireplace with mantle.",
"firkin.",
"fountain.",
"fresco.",
"grindstone.",
"hamper.",
"hassock.",
"hogshead.",
"idol (large).",
"keg.",
"loom.",
"mat.",
"mattress.",
"pail.",
"painting.",
"pallet.",
"pallet.",
"pallet.",
"pedestal.",
"pegs.",
"pegs.",
"pegs.",
"pillow.",
"pipe (large cask).",
"quilt.",
"rug (small).",
"rug (medium).",
"rug (large).",
"rushes.",
"sack.",
"sconce, wall.",
"screen.",
"sheet.",
"shelf.",
"shelf.",
"shrine.",
"sideboard.",
"sofa.",
"staff, normal.",
"stand.",
"statue.",
"stool, high.",
"stool, normal.",
"table, large.",
"table, long.",
"table, low.",
"table, round.",
"table, small.",
"table, trestle.",
"tapestry.",
"throne.",
"trunk.",
"tub.",
"tun.",
"urn.",
"wall basin and font.",
"wood billets.",
"workbench.",   ]},
 {"title": "d100 Religious Articles and Furnishings", "id":"d100religiousarticlesandfurnishings_randomdugeonfeatures", "roll":[
"altar.",
"altar.",
"altar.",
"altar.",
"bell(s).",
"bell(s).",
"bell(s).",
"brazier(s).",
"brazier(s).",
"brazier(s).",
"candelabra.",
"candles.",
"candles.",
"candlesticks.",
"cassocks.",
"chime(s).",
"cloth (altar).",
"cloth (altar).",
"columns/pillars.",
"columns/pillars.",
"columns/pillars.",
"columns/pillars.",
"curtain/tapestry.",
"drum.",
"font.",
"font.",
"gong.",
"gong.",
"holy/unholy symbol(s).",
"holy/unholy symbol(s).",
"holy/unholy symbol(s).",
"holy/unholy symbol(s).",
"holy/unholy symbol(s).",
"holy/unholy symbol(s).",
"holy/unholy writings.",
"holy/unholy writings.",
"idol(s).",
"idol(s).",
"idol(s).",
"idol(s).",
"idol(s).",
"idol(s).",
"incense burner(s).",
"incense burner(s).",
"incense burner(s).",
"incense burner(s).",
"incense burner(s).",
"kneeling bench.",
"lamp(s).",
"lamp(s).",
"lamp(s).",
"lamp(s).",
"lectern.",
"mosaics.",
"offertory container.",
"offertory container.",
"offertory container.",
"paintings/frescoes.",
"pews.",
"pews.",
"pipes (musical).",
"prayer rug.",
"pulpit.",
"rail.",
"robes.",
"robes.",
"sanctuary.",
"sanctuary.",
"screen.",
"screen.",
"shrine.",
"shrine.",
"shrine.",
"shrine.",
"shrine.",
"side chair(s).",
"stand.",
"stand.",
"statues(s).",
"statues(s).",
"statues(s).",
"throne.",
"thurible.",
"thurible.",
"tripod.",
"tripod.",
"tripod.",
"vestry.",
"vestry.",
"vestments.",
"vestments.",
"vestments.",
"vestments.",
"vestments.",
"vestments.",
"vestments.",
"votive light.",
"votive light.",
"votive light.",   ]},
 {"title": "d100 Torture Chamber Furnishings", "id":"d100torturechamberfurnishings_randomdugeonfeatures", "roll":[
"bastinadoes.",
"bell (huge).",
"bench.",
"bench.",
"bench.",
"boots (iron).",
"boots (iron).",
"boots (iron).",
"boots (iron).",
"branding irons.",
"branding irons.",
"branding irons.",
"branding irons.",
"branding irons.",
"brazier.",
"brazier.",
"brazier.",
"brazier.",
"brazier.",
"cage.",
"cage.",
"chains.",
"chains.",
"chains.",
"chains.",
"chair with straps.",
"clamps.",
"cressets.",
"cressets.",
"cressets.",
"fetters.",
"fire pit.",
"fire pit.",
"fire pit.",
"grill.",
"hooks.",
"hooks.",
"iron maiden.",
"iron maiden.",
"iron maiden.",
"iron maiden.",
"iron maiden.",
"knives.",
"manacles.",
"oubliette.",
"oil (barrel of).",
"oil (barrel of).",
"pillory.",
"pillory.",
"pincers.",
"pincers.",
"pincers.",
"pincers.",
"pliers.",
"pliers.",
"pot (huge).",
"pot (huge).",
"rack.",
"rack.",
"rack.",
"rack.",
"rack.",
"rack.",
"rack.",
"rack.",
"ropes.",
"ropes.",
"stocks.",
"stool.",
"stool.",
"strappado.",
"strappado.",
"strappado.",
"strappado.",
"straw.",
"straw.",
"straw.",
"table.",
"table.",
"thongs.",
"thumb screws.",
"thumb screws.",
"thumb screws.",
"thumb screws.",
"torches.",
"torches.",
"torches.",
"\"U\" rack.",
"\"U\" rack.",
"vice.",
"well.",
"well.",
"wheel.",
"wheel.",
"wheel.",
"whips.",
"whips.",
"whips.",
"whips.",   ]},
 {"title": "d100 Magic-User Furnishings", "id":"d100magic-userfurnishings_randomdugeonfeatures", "roll":[
"alembic.",
"alembic.",
"balance & weights.",
"balance & weights.",
"beaker.",
"beaker.",
"beaker.",
"beaker.",
"bellows.",
"bladder.",
"bottle.",
"bottle.",
"book.",
"book.",
"book.",
"bowl.",
"box.",
"brazier.",
"brazier.",
"brazier.",
"brazier.",
"cage.",
"cauldron.",
"cauldron.",
"candle.",
"candlestick.",
"carafe.",
"chalk.",
"chalk.",
"crucible.",
"cruet.",
"crystal ball.",
"decanter.",
"desk.",
"dish.",
"flask.",
"flask.",
"funnel.",
"furnace.",
"herbs.",
"herbs.",
"herbs.",
"herbs.",
"horn.",
"hourglass.",
"jar.",
"jar.",
"jug.",
"kettle.",
"ladle.",
"lamp.",
"lens (concave, convex, etc...).",
"magic circle.",
"mortar & pestle.",
"pan.",
"parchment.",
"parchment.",
"pentacle.",
"pentagram.",
"phial.",
"pipette.",
"pot.",
"prism.",
"quill.",
"retort.",
"retort.",
"retort.",
"rod, mixing/stirring.",
"scroll.",
"scroll.",
"scroll tube.",
"sheet.",
"skin.",
"skull.",
"spatula.",
"spoon, measuring.",
"stand.",
"stool.",
"stuffed animal.",
"tank (container).",
"tongs.",
"tripod.",
"tube (container).",
"tube (piping).",
"tube (piping).",
"tweezers.",
"vial.",
"vial.",
"vial.",
"waterclock.",
"wire.",
"workbench.",
"workbench.",
"workbench.",
"workbench.",
"workbench.",
"workbench.",
"workbench.",
" workbench.",   ]},
 {"title": "d30 General Description of Container Contents", "id":"d30generaldescriptionofcontainercontents_randomdugeonfeatures", "roll":[
"bark.",
"bone.",
"bone.",
"chunks.",
"cinders.",
"crystals.",
"dust.",
"fibers.",
"fibers.",
"gelatin.",
"globes.",
"grains.",
"greasy.",
"husks.",
"leaves.",
"liquid.",
"lump(s).",
"oily.",
"paste.",
"pellets.",
"powder.",
"semi-liquid.",
"semi-liquid.",
"skin/hide.",
"splinters.",
"stalks.",
"strands.",
"strips.",
"viscous.",   ]},
 {"title": "d100 Miscellaneous Utensils and Personal Items", "id":"d100miscellaneousutensilsandpersonalitems_randomdugeonfeatures", "roll":[
"bandages.",
"basin.",
"basket.",
"basket.",
"beater.",
"book.",
"bottle.",
"bottle.",
"bowl.",
"box (small).",
"brush.",
"brush.",
"candle.",
"candle snuffer.",
"candlestick.",
"cane (walking stick).",
"case.",
"casket (small).",
"chopper.",
"coffer.",
"cologne.",
"comb.",
"cup.",
"decanter.",
"dipper.",
"dish.",
"earspoon.",
"ewer.",
"flagon.",
"flask.",
"food.",
"fork.",
"grater.",
"grinder.",
"hourglass.",
"jack (container).",
"jar.",
"jug.",
"kettle.",
"knife.",
"knucklebones.",
"ladle.",
"lamp/lantern.",
"lamp/lantern.",
"masher.",
"mirror.",
"mug.",
"needle(s).",
"oil, cooking (or fuel).",
"oil fuel.",
"oil, scented.",
"pan.",
"parchment.",
"pitcher.",
"pipe, musical.",
"pipe, smoking.",
"plate.",
"platter.",
"pot.",
"pouch.",
"puff.",
"quill.",
"razor.",
"rope.",
"salve.",
"saucer.",
"scraper.",
"scroll.",
"shaker.",
"sifter.",
"soap.",
"spigot.",
"spoon.",
"stopper.",
"statuette/figurine.",
"strainer.",
"tankard.",
"thongs.",
"thread.",
"tinderbox (with flint & steel).",
"tinderbox (with flint & steel).",
"tinderbox (with flint & steel).",
"tinderbox (with flint & steel).",
"towel.",
"towel.",
"tray.",
"trivet.",
"tureen.",
"twine.",
"twine.",
"unguent.",
"vase.",
"vial.",
"wallet.",
"washcloth.",
"whetstone.",
"wig.",
"wool.",
" yarn.",   ]},
 {"title": "d100 Clothing and Footwear", "id":"d100clothingandfootwear_randomdugeonfeatures", "roll":[
"apron.",
"belt.",
"belt.",
"blouse.",
"boots.",
"boots.",
"boots.",
"buskins.",
"cap.",
"cap.",
"cape.",
"cape.",
"cloak.",
"cloak.",
"cloak.",
"coat.",
"coat.",
"coif.",
"doublet.",
"dress.",
"dress.",
"frock/pinafore.",
"frock/pinafore.",
"gauntlets.",
"gauntlets.",
"girdle.",
"girdle.",
"gloves.",
"gown.",
"gown.",
"hat.",
"hat.",
"hat.",
"habit.",
"hood.",
"hood.",
"hood.",
"hood.",
"hose.",
"hose.",
"jerkin.",
"jerkin.",
"jupon.",
"kerchief.",
"kerchief.",
"kirtle.",
"kirtle.",
"leggings.",
"leggings.",
"linen (drawers).",
"linen (drawers).",
"linen (drawers).",
"linen (drawers).",
"linen (undershirt).",
"linen (undershirt).",
"linen (undershirt).",
"linen (undershirt).",
"mantle.",
"pantaloons.",
"petticoat.",
"petticoat.",
"pouch/purse.",
"pouch/purse.",
"pouch/purse.",
"pouch/purse.",
"robe.",
"robe.",
"robe.",
"robe.",
"sandals.",
"sandals.",
"sandals.",
"sandals.",
"scarf.",
"scarf.",
"shawl.",
"shift.",
"shift.",
"slippers.",
"slippers.",
"slippers.",
"slippers.",
"smock.",
"smock.",
"smock.",
"stockings.",
"stockings.",
"stockings.",
"surcoat.",
"toga.",
"trousers.",
"trousers.",
"trousers.",
"tunic.",
"tunic.",
"veil.",
"vest.",
"wallet.",
" wrapper. ",   ]},




{"title": "d10 The master of this tower is...", "id":"d10themasterofthistoweris_magetower", "roll":[
"An elven sorceress.",
"A terrifying witch.",
"A creepy necromancer.",
"A mystic seer.",
"A long-bearded sage.",
"A half-mad elementalist.",
"A legendary conjurer.",
"A retired explorer.",
"The leader of a cabal of tricky witches.",
"The head of a secret society of wizards.",   ]},
{"title": "d10 The tower's shape is approximately that of...", "id":"d10thetowersshapeisapproximatelythatof_magetower", "roll":[
"A cylinder.",
"A pyramid.",
"A stepped pyramid.",
"A cone.",
"A triangular prism.",
"A rectangular prism.",
"A pentagonal prism.",
"A hexagonal prism.",
"An octagonal prism.",
"An icosahedron.",   ]},
{"title": "d10 The tower is built of...", "id":"d10thetowerisbuiltof_magetower", "roll":[
"Clay bricks.",
"Limestone.",
"Sandstone.",
"Marble.",
"Obsidian.",
"Enchanted wood.",
"Crystal.",
"Bones.",
"Granite.",
"Solid gold.",   ]},
{"title": "d10 The exterior of the tower features...", "id":"d10theexteriorofthetowerfeatures_magetower", "roll":[
"Spider webs.",
"Ooze.",
"Fruit-bearing vines.",
"Thorny vines.",
"Extensive repairs.",
"Ancient hieroglyphs.",
"Arcane runes.",
"Steel plates.",
"Scorch marks.",
"Scratch marks.",   ]},
{"title": "d10 The tower's entrance is guarded by...", "id":"d10thetowersentranceisguardedby_magetower", "roll":[
"An ill-tempered dragon.",
"A watchful golem (d6): 1. bone; 2. chain; 3. clay; 4. flesh; 5. iron; 6. stone.",
"An angry giant (d6): 1. eldritch; 2. fire; 3. frost; 4. shadow; 5. stone; 6. storm.",
"Cruel gargoyles.",
"Terrifying elementals (d6): 1. air; 2. earth; 3. fire; 4. ice; 5. storm; 6. water.",
"Undead minions (d6): 1. ghosts; 2. ghouls; 3. phantom warriors; 4. spectres; 5. wights; 6. zombies.",
"Devious traps.",
"A cunning sphinx.",
"A ferocious, talking beast (d6): 1. bear; 2. griffon; 3. eagle; 4. lion; 5. serpent; 6. wolf.",
"A menacing, tentacled beast.",   ]},
{"title": "d10 The most well-protected room in the tower is...", "id":"d10themostwell-protectedroominthetoweris_magetower", "roll":[
"The mage's laboratory.",
"The mage's library.",
"The mage's bedchamber.",
"The mage's wine cellar.",
"The mage's treasure vault.",
"A chamber specially prepared for divination rituals.",
"A chamber specially prepared for summoning rituals.",
"A chamber specially prepared for magical duels.",
"An inescapable prison.",
"The crypt of someone important to the mage (d6): 1. master; 2. teacher; 3. child; 4. parent; 5. lover; 6. vanquished rival.",   ]},
{"title": "d10 The room is protected by...", "id":"d10theroomisprotectedby_magetower", "roll":[
"A gauntlet of mechanical traps.",
"A series of sophisticated magical traps.",
"An exploding ward.",
"A powerful charm that makes it easy to ignore.",
"A powerful charm that makes it impossible for intruders to open the door.",
"Illusions that make it difficult to find the door.",
"A powerful curse that frightens those who approach the door.",
"A powerful curse that causes pain in those who approach the door.",
"An indefatigable construct.",
"A bound guardian (d6): 1. devil; 2. demon; 3. elemental; 4. enchanted beast; 5. troll; 6. wraith.",   ]},
{"title": "d10 Rumor has it that within the walls of the tower, the mage keeps...", "id":"d10rumorhasitthatwithinthewallsofthetowerthemagekeeps_magetower", "roll":[
"The weapon of a storied hero.",
"The staff of an infamous sorcerer or necromancer.",
"The wand of a famous witch or wizard.",
"The spellbook of a notorious magic-user.",
"The artifacts of an elvish hero.",
"Monstrosities of the mage's own creation.",
"A legendary stone, mirror, or pool used for watching the world from afar.",
"A fabled book of dangerous lore (d6): 1. demonology; 2. curses of undeath; 3. dream travel; 4. love and war; 5. planar portals; 6. vile darkness.",
"An imprisoned being of terrible power (d6): 1. aberration; 2. devil; 3. demon; 4. djinni; 5. efreeti; 6. vampire lord.",
"A captive princess.",   ]},




{"title": "d10 This place is (or was) a...", "id":"d10thisplaceisorwasa_dungeondetails", "roll":[
"A stronghold.",
"A temple.",
"A tomb.",
"A prison.",
"A mine.",
"A lair.",
"A palace.",
"A storage vault.",
"A sewer.",
"A maze.",   ]},
 {"title": "d12 ...built by...", "id":"d12builtby_dungeondetails", "roll":[
"An ancient dwarvish clan.",
"An ancient elf prince.",
"A powerful wizard.",
"A dark sorceress.",
"A foreign empire.",
"An ambitious queen of old.",
"Prosperous merchants.",
"A powerful noble family.",
"Religious zealots.",
"An ancient race of giants.",
"A tyrannical king of old.",
"No one; it's a natural cave.",   ]},
 {"title": "d12 ...and located...", "id":"d12andlocated_dungeondetails", "roll":[
"Beneath a cold mountain.",
"Beneath a fiery mountain.",
"Near a well-traveled mountain pass.",
"Deep within a forest.",
"Deep within a desert.",
"Beside the sea.",
"On an island.",
"Beneath a bustling city.",
"Beneath the ruin of an ancient city.",
"Beneath a well-known castle or monastery.",
"Beneath a the ruin of an old castle or monastery.",
"In a place reachable only by magic.",   ]},
 {"title": "d12 The place is currently occupied by...", "id":"d12theplaceiscurrentlyoccupiedby_dungeondetails", "roll":[
"A dangerous outlaw.",
"An elemental lord.",
"A vampire.",
"A lich.",
"A demon.",
"A devil.",
"An orc warlord.",
"A hobgoblin commander.",
"An aberrant presence.",
"A witch.",
"A giant.",
"A dragon.",   ]},
 {"title": "d12 ...and some...", "id":"d12andsome_dungeondetails", "roll":[
"Thieves.",
"Goblins.",
"Zombies.",
"Skeletons.",
"Bats.",
"Rats.",
"Spiders.",
"Oozes.",
"Kobolds.",
"Cultists.",
"Troglodytes.",
"Ogres.",   ]},
 {"title": "d12 If you survive the...", "id":"d12ifyousurvivethe_dungeondetails", "roll":[
"Gauntlet of mechanical traps.",
"Powerful magical wards.",
"Golem guardians.",
"Elemental guardians.",
"Noxious gas.",
"Toxic mold.",
"Horrible curse.",
"Unstable ceilings.",
"Flooding chambers.",
"Sinkholes.",
"Steam vents and lava flows.",
"Slippery footing.",   ]},
 {"title": "d12 ...you might recover the...", "id":"d12youmightrecoverthe_dungeondetails", "roll":[
"Weapon of a legendary warrior.",
"Wand of a famous witch or wizard.",
"Spellbook of a notorious mage.",
"Treasure stash of a notable pirate.",
"Hoard of an old dragon.",
"Treasury of an ancient dwarvish realm.",
"Artifacts of an elvish hero.",
"Relics of a celebrated priest.",
"Chests of silver carried by a lost ship or caravan.",
"Crown jewels of a long-dead queen.",
"Largest diamond found in this part of the world.",
"Staff of an infamous sorcerer or necromancer.",   ]},



  {"title": "d10 The castle sits...", "id":"d10thecastlesits", "roll":[
  "Atop a mountain.",
  "On a hill overlooking a wide plain.",
  "At the fork of a river.",
  "On a narrow, rocky peninsula.",
  "Above a seaside cliff.",
  "On a hill overlooking a river valley.",
  "On a hill rising out of a swamp.",
  "On a hill overlooking a forest.",
  "Astride a desert oasis or natural spring.",
  "On a ridge overlooking a frozen plain.",
  ]},
  {"title": "d12 The castle was built by...", "id":"d12thecastlewasbuiltby", "roll":[
  "A wise king or queen.",
  "An ambitious lord or lady.",
  "An evil tyrant.",
  "A mighty warrior or warlord.",
  "A retired adventurer.",
  "A celebrated war hero.",
  "An unscrupulous king or queen.",
  "A vain lord or lady.",
  "A powerful witch or wizard.",
  "A beloved sovereign.",
  "A prosperous merchant.",
  "A member of an ancient noble house.",
  ]},
  {"title": "d4 The castle was built...", "id":"d4thecastlewasbuilt", "roll":[
  "In a past age.",
  "Hundreds of years ago.",
  "A few decades ago.",
  "Within the past decade.",
  ]},
  {"title": "d6 Currently, the castle’s condition is...", "id":"d6currentlythecastlesconditionis", "roll":[
  "Perfect; upkeep has been fastidious.",
  "Good; it been well-maintained.",
  "Decent; there are only a few cracks in the walls, but the place can withstand a siege.",
  "Fair; the castle has seen better days.",
  "Poor; the walls and towers are in dire need of repairs.",
  "Decrepit; the place is practically a ruin.",
  ]},
  {"title": "d12 Presently, the castle is occupied by...", "id":"d12presentlythecastleisoccupiedby", "roll":[
  "A member of the royal family.",
  "An ambitious lord or lady.",
  "An evil tyrant.",
  "An elderly lord or lady.",
  "A brash, young lord or lady.",
  "A mercenary company.",
  "A fearsome warlord or retired sell-sword.",
  "A wealthy merchant.",
  "A retired pirate or thief.",
  "A former adventurer.",
  "An absentee noble lord.",
  "The crown, but the king or queen rarely stays here.",
  ]},
  {"title": "d12 The position or territory is worth defending because...", "id":"d12thepositionorterritoryisworthdefendingbecause", "roll":[
  "The surrounding land is excellent for growing crops.",
  "The nearby mines are rich in ores or gems.",
  "The surrounding land is excellent for grazing livestock.",
  "The nearby pass is the easiest way to cross the mountains.",
  "The nearby harbor is important for trade.",
  "The nearby river is important for trade.",
  "The nearby source of freshwater is precious is in this region.",
  "The wild lands beyond are full of threats.",
  "The surrounding lands are part of a long-standing territorial dispute.",
  "The surrounding land is held sacred.",
  "The nearby lands are home to a rare herb, tree, or creature that has magical uses.",
  ]},
  {"title": "d10 The castle’s outer defenses include...", "id":"d10thecastlesouterdefensesinclude", "roll":[
  "Very high stone walls.",
  "Incredibly thick stone walls.",
  "A series of curtain walls and gatehouses.",
  "A treacherous climb to reach the castle walls.",
  "A moat filled with putrescent water.",
  "A moat filled with thick, boot-sucking mud.",
  "A moat filled with sharp spikes.",
  "A moat that is home to one or more dangerous aquatic beasts.",
  "An immense barbican.",
  "A narrow footbridge to reach the postern.",
  ]},
  {"title": "d6 The inner keep’s defenses include...", "id":"d6theinnerkeepsdefensesinclude", "roll":[
  "Hundreds of arrow slits.",
  "One of the world's largest dual-portcullis gates.",
  "A winding climb to reach the entrance.",
  "Several covered parapets with murder holes under which intruders must pass.",
  "A wide courtyard surrounded by flanking towers in the curtain wall.",
  "An unusual or hidden means of entry.",
  ]},
  {"title": "d8 The castle can be held effectively by as few as...", "id":"d8thecastlecanbeheldeffectivelybyasfewas", "roll":[
  "5 soldiers and 20 archers.",
  "20 soldiers, 5 knights, and 20 archers.",
  "50 soldiers, 10 knights, and 40 archers.",
  "20 knights, 20 archers, and 5 warmages.",
  "100 soldiers, 50 archers, and 5 warmages.",
  "100 soldiers, 20 knights, and 50 archers.",
  "200 soldiers, 50 knights, and 100 archers.",
  "200 soldiers, 100 knights, and 200 archers.",
  ]},
  {"title": "d6 In addition to its garrison, the castle can hold foodstores to withstand a three-month siege for up to...", "id":"d6inadditiontoitsgarrisonthecastlecanholdfoodstorestowithstandathreemonthsiegeforupto", "roll":[
  "50 people.",
  "100 people.",
  "200 people.",
  "500 people.",
  "1,000 people.",
  "2,000 people.",
  ]},
  {"title": "d12 The castle is known for...", "id":"d12thecastleisknownfor", "roll":[
  "Withstanding a grueling, lengthy siege.",
  "Suffering an immense conflagration.",
  "Changing hands several times over the course of the same war.",
  "Bringing ill-fortune to those who hold it.",
  "Being haunted by a former occupant.",
  "Never falling in a siege.",
  "Welcoming travelers seeking refuge.",
  "Turning away travelers seeking refuge.",
  "Its unusual architectural style.",
  "Its beautiful, historic tapestries.",
  "Its breathtakingly beautiful chapel.",
  "The quality of its meals.",
  ]},
  {"title": "d12 What is rumored to be hidden in the castle?", "id":"d12whatisrumoredtobehiddeninthecastle", "roll":[
  "An underground tunnel that can serve as a last-gasp escape route.",
  "The weapon of a long-dead hero.",
  "The preserved head of an ancient villain.",
  "A long-lost religious artifact.",
  "A missing lord or lady.",
  "A book of vile curses.",
  "A book of dark and ancient secrets.",
  "A cursed treasure hoard.",
  "The last bottle of famous vintage of wine.",
  "A lost work of a celebrated artist.",
  "The crypt of an ancient sovereign.",
  "An unhatched dragon egg.",
  ]},
  {"title": "d20 Rooms: This chamber is...", "id":"d20roomsthischamberis", "roll":[
  "An antechamber or waiting room.",
  "An armory.",
  "An aviary, dovecote, owlery, or rookery.",
  "A banquet hall.",
  "The barracks.",
  "A bath or privy.",
  "A bedroom (d3): 1. simple; 2. comfortable; 3. luxurious.",
  "A chapel or shrine.",
  "A crypt.",
  "An intimate or informal dining room.",
  "A dressing room.",
  "A gallery (d6): 1. armor and weaponry; 2. paintings; 3. sculptures; 4. tapestries; 5. hunting trophies; 6. trophies of war.",
  "A guardroom.",
  "A kennel, menagerie, or stable.",
  "The kitchen.",
  "A library or study.",
  "A pantry.",
  "Store room for mundane supplies or a cistern for drinking water.",
  "The throne room.",
  "A treasure vault (likely hidden and/or protected by traps).",
  ]},
  {"title": "d20 Features: You notice...", "id":"castled20featuresyounotice", "roll":[
  "An armchair flanked by two sconces.",
  "A large armoire or buffet cabinet.",
  "A bench with a cushion.",
  "A brazier.",
  "A candelabrum on a large table.",
  "A plain chair beside a window.",
  "A heavy wooden chest.",
  "A chest of drawers with a blanket on top.",
  "A desk with some quills and parchment.",
  "A fireplace with a mantle.",
  "A fireplace with a small pile of wood.",
  "A fresco with a padded chair beneath it.",
  "Portrait of a noble.",
  "A painting of a landscape or seascape.",
  "A bust on a pedestal.",
  "A shelf containing books or knick knacks.",
  "A low table in front of a small sofa.",
  "A large table beneath a chandelier.",
  "An ornate tapestry.",
  "A small wall basin and font.",
  ]},
  {"title": "d10 Under siege: You come upon...", "id":"d10undersiegeyoucomeupon", "roll":[
  "A squad of archers hustling up a stair.",
  "A patrol of guards brandishing weapons.",
  "A guard shouting instructions.",
  "A knight hurrying to the stables.",
  "A servant cowering in a hiding place.",
  "A curious child peaking out a window.",
  "A servant kneeling in prayer.",
  "A noble hastily penning a letter.",
  "A squire aiding a knight with his armor.",
  "A healer checking over his potions.",
  ]},
  {"title": "d10 In peace: You come upon...", "id":"d10inpeaceyoucomeupon", "roll":[
  "The huntsman cleaning a recent kill.",
  "The kennel master leading a leashed dog.",
  "The horse master instructing a young rider.",
  "The armorer scolding an apprentice.",
  "A maid fussing over her lady’s dress.",
  "The tutor or sage lost in a book.",
  "The chaplain whispering with a maid.",
  "A maid polishing an ornamental shield.",
  "A servant carrying a tray of food.",
  "Several archers practicing in the yard.",
  ]},
  {"title": "d6 The dungeon is located...", "id":"d6thedungeonislocated", "roll":[
  "In a tower set apart from the main castle.",
  "Beneath the keep.",
  "In a flanking tower of the castle.",
  "Beneath flanking tower in the castle.",
  "In a corner tower of the castle.",
  "Beneath the corner tower.",
  ]},
  {"title": "d4 The dungeon was built...", "id":"d4thedungeonwasbuilt", "roll":[
  "As part of the original castle.",
  "As a later addition.",
  "For another purpose originally.",
  "Long before most of the castle.",
  ]},
  {"title": "d8 The dungeon is...", "id":"d8thedungeonis", "roll":[
  "A sprawling maze of twisting passages.",
  "A sprawling maze of narrow passages.",
  "Organized into small, neat rows of cells or pits.",
  "Organized around a large central cell block or pit.",
  "Only a few rooms.",
  "An endless series of long corridors.",
  "An endless series of small rooms and staircases.",
  "A series of corridors with very low ceilings.",
  ]},
  {"title": "d10 Prisoners are held within...", "id":"d10prisonersareheldwithin", "roll":[
  "Individual cells, in complete isolation.",
  "Individual cells, but they can see and hear other prisoners.",
  "Individual cells, but they can hear other prisoners.",
  "Cells that accommodate up to two prisoners.",
  "Cells that accommodate up to two prisoners, each shackled to the wall.",
  "Cells that accommodate up to four prisoners.",
  "Cells that accommodate up to four prisoners, each shackled to the wall.",
  "A large chamber with many other prisoners, each shackled to the wall.",
  "Individual pits or wells, open at the top.",
  "One or more huge pit with many other prisoners.",
  ]},
  {"title": "d4 The cells’ (or pits’) condition is...", "id":"d4thecellsorpitsconditionis", "roll":[
  "Well-maintained; the walls are solid.",
  "Aging, but sturdy; the walls have some cracks.",
  "Decrepit; the walls are crumbling.",
  "So dark it’s difficult to say.",
  ]},
  {"title": "d4 Prisoners are treated...", "id":"d4prisonersaretreated", "roll":[
  "Humanely; they receive reasonable meals, some exercise, and healing when needed.",
  "Like dogs; they receive poor quality meals and enough healing to keep them alive.",
  "Like rats; they receive terrible meals and are plagued by sickness.",
  "Like they don’t exist; occasionally they receive food.",
  ]},
  {"title": "d10 The dungeon is known for...", "id":"d10thedungeonisknownfor", "roll":[
  "Many prisoners dying in a terrible plague.",
  "A mass escape in the past.",
  "The escape of a famous criminal.",
  "Being the final home of a famous criminal.",
  "Being the final home of a legendary hero.",
  "Being haunted by vengeful ghosts.",
  "Its horrific torture pits.",
  "Never suffering a successful escape.",
  "Its quirky jailer.",
  "The quality of its meals.",
  ]},
  {"title": "d8 According to rumor, within the castle’s dungeon lies...", "id":"d8accordingtorumorwithinthecastlesdungeonlies", "roll":[
  "A secret tunnel to the outside.",
  "The bones of a long-lost hero.",
  "The preserved head of an ancient villain.",
  "A terrible beast to which prisoners are fed.",
  "A missing lord or lady.",
  "A famous jewel by a notorious prisoner.",
  "A unique and terrible torture device.",
  "The bones of a deposed king or queen.",
  ]},
  {"title": "d10 Rooms: This chamber is...", "id":"castledungeond10roomsthischamberis", "roll":[
  "A dungeon cell.",
  "Another dungeon cell.",
  "A passageway connecting cell blocks.",
  "A guardroom.",
  "The barracks.",
  "The jailer’s quarters.",
  "A yard or large indoor space for exercise.",
  "A small dining room.",
  "An interrogation room.",
  "A torture chamber.",
  ]},
  {"title": "d20 Features: You notice...", "id":"castledungeond20featuresyounotice", "roll":[
  "A wooden door reinforced with steel bands.",
  "Steel bars where you expected a stone wall.",
  "Empty manacles along the wall.",
  "An empty sconce to hold a torch.",
  "Distant torchlight.",
  "The floor is uneven.",
  "A crack in the stone floor.",
  "A mouse skittering underfoot.",
  "The stench of rotting flesh.",
  "The scent of stale urine.",
  "A putrid smell.",
  "A dank and moldy odor.",
  "An uncomfortable groaning.",
  "A faint scratching sound.",
  "An odd tapping sound.",
  "The squeaking of rats.",
  "The shouting of distant voices.",
  "Howls of agony.",
  "Horrific screams.",
  "The clanking of chains.",
  ]},
  {"title": "d12 Escape Encounters: You come upon...", "id":"d12escapeencountersyoucomeupon", "roll":[
  "A snoozing guard or jailer.",
  "A pair of guards on patrol.",
  "A quartet of guards playing cards or dice on their break.",
  "A pack of trained hunting dogs commanded by a high-ranking guard who has been alerted of the escape attempt.",
  "An inquisitor on-site to interrogate another prisoner about an unrelated case.",
  "An ear-splitting shriek from a maidservant.",
  "A wide, well-lit yard that must be crossed with guards watching it from towers.",
  "A high wall directly in the path of escape.",
  "A barred window in the path of escape.",
  "The rat-infested kitchens.",
  "An imprisoned nobleman who offers to help if you help him escape.",
  "An imprisoned thief who is bent on revenge.",
  ]},
  {"title": "d10 Entrance: The cave mouth is...", "id":"d10entrancethecavemouthis", "roll":[
  "Wide and tall, letting much daylight into the entry chamber.",
  "A wide sinkhole.",
  "An easy to spot, narrow passage.",
  "A steep, slippery sloped tunnel.",
  "A man-made tunnel.",
  "A collapsed tunnel, impassable without excavation.",
  "Marked with several warning signs.",
  "Hidden by the terrain (d4): 1. some boulders; 2. a waterfall; 3. a rocky overhang; 4. a hillock.",
  "Hidden by vegetation (d4): 1. a briar patch; 2. a curtain of moss; 3. enormous tree roots; 4. overgrown vines.",
  "Difficult to access (d4): 1. up or down a cliff face; 2. down a deep hole. 3. in an underwater tunnel. 4. through an illusory rock or wall.",
  ]},
  {"title": "d50 Denizens: What lives in the cave?", "id":"d50denizenswhatlivesinthecave", "roll":[
  "Bullywug.",
  "Carrion crawler.",
  "Chuul.",
  "Cloaker.",
  "Crawling claw.",
  "Cyclops.",
  "Darkmantle.",
  "Shadow dragon.",
  "Drider.",
  "Duergar.",
  "Elves, dark.",
  "Ettin.",
  "Fomorian.",
  "Fungi.",
  "Galeb duhr.",
  "Gargoyle.",
  "Ghost.",
  "Ghoul.",
  "Giant, hill.",
  "Giant, stone.",
  "Gibbering mouther.",
  "Goblins.",
  "Grell.",
  "Grick.",
  "Grimlock.",
  "Hobgoblins.",
  "Hook Horror.",
  "Kobolds.",
  "Mephits.",
  "Mimic.",
  "Myconids.",
  "Ogres.",
  "Oozes.",
  "Orcs.",
  "Otyugh.",
  "Piercer.",
  "Purple worm.",
  "Roper.",
  "Rust monster.",
  "Shadow.",
  "Skeleton.",
  "Spectre.",
  "Stirge.",
  "Troglodyte.",
  "Troll.",
  "Umber hulk.",
  "Wraith.",
  "Xorn.",
  "Yuan-ti.",
  "Zombies.",
  ]},
  {"title": "d10 Ecology: The creature is...", "id":"d10ecologythecreatureis", "roll":[
  "A predator or a hunter.",
  "A food source for other denizens.",
  "A recently-arrived squatter or invader.",
  "A long-time resident.",
  "A parasite or a scavenger.",
  "A host or the dominant species.",
  "Unusually abundant.",
  "Living in deliberate isolation.",
  "Living in unintentional isolation.",
  "Severely out of place in this cave.",
  ]},
  {"title": "d20 Distinguishing Landmark: You see...", "id":"cavernd20distinguishinglandmarkyousee", "roll":[
  "A trickle of water flowing down the walls and across the floor.",
  "An underground lake of potable water.",
  "A pool of stagnant water.",
  "A natural bridge over a chasm.",
  "A narrow chasm with walls close enough to climb between.",
  "A deep chasm with no bottom in sight.",
  "A shaft in the ceiling with no light coming from it.",
  "A shaft in the ceiling with dim light coming from it.",
  "A group of stalagmites arranged in a circle.",
  "An arrangement of two large stalactites and two large stalagmites, reminiscent of fangs in a yawning mouth.",
  "A pair of natural columns.",
  "A large stalactite that has broken off from the ceiling and fallen to the floor.",
  "An array of many small stalactites spreading across the ceiling.",
  "A damp wall covered in soft mold.",
  "A recess in the wall, covered in slimy mold.",
  "A large patch of glowing fungus.",
  "A large patch of small mushrooms.",
  "A group of enormous mushrooms.",
  "A large cavern with a strong echo.",
  "A claustrophobic tunnel with a low ceiling.",
  ]},
  {"title": "d12 Features: You notice...", "id":"cavernd12featuresyounotice", "roll":[
  "A cache of abandoned, decrepit mining equipment.",
  "Some old dry bones.",
  "Many bones underfoot.",
  "Evidence of a recent encampment.",
  "An enormous spider web.",
  "A wide slippery patch of mold on the floor.",
  "The clatter of rocks falling.",
  "Loose stones underfoot.",
  "An unstable ceiling.",
  "A distant sound—a scream, hammers at work, footsteps, or drums.",
  "The name of a previous traveler carved into a wall.",
  "Several ancient runes carved into the wall.",
  ]},
  {"title": "d12 The cave wall is...", "id":"d12thecavewallis", "roll":[
  "Slightly damp.",
  "Dripping wet.",
  "Slick with mold.",
  "Covered in soft fungi.",
  "Dry as a bone.",
  "Rough and dry.",
  "Dry and smooth.",
  "Jagged.",
  "Pockmarked.",
  "Crumbling, with loose bits flaking off.",
  "Crumbling, with large chunks falling off at a touch.",
  "Covered in an unidentifiable slime.",
  ]},
  {"title": "d6 The cave ceiling is...", "id":"d6thecaveceilingis", "roll":[
  "Uncomfortably close to your head.",
  "Covered in stalactites (watch your head!).",
  "Smooth as glass.",
  "Rough and jagged.",
  "Connected to the floor by natural columns.",
  "So high it’s difficult to see.",
  ]},
  {"title": "d6 Hazards/Obstacles: You find...", "id":"d6hazardsobstaclesyoufind", "roll":[
  "A colony of poisonous mushrooms.",
  "A patch of toxic mold.",
  "The ceiling caves in.",
  "Several rocks tumble down a sloped wall.",
  "The floor is very slippery.",
  "Your foot misses the floor as you step into a pit or chasm.",
  ]},
  {"title": "d12 Travelers/Visitors: You come upon...", "id":"d12travelersvisitorsyoucomeupon", "roll":[
  "An explorer (d4): 1. duergar; 2. goblin; 3. human; 4. kobold.",
  "An escaped slave (d6): 1. dwarf; 2. goblin; 3. gnome; 4. halfling; 5. human; 6. kobold.",
  "A forager (d4): 1. duergar; 2. goblin; 3. kobold; 4. orc.",
  "A fugitive criminal (d4): 1. heretic; 2. killer; 3. smuggler; 4. thief.",
  "A lost treasure hunter (d4): 1. dwarf; 2. half-elf; 3. high elf; 4. human.",
  "A mapmaker (d4): 1. dwarf; 2. goblin; 3. gnome; 4. svirfneblin.",
  "A messenger (d4): 1. dark elf; 2. goblin; 3. gnome; 4. svirfneblin.",
  "A miner (d6): 1. dwarf; 2. gnome; 3. goblin; 4. human; 5. kobold; 6. svirfneblin.",
  "A prospector (d4): 1. dwarf; 2. gnome; 3. human; 4. svirfneblin.",
  "A scout (d4): 1. dark elf; 2. goblin; 3. kobold; 4. orc.",
  "A soldier (d6): 1. dark elf; 2. duergar; 3. dwarf; 4. goblin; 5. kobold; 6. orc.",
  "A spy (d4): 1. dark elf; 2. duergar; 3. goblin; 4. kobold.",
  ]},
  {"title": "d20 The mine is a source of...", "id":"d20themineisasourceof", "roll":[
  "Chalk.",
  "Coal.",
  "Copper.",
  "Gold.",
  "Iron.",
  "Lead.",
  "Lime.",
  "Nickel.",
  "Platinum.",
  "Salt.",
  "Silver.",
  "Zinc.",
  "Diamonds.",
  "Emeralds.",
  "Jade.",
  "Rubies.",
  "Sapphires.",
  "Turquoise.",
  "Other gems (d6): 1. amethyst; 2. aquamarine; 3. garnet; 4. opal; 5. peridot; 6. tanzanite; 7. topaz, 8. zirconium.",
  "An especially rare metal (d3): 1. adamantine; 2. mithral; 3. orium.",
  ]},
  {"title": "d12 Entrance: The mine’s entrance is...", "id":"d12entrancetheminesentranceis", "roll":[
  "Up a winding trail from a camp or village.",
  "Up a steep trail from a camp or village.",
  "A wide, natural cave mouth.",
  "A wide open pit.",
  "An easy to spot, narrow passage.",
  "A steep, slippery sloped tunnel.",
  "A tunnel reinforced with wood beams.",
  "A partially collapsed tunnel, impassable without excavation.",
  "Marked with several signs.",
  "Hidden by the terrain (d4): 1. boulders; 2. waterfall; 3. rocky overhang; 4. hillock.",
  "Hidden by vegetation (d4): 1. a briar patch; 2. a curtain of moss; 3. enormous tree roots; 4. overgrown vines.",
  "Difficult to access (d4): 1. up or down a cliff face; 2. down a deep hole; 3. un an underwater tunnel; 4. through an illusory rock or wall.",
  ]},
  {"title": "d6 Most of the mine is...", "id":"d6mostofthemineis", "roll":[
  "A sprawling maze of twisting tunnels.",
  "A sprawling maze of narrow tunnels.",
  "A series of tunnels connecting large natural caverns.",
  "A wide open-pit quarry.",
  "A series of tunnels connecting large open pits or sinkholes.",
  "A sprawling maze of open trenches.",
  ]},
  {"title": "d8 Material excavated from the mine is...", "id":"d8materialexcavatedfromthemineis", "roll":[
  "Floated on rafts down a stream or river.",
  "Hauled out on pack mules.",
  "Hauled out on mule-drawn carts.",
  "Hauled out on sure-footed ponies.",
  "Hauled out on ox-drawn carts.",
  "Hauled out on the backs of uncommon beasts of burden (d4): 1. bears; 2. giant lizards; 3. goats; 4. undead horses.",
  "Rolled out in single mine carts.",
  "Rolled out in long trains of mine carts.",
  ]},
  {"title": "d10 Hazards/Obstacles: You find...", "id":"d10hazardsobstaclesyoufind", "roll":[
  "A colony of poisonous mushrooms.",
  "A patch of toxic mold.",
  "A sudden cave in.",
  "Several rocks tumble down a sloped wall.",
  "The floor is very slippery.",
  "Your foot misses the floor as you step into a pit or chasm.",
  "A heap of unstable explosives.",
  "A sudden explosion in another part of the mine shakes the floor.",
  "The floor is writhing with vermin (d4): 1. beetles; 2. centipedes; 3. rats; 4. spiders.",
  "The tunnel or trench is steadily flooding.",
  ]},
  {"title": "d20 Denizens: If you dig deep, you’ll find...", "id":"d20denizensifyoudigdeepyoullfind", "roll":[
  "Carrion crawler.",
  "Cloaker.",
  "Darkmantle.",
  "Drider.",
  "Fungi.",
  "Gargoyle.",
  "Ghosts.",
  "Gricks.",
  "Hook horror.",
  "Mimics.",
  "Myconids.",
  "Ooze.",
  "Otyugh.",
  "Piercer.",
  "Roper.",
  "Rust monster.",
  "Skeletons.",
  "Stirges.",
  "Umber hulk.",
  "Wraith.",
  ]},
  {"title": "d12 Neighbors: The miners complain of trouble from a nearby colony of...", "id":"d12neighborstheminerscomplainoftroublefromanearbycolonyof", "roll":[
  "Cyclops.",
  "Duergar.",
  "Dwarves.",
  "Elves, dark.",
  "Gnomes, deep.",
  "Goblins.",
  "Grimlocks.",
  "Hobgoblins.",
  "Kobolds.",
  "Orcs.",
  "Troglodytes.",
  "Trolls.",
  ]},
  {"title": "d20 Distinguishing Landmark: You see...", "id":"mined20distinguishinglandmarkyousee", "roll":[
  "A trickle of water flowing down the walls and across the floor.",
  "An underground lake of potable water.",
  "A pool of stagnant water.",
  "A rickety bridge over a chasm.",
  "A narrow chasm with walls close enough to climb between.",
  "A deep chasm with no bottom in sight.",
  "A group of boulders arranged in a circle.",
  "A damp wall covered in soft mold.",
  "A recess in the wall, covered in slimy mold.",
  "A large patch of soft fungus.",
  "A cavern with a strong echo.",
  "A claustrophobic tunnel with a low ceiling.",
  "A forked path with tracks for mine carts.",
  "An overturned mine cart.",
  "An unlit lantern mounted to the wall.",
  "A glowing lantern mounted to the wall.",
  "A swirling vein of ore visible in the wall.",
  "A wide vein of ore visible in the wall.",
  "A partially excavated wall with plentiful ore.",
  "A heap of excavated rock.",
  ]},
  {"title": "d12 Features: You notice...", "id":"mined12featuresyounotice", "roll":[
  "Some broken mining equipment.",
  "Some old dry bones.",
  "Evidence of a recent, brief encampment.",
  "Evidence of an abandoned campsite.",
  "An enormous spider web.",
  "A wide slippery patch of mold on the floor.",
  "The clatter of rocks falling.",
  "Loose stones underfoot.",
  "The clang of a pick breaking rock.",
  "The distant sound of hammers at work.",
  "A prospector’s mark scratched on the wall.",
  "A cracked wooden beam overhead.",
  ]},
  {"title": "d4 The mine is widely believed to be...", "id":"d4themineiswidelybelievedtobe", "roll":[
  "Full of riches.",
  "A productive place to dig.",
  "Becoming increasingly unprofitable.",
  "Nearly dried up.",
  ]},
  {"title": "d8 The mine is controlled by...", "id":"d8themineiscontrolledby", "roll":[
  "A powerful, well-known merchant guild.",
  "A wealthy noble house.",
  "A partnership of a few prospectors.",
  "A clan or collective of locals.",
  "No one in particular; finders keepers.",
  "A shadowy cabal of merchants.",
  "A vicious warlord or mercenary captain.",
  "A crime boss who’s never visited the site.",
  ]},
  {"title": "d6 Most of the miners are...", "id":"d6mostoftheminersare", "roll":[
  "Free men working for wages.",
  "Low-level members of a guild.",
  "Paid with a fraction of what they haul out.",
  "Paid with credit at a merchant’s store.",
  "Prisoners.",
  "Slaves.",
  ]},
  {"title": "d12 Visitors to the monastery come seeking...", "id":"d12visitorstothemonasterycomeseeking", "roll":[
  "Ancient knowledge.",
  "Mystic wisdom.",
  "Spiritual guidance.",
  "Prayers and healing.",
  "Ales and other goods made on-site.",
  "Refuge from war.",
  "Shelter on a long journey.",
  "The secret of true happiness.",
  "Physical perfection.",
  "The means to travel to another realm.",
  "Training in a unique fighting style.",
  "The tools and training to exact vengeance.",
  ]},
  {"title": "d12 The monastery is known for its...", "id":"d12themonasteryisknownforits", "roll":[
  "Compassionate healers.",
  "Sacred music.",
  "Ancient wisdom.",
  "Dark prophecies.",
  "Stunning architecture.",
  "Unusual architecture.",
  "A famous sculpture or painting.",
  "Lengthy prayer services and vigils.",
  "Extensive library and scholarly debates.",
  "Master brewers or vintners.",
  "Powerful mystics.",
  "Indefatigable warriors.",
  ]},
  {"title": "d8 The monastery complex is located...", "id":"d8themonasterycomplexislocated", "roll":[
  "On a hilltop far from any cities, but with a village below.",
  "On a hilltop not far from a large city.",
  "On a remote mountaintop.",
  "On the side of a mountain.",
  "Deep within a forest.",
  "Near a desert oasis.",
  "Below ground.",
  "In the heart of a city.",
  ]},
  {"title": "d10 The monastery complex is...", "id":"d10themonasterycomplexis", "roll":[
  "A tight cluster of buildings (or chambers).",
  "A cluster of buildings with gardens, lawns, and yards in the spaces between.",
  "A cluster of interconnected buildings.",
  "A cluster of buildings ringed by a fence or low wall.",
  "A cluster of buildings ringed by a defensible stone wall.",
  "A single large building.",
  "A large main building with several smaller support buildings located nearby.",
  "A fortress with walls and watchtowers or sentry posts.",
  "A labyrinthine series of small buildings.",
  "Symmetrically divided into two or more wings.",
  ]},
  {"title": "d4 Many of the monastery’s ceilings are...", "id":"d4manyofthemonasterysceilingsare", "roll":[
  "Uncomfortably close to your head.",
  "Connected to the floor by columns.",
  "Painted with mythological scenes.",
  "Domes or cupolas.",
  ]},
  {"title": "d6 The buildings/chambers are...", "id":"d6thebuildingschambersare", "roll":[
  "Decorated with statues.",
  "Decorated with stone arches and columns.",
  "Colorful structures of painted wood and plaster.",
  "Sturdy structures of finished wood.",
  "Solid structures of oven-fired clay bricks.",
  "Behind large metal doors (d6): 1. brass; 2. bronze; 3. gold; 4. iron; 5. steel; 6. tin",
  ]},
  {"title": "d8 Many of the monastery’s interior walls are...", "id":"d8manyofthemonasterysinteriorwallsare", "roll":[
  "Rough hewn stone.",
  "Smooth cut stone.",
  "Painted or lacquered wood.",
  "Unfinished hardwood.",
  "Decorated with intricate mosaics.",
  "Decorated with elaborate murals.",
  "Decorated with relief carvings.",
  "Decorated with sacred texts and runes.",
  ]},
  {"title": "d10 The monastery guards the secret to...", "id":"d10themonasteryguardsthesecretto", "roll":[
  "World peace.",
  "Inner peace.",
  "Spiritual enlightenment.",
  "Total consciousness.",
  "Apotheosis.",
  "Armageddon.",
  "Ritual transformation into a god’s avatar.",
  "Unsealing a portal to another realm.",
  "Instant and irreversible death.",
  "The perfect pint of ale.",
  ]},
  {"title": "d4 The monastery’s secret is known to...", "id":"d4themonasteryssecretisknownto", "roll":[
  "Everyone, but the specifics are hidden.",
  "Monks that perform a particular service.",
  "Several of the monastery’s masters.",
  "A single master and a single student.",
  ]},
  {"title": "d12 This building/chamber is...", "id":"d12thisbuildingchamberis", "roll":[
  "A chapel or shrine.",
  "A dormitory.",
  "A cloister.",
  "A refectory (dining hall).",
  "A library.",
  "A balneary (bath).",
  "An infirmary.",
  "A sanatorium or hospice.",
  "A school.",
  "A forge.",
  "A brewery.",
  "A barn.",
  ]},
  {"title": "d20 Features: You notice...", "id":"monasteryd20featuresyounotice", "roll":[
  "A small altar set in an alcove in the wall.",
  "The sound of bells ringing in a tower.",
  "A wall sconce holding many candles.",
  "Tall candles on holders, taller than a man.",
  "The tinkle of chimes from a nearby room.",
  "A tapestry depicting a mythological scene.",
  "A small fountain or reflecting pool.",
  "The sound of a gong from another room.",
  "A large holy symbol embedded in the wall.",
  "A huge book of sacred texts or prayers.",
  "The scent of incense burning nearby.",
  "A kneeler beneath a small statue or icon.",
  "An oil lamp with colored glass panels.",
  "A mosaic set into the floor of the room.",
  "A wide fresco or mural depicting a mythological scene.",
  "The pipes of an indoor plumbing system running along the wall.",
  "Robes and cassocks hanging on hooks.",
  "An ornamental rug.",
  "The sound of chanting from another room.",
  "A statue of a recognizable figure.",
  ]},
  {"title": "d12 Encounters: You come upon...", "id":"d12encountersyoucomeupon", "roll":[
  "A bright-eyed student.",
  "An exhausted student.",
  "A patient initiate.",
  "A fierce martial artist.",
  "A dogmatic teacher.",
  "An eccentric scholar.",
  "A wise old master.",
  "A traveler from afar.",
  "A member of the monastery’s serving staff.",
  "A member of the monastery’s guard.",
  "A strange energy.",
  "A feeling that you’re being watched.",
  ]},
  {"title": "d12 The prison is located...", "id":"d12theprisonislocated", "roll":[
  "On a small island on a remote coast.",
  "On a small island near a city.",
  "In a tower of a castle.",
  "Beneath a temple complex.",
  "In an annex on a temple complex.",
  "Beneath a town hall.",
  "In an annex on a town hall.",
  "Underneath a city, deep below ground.",
  "Behind walls in a fortified rural location (d4): 1. coastland; 2. farmland; 3. mining country; 4. ranchland.",
  "Below ground, in a hidden rural location (d4): 1. coastland; 2. farmland; 3. mining country; 4. ranchland.",
  "Behind walls in a fortified wilderness location (d6): 1. desert, 2. forest, 3. hills; 4. mountains, 5. swamp; 6. tundra.",
  "Below ground, in a hidden wilderness location (d6): 1. desert, 2. forest, 3. hills; 4. mountains, 5. swamp; 6. tundra.",
  ]},
  {"title": "d8 The prison was built by...", "id":"d8theprisonwasbuiltby", "roll":[
  "A wise king or queen.",
  "An ambitious lord or lady.",
  "An evil tyrant.",
  "A civic committee.",
  "A popular mayor or sheriff.",
  "An unscrupulous king or queen.",
  "A prosperous merchant guild.",
  "A powerful noble house.",
  ]},
  {"title": "d6 The prison complex is...", "id":"d6theprisoncomplexis", "roll":[
  "A sprawling maze of twisting passages.",
  "A sprawling maze of narrow passages.",
  "Organized into small, neat rows of cells or pits.",
  "Organized around a large central cell block or pit.",
  "An endless series of long corridors.",
  "A series of corridors with very low ceilings.",
  ]},
  {"title": "d6 The prison is surrounded by...", "id":"d6theprisonissurroundedby", "roll":[
  "Very high stone walls.",
  "Incredibly thick stone walls.",
  "A curtain wall with many gatehouses.",
  "A moat filled with putrescent water.",
  "A moat filled with thick, boot-sucking mud.",
  "A moat filled with sharp spikes.",
  ]},
  {"title": "d10 Prisoners are held within...", "id":"d10prisonersareheldwithin", "roll":[
  "Individual cells, in complete isolation.",
  "Individual cells, but they can see and hear other prisoners.",
  "Individual cells, but they can hear other prisoners.",
  "Cells that accommodate up to two prisoners.",
  "Cells that accommodate up to two prisoners, each shackled to the wall.",
  "Cells that accommodate up to four prisoners.",
  "Cells that accommodate up to four prisoners, each shackled to the wall.",
  "A large chamber with many other prisoners, each shackled to the wall.",
  "Individual pits or wells, open at the top.",
  "One or more huge pit with many other prisoners.",
  ]},
  {"title": "d4 The cells’ (or pits’) condition is...", "id":"d4thecellsorpitsconditionis", "roll":[
  "Well-maintained; the walls are solid.",
  "Aging, but sturdy; the walls have some cracks.",
  "Decrepit; the walls are crumbling.",
  "So dark it’s difficult to say.",
  ]},
  {"title": "d4 Prisoners are treated...", "id":"d4prisonersaretreated", "roll":[
  "Humanely; they receive reasonable meals, some exercise, and healing when needed.",
  "Like dogs; they receive poor quality meals and enough healing to keep them alive.",
  "Like rats; they receive terrible meals and are plagued by sickness.",
  "Like they don’t exist; occasionally they receive food.",
  ]},
  {"title": "d10 The prison is known for...", "id":"d10theprisonisknownfor", "roll":[
  "Many prisoners dying in a terrible plague.",
  "A mass escape in the past.",
  "The escape of a famous criminal.",
  "Being the final home of a famous criminal.",
  "Being the final home of a legendary hero.",
  "Being haunted by vengeful ghosts.",
  "Its horrific torture pits.",
  "Never suffering a successful escape.",
  "Its unusual architectural style.",
  "The quality of its meals.",
  ]},
  {"title": "d8 According to rumor, within the prison’s walls lies...", "id":"d8accordingtorumorwithintheprisonswallslies", "roll":[
  "A secret tunnel to the outside.",
  "The bones of a celebrated outlaw.",
  "The preserved head of an ancient villain.",
  "A terrible beast to which prisoners are fed.",
  "A missing lord or lady.",
  "A treasure stolen by a notorious prisoner.",
  "A unique and terrible torture device.",
  "The bones of a deposed king or queen.",
  ]},
  {"title": "d10 Rooms: This chamber is...", "id":"prisond10roomsthischamberis", "roll":[
  "A prison cell.",
  "Another prison cell.",
  "A passageway connecting cell blocks.",
  "A guardroom.",
  "The barracks.",
  "The jailer’s quarters.",
  "A yard or large indoor space for exercise.",
  "A dining hall.",
  "An interrogation room.",
  "A torture chamber.",
  ]},
  {"title": "d20 Features: You notice...", "id":"prisond20featuresyounotice", "roll":[
  "A wooden door reinforced with steel bands.",
  "Steel bars where you expected a stone wall.",
  "Empty manacles along the wall.",
  "An empty sconce to hold a torch.",
  "Distant torchlight.",
  "The floor is uneven.",
  "A crack in the stone floor.",
  "A mouse skittering underfoot.",
  "The stench of rotting flesh.",
  "The scent of stale urine.",
  "A putrid smell.",
  "A dank and moldy odor.",
  "An uncomfortable groaning.",
  "A faint scratching sound.",
  "An odd tapping sound.",
  "The squeaking of rats.",
  "The shouting of distant voices.",
  "Howls of agony.",
  "Horrific screams.",
  "The clanking of chains.",
  ]},
  {"title": "d12 You come upon...", "id":"d12youcomeupon", "roll":[
  "A snoozing guard.",
  "A pair of guards on patrol.",
  "A quartet of guards playing cards or dice on their break.",
  "A pack of trained hunting dogs commanded by a high-ranking guard who has been alerted of the escape attempt.",
  "A law official on-site to interrogate another prisoner about an unrelated case.",
  "An ear-splitting alarm triggers.",
  "A wide, well-lit yard that must be crossed with guards watching it from towers.",
  "A high wall directly in the path of escape.",
  "A barred window in the path of escape.",
  "The rat-infested kitchens and mess hall.",
  "An imprisoned serial killer who also attempting to escape.",
  "An imprisoned thief who is bent on revenge.",
  ]},
  {"title": "d8 The jailer is...", "id":"d8thejaileris", "roll":[
  "A coward who likes to act tough.",
  "A bully in every sense of the word.",
  "A bastard son of a noble house.",
  "A man who grew up among criminals.",
  "A priest with a puritanical agenda.",
  "A horrible sadist.",
  "A mild-mannered man of faith.",
  "A wicked little man.",
  ]},
  {"title": "d4 The jailer is concerned about...", "id":"d4thejailerisconcernedabout", "roll":[
  "Rumors of an upcoming escape attempt.",
  "Losing his job after a messy prisoner death.",
  "Facing a prisoner who creeps him out.",
  "Ways to make a little extra silver.",
  ]},
  {"title": "d4 The jailer is looking to...", "id":"d4thejailerislookingto", "roll":[
  "Abuse someone who is defenseless.",
  "Make himself feel powerful.",
  "Reach out to a disturbed prisoner.",
  "Swap grisly tales.",
  ]},
  {"title": "d8 The jailer carries...", "id":"d8thejailercarries", "roll":[
  "A large ring of keys.",
  "A large knife and a sap.",
  "A pale of cold porridge from the kitchens.",
  "A trophy taken from a tortured prisoner.",
  "A pocket-sized prayer book.",
  "A spiked club.",
  "A scourge or whip.",
  "A wineskin.",
  ]},
  {"title": "d4 The guard took this job for...", "id":"d4theguardtookthisjobfor", "roll":[
  "The steady pay.",
  "The chance to bully others.",
  "To prove how tough he is.",
  "To take out his aggression on criminals.",
  ]},
  {"title": "d4 On the guard’s face is...", "id":"d4ontheguardsfaceis", "roll":[
  "An unsightly scar.",
  "A stupid grin.",
  "A blank stare.",
  "A bushy mustache.",
  ]},
  {"title": "d4 The prisoner has...", "id":"d4theprisonerhas", "roll":[
  "A long scraggly beard.",
  "A patchy beard.",
  "Skin draped loosely over his bones.",
  "Boils and sores on his skin.",
  ]},
  {"title": "d6 The prisoner is here because...", "id":"d6theprisonerisherebecause", "roll":[
  "He stole something.",
  "He killed someone.",
  "He raped someone.",
  "He advocated rebellion and unrest.",
  "He committed an act of fraud.",
  "Someone confused him with someone else.",
  ]},
  {"title": "d6 Worshipers at the temple pray to...", "id":"d6worshipersatthetempleprayto", "roll":[
  "One god and only one god.",
  "One god primarily, but other gods occasionally or for specific petitions.",
  "Several gods within a pantheon, but two gods above the rest.",
  "An entire pantheon, petitioning each god for specific needs.",
  "One god to whom the temple was not originally dedicated.",
  "Several gods within a pantheon to whom the temple was not originally dedicated.",
  ]},
  {"title": "d12 The temple is dedicated to...", "id":"d12thetempleisdedicatedto", "roll":[
  "The god of the sun/sky.",
  "The earth/mother goddess.",
  "The goddess of the harvest/seasons.",
  "The god of craft/knowledge.",
  "The god of darkness/secrets.",
  "The god of death/evil.",
  "The goddess of the hunt/woodlands.",
  "The goddess of love/beauty/fertility.",
  "The goddess of the moon/magic.",
  "The god of the seas/storms.",
  "The trickster/messenger god.",
  "The tyrant/war god.",
  ]},
  {"title": "d12 The temple is known for its...", "id":"d12thetempleisknownforits", "roll":[
  "Miraculous healers.",
  "Compassionate healers.",
  "Beautiful priestesses.",
  "Wonderful music.",
  "Accurate prophecies.",
  "Collected wisdom.",
  "Stunning architecture.",
  "Unusual architecture.",
  "Incredible collection of artwork.",
  "A famous sculpture or painting.",
  "Lengthy prayer services and vigils.",
  "Lively prayer services and debates.",
  ]},
  {"title": "d6 The temple’s entrance is guarded by...", "id":"d6thetemplesentranceisguardedby", "roll":[
  "A sworn order of devout warriors.",
  "Sell-swords.",
  "Frightening statues of monstrous beings.",
  "Impressive, colossal statues of warriors.",
  "Statues of beautiful maidens, beckoning visitors into a trap.",
  "Nothing; the temple welcomes all.",
  ]},
  {"title": "d8 The temple’s main floor plan is...", "id":"d8thetemplesmainfloorplanis", "roll":[
  "Circular.",
  "Ellipsoidal.",
  "Triangular.",
  "Square.",
  "Rectangular.",
  "Pentagonal.",
  "Polygonal with many sides (d8): 1. six; 2. seven; 3. eight; 4. nine; 5. ten; 6. twelve; 7. thirteen; 8. twenty.",
  "Cruciform.",
  ]},
  {"title": "d8 The temple complex is...", "id":"d8thetemplecomplexis", "roll":[
  "Simple; a large main worship chamber with a handful of functional rooms adjoining.",
  "Simple with a large annex; the annex contains many chambers.",
  "Simple with fortifications.",
  "Multi-layered; upper or lower layers are inaccessible to most visitors.",
  "Multi-winged; some wings are inaccessible to most visitors.",
  "Arranged in a concentric fashion; inner areas are inaccessible to most visitors.",
  "Labyrinthine; designed to deliberately confuse outsiders.",
  "Simple with an intricate complex hidden beneath the main worship chamber.",
  ]},
  {"title": "d6 The temple grounds are dominated by...", "id":"d6thetemplegroundsaredominatedby", "roll":[
  "Impenetrable stone walls.",
  "An intricate structure of stone arches and columns.",
  "A colorful structure of painted wood and plaster.",
  "A sturdy structure of finished wood.",
  "A solid structure of oven-fired clay bricks.",
  "A large structure with immense metal doors (d6): 1. brass; 2. bronze; 3. gold; 4. iron; 5. steel; 6. tin",
  ]},
  {"title": "d8 Many of the temple’s interior walls are...", "id":"d8manyofthetemplesinteriorwallsare", "roll":[
  "Rough hewn stone.",
  "Smooth cut stone.",
  "Painted or lacquered wood.",
  "Unfinished hardwood.",
  "Decorated with intricate mosaics.",
  "Decorated with elaborate murals.",
  "Decorated with relief carvings.",
  "Decorated with sacred texts and runes.",
  ]},
  {"title": "d6 Many of the temple’s ceilings are...", "id":"d6manyofthetemplesceilingsare", "roll":[
  "Uncomfortably close to your head.",
  "Connected to the floor by columns.",
  "Painted with mythological scenes.",
  "So high its difficult to make out details.",
  "Vaulted.",
  "Domes or cupolas.",
  ]},
  {"title": "d20 The purpose of this room is...", "id":"templed20thepurposeofthisroomis", "roll":[
  "An armory or barracks.",
  "A guardroom or sentry post.",
  "A cell for solitary prayer.",
  "A cell for holding prisoners.",
  "An inquisition or torture chamber.",
  "A priest’s office or audience chamber.",
  "A sanitarium or infirmary.",
  "A ceremonial pool, bath, or fountain.",
  "A morgue or mortuary.",
  "A crypt for a person of importance (d4): 1. well-known hero; 2. powerful high priest; 3. obscure priest; 4. wealthy noble.",
  "A room dedicated for specific rituals (d4): 1. conjurations; 2. divinations; 3. funerals; 4. healing miracles.",
  "A chapel or shrine dedicated to a lesser deity, saint, or martyr.",
  "A classroom or dormitory.",
  "A library.",
  "A priest’s quarters or robing room.",
  "A banquet room, large dining hall, or small dining room.",
  "A kitchen or pantry.",
  "A trophy room or art gallery.",
  "A stable or kennel.",
  "A workshop for temple craftsmen.",
  ]},
  {"title": "d20 Features: You notice...", "id":"templed20featuresyounotice", "roll":[
  "A small altar set in an alcove in the wall.",
  "The sound of bells ringing in a tower.",
  "A wall sconce holding many candles.",
  "Tall candles on holders, taller than a man.",
  "The tinkle of chimes from a nearby room.",
  "A tapestry depicting a mythological scene.",
  "A small fountain or reflecting pool.",
  "The sound of a gong from another room.",
  "A large holy symbol embedded in the wall.",
  "A huge book of sacred texts or prayers.",
  "The scent of incense burning nearby.",
  "A kneeler beneath a small statue or icon.",
  "An oil lamp with colored glass panels.",
  "A mosaic set into the floor of the room.",
  "A wide fresco or mural depicting a mythological scene.",
  "The pipes of an immense organ running along the walls.",
  "Robes and cassocks hanging on hooks.",
  "An ornamental rug.",
  "A screen to hide priests from view.",
  "A statue of a recognizable figure.",
  ]},
  {"title": "d6 Encounters: You come upon...", "id":"d6encountersyoucomeupon", "roll":[
  "A young priest or priestess.",
  "An old priest or priestess.",
  "A traveler from afar.",
  "A regular, local worshiper.",
  "A member of the temple’s serving staff.",
  "A member of the temple’s guard.",
  ]},
  {"title": "d20 This tomb was built for...", "id":"d20thistombwasbuiltfor", "roll":[
  "An ancient king.",
  "An ancient queen.",
  "An ancient high priest or priestess.",
  "An ancient sorcerer.",
  "A mighty warrior.",
  "A terrible villain.",
  "A legendary adventurer.",
  "A celebrated war hero.",
  "An unscrupulous king or queen.",
  "A vain mayor or townmaster.",
  "A powerful military commander or warlord.",
  "A powerful witch or wizard.",
  "A powerful priest or priestess.",
  "A beloved sovereign.",
  "A wealthy merchant.",
  "A member of a noble house.",
  "A member of the royal family.",
  "The wife of a wealthy person or ruler.",
  "The mother of a wealthy person or ruler.",
  "The child of a wealthy person or ruler.",
  ]},
  {"title": "d12 The tomb’s entrance is...", "id":"d12thetombsentranceis", "roll":[
  "Yawning open, letting much daylight into the entry chamber.",
  "Behind a huge pair of metal doors (d4): 1. brass; 2. bronze; 3. gold; 4. iron.",
  "Beneath a stone slab.",
  "A simple wooden door framed in stone.",
  "A heavy wooden door framed in stone.",
  "Behind a heavy stone door.",
  "Beneath a gnarled, old tree.",
  "Beneath an obelisk or similar monument.",
  "Beneath a large statue.",
  "Hidden by the terrain (d4): 1. boulders; 2. waterfall; 3. rocky overhang; 4. hillock.",
  "Hidden by vegetation (d4): 1. a briar patch; 2. a curtain of moss; 3. enormous tree roots; 4. overgrown vines.",
  "Difficult to access (d4): 1. up or down a cliff face; 2. down a deep hole; 3. in an underwater tunnel; 4. through an illusory rock or wall.",
  ]},
  {"title": "d10 The tomb’s entrance is guarded by...", "id":"d10thetombsentranceisguardedby", "roll":[
  "A sworn order of devout warriors.",
  "Sell-swords.",
  "Large, frightening statues of beasts (d8): 1. bats; 2. bears; 3. dragons; 4. eagles; 5. lions; 6. ravens; 7. snakes; 8. wolves.",
  "Impressive, colossal statues of warriors.",
  "Statues of beautiful maidens, beckoning visitors into a trap.",
  "Several crumbling statues.",
  "Skeletal warriors.",
  "An unsettling arrangement of bones.",
  "A band of outlaws who are carefully delving its secrets.",
  "Nothing; the tomb is rather homey and welcoming.",
  ]},
  {"title": "d6 The tomb’s grand crypt is located...", "id":"d6thetombsgrandcryptislocated", "roll":[
  "Just beyond a heavy door in the entry chamber.",
  "Down a steep set of spiraling stairs from the entry chamber.",
  "At the end of a long passageway lined with lesser crypts.",
  "At the end of a long passage lined with statues.",
  "At the end of a long passageway lined with passageways leading to lesser crypts.",
  "Several levels below the entry chamber.",
  ]},
  {"title": "d8 The tomb’s layout is...", "id":"d8thetombslayoutis", "roll":[
  "Simple; a large grand crypt with a handful of smaller crypts and rooms adjoining.",
  "Simple with a large entry chamber; the entry chamber leads off to smaller crypts and other rooms.",
  "Multi-layered; access to the lower layers is easy to find.",
  "Multi-layered; access to the lower layers is difficult to find.",
  "Multi-winged; access to some wings is difficult to find.",
  "A series of rooms arranged in a concentric fashion; the grand crypt is located among the inner rooms.",
  "Labyrinthine; designed to deliberately confuse intruders.",
  "Simple with an intricate complex hidden beneath the grand crypt.",
  ]},
  {"title": "d8 Many of the tomb's interior walls are...", "id":"d8manyofthetombsinteriorwallsare", "roll":[
  "Rough hewn stone.",
  "Smooth cut stone.",
  "Painted or lacquered wood.",
  "Unfinished hardwood.",
  "Decorated with intricate mosaics.",
  "Decorated with elaborate murals.",
  "Decorated with bones and icons of death.",
  "Decorated with sacred texts and runes.",
  ]},
  {"title": "d6 Many of the tomb’s ceilings are...", "id":"d6manyofthetombsceilingsare", "roll":[
  "Uncomfortably close to your head.",
  "Stone, smooth as glass.",
  "Stone, rough and jagged.",
  "Connected to the floor by columns.",
  "Painted or carved with iconic scenes.",
  "Crossed by wooden beams.",
  ]},
  {"title": "d6 The tomb is rumored to...", "id":"d6thetombisrumoredto", "roll":[
  "Hold tremendous treasure.",
  "Be heavily trapped to guard against intruders.",
  "Hold a legendary weapon or artifact.",
  "Bestow a powerful curse on intruders.",
  "House the remains of someone whose body is widely believed to have been lost.",
  "Have already been cleared of monsters and gold by treasure hunters.",
  ]},
  {"title": "d20 The purpose of this room is...", "id":"tombd20thepurposeofthisroomis", "roll":[
  "An antechamber to a crypt or chapel.",
  "A chapel dedicated to protecting the souls of the deceased.",
  "A chapel dedicated to aiding the journey of the souls of the deceased.",
  "A grand crypt for a person of importance (d4): 1. well-known hero; 2. high priest; 3. powerful noble; 4. wealthy merchant.",
  "A false crypt to attract and to trap grave-robbers and treasure hunters.",
  "A crypt for immediate family members.",
  "A crypt for previous generations of the family.",
  "A crypt for the spouse of the deceased.",
  "A crypt of unmarked graves.",
  "A reflecting pool or fountain.",
  "A crypt for devoted servants or slaves.",
  "A room dedicated for specific rituals (d3): 1. divinations; 2. funerals; 3. necromancy.",
  "Gallery dedicated to the deceased (d3): 1. trophies; 2. statues; 3. paintings.",
  "A guardroom with guards (d8): 1. ghosts; 2. golems; 3. knights; 4. sell-swords; 5. cultists; 6. skeletons; 7. wights; 8. zombies.",
  "A priest’s robing room.",
  "Storage room for embalming tools.",
  "Storage room for tools and materials to maintain the tomb.",
  "Workshop for embalming the dead.",
  "A crypt hidden by a secret door where the most important person in the tomb rests.",
  "A priest’s quarters or robing room.",
  ]},
  {"title": "d20 Features: You notice...", "id":"tombd20featuresyounotice", "roll":[
  "A small altar set in an alcove in the wall.",
  "A plaque listing a family lineage.",
  "A plaque noting birth and death dates.",
  "A wall sconce holding several candles.",
  "An empty wall sconce for holding a torch.",
  "A rotten, earthy stench.",
  "A musty, moldy odor.",
  "The scent of decaying flesh.",
  "A mural depicting a mythological scene.",
  "A small fountain or reflecting pool.",
  "A huge book of sacred texts or prayers.",
  "An ornate oil lamp.",
  "A mosaic set into the floor of the room.",
  "A wide fresco or mural depicting a mythological or historical scene.",
  "A gilded sarcophagus.",
  "A simple stone sarcophagus.",
  "A finely-crafted, heavy wooden coffin.",
  "A simple, sturdy wooden coffin.",
  "A stone coffin marked with dates.",
  "An empty coffin.",
  ]},
  {"title": "d20 What haunts this tomb?", "id":"d20whathauntsthistomb", "roll":[
  "A swarm of crawling claws.",
  "A covetous wight.",
  "An ancient demilich.",
  "Malevolent ghosts.",
  "Zombie warriors.",
  "A skeletal hound.",
  "A newly-made vampire.",
  "An ancient vampire.",
  "A huge, animated pile of bones.",
  "Twisted humanoid skeletons.",
  "A zombie made from a fallen adventurer.",
  "A hateful mummy.",
  "Skeletal guardians.",
  "Phantom soldiers.",
  "The ghost of a fair maiden.",
  "Hungry ghouls.",
  "A mad wraith.",
  "A playful ghost.",
  "A treacherous spellcaster-turned-lich.",
  "A vengeful death knight.",
  ]},
  {"title": "d12 Denizens: What lives in the tomb now?", "id":"d12denizenswhatlivesinthetombnow", "roll":[
  "Carrion crawler.",
  "Cloaker.",
  "Darkmantle.",
  "Fungi.",
  "Mimics.",
  "Myconids.",
  "Ooze.",
  "Otyugh.",
  "Piercer",
  "Roper.",
  "Stirges.",
  "Umber hulk.",
  ]},
  {"title": "d8 Visitors: Who has entered the tomb of late?", "id":"d8visitorswhohasenteredthetomboflate", "roll":[
  "A devoted old priest or priestess.",
  "A curious young priest or priestess.",
  "A traveler or scholar from afar.",
  "A member of the deceased’s family.",
  "A greedy treasure hunter.",
  "A student of necromancy.",
  "A fugitive serial killer.",
  "A brave but foolish adventurer.",
  ]},



// end of dungeons

];
