// factions.js
//


top.factions = [



 {"title": "d20 This mercenary is a", "id":"d20thismercenaryisa", "roll":[
"lifelong wanderer ",
"disillusioned deserter",
"bawdy adventurer",
"cold professional",
"glory-seeking soldier of fortune",
"seeker of knowledge and experiences",
"proud warrior on a quest to find a worthy opponent",
"commoner looking to make some easy money",
"loveable scoundrel",
"reputable veteran",
"bloodthirsty sadist",
"ascended beggar",
"hardened refugee",
"a former member of a disbanded army",
"devious sellsword",
"on a quest to cleanse the world of bandits or monsters",
"dishonoured city watchman",
"a runaway slave",
"merchant who has taken up killing",   ]},
 {"title": "d8 their skillset is that of a (optional add a coin flip)", "id":"d8theirskillsetisthatofaoptionaladdacoinflip", "roll":[
"Hunter or Trapper",
"Rogue or Assassin",
"Mage or Enchanter",
"Healer or Alchemist",
"Monster Hunter or Exterminator",
"Gladiator or Duellist",
"Cleric or Bard",   ]},
 {"title": "d10 their primary weapon is a", "id":"d10theirprimaryweaponisa", "roll":[
"Battleaxe",
"Scimitar",
"Halberd",
"Bow",
"Shortsword and Dagger",
"Crossbow",
"Warmace",
"Staff",
"Hammer",   ]},
 {"title": "d8 which stands out for being", "id":"d8whichstandsoutforbeing", "roll":[
"made of an unusual material",
"emitting a supernatural hum or glow",
"obviously mastercrafted",
"of foreign design",
"poorly maintained and dirty",
"battered to the point of breaking",
"engraved with a name",   ]},
 {"title": "d6 they are also good at ", "id":"d6theyarealsogoodat", "roll":[
"Game (d6): 1. Cards; 2. Dice; 3. Arm Wrestling; 4. Board Strategy; 5. Slap Jack; 6. Horseshoe Throwing",
"Secondary weapon (d6): 1. Throwing Knives; 2. Javelin; 3. Flail; 4. Unarmed Combat; 5. Darts; 6. Whip",
"Performing art (d6): 1. Singing; 2. Dancing; 3. Storytelling; 4. Acting; 5. Juggling; 6: Playing an Instrument",
"Craftsmanship (d6): 1. Smithing; 2. Construction; 3. Tailoring; 4. Brewing; 5. Carpenting; 6. Cooking",
"Adventuring skill (d6): 1. Geography or Navigation; 2. Lockpicking; 3. Equipment Maintenance; 4. Shadowing; 5. Riding; 6. Trade",   ]},
 {"title": "d40 their main distinguishing feature is", "id":"d40theirmaindistinguishingfeatureis", "roll":[
"colourful clothing",
"a disfiguring facial scar",
"an unwillingness to do certain types of jobs",
"obvious foreign origin",
"a strange hairstyle or colour",
"exuding an aura of fear/respect/professionalism",
"looking a remarkably similar to a certain criminal being searched for a few towns over",
"always being either drunk or hungover",
"an unusual level of attractiveness",
"flaunting expensive jewellery",
"having an unusual fighting style",
"wearing protective charms and amulets",
"talking very little",
"displaying the colours of his liege or realm of origin",
"always looking to bed someone",
"extreme profanity",
"having a pet",
"very bad teeth",
"smoking a pipe",
"being very old",
"sporting religious symbols",
"a loud, penetrating voice",
"currently wounded",
"wearing a trophy",
"carrying a small book in a satchel",
"fat",
"heterochromatic",
"speech impediment",
"always eating something",
"wears an eyepatch",
"walks with a limp",
"clad in black",
"good with children",
"looking depressed or dead inside",
"missing an ear",
"clothed inappropriately for the weather",
"spitting on the ground a lot",
"an annoying laugh",
"constantly fidgeting with a coin",   ]},
 {"title": "d4 their level of competence is", "id":"d4theirlevelofcompetenceis", "roll":[
"Average",
"Good",
"Excellent",   ]},
 {"title": "d6 their pricing is", "id":"d6theirpricingis", "roll":[
"Low",
"Affordable",
"Above average",
"High",
"Exorbitant",   ]},


{"title": "d12 The guild’s symbol is...", "id":"d12theguildssymbolis", "roll":[
"A skull.",
"An eye.",
"A flame.",
"A dagger.",
"A scythe.",
"An arrow.",
"A fish.",
"A crow.",
"A rat.",
"A scorpion.",
"A spider.",
"A snake.",
]},
{"title": "d20 The guild’s preferred method of execution is...", "id":"d20theguildspreferredmethodofexecutionis", "roll":[
"Ingested poison or allergic reaction.",
"Exposure to deadly (but not highly contagious) disease.",
"Contact poison applied to a weapon.",
"Arrow/bolt from range.",
"Knife in the chest or back.",
"Multiple stab wounds.",
"Slitting throats.",
"Gutting or eviscerating.",
"Flaying or scalping.",
"Beheading.",
"Strangulation.",
"Hanging.",
"Burying alive.",
"Drowning.",
"Boiling alive.",
"Throwing off a roof.",
"Acid (pouring or submersion).",
"Fiery explosion.",
"Burning alive.",
"Feeding to animals.",
]},
{"title": "d12 Guildmembers typically arm themselves with...", "id":"d12guildmemberstypicallyarmthemselveswith", "roll":[
"Poisoned daggers and short swords.",
"Throwing knives.",
"Over-sized daggers.",
"Serrated daggers.",
"Daggers and crossbows.",
"Axes and knives.",
"Bows and arrows.",
"Short swords and crossbows.",
"Sickles and scythes.",
"Garrotes and daggers.",
"Exotic blades and blowguns.",
"Bolas and poisoned projectiles.",
]},
{"title": "d6 Guildmembers typically operate...", "id":"d6guildmemberstypicallyoperate", "roll":[
"Alone.",
"In pairs.",
"In small groups.",
"By infiltrating an organization.",
"By impersonating a specific individual.",
"In plain sight.",
]},
{"title": "d6 Guildmembers typically know...", "id":"d6guildmemberstypicallyknow", "roll":[
"Very few other guildmembers.",
"Several other guildmembers.",
"The details of the guild’s organization.",
"Nothing about the guild’s leadership.",
"The names of the guild’s leaders, though they’ve never met any of them.",
"One of the guild’s leading members and no other guildmembers.",
]},
{"title": "d12 The guild’s leader is...", "id":"d12theguildsleaderis", "roll":[
"A dangerous megalomaniac.",
"A charismatic demagogue.",
"A mysterious foreigner.",
"A talented thief.",
"A well-known public figure.",
"A ruthless killer.",
"A femme fatale.",
"A charming rogue.",
"A dashing swashbuckler.",
"A brutish thug.",
"A religious fanatic.",
"A veteran soldier.",
]},
{"title": "d6 The guild’s goals include (leadership and rank-and-file members could have different goals)...", "id":"d6theguildsgoalsincludeleadershipandrankandfilememberscouldhavedifferentgoals", "roll":[
"Expanding the client base.",
"Corrupting and influencing the politics of the city or region.",
"Eliminating a rival assassins’ guild in the same city or region.",
"Eliminating a rival assassins’ guild in a foreign city or region.",
"Intimidating the masses.",
"Instigating rebellion among the masses.",
]},
{"title": "d8 The guild refuses to take contracts to kill...", "id":"d8theguildrefusestotakecontractstokill", "roll":[
"Women.",
"Young children.",
"Nobles and prominent citizens.",
"Priests and monks.",
"Peasants and poor folk.",
"Foreigners and travelers.",
"Members of the client’s family.",
"Fellow criminals.",
]},
{"title": "d8 Guildmembers typically strike with...", "id":"d8guildmemberstypicallystrikewith", "roll":[
"Hit-and-run tactics.",
"Ambush tactics.",
"Diversionary tactics.",
"A precisely planned attack strategy.",
"A well-planned escape strategy.",
"The element of surprise.",
"Announcing their presence.",
"No thought of escape.",
]},
{"title": "d8 Guildmembers typically plan their attacks for...", "id":"d8guildmemberstypicallyplantheirattacksfor", "roll":[
"Just after sunrise.",
"High noon.",
"Just after sunset.",
"Well into the night.",
"The toll of midnight.",
"After midnight.",
"The wee hours of the morning.",
"Just before sunrise.",
]},
{"title": "d12 The guild’s headquarters is hidden in or near...", "id":"d12theguildsheadquartersishiddeninornear", "roll":[
"The residence of the leader or a senior guildmember.",
"An artisan's shop or guildhall.",
"A merchant's office.",
"A tavern.",
"A brothel.",
"A warehouse or shipyard.",
"A temple complex.",
"The city's sewers.",
"The town hall.",
"An abandoned guildhall or warehouse.",
"An armory or barracks.",
"The residence of a wealthy individual or prominent citizen.",
]},
{"title": "d12 The guild is feared or respected by...", "id":"d12theguildisfearedorrespectedby", "roll":[
"Fishermen and sailors.",
"Beggars and orphans.",
"Merchants and moneychangers.",
"Nobles and rulers.",
"Politicians and magistrates.",
"Guards and sheriffs.",
"Soldiers and warriors.",
"Thieves and criminals.",
"Servants and slaves.",
"Priests and sages.",
"Women and children.",
"Other assassins.",
]},
{"title": "d20 This is a guild for...", "id":"d20thisisaguildfor", "roll":[
"Miners.",
"Foresters.",
"Farmers.",
"Laborers.",
"Smithies.",
"Barbers and dentists.",
"Jewelers.",
"Fools, entertainers, and players.",
"Shipwrights.",
"Tanners, furriers, and shoemakers.",
"Butchers.",
"Locksmiths and nailsmiths.",
"Potters and dyers.",
"Saddlers, farriers, and stable masters.",
"Joiners, wheelwrights, and coopers.",
"Masons.",
"Weavers and tailors",
"Goldsmiths and watchmakers",
"Learned professionals (d8): 1. alchemists; 2. architects; 3. calligraphers; 4. historians; 5. lawyers and judges; 6. scribes; 7. siege engineers; 8. writers.",
"Special artisans and artists (d10): 1. brewers; 2. candlers; 3. chefs; 4. glassblowers; 5. historical reenactors; 6. mithrilsmiths; 7. musicians; 8. painters; 9. sculptors; 10. silversmiths.",
]},
{"title": "d8 This guild's status and control is...", "id":"d8thisguildsstatusandcontrolis", "roll":[
"Poor; though once great, this guild has fallen on hard times and is struggling to maintain its power.",
"Brand new, and frantically recruiting members in order to snatch power.",
"Exponentially rising, a recent boon has granted them great profits.",
"Slowing, a rising competitor is slowly cutting into profits.",
"Absolute, they have complete dominance in their field.",
"Spotty, depending on the will of the coin and the market this guild may be drinking Elven wine or rotten grog.",
"Unquestioned, they exert complete dominance over all other guilds in the area.",
"Questionable, though they claim to have control, some operators have undermined it.",
]},
{"title": "d8 This guild's illicit affairs comprise...", "id":"d8thisguildsillicitaffairscomprise", "roll":[
"Literally nothing, they are paragons of upright morality.",
"Staying well within the law, if slipping on a few taxes due to ignorance, of course.",
"Knowing how to play the political game, they garner a few indirect favors from officials.",
"Guild leaders having dollar signs for eyes, and setting advantageous prices in the city.",
"Price floors becoming commonplace, and officials are often bribed in order to overlook some minor illicit activities.",
"A variety of upper-level bribes, some minor scams, and the dismay of local priests.",
"Rampant corruption, with large-scale bribery of various city officials and contracts with thieves’ guild and occasionally an assassin.",
"Pacts with devils, large-scale counterfeiting, and treasonous activities are a normal Tuesday morning for this guild.",
]},
{"title": "d8 This guild's headquarters is...", "id":"d8thisguildsheadquartersis", "roll":[
"The leader's or leaders' personal residence, a large manor.",
"The dusty basement of the city's capital hall.",
"A single, thin, and very tall townhouse that leans slightly into the street.",
"A moored ship, especially curious in landlocked cities.",
"An open-air pavilion centered in the city's bazaar.",
"Doubling as a large and prestigious bank.",
"An opulent demiplane hidden in a shady back-alley.",
"Jointly shared with all the guilds of the city, and the thieves guild lurks in the sewers below.",
]},
{"title": "d6 Minor Quest: You must fetch a shipment of goods from...", "id":"d6minorquestyoumustfetchashipmentofgoodsfrom", "roll":[
"The city gates, held up by a bureaucratic city official.",
"The nearest village, where they're caught up in some small-town superstition.",
"A relatively nearby city, where there a severe mix-up with the shipments.",
"The natural areas one would gather them, yourself, to learn the roots of your trade.",
"The stores of the city's banks, which must be paid off from their mortgage.",
"Across the room where the party receives the quest.",
]},
{"title": "d6 Standard Quest: Recently the guild has lost access to raw materials or manufacturing because of...", "id":"d6standardquestrecentlytheguildhaslostaccesstorawmaterialsormanufacturingbecauseof", "roll":[
"A recent venture with a supplier, rival, or local official that has turned out bad.",
"A trade blockade that has to be resolved.",
"A thieves’ guild that is targeting the guild, but may be convinced to look somewhere else.",
"A master using it frivolously, you must go out to harvest a sufficient replacement amount.",
"A city official banning them, citing it as an immoral substance.",
"Spending all the coffer's stores on fulfilling a special contract or bribing officials, lacking the foresight to buy sufficient raw materials.",
]},
{"title": "d6 Major Quest: The guild would like you to fetch a rare creature or material from...", "id":"d6majorquesttheguildwouldlikeyoutofetchararecreatureormaterialfrom", "roll":[
"The marketplace of the City of Brass.",
"An ancient dwarven stronghold's forges.",
"A quaint pasture—in the wildest parts of Arborea.",
"A faraway island, rumored to have cannibals and foul magicks.",
"A mystic mirage that manifests in a desert for twenty minutes once every century.",
"The Plane of Rats (or similar filthy location).",
]},
{"title": "d4 The apprentice is...", "id":"d4theapprenticeis", "roll":[
"Bored.",
"Eager to learn.",
"Frustrated by his or her own mistakes.",
"Nervously looking about.",
]},
{"title": "d4 The apprentice seeks someone to...", "id":"d4theapprenticeseekssomeoneto", "roll":[
"Give him some tips in the craft.",
"Purchase an item made by the apprentice.",
"Tell a tale that inspires creativity.",
"Sneak off for a drink and some kisses.",
]},
{"title": "d6 The artisan is...", "id":"guildd6theartisanis", "roll":[
"A young journeyman.",
"A mediocre journeyman.",
"A skilled journeyman.",
"A veteran of the craft.",
"A master of the craft.",
"An old crafter.",
]},
{"title": "d8 The artisan has...", "id":"guildd8theartisanhas", "roll":[
"A friendly smile.",
"Keen eyes.",
"Watery eyes.",
"A stubborn scowl.",
"A dour frown.",
"A missing tooth.",
"Tired eyes.",
"An amused smirk.",
]},
{"title": "d8 The artisan has...", "id":"guildd8theartisanhas2", "roll":[
"A limp.",
"A hunchback.",
"Unsteady hands when they aren’t at work.",
"A habit of looking down.",
"A bulbous nose.",
"A burn scar on the face.",
"A wispy mustache.",
"A thick mustache.",
]},
{"title": "d6 The artisan is particularly skilled at...", "id":"d6theartisanisparticularlyskilledat", "roll":[
"Crafting one particular type of item.",
"Identifying high quality raw materials.",
"Putting the finishing touches on an item.",
"Instructing and training apprentices.",
"Negotiating better prices for goods.",
"Maneuvering in guild politics.",
]},
{"title": "d8 The artisan is looking for...", "id":"d8theartisanislookingfor", "roll":[
"A new apprentice.",
"A journeyman craftsman to hire.",
"Rare materials.",
"A better set of tools.",
"Someone with whom to talk shop.",
"Someone who witnessed a recent sporting event.",
"Someone who is attending an upcoming sporting event.",
"A mug of strong ale.",
]},
{"title": "d6 The artisan is carrying...", "id":"d6theartisaniscarrying", "roll":[
"The tools of his or her trade.",
"Some raw materials.",
"A finished product.",
"A little coin.",
"A to-do list scrawled on a bit of parchment.",
"A set of many keys.",
"A pipe and some tobacco.",
"A flask of whisky.",
]},
{"title": "d6 The artisan is...", "id":"guildd6theartisanis2", "roll":[
"A well-known member of the guild.",
"An established or up-and-coming leader in the guild.",
"A new member of the guild, having recently relocated from a distant land.",
"A quiet guildmember, who doesn’t get involved in guild politics.",
"On the outs with guild leadership.",
"A favorite of some of the guild’s leaders.",
]},
{"title": "d6 The artisan dreams of...", "id":"d6theartisandreamsof", "roll":[
"Producing a masterwork of the craft.",
"Holding the reins of guild leadership.",
"Retiring peacefully.",
"Retiring rich.",
"Running away from it all.",
"A life of adventure.",
]},
{"title": "d12 The cultists revere...", "id":"d12thecultistsrevere", "roll":[
"A dragon.",
"A demon lord.",
"An archdevil.",
"A long-dead ancient hero.",
"A long-dead ancient villain.",
"A dead god.",
"An aberrant creature.",
"An elemental creature.",
"A primordial.",
"Primal spirits.",
"An exarch of a god.",
"The cult’s own leader.",
]},
{"title": "d10 The cultists meet in...", "id":"d10thecultistsmeetin", "roll":[
"A secret chamber in a well-known temple.",
"The cellar of a popular tavern.",
"A secret chamber in a well-known guildhall.",
"The cellar of a wealthy merchant's house.",
"The city sewers.",
"Ancient catacombs beneath the city.",
"A cabin in the countryside.",
"A creepy, dark cave.",
"A heavily guarded chamber within a castle.",
"The stacks of a well-stocked library.",
]},
{"title": "d20 The cult’s leader is...", "id":"d20thecultsleaderis", "roll":[
"A devoted acolyte.",
"A dogmatic teacher.",
"An adept healer.",
"A charismatic preacher.",
"An eccentric scholar.",
"An outspoken zealot.",
"A dangerous megalomaniac.",
"A charismatic demagogue.",
"A mysterious foreigner.",
"A well-known public figure.",
"A ruthless killer.",
"A femme fatale.",
"A charming rogue.",
"A powerful noble.",
"A talented artist.",
"A religious fanatic.",
"A veteran soldier.",
"A humble artisan.",
"An ancient hero reborn.",
"The second coming of a god.",
]},
{"title": "d6 The cult's membership is primarily made up of...", "id":"d6thecultsmembershipisprimarilymadeupof", "roll":[
"The poor and downtrodden (d4): 1. beggars; 2. laborers; 3. servants; 4. slaves.",
"The wealthy elite (d4): 1. guildmasters; 2. merchants; 3. nobles; 4. royalty.",
"A segment of another religion's population (d8): 1. sun god; 2. earth mother; 3. death god; 4. huntress; 5. goddess of love; 6. storm god; 7. trickster god; 8. war god.",
"Members of a particular trade (d8): 1. blacksmiths; 2. carpenters; 3. farmers; 4. fishermen; 5. miners; 6. soldiers 7. stonemasons; 8. weavers.",
"Members of a particular race (d8): 1. dwarves; 2. elves; 3. gnomes;; 4. goblins; 5. half-breeds; 5. halflings; 6. humans; 7. orcs; 8. reptilians.",
"Members of all social strata.",
]},
{"title": "d8 The cult's practices involve (leadership and believers could adhere to different practices)...", "id":"d8thecultspracticesinvolveleadershipandbelieverscouldadheretodifferentpractices", "roll":[
"Animal sacrifice (d10): 1. bulls; 2. calves; 3. cats; 4. chickens; 5. dogs; 6. goats; 7. pigeons; 8. rabbits; 9. rams; 10. songbirds.",
"Human sacrifice (d6): 1. children; 2. elderly; 3. harlots; 4. nonbelievers; 5. priests and priestesses; 6. virgins.",
"Self-mutilation (d10): 1. arm; 2. back; 3. cheek; 4. chest; 5. ear; 6. eye.; 7. feet; 8. finger; 9. genitalia; 10. nose.",
"Burnt offerings (d4): 1. herbs; 2. incense; 3. meat; 4. prisoners.",
"Offerings of gold, gems, and valuables.",
"Strange incantations.",
"Public acts of violence (d4): 1. beatings; 2. looting; 3. murders; 4. riots.",
"Ritualistic sexual acts (d4): 1. bestiality; 2. breedings; 3. deflowerings; 4. orgies.",
]},
{"title": "d8 The cult's goals (leadership and believers could have different goals)...", "id":"d8thecultsgoalsleadershipandbelieverscouldhavedifferentgoals", "roll":[
"Domination of the city or region.",
"Destruction of the city or region.",
"Reincarnation of a long-dead entity.",
"Declaration of war against a rival city or nation.",
"Rebellion against the city or nation's elite.",
"Death to non-believers.",
"Opening a portal to another plane.",
"Release of a powerful captive entity.",
]},
{"title": "d12 The cult’s members must follow a strict rule regarding...", "id":"d12thecultsmembersmustfollowastrictruleregarding", "roll":[
"Wearing a flower in the hair or on the lapel (d4): 1. lily; 2. orchid; 3. rose; 4. tulip.",
"Fashion trends.",
"Maintaining their personal weapon (d4): 1. club; 2. dagger; 3. handaxe; 4. staff.",
"Treatment of pets.",
"Mounting a horse.",
"Dressing one’s self for worship.",
"Dressing one’s self for day-to-day activities.",
"Diet.",
"Exercise routines.",
"Bathing.",
"Styling one’s hair.",
"Brushing one’s teeth.",
]},
{"title": "d12 The cult’s members are particularly afraid of or takes special care to avoid...", "id":"d12thecultsmembersareparticularlyafraidofortakesspecialcaretoavoid", "roll":[
"Hallowed places.",
"Moonlight.",
"Sunlight.",
"Crossing running water.",
"Sharp wooden objects.",
"Garlic.",
"Silver objects.",
"Relics of the gods.",
"Sleeping outdoors.",
"Milk and cheese.",
"Eating meat.",
"Sobriety.",
]},
{"title": "d6 The cultist...", "id":"d6thecultist", "roll":[
"Is an outspoken true believer.",
"Is a raving lunatic.",
"Is a quiet, fervent believer.",
"Has doubts, but is devoted to the cult's leader.",
"Has doubts, but is too afraid to voice them.",
"Doesn't care about the religious stuff; the cult meets other needs.",
]},
{"title": "d10 The cultist wears...", "id":"d10thecultistwears", "roll":[
"A bandage on the thumb.",
"A face tattoo of a holy symbol.",
"A tattoo depicting an evil icon.",
"A string of garlic around the neck.",
"A robe with a tear at the knee.",
"A fine silk robe.",
"A large gold ring on one hand.",
"A hooded robe.",
"A robe emblazoned with a holy symbol.",
"A lush, full beard.",
]},
{"title": "d10 The cultist has...", "id":"d10thecultisthas", "roll":[
"A ceremonial dagger in hand.",
"A book protruding from his or her pocket.",
"A large scar on the throat.",
"Scraggly matted hair.",
"A shaved head.",
"Scars on the wrists.",
"A protruding chin.",
"A maniacal grin.",
"A surly curl of the lip.",
"A gap between the front teeth.",
]},
{"title": "d10 The cultist is...", "id":"d10thecultistis", "roll":[
"Humming an eerie incantation.",
"Sweating profusely.",
"Breathing heavily.",
"Twitching nervously.",
"Laughing hysterically.",
"Muttering under his/her breath.",
"Coughing up a lung.",
"Whispering a prayer.",
"Moving with a limp.",
"Stinking of wine.",
]},
{"title": "d10 The cultist is looking for...", "id":"d10thecultistislookingfor", "roll":[
"Ways to impress the cult’s leader.",
"Tips for seducing the cult’s leader.",
"Methods to assassinate the cult’s leader.",
"Something that will impress his/her god.",
"Something to eat.",
"Something to kill.",
"Ways to advance the cult’s goals.",
"New recruits.",
"Religious scholars to debate.",
"A bottle of wine.",
]},
{"title": "d12 The mercenary troop’s colors are...", "id":"d12themercenarytroopscolorsare", "roll":[
"Black.",
"Red / scarlet.",
"Gold.",
"Forest green.",
"Royal blue.",
"Brown / beaver.",
"Dark grey / gunmetal.",
"Maroon.",
"Navy blue.",
"Dark brown / chocolate.",
"Steel / blue grey.",
"Olive green.",
]},
{"title": "d20 The mercenary troop’s banner features...", "id":"d20themercenarytroopsbannerfeatures", "roll":[
"A skull.",
"A ghost.",
"A clenched fist.",
"A flame.",
"An arrow.",
"A dagger.",
"A sword.",
"A hammer.",
"The sun.",
"The moon.",
"A bat.",
"A bull.",
"A dragon.",
"A falcon.",
"A lion.",
"A raven.",
"A scorpion.",
"A snake.",
"A vulture.",
"A wolf.",
]},
{"title": "d10 The mercenary troop’s commander is...", "id":"d10themercenarytroopscommanderis", "roll":[
"A brazen outlaw.",
"A charismatic demagogue.",
"A mysterious foreigner.",
"An outcast from a prominent family.",
"A ruthless killer.",
"A dashing swashbuckler.",
"A brutish thug.",
"A celebrated war hero.",
"A disgraced knight.",
"A former arena champion.",
]},
{"title": "d6 The mercenary troop’s attitude toward their commander is...", "id":"d6themercenarytroopsattitudetowardtheircommanderis", "roll":[
"Friendly and loyal.",
"Respectful and business-like.",
"Cautious and uncertain.",
"Terrified and tight-lipped.",
"Disappointed and rude.",
"Angry and rebellious.",
]},
{"title": "d6 The mercenary troop is currently...", "id":"d6themercenarytroopiscurrently", "roll":[
"Gainfully employed as guards.",
"Gainfully employed in war.",
"Under contract with some criminals.",
"Under contract with some merchants.",
"Under contract with some nobles.",
"Looking for work.",
]},
{"title": "d10 The mercenary troop specializes in...", "id":"d10themercenarytroopspecializesin", "roll":[
"Siege-breaking.",
"Holding a redoubt or fort.",
"Frontal assault.",
"Infiltration tactics.",
"Skirmishes.",
"Laying ambushes.",
"Patrolling.",
"Flanking maneuvers.",
"Guerilla tactics.",
"Raiding and pillaging.",
]},
{"title": "d8 The mercenary troop is notorious for...", "id":"d8themercenarytroopisnotoriousfor", "roll":[
"Taking no prisoners.",
"Leaving the dead to be eaten by beasts.",
"Tattooing or branding prisoners.",
"Scalping or flaying prisoners.",
"Burning villages and fields.",
"Betraying their employers.",
"Singing bawdy songs.",
"Drinking too much ale and wine.",
]},
{"title": "d8 The mercenary troop fights with...", "id":"d8themercenarytroopfightswith", "roll":[
"Hit-and-run tactics.",
"Making a direct assault.",
"Fancy footwork.",
"Unpredictable lurches.",
"Masterful combat maneuvers.",
"No mercy.",
"Lots of taunts and jeers.",
"Dirty tactics.",
]},
{"title": "d8 Many of the mercenaries in the troop are armored in...", "id":"d8manyofthemercenariesinthetrooparearmoredin", "roll":[
"Exotic robes.",
"Leather armor.",
"Studded leather armor.",
"Hide armor",
"Ringmail.",
"Chainmail.",
"Scale armor.",
"Plate armor.",
]},
{"title": "d12 Many of the mercenaries in the troop are wielding...", "id":"d12manyofthemercenariesinthetrooparewielding", "roll":[
"Longswords.",
"Longswords and shields.",
"Short swords and spears.",
"Short swords and shields.",
"Longswords and crossbows.",
"Greatswords.",
"Spears and shields.",
"Battleaxes.",
"Battleaxes and shields.",
"Warhammers.",
"Scimitars.",
"Scimitars and a shields.",
]},
{"title": "d8 The guild is controlled by...", "id":"d8theguildiscontrolledby", "roll":[
"A no-nonsense kingpin who despises bureaucracy.",
"A small and pinched-face gnome with a sinister desire for money.",
"An inexperienced young noble with a petulant need for a full purse.",
"A council of the heads of local crafting guilds.",
"An argumentative mass democracy of all the city's merchants.",
"A longstanding and ancient charter that applies to all merchants, and the militia acting as the charter's executors.",
"The most wealthy merchant in the city.",
"A city-appointed monk, who has sworn away worldly wealth.",
]},
{"title": "d8 This guild's illicit affairs comprise...", "id":"d8thisguildsillicitaffairscomprise", "roll":[
"Literally nothing, they are paragons of upright morality.",
"Staying well within the law, if slipping on a few taxes due to ignorance, of course.",
"Knowing how to play the political game, they garner a few indirect favors from officials.",
"Guild leaders having dollar signs for eyes, and setting advantageous prices in the city.",
"Price floors becoming commonplace, and officials are often bribed in order to overlook some minor illicit activities.",
"A variety of upper-level bribes, some minor scams, and the dismay of local priests.",
"Rampant corruption, with large-scale bribery of various city officials and contracts with thieves’ guild and occasionally an assassin.",
"Pacts with devils, large-scale counterfeiting, and treasonous activities are a normal Tuesday morning for this guild.",
]},
{"title": "d8 This guild's status and control is...", "id":"d8thisguildsstatusandcontrolis", "roll":[
"Poor; though once great, this guild has fallen on hard times and is struggling to maintain its power.",
"Brand new, and frantically recruiting members in order to snatch power.",
"Exponentially rising, a recent boon has granted them great profits.",
"Slowing, a rising competitor is slowly cutting into profits.",
"Absolute, they have complete dominance in their field.",
"Spotty, depending on the will of the coin and the market this guild may be drinking Elven wine or rotten grog.",
"Unquestioned, they exert complete dominance over all other guilds in the area.",
"Questionable, though they claim to have control, some operators have undermined it.",
]},
{"title": "d8 Minor Quest: The guild has been having some trouble with...", "id":"d8minorquesttheguildhasbeenhavingsometroublewith", "roll":[
"A merchant was recently shaken down by a lowly thug, send a message.",
"Gold stores, perhaps you could make a donation of 500 gold pieces?",
"Transporting a semi-rare magical item to a nearby branch.",
"A caravan that doesn't feel comfortable going through a newly discovered path in the nearby woods, escort them.",
"A city militia member getting nosy.",
"A crafting guild hesitant to sign up for the merchant guild's special loyalty program.",
"A rat infestation.",
"A rat infestation (that actually is a rift to the Plane of Rats or similar filthy location).",
]},
{"title": "d8 Standard Quest: The guild needs you to handle...", "id":"d8standardquesttheguildneedsyoutohandle", "roll":[
"A caravan gone missing in a nearby region.",
"A rising thieves’ guild that seems uncooperative.",
"A city official hellbent on stamping out capitalism.",
"A competing Merchant guild that has begun to outpace the guild.",
"A recent trade blockade—you need to resolve the tensions or clear the blockade.",
"Rumors of aberrations in the night that have driven away trade.",
"A Board Member who has decided to go rogue and has stolen from the coffers.",
"A very large rat infestation (the rift has become a permanent Gate to the Plane of Rats or similar filthy location).",
]},
{"title": "d8 Major Quest: A matter of great import, the guild is faced with...", "id":"d8majorquestamatterofgreatimporttheguildisfacedwith", "roll":[
"A mercenary army that has laid siege to the city!",
"Mass corruption from the inside, half the board is revealed to be mind flayers.",
"A massive religious revival that causes the entire population to scorn material pursuits and cut deep into the bottom line.",
"A mummy king who has taken a caravan with most of the guild coffer's investments hostage.",
"Political revolution that threatens the guild coffers with looting, protect our stores but civilians cannot be harmed.",
"An investigation from the King's Spymaster into the extent of the guild's illicit activities.",
"A planar being has supplanted the guild master, who is imprisoned in a planar cage.",
"Waves of rats that threaten the entire guildhall's basement (the rift has become a gigantic faucet of rats) where an Avatar of the God of Rats has taken up residence.",
]},
{"title": "d6 This trading company's specific specialty or purpose is...", "id":"d6thistradingcompanysspecificspecialtyorpurposeis", "roll":[
"Long-range sea trade, exploration, and transport.",
"Long-range aerial trade; accomplished with airships, aarakocra messengers, and the occasional roc or dragon.",
"The hunting and trapping of exotic monsters and animals.",
"Acting as a puppet agency for a local kingdom manipulating global trade.",
"Securing and creating long-range caravans, and the slow growth of roads (and maybe even railroads).",
"Exploring and exploiting newly discovered lands or planes.",
]},
{"title": "d8 This trading company is controlled by...", "id":"d8thistradingcompanyiscontrolledby", "roll":[
"A planar being disguised as a wealthy merchant (refer to illicit activities roll for planar source, low is celestial, middle is neutral, high is fiendish).",
"A joint council of Masters of Coin from all civilized kingdoms of the world.",
"A savant goblin who has achieved immortality by divine blessing.",
"A grizzled ex-adventurer.",
"A council of investors.",
"An argumentative mass democracy of all the company's merchants.",
"A massively wealthy caravan master who found a lost city of gold.",
"A large and grotesque slave master.",
]},
{"title": "d4 The shopkeeper is...", "id":"d4theshopkeeperis", "roll":[
"Bored.",
"Eager to help.",
"Visibly perturbed.",
"Nervously looking about.",
]},
{"title": "d4 The shopkeeper seeks someone to...", "id":"d4theshopkeeperseekssomeoneto", "roll":[
"Purchase faulty goods.",
"Purchase a large shipment of goods.",
"Listen to some whining.",
"Share some wine and chat.",
]},
{"title": "d6 The merchant is...", "id":"d6themerchantis", "roll":[
"A member of a trading clan.",
"A minor lord or lady.",
"An enterprising trader.",
"A member of a prominent family.",
"Of common birth.",
"The representative of a more powerful merchant.",
]},
{"title": "d4 The merchant wears...", "id":"d4themerchantwears", "roll":[
"An unpleasant grin.",
"An arrogant smirk.",
"Too much perfume.",
"A baggy shirt to cover a fat belly.",
]},
{"title": "d4 The merchant seeks someone to...", "id":"d4themerchantseekssomeoneto", "roll":[
"Obtain a mysterious artifact.",
"Negotiate a trade contract.",
"Sabotage a rival merchant.",
"Have a good time with.",
]},
{"title": "d6 The merchant carries...", "id":"d6themerchantcarries", "roll":[
"A family heirloom.",
"Several inventories and invoices.",
"Some very valuable jewels.",
"A compromising love letter.",
"A small knife.",
"A vial of healing potion, just in case.",
]},
{"title": "d6 Currency: Besides coin, the merchant will trade in...", "id":"d6currencybesidescointhemerchantwilltradein", "roll":[
"Gems and jewelry.",
"Gold and silver bullion.",
"Water, provisions, and other goods.",
"Shells, beads, and trinkets.",
"Favors.",
"Scandalous information.",
]},
{"title": "d20 The company’s colors are...", "id":"d20thecompanyscolorsare", "roll":[
"Black.",
"Red / scarlet.",
"Gold.",
"Forest green.",
"Royal blue.",
"Violet.",
"Silver / light grey.",
"Bronze.",
"Tan / khaki.",
"Brown / beaver.",
"Dark grey / gunmetal.",
"White.",
"Maroon.",
"Sky blue.",
"Navy blue.",
"Dark brown / chocolate.",
"Teal / turquoise.",
"Yellow.",
"Orange.",
"Olive green.",
]},
{"title": "d20 The company’s banner features...", "id":"d20thecompanysbannerfeatures", "roll":[
"A skull.",
"A clenched fist.",
"A flame.",
"A shield.",
"An arrow.",
"An axe.",
"A hammer.",
"A sword.",
"The sun.",
"The moon.",
"A bear.",
"A bull.",
"A dragon.",
"A falcon.",
"A lion.",
"A raven.",
"A scorpion.",
"A snake.",
"A stag.",
"A wolf.",
]},
{"title": "d10 The company’s commander is...", "id":"d10thecompanyscommanderis", "roll":[
"A brilliant strategist.",
"A scion from a prominent family.",
"An outcast from a prominent family.",
"A dashing swashbuckler.",
"A brutish thug.",
"A celebrated war hero.",
"A disgraced knight.",
"An anointed knight.",
"A career soldier",
"A former arena champion.",
]},
{"title": "d6 The company’s attitude toward their commander is...", "id":"d6thecompanysattitudetowardtheircommanderis", "roll":[
"Friendly and loyal.",
"Respectful and business-like.",
"Cautious and uncertain.",
"Terrified and tight-lipped.",
"Disappointed and disrespectful.",
"Agitated and restless.",
]},
{"title": "d8 The company specializes in...", "id":"d8thecompanyspecializesin", "roll":[
"Siege-breaking.",
"Holding redoubts.",
"Frontal assaults.",
"Skirmishes.",
"Patrolling.",
"Flanking maneuvers.",
"Guerilla tactics.",
"Foraging.",
]},
{"title": "d8 The company is notorious for...", "id":"d8thecompanyisnotoriousfor", "roll":[
"Taking no prisoners.",
"Scarring or branding prisoners.",
"Incompetence.",
"Cowardice.",
"Singing bawdy songs.",
"Romantic escapades.",
"Eating everything that is available.",
"Drinking too much ale and wine.",
]},
{"title": "d6 Most soldiers in the company are outfitted with...", "id":"d6mostsoldiersinthecompanyareoutfittedwith", "roll":[
"Patched leather armor.",
"Leather armor marked with the symbol of their liege lord.",
"Helms and breastplates emblazoned with the symbol of their liege lord.",
"Well-maintained chainmail.",
"Well-worn scale armor.",
"Newly-forged scale armor.",
]},
{"title": "d12 Most soldiers in the company are equipped with...", "id":"d12mostsoldiersinthecompanyareequippedwith", "roll":[
"Longswords and short bows.",
"Longswords and crossbows.",
"Longswords and shields.",
"Short swords and longbows.",
"Short swords and shields.",
"Mornngstars and crossbows.",
"Battleaxes and handaxes.",
"Warhammers and shields.",
"Spears and shields.",
"Longspears and shortswords.",
"Pikes and shortswords.",
"Halberds and handaxes.",
]},
{"title": "d8 Most soldiers in the company are...", "id":"d8mostsoldiersinthecompanyare", "roll":[
"Trained men-at-arms.",
"Militia men.",
"Veterans of war.",
"Prisoners of war.",
"Conscripts from a city.",
"Conscripts from peasant villages.",
"Convicted criminals.",
"Green boys.",
]},
{"title": "d12 The soldier is...", "id":"d12thesoldieris", "roll":[
"A farm boy.",
"The son of a miner or fisherman.",
"A veteran of gladiatorial combat.",
"A veteran of warfare.",
"A prisoner of war.",
"A political dissident.",
"The son of a poor man.",
"A drunk.",
"A fugitive criminal.",
"A former pirate.",
"A failed craftsman.",
"A favorite among the ladies.",
]},
{"title": "d12 The soldier fights for...", "id":"d12thesoldierfightsfor", "roll":[
"The steady pay.",
"The love of someone he cannot have.",
"Pure bloodlust.",
"A chance to deal out sadistic torment.",
"A chance at vengeance.",
"Gold to repay debts.",
"Gold to aid a family member.",
"A chance to escape from life imprisonment.",
"A chance at redemption.",
"God and country.",
"Fortune and glory.",
"Strength and honor.",
]},
{"title": "d12 On the soldier’s face is...", "id":"d12onthesoldiersfaceis", "roll":[
"A large wart.",
"An eyepatch.",
"An unsightly scar.",
"A haughty sneer.",
"A look of sadness.",
"A stupid grin.",
"An eager grin.",
"A frame of long, beautiful long hair.",
"Ferocious sideburns.",
"A neatly-trimmed goatee.",
"An unruly beard.",
"A lush, thick mustache.",
]},
{"title": "d10 The soldier carries...", "id":"d10thesoldiercarries", "roll":[
"A blade with soft leather tassels dangling from the pommel.",
"A blade with a carved hilt (d6): 1. ivory; 2. jade; 3. soapstone; 4. ebony; 5. mahogany; 6. oak.",
"A blade with beasts sculpted into the steel of the guard (d6): 1. dragons; 2. lions; 3. scorpions; 4. snakes; 5. spiders; 6. wolves.",
"A blade made of blackened steel.",
"A highly polished blade.",
"A token from a sweetheart.",
"A token from a parent.",
"A letter from a fallen comrade.",
"A trophy from a fallen enemy.",
"A ribbon from a faraway maiden.",
]},
{"title": "d6 The house is...", "id":"d6thehouseis", "roll":[
"Ancient and well-respected by all houses, great and small.",
"Ancient and greatly diminished in standing from what it once was.",
"Old with the respect of many houses, great and small.",
"Old and struggling to maintain respect of other houses.",
"Old but often overshadowed by other houses.",
"Newly raised up to the nobility.",
]},
{"title": "d20 The house's colors are...", "id":"d20thehousescolorsare", "roll":[
"Black.",
"Red / scarlet.",
"Gold.",
"Forest green.",
"Royal blue.",
"Violet.",
"Silver / light grey.",
"Bronze.",
"Tan / khaki.",
"Brown / beaver.",
"Dark grey / gunmetal.",
"White.",
"Maroon.",
"Sky blue.",
"Navy blue.",
"Dark brown / chocolate.",
"Teal / turquoise.",
"Yellow.",
"Orange.",
"Olive green.",
]},
{"title": "d8 The house's symbol is...", "id":"d8thehousessymbolis", "roll":[
"A weapon (d8): 1. arrow; 2. axe; 3. dagger; 4. hammer; 5. mace; 6. spear; 7. staff; 8. sword.",
"A piece of armor (d4): 1. breastplate; 2. gauntlet; 3. helm; 4. shield.",
"A celestial body (d4): 1. sun; 2. moon; 3. star; 4. comet.",
"A plant or part of a plant (d12): 1. apple; 2. barley; 3. briar; 4. fig; 5. grapes; 6. lily; 7. maple; 8. oak; 9. olive; 10. pine; 11. rose; 12. wheat.",
"An aquatic beast (d6): 1. crab; 2. crocodile; 3. frog; 4. fish; 5. octopus; 6. whale.",
"A small beast (d12): 1. badger; 2. bat; 3. beaver; 4. dog; 5. ferret; 6. fox; 7. hedgehog; 8. lizard; 9. rat; 10. scorpion; 11. snake; 12. spider.",
"A great beast (d8): 1. bear; 2. boar; 3. bull; 4. dragon; 5. lion; 6. ox; 7. stag; 8. wolf.",
"A bird (d12): 1. cardinal; 2. dove; 3. eagle; 4. hawk; 5. mockingbird; 6. owl; 7. pelican; 8. raven; 9. rooster; 10. sparrow; 11. swan; 12. vulture.",
]},
{"title": "d20 The house's motto champions the ideals of...", "id":"d20thehousesmottochampionstheidealsof", "roll":[
"Compassion.",
"Courage.",
"Courtesy.",
"Determination.",
"Discipline.",
"Duty.",
"Excellence.",
"Faith.",
"Generosity.",
"Honor.",
"Hope.",
"Integrity.",
"Justice.",
"Loyalty.",
"Mercy.",
"Patience.",
"Righteousness.",
"Strength.",
"Trust.",
"Wisdom.",
]},
{"title": "d12 The best known member of the house is or was...", "id":"d12thebestknownmemberofthehouseisorwas", "roll":[
"A gallant knight.",
"A beautiful woman.",
"A ruthless negotiator.",
"An adept diplomat.",
"A famous traveler or explorer.",
"A brilliant military strategist.",
"A notorious rebel or outlaw.",
"A dashing swashbuckler.",
"A fearsome warrior.",
"A brilliant scholar.",
"A gifted orator.",
"A dangerous and mad ruler.",
]},
{"title": "d10 The current head of the house is...", "id":"d10thecurrentheadofthehouseis", "roll":[
"A kindly old man or woman.",
"A ruthless old man or woman.",
"A wily old man or woman.",
"A charming man or woman.",
"A grim veteran of wars.",
"An astute politician.",
"A devout adherent of a religion.",
"A heartbroken widower or widow.",
"A reckless or hot-headed young man or woman.",
"A child.",
]},
{"title": "d8 The house's goals include (individual members may have different goals)...", "id":"d8thehousesgoalsincludeindividualmembersmayhavedifferentgoals", "roll":[
"Domination of the city or region's politics.",
"Domination of the city or region's trade.",
"Revenge against a rival house in the same city or region.",
"Revenge against a rival house in another city or region.",
"Sabotage of a group run by commoners—a guild, academy, religious faith, or secret society.",
"Fomenting rebellion against the city or region's ruling house.",
"Marriage with a powerful allied house.",
"Marriage with a powerful rival house.",
]},
{"title": "d8 One or more house members keep secret (the secret may involve past or present events)...", "id":"d8oneormorehousememberskeepsecretthesecretmayinvolvepastorpresentevents", "roll":[
"A long-time scandalous romance.",
"The existence of a bastard child.",
"A murder in one of the house's keeps, castles, or palaces.",
"Religious zealotry.",
"The birth of a malformed freak.",
"Treason against the region's sovereign.",
"The senility or madness of family members.",
"Criminal sabotage of a rival house.",
]},
{"title": "d10 The house's seat of power is located in or near...", "id":"d10thehousesseatofpowerislocatedinornear", "roll":[
"A port city.",
"A range of high mountains.",
"A wide, fertile plain.",
"A fertile river valley.",
"An ancient forest.",
"A jagged coastline.",
"A sodden swamp.",
"A pristine lake.",
"A desert plateau.",
"An idyllic hill country.",
]},
{"title": "d6 The noble is...", "id":"d6thenobleis", "roll":[
"A knight.",
"An old lord.",
"A young lord.",
"An old lady.",
"A young lady.",
"A wealthy merchant.",
]},
{"title": "d8 The noble seeks someone to...", "id":"d8thenobleseekssomeoneto", "roll":[
"Dispose of an enemy.",
"Negotiate a trade contract.",
"Deliver a letter.",
"Prepare an army for war.",
"Sabotage a rival.",
"Secure an advantageous marriage for himself or herself.",
"Secure an advantageous marriage for a friend or family member.",
"Have a good time with.",
]},
{"title": "d6 The noble carries...", "id":"d6thenoblecarries", "roll":[
"Several deeds and titles.",
"A family heirloom.",
"Several inventories and invoices.",
"Some very valuable jewels.",
"A compromising love letter.",
"A letter from a powerful lord or lady.",
]},
{"title": "d8 The noble wears…", "id":"d8thenoblewears", "roll":[
"A flashy gold necklace or chain.",
"Shiny leather boots.",
"An ornate signet ring.",
"Fine silk clothes.",
"A handsome grin.",
"An extremely ugly scowl.",
"An arrogant sneer.",
"Beautifully-styled hair and/or facial hair.",
]},
{"title": "d8 The noble has…", "id":"d8thenoblehas", "roll":[
"A loud, deep laugh.",
"A high-pitched laugh.",
"A twittering nervous laugh.",
"A nervous habit of fidgeting.",
"A silver tongue.",
"A commanding presence.",
"Complete disregard for commoners.",
"Not a care in the world.",
]},
{"title": "d10 The outlaw band’s primary “business” involves...", "id":"d10theoutlawbandsprimarybusinessinvolves", "roll":[
"Poaching from the sovereign's preserve or a prominent noble’s lands.",
"Harboring fugitives.",
"Harassing government officials and nobles who pass along the road.",
"Robbing caravans carrying gems, precious metals, and exotic goods.",
"Holding up incoming or outgoing ships or wagons.",
"Smuggling drugs (d4): 1. smokeleaf; 2. hallucinogenic mushrooms; 3. sleepysalt (a downer); 4. sharpsugar (an upper).",
"Smuggling rare antiquities.",
"Smuggling stolen goods.",
"Smuggling living things (d4): 1. exotic beasts; 2. foreign harlots; 3. fugitives; 4. slaves.",
"Serving as muscle for shady merchants and/or brothel-keepers.",
]},
{"title": "d10 The outlaw band’s colors are...", "id":"d10theoutlawbandscolorsare", "roll":[
"Black.",
"Gold.",
"Forest green.",
"Bronze.",
"Tan / khaki.",
"Brown / beaver.",
"Dark grey / gunmetal.",
"Maroon.",
"Dark brown / chocolate.",
"Olive green.",
]},
{"title": "d12 The outlaw band’s symbol is...", "id":"d12theoutlawbandssymbolis", "roll":[
"A skull.",
"An arrow.",
"A dagger.",
"A goblet.",
"The moon.",
"A star.",
"A snake.",
"A badger.",
"A spider.",
"A rat.",
"A wolf.",
"A bear.",
]},
{"title": "d12 The outlaw band’s leader is...", "id":"d12theoutlawbandsleaderis", "roll":[
"A dangerous megalomaniac.",
"A charismatic demagogue.",
"A mysterious foreigner.",
"A talented thief.",
"A member of a prominent family.",
"A ruthless killer.",
"A femme fatale.",
"A charming rogue.",
"A dashing swashbuckler.",
"A brutish thug.",
"A devoted priest.",
"A well-known fugitive.",
]},
{"title": "d6 The outlaw band’s members are primarily...", "id":"d6theoutlawbandsmembersareprimarily", "roll":[
"Out-of-work artisans.",
"Displaced peasants.",
"Desperate peasants.",
"Escaped slaves.",
"Combat veterans.",
"Foreign refugees.",
]},
{"title": "d8 The outlaw band’s goals include (leadership and rank-and-file members could have different goals)...", "id":"d8theoutlawbandsgoalsincludeleadershipandrankandfilememberscouldhavedifferentgoals", "roll":[
"Domination of the region’s trade.",
"Sabotage of the region’s trade.",
"Revenge against a rival band of outlaws.",
"Revenge against the region’s elite.",
"Rebellion against the region’s elite.",
"Equality and freedom for all.",
"A wealthy and peaceful retirement.",
"Violence to slake their bloodlust.",
]},
{"title": "d10 Members of the outlaw band typically arm themselves with...", "id":"d10membersoftheoutlawbandtypicallyarmthemselveswith", "roll":[
"Wooden clubs.",
"Over-sized daggers.",
"Shortbows and arrows.",
"Longbows and arrows.",
"Daggers and crossbows.",
"Axes and knives.",
"Sticks and stones.",
"Shortswords.",
"Brass knuckles.",
"Daggers and sling shots.",
]},
{"title": "d10 The outlaw band’s headquarters is hidden in or near...", "id":"d10theoutlawbandsheadquartersishiddeninornear", "roll":[
"The residence of a prominent noble.",
"The village’s market square.",
"A wayside inn.",
"A tavern.",
"A brothel.",
"An old lighthouse.",
"An abandoned cabin.",
"A waterfall.",
"A cave.",
"A dense forest.",
]},
{"title": "d10 The outlaw band is feared or respected by...", "id":"d10theoutlawbandisfearedorrespectedby", "roll":[
"Ambassadors and tax collectors.",
"Merchants and peddlers.",
"Politicians and magistrates.",
"Guards and sheriffs.",
"Soldiers and warriors.",
"Nobles and wealthy travelers.",
"Knights and loyalists.",
"Peasants and farmers.",
"Priests and sages.",
"Women and children.",
]},
{"title": "d12 Distinguishing feature for an individual: The outlaw has...", "id":"d12distinguishingfeatureforanindividualtheoutlawhas", "roll":[
"A flashy earring ring.",
"Shiny leather boots.",
"A hole in the toe of one boot.",
"A dagger in each boot.",
"A mask on the face.",
"A wide-brimmed hat.",
"A dragon tattoo on the forearm.",
"A flame tattoo around the arm.",
"A maniacal laugh.",
"A bent, broken nose.",
"An open shirt and a very hairy chest.",
"Extravagant mustaches.",
]},
{"title": "d8. The poachers’ favorite prey includes...", "id":"d8thepoachersfavoritepreyincludes", "roll":[
"Bears.",
"Birds of prey (d4): 1. eagles; 2. falcons; 3. hawks; 4. owls.",
"Boars.",
"Deer (d4): 1. elk; 2. harts; 3. moose; 4. stags.",
"Exotic beasts (d8): 1. behemoths; 2. elephants; 3. griffons; 4. hippogriffs; 5. lions; 6. owl bears; 7. tigers; 8. wyverns).",
"Game birds (d6): 1. doves; 2. grouses; 3. partridges; 4. pheasants; 5. quails; 6. turkeys.",
"Waterfowl (d6): 1. ducks; 2. geese; 3. herons; 4. puffins; 5. snipes; 6. swans.",
"Small furry beasts (d6): 1. beavers; 2. ermines; 3. otters; 4. raccoons; 5. sables; 6. skunks.",
"Small predators (d4): 1. badgers; 2. coyotes; 3. foxes; 4. wolverines.",
"Wolves.",
]},
{"title": "d6. The poachers’ hunt...", "id":"d6thepoachershunt", "roll":[
"For sport.",
"To feed their families.",
"To feed the impoverished peasants.",
"To exact revenge on the landowner.",
"To sell the beasts’ meat.",
"To sell the beasts’ pelts.",
]},
{"title": "d6 The robbers typically strike with...", "id":"d6therobberstypicallystrikewith", "roll":[
"Swarm tactics.",
"Hit-and-run tactics.",
"Ambush tactics.",
"Choreographed maneuvers.",
"Unpredictable maneuvers.",
"Lots of fancy footwork.",
]},
{"title": "d8 The robbers are notorious for...", "id":"d8therobbersarenotoriousfor", "roll":[
"Never leaving survivors.",
"Branding captives.",
"Scalping captives.",
"Burning wagons and ships.",
"Using explosives.",
"Romantic escapades.",
"Singing bawdy songs.",
"Drinking too much ale.",
]},
{"title": "d6 The smuggling ring's primary modus operandi involves...", "id":"d6thesmugglingringsprimarymodusoperandiinvolves", "roll":[
"Underground tunnels.",
"Secret compartments.",
"Stealth watercraft.",
"Humanoid mules.",
"Bribery of officials.",
"A network of safehouses.",
]},
{"title": "d8 The ring is supported by...", "id":"d8theringissupportedby", "roll":[
"A prominent merchant.",
"An important minister or magistrate.",
"A major crime boss.",
"A pirate captain.",
"An admiral.",
"A group of subversives.",
"The captain of the guard or a local sheriff.",
"The sovereign’s main rival.",
]},
{"title": "d10 The pirates' ship is...", "id":"d10thepiratesshipis", "roll":[
"Little more than a raft.",
"A galley.",
"A longship.",
"A catamaran.",
"A cog.",
"A hulk.",
"A carrack.",
"A caravel.",
"A schooner.",
"A dreadnought.",
]},
{"title": "d8 Presently, the pirates’ ship is...", "id":"d8presentlythepiratesshipis", "roll":[
"Laden with treasure.",
"Full of stolen goods.",
"Well-stocked with provisions.",
"In tip-top shape.",
"“On loan” to some other pirates.",
"In need of repair.",
"Barely staying afloat.",
"Resting beneath the waves.",
]},
{"title": "d20 The ship's banner features...", "id":"d20theshipsbannerfeatures", "roll":[
"A skull.",
"A pair of crossed bones.",
"A skull and cross bones.",
"A skeletal hand.",
"A skeletal fish.",
"A flaming skull.",
"A clenched fist.",
"A ghost.",
"A mermaid.",
"A pair of crossed cutlasses.",
"A dagger.",
"A bloody dagger.",
"An albatross.",
"A pelican.",
"A whale.",
"An octopus.",
"A swordfish.",
"A crab.",
"A sea turtle.",
"A big tuna.",
]},
{"title": "d20 The ship's mascot is...", "id":"d20theshipsmascotis", "roll":[
"A parrot",
"A parrot",
"A parrot",
"A parrot",
"A budgie (fond of saying \"Ye scalawags!\" or \"Aye, Captain!\").",
"A cockatoo (fond of saying \"Pieces of eight!\" or \"It's shark week!\").",
"A conure (fond of saying \"Dead men tell no tales!\" or \"Ahoy!\").",
"A macaw (fond of saying \"Show me the booty!\" or \"Land, ho!\"). ",
"A monkey",
"A monkey",
"A monkey",
"A monkey",
"A capuchin monkey (with or without an eyepatch).",
"A macaque (with or without a vest).",
"A spider monkey (with or without a bandanna).",
"A tamarin (with or without mustaches).",
"An old turtle.",
"A lazy sea-faring cat.",
"A pot-belly pig.",
"A high-energy herding dog.",
]},
{"title": "d10 The ship's captain is...", "id":"d10theshipscaptainis", "roll":[
"A dangerous megalomaniac.",
"A charismatic demagogue.",
"A mysterious foreigner.",
"A talented thief.",
"A member of a prominent family.",
"A ruthless killer.",
"A femme fatale.",
"A charming rogue.",
"A dashing swashbuckler.",
"A brutish thug.",
"An old sailor.",
"A celebrated naval hero.",
]},
{"title": "d8 The crew's attitude toward their captain is...", "id":"d8thecrewsattitudetowardtheircaptainis", "roll":[
"Adoring and loyal.",
"Friendly and pleased.",
"Respectful and business-like.",
"Mercenary and eager.",
"Terrified and tight-lipped.",
"Disappointed and indifferent.",
"Restless and rebellious.",
"Angry and mutinous.",
]},
{"title": "d10 Crewmembers often sport matching...", "id":"d10crewmembersoftensportmatching", "roll":[
"Puffy shirts.",
"Breeches.",
"Scarves.",
"Vests.",
"Bandannas.",
"Boots.",
"Tattoos.",
"Hats.",
"Scars.",
"Mustaches.",
]},
{"title": "d8 The crew's goals include (captain and crewmembers could have different goals)...", "id":"d8thecrewsgoalsincludecaptainandcrewmemberscouldhavedifferentgoals", "roll":[
"Discovery of a legendary hidden treasure.",
"Domination of the region's maritime trade.",
"Revenge against a naval hero.",
"Revenge against a rival pirate crew.",
"Rebellion against the dominant merchant traders.",
"A wealthy and peaceful retirement.",
"Violence to slake their bloodlust.",
"Drinking all the rum.",
]},
{"title": "d10 Crewmembers typically arm themselves with...", "id":"d10crewmemberstypicallyarmthemselveswith", "roll":[
"Belaying pins (wooden clubs).",
"Throwing knives.",
"Over-sized daggers.",
"Serrated daggers.",
"Cutlasses.",
"Clubs and daggers.",
"Brass knuckles.",
"Bare fists.",
"Nets and tridents.",
"Harpoons.",
]},
{"title": "d10 The pirate crew typically fights with...", "id":"d10thepiratecrewtypicallyfightswith", "roll":[
"Swarm tactics.",
"Hit-and-run tactics.",
"Ambush tactics.",
"Choreographed maneuvers.",
"Unpredictable maneuvers.",
"Lots of smiles and jokes.",
"Lots of fancy footwork.",
"Lots of screaming and shouting.",
"Kicking and stomping.",
"Lots of head-butting.",
]},
{"title": "d10 The crew's headquarters is hidden in or near...", "id":"d10thecrewsheadquartersishiddeninornear", "roll":[
"A rugged seaside cliff.",
"A hidden lagoon.",
"A remote island.",
"A swampy river mouth.",
"A coastal cave.",
"A tavern.",
"A brothel.",
"A warehouse or shipyard.",
"A poor fishing village",
"An old lighthouse.",
]},
{"title": "d12 The crew is notorious for...", "id":"d12thecrewisnotoriousfor", "roll":[
"Never leaving survivors.",
"Feeding captives to sharks.",
"Tattooing or branding captives.",
"Scalping captives.",
"Flaying captives.",
"Burning seaside villages.",
"Plundering the ships of a wealthy tyrant.",
"Using a lot of explosives.",
"Convening with ghosts.",
"Romantic escapades.",
"Singing bawdy songs.",
"Drinking too much rum.",
]},
{"title": "d12 Tattoo: The pirate has...", "id":"d12tattoothepiratehas", "roll":[
"A dagger tattoo.",
"An anchor tattoo.",
"A skull tattoo.",
"A pair of crossed bones tattoo.",
"A snake tattoo.",
"A fish tattoo.",
"A spider web tattoo.",
"An octopus tattoo.",
"A whale tattoo.",
"A lobster tattoo.",
"A mermaid tattoo.",
"A dragon tattoo.",
]},
{"title": "d12 Distinguishing feature: The pirate has...", "id":"d12distinguishingfeaturethepiratehas", "roll":[
"A nose ring.",
"Shiny leather boots.",
"Gold teeth.",
"An oversized dagger in the belt.",
"A heavy gold chain around the neck.",
"A wide-brimmed hat.",
"An eyepatch.",
"A long black beard.",
"A maniacal laugh.",
"A long, hooked nose.",
"An open shirt and a very hairy chest.",
"Extravagant mustaches.",
]},
{"title": "d6 The barbarians are...", "id":"d6thebarbariansare", "roll":[
"A tribe of nomads, following game.",
"A tribe that began raiding after being displaced from their native lands.",
"A clan exiled from their native lands.",
"A clan in the service of a sovereign.",
"A confederacy of related tribes or clans.",
"The degenerate survivors of a broken army.",
]},
{"title": "d6 The barbarians travel...", "id":"d6thebarbarianstravel", "roll":[
"On foot.",
"On foot with small carts.",
"On foot with mounted scouts.",
"On mounts.",
"On mounts with wagons.",
"In small watercraft.",
]},
{"title": "d8 The barbarians value...", "id":"d8thebarbariansvalue", "roll":[
"Bravery.",
"Strength.",
"Wisdom.",
"Virility.",
"Honoring the gods.",
"Honoring their ancestors.",
]},
{"title": "d4 The barbarians’ iconography features...", "id":"d4thebarbariansiconographyfeatures", "roll":[
"Symbols of death and destruction (d8): 1. bats; 2. bones; 3. crows; 4. flames; 5. ghosts; 6. scorpions; 7. skulls; 8. vultures.",
"Symbols of the heavens (d6): 1. clouds; 2. lightning; 3. moon; 4. snow; 5. stars; 6. sun.",
"Symbols of strength and weaponry (d6): 1. arrows; 2. axes; 3. fists; 4. spears; 5. stones; 6. swords.",
"Totem beasts (d8): 1. bears; 2. boars; 3. eagles; 4. horses; 5. lions; 6. owls; 7. snakes; 8. wolves.",
]},
{"title": "d10 The barbarians’ leader is...", "id":"d10thebarbariansleaderis", "roll":[
"A well-respected chief.",
"A charismatic warlord.",
"A mysterious prophet.",
"A descendent of an honored hero.",
"A ruthless killer.",
"A brutish thug.",
"An impatient young warrior.",
"A wise old man.",
"A celebrated war hero.",
"A prolific lover.",
]},
{"title": "d10 The barbarians fear...", "id":"d10thebarbariansfear", "roll":[
"Foreigners wearing a particular color of clothing (d8): 1. red; 2. gold; 3. green; 4. blue; 5. purple; 6. white; 7. black; 8. grey.",
"Foreigners armored in steel.",
"Foreigners with facial hair.",
"Foreign women.",
"All foreigners.",
"Members of a particular race (d4): 1. dwarves; 2. elves; 3. goblinoids; 4. reptilian humanoids.",
"A particular natural phenomenon (d6): 1. blizzards; 2. earthquakes; 3. floods; 4. thunderstorms; 5. volcanoes; 6. typhoons.",
"Spellcasters.",
"The gods.",
"Dragons.",
]},
{"title": "d10 The barbarians are notorious for...", "id":"d10thebarbariansarenotoriousfor", "roll":[
"Never leaving survivors.",
"Feeding prisoners to wild beasts.",
"Tattooing or branding prisoners.",
"Scalping enemies.",
"Flaying enemies.",
"Raiding and burning villages.",
"Plundering merchant caravans.",
"Eating prisoners.",
"Claiming prisoners as slaves.",
"Taking prisoners as wives, concubines, or catamites.",
]},
{"title": "d10 The barbarians are known for...", "id":"d10thebarbariansareknownfor", "roll":[
"Screaming and shouting during battle.",
"Convening with ghosts and spirits.",
"Ritual animal sacrifice.",
"Ritual human sacrifice.",
"Ritualistic blood-letting.",
"Ritualistic sexual acts.",
"Eating unusual meats.",
"Prolific amounts of drinking.",
"Never cutting their hair.",
"Shaving their heads and bodies.",
"Never bathing.",
"Bathing and perfuming their bodies.",
]},
{"title": "d6 The barbarians’ attitude is...", "id":"d6thebarbariansattitudeis", "roll":[
"Rowdy and festive.",
"Joyful and eager to fight.",
"Relaxed and carefree.",
"Frightened and suspicious.",
"Hostile and suspicious.",
"Hostile and eager to fight.",
]},
{"title": "d6 The society's main goal is to...", "id":"d6thesocietysmaingoalisto", "roll":[
"Foil the plans of another secret society.",
"Bring about the destruction of the city, region, or world.",
"Foment rebellion against the ruling class.",
"Hunt down and eliminate members of a specific race or class.",
"Protect the common people from tyranny.",
"Protect the city, region, or world from outside malign influences.",
]},
{"title": "d12 The society is led by...", "id":"d12thesocietyisledby", "roll":[
"A council who gain their seats by virtue of heredity.",
"A council who gain their seats by virtue of experience.",
"A council who gain their seats by elections.",
"A dangerous megalomaniac.",
"A femme fatale.",
"An altruistic knight.",
"A dashing rogue.",
"A religious zealot.",
"A wise old priest or mage.",
"A celebrated war hero.",
"A wealthy merchant or noble.",
"A fugitive from justice.",
]},
{"title": "d8 Members of the society recognize each other by...", "id":"d8membersofthesocietyrecognizeeachotherby", "roll":[
"A secret handshake.",
"A secret gesture.",
"A secret password.",
"A set of coded phrases and responses.",
"A subtle pin or piece of jewelry.",
"A subtle fashion or style of dress.",
"A cue specified by another member of the society.",
"The way society members style their facial hair.",
]},
{"title": "d20 The society's colors are...", "id":"d20thesocietyscolorsare", "roll":[
"Black.",
"Red / scarlet.",
"Gold.",
"Forest green.",
"Royal blue.",
"Violet.",
"Silver / light grey.",
"Bronze.",
"Tan / khaki.",
"Brown / beaver.",
"Dark grey / gunmetal.",
"White.",
"Maroon.",
"Sky blue.",
"Navy blue.",
"Dark brown / chocolate.",
"Teal / turquoise.",
"Yellow.",
"Orange.",
"Olive green.",
]},
{"title": "d10 The society's symbol is...", "id":"d10thesocietyssymbolis", "roll":[
"A weapon (d8): 1. arrow; 2. axe; 3. dagger; 4. hammer; 5. mace; 6. spear; 7. staff; 8. sword.",
"A piece of armor (d4): 1. breastplate; 2. gauntlet; 3. helm; 4. shield.",
"A celestial body (d4): 1. sun; 2. moon; 3. star; 4. comet.",
"A plant or part of a plant (d12): 1. apple; 2. barley; 3. briar; 4. fig; 5. grapes; 6. lily; 7. maple; 8. oak; 9. olive; 10. pine; 11. rose; 12. wheat.",
"An aquatic beast (d6): 1. crab; 2. crocodile; 3. frog; 4. fish; 5. octopus; 6. whale.",
"A small beast (d12): 1. badger; 2. bat; 3. beaver; 4. dog; 5. ferret; 6. fox; 7. hedgehog; 8. lizard; 9. rat; 10. scorpion; 11. snake; 12. spider.",
"A great beast (d8): 1. bear; 2. boar; 3. bull; 4. dragon; 5. lion; 6. ox; 7. stag; 8. wolf.",
"A bird (d12): 1. cardinal; 2. dove; 3. eagle; 4. hawk; 5. mockingbird; 6. owl; 7. pelican; 8. raven; 9. rooster; 10. sparrow; 11. swan; 12. vulture.",
"An elemental rune or image (d8): 1. cloud; 2. flame; 3. ice; 4. lightning bolt; 5. snow; 6. stone; 7. wave of water; 8. whirlwind.",
"An icon of death (d4): 1. a pair of crossed bones; 2. a ghost; 3. a skull; 4. a spectral hand.",
]},
{"title": "d20 The society's motto champions the ideals of...", "id":"d20thesocietysmottochampionstheidealsof", "roll":[
"Compassion.",
"Courage.",
"Discipline.",
"Domination.",
"Duty.",
"Excellence.",
"Faith.",
"Honor.",
"Hope.",
"Integrity.",
"'Knowledge",
"Justice.",
"Loyalty.",
"Mercy.",
"Patience.",
"Power.",
"Righteousness.",
"Strength.",
"Victory.",
"Wisdom.",
]},
{"title": "d6 Members of the society typically operate...", "id":"d6membersofthesocietytypicallyoperate", "roll":[
"Alone and in secret.",
"In pairs, working in secret.",
"In small groups, working in secret.",
"Alone, but openly.",
"In pairs, but openly.",
"In small groups, but openly.",
]},
{"title": "d6 Members of the society typically know...", "id":"d6membersofthesocietytypicallyknow", "roll":[
"Very few other members of the society.",
"Several other members of the society.",
"The details of the society's organization.",
"Nothing about the society's leadership.",
"The names of the society's leaders, though they’ve never any of them.",
"One of the society's leading members and no other members.",
]},
{"title": "d12 Members of the society occasionally gather to meet in...", "id":"d12membersofthesocietyoccasionallygathertomeetin", "roll":[
"A secret chamber in a well-known temple.",
"The cellar of a popular tavern.",
"A secret chamber in a well-known guild-hall.",
"The cellar of a wealthy merchant's house.",
"The city sewers.",
"The ancient catacombs beneath the city.",
"The residence of the leader or a senior member.",
"A wealthy merchant's office.",
"A private dining room in a dingy tavern.",
"A brothel.",
"A warehouse or shipyard.",
"The city's sewers.",
]},
{"title": "d8 The society's membership is primarily made up of...", "id":"d8thesocietysmembershipisprimarilymadeupof", "roll":[
"The poor and downtrodden (slaves, beggars, urchins, laborers, servants, etc.).",
"The wealthy elite (merchants, nobles, etc.).",
"Members of a particular religion (a temple, a cult, a sect, etc.).",
"Members of a particular trade (blacksmiths, carpenters, fishermen, weavers, etc.).",
"Members of a particular class (bards, fighters, mages, priests, rangers, thieves, etc.)",
"Members of a particular race (dwarves, elves, gnomes, halflings, etc.).",
"Members of specific ancient lineages (noble houses, descendants of heroes, etc.)",
"An eclectic mix of society.",
]},
{"title": "d8 The gang's money-making schemes include...", "id":"d8thegangsmoneymakingschemesinclude", "roll":[
"Distributing drugs (d4): 1. smokeleaf; 2. hallucinogenic mushrooms; 3. sleepysalt (a downer); 4. sharpsugar (an upper).",
"Running heists of and/or fencing stolen gems and precious metals.",
"Petty theft, burglary, and/or pickpocketing.",
"Assassinations that look like accidents or that frame someone else.",
"Running brothels (d3): 1. exotic; 2. low; 3. high-class.",
"Shaking down legitimate local businesses and/or city officials.",
"Serving as muscle for shady merchants and/or brothel-keepers.",
"Holding up outgoing ships or wagons.",
]},
{"title": "d20 The gang's colors are...", "id":"d20thegangscolorsare", "roll":[
"Black.",
"Red / scarlet.",
"Gold.",
"Forest green.",
"Royal blue.",
"Violet.",
"Silver / light grey.",
"Bronze.",
"Tan / khaki.",
"Brown / beaver.",
"Dark grey / gunmetal.",
"White.",
"Maroon.",
"Sky blue.",
"Navy blue.",
"Dark brown / chocolate.",
"Teal / turquoise.",
"Steel / blue grey.",
"Orange.",
"Olive green.",
]},
{"title": "d20 The gang's symbol is...", "id":"d20thegangssymbolis", "roll":[
"A skull.",
"A ghost.",
"An open hand.",
"A clenched fist.",
"An arrow.",
"A dagger.",
"A sword.",
"A hammer.",
"A crown.",
"A goblet.",
"The moon.",
"A star.",
"A fish.",
"A snake.",
"A badger.",
"A spider.",
"A rat.",
"A wolf.",
"A bear.",
"An eagle.",
]},
{"title": "d10 Gang members often sport matching...", "id":"d10gangmembersoftensportmatching", "roll":[
"Shirts.",
"Jackets.",
"Scarves.",
"Vests.",
"Bandannas.",
"Boots.",
"Tattoos.",
"Hats.",
"Scars.",
"Mustaches.",
]},
{"title": "d10 The gang's leader is...", "id":"d10thegangsleaderis", "roll":[
"A dangerous megalomaniac.",
"A charismatic demagogue.",
"A mysterious foreigner.",
"A talented thief.",
"A well-known public figure.",
"A ruthless killer.",
"A femme fatale.",
"A charming rogue.",
"A dashing swashbuckler.",
"A brutish thug.",
]},
{"title": "d12 For recruitment, the gang targets individuals who are...", "id":"d12forrecruitmentthegangtargetsindividualswhoare", "roll":[
"Artisans.",
"Relocated peasants.",
"Sailors.",
"Drunks.",
"Beggars.",
"Thieves.",
"Servants and slaves.",
"Combat veterans.",
"Laborers.",
"Foreigners.",
"Young children.",
"Circus performers.",
]},
{"title": "d6 The gang's goals include (leadership and rank-and-file members could have different goals)...", "id":"d6thegangsgoalsincludeleadershipandrankandfilememberscouldhavedifferentgoals", "roll":[
"Domination of the city's politics.",
"Domination of the city's trade.",
"Revenge against a rival gang in the same city.",
"Revenge against a rival gang in another city.",
"Revenge against the city's elite.",
"Rebellion against the city's elite.",
]},
{"title": "d10 Gang members typically arm themselves with...", "id":"d10gangmemberstypicallyarmthemselveswith", "roll":[
"Wooden clubs.",
"Throwing knives.",
"Over-sized daggers.",
"Serrated daggers.",
"Daggers and crossbows.",
"Hammers and daggers.",
"Sticks and stones.",
"Shortswords.",
"Brass knuckles.",
"Bare fists.",
]},
{"title": "d10 Gang members typically fight with...", "id":"d10gangmemberstypicallyfightwith", "roll":[
"Swarm tactics.",
"Hit-and-run tactics.",
"Ambush tactics.",
"Choreographed maneuvers.",
"Unpredictable maneuvers.",
"Lots of smiles and jokes.",
"Lots of fancy footwork.",
"Lots of screaming and shouting.",
"Kicking and stomping.",
"Lots of head-butting.",
]},
{"title": "d12 The gang's headquarters is hidden in or near...", "id":"d12thegangsheadquartersishiddeninornear", "roll":[
"The residence of the leader or a senior gang member.",
"An artisan's shop or guildhall.",
"A merchant's office.",
"A tavern.",
"A brothel.",
"A warehouse or shipyard.",
"A temple complex.",
"The city's sewers.",
"The town hall.",
"An abandoned guildhall or warehouse.",
"A shantytown",
"The residence of a wealthy individual.",
]},
{"title": "d12 The gang is feared or respected by...", "id":"d12thegangisfearedorrespectedby", "roll":[
"Fishermen and sailors.",
"Beggars and thieves.",
"Merchants and moneychangers.",
"Jewelers and gem cutters.",
"Politicians and magistrates.",
"Guards and sheriffs.",
"Soldiers and warriors.",
"Gladiators and pugilists.",
"Peasants and farmers.",
"Servants and slaves.",
"Priests and sages.",
"Women and children.",
]},
{"title": "d12 Distinguishing feature for an individual: The gang member has...", "id":"d12distinguishingfeatureforanindividualthegangmemberhas", "roll":[
"A nose ring.",
"Shiny leather boots.",
"A hole in the toe of one boot.",
"A dagger in each boot.",
"A heavy gold chain around the neck.",
"A wide-brimmed hat.",
"A dagger tattoo on the forearm.",
"A snake tattoo around the arm.",
"A maniacal laugh.",
"A long, hooked nose.",
"An open shirt and a very hairy chest.",
"Extravagant mustaches.",
]},
{"title": "d12 The watch’s colors are...", "id":"d12thewatchscolorsare", "roll":[
"Black.",
"Red / scarlet.",
"Gold.",
"Forest green.",
"Royal blue.",
"Silver / light grey.",
"Brown / beaver.",
"White.",
"Maroon.",
"Sky blue.",
"Navy blue.",
"Dark brown / chocolate.",
]},
{"title": "d12 The watch’s symbol is...", "id":"d12thewatchssymbolis", "roll":[
"A flame.",
"A gauntlet.",
"A shield.",
"A sword.",
"The sun.",
"An eye.",
"An eagle.",
"An owl.",
"A dragon.",
"A lion.",
"A raven.",
"A wolf.",
]},
{"title": "d12 The watch’s captain is...", "id":"d12thewatchscaptainis", "roll":[
"A religious zealot.",
"A scion from a prominent family.",
"An outcast from a prominent family.",
"A dashing swashbuckler.",
"A brutish thug.",
"A celebrated war hero.",
"An anointed knight.",
"A career soldier.",
"A grizzled veteran.",
"An adept investigator.",
"An erudite detective.",
"A devoted public servant.",
]},
{"title": "d6 The watch’s attitude toward their captain is...", "id":"d6thewatchsattitudetowardtheircaptainis", "roll":[
"Friendly and loyal.",
"Respectful and business-like.",
"Completely indifferent.",
"Cautious and uncertain.",
"Terrified and tight-lipped.",
"Disappointed and disrespectful.",
]},
{"title": "d10 The watch has a reputation for...", "id":"d10thewatchhasareputationfor", "roll":[
"High morals.",
"Efficiency.",
"Reliability.",
"Brutality.",
"Taking bribes.",
"Shaking down shopkeepers and artisans.",
"Frequenting brothels.",
"Cowardice.",
"Incompetence.",
"Intoxication.",
]},
{"title": "d6 Most members of the watch are outfitted with...", "id":"d6mostmembersofthewatchareoutfittedwith", "roll":[
"Rough-spun wool cloaks.",
"Whatever armor they can find.",
"Leather armor marked with the symbol of the watch.",
"Leather armor marked with the symbol of their city or lord.",
"Helms and breastplates emblazoned with the symbol of their city or lord.",
"Well-maintained chainmail.",
]},
{"title": "d10 Most members of the watch are equipped with...", "id":"d10mostmembersofthewatchareequippedwith", "roll":[
"Longswords and shortbows.",
"Longswords and crossbows.",
"Longswords and shields.",
"Shortswords and shields.",
"Maces and crossbows.",
"Maces and shields.",
"Maces and daggers.",
"Pikes and shortswords.",
"Halberds and daggers.",
"Halberds and crossbows.",
]},
{"title": "d10 The constable is...", "id":"d10theconstableis", "roll":[
"A priest or monk.",
"A stoic monk.",
"A former soldier.",
"A mysterious foreigner.",
"A pompous windbag.",
"An accomplished scholar.",
"A violent drunk.",
"A criminal lackey.",
"A popular tavern patron.",
"Ruggedly handsome.",
]},
{"title": "d6 The constable works for...", "id":"d6theconstableworksfor", "roll":[
"The steady pay.",
"A chance to bring evil-doers to justice.",
"Gold to repay debts.",
"Gold to support his addiction (d4): 1. drinking; 2. gambling; 3. harlots; 4. smoking.",
"The joy of solving mysteries.",
"A chance for vengeance.",
]},
{"title": "d12 On the constable’s face is...", "id":"d12ontheconstablesfaceis", "roll":[
"A scar from a burn.",
"A jagged scar.",
"A hard-set jaw.",
"A friendly grin.",
"A faraway look.",
"A furrowed brow.",
"A pair of piercing eyes.",
"A broken nose.",
"Bushy eyebrows.",
"Unshaven stubble.",
"A neatly-trimmed beard.",
"An intimidating mustache.",
]},
{"title": "d10 The constable carries...", "id":"d10theconstablecarries", "roll":[
"A magnifying lens.",
"A blade with a carved hilt (d6): 1. ivory; 2. jade; 3. soapstone; 4. ebony; 5. mahogany; 6. oak.",
"A blade with beasts sculpted into the steel of the guard (d6): 1. dragons; 2. lions; 3. scorpions; 4. snakes; 5. spiders; 6. wolves.",
"A blade made of blackened steel.",
"An unusual hat.",
"A clue from an unsolved crime.",
"A token from a lost love.",
"Props for several disguises.",
"Alchemical reference manual.",
"A pocket-sized almanac.",
]},
{"title": "d10 The guard is...", "id":"d10theguardis", "roll":[
"A farm boy.",
"The son of a miner or fisherman.",
"A veteran of warfare.",
"A foreigner.",
"The son of a poor man.",
"A drunk.",
"A reformed criminal.",
"A thug.",
"A failed craftsman.",
"A favorite among the ladies.",
]},
{"title": "d6 The guard works for...", "id":"d6theguardworksfor", "roll":[
"The steady pay.",
"A chance to deal out sadistic punishment.",
"Gold to repay debts.",
"Gold to aid a family member.",
"A chance to escape from life imprisonment.",
"Patriotic devotion.",
]},
{"title": "d12 On the guard’s face is...", "id":"d12ontheguardsfaceis", "roll":[
"A large wart.",
"An unsightly scar.",
"A look of determination.",
"A foolish grin.",
"A stupid stare.",
"A look of confusion.",
"A bulbous nose.",
"Bushy eyebrows.",
"Fearsome sideburns.",
"An unruly beard.",
"A neatly-trimmed mustache.",
"A waxed mustache.",
]},
{"title": "d10 The guard carries...", "id":"d10theguardcarries", "roll":[
"A blade with soft leather tassels dangling from the pommel.",
"A blade with an inscription.",
"A highly polished blade.",
"A token from a favorite harlot.",
"A trophy from a criminal.",
"A ribbon from a noble maiden.",
"A silk handkerchief.",
"A flask of wine.",
"A lucky charm (d4): 1. rabbit’s foot; 2. old coin; 3. shiny coin; 4. four-leaf clover.",
"A grocery list.",
]},



// end of factions

];
