// food.js
//


top.food = [

// start of food






{"title": "d10 Tonight, at a mining town pub, we dine on...", "id":"d10tonightataminingtownpubwedineon", "roll":[
"Stewed.",
"Roasted.",
"Fried.",
"Smoked.",
"Baked.",
"Brined.",
"Seared.",
"Peppered.",
"Salted.",
"Pickled.",   ]},
 {"title": "d10 ...", "id":"d10mt", "roll":[
"Goat.",
"Chicken.",
"Blackbird.",
"Mutton.",
"Lamb.",
"Ram.",
"Ewe.",
"Pork.",
"Sausage.",
"Bacon.",   ]},
 {"title": "d12 ...with...", "id":"d12mtwith", "roll":[
"Golden potatoes.",
"Red potatoes.",
"Beets.",
"Leeks.",
"Lentils.",
"Red beans.",
"Black beans.",
"White beans.",
"Turnip mash.",
"Diced turnips.",
"White onions.",
"Yellow onions.",   ]},
 {"title": "d10 ...and...", "id":"d10mtand", "roll":[
"Carrots.",
"Red cabbage.",
"Green cabbage.",
"Purple cabbage.",
"Mushrooms.",
"Pine nuts.",
"Raisins.",
"Parsley.",
"Radishes.",
"Peas.",   ]},
 {"title": "d10 On the side, there is some...", "id":"d10mtonthesidethereissome", "roll":[
"Hard tack.",
"Fresh bread.",
"Crusty bread.",
"Rye bread.",
"Oat bread.",
"Pumpernickel bread.",
"Sharp cheese.",
"Stinky cheese.",
"Goat cheese.",
"Sheep's milk cheese.",   ]},
 {"title": "d10 To wash it down, we have some...", "id":"d10mttowashitdownwehavesome", "roll":[
"Bitter ale.",
"Wheat ale.",
"Black ale.",
"Stout.",
"Porter.",
"Mead.",
"Strong wine.",
"Red wine.",
"Brandy.",
"Whisky.",   ]},



 {"title": "d10 Tonight, at a hunters' lodge, we dine on...", "id":"d10tonightatahunterslodgewedineon", "roll":[
"Stewed.",
"Roasted.",
"Skewered.",
"Braised.",
"Smoked.",
"Grilled.",
"Seared.",
"Flame-broiled.",
"Salted.",
"Peppered.",   ]},
 {"title": "d20 ...", "id":"d20hl", "roll":[
"Rabbit.",
"Quail.",
"Duck.",
"Swan.",
"Boar.",
"Aurochs.",
"Pheasant.",
"Goose.",
"Trout.",
"Pike.",
"Clams.",
"Bear.",
"Venison.",
"Hare.",
"Beaver.",
"Wolf.",
"Squirrel.",
"Otter.",
"Hind.",
"Mockingbird.",   ]},
 {"title": "d12 ...with...", "id":"d12hlwith", "roll":[
"Potatoes.",
"Red cabbage.",
"White cabbage.",
"Leeks.",
"Lentils.",
"Rhubarb.",
"Peas.",
"Turnips.",
"Parsnips.",
"String beans.",
"Chives.",
"Onions.",   ]},
 {"title": "d12 ...and...", "id":"d12hland", "roll":[
"Carrots.",
"Apples.",
"Cherries.",
"Wild mushrooms.",
"Sliced mushrooms.",
"Black mushrooms.",
"Truffles.",
"Rosemary.",
"Sage.",
"Parsley.",
"Pine nuts.",
"Raisins.",   ]},
 {"title": "d12 On the side, there is some...", "id":"d12hlonthesidethereissome", "roll":[
"Rye bread.",
"Wheat bread.",
"Crusty bread.",
"Sesame bread.",
"Oat cake.",
"Pumpernickel bread.",
"Hard tack.",
"Dry flatbread.",
"Honey cake.",
"Deer sausage.",
"Boar's feet.",
"Sow's ear.",   ]},
 {"title": "d10 To wash it down, we have some...", "id":"d10hltowashitdownwehavesome", "roll":[
"Dark ale.",
"Pale ale.",
"Lager.",
"Stout.",
"Strong wine.",
"Sweet wine.",
"White wine.",
"Red wine.",
"Tea.",
"Whisky.",   ]},



{"title": "d8 Tonight, in an elvish dwelling, we dine on...", "id":"d8tonightinanelvishdwellingwedineon", "roll":[
"Stewed.",
"Roasted.",
"Boiled.",
"Simmered.",
"Smoked.",
"Baked.",
"Marinated.",
"Peppered.",   ]},
 {"title": "d12 ...", "id":"d12el", "roll":[
"Boar.",
"Rabbit.",
"Pheasant.",
"Goose.",
"Trout.",
"Pike.",
"Clams.",
"Chestnuts.",
"Wild rice.",
"Leafy greens.",
"White beans.",
"Red beans.",   ]},
 {"title": "d12 ...with...", "id":"d12elwith", "roll":[
"Green cabbage.",
"Sweet cabbage.",
"Wild arugula.",
"Wild rhubarb.",
"Sugarsnap peas.",
"Wild carrots.",
"Wild parsnips.",
"String beans.",
"Green onions.",
"Sweet onions.",
"Wild mushrooms.",
"Cave mushrooms.",   ]},
 {"title": "d12 ...and...", "id":"d12eland", "roll":[
"Apples.",
"Pears.",
"Lemons.",
"Rose petals.",
"Dandelions.",
"Flower petals.",
"Elder petals.",
"Red berries.",
"Black berries.",
"Blueberries.",
"Grapes.",
"Plums.",   ]},
 {"title": "d8 On the side, there is some...", "id":"d8elonthesidethereissome", "roll":[
"Crispy bread.",
"Fluffy bread.",
"Oat cake.",
"Honey cake.",
"Oat cake.",
"Flatbread.",
"Assorted fruit.",
"Assorted cheese.",   ]},
 {"title": "d12 To wash it down, we have some...", "id":"d12eltowashitdownwehavesome", "roll":[
"Spring water.",
"Sweet water.",
"Floral tea.",
"Strong tea.",
"Sweet wine.",
"Honey wine.",
"White wine.",
"Rosé.",
"Red wine.",
"Dark wine.",
"Ancient wine.",
"Young wine.",   ]},
 {"title": "d8 ...that leaves you feeling...", "id":"d8elthatleavesyoufeeling", "roll":[
"Refreshed.",
"Peaceful.",
"Content.",
"Carefree.",
"A little sleepy.",
"A little light-headed.",
"Rather nostalgic.",
"Rather melancholy.",   ]},



{"title": "d12 Tonight, in a dwarvish alehouse, we dine on...", "id":"d12tonightinadwarvishalehousewedineon", "roll":[
"Stewed.",
"Flame-roasted.",
"Glazed and skewered.",
"Braised.",
"Smoked.",
"Battered and fried.",
"Glazed and seared.",
"Flame-broiled.",
"Salted and grilled.",
"Peppered and grilled.",
"Stone oven-roasted.",
"Stone oven-baked.",   ]},
{"title": "d12 ...", "id":"d12dwarven", "roll":[
"Rabbit.",
"Duck.",
"Goose.",
"Boar.",
"Pork.",
"Ox.",
"Trout.",
"Salmon.",
"Venison.",
"Mutton.",
"Steak.",
"Pheasant.",   ]},
{"title": "d10 ...with...", "id":"d10dwwith", "roll":[
"Red potatoes.",
"Golden potatoes.",
"Red cabbage.",
"White cabbage.",
"Green cabbage.",
"Peas.",
"Sliced turnips.",
"Turnip mash.",
"White onions.",
"Red onions.",   ]},
{"title": "d10 ...and...", "id":"d10dwand", "roll":[
"Carrots.",
"Apples.",
"Cherries.",
"Cave mushrooms.",
"Purple mushrooms.",
"Wild mushrooms.",
"Truffles.",
"Thick gravy.",
"Rich gravy.",
"Garlic.",   ]},
{"title": "d12 On the side, there is some...", "id":"d12dwonthesidethereissome", "roll":[
"Rye bread.",
"Wheat bread.",
"Crusty bread.",
"Honey cake.",
"Oat cake.",
"Poppyseed cake.",
"Hard biscuit.",
"Fluffy biscuit.",
"Pork sausage.",
"Deer sausage.",
"Bacon.",
"Ham.",   ]},
{"title": "d12 To wash it down, we have some...", "id":"d12dwtowashitdownwehavesome", "roll":[
"Black ale.",
"Pale ale.",
"Brown ale.",
"Red ale.",
"White ale.",
"Wheat ale.",
"Pilsner.",
"Lager.",
"Chocolate stout.",
"Coffee stout.",
"Black porter.",
"Brown porter.",   ]},
{"title": "d12 ...that is just a bit...", "id":"d12dwthatisjustabit", "roll":[
"Too dark in color.",
"Too light in color.",
"Too strong in flavor.",
"Too mild in flavor.",
"Too foamy.",
"Too fizzy.",
"Too flat.",
"Too bitter.",
"On the nutty side.",
"On the floral side.",
"On the sweet side.",
"Chewy.",   ]},



 {"title": "d10 Tonight, at a dockside tavern, we dine on...", "id":"d10tonightatadocksidetavernwedineon", "roll":[
"Stewed.",
"Breaded.",
"Fried.",
"Battered.",
"Baked.",
"Brined.",
"Seared.",
"Peppered.",
"Salted.",
"Pickled.",   ]},
 {"title": "d20 ...", "id":"d20dock", "roll":[
"Clams.",
"Crab.",
"Herring.",
"Lobster.",
"Mussels.",
"Oysters.",
"Salmon.",
"Smelt.",
"Haddock.",
"Mackerel.",
"Squid.",
"Shrimp.",
"Prawns.",
"Tuna.",
"Halibut.",
"Cod.",
"Sea bass.",
"Goose.",
"Chicken.",
"Mutton.",   ]},
 {"title": "d10 ...with...", "id":"d10dockwith", "roll":[
"Golden potatoes.",
"Red potatoes.",
"Beets.",
"Leeks.",
"Lentils.",
"Red beans.",
"Black beans.",
"Turnip mash.",
"Diced turnips.",
"Wild rice.",   ]},
 {"title": "d12 ...and...", "id":"d12dockand", "roll":[
"Carrots.",
"Red cabbage.",
"Green cabbage.",
"Purple cabbage.",
"Dill weed.",
"Lemongrass.",
"Lemon wedges.",
"Parsley.",
"Radishes.",
"Peas.",
"Green onions.",
"Yellow onions.",   ]},
 {"title": "d8 On the side, there is some...", "id":"d8onthesidethereissome", "roll":[
"Sourdough bread.",
"Fresh bread.",
"Crusty bread.",
"Sweet bread.",
"Sesame bread.",
"Oat bread.",
"Pumpernickel bread.",
"Beer bread.",   ]},
 {"title": "d10 To wash it down, we have some...", "id":"d10docktowashitdownwehavesome", "roll":[
"Bitter ale.",
"Wheat ale.",
"Steam beer.",
"Porter.",
"Mead.",
"Sour wine.",
"Red wine.",
"Tea.",
"Spiced rum.",
"Dry rum.",   ]},



{"title": "d10 Tonight, at a country inn, we dine on...", "id":"d10tonightatacountryinnwedineon", "roll":[
"Stewed.",
"Roasted.",
"Fried.",
"Boiled.",
"Baked.",
"Grilled.",
"Seared.",
"Steamed.",
"Salted.",
"Pickled.",   ]},
{"title": "d12 ...", "id":"d12ci", "roll":[
"Rabbit.",
"Chicken.",
"Duck.",
"Mutton.",
"Pork.",
"Beef.",
"Pheasant.",
"Goose.",
"Trout.",
"Clams.",
"Pork sausage.",
"Duck sausage.",   ]},
{"title": "d20 ...with...", "id":"d20withci", "roll":[
"Dumplings.",
"Red cabbage.",
"White cabbage.",
"Shredded cabbage.",
"Leeks.",
"Lentils.",
"Broccoli.",
"Peas.",
"Cauliflower.",
"Kidney beans.",
"String beans.",
"White beans.",
"Turnip mash.",
"Sliced turnips.",
"Asparagus.",
"Sprouts.",
"Sweet peppers.",
"Red potatoes.",
"Golden potatoes.",
"Yams.",   ]},
{"title": "d12 ...and...", "id":"d12andci", "roll":[
"Carrots.",
"Apples.",
"Cherries.",
"Tomatoes.",
"Blueberries.",
"Strawberries.",
"Beets.",
"Mushrooms.",
"Radishes.",
"Squash.",
"Sweet onions.",
"Red onions.",   ]},
{"title": "d12 On the side, there is some...", "id":"d12onthesidethereissomeci", "roll":[
"Corn bread.",
"Corn mash.",
"Fresh bread.",
"Crusty bread.",
"Sesame bread.",
"Oat bread.",
"Pumpernickel bread.",
"Pretzel bread.",
"Fried egg.",
"Bacon.",
"Sharp cheese.",
"Soft cheese.",   ]},
{"title": "d10 To wash it down, we have some...", "id":"d10towashitdownwehavesomeci", "roll":[
"Water.",
"Wheat ale.",
"Porter.",
"Mead.",
"White wine.",
"Red wine.",
"Sweet wine.",
"Milk.",
"Coffee.",
"Brandy.",   ]},


 {"title": "d10 Tonight, around the campfire, we dine on...", "id":"d10tonightaroundthecampfirewedineon", "roll":[
"Stewed.",
"Roasted.",
"Skewered.",
"Boiled.",
"Smoked.",
"Grilled.",
"Seared.",
"Flame-broiled.",
"Salted.",
"Peppered.",   ]},
 {"title": "d10 ...", "id":"d10cf", "roll":[
"Rabbit.",
"Duck.",
"Pork.",
"Fish.",
"Venison.",
"Deer.",
"Squirrel.",
"Pheasant.",
"Mutton.",
"Lamb.",   ]},
 {"title": "d8 ...with...", "id":"d8cfwith", "roll":[
"Potatoes.",
"Lentils.",
"White beans.",
"Red beans.",
"Black beans.",
"Peas.",
"Turnips.",
"Onions.",   ]},
 {"title": "d12 ...and...", "id":"d12cfand", "roll":[
"Carrots.",
"Raisins.",
"Dried cherries.",
"Wild mushrooms.",
"Sliced mushrooms.",
"Rosemary.",
"Pine nuts.",
"Cashews.",
"Almonds.",
"Olives.",
"Dried berries.",
"Sunflower seeds.",   ]},
 {"title": "d6 On the side, there is some...", "id":"d6cfonthesidethereissome", "roll":[
"Rye bread.",
"Hard tack.",
"Crusty bread.",
"Sesame bread.",
"Hard cheese.",
"Sharp cheese.",   ]},
 {"title": "d6 To wash it down, we have some...", "id":"d6cftowashitdownwehavesome", "roll":[
"Water.",
"Watery ale.",
"Strong ale.",
"White wine",
"Red wine.",
"Tea.",   ]},


 {"title": "d12 This morning, at a traveler's inn, we break our fast on...", "id":"d12thismorningatatravelersinnwebreakourfaston", "roll":[
"Scrambled eggs.",
"Fried eggs.",
"Boiled eggs.",
"Poached eggs.",
"Smoked ham.",
"Honey ham.",
"Hard cheese.",
"Soft cheese.",
"Hot porridge.",
"Cold porridge.",
"Thin porridge.",
"Warm gruel.",   ]},
 {"title": "d10 ...with...", "id":"d10tiwith", "roll":[
"Soggy bacon.",
"Chewy bacon.",
"Crispy bacon.",
"Thick-cut bacon.",
"Sweet sausage.",
"Mild sausage.",
"Spicy sausage.",
"Hot sausage.",
"Sour yogurt.",
"Sweetened yogurt.",   ]},
 {"title": "d8 ...and...", "id":"d8tiand", "roll":[
"Fried potatoes.",
"Boiled potatoes.",
"Tomatoes.",
"Mushrooms.",
"Sweet peppers.",
"Spinach.",
"Sweet onions.",
"Red onions.",   ]},
 {"title": "d12 On the side, there is some...", "id":"d12tionthesidethereissome", "roll":[
"Corn bread.",
"Corn mash.",
"Fresh bread.",
"Crusty bread.",
"Dry toast.",
"Buttered toast.",
"Pumpernickel bread.",
"Pretzel bread.",
"Fried egg.",
"Extra bacon.",
"Sharp cheese.",
"Pungent cheese.",   ]},
 {"title": "d6 ...and there are some...", "id":"d6tiandtherearesome", "roll":[
"Apples.",
"Cherries.",
"Blueberries.",
"Strawberries.",
"Pears.",
"Blackberries.",   ]},
 {"title": "d10 To wash it down, we have some...", "id":"d10titowashitdownwehavesome", "roll":[
"Water.",
"Brown ale.",
"Red ale.",
"Porter.",
"Stout.",
"Spiced wine.",
"Red wine.",
"Milk.",
"Coffee.",
"Tea.",   ]},


 {"title": "d12 This morning, at a city cafe, we break our fast on...", "id":"d12thismorningatacitycafewebreakourfaston", "roll":[
"Scrambled eggs.",
"Fried eggs.",
"Boiled eggs.",
"Poached eggs.",
"Hard cheese.",
"Soft cheese.",
"A cinnamon roll.",
"A sticky bun.",
"A sweet roll.",
"A croissant.",
"A chocolate croissant.",
"An almond croissant.",   ]},
 {"title": "d6 ...with...", "id":"d6withcc", "roll":[
"Crispy bacon.",
"Thick-cut bacon.",
"Mild sausage.",
"Spicy sausage.",
"Sour yogurt.",
"Sweetened yogurt.",   ]},
 {"title": "d6 ...and...", "id":"d6andcc", "roll":[
"Tomatoes.",
"Mushrooms.",
"Sweet peppers.",
"Spinach.",
"Green onions.",
"Red onions.",   ]},
 {"title": "d6 On the side, there is some...", "id":"d6onthesidethereissomecc", "roll":[
"Fresh bread.",
"Buttered toast.",
"Pumpernickel bread.",
"Pretzel bread.",
"Sharp cheese.",
"Pungent cheese.",   ]},
 {"title": "d6 ...and there are some...", "id":"d6andtherearesomecc", "roll":[
"Apples.",
"Cherries.",
"Blueberries.",
"Strawberries.",
"Pears.",
"Blackberries.",   ]},
 {"title": "d8 To wash it down, we have some...", "id":"d8towashitdownwehavesomecc", "roll":[
"Water.",
"Brown ale.",
"Red ale.",
"Porter.",
"Stout.",
"Spiced wine.",
"Orange juice.",
"Apple juice.",   ]},
 {"title": "d6 ...and a cup of...", "id":"d6andacupofcc", "roll":[
"Green tea.",
"Black tea.",
"Light-roasted coffee.",
"Dark-roasted coffee.",
"Strong coffee.",
"Weak coffee.",   ]},
 {"title": "d8 ...with...", "id":"d8withcc", "roll":[
"Milk.",
"Sugar.",
"Cream.",
"Milk and sugar.",
"Cream and sugar.",
"Honey.",
"Cinnamon.",
"Nothing added.",   ]},


{"title": "d6 Varieties This dish is...", "id":"d6varietiesthisdishis", "roll":[
"Exotic / Unusual (roll again and choose something outlandish/rare).",
"Fruits.",
"Meats.",
"Savories: These include cheese, nuts and seeds.",
"Seafood: This includes shellfish and ocean plants.",
"Vegetables.",   ]},
{"title": "d4 Flavor This dish is...", "id":"d4flavorthisdishis", "roll":[
"Sweet.",
"Spicy.",
"Sour.",
"Savory.",   ]},
{"title": "d10 Preparation This dish is...", "id":"d10preparationthisdishis", "roll":[
"Baked.",
"Boiled.",
"Broiled.",
"Fried.",
"Grilled.",
"Poached.",
"Roasted.",
"Sauteed.",
"Seared.",
"Steamed.",   ]},
{"title": "d4 Presentation This dish is served on or with...", "id":"d4presentationthisdishisservedonorwith", "roll":[
"Bread.",
"Leaf/Skewer.",
"Pastry.",
"Rice.",   ]},
{"title": "d8 Beverages Enjoy this dish with...", "id":"d8beveragesenjoythisdishwith", "roll":[
"Cider.",
"Juice.",
"Mead.",
"Milk / Kefir.",
"Tea / Coffee / Chocolate.",
"Wine.",
"Beer.",
"Spirits / Cocktails.",   ]},
{"title": "d6 Sweet flavors The dish is flavored with...", "id":"d6sweetflavorsthedishisflavoredwith", "roll":[
"Sugar.",
"Molasses.",
"Honey.",
"Glaze (roll on fruits table).",
"Jam (roll on fruits table).",
"Pixie parts.",   ]},
{"title": "d12 Spicy flavors The dish is flavored with...", "id":"d12spicyflavorsthedishisflavoredwith", "roll":[
"Curry.",
"Cumin.",
"Black pepper.",
"Red pepper.",
"Chili powder.",
"Cinnamon.",
"Green chili pepper.",
"Ghost chili pepper.",
"Paprika.",
"Sriracha.",
"Red dragon oil.",
"Flecks of salamander.",   ]},
{"title": "d4 Sour flavors The dish is flavored with...", "id":"d4sourflavorsthedishisflavoredwith", "roll":[
"Yogurt.",
"Sour cream.",
"Sour fruit juice (roll d6 on fruits table).",
"Vinegar (d4): 1. white wine 2. red wine 3. fruits 4. digester juice",   ]},
{"title": "d20 Fruits The dish is made with...", "id":"d20fruitsthedishismadewith", "roll":[
"Lemon.",
"Lime.",
"Grapes.",
"Apple.",
"Orange.",
"Cherry.",
"Pear.",
"Plum.",
"Peach.",
"Mango.",
"Coconut.",
"Banana.",
"Papaya.",
"Blueberries.",
"Raspberries.",
"Blackberries.",
"Watermelon.",
"Cantaloupe.",
"Honeydew.",
"Dryad melons.",   ]},
{"title": "d20 Vegetables The dish is made with...", "id":"d20vegetablesthedishismadewith", "roll":[
"Asparagus.",
"Arugula.",
"Broccoli.",
"Carrots.",
"Cucumber.",
"Cauliflower.",
"Beans (d4): 1. black; 2. red; 3. string; 4. white.",
"Peppers (d4): 1. bell; 2. chili; 3. hot; 4. sweet.",
"Onion (d4): 1. green; 2. red; 3. sweet; 4. yellow.",
"Corn.",
"Parsnips.",
"Cabbage (d4): 1. green; 2. red; 3. purple; 4. white.",
"Turnips.",
"Radishes.",
"Beets.",
"Peas.",
"Spinach.",
"Sprouts.",
"Lettuce (d4): 1. butter; 2. iceberg; 3. romaine; 4. weedy.",
"Squash (d4): 1. butternut; 2. pumpkin; 3. summer; 4. zucchini.",   ]},
{"title": "d20 Savories The dish is made with...", "id":"d20savoriesthedishismadewith", "roll":[
"White cheese.",
"Sharp cheese.",
"Mild cheese.",
"Stinky cheese.",
"Pungent cheese.",
"Blue cheese.",
"Yellow cheese.",
"Goat cheese.",
"Sheep's milk cheese.",
"Sunflower seeds.",
"Pumpkin seeds.",
"Poppy seeds.",
"Soybeans.",
"Pine nuts.",
"Almonds.",
"Pecans.",
"Hickory nuts.",
"Peanuts.",
"Pistachios.",
"Walnuts.",   ]},
{"title": "d20 Common seafood The dish is made with...", "id":"d20commonseafoodthedishismadewith", "roll":[
"Clams.",
"Crab.",
"Herring.",
"Lobster.",
"Mussels.",
"Oysters.",
"Salmon.",
"Smelt.",
"Haddock.",
"Mackerel.",
"Squid.",
"Shrimp.",
"Prawns.",
"Tuna.",
"Halibut.",
"Cod.",
"Sardines.",
"Anchovies.",
"Scallops.",
"Sea bass.",   ]},
{"title": "d20 Unusual seafood Unusual but tasty, the dish is made with...", "id":"d20unusualseafoodunusualbuttastythedishismadewith", "roll":[
"Skate.",
"Cuttlefish.",
"Flounder.",
"Grouper.",
"Marlin.",
"Snapper.",
"Monkfish.",
"Shark.",
"Swordfish.",
"Electric eel.",
"Dolphin.",
"Whale.",
"Seal.",
"Walrus.",
"Sea cucumber.",
"Starfish.",
"Jellyfish.",
"Kraken suckers.",
"Mermaid fin.",
"Aberrant tentacles.",   ]},
{"title": "d20 Common meats The dish is made with...", "id":"d20commonmeatsthedishismadewith", "roll":[
"Beef.",
"Pork.",
"Mutton.",
"Chicken.",
"Turkey.",
"Duck.",
"Goose.",
"Venison.",
"Horse.",
"Ox.",
"Lamb.",
"Veal.",
"Pheasant.",
"Quail.",
"Rabbit.",
"Boar.",
"Goat.",
"Pigeon.",
"Sausage (roll 1d12 to determine base meat)",
"Roll twice and combine the meats",   ]},
{"title": "d20 Uncommon meats Unusual but tasty, the dish is made with...", "id":"d20uncommonmeatsunusualbuttastythedishismadewith", "roll":[
"Squirrel.",
"Gopher.",
"Cat.",
"Dog.",
"Bear.",
"Wolf.",
"Crocodile.",
"Lizard.",
"Snake.",
"Rat.",
"Panther.",
"Beaver.",
"Bat.",
"Beetles.",
"Crickets.",
"Maggots.",
"Frog.",
"Turtle.",
"Lion.",
"Antelope.",   ]},
{"title": "d20 Weird meats Surprisingly tasty, the dish is made with...", "id":"d20weirdmeatssurprisinglytastythedishismadewith", "roll":[
"Giant spider.",
"Ghoulflesh.",
"Rump of the satyr.",
"Centipede.",
"Medusa hair.",
"Manticore.",
"Dragonflesh (not usually from a real dragon, but a wyvern or drake).",
"Displacer beast.",
"Hellhound.",
"Aberrant eyes.",
"Gelatinous cube.",
"Halfling",
"Tarrasque testicles.",
"Devil's tongue.",
"Demon lips.",
"Otyugh feet.",
"Stirge wings.",
"Owlbear (the cheek is the best, the best places serve it plated with the beak intact).",
"Umber hulk.",
"Virgin priestess.",   ]},
{"title": "d12 Bread The bread portion of the dish is...", "id":"d12breadthebreadportionofthedishis", "roll":[
"Sourdough baguette.",
"Whole-grain baguette.",
"Bread bowl.",
"Crusty roll.",
"Soft roll.",
"Pumpernickel roll.",
"Sesame seed bun.",
"Tortilla.",
"Pita.",
"Flat bread.",
"Mini pizza.",
"Hot pocket.",   ]},


 {"title": "d10 This wine was made in...", "id":"d10thiswinewasmadein", "roll":[
"A traditional coastal region known for its wines.",
"A mild, mountain valley known for its wines.",
"A region with a growing community of winemakers.",
"A foreign land that has been making wines for centuries.",
"A region where settlers have begun making wine as their ancestors had.",
"A secluded monastery.",
"A chain of islands far across the sea.",
"The basement of a little country inn.",
"The basement of a little country chapel or shrine.",
"The household of an elvish lord.",   ]},
 {"title": "d10 The wine is...", "id":"d10thewineis", "roll":[
"A pale white.",
"A bubbly white.",
"A goldish white.",
"A pale rosé.",
"A rich rosé.",
"A delicate red.",
"A thick red.",
"A deep red.",
"A robust red.",
"A reddish purple.",   ]},
 {"title": "d20 The wine smells of...", "id":"d20thewinesmellsof", "roll":[
"Springtime breezes.",
"Wildflowers.",
"Honey.",
"Roses.",
"Cherry blossoms.",
"Lilacs.",
"Lilies.",
"Wildflowers.",
"Morning dew.",
"Rain-covered flower petals.",
"Orange blossoms.",
"Young grapes.",
"Ripe grapes.",
"Cherries.",
"Tangerines.",
"Apple blossoms.",
"Ripe grapes.",
"Lemongrass.",
"Peach blossoms.",
"Hydrangeas.",   ]},
 {"title": "d20 The wine's flavor has notes of...", "id":"d20thewinesflavorhasnotesof", "roll":[
"Apple.",
"Blueberry.",
"Butter.",
"Citrus.",
"Cherry.",
"Chocolate.",
"Cloves.",
"Ginger.",
"Lemon.",
"Oak.",
"Peach.",
"Pear.",
"Pepper.",
"Pine.",
"Plum.",
"Raspberry.",
"Spices.",
"Smokiness.",
"Strawberry.",
"Tangerine.",   ]},
 {"title": "d10 The wine is served in...", "id":"d10thewineisservedin", "roll":[
"A glass goblet.",
"A glass flute.",
"A glass mug.",
"A glass cup.",
"A tin cup.",
"A brass goblet.",
"A steel mug.",
"A gilded flute.",
"A silver goblet.",
"A bucket.",   ]},
 {"title": "d10 The wine is best when enjoyed...", "id":"d10thewineisbestwhenenjoyed", "roll":[
"Iced.",
"Chilled.",
"Cold.",
"After it has had a few minutes to breathe.",
"After it has had a few hours to breathe.",
"Lightly spiced.",
"Warmed.",
"Hot.",
"Honeyed.",
"Heavily spiced and boiled.",   ]},
 {"title": "d10 The wine makes a great pairing with...", "id":"d10thewinemakesagreatpairingwith", "roll":[
"Oysters or fish.",
"Lobster or crab.",
"Chicken or turkey.",
"Pork chops or bacon.",
"Steak or veal.",
"Mutton or lamb.",
"Sausage.",
"A soft cheese.",
"A hard cheese.",
"A stinky cheese.",   ]},
 {"title": "d10 There is a tale that this type of wine was...", "id":"d10thereisatalethatthistypeofwinewas", "roll":[
"A gift from a god or goddess to an ancient people.",
"Drunk at a famed wedding feast.",
"Drunk at the funeral of a legendary king or queen.",
"Consumed by a legendary warrior before slaying a dragon.",
"Consumed by a legendary priest or priestess prior to making a dark prophecy.",
"Consumed by a legendary witch or wizard before he or she mysteriously disappeared.",
"Consumed by a legendary thief before stealing a celebrated gem.",
"Consumed by a legendary knight before leading a host to victory against impossible odds.",
"Consumed by a famous pair of lovers as they poisoned themselves.",
"First produced by a now-extinct, ancient race or clan.",   ]},


// end of food

];
