// monsters.js
//

top.monsters = [

// beginning of monsters





 {"title": "d4 Age The Dragon is a... ", "id":"d4agethedragonisa", "roll":[
"Youngling.",
"Adult.",
"Ancient One.",   ]},
 {"title": "d10 Colour The Dragon is coloured... ", "id":"d10colourthedragoniscoloured", "roll":[
"Blue, as proud as it is deadly.",
"Green, treacherously cunning.",
"Red, fiery and mad.",
"White, a primal beast of ice.",
"Brass, always fond of a nice chat.",
"Copper, a crafty jokester.",
"Gold, majestic and wealthy.",
"Silver, friendly and caring.",
"Bronze, a dragon of the coast.",   ]},
 {"title": "d70 Appearance The dragon has a unique appearance ", "id":"d70appearancethedragonhasauniqueappearance", "roll":[
"Is relatively normal for its colour.",
"It has very tough and overgrown scales like barbaric plate armour.",
"Shards of bone grow out of its body painfully at every angle.",
"Crystal grows out of its scales seemingly brimming with magical power.",
"It has runes carved into every scale each one with magical meaning.",
"It is albino and while mistaken for a White Dragon may actually have a very different appearance.",
"Its entire body is covered in thick shaggy fur.",
"It has multiple sets of small sharp wings.",
"Its wings are coated in feathers giving it an oddly angelic appearance.",
"It radiates its chosen element making it glow with power under its scales.",
"It has weapons of all kinds in its scales which the dragon wears proudly.",
"It’s covered in thick chains. Most likely result of it losing a fight long ago.",
"Large scars cut into its body.",
"Shadows seem to cling to its form like a cloak, no matter how bright the area is.",
"A long slender body like a great serpent.",
"An extra set of arms with strong muscle and sharp claws.",
"Mottled scale colours that give it a patchy look between two colours",
"A bloated and obese body that makes it exceedingly large.",
"An insect like mandible instead of a normal maw.",
"A mouth so large it has trouble shutting with rows and rows of sharp teeth.",
"A slimy goo like substance all over its body.",
"Appears to be changing colours at all times like an optical illusion.",
"Bark or stone all over its body.",
"Multiple sets of eyes that glow with arcane power.",
"Large ancient gauntlet like constructs on its claws that it uses in combat.",
"Extra armour added to its body, adamantine or mithral.",
"A thin almost skeletal form.",
"Ugly diseased marks on its scales and a sickly pallor. ",
"Its front legs are its wings in a way similar to a Wyvern. ",
"It wears the trophies of its kills on its body, covered in heads and hands.",
"Areas of its body are completely devoid of scales. Its skin has grown tough and leathery to make up for that.",
"Has fish like adaptations to living at deep sea.",
"Has some kind of weakness and wears an exosuit like harness over their body to make them stronger.",
"A second head on its tail that can also shoot breath weapons.",
"Two heads, both with different personalities like an Ettin.",
"It has an aura of its elemental power around it at all times, such as a bubble of flame uncontrollably burning.",
"The dragon has no mouth and speaks entirely telepathically. Its breath weapon is magical instead.",
"The dragon seems blind, and relies on extremely strong smell and sound to find prey.",
"It has sharp monstrous barbs all over its body.",
"It has a very soft underbelly of a different colour that is weaker than its other scales.",
"Has gemstones and coins inset into its scales like a traditional dragon, gaining it strength and armour.",
"It has sharp scythe like claws that make up its front claws.",
"Its claws are very long and slender but have great tactile control.",
"It has a very long tongue that it eagerly uses like an extra arm.",
"It has a face eerily similar to a humanoids.",
"Its form is slightly more humanoid than usual, with the typical muscles more prominent and obvious than usual.",
"Has ridges of horn like spines over its back each one just as sharp.",
"Has very long curled horns like a minotaur that it will use on headbutting goring attacks.",
"It has only one but very large horn like a unicorn.",
"It seems to have no claws at all instead relying on hard slamming attacks.",
"It’s missing one of its limbs entirely.",
"It has half of its face missing, revealing the bone and muscle beneath. ",
"Its scales are slightly translucent allowing one to see its insides.",
"A cobra like hood on its neck.",
"Bandages and wrappings around a good deal of its body.",
"A somewhat bird like beak instead of a traditional dragon maw.",
"Has eerily human like hands instead of claws.",
"A disturbing number of multiple scuttling legs.",
"Huge crab like claws.",
"A beholder like eye with several twisting eyestalks.",
"A huge twisting wurm like body.",
"A sharp bladed tail that it uses as a weapon.",
"A bloody stump where the tail was meant to be.",
"Smoke and clouds around its body at all times.",
"Huge and actually somewhat uncomfortable wings that sweep around it.",
"It stands on its hind legs similar to a humanoid.",
"Carefully manicured claws in sword like shapes.",
"Broad fan like tail fins.",
"Wreathes of flowers and plants around its body.",   ]},
 {"title": "d40 Appearance 2  It also has ", "id":"d40appearance2italsohas", "roll":[
"Light scaring around the eyes.",
"A heavy mace like tail which it will happily use as a weapon.",
"A mane of ‘hair’ by its head.",
"A crown of horns around the top of its skull.",
"A face that looks like a skull.",
"A pair of overly large fangs.",
"A powerful artefact of some kind embedded in its forehead.",
"An extra tail.",
"Each eye is a different colour and extra vibrant.",
"A hungry and yet charming grin.",
"A beard of hanging scales.",
"Scales of varying shininess and hue.",
"Far brighter colours than normal.",
"Far darker colours than normal.",
"Often covered in mud or dirt.",
"Appears to have used some kind of make up.",
"Has painted tattoos on its scales.",
"Several missing teeth.",
"A single missing scale making a small weak point.",
"Missing a single wing.",
"Has stripe like patterns to its scales.",
"Has one single magical eye.",
"A pet that constantly stays by its side.",
"Brand like markings burnt onto its body.",
"Smoke constantly billowing from its mouth and nostrils.",
"A thin slender form.",
"A cuddly stocky form.",
"A spiney ridge on their back.",
"Wears very large custom made eyeglasses.",
"A large ridge on its head like a triceratops. ",
"Shackles on its legs.",
"Plants growing on its body.",
"A very long tail, several times the lengths of its body.",
"Large fins on its tail.",
"A vastly different than normal hue. ",
"Fins on its limbs.",
"A large overbiting jaw.",
"A large underbiting jaw.",
"Fake horns.",   ]},
 {"title": "d70 Traits  The dragon is  ", "id":"d70traitsthedragonis", "roll":[
"The runt of the litter. It’s smaller than average and weaker, yet more intelligent and stealthy.",
"A new parent protecting its eggs. It is proud and excited for them but will protect them to the death.",
"Part of a long family lineage of dragons and trying to live up to the expectations of that.",
"The survivor of an attack that haunts it. Whatever this attack is deeply disturbs the dragon whenever anything similar happens, for example causing the dragon to freeze and panic around fire.",
"One half of a pair of twins. Very connected to their twin.",
"Fond of staying in human form. They live as a human, or similar race, living the normal life of a mortal and enjoying it greatly. ",
"A powerful wild mage. It uses its spells as breath attacks that often cause completely unexpected chaotic surges of magic.",
"A powerful wizard who has a large tome of magic. It adores magic and tries to learn as much as possible.",
"Tainted by fiends, becoming demonic. More evil than normal and the lord of many minor demons that do its bidding.",
"Tainted by celestials making it holy and good. Worshipped by many due to its holiness.",
"A fey dragon, giving it an attenuation to the feywild and an affinity to nature. It seems constantly surrounded by flowers and fairies and seems to be quite the trickster.",
"Loves building, and has actually tried to make its lair into the perfect dungeon. It will eagerly lure in and tempt people into it. It would even be excited if someone survived the entire dungeon.",
"Considers itself to be a mercenary hunting down either heroes or evildoers. It hunts down these people and fights them mercilessly. ",
"Fond of meditation and has spent years reaching inner enlightenment and tranquillity. ",
"Very eager to make friends. Although making friends for a dragon often involves ‘playing’ with them in ways similar to a cat playing with a mouse.",
"Trying to become the most infamous dragon in the entire realm. Almost to the extent of making itself a brand.",
"Part of a pair mated for life. They’re very unwilling to separate.",
"Actually very stealthy. Will lay traps and bait an enemy and attack from the shadows. ",
"Undead but trying to cling to what it once was, and not lose its soul and its mind.",
"Not afraid of using technology. It has learnt from Rock Gnomes various steam and clockwork powered technologies, and will create auto turrets to use in its fight.",
"Highly religious. It worships its god or gods strongly and will go to the extent of performing great rituals or sacrifices. ",
"Has a cult of followers who worship them like a god. It of course loves this as it strokes their ego.",
"Highly emotional and will go through manic swings with their emotions. Kind and caring one day, destructive the other.",
"Connected to the environment around its lair in a great way, able to manipulate the surrounding area and protects it.",
"Considers itself a scientist and uses arcane magic to do twisted experiments on itself and others. Its lair is full of these experiments.",
"Has an agreement with a monster hunting guild to kill those applicants that get annoying after they pay in their initial application payments. ",
"Respects mortals and smaller creatures. Sees meaning in all life, even something as small as an insect.",
"Is a king of a small land. Complete with crown. May be a harsh king but the locals wont argue with a huge dragon.",
"Is very interested in medicine and will heal and fix up anyone near death, even those trying to kill them. They will then keep them in a dungeon until they regain strength.",
"Is almost entirely feral and primal.",
"Likes to live in animal form, experiencing the wild. It has picked up many animal like traits due to this.",
"Is extremely intelligent, or thinks it is. Tries to use its mind to solve problems. And of course thinks it’s better than everything else.",
"Is very charming and charismatic. Will actually talk its way out of, or into situations.",
"Was created by magic or some other source, not a blood born dragon. This makes it confused about its life and creation.",
"Was raised by mortals. If they were kind, it loves mortals. If they hurt it, it caused a hatred for mortals that caused their madness.",
"Is entirely insane. Perhaps caused by magic or some kind of drug abuse.",
"Always flies, tries to touch the ground as little as possible. Even flies in its sleep floating above the ground. ",
"Never leaves the ground, despite having wings. Has learnt to burrow instead when it needs to fly.",
"Is not particularly strong, but is extremely fast and agile. Able to dish out many attacks at one go that deal small but biting damage. ",
"Slow, lumbering… but deadly. When this dragon eventually gets to combat its blows are entirely destructive.",
"Has a strange honour system, only ever wanting to fight when it follows its exact set of rules. When people break this honoured battle system, the dragon uses its true power and gets angry.",
"The dragon is part of a large community of friendly or not so friendly dragons who send messages and gifts to eachother on a regular basis.",
"Hibernates for centuries at a time… leading to a lot of confusion. Its snoring is so loud it is mistaken for wind.",
"Tries to be the opposite alignment of its natural state… While it tries hard it still feels urges and can lose control.",
"Considers itself a master bard and will write songs and music. They may be good, but dragons are not the best at singing or playing the lute.",
"Cursed with vampirism. While this doesn’t work exactly the same it has given the dragon a huge hunger for blood.",
"Cursed with lycanthropy. While it doesn’t work the same, the dragon is amazingly violent on a full moon and hades silver.",
"Has a terminal disease and is either trying to help or hinder the world as much as possible in its dying days.",
"Runs a shop to those that are strong enough to survive the trip through its lair to get there.",
"Thinks itself an intelligent mastermind, a game master that plays with its pawns in one huge game, a game of dungeons and dragons.",
"Follows ‘the law’ of the land. Very strenuously stretching laws to let it do what it wants.",
"It will be kind to those that give it gifts that it deems exciting enough.",
"quite the nymphomaniac. Which can be rather dangerous especially when it gets its eye on a party member.",
"Endorses adventurers or mercinaries across the land, giving them funds to do things the dragon is simply to lazy to do.",
"A glutton. For food, drink, just about everything.",
"Full of Pride. As are all dragons, but this one has trouble looking away from the mirror.",
"Greedy, more than most dragons. If anyone has any treasure in any way, the dragon needs it.",
"Lazy. Why do anything when you can rest. It doesn’t want to bother any one as much as it just wants to sleep and be by itself.",
"Vengeful. If someone slightly wrongs this dragon they will come at them, their children, their childrens children as well as every town they have been through ever.",
"Is protecting a powerful artefact of intense magical power.",
"Lonely, and only wants to find friends.",
"Bullies all the other dragons and monsters in the area, becoming their leader.",
"Works intensely on illusions and creates illusionary traps and environments.",
"Demands protection money and food from nearby settlements.",
"Serious social anxiety and doesn’t want to talk to anyone.",
"It in its human form is influencing the entire realm and doing dark dealings.",
"It only leaves its lair during a certain season each year.",
"It wants to die in such a way that legends and songs will be created after it. Will actually try and orchestrate this.",
"Is sick. A dragon sneezing is a powerful, but embarrassing weapon.",   ]},
 {"title": "d20 Speech  When it comes to conversation; ", "id":"d20speechwhenitcomestoconversation", "roll":[
"It knows many languages and loves to talk.",
"Is mute and refuses to talk.",
"Talks very slowly and conservatively.",
"Speaks its mind very simply.",
"Speaks only in riddles and metaphors.",
"Tends to ask constant questions but give no answers. ",
"Very flirty. Uncomfortably so.",
"Mimics anyone that talks to them",
"Will find any excuse to argue.",
"Uses its breath weapon as violent punctuation.",
"Speaks using illusions like charades. ",
"Is very friendly until someone swears and then is extremely offended and angry.",
"Laughs darkly almost whenever possible.",
"Growls out most of its words.",
"Speaks very broken language.",
"Refers to itself in third person.",
"Only speaks through a scribe interpreter. ",
"It gets uncomfortably close as it speaks.",
"It seems to know everything about everyone it talks too.",   ]},
 {"title": "d30 Hoard  Each dragon is compelled to hoard, but many hoard in different ways. This dragons hoard is, ", "id":"d30hoardeachdragoniscompelledtohoardbutmanyhoardindifferentwaysthisdragonshoardis", "roll":[
"Gold but only the currency of one race, oddly not the race in the nearby areas.",
"Carefully organised money in stacks and every treasure is organised using a complex system.",
"All famous art, paintings and statues. It will commission paintings of itself, and go to art shows in disguise.",
"Food. The Dragon loves to eat and sees food as a potential to be an art form. Actually hires chefs to cook the best food possible.",
"The frozen or petrified statuesque forms of adventurers that try to kill it. It will tell the tales of their attempts proudly and with great interest.",
"Stories and legends. It loves to hear and tell stories and has an obsession with bards.",
"Music. It constantly needs music playing in its lair, and gets very agitated if there is none.",
"A zoo of various monsters and creatures. It aims to have two of every race at one point, a male and female. ",
"Buildings. This dragon hoards real estate and territory. In disguise it owns and buys land. The land is more important than the people that live there, but will help the people if it helps them get more land.",
"Gemstones. This dragon has little time for money but loves gemstones. Preferably cut.",
"A library of books and stories. Knowledge is its passion.",
"Magical artefacts, from all across the world. ",
"A very beautiful mansion that it uses like a doll house, getting the finest appearance possible.",
"People it deems interesting that are either enslaved or convinced to stay.",
"Narcotics. The dragon loves to try different types of drugs, such as pipeweeds and psychotropic mushrooms. Of course it needs large amounts to work.",
"A large and beautiful garden that it keeps and tends for.",
"Their children. The dragon has many pure and half blood children and takes care of them greatly.",
"Potions and all kinds of strange alchemical creations.",
"The corpses and remains of other dragons. Particularly interested in weapons and armours made of dragonscales.",
"Artisan jewellery that the dragon actually wears on its body.",
"Literally everything. Or tries. This leads to this dragons hoard being very random and chaotic.",
"Objects of power linked to its element.",
"Minions that swear loyalty to the dragon.",
"Gemstones and other things the same colour as the dragon.",
"Very sparsely laid out with a treasure each dedicated to a room.",
"Very compact with a large amount of treasure forced into one small room.",
"Hidden, the dragon assumed someone was coming and hid the hoard away.",
"Up for being shared. The dragon will often share its hoard to those that need it, endorsing heroes. Often though this is a loan to be repaid.",
"Has been passed down for generations and only grown in size.",   ]},
 {"title": "d30 Lair  Dragons have a home, a lair. Often a large dungeon. This dragons lair is,  ", "id":"d30lairdragonshaveahomealairoftenalargedungeonthisdragonslairis", "roll":[
"The peak of the tallest mountain, with few paths up to the lair.",
"A temple built for the dragon personally by its worshippers or people enslaved.",
"A flying island above the land. Lush or barren, still a very safe place for a dragon.",
"An underwater wreckage of a galley. Perhaps with caverns and ruins below it.",
"An abandoned mine. The mineshafts are filled with minions to defend the dragon.",
"A cavern carved out of the stone by the dragon. The walls are full of these sharp cuts scraped by the dragon and the chambers are shaped similarly to the dragons wingspan.",
"A reclaimed castle. The surrounding area is planes or desert, the castle most likely abandoned by its old owners.",
"A desert pyramid, surrounded by dangerous deserts.",
"A giant tree. Perhaps dead, or in a lush environment, a tree large enough to hold a dragon is impressive.",
"Underdark Caverns. The underdark can be a great place for a dragon that’s trying to hide away.",
"A volcano. The heat is perfect for a red fire dragon, but also presents for defence from attackers.",
"An abandoned settlement. The towns walls now protect the dragon, who claims the empty town.",
"A tomb. Dragons have little respect for the dead of mortals, so a tomb can be turned into a useful lair.",
"A lonely island away from most of the world.",
"Built by minions, a ramshackle base made by goblins and the sort. It seems like it will fall apart at any times.",
"A flat mesa. High up but with a flat environment perfect for dragon duels.",
"Behind a waterfall. Hidden behind the waterfall is a large cave system.",
"Nomadic. The dragon has no fixed home, and is travelling for some reason.",
"A large roost community of several young dragons.",
"A pocket dimension of its own creation. ",
"A realm designed to imprison it. Perhaps the dragon took control of the realm after.",
"An elemental plane linked to the dragon.",
"A citadel designed to imprison the dragon. And perhaps also other beings of similar power waiting to be freed.",
"A site of a great battle. The ground littered with corpses, perfect stomping ground for a dragon.",
"A ravine where the dragon can enter with ease.",
"Built by the dragon. The best homes are made yourself.",
"An arctic glacier. Cold and far away.",
"Under a settlement. Most likely hidden from the population.",
"A mountain top shrine. ",   ]},
 {"title": "d30 Lair 2  The lair also has, ", "id":"d30lair2thelairalsohas", "roll":[
"A place of elemental power.",
"A portal between realms.",
"Skinned monsters in every hallway. The decorator has a macabre sense of style.",
"A library of ancient tomes.",
"A room of the dragons concubines of various races.",
"Puzzles that requires a dragons strength to operate.",
"Arcane traps.",
"Murals of the dragons personal conquests.",
"A clutch of dragon eggs.",
"Magic playing tricks on all that enter.",
"Shed lizard skin all over the floors.",
"A fake hoard filled with a sea of coin mimics. ",
"Several holes in the roof where the dragon takes off from.",
"Friendly inhabitants that live with the dragon.",
"Many statues and paintings of the dragon.",
"Maze like corridors.",
"Puzzles that are easy if one understands draconic.",
"A huge chess set with pawns the size of people.",
"The bones of the dragons mother/father.",
"Warding stones outside from several races warning of danger.",
"A spectator summoned to guard the lair and politely turn away invaders.",
"A cloud of smoke and mist around it at all times.",
"A huge pantry of all kinds of raw meats.",
"An illusionary fake dragon to try and bait out enemy spells.",
"Strange music travelling throughout the whole lair.",
"An alarming amount of mould and decay",
"Strange and violent weather all around.",
"Flooded caverns of waterborne monsters.",
"One huge chamber with pillars breaking it up.",   ]},
 {"title": "d20 Henchmen  Their lair is defended by, ", "id":"d20henchmentheirlairisdefendedby", "roll":[
"Mercenaries hired by the dragon to keep it safe. The races and skills do not matter to the dragon, so would be varied.",
"Hobgoblin soldiers. More trained professionals.",
"The dragons children. Purebred and half-dragon children.",
"The nightmares of all that enter.",
"Kobolds with the intelligence of toddlers. They just want to help.",
"Mortal cultists.",
"A sect of mortal dragon knights.",
"Wild beasts. Lured in by the dragon.",
"Intelligent beasts.",
"Mephits and elementals suiting the dragon.",
"Gensai linked to the dragons element.",
"Undead.",
"Fiends.",
"Shadowy versions of the party raiding the dungeon.",
"Seemingly harmless warning signs that hold deadly curses.",
"Terrified peasants.",
"Arcane defence turrets.",
"Giant Insects.",
"Smaller dragon like creatures.",   ]}, 



{"title": "d10 Color The wolf's coat is...", "id":"d10colorthewolfscoatis", "roll":[
"Black.",
"Dark grey.",
"Dark brown.",
"Black and brown.",
"Black and grey.",
"Pale brown.",
"Brown and grey.",
"Reddish brown.",
"Sandy brown.",
"White.",   ]},
 {"title": "d10 Markings The wolf has...", "id":"d10markingsthewolfhas", "roll":[
"White or pale fur on each paw.",
"White or pale fur on one paw.",
"White or pale fur around the face and muzzle.",
"Black or dark fur around the face and muzzle.",
"A banded pattern on its back (d4): 1. dark grey; 2. pale grey; 3. reddish brown; 4. sandy brown.",
"Lighter fur on its belly.",
"Darker fur on its belly.",
"A distinct, white or pale grey shape on its chest (d4): 1. arrowhead; 2. diamond; 3. a wide stripe; 4. star.",
"A scar from a past injury (d6): 1. flank; 2. foreleg; 3. hindleg; 4. snout; 5. eye; 6. ear.",
"No obvious markings.",   ]},
 {"title": "d12 Eyes The wolf's eyes are...", "id":"d12eyesthewolfseyesare", "roll":[
"Reflective and black.",
"Pale grey.",
"Brownish grey.",
"Dark grey.",
"Dark brown.",
"Golden brown.",
"Light brown.",
"Red.",
"Yellow.",
"Green.",
"Pale blue.",
"Dark blue.",   ]},
 {"title": "d12 Manner The wolf is...", "id":"d12mannerthewolfis", "roll":[
"Panting lightly.",
"Panting heavily, its tongue lolling out of its mouth.",
"Salivating.",
"Hungrily licking its chops.",
"Yawning.",
"Watching curiously.",
"Watching warily.",
"Pacing nervously.",
"Whining softly.",
"Watching with ears perked and hackles raised.",
"Growling low, giving warning.",
"Standing perfectly still, ready to lunge.",   ]},
 {"title": "d6 Hunting The wolf prefers to...", "id":"d6huntingthewolfprefersto", "roll":[
"Pick off weak, easy prey.",
"Stalk its prey until the opportune time to strike.",
"Harrying its prey over long distances until the prey is exhausted.",
"Chase its prey to a place where its packmates are waiting in ambush.",
"Wait in ambush while one or more of its packmates chases the prey to it.",
"Choose its prey and to run it down.",   ]},
 {"title": "d10 Favorite prey If given the choice, the wolf will opt to eat...", "id":"d10favoritepreyifgiventhechoicethewolfwillopttoeat", "roll":[
"Rabbit.",
"Squirrel.",
"Pheasant.",
"Goose.",
"Deer.",
"Sheep.",
"Chicken.",
"Carrion.",
"Human flesh.",
"Scraps from a roadside inn's refuse heap.",   ]},
 {"title": "d10 Pack The wolf is...", "id":"d10packthewolfis", "roll":[
"The alpha of a large pack.",
"The alpha of a small pack.",
"The beta of its pack, patiently waiting for the alpha to fail.",
"The beta of its pack, constantly challenging the alpha.",
"Somewhere in the middle of the pack order, looking for opportunities to ascend.",
"Somewhere in the middle of the pack order, satisfied to follow the alpha.",
"The omega of a large pack.",
"The omega of a small pack.",
"One of a mated pair.",
"A lone predator.",   ]},
 {"title": "d10 Habitat This type of wolf evolved to thrive...", "id":"d10habitatthistypeofwolfevolvedtothrive", "roll":[
"In canyonlands.",
"In grassy hills.",
"In forested hills.",
"On grassy plains.",
"In ancient forests.",
"In young forests.",
"In rocky deserts.",
"In the foothills of mountains.",
"In mountain passes.",
"In frozen lands.",   ]},


 {"title": "d8 Color The spider is...", "id":"d8colorthespideris", "roll":[
"Black.",
"Dark grey.",
"Dark brown.",
"Black and brown.",
"Black and grey.",
"Pale brown.",
"Brown and grey.",
"Reddish brown.",   ]},
 {"title": "d8 Markings The spider has...", "id":"d8markingsthespiderhas", "roll":[
"Pale banding on its legs.",
"Dark banding on its legs.",
"Bright banding on its legs (d4): 1. orange; 2. red; 3. white; 4. yellow.",
"Pale stripes down its abdomen.",
"Dark stripes down its abdomen.",
"A distinct, crimson shape on its abdomen (d4): 1. arrowhead; 2. pair of eye-like spots; 3. hourglass; 4. star.",
"A distinct, black or dark grey shape on its abdomen (d4): 1. arrowhead; 2. diamond; 3. pair of wavy lines; 4. star.",
"No obvious marking.",   ]},
 {"title": "d6 Eyes The spiders eyes are...", "id":"d6eyesthespiderseyesare", "roll":[
"Dull and black.",
"Reflective and black.",
"Dark grey, almost black.",
"Dark red.",
"Bright red.",
"Pearly white.",   ]},
 {"title": "d6 Mouth The spider's mouth is...", "id":"d6mouththespidersmouthis", "roll":[
"Flanked by fangs, dripping venom.",
"Flanked by hooked fangs.",
"Flanked by hairy chelicerae, each ending in a sharp fang.",
"Flanked by chelicerae, covered in hair that hides any fangs.",
"Hungrily opening and closing.",
"Yawning open.",   ]},
 {"title": "d8 Poison The spider's venom can cause...", "id":"d8poisonthespidersvenomcancause", "roll":[
"Paralysis.",
"Loss of consciousness.",
"Nausea.",
"Headache.",
"Loss of coordination.",
"Blindness.",
"Dizziness.",
"Shortness of breath.",   ]},
 {"title": "d6 Hunting The spider prefers...", "id":"d6huntingthespiderprefers", "roll":[
"Pick off weak, easy prey.",
"Pursue its prey until the opportune time to strike.",
"Lay web traps and wait.",
"Incapacitate prey, wrap it in webbing and carry it off to its larder.",
"Ambush prey in territory the spider knows well.",
"Poison its prey and then retreat, following the prey until it falls.",   ]},
 {"title": "d6 Webs The spider spins...", "id":"d6websthespiderspins", "roll":[
"Sheet-like webs.",
"Webs with radial symmetry.",
"Webs with triangular symmetry.",
"Webs with hexagonal symmetry.",
"Webs with irregular shapes.",
"Almost no webs; the spider is constantly on the move and on the hunt.",   ]},

{"title": "d12 The faerie is...", "id":"d12thefaerieis", "roll":[
"A capricious nymph.",
"An apprehensive nymph.",
"A playful nymph.",
"A nervous pixie.",
"A cheerful pixie.",
"A carefree pixie.",
"A wrathful sprite.",
"A curious sprite.",
"A surly sprite.",
"A drunken satyr.",
"A satyr bully.",
"A sharp-witted satyr.",
]},
{"title": "d20 Hair: The faerie has...", "id":"d20hairthefaeriehas", "roll":[
"Black hair.",
"Copper hair.",
"Golden blonde hair.",
"Platinum blonde hair.",
"Silver-white hair.",
"Dark brown hair.",
"Reddish-brown.",
"Fiery red hair.",
"Light brown hair.",
"Auburn hair.",
"Black hair with a brown streak.",
"Dark brown hair with an auburn streak.",
"Brown hair with a blonde streak.",
"Bright white hair.",
"Silver-blonde hair.",
"Whitish blonde hair.",
"Golden hair with a pink streak.",
"Golden hair with a green streak.",
"Black hair with a blue streak.",
"Black hair with a white streak.",
]},
{"title": "d20 Eyes: The faerie has...", "id":"d20eyesthefaeriehas", "roll":[
"Pale golden eyes.",
"Bright golden eyes.",
"Dark green eyes.",
"Brilliant green eyes.",
"Bright blue eyes.",
"Dark blue eyes.",
"Blue eyes with golden flecks.",
"Green eyes with golden flecks.",
"Pale green eyes.",
"Golden brown eyes.",
"Dark brown eyes.",
"Hazel eyes.",
"Whitish blue eyes.",
"Pale blue eyes.",
"Lilac eyes.",
"Pale violet eyes.",
"Bright violet eyes.",
"Deep red eyes.",
"Pale pink eyes.",
"Silver eyes.",
]},
{"title": "d12 Mannerisms: The faerie has...", "id":"d12mannerismsthefaeriehas", "roll":[
"A likable grin.",
"A delicate laugh.",
"A playful laugh.",
"A laugh that goes on too long.",
"An amused smirk.",
"A humorless visage.",
"A habit of sighing.",
"A touch of sorrow in his or her voice.",
"A habit of pacing.",
"A habit of scratching the back of the neck.",
"A habit of winking.",
"A seductive sway of the hips.",
]},
{"title": "d12 The faerie is looking for...", "id":"d12thefaerieislookingfor", "roll":[
"An unnatural creature that has taken up residence in the forest.",
"Ways to cause mischief for travelers.",
"Worthy visitors of a secret grove.",
"Amusement in frightening travelers.",
"Someone to listen to a new song.",
"A heart to break.",
"Love and war.",
"Love and mischief.",
"Mischief and mayhem.",
"The answer to a riddle.",
"A dance partner.",
"A drinking partner.",
]},
{"title": "d12 The faerie carries...", "id":"d12thefaeriecarries", "roll":[
"An delicate wreath of flowers.",
"A gem glowing with moonlight or starlight.",
"A finely-crafted bow or knife.",
"A vial containing a potent potion.",
"Several magical mushrooms.",
"A variety of herbs commonly used in potion making.",
"A message from a faerie king or queen.",
"A token from a past love.",
"A string instrument (d4): 1. fiddle; 2. harp; 3. lute; 4. lyre.",
"A wind instrument (d4): 1. flute; 2. horn; 3. ocarina; 4. panpipes.",
"A piece of sweet cake.",
"A jug of wine.",
]},
{"title": "d10 The goblins’ primary “business” involves...", "id":"d10thegoblinsprimarybusinessinvolves", "roll":[
"Raiding villages and farms.",
"Burglarizing storehouses and shops.",
"Harassing anyone who passes through their territory.",
"Robbing caravans carrying gems, precious metals, and exotic goods.",
"Holding up traders’ ships or wagons.",
"Smuggling drugs (d4): 1. smokeleaf; 2. a hallucinogenic mushroom; (3) sleepysalt (a downer); 4. sharpsugar (an upper).",
"Smuggling living things (d4): 1. exotic beasts; 2. foreign harlots; 3. fugitives; 4. slaves.",
"Serving as muscle for evildoers.",
"Mining and crafting.",
"Pranks and hijinks.",
]},
{"title": "d10 The goblin gang’s symbol is...", "id":"d10thegoblingangssymbolis", "roll":[
"A skull.",
"An arrow.",
"A dagger.",
"The moon.",
"A star.",
"A snake.",
"A spider.",
"A rat.",
"A wolf.",
"A bat.",
]},
{"title": "d6 The goblins’ lair is located...", "id":"d6thegoblinslairislocated", "roll":[
"In a dark and haunted forest.",
"In an enchanted forest.",
"Along a mountain pass.",
"High in the mountains.",
"Beneath a bustling city.",
"Near a quiet farm village.",
]},
{"title": "d6 The goblins’ lair is...", "id":"d6thegoblinslairis", "roll":[
"A series of natural caverns.",
"An abandoned mine.",
"A mine in which the goblins are actively digging.",
"An underground fortress.",
"A semi-organized military encampment.",
"A crude encampment.",
]},
{"title": "d20 The goblins are particularly fond of picking on...", "id":"d20thegoblinsareparticularlyfondofpickingon", "roll":[
"Fishermen and sailors.",
"Beggars and drunks.",
"Merchants and moneychangers.",
"Young noblemen.",
"Young noblewomen.",
"Old noblewomen.",
"Gamblers and thieves.",
"Priests and monks.",
"Priestesses.",
"Constables and sheriffs.",
"Castle or town guards.",
"Cooks and scullery maids.",
"Barkeeps and barmaids.",
"Harlots and madames.",
"Circus performers.",
"Foreign travelers and peasant girls.",
"Young children.",
"Miners and prospectors.",
"Elves and rangers.",
"Dwarves and gnomes.",
]},
{"title": "d10 The goblins’ are currently planning a raid on...", "id":"d10thegoblinsarecurrentlyplanningaraidon", "roll":[
"The residence of the leader or a senior gang member.",
"An artisan's shop or guildhall.",
"A merchant's office.",
"A tavern or inn.",
"A brothel.",
"A warehouse or shipyard.",
"A temple complex or shrine.",
"The town hall.",
"A shantytown",
"The residence of a wealthy individual or prominent citizen.",
]},
{"title": "d10 The goblins’ boss is...", "id":"d10thegoblinsbossis", "roll":[
"An egotistical goblin warrior.",
"A charismatic goblin rogue.",
"A mysterious goblin shaman.",
"A talented goblin thief.",
"A well-known goblin war hero.",
"A ruthless goblin hexer.",
"A cunning gobliness.",
"A brutal hobgoblin war priest.",
"A brilliant hobgoblin warlord.",
"A calculating bugbear assassin.",
]},
{"title": "d6 The goblins’ goals include (boss and rank-and-file members could have different goals)...", "id":"d6thegoblinsgoalsincludebossandrankandfilememberscouldhavedifferentgoals", "roll":[
"Disruption of the region’s politics.",
"Disruption of the region’s trade.",
"Revenge against a specific organization.",
"Revenge against a rival goblin gang.",
"Spreading chaos and destruction.",
"Possession of a powerful artifact.",
]},
{"title": "d12 The goblins typically fight with...", "id":"d12thegoblinstypicallyfightwith", "roll":[
"Swarm tactics.",
"Hit-and-run tactics.",
"Ambush tactics.",
"Choreographed maneuvers.",
"Unpredictable maneuvers.",
"Lots of smiles and jokes.",
"Lots of fancy footwork.",
"Lots of screaming and shouting.",
"Kicking and stomping.",
"Lots of head-butting.",
"Lots of biting and scratching.",
"Laying traps.",
]},
{"title": "d6 As enforcers or extra muscle, the goblins sometimes hire...", "id":"d6asenforcersorextramusclethegoblinssometimeshire", "roll":[
"Hobgoblin mercenaries.",
"Bugbear thugs.",
"Ogre savages.",
"Orc berserkers.",
"Trolls.",
"Other goblin gangs.",
]},
{"title": "d6 As guardians or pets, the goblins sometimes keep...", "id":"d6asguardiansorpetsthegoblinssometimeskeep", "roll":[
"Wolves.",
"Wargs.",
"Giant spiders.",
"Boars.",
"Giant bats.",
"Dire rats.",
]},
{"title": "d12 The goblin is particularly skilled at...", "id":"d12thegoblinisparticularlyskilledat", "roll":[
"Being sneaky.",
"Not being seen.",
"Tracking foes.",
"Building traps.",
"Avoiding traps.",
"Repairing traps.",
"Foraging for food and water.",
"Wrangling beasts.",
"Digging tunnels.",
"Crafting arms and armor.",
"Crushing skulls.",
"Cutting throats.",
]},
{"title": "d12 The goblin wields...", "id":"d12thegoblinwields", "roll":[
"A rusty sword.",
"A finely-made sword",
"A spiked club.",
"A wicked looking axe.",
"A spear decorated with feathers.",
"Several polished daggers.",
"A large, serrated dagger.",
"A pair of curved daggers.",
"A cracked wooden shield.",
"A shield, emblazoned with the gangs’ symbol.",
"Arrows fletched with crow feathers.",
"Arrows fletched with hawk feathers.",
]},
{"title": "d12 The goblin wears...", "id":"d12thegoblinwears", "roll":[
"Armor with greasy stains.",
"Patched leather armor.",
"Piecemeal chain armor.",
"A leather helm.",
"A large skull as a helm.",
"A wolf-face helm.",
"A lanyard of severed ears.",
"A big hoop earring.",
"A shiny silver belt.",
"A wolf skin.",
"A black cloak with a hood.",
"A large belt purse.",
]},
{"title": "d12 The goblin’s face has...", "id":"d12thegoblinsfacehas", "roll":[
"Blue warpaint.",
"An eyepatch.",
"Burn scars.",
"Only one ear.",
"No front teeth.",
"An unusual tattoo on the forehead.",
"Stitches closing a wound on the jaw.",
"A topknot above it.",
"Several muddy smudges.",
"A boil oozing pus.",
"A wisp of a mustache.",
"Amazing sideburns.",
]},
{"title": "d8 The goblin has...", "id":"d8thegoblinhas", "roll":[
"An unsettling stare.",
"A lean and hungry look.",
"A maniacal laugh.",
"A mad cackling laugh.",
"A high-pitched twittering laugh.",
"A tendency to snicker at everything.",
"A nervous twitch.",
"A difficult time standing still.",
]},
{"title": "d8 Coloring: The lizardolk's scales are...", "id":"d8coloringthelizardolksscalesare", "roll":[
"Mottled green and brown.",
"Dull and green.",
"Shiny and green.",
"Green with black stripes.",
"Black and grey.",
"Brown with black stripes.",
"Mottled black and brown.",
"Brown and grey.",
]},
{"title": "d8 Mannerism: The lizardfolk has...", "id":"d8mannerismthelizardfolkhas", "roll":[
"An unsavory habit of licking its lips.",
"Shifty eyes.",
"A nervous, hissing laugh.",
"Eyes that never blink.",
"A tongue that protrudes when it speaks.",
"A crest atop its head.",
"Two ridges starting above the brow and running down its head and neck.",
"Sagging folds of skin on its throat.",
]},
{"title": "d10 Profession: The lizardfolk is...", "id":"d10professionthelizardfolkis", "roll":[
"A savvy hunter.",
"A deadly tracker.",
"A skilled scout.",
"A savage berserker.",
"A dim-witted brute.",
"A celebrated warrior.",
"A powerful shaman.",
"An eerie mystic.",
"A scaly shapeshifter.",
"A cold-blooded killer.",
]},
{"title": "d6 Goal: The lizardfolk is looking for...", "id":"d6goalthelizardfolkislookingfor", "roll":[
"New waters for fishing and hunting.",
"The tracks of an intruder in the region.",
"The lair of a troublesome beast.",
"Safe nesting grounds.",
"Decent arms and armor.",
"Fresh meat.",
]},
{"title": "d12 Possessions: The lizardfolk carries...", "id":"d12possessionsthelizardfolkcarries", "roll":[
"A scimitar and a wooden shield.",
"A scimitar and a short bow.",
"A spear and a blowgun.",
"A curved dagger and a blowgun.",
"A curved dagger with feathers on the hilt.",
"A handaxe and a shortbow.",
"An oversized club.",
"A wooden club and a wooden shield.",
"A milky white gem fastened about the neck.",
"A string of trophies fastened about the neck (d4): 1. ears; 2. finger bones; 3. scalps; 4. teeth.",
"A gnarled wooden staff.",
"A string of beads made from a variety of materials (d8): 1. bone; 2. clay; 3. copper; 4. silver; 5. stone; 6. teeth; 7. tin; 8. wood.",
]},
{"title": "d12 The beastshifter transforms into...", "id":"d12thebeastshiftertransformsinto", "roll":[
"A grizzly bear.",
"A black bear.",
"A wild boar.",
"A oversized black rat.",
"A large brown rat.",
"A lanky grey rat.",
"A fierce tiger.",
"A grey wolf.",
"A mottled brown and grey wolf.",
"A reddish brown wolf.",
"A dark brown or black wolf.",
"A white wolf.",
]},
{"title": "d6 The beastshifter transforms involuntarily...", "id":"d6thebeastshiftertransformsinvoluntarily", "roll":[
"Whenever it is in moonlight.",
"On nights when a full moon occurs.",
"On nights when the moon is half full or more.",
"Whenever the leader of its pack or clan transforms.",
"Whenever it becomes enraged.",
"Never; it is in complete control of its power.",
]},
{"title": "d8 While transformed, the beastshifter behaves...", "id":"d8whiletransformedthebeastshifterbehaves", "roll":[
"Mostly as a normal beast of its type.",
"As an unusually intelligent version of the beast of its type.",
"More like a human than a beast.",
"As a skilled hunter.",
"As a cautious predator.",
"As a savage predator.",
"As a frightened beast.",
"Violently, spreading blood and chaos.",
]},
{"title": "d8 The beastshifter lives...", "id":"d8thebeastshifterlives", "roll":[
"Alone among humans, hiding its powers.",
"Alone among humans who know and accept its powers.",
"Alone as an outcast from human society.",
"Among other beastshifters integrated into human society.",
"Among other beastshifters as outcasts from human society.",
"Among other beastshifters, hiding their powers from society.",
"Among other beastshifters, apart from human society.",
"Alone as an outcast from its pack or clan.",
]},
{"title": "d12 The beastshifter makes its home...", "id":"d12thebeastshiftermakesitshome", "roll":[
"In a cave.",
"In a swamp.",
"On a vast plain.",
"In a forest.",
"In a cottage in the woods.",
"Hidden in the mountains.",
"In a quiet village.",
"Just outside a quiet village.",
"Down a dark alley in the city.",
"In the city sewers.",
"On a quiet residential street in the city.",
"In or near a castle or palace.",
]},
{"title": "d8 The beastshifter has a tendency to...", "id":"d8thebeastshifterhasatendencyto", "roll":[
"Lose its temper easily.",
"Speak in low growls (or squeaks), making it difficult for others to understand when excited.",
"Recoil from touching anything made of silver.",
"Get nervous in moonlight.",
"Lick its lips hungrily all the time.",
"Fidget or pace when in indoor spaces.",
"Daydream about hunting in its beast form.",
"Sniff people upon meeting them.",
]},
{"title": "d8 In humanoid form, the beastshifter fights with...", "id":"d8inhumanoidformthebeastshifterfightswith", "roll":[
"Hit-and-run tactics.",
"Making a mad charge.",
"Kicking and stomping.",
"Sharp claws.",
"Sharp teeth.",
"Lots of taunts and jeers.",
"Lots of screaming and shouting.",
"Lots of head-butting.",
]},
{"title": "d12 In humanoid form, the beastshifter presents itself as...", "id":"d12inhumanoidformthebeastshifterpresentsitselfas", "roll":[
"A farmer or herder.",
"A miner or fisher.",
"A beggar or urchin.",
"A noble or knight.",
"A barkeep or barmaid.",
"A barbarian or gladiator.",
"An herbalist or healer.",
"A soldier or sell-sword.",
"A hunter or assassin.",
"A thief or bandit.",
"A smuggler or con artist.",
"A sailor or pirate.",
]},
{"title": "d12 In humanoid form, the beastshifter’s face has...", "id":"d12inhumanoidformthebeastshiftersfacehas", "roll":[
"Unsightly nose and ear hair.",
"A garish earring.",
"An empty eye socket.",
"A grisly scar.",
"A grim look.",
"Sad puppy-dog eyes.",
"A nervous grin.",
"An toothy grin.",
"A frame of long, beautiful long hair.",
"Ferocious sideburns.",
"An unruly beard.",
"An intimidating mustache.",
]},
{"title": "d20 The beastshifter’s favorite prey are...", "id":"d20thebeastshiftersfavoritepreyare", "roll":[
"Foreigners and travelers.",
"Beggars and drunks.",
"Young men.",
"Young women.",
"Old women.",
"Old noblewomen.",
"Priests and monks.",
"Priestesses.",
"Harlots and madames.",
"Farmwives and peasant girls.",
"Young children.",
"Rabbits and hares.",
"Squirrels and chipmunks.",
"Pheasants and other gamefowl.",
"Ducks and other waterfowl.",
"Mice and rats.",
"Pigeons and doves.",
"Sheep and goats.",
"Chickens and turkeys.",
"Dogs and cats.",
]},
{"title": "d8 The pack is...", "id":"d8thepackis", "roll":[
"A band of exiles and outcasts.",
"A roving band of outlaws and thieves.",
"A nomadic warrior clan.",
"A band of sought-after mercenaries.",
"An integral part of the local thieves’ or assassins’ guild.",
"A mercenary company in the service of a local lord or city watch.",
"A wild bunch of hunters and killers.",
"An ancient clan of warrior-hunters.",
]},
{"title": "d12 The pack’s leader is...", "id":"d12thepacksleaderis", "roll":[
"A dangerous megalomaniac.",
"A charismatic demagogue.",
"A mysterious foreigner.",
"A talented thief.",
"An outcast from a prominent family.",
"A ruthless killer.",
"A femme fatale.",
"A former arena champion.",
"A disgraced knight.",
"A brutish thug.",
"A de-frocked priest.",
"A well-known fugitive.",
]},
{"title": "d6 The pack’s attitude toward their leader is...", "id":"d6thepacksattitudetowardtheirleaderis", "roll":[
"Friendly and loyal.",
"Respectful and business-like.",
"Cautious and uncertain.",
"Terrified and tight-lipped.",
"Disappointed and disrespectful.",
"Agitated and restless.",
]},
{"title": "d6 The pack’s goals include...", "id":"d6thepacksgoalsinclude", "roll":[
"Becoming the region’s dominant predators.",
"Revenge against a rival band of lycanthropes or outlaws.",
"Revenge against the region’s elite.",
"Rebellion against the region’s elite.",
"A quiet and peaceful existence.",
"Violence to slake their bloodlust.",
]},
{"title": "d20 The beastshifter transforms into...", "id":"d20thebeastshiftertransformsinto", "roll":[
"A badger.",
"A bat.",
"A cat.",
"A crocodile.",
"A dog.",
"A dolphin.",
"A fox.",
"A hyena.",
"A jackal.",
"A jaguar.",
"A leopard.",
"A lion.",
"An owl.",
"A panther.",
"A raven.",
"A seal.",
"A serpent.",
"A shark.",
"A spider.",
"A swine.",
]},
{"title": "d12 The orcs are...", "id":"d12theorcsare", "roll":[
"Nomadic hunters, following game.",
"Raiders displaced from their native lands.",
"In exile from their native lands.",
"In the service of a sovereign warlord.",
"A loose confederacy of tribes and families related by blood.",
"Degenerate survivors from a broken army.",
"Disorganizes; a clan of competing warriors.",
"A tight-knit war band.",
"Bent on sowing chaos and mayhem.",
"Raiders after supplies and slaves.",
"Marching to war under the leadership of a great chief.",
"On an errand for an evil wizard or other powerful being.",
]},
{"title": "d12 The orcs value...", "id":"d12theorcsvalue", "roll":[
"Bravery.",
"Strength.",
"Wisdom.",
"Virility.",
"Honoring the gods.",
"Honoring their ancestors.",
"Battle-scars.",
"Survival.",
"Kill counts.",
"Scalps.",
"Steel.",
"Meat.",
]},
{"title": "d4 The orcs’ iconography features...", "id":"d4theorcsiconographyfeatures", "roll":[
"Symbols of death and destruction (d10): 1. bats; 2. blood; 3. bones; 4. corpses; 5. crows; 6. flames; 7. ghosts; 8. scorpions; 9. skulls; 10. vultures.",
"Symbols of the heavens (d6): 1. clouds; 2. lightning; 3. moon; 4. snow; 5. stars; 6. sun.",
"Symbols of strength and weaponry (d6): 1. arrows; 2. axes; 3. fists; 4. spears; 5. stones; 6. swords.",
"A great beast (d8): 1. bears; 2. boars; 3. eagles; 4. horses; 5. lions; 6. owls; 7. snakes; 8. wolves.",
]},
{"title": "d10 The orcs’ chief is...", "id":"d10theorcschiefis", "roll":[
"A well-respected chief.",
"A charismatic warlord.",
"A mysterious shaman.",
"A descendent of an honored hero.",
"A ruthless killer.",
"A brutish thug.",
"An impatient young warrior.",
"A wise old chief.",
"A celebrated war hero.",
"A prolific lover.",
]},
{"title": "d12 The orcs’ favorite meat comes from...", "id":"d12theorcsfavoritemeatcomesfrom", "roll":[
"Dwarves and halflings.",
"Beggars and thieves.",
"Merchants and caravan guards.",
"Noblemen.",
"Noblewomen.",
"Priests and priestesses.",
"Slaves.",
"Circusfolk and minstrels.",
"Foreign travelers.",
"Peasant women.",
"Young children.",
"Elves and pixies.",
]},
{"title": "d8 The orcs fear...", "id":"d8theorcsfear", "roll":[
"Men armored in steel.",
"Human women.",
"Spellcasters.",
"Members of a particular race (d4): 1. dwarves; 2. elves; 3. goblinoids; 4. reptilian humanoids.",
"A particular natural phenomenon (d6): 1. blizzards; 2. earthquakes; 3. floods; 4. thunderstorms; 5. volcanoes; 6. typhoons.",
"The gods.",
"Aberrant evils.",
"Dragons.",
]},
{"title": "d10 The orcs are notorious for...", "id":"d10theorcsarenotoriousfor", "roll":[
"Never leaving survivors.",
"Feeding prisoners to wild beasts.",
"Tattooing or branding prisoners.",
"Scalping enemies.",
"Flaying enemies.",
"Raiding and burning villages.",
"Plundering merchant caravans.",
"Eating prisoners raw.",
"Claiming prisoners as slaves.",
"Taking prisoners as wives, concubines, or catamites.",
]},
{"title": "d12 The orcs are known for...", "id":"d12theorcsareknownfor", "roll":[
"Screaming and shouting during battle.",
"Convening with ghosts and spirits.",
"Ritual animal sacrifice under the new moon.",
"Ritual humanoid sacrifice deep within the earth.",
"Ritualistic blood-letting.",
"Ritualistic sexual acts under the full moon.",
"Eating unusually-prepared meats.",
"Prolific amounts of drinking.",
"Never cutting their hair.",
"Shaving their heads and bodies.",
"Wearing long top-knots or braids.",
"Bathing and perfuming their bodies.",
]},
{"title": "d6 The orcs’ attitude is...", "id":"d6theorcsattitudeis", "roll":[
"Rowdy and festive.",
"Joyful and eager to fight.",
"Relaxed and carefree.",
"Frightened and suspicious.",
"Hostile and suspicious.",
"Hostile and eager to fight.",
]},
{"title": "d6 The orcs’ goals include (chief and lower-ranking members could have different goals)...", "id":"d6theorcsgoalsincludechiefandlowerrankingmemberscouldhavedifferentgoals", "roll":[
"Upheaval of the region’s politics.",
"Disruption of the region’s trade.",
"Revenge against another civilization.",
"Revenge against a rival orkish clan.",
"Spreading chaos and destruction.",
"Possession of a powerful artifact.",
]},
{"title": "d8 The orcs typically fight with...", "id":"d8theorcstypicallyfightwith", "roll":[
"Hit-and-run tactics.",
"Ambush tactics.",
"Unpredictable maneuvers.",
"Lots of screaming and shouting.",
"Kicking and stomping.",
"Lots of head-butting.",
"Lots of biting and scratching.",
"Frequent breaks for (d4): 1. eating; 2. looting corpses; 3. re-forming ranks; 4. arguing among themselves.",
]},
{"title": "d6 As guardians or pets, the orcs sometimes keep...", "id":"d6asguardiansorpetstheorcssometimeskeep", "roll":[
"Boars.",
"Dire rats.",
"Giant lizards.",
"Ogres.",
"Wargs.",
"Wolves.",
]},
{"title": "d10 As slaves, the orcs keep...", "id":"d10asslavestheorcskeep", "roll":[
"Dwarves.",
"Gnomes.",
"Goblins.",
"Halflings.",
"Humans.",
"Kobolds.",
"Undead servitors.",
"Nothing; the orcs eat any captives they take.",
"Nothing; the orcs leave no survivors.",
"Nothing; the orcs believe in freedom for all beings.",
]},
{"title": "d12 Most of the orcs are wielding...", "id":"d12mostoftheorcsarewielding", "roll":[
"Spears and large hunting knives.",
"Spears and javelins.",
"Exotic, curved blades and several bolas.",
"Huge, curved blades.",
"Exotic, curved blades and blowguns.",
"Pikes and shortswords.",
"Pikes and short bows.",
"Battleaxes and throwing axes.",
"Battleaxes and longbows.",
"Longswords and longbows.",
"Jagged greatswords and shortbows.",
"Greataxes and javelins.",
]},
{"title": "d8 Appearance: The orc has...", "id":"d8appearancetheorchas", "roll":[
"Pale green skin.",
"Yellowish green skin.",
"Dirty brown skin.",
"Reddish brown skin.",
"Grey skin.",
"A tall frame.",
"A thick-set frame.",
"Bug eyes.",
]},
{"title": "d6 Tattoo: The orc has...", "id":"d6tattootheorchas", "roll":[
"A bone tattoo.",
"A dragon tattoo.",
"A skull tattoo.",
"A spear tattoo.",
"A spiderweb tattoo.",
"A tattoo of thorns.",
]},
{"title": "d8 Role: The orc is...", "id":"d8roletheorcis", "roll":[
"A ferocious berserker.",
"A rage-filled killer.",
"A persistent hunter.",
"A fearless scout.",
"A masterful strategist.",
"A mighty leader.",
"A grim mystic (d4): 1. bone shaman; 2. blood shaman; 3. earth shaman; 4. moon shaman.",
"An eager warrior.",
]},
{"title": "d8 Skill: Even among orcs, the orc is particularly good at...", "id":"d8skillevenamongorcstheorcisparticularlygoodat", "roll":[
"Tracking creatures by scent.",
"Identifying and following the tracks of creatures.",
"Running down prey.",
"Decapitating foes.",
"Impaling foes.",
"Roping captives.",
"Breaking slaves.",
"Handling savage beasts.",
]},
{"title": "d8 Armor: The orc is armored in...", "id":"d8armortheorcisarmoredin", "roll":[
"Nothing.",
"Tattered leather.",
"Blood-stained leather.",
"Boiled leather.",
"The hides of scaly beasts.",
"The hides of furry beasts.",
"The hides of exotic beasts.",
"A helm and breastplate taken from a fallen enemy.",
]},
{"title": "d8 Weapon: The orc is wielding...", "id":"d8weapontheorciswielding", "roll":[
"A spear.",
"A scimitar.",
"A falchion..",
"A pike.",
"A battleaxe.",
"A greatsword.",
"A greataxe.",
"A longbow.",
]},
{"title": "d6 Motivation: The orc is looking for...", "id":"d6motivationtheorcislookingfor", "roll":[
"A good meal, fresh if possible.",
"A hearty meal, spoiled is not a problem.",
"A throat to cut or a head to bash.",
"A chance to prove itself in combat.",
"A place to rest and to sharpen weapons.",
"A strong drink.",
]},
{"title": "d10 Profession: The cultist is...", "id":"d10professionthecultistis", "roll":[
"A cunning warrior.",
"A battle-tested soldier.",
"A stealthy assassin.",
"A fanatical priest or priestess.",
"A newly initiated acolyte.",
"A charismatic preacher.",
"A foolish zealot.",
"A raving madman or madwoman.",
"A scaly shapeshifter.",
"An enthusiastic poisonmaker.",
]},
{"title": "d12 Scaly Obsession: The cultist is particularly fond of or fearful of...", "id":"d12scalyobsessionthecultistisparticularlyfondoforfearfulof", "roll":[
"Cobras and asps.",
"Rattlers and sidewinders.",
"Pythons and boas.",
"Sea snakes.",
"Black dragons.",
"Green dragons.",
"Female medusas.",
"Male medusas.",
"Giant snakes.",
"Yuan-ti malisons.",
"Yuan-ti abominations.",
"Yuan-ti halfbloods.",
]},
{"title": "d10 Distinguishing Feature: The cultist has...", "id":"d10distinguishingfeaturethecultisthas", "roll":[
"A bandaged thumb.",
"A tattoo on the face.",
"A tear at the knee of his or her robe.",
"A forked tongue.",
"A nervous twitch.",
"Almost no nose.",
"An unsettling laugh.",
"A large scar on the throat.",
"A profuse amount of sweat soaking through his or her robes.",
"A hissing lisp when he or she speaks.",
]},
{"title": "d6 Goal: The cultist is looking to...", "id":"d6goalthecultistislookingto", "roll":[
"Recruit new members to the cult.",
"Warn outsiders away from the cult.",
"Collect captives for human sacrifice.",
"Lead travelers into a trap near the cult's shrine or temple.",
"Escape from the clutches of the cult's leadership.",
"Slip some poison into someone’s drink.",
]},
{"title": "d8 Possessions: The cultist carries or wears...", "id":"d8possessionsthecultistcarriesorwears", "roll":[
"Several eggs stolen from a snake’s nest.",
"A necklace or bracelet of snake fangs.",
"Snakeskin armor or boots.",
"A book of prayers and curses.",
"A sharp, ceremonial dagger.",
"A scimitar and a set of lightweight, supple armor.",
"A constrictor snake fashioned like a scarf about the shoulders.",
"Several doses of a deadly poison.",
]},
{"title": "d8 The treeperson is...", "id":"d8thetreepersonis", "roll":[
"A dryad enchantress.",
"A dryad protector.",
"A dryad witch.",
"A dryad oracle.",
"A treant loreseeker.",
"A treant guardian.",
"A treant lorekeeper.",
"A treant elder.",
]},
{"title": "d12 Appearance: The treeperson could be described as...", "id":"d12appearancethetreepersoncouldbedescribedas", "roll":[
"Tall.",
"Very tall.",
"Slender.",
"Sturdy.",
"Unwavering.",
"Bent.",
"Gnarled.",
"Knotty.",
"Weathered.",
"Moss-covered.",
"Withered.",
"Stumpy.",
]},
{"title": "d20 Features: The treeperson's bark and leaves are reminiscent of...", "id":"d20featuresthetreepersonsbarkandleavesarereminiscentof", "roll":[
"An apple or pear tree.",
"An ash.",
"A birch.",
"A beech.",
"A cedar or juniper.",
"A cherry or plum tree.",
"A chestnut or hazel tree.",
"A cypress.",
"An elm.",
"An fir.",
"A hawthorn or hemlock.",
"A hickory or walnut tree.",
"A linden or lime tree.",
"A maple.",
"An oak.",
"A pine.",
"A poplar.",
"A spruce.",
"A willow.",
"A yew or holly tree.",
]},
{"title": "d10 Personality: The treeperson is...", "id":"d10personalitythetreepersonis", "roll":[
"Sappy.",
"Soft-spoken.",
"Rooted.",
"Dry.",
"Patient.",
"Green.",
"Flowery.",
"Steady.",
"Prickly.",
"Thorny.",
]},
{"title": "d8 The treeperson is looking to...", "id":"d8thetreepersonislookingto", "roll":[
"Drive away intruders.",
"Warn intruders of dangers ahead.",
"Find a spot where a rare flower grows.",
"Nurture an ancient grove back to health.",
"Protect the oldest tree in the forest.",
"Eliminate any threats to the forest.",
"Plant trees where others been felled.",
"Talk after centuries of silence.",
]},
{"title": "d6 The treeperson carries...", "id":"d6thetreepersoncarries", "roll":[
"A magic acorn, nut, or other seed.",
"A clipping of ancient wood.",
"A rare moss with healing properties.",
"A deathly poison mushroom.",
"A sapling from an ancient tree.",
"A cudgel made from the wood of a legendary tree.",
]},
{"title": "d20 The person was...", "id":"d20thepersonwas", "roll":[
"A farmer or herder.",
"A miner or fisher.",
"A slave or servant.",
"A laborer or unskilled worker.",
"A beggar or urchin.",
"A noble or knight.",
"An artist or craftsman.",
"A merchant or shopkeeper.",
"A barkeep or barmaid.",
"A barbarian or gladiator.",
"A minstrel or singer.",
"A priest or monk.",
"An herbalist or healer.",
"A soldier or sell-sword.",
"A cultist or preacher",
"A hunter or assassin.",
"A thief or bandit.",
"A smuggler or con artist.",
"A sailor or pirate.",
"An alchemist or seer.",
]},
{"title": "d20 The person died from...", "id":"d20thepersondiedfrom", "roll":[
"Hanging or strangulation.",
"Beheading.",
"A stab wound or beating.",
"Blunt trauma or being crushed.",
"Drowning.",
"A plague.",
"A gastrointestinal illness.",
"A respiratory illness.",
"An infected wound.",
"Poisoning.",
"Falling from a great height.",
"A horse or wagon accident.",
"A venereal disease.",
"An allergic reaction.",
"Shock.",
"A heart attack or stroke.",
"Liver failure.",
"Old age.",
"Natural causes.",
"Unknown causes or under mysterious circumstances.",
]},
{"title": "d12 The person's spirit lingers...", "id":"d12thepersonsspiritlingers", "roll":[
"To seek vengeance.",
"To pine for lost love.",
"To bemoan lost treasure.",
"Out of pure hatred of the living.",
"Out of jealousy of the living.",
"To covet the belongings of a specific individual.",
"To provide protection to a specific someone.",
"To warn a specific someone against danger.",
"To warn everyone against a specific danger.",
"To torment a specific someone.",
"To torment members of a specific group.",
"To torment anyone who crosses its path.",
]},
{"title": "d12 The person's spirit can move on if...", "id":"d12thepersonsspiritcanmoveonif", "roll":[
"Someone helps it achieve it's goal.",
"It saves the life of at least one other person.",
"It achieves its goal on its own.",
"It is destroyed.",
"It is driven from its current location.",
"It is given evidence of events that happened after the person's death.",
"It is made aware of the circumstances of the person's death.",
"It is forced to visit the location of the person's death.",
"It is given the opportunity to speak to a loved one.",
"It sufficiently satisfies its lust for blood.",
"It sufficiently satisfies its lust for human touch.",
"The Hells freeze over.",
]},
{"title": "d6 The spirit’s initial reaction when it encounters living creatures is...", "id":"d6thespiritsinitialreactionwhenitencounterslivingcreaturesis", "roll":[
"Hostile and aggressive.",
"Hostile and suspicious.",
"Nervous and frightened.",
"Mostly indifferent.",
"Completely indifferent.",
"Curious but suspicious.",
"Curious and playful.",
"Desperate and aggressive.",
]},
{"title": "d10 The person's spirit is...", "id":"d10thepersonsspiritis", "roll":[
"Occupying its original body, showing no signs of decay.",
"Occupying its original body, showing some signs of decay.",
"Occupying its original body, badly decomposed.",
"Occupying its original body, only bare bones remain.",
"Occupying the corpse of someone else.",
"Occupying the living body of a stranger.",
"Occupying the living body of someone the person new.",
"Occupying the living body of a beast.",
"Occupying part of its original body (skull or hand).",
"Occupying part of someone else’s corpse (skull or hand).",
]},
{"title": "d6 The creature moves...", "id":"d6thecreaturemoves", "roll":[
"With a shambling gait.",
"With an awkward limp.",
"Lurching unpredictably.",
"With more of shimmy than a walk.",
"Taking slow, steady steps.",
"With surprising quickness and agility.",
]},
{"title": "d12 The creature has...", "id":"d12thecreaturehas", "roll":[
"A tattered shirt.",
"A missing arm, leg, or finger.",
"Only one eye.",
"A club foot.",
"Long-scraggly hair.",
"Chattering teeth.",
"Large crude stitches in its side.",
"An awful hunchback.",
"Incredibly long fingernails.",
"Drool on its chin.",
"Buck teeth.",
"A creepy mustache.",
]},
{"title": "d10 The spirit is...", "id":"d10thespiritis", "roll":[
"Incorporeal, invisible, and incapable of affecting its material surroundings.",
"Incorporeal, invisible, and capable of moving small objects.",
"Incorporeal, invisible, but capable of making itself seen.",
"Incorporeal, invisible, and hidden within an inanimate object (d4): 1. chest; 2. drawer; 3. kettle; 4. wardrobe.",
"Incorporeal, visible, but incapable of affecting it's material surroundings.",
"Incorporeal, visible, and capable of significant mischief and harm.",
"Incorporeal, extraordinarily beautiful, and capable of mischief and harm.",
"Incorporeal, wretched and slimy, and capable of mischief and harm.",
"Incorporeal, glowing blue or green, and capable of mischief and harm.",
"Incorporeal, visible, but in an unrecognizable form (d6): 1. mist or fog; 2. animal shape; 3. floating skull; 4. faint glow; 5. pool of shadows; 6. spectral hand.",
]},
{"title": "d6 The spirit moves...", "id":"d6thespiritmoves", "roll":[
"By creeping, oozelike, across the ground.",
"Smoothly, gliding above the grond.",
"Taking slow, fluid steps.",
"Lightly, rarely touching the ground.",
"Much quicker than you expect it to.",
"By teleporting in a swirl of shadows.",
]},
{"title": "d10 The spirit appears to be...", "id":"d10thespiritappearstobe", "roll":[
"Severely bloated.",
"Moaning in anguish.",
"Snarling at you.",
"Breathing heavily.",
"Cowering in fear.",
"Poised to strike.",
"Gently bobbing up and down.",
"Wind-blown and haggard.",
"Fidgeting nervously.",
"Oozing ectoplasm.",
]},
{"title": "d12 In life, the vampire was...", "id":"d12inlifethevampirewas", "roll":[
"An alchemist or pyromancer.",
"An assassin or poisonmaker.",
"A barkeep or barmaid.",
"A con artist or gambler.",
"A harlot or madame.",
"A hunter or woodsman.",
"A knight or sell-sword.",
"A lord or lady.",
"A priest or monk.",
"A sailor or pirate.",
"A seer or mystic.",
"A thief or smuggler.",
]},
{"title": "d12 Often, the vampire poses as...", "id":"d12oftenthevampireposesas", "roll":[
"A powerful noble.",
"An eccentric scholar.",
"A mysterious foreigner.",
"A talented artist.",
"A polite shopkeeper.",
"A creepy peddler.",
"A femme fatale.",
"A charming rogue.",
"A friendly barkeep or barmaid.",
"A charismatic entertainer.",
"A religious fanatic.",
"A veteran soldier.",
]},
{"title": "d12 In addition to draining blood, the vampire is fond of...", "id":"d12inadditiontodrainingbloodthevampireisfondof", "roll":[
"Shooting prey with an arrow or bolt from range.",
"Impaling prey.",
"Gutting or eviscerating prey.",
"Flaying prey.",
"Beheading prey.",
"Strangling prey.",
"Hanging prey.",
"Burying prey alive.",
"Drowning prey.",
"Throwing prey off a roof.",
"Severely beating prey.",
"Dismembering prey.",
]},
{"title": "d8 The vampire’s goals include...", "id":"d8thevampiresgoalsinclude", "roll":[
"Procreating.",
"Corrupting and influencing the politics of the city or region.",
"Domination of the city or region’s politics.",
"Revenge against a rival vampire.",
"Revenge against a living person, family, or organization.",
"Seeking hedonistic pleasure.",
"Uncovering ancient secrets of death and undeath.",
"Enslaving the living to create an easy source of food for vampires.",
]},
{"title": "d10 The vampire’s base of operations is...", "id":"d10thevampiresbaseofoperationsis", "roll":[
"A beautiful manor house.",
"A run-down castle.",
"An ancient fortress.",
"A quaint house on a quiet street.",
"A tavern.",
"A brothel.",
"An unpleasant underground lair.",
"A crypt in a graveyard.",
"A crypt beneath a temple.",
"The vampire is a transient.",
]},
{"title": "d6 The vampire prefers to hunt...", "id":"d6thevampirepreferstohunt", "roll":[
"Just before sunrise.",
"Just after sunset.",
"In the early evening.",
"Well into the night.",
"The toll of midnight.",
"After midnight.",
]},
{"title": "d20 The vampire’s favorite prey are...", "id":"d20thevampiresfavoritepreyare", "roll":[
"Fishermen and sailors.",
"Beggars and thieves.",
"Merchants and moneychangers.",
"Young noblemen.",
"Young noblewomen.",
"Old noblewomen.",
"Gamblers and drunks.",
"Priests and monks.",
"Priestesses.",
"Serving girls.",
"Slaves.",
"Barmaids.",
"Harlots and madames.",
"Circus performers.",
"Foreign travelers.",
"Farmwives.",
"Peasant girls.",
"Inquisitive children.",
"Young children.",
"Elves and the fey.",
]},
{"title": "d12 The vampire refuses to feed on...", "id":"d12thevampirerefusestofeedon", "roll":[
"Ugly women.",
"Beautiful women.",
"Pregnant women.",
"Shy children.",
"Bold children.",
"Anyone with blue eyes.",
"Anyone with green eyes.",
"Anyone with blonde hair.",
"Anyone with red hair.",
"Anyone who is blind, deaf, or lame.",
"Big burly men.",
"Dwarves and underground dwellers.",
]},
{"title": "d6 The vampire can shapeshift to take the form of...", "id":"d6thevampirecanshapeshifttotaketheformof", "roll":[
"A tiny bat.",
"A swarm of bats.",
"A cloud of mist.",
"A swirl of shadows.",
"A wolf.",
"A giant bat.",
]},
{"title": "d8 Even among vampires, the vampire is quite good at...", "id":"d8evenamongvampiresthevampireisquitegoodat", "roll":[
"Charming humanoids.",
"Frightening humanoids.",
"Draining blood quickly.",
"Sniffing out living creatures.",
"Traveling overland quickly.",
"Disguising its true nature.",
"Negotiations.",
"Climbing.",
]},
{"title": "d6 The vampire’s gravedirt is from...", "id":"d6thevampiresgravedirtisfrom", "roll":[
"A faraway land.",
"A local cemetery or temple.",
"A country village or manor.",
"A well-known castle or fortress.",
"A battlefield.",
"A remote forest or mountain.",
]},
{"title": "d10 The vampire’s associates include...", "id":"d10thevampiresassociatesinclude", "roll":[
"Less powerful vampires.",
"Skeletons, zombies, and other undead thralls.",
"Living thralls on which to feed.",
"Living thralls who provide pleasurable diversions.",
"Hundreds of bats.",
"Rats and maggots.",
"A pack of vicious wolves.",
"Members of a death cult.",
"The local nobility.",
"The local band of outlaws or assassins’ guild.",
]},
{"title": "d12 Even among vampires, the vampire is especially...", "id":"d12evenamongvampiresthevampireisespecially", "roll":[
"Agile.",
"Attractive.",
"Charming.",
"Cruel.",
"Domineering.",
"Intimidating.",
"Quick.",
"Sadistic.",
"Sleazy.",
"Smooth.",
"Sneaky.",
"Witty.",
]},
{"title": "d10 The vampire often wears...", "id":"d10thevampireoftenwears", "roll":[
"Shiny leather boots.",
"A black cape with a hood.",
"A black cape with a high collar.",
"A wide-brimmed hat.",
"A cap pulled low.",
"A low-cut shirt.",
"Tight-fitting clothes.",
"A family signet ring.",
"An unusual brooch or necklace.",
"A waxy mustache.",
]},
{"title": "d12 The vampire is unusually fond of or particular regarding...", "id":"d12thevampireisunusuallyfondoforparticularregarding", "roll":[
"Horticulture and floral arrangements.",
"Fashion trends.",
"Arms and armor maintenance.",
"Small animals.",
"Horses.",
"High quality fabrics and leathers.",
"Foreign music.",
"Theater troupes and dancers.",
"Social status.",
"Personal hygiene.",
"Hair styles.",
"Dental hygiene.",
]},
{"title": "d8 The vampire is particularly afraid of or takes special care to avoid...", "id":"d8thevampireisparticularlyafraidofortakesspecialcaretoavoid", "roll":[
"Hallowed places.",
"Densely populated areas.",
"Sunlight.",
"Running water.",
"Sharp wooden objects.",
"Garlic.",
"Silver objects.",
"Relics of the gods.",
]},
{"title": "d20 The witch is...", "id":"d20thewitchis", "roll":[
"A femme fatale.",
"The wife of a farmer, fisherman, or miner.",
"The wife of a soldier.",
"An old seamstress or weaver.",
"A peasant girl.",
"A noble woman.",
"A slave or servant.",
"An attractive shopkeeper.",
"A stern barmaid.",
"An old fortune teller.",
"A talented dancer or singer.",
"A heretical priestess.",
"An herbalist or healer.",
"A skilled hunter.",
"A very young girl",
"The daughter of a thief.",
"The daughter of a sailor.",
"An old crone.",
"An old widow.",
"An attractive young widow.",
]},
{"title": "d10 The witch learned her craft from...", "id":"d10thewitchlearnedhercraftfrom", "roll":[
"A fellow witch who kidnapped her as a young girl.",
"A fellow witch who aided her in a time of need.",
"A neighbor.",
"Her mother.",
"Her older sister.",
"Her grandmother.",
"Books of forbidden lore.",
"Communication with the spirits of the dead.",
"Consorting with a fiend.",
"Participating in bacchanalian fey orgies.",
]},
{"title": "d12 The witch specializes in...", "id":"d12thewitchspecializesin", "roll":[
"Charms.",
"Clairvoyance.",
"Communing with the dead.",
"Conjuring evil spirits.",
"Curses.",
"Demonology.",
"Enchantments.",
"Herbalism.",
"Hexes.",
"Poisons.",
"Potions.",
"Prophecies.",
]},
{"title": "d10 Trade: For coin or barter, the witch will...", "id":"d10tradeforcoinorbarterthewitchwill", "roll":[
"Read your palm.",
"Gaze into her crystal ball.",
"Contact a dead relative or friend.",
"Place a hex on an enemy.",
"Give you a piece of forbidden magical lore.",
"Enchant an item.",
"Curse an item.",
"Prepare an herbal remedy.",
"Prepare a potion.",
"Give you an old family recipe.",
]},
{"title": "d12 The witch is seeking...", "id":"d12thewitchisseeking", "roll":[
"The means to summon a fiend.",
"The means to control a fiend.",
"Eternal youth and beauty.",
"The soul of a specific person.",
"Vengeance against a powerful person.",
"A long lost recipe.",
"Instructions for a powerful ritual.",
"The wand of a legendary witch or wizard.",
"The staff of an ancient witch or wizard.",
"The meaning of a cryptic prophecy.",
"A baby or young child to steal.",
"A baby or young child to eat.",
]},
{"title": "d8 The witch has uncovered dark secrets. She cannot be killed by...", "id":"d8thewitchhasuncovereddarksecretsshecannotbekilledby", "roll":[
"Hanging or strangulation.",
"Drowning.",
"Burning.",
"Disease.",
"Poisoning.",
"The hand of a mortal man.",
"Falling from a great height.",
"Old age.",
]},
{"title": "d6 The witch prefers to travel by...", "id":"d6thewitchpreferstotravelby", "roll":[
"Flying broomstick.",
"Flying mount (giant owl or hippogriff).",
"Horseback.",
"Walking.",
"Transforming into a beast (d8): 1. bat; 2. cat; 3. fox; 4. horse; 5. owl; 6. rat; 7. raven; 8. wolf.",
"Teleportation.",
]},
{"title": "d10 The witch’s home is...", "id":"d10thewitchshomeis", "roll":[
"In a cave.",
"In a swamp.",
"On an island.",
"Beneath a large tree in a forest.",
"In a cottage in the woods.",
"Hidden in the mountains.",
"In a quiet village.",
"Just outside a quiet village.",
"Down a dark alley in the city.",
"In the castle or palace of a lord.",
]},
{"title": "d12 Distinguishing Feature: The witch has...", "id":"d12distinguishingfeaturethewitchhas", "roll":[
"A large wart on her nose.",
"An oversized, crooked nose.",
"A cute little button nose.",
"A beauty mark on her cheek.",
"A hairy mole on her cheek.",
"A jagged scar on her cheek.",
"An obnoxious cackling laugh.",
"A hideous belting laugh.",
"A nervous twittering laugh.",
"Long straggly hair.",
"Long beautiful hair.",
"Her hair pulled up.",
]},
{"title": "d10 The witch's brew is percolating in...", "id":"d10thewitchsbrewispercolatingin", "roll":[
"A delicate ceramic tea kettle.",
"A large cast iron cauldron.",
"A heavy-bottomed iron pot.",
"A thick cast iron vat.",
"A copper tea kettle.",
"A thick copper vat.",
"A heavy steel cook-pot.",
"A blackened steel cauldron.",
"A thick bronze cauldron.",
"A large bronze cook-pot.",
]},
{"title": "d20 The witch's brew in the cauldron contains...", "id":"d20thewitchsbrewinthecauldroncontains", "roll":[
"Eye of newt.",
"Toe of frog.",
"Wool of bat.",
"Tongue of dog.",
"Adder's fork.",
"Blind-worm's sting.",
"Lizard's leg.",
"Howlet's wing.",
"Monkey's paw.",
"Pint of blood.",
"Pound of flesh.",
"Cup of mud.",
"Beak of duck.",
"Housecat's tail.",
"Glob of mold.",
"Rusty nail.",
"Garlic bulb.",
"Cob of corn.",
"Stirge's foot.",
"Dryad's thorn.",
]},
{"title": "d8 The witch is currently brewing...", "id":"d8thewitchiscurrentlybrewing", "roll":[
"A love potion.",
"A fertility tonic.",
"A magical cure-all.",
"A terrible poison.",
"A component for a summoning ritual.",
"A component for a necromantic ritual.",
"A component for a polymorphing hex.",
"A component for a beguiling charm.",
]},
{"title": "d12 The witch’s familiar is...", "id":"d12thewitchsfamiliaris", "roll":[
"An elemental spirit (d8): 1. air; 2. earth; 3. fire; 4. ice; 5. mud; 6. storm; 7. stone; 8. water.",
"A fey spirit (d4): 1. animated toadstool; 2. pixie; 3. sprite; 4. talking songbird.",
"A fiendish spirit (d4): 1. demon trapped in a book; 2. devil trapped in a gem; 3. imp; 4. quasit.",
"An undead creature (d4): 1. crawling crawl; 2. disembodied voice; 3. floating skull; 4. formless ghost.",
"A bat.",
"A cat.",
"An owl.",
"A snake.",
"A spider.",
"A raven.",
"A rat.",
"A toad.",
]},
{"title": "d12 The witch’s familiar’s manner is...", "id":"d12thewitchsfamiliarsmanneris", "roll":[
"Calculating.",
"Clever.",
"Coy.",
"Cruel.",
"Gleeful.",
"Grumpy.",
"Insolent.",
"Shy.",
"Skittish.",
"Surly.",
"Suspicious.",
"Talkative.",
]},



// end of monsters

];
