// potions.js
//
// Random Potion: one click gives a bottle worth describing, not just an effect.
//
// The vessel is picked from six category tables, so a blown-glass phial and a
// wax lozenge are described by different lists. Twelve facets always roll: the
// liquid, how it behaves in the vessel, smell, taste, the stopper, the label,
// the effect, onset, how long it lasts, doses, worth and the brewer. Then ten
// tangents are chance-gated through percent_to, from a 65% side effect down to
// a 6% "this is not a potion", and each gate rolls a variant that consults its
// own leaf tables, so two bottles rarely share the shape of their entry.

top.potions = [
  /* ------------------------------------------------------------------
   * The vessel: one of these six is picked per potion
   * ---------------------------------------------------------------- */
  {
    title: "d12 Vessel - blown glass",
    id: "d12vesselglass_potions",
    roll: [
      "A slim phial of green glass with a bubble trapped in the neck.",
      "A round-bellied bottle that will not stand up without help.",
      "Clear glass, flawless, worth more empty than most potions are full.",
      "A phial blown in the shape of a sleeping bird, the tail as the stopper.",
      "Glass so thin it warms to the hand in seconds and chills just as fast.",
      "A squat bottle with a pontil scar sharp enough to catch a pocket.",
      "Amber glass, deliberately dark, so the contents cannot be judged by eye.",
      "A phial with a hairline crack that has never leaked and never will.",
      "Twin lobes joined at the neck, and the two halves do not match in colour.",
      "A bottle with a maker's mark on the base from a house that closed generations ago.",
      "Glass with a strand of something suspended inside the wall itself.",
      "A phial that rings when tapped, in a note that (d4): 1. holds far too long; 2. is always the same; 3. rises as it empties; 4. nobody else can hear",
    ],
  },
  {
    title: "d10 Vessel - clay and stoneware",
    id: "d10vesselclay_potions",
    roll: [
      "A stoneware bottle glazed salt-grey, cool in any weather.",
      "A red clay jug with a thumbprint fired into the shoulder.",
      "A tiny pot, unglazed, that sweats a little in the palm.",
      "A vessel sealed with a clay bung that must be broken to open.",
      "An apothecary jar with a painted label in a script nobody local reads.",
      "A pilgrim's flask stamped with a shrine that no longer stands.",
      "A crackle-glazed bottle whose surface pattern is slowly changing.",
      "A funeral urn, small, repurposed, and honest about it.",
      "A jug with two handles, meant to be passed and shared.",
      "A pot whose glaze is (d4): 1. still tacky; 2. warm; 3. singing faintly; 4. the wrong colour in candlelight",
    ],
  },
  {
    title: "d10 Vessel - metal",
    id: "d10vesselmetal_potions",
    roll: [
      "A pewter flask dented to the shape of somebody's hip.",
      "A brass ampoule sealed by solder, opened only by cutting.",
      "A silver phial gone black, except at the lip.",
      "An iron flask, heavy, banded, and cold enough to sting.",
      "A copper bottle gone green everywhere but a thumb-shaped patch.",
      "A gilded scent bottle with a chain for a wrist, out of place in a pack.",
      "A soldier's canteen with a name scratched out and another scratched over it.",
      "A lead vessel, which is a warning in itself.",
      "A screw-topped tube of tin with the thread worn nearly smooth.",
      "A metal flask that is (d4): 1. never the ambient temperature; 2. slightly magnetic; 3. lighter than empty metal; 4. sweating from the inside",
    ],
  },
  {
    title: "d10 Vessel - grown, not made",
    id: "d10vesselorganic_potions",
    roll: [
      "A gourd, dried and waxed, with a whittled plug.",
      "A drinking horn with a stoppered tip and a silver-banded rim.",
      "An eggshell sealed with wax, and the egg was not a chicken's.",
      "A wineskin that has held far worse things than wine.",
      "A hollow bone, capped both ends, warm at the joint.",
      "A seed pod the size of a fist that rattles when it should slosh.",
      "A section of thick reed, sealed with pitch at both nodes.",
      "A bladder tied with gut string, unpleasant to hold and perfectly effective.",
      "A nut with a screw of resin in the shell, opened by a twist and a prayer.",
      "A vessel that is unmistakably (d4): 1. still alive; 2. growing; 3. someone's; 4. regrowing its own stopper",
    ],
  },
  {
    title: "d10 Vessel - improvised",
    id: "d10vesselimprovised_potions",
    roll: [
      "A wine bottle with the original label soaked half off.",
      "An ink pot, rinsed once, with a faint black tidemark at the neck.",
      "A cheap perfume bottle, the atomiser removed and the hole plugged.",
      "A medicine bottle from a physician's kit, dosage marks on the side.",
      "A lantern's oil reservoir, unscrewed and carried separately.",
      "A jam jar with a cloth lid tied down with string.",
      "A powder horn that clearly did not hold powder last.",
      "A hip flask engraved to a person the carrier plainly is not.",
      "A vinegar cruet from an inn, and the inn is going to notice.",
      "Something borrowed in a hurry that still smells of (d4): 1. turpentine; 2. cheap brandy; 3. medicine; 4. blood",
    ],
  },
  {
    title: "d10 Vessel - not a bottle at all",
    id: "d10vesselnotbottle_potions",
    roll: [
      "A wax lozenge to be held under the tongue until it goes.",
      "A cloth soaked and dried, brewed back to life in hot water.",
      "A jellied cube in oiled paper, sweet and unpleasantly warm.",
      "A paste in a screw of parchment, meant to be rubbed into the gums.",
      "A candle whose smoke is the dose, and the whole thing must burn.",
      "A dried root to be chewed for exactly as long as it takes to count to fifty.",
      "A sealed jar of vapour, no liquid at all, and it must be breathed in.",
      "A comb of honey, one cell of which is not honey.",
      "A pill of pressed powder, stamped with a maker's mark like a coin.",
      "A dose delivered by (d4): 1. a needle; 2. a lozenge; 3. an inhaled powder; 4. touch alone",
    ],
  },

  /* ------------------------------------------------------------------
   * The spine: these always roll
   * ---------------------------------------------------------------- */
  {
    title: "d20 The liquid",
    id: "d20liquid_potions",
    roll: [
      "A clear liquid, thinner than water, that beads on the glass.",
      "Deep red, and it clings to the sides the way good wine does.",
      "A milky white that separates into two layers if left standing.",
      "Black, entirely light-swallowing, and no reflection on the surface.",
      "Bright yellow, cheerful, and quite at odds with what it does.",
      "A green that shifts toward blue as the bottle is turned.",
      "Silver, mirror-bright, showing the room upside down.",
      "Pale gold with a sediment of fine bright grains at the bottom.",
      "A pink so pale it is almost the colour of a healing scar.",
      "Two liquids that will not mix, one blue, one amber, in equal parts.",
      "A slurry of grey with something fibrous suspended in it.",
      "Colourless, and the bottle looks empty until it is tipped.",
      "Violet, with a slow spiral in it that never quite stops.",
      "The precise colour of the drinker's own eyes, whoever holds it.",
      "Rust-brown, and it stains everything it touches permanently.",
      "A blue so dark it reads as black until it is held to a flame.",
      "Iridescent, like oil on a puddle, and it will not settle.",
      "Almost solid: it pours in one slow lump.",
      "Bright white, glowing enough to read a page by.",
      "A colour the drinker cannot afterwards name, somewhere between (d4): 1. green and gold; 2. red and grey; 3. blue and nothing; 4. two colours that do not sit together",
    ],
  },
  {
    title: "d16 How it behaves in the vessel",
    id: "d16behaviour_potions",
    roll: [
      "Perfectly still, even when the bottle is shaken.",
      "It sloshes a moment after the bottle moves, always late.",
      "A slow rolling boil that produces no heat at all.",
      "It creeps up the inside of the glass and settles back down.",
      "A single bubble crosses the surface once a minute, regular as a clock.",
      "It leans toward whoever is nearest.",
      "It swirls anticlockwise, always, whichever way it is stirred.",
      "It goes perfectly clear when watched, and cloudy the moment it is not.",
      "It fogs the inside of the vessel, and the fog forms shapes if you let it.",
      "It is warm on one side of the bottle and cold on the other.",
      "It shrinks a little every day, though the seal has never been broken.",
      "It gets one shade darker every time it changes hands.",
      "It ripples when a lie is told nearby.",
      "It settles into layers overnight and mixes itself by morning.",
      "It clings in a film that spells nothing legible, but nearly.",
      "It reacts to (d4): 1. sunlight; 2. song; 3. the drinker's name; 4. iron",
    ],
  },
  {
    title: "d16 The smell",
    id: "d16smell_potions",
    roll: [
      "Aniseed and something underneath it that is not aniseed.",
      "Nothing at all, aggressively: it seems to take the smell out of the room.",
      "Wet stone after rain.",
      "A sickroom: vinegar, tallow and old linen.",
      "Cut grass, so strongly it makes the eyes water.",
      "Cold iron and pepper.",
      "Honeysuckle, faint, and it gets stronger for the person about to drink it.",
      "Burnt hair, and no amount of airing improves it.",
      "The sea, specifically the low tide part.",
      "Something the drinker last smelled at a funeral.",
      "New bread, which is deeply out of place.",
      "Sharp alcohol over something rotten, poorly disguised.",
      "Church incense, three days stale.",
      "A stable in winter: straw, horse and cold.",
      "Nothing until the stopper is out for a count of ten, then everything at once.",
      "Whatever the person holding it (d4): 1. most misses; 2. most fears; 3. smelled as a child; 4. cannot place at all",
    ],
  },
  {
    title: "d16 The taste",
    id: "d16taste_potions",
    roll: [
      "Bitter enough to make the jaw ache, and it lingers for an hour.",
      "Sickly sweet, like syrup left in a hot room.",
      "Salt, plain salt, and far too much of it.",
      "Clean and cold, like meltwater, and startlingly pleasant.",
      "Metallic, and the mouth tastes of coins until the next meal.",
      "Sour first, then sweet, then sour again as an afterthought.",
      "Fatty, like broth gone cold, and it coats the throat.",
      "Peppery enough to cause a coughing fit at the wrong moment.",
      "Faintly of blood, whether or not there is any in it.",
      "Of nothing whatsoever, which is somehow worse.",
      "Of a meal the drinker ate once and has never found again.",
      "Chalk and old wine.",
      "Smoke, as though the liquid itself had been burned.",
      "Green and vegetal, like chewing a stem.",
      "It changes halfway down the swallow and the second half is not the same drink.",
      "It tastes strongly of (d4): 1. liquorice; 2. rust; 3. rain; 4. an apology",
    ],
  },
  {
    title: "d12 The stopper",
    id: "d12stopper_potions",
    roll: [
      "Cork, dried out, and it will crumble the first time it is pulled.",
      "Cork sealed over with red wax and a thumbprint.",
      "A glass stopper ground to fit, which whistles as it comes free.",
      "Wax alone, poured deep, so opening it means digging.",
      "A wooden plug wrapped in oiled rag.",
      "A screw cap of tin, cross-threaded by somebody in a hurry.",
      "Wax over cork, over cloth, over more wax: somebody was very serious.",
      "A stopper carved as a small face, worn smooth about the mouth.",
      "Lead, crimped, and it must be cut off rather than pulled.",
      "Nothing: the neck is sealed shut by whatever is inside.",
      "A stopper that is not original, and does not quite fit.",
      "Sealed with (d4): 1. a hair tied round the neck; 2. a wire and a lead tag; 3. a ribbon of a guild colour; 4. someone's ring",
    ],
  },
  {
    title: "d16 The label",
    id: "d16label_potions",
    roll: [
      "No label at all. Never was one.",
      "A label torn off, leaving the corner and half a word.",
      "A neat apothecary's label with a name, a date and a dose.",
      "One word, in charcoal: DRINK.",
      "One word, in charcoal: DO NOT.",
      "A patient's name and a physician's initials, which can be traced.",
      "A price in chalk, rubbed and rewritten twice, going up each time.",
      "A guild seal, and the guild takes counterfeits personally.",
      "Instructions in a language nobody at the table reads, in an alphabet they do.",
      "A label from an entirely different product, deliberately.",
      "A tally of doses with three of five struck through.",
      "A skull drawn badly, possibly as a joke.",
      "A dose written in a unit that has not been used for a century.",
      "A love note, and no information about the contents whatsoever.",
      "The name of a person, not a preparation, and nothing else.",
      "A label that says (d4): 1. FOR THE DOG; 2. SECOND ATTEMPT; 3. NOT FOR SALE; 4. SORRY",
    ],
  },
  {
    title: "d30 What it does",
    id: "d30effect_potions",
    roll: [
      "Closes wounds cleanly, and the drinker keeps every scar it saves them from earning.",
      "Cures one disease entirely, chosen by the potion, not the drinker.",
      "Purges any poison, violently, and the next hour is not dignified.",
      "Grants the strength to lift a horse, for about as long as it takes to lift one.",
      "Steadies the hands absolutely: no shake, no flinch, no fear either.",
      "Grants sight in total darkness, and makes ordinary daylight painful for a day.",
      "Makes the drinker weightless enough to be carried by a stiff wind.",
      "Lets them breathe water, and afterwards air tastes stale for a week.",
      "Wakes them fully, as though they had slept a full night, at the cost of one later.",
      "Removes the need to eat or drink for three days, and the pleasure of it for a month.",
      "Silences every sound the drinker makes, including their voice.",
      "Turns the skin to something like bark, stiff and slow and hard to cut.",
      "Lets the drinker understand every spoken language for an hour, but not read a word.",
      "Shows them the nearest living thing that wishes them harm, as a pull, not a picture.",
      "Makes them entirely unmemorable for a day.",
      "Puts them into a sleep indistinguishable from death for as long as they wish.",
      "Restores a memory that was taken, or lost, or buried on purpose.",
      "Takes a memory away, and the drinker chooses which only if they are quick.",
      "Makes the drinker beautiful, briefly and unmistakably, in a way that is remembered.",
      "Ages the drinker a year, and heals absolutely everything wrong with them.",
      "Un-ages the drinker a year, and takes a year of their memories with it.",
      "Lets them speak once with someone who died within the past day.",
      "Makes them immune to fire, and permanently unafraid of it, which is worse.",
      "Doubles their speed, and their heart pays for every second of it.",
      "Makes them tell the truth for an hour, whether or not anyone is asking.",
      "Makes anyone who hears them believe the next thing they say.",
      "Numbs all pain completely, including the pain that was warning them.",
      "Lets them see the last hour that happened in the room they are standing in.",
      "Does nothing whatsoever, and is not a fake: it simply has no effect on this drinker.",
      "Does what the label claims, except (d4): 1. twice as strongly; 2. an hour late; 3. to the nearest other person; 4. only the first time",
    ],
  },
  {
    title: "d12 Onset",
    id: "d12onset_potions",
    roll: [
      "Immediately, before the bottle is back on the table.",
      "Three breaths, and a very long three breaths they are.",
      "A slow warmth spreading from the stomach over a minute.",
      "As soon as the drinker next stands up.",
      "Only after they have swallowed the whole dose, not before.",
      "Ten minutes, exactly, every time, reliably enough to plan around.",
      "The moment the drinker stops thinking about it.",
      "At the next sunset or sunrise, whichever comes first.",
      "As soon as their heart rate rises.",
      "When they next fall asleep, which is a poor time to find out.",
      "In stages, over an hour, each stage stronger than the last.",
      "Whenever it wants, within (d4): 1. a minute; 2. an hour; 3. a day; 4. this scene",
    ],
  },
  {
    title: "d12 How long it lasts",
    id: "d12duration_potions",
    roll: [
      "A handful of heartbeats. Use it now or lose it.",
      "About a minute: long enough for one decision.",
      "Ten minutes, and it fades gently rather than stopping.",
      "An hour, then a hard, sudden crash.",
      "Until sunrise, and no bargaining.",
      "Until the drinker next sleeps, however long they stay awake.",
      "A day and a night, wearing off unevenly in between.",
      "A month, and it cannot be ended early by any means known locally.",
      "Permanently, which is far rarer than the seller claims.",
      "As long as the drinker keeps talking.",
      "As long as the empty bottle stays unbroken.",
      "It lasts (d4): 1. exactly as long as it is needed; 2. one minute too short; 3. one hour too long; 4. nobody agrees",
    ],
  },
  {
    title: "d10 Doses",
    id: "d10doses_potions",
    roll: [
      "One mouthful, and the bottle is done.",
      "Two doses, and the second is weaker than the first.",
      "Three careful doses, or one reckless one.",
      "Half a dose left. Somebody already used this.",
      "A full bottle of five, from a batch of a hundred.",
      "One dose, and it is plainly not the dose the vessel was made for.",
      "Enough for the whole party, thinly, and nobody will get the full effect.",
      "One dose, and a residue that is worth analysing.",
      "It refills, slowly, at a rate of about a dose a season.",
      "Doses remaining: (d4): 1. one; 2. two; 3. three; 4. more than there should be",
    ],
  },
  {
    title: "d12 What it is worth",
    id: "d12worth_potions",
    roll: [
      "A few coppers. Any village herbalist makes something similar.",
      "A day's wages, and worth every penny.",
      "Fifty gold, and the buyer will haggle on principle.",
      "More than a warhorse, and the seller knows exactly what they have.",
      "Nothing on the open market and everything to one particular buyer.",
      "The going rate is unclear because the last three sales all ended badly.",
      "Whatever a dying person's family can raise by morning.",
      "Cheap, suspiciously so, and the seller wants it gone today.",
      "Priced by the dose, and the price rises with each one poured.",
      "It is illegal to sell here, which has doubled the price.",
      "Worth more as evidence than as medicine.",
      "It is worth (d4): 1. a favour; 2. a debt forgiven; 3. a name; 4. more than the party will be offered for it",
    ],
  },
  {
    title: "d16 Who brewed it",
    id: "d16brewer_potions",
    roll: [
      "A licensed apothecary, properly, with the paperwork to prove it.",
      "A hedge witch working from a recipe four generations old.",
      "A field surgeon, in bulk, badly, and it saved lives anyway.",
      "A temple infirmary, where they pray over the batch as it cools.",
      "A student, in a rented room, from a book they should not have.",
      "A guild laboratory, one of a numbered batch, with a serial on the base.",
      "An alchemist who has not been seen in three years.",
      "Someone who was clearly guessing, and got lucky.",
      "A prisoner, with materials smuggled in a piece at a time.",
      "A brewer of ale who branched out and has an alarming success rate.",
      "A creature, not a person, and the difference shows in the method.",
      "The drinker's own family, generations back, from a still in the cellar.",
      "A poisoner, moonlighting honestly, and very good at both trades.",
      "Nobody: it was found already made, in a place with no brewer.",
      "A rival of somebody the party knows, which will come up later.",
      "Made by (d4): 1. a rival guild; 2. a dead master; 3. a machine; 4. the person selling it, five minutes ago",
    ],
  },

  /* ------------------------------------------------------------------
   * Leaf tables: consulted by the gated tangents below
   * ---------------------------------------------------------------- */
  {
    title: "d16 The side effect",
    id: "d16sideeffect_potions",
    roll: [
      "The drinker's eyes stay the potion's colour for a day.",
      "A nosebleed at the worst possible time, and it will not stop quickly.",
      "Their voice drops or rises a full tone, permanently.",
      "They sweat something faintly luminous for an hour.",
      "Everything tastes of the potion for three days, water included.",
      "They cannot bear to be touched until it wears off.",
      "Their reflection lags a beat behind them.",
      "They cannot sleep tonight, at all, no matter how tired.",
      "Their hands shake for an hour afterwards, badly enough to matter.",
      "Animals will not come near them until they wash.",
      "They can smell magic for a day, and it smells appalling.",
      "A rash in the shape of the maker's mark on the bottle.",
      "They hiccup, and each hiccup is briefly audible from a very long way off.",
      "They are ravenously hungry, and only for one specific food.",
      "A stripe of their hair turns white and never turns back.",
      "They talk in their sleep, in (d4): 1. the brewer's voice; 2. a dead language; 3. answers to questions nobody asked; 4. the recipe",
    ],
  },
  {
    title: "d12 The sediment",
    id: "d12sediment_potions",
    roll: [
      "A fine grit that gets between the teeth.",
      "Something fibrous, like a root, that never quite dissolves.",
      "A single seed, and it will sprout if planted.",
      "Flakes of gold leaf, which is either the active ingredient or pure showmanship.",
      "Sand, and it is not from anywhere within a hundred miles.",
      "A tooth. Small. Not human.",
      "Ash, and it swirls up whenever the bottle is disturbed.",
      "A curl of hair, tied with thread.",
      "A dead insect that the brewer clearly intended to be there.",
      "A splinter of bone, polished by long immersion.",
      "Something that moves against the current when the bottle is tilted.",
      "A residue that (d4): 1. is still growing; 2. is the real dose; 3. spells a letter; 4. dissolves when watched",
    ],
  },
  {
    title: "d12 What the label got wrong",
    id: "d12mislabelled_potions",
    roll: [
      "It is a different preparation entirely, and a more valuable one.",
      "It is a different preparation entirely, and a much cheaper one.",
      "The dose is out by a factor of ten, in the dangerous direction.",
      "The label is right and the contents were swapped by a previous owner.",
      "Two bottles in the batch got each other's labels, and the other is out there.",
      "The name is a code, and it means something quite different to the trade.",
      "It is the same preparation, but old enough that it now does something else.",
      "The label names a maker who did not make it.",
      "It is a diluted version, at full price, and the dilution is water.",
      "It is stronger than labelled, because the labeller was being cautious.",
      "The warning on it belongs to a different bottle and this one has none.",
      "It was mislabelled (d4): 1. by accident; 2. to smuggle it; 3. to sell it; 4. to protect whoever finds it",
    ],
  },
  {
    title: "d12 The delayed second effect",
    id: "d12delayed_potions",
    roll: [
      "At the next sunrise, the first effect happens again, weaker and uninvited.",
      "A day later, the drinker sleeps for twelve hours and cannot be woken.",
      "A week later, they dream the brewer's last night, in detail.",
      "The next time they are badly hurt, the potion fires again and saves them once.",
      "A month later, they become briefly, violently immune to all magic.",
      "The effect returns whenever they are frightened, until it is used up.",
      "At the next full moon, someone else gets the effect instead.",
      "The following day, everything they say is true, briefly, again.",
      "It returns once, at the worst moment, and never again.",
      "A year later, exactly, and by then nobody connects the two.",
      "The next potion they drink is doubled, whatever it is.",
      "It comes back (d4): 1. tonight; 2. when they next lie; 3. when the bottle breaks; 4. when they say the brewer's name",
    ],
  },
  {
    title: "d12 What it reacts with",
    id: "d12interaction_potions",
    roll: [
      "Alcohol, catastrophically, and taverns are where potions get drunk.",
      "Any healing draught: the two cancel and both are wasted.",
      "Holy water, which sets it foaming and ruins both.",
      "Iron, so the flask it is carried in matters.",
      "Sunlight, which spoils it in an afternoon.",
      "Another dose of itself: the second dose is dangerous, not stronger.",
      "Anything the drinker is already carrying that is magical.",
      "Salt, which renders it inert but stable, and stable is worth something.",
      "Fear: it does far less for a calm drinker than a terrified one.",
      "Blood, and the effect takes on the character of whoever it came from.",
      "Cold, which thickens it past the point of pouring.",
      "It reacts badly to (d4): 1. being shaken; 2. being sold; 3. being shared; 4. being refused",
    ],
  },
  {
    title: "d10 The craving it leaves",
    id: "d10craving_potions",
    roll: [
      "Only for more of the same, and only for a day.",
      "A dull want that never quite leaves, and never gets worse.",
      "A need for it that arrives at the same hour every night.",
      "A craving not for the potion but for the taste of the vessel it came in.",
      "The drinker begins collecting the bottles, without deciding to.",
      "A hunger for whatever the potion was brewed from, in any form.",
      "They will pay more for the next one, every time, without noticing.",
      "They defend the brewer's reputation, warmly, having never met them.",
      "They dream about it, and the dreams are better than the potion.",
      "It takes hold after (d4): 1. one dose; 2. three; 3. the first refusal; 4. it has already taken hold",
    ],
  },
  {
    title: "d12 Who wants it",
    id: "d12seeker_potions",
    roll: [
      "The apothecary who brewed it, who did not consent to the sale.",
      "The patient it was made for, who is running out of time.",
      "That patient's family, who are not out of money.",
      "A guild inspector following a batch number.",
      "A rival brewer who wants the recipe, not the bottle.",
      "The person who poisoned someone and needs the antidote back.",
      "A collector of vessels who does not care what is in it.",
      "A temple that considers the whole preparation blasphemous.",
      "The thief it was taken from, who has friends.",
      "Somebody's heir, who would rather the cure did not arrive.",
      "A creature that was distilled into it, or part of it, wanting itself back.",
      "Someone who is (d4): 1. offering to buy; 2. offering not to hurt anyone; 3. already following; 4. in the room",
    ],
  },
  {
    title: "d10 How close they are",
    id: "d10howclose_potions",
    roll: [
      "They do not know it exists yet.",
      "They know the batch is loose, not who has it.",
      "They are asking questions in town, quietly.",
      "They have offered a reward, and the reward is generous.",
      "They are watching the party's inn from across the street.",
      "They have already met the party, and said nothing about it.",
      "They will be here by nightfall.",
      "They are dead, and their debts are being collected by someone else.",
      "They sent a letter, and it is unpleasantly well informed.",
      "They arrive (d4): 1. tonight; 2. as it is drunk; 3. after it is drunk; 4. with witnesses",
    ],
  },
  {
    title: "d12 The brewer's story",
    id: "d12brewerstory_potions",
    roll: [
      "It was the last batch before the still was seized.",
      "It was brewed for a wedding, and the wedding did not happen.",
      "It was a test batch, and the brewer is waiting to hear how it went.",
      "The brewer died of something this potion would have cured.",
      "It was made under duress, and the brewer left a flaw in it deliberately.",
      "The recipe was stolen, and this is the first proof of that.",
      "The brewer made it for themselves and never had the nerve to drink it.",
      "It took nine months and everything they owned.",
      "It was made in a plague year, in quantity, and most of it was used.",
      "The brewer has since given up the trade entirely and will not say why.",
      "It is the only surviving example of a method that is now illegal.",
      "The brewer is (d4): 1. famous; 2. wanted; 3. dead a century; 4. eleven years old",
    ],
  },
  {
    title: "d12 What it actually is",
    id: "d12actuallyis_potions",
    roll: [
      "Coloured water, expertly presented, and utterly inert.",
      "A poison, and the label is not lying, exactly: it does what it says first.",
      "A dye, industrial, and drinking it is a bad idea rather than a magical one.",
      "Something's blood, thinned, and it still counts as being something's blood.",
      "A preserving fluid, and whatever it was preserving is nearby.",
      "An ordinary medicine, extremely effective, with no magic in it whatsoever.",
      "A component, not a potion: it is meant to be added to something else.",
      "A message: the sediment settles into a readable shape if left still for a day.",
      "A living thing, dormant, and drinking it is not what it is for.",
      "A test dose from a batch that killed everyone else who tried it.",
      "The genuine article, and it is the seller who is fake.",
      "Not a potion but (d4): 1. an offering; 2. an ink; 3. a lure; 4. a very old joke",
    ],
  },
  {
    title: "d12 How it acts alive",
    id: "d12alive_potions",
    roll: [
      "It goes still and clear when its owner speaks to it.",
      "It presses against the glass on the side nearest a wounded person.",
      "It will not be poured for someone it dislikes: the neck simply blocks.",
      "It taps the inside of the vessel at night, three at a time.",
      "It changes colour toward the mood of whoever is holding it.",
      "It leaves the bottle when nobody is looking and is back before morning.",
      "It shrinks away from fire and crowds toward cold.",
      "It has learned the shape of the party's camp and settles when it hears it.",
      "It pours itself out entirely if left uncorked, and finds its way to a drain.",
      "It answers yes and no by clouding and clearing.",
      "It grieves, visibly, when another bottle in the batch is emptied.",
      "It wants (d4): 1. to be drunk; 2. to be kept; 3. to be poured out; 4. to be taken home",
    ],
  },

  /* ------------------------------------------------------------------
   * The gated tangents (sub_rolls entries). percent_to is the chance the
   * whole block appears at all; the "type" gates then pick a variant whose
   * own main_rolls decide which leaf tables get consulted.
   * ---------------------------------------------------------------- */
  {
    title: "It does something else as well",
    singular: "Effect",
    id: "gateside_potions",
    roll_type: "type",
    number: "1d2",
    percent_to: "65",
    percent_of: "100",
    roll: [
      {
        title: "A cost the brewer knew about and priced in",
        main_rolls: ["potions/d16sideeffect_potions"],
        sub_rolls: [],
      },
      {
        title: "A cost the brewer did not know about",
        main_rolls: [
          "potions/d16sideeffect_potions",
          "potions/d12brewerstory_potions",
        ],
        sub_rolls: [],
      },
      {
        title: "Something the drinker will not notice for a while",
        main_rolls: [
          "potions/d16sideeffect_potions",
          "potions/d12delayed_potions",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "There is something in the bottom",
    singular: "Sediment",
    id: "gatesediment_potions",
    roll_type: "type",
    number: "1d1",
    percent_to: "40",
    percent_of: "100",
    roll: [
      {
        title: "An ingredient that never dissolved",
        main_rolls: ["potions/d12sediment_potions"],
        sub_rolls: [],
      },
      {
        title: "Evidence of how it was made",
        main_rolls: [
          "potions/d12sediment_potions",
          "potions/d12brewerstory_potions",
        ],
        sub_rolls: [],
      },
      {
        title: "The part that actually works",
        main_rolls: [
          "potions/d12sediment_potions",
          "potions/d12actuallyis_potions",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "Where it came from",
    singular: "Chapter",
    id: "gatebrewer_potions",
    roll_type: "type",
    number: "1d1",
    percent_to: "55",
    percent_of: "100",
    roll: [
      {
        title: "The batch it belonged to",
        main_rolls: [
          "potions/d12brewerstory_potions",
          "potions/d16brewer_potions",
        ],
        sub_rolls: [],
      },
      {
        title: "Who it was made for, and whether they got it",
        main_rolls: [
          "potions/d12brewerstory_potions",
          "potions/d12seeker_potions",
        ],
        sub_rolls: [],
      },
      {
        title: "How it left the brewer's hands",
        main_rolls: [
          "potions/d12brewerstory_potions",
          "potions/d16label_potions",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "The label is wrong",
    singular: "Error",
    id: "gatemislabelled_potions",
    roll_type: "type",
    number: "1d1",
    percent_to: "30",
    percent_of: "100",
    roll: [
      {
        title: "An honest mistake, somewhere down the line",
        main_rolls: ["potions/d12mislabelled_potions"],
        sub_rolls: [],
      },
      {
        title: "A deliberate swap",
        main_rolls: [
          "potions/d12mislabelled_potions",
          "potions/d12seeker_potions",
        ],
        sub_rolls: [],
      },
      {
        title: "It is not the preparation named at all",
        main_rolls: [
          "potions/d12mislabelled_potions",
          "potions/d12actuallyis_potions",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "It does not mix",
    singular: "Reaction",
    id: "gateinteraction_potions",
    roll_type: "type",
    number: "1d1",
    percent_to: "22",
    percent_of: "100",
    roll: [
      {
        title: "Known to the trade, and usually written on the label",
        main_rolls: [
          "potions/d12interaction_potions",
          "potions/d16label_potions",
        ],
        sub_rolls: [],
      },
      {
        title: "Not known to the trade, and about to be",
        main_rolls: [
          "potions/d12interaction_potions",
          "potions/d16sideeffect_potions",
        ],
        sub_rolls: [],
      },
      {
        title: "It is why this bottle was set aside in the first place",
        main_rolls: [
          "potions/d12interaction_potions",
          "potions/d12brewerstory_potions",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "It comes back later",
    singular: "Return",
    id: "gatedelayed_potions",
    roll_type: "type",
    number: "1d1",
    percent_to: "20",
    percent_of: "100",
    roll: [
      {
        title: "A second dose the drinker never took",
        main_rolls: ["potions/d12delayed_potions"],
        sub_rolls: [],
      },
      {
        title: "The effect was never finished the first time",
        main_rolls: [
          "potions/d12delayed_potions",
          "potions/d16sideeffect_potions",
        ],
        sub_rolls: [],
      },
      {
        title: "It waits for a condition, and the condition will happen",
        main_rolls: [
          "potions/d12delayed_potions",
          "potions/d12interaction_potions",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "It leaves a want behind",
    singular: "Craving",
    id: "gatecraving_potions",
    roll_type: "type",
    number: "1d1",
    percent_to: "15",
    percent_of: "100",
    roll: [
      {
        title: "Mild, and easy to mistake for a preference",
        main_rolls: ["potions/d10craving_potions"],
        sub_rolls: [],
      },
      {
        title: "A real dependency, and the supply is limited",
        main_rolls: ["potions/d10craving_potions", "potions/d12seeker_potions"],
        sub_rolls: [],
      },
      {
        title: "Designed in, to keep customers coming back",
        main_rolls: [
          "potions/d10craving_potions",
          "potions/d12brewerstory_potions",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "Somebody wants it",
    singular: "Interest",
    id: "gatewanted_potions",
    roll_type: "type",
    number: "1d1",
    percent_to: "12",
    percent_of: "100",
    roll: [
      {
        title: "They want the bottle back",
        main_rolls: ["potions/d12seeker_potions", "potions/d10howclose_potions"],
        sub_rolls: [],
      },
      {
        title: "They need what is in it, urgently",
        main_rolls: [
          "potions/d12seeker_potions",
          "potions/d10howclose_potions",
          "potions/d12brewerstory_potions",
        ],
        sub_rolls: [],
      },
      {
        title: "They want it never to be drunk",
        main_rolls: [
          "potions/d12seeker_potions",
          "potions/d10howclose_potions",
          "potions/d12actuallyis_potions",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "There is something living in it",
    singular: "Sign",
    id: "gatealive_potions",
    roll_type: "type",
    number: "1d1",
    percent_to: "8",
    percent_of: "100",
    roll: [
      {
        title: "Attentive: it notices who is holding it",
        main_rolls: ["potions/d12alive_potions"],
        sub_rolls: [],
      },
      {
        title: "Unwilling: it does not want to be drunk",
        main_rolls: ["potions/d12alive_potions", "potions/d12seeker_potions"],
        sub_rolls: [],
      },
      {
        title: "Something was distilled in there, and is still in there",
        main_rolls: [
          "potions/d12alive_potions",
          "potions/d12actuallyis_potions",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "It is not a potion",
    singular: "Truth",
    id: "gatetruth_potions",
    roll_type: "type",
    number: "1d1",
    percent_to: "6",
    percent_of: "100",
    roll: [
      {
        title: "It never was, and the presentation is the deception",
        main_rolls: [
          "potions/d12actuallyis_potions",
          "potions/d12mislabelled_potions",
        ],
        sub_rolls: [],
      },
      {
        title: "It stopped being one, with age or with handling",
        main_rolls: [
          "potions/d12actuallyis_potions",
          "potions/d12sediment_potions",
        ],
        sub_rolls: [],
      },
      {
        title: "It is part of something larger and was never meant to be drunk",
        main_rolls: [
          "potions/d12actuallyis_potions",
          "potions/d12brewerstory_potions",
        ],
        sub_rolls: [],
      },
    ],
  },
];
