// magic.js
//

top.magic = [



   {"title": "d4 Each side pouch can hold ___ pounds of material...", "id":"d4eachsidepouchcanhold___poundsofmaterial_dimensonshaversack", "roll":[
  "10",
  "15",
  "20",
  "25",   ]},
   {"title": "d4 not exceeding a volume of ___ cubic feet...", "id":"d4notexceedingavolumeof___cubicfeet_dimensonshaversack", "roll":[
  "1",
  "1/2",
  "2",
  "2 1/2",   ]},
   {"title": "d6 The large central pouch can hold up to ___ pounds of material...", "id":"d6thelargecentralpouchcanholdupto___poundsofmaterial_dimensonshaversack", "roll":[
  "50",
  "60",
  "70",
  "80",
  "90",
  "100",   ]},
   {"title": "d6 or ___ cubic feet...", "id":"d6or___cubicfeet_dimensonshaversack", "roll":[
  "6 1/2",
  "7",
  "7 1/2",
  "8",
  "8 1/2",
  "9",   ]},
   {"title": "d4 The haversack always weighs ___ pound regardless of its contents...", "id":"d4thehaversackalwaysweighs___poundregardlessofitscontents_dimensonshaversack", "roll":[
  "2 1/2",
  "5",
  "7 1/2",
  "10",   ]},

   {"title": "d6 On the outside, the bag is roughly ___ feet in diameter at the mouth...", "id":"d6ontheoutsidethebagisroughly___feetindiameteratthemouth_dimensions", "roll":[
  "1",
  "1 1/2",
  "2",
  "2 1/2",
  "3",
  "3/12",   ]},
   {"title": "d6 and ___ feet deep...", "id":"d6and___feetdeep_dimensions", "roll":[
  "2 1/2",
  "3",
  "3 1/2",
  "4",
  "4 1/2",
  "5",   ]},
   {"title": "d6 It can hold up to ___ pounds...", "id":"d6itcanholdupto___pounds_dimensions", "roll":[
  "200",
  "350",
  "500",
  "650",
  "800",
  "1000",   ]},
   {"title": "d4 Not exceeding a volume of ___ cubic feet...", "id":"d4notexceedingavolumeof___cubicfeet_dimensions", "roll":[
  "32",
  "48",
  "64",
  "80",   ]},
   {"title": "d4 The bag always weighs ___ pounds regardless of its contents", "id":"d4thebagalwaysweighs___poundsregardlessofitscontents_dimensions", "roll":[
  "10",
  "15",
  "20",
  "25",   ]},

 {"title": "d20 The item appears to be made of...", "id":"d20theitemappearstobemadeof_bagofholding", "roll":[
"rough leather",
"fine leather",
"hemp or linen",
"heavy paper",
"silk",
"burlap",
"a preserved organ",
"spider silk",
"mithril chain",
"human hair",
"canvas",
"dragon scales",
"woven vines",
"pressed leaves",
"an old set of bagpipes",
"a human (or other pc race) skull and/or rib cage",
"living flesh",
"cloth of gold",
"cloth of silver",
"velvet",   ]},
 {"title": "d10 The item is of ___ origin...", "id":"d10theitemisof___origin_bagofholding", "roll":[
"infernal",
"celestial",
"arcane",
"divine",
"planar",
"interdimensional",
"natural",
"mundane",
"miraculous",
"unknown",   ]},
 {"title": "d10 The item...", "id":"d10theitem_bagofholding", "roll":[
"smells strange",
"is covered in postage stamps/seals",
"is embossed or embroidered with an ornate design",
"glows in the dark",
"has an obvious repair",
"is made of two different materials (roll twice on the 'appears to be made of...' table)",
"has more than one compartment (roll internal dimensions for the main pouch twice, but otherwise treat as one item)",
"requires attunement to use",
"deals one d-eight bludgeoning damage",
"is always open",   ]},
 {"title": "d20 Things that are placed into the item...", "id":"d20thingsthatareplacedintotheitem_bagofholding", "roll":[
"grow in size over time",
"shrink in size over time",
"are cleaned over time",
"are dirtied over time",
"rust over time",
"age unnaturally quickly",
"age unnaturally slowly",
"rot",
"are preserved",
"are hot to the touch",
"are cool to the touch",
"slowly gain sentience",
"slowly lose intelligence",
"change color",
"lose color",
"are blessed",
"are cursed",
"shine in darkness",
"absorb light",
"roll Twice",   ]},
 {"title": "d10 The item's previous owner...", "id":"d10theitemspreviousowner_bagofholding", "roll":[
"the bag had no previous owner",
"threw it away",
"sold it",
"lost it gambling",
"had it stolen",
"gave it to a friend",
"died suddenly",
"is looking for it",
"knows where it is",
"is the Big Bad",   ]},
 {"title": "d20 Adventure Seed: Congratulations! You found an [insert extradimensional item here]! It contains...", "id":"d20adventureseedcongratulations!youfoundan[insertextradimensionalitemhere]!itcontains_bagofholding", "roll":[
"nothing",
"60ft of rope",
"a wheel of cheese",
"a bundle of dried leaves",
"a mummified bird",
"a signet ring",
"thirteen random playing cards",
"a broken tin whistle",
"a pair of false teeth",
"an I.O.U.",
"a dried-up self-inking quill",
"a packet of seeds",
"a brochure from a bank",
"a knit hat",
"a handful of diamonds",
"a single children's shoe",
"a set of thieves' tools",
"a half-full thermos of warm tea",
"the remains of the item's previous owner",
"another [insert extradimensional item here]",   ]},
 {"title": "d20 Adventure Seed: You love your [generic extradimensional doodad]! It's great! But suddenly...", "id":"d20adventureseedyouloveyour[genericextradimensionaldoodad]!itsgreat!butsuddenly_bagofholding", "roll":[
"the item begins to emit smoke when open",
"you have a 25% chance to pull a living fish out of the item instead of whatever you were looking for",
"any gold stored in the item instantly becomes lead",
"any gold stored in the item is instantly doubled",
"a contract appears in the item, claiming that your lease is up, and that all contents of the item will be repossessed as soon as you finish reading this sentence",
"rations appear in the item every sunrise, and if unconsumed, disappear every sunset",
"the item begins to emit bright light from the opening when open",
"a black-hilted dagger and a list of names appear in the item",
"a love letter from an NPC you've encountered in the past appears in the item",
"a bejeweled mechanical bird appears in the item. If wound, it casts sleep (as a first level spell) once per day, but affects creatures of the DM's choosing",
"a cool breeze begins to flow through the item, and creatures left in the item do not suffocate",
"if thrown or dropped, the item begins to fall so that it points toward something specific",
"a crystal ball appears in the item, and if touched, is filled with the image of a searching eye",
"a long, thin needle appears in the item that can be used to expand or alter the item's outside dimensions",
"a book appears in the item that contains a first level spell you do not know. This spell can be cast once a day.",
"a set of two six sided dice appear in the item. Once per day, as an action they can be rolled, and if their value equals nine or more, you may immediately take an extra turn",
"the item begins to make an unignorable high-pitched squeal any time it is open",
"the inside dimensions of your item have changed, and you must reroll them",
"the contents of your item have been swapped with those of another pocket dimension",
"you hear voices from inside you item, and you are surprised to find two halflings rummaging through the contents of your item",   ]},
 {"title": "d20 Adventure Seed: You're walking down a forest/desert/city road when out of nowhere!...", "id":"d20yourewalkingdownaforestdesertcityroadwhenoutofnowhere!_bagofholding", "roll":[
"a bag of holding appears in your hand",
"a heward's handy haversack appears on your back",
"a portable hole appears on the ground",
"you come across a bag of holding the size of a horse",
"you come across a bag of holding the size of a horsefly",
"you hear a voice say 'you wanna buy a bag of holding?'",
"you hear a voice say 'if you've got a bag of holding to sell, I'll make it worth your while...'",
"a desperate individual asks you if you've seen their bag of holding",
"a fleeing individual thrusts a bag of holding into your hands",
"a small creature makes eye contact with you, then disappears into a bag of holding",
"a distraught individual threatens to throw (what they say is) a bag of holding into (what they claim is) a portable hole",
"a well meaning individual doesn't understand why they can't put their portable hole into a bag of holding",
"an emaciated individual appears out of nowhere, and claims a member of your party trapped them in a portable hole",
"a member of your party appears out of nowhere, and claims that a doppelganger trapped them in a portable hole",
"a merchant tries to sell you the schematics for an 'arrowhead of total destruction'",
"you come across a plaque commemorating the detonation of an 'arrowhead of total destruction'",
"you come across a worn blue-painted wooden cabinet with a portable hole on one of the inside walls",
"an individual who claims to be Heward wants you to fill out a questionnaire about haversacks and their relative handiness",
"an individual who claims to be Heward asks you to test a new invention he calls Heward's Handsome Hat",
"you come across what you believe to be bag of holding, but is actually a mimic. Oh no!",   ]},
 {"title": "d6 Adventure Seed: You come across a bag of holding the size of a house. The opening is...", "id":"d6adventureseedyoucomeacrossabagofholdingthesizeofahousetheopeningis_bagofholding", "roll":[
"open, and you can see inside",
"open, but dark",
"open, but barred by a large gate or door",
"open, but sealed by a wall or rocks",
"closed, but easily opened",
"closed, and not easily opened",   ]},
 {"title": "d20 Adventure Seed: the inside of the bag is...", "id":"d20adventureseedtheinsideofthebagis_bagofholding", "roll":[
"a house, complete with chimney, porch and cellar. It is very slightly larger on the inside than is on the outside",
"full of rations, coins and other mundane items, but much larger than you're used to seeing",
"full of rations, coins and common magical items, but much larger than you're used to seeing",
"the entrance to a series of caves and caverns that would otherwise be impossible in the area you're in",
"a facility for the care and maintenance of pocket dimensions. The interior is seemingly infinite, but the opening is always a few steps away",
"a small kingdom. The entrance is guarded by individuals in heavy armor",
"a large shop",
"seemingly empty",
"seemingly full, but everything is actually an illusion",
"smaller on the inside than it is on the outside",
"another universe, seemingly of equal size and complexity as the one you came from",
"another universe, but everything is slightly smaller than it is in the one you came from",
"another universe, but everything is slightly larger than is is in the one you came from",
"another universe, but everything is wildly disproportionate",
"full of dinosaurs, swamps, and palm trees",
"an arid vacuum. In the distance you can see stars, planets and endless darkness",
"an academy",
"a desert island in a vast sea",
"an ornately decorated bedroom",
"a fully stocked torture chamber",   ]},



   {"title": "d20 The magical disease is associated with...", "id":"d20themagicaldiseaseisassociatedwith_magicalmaladies", "roll":[
  "Belching up vermin.",
  "Demonic or ghostly possession.",
  "The desire to consume humanoid flesh.",
  "The desire to consume rocks or dirt.",
  "The desire to consume pixies and sprites.",
  "The desire to dig a deep hole.",
  "The desire to build an immense wall.",
  "Gaining the personality of a long-dead, well-known magic-user.",
  "Gradually morphing into a wild beast.",
  "Gradually morphing into a puddle of ooze.",
  "Imitating the behavior of a common beast.",
  "Loss of the power of speech.",
  "Periodic spells of befuddlement.",
  "Purple or green splotches on the skin.",
  "Rapid growth of facial hair.",
  "Rapid growth of fingernails or teeth.",
  "Rapid hair growth.",
  "Uncontrollable fits of laughter or tears.",
  "Uncontrollable singing or dancing.",
  "Overactive libido.",   ]},



];
