top.encounters = [
    {
        "id": "combat",
        "title": "Combat",
        "roll": [
            "Gust of Wind {A strong gust of wind suddenly blows across the battlefield. The force of the gust automatically extinguishes candles, torches, and similar unprotected flames. It causes protected flames, such as those of lanterns, to dance wildly and has a 50% chance to extinguish those lights. Ranged attack rolls and non-magical flight are not affected, because the gust is too brief. In addition to the effects noted, a gust of wind can do anything that a sudden blast of wind would be expected to do. It can create a stinging spray of sand or dust, fan a large fire, overturn delicate awnings or hangings, heel over a small boat, and blow gases or vapors to the edge of its range.}",
            "Visibility {An environmental effect limits visibility. The cause of this depends on the location; it may be the closing of a window or door, clouds obscuring moonlight, a sudden heavy fog or sandstorm, or the failure of magical lighting. Depending on the reason chosen, creatures with darkvision may still be able to see. Those who cannot see are considered blinded. The effect persists for one round.}",
            "Innocent {An innocent party unwittingly enters the battlefield. This could cause a hostage situation, or prompt good characters to protect the new arrival. The innocent will be vulnerable (low level, young, etc.)}",
            "Tremor {A minor earth tremor forces all combatants on the ground to make a DC 15 Dexterity save or fall prone.}",
            "Weather {It begins to rain or sleet heavily (depending on the environment). The weather lightly obscures vision, and all creatures on the battlefield suffer disadvantage on sight-based Wisdom (Perception) checks; if the weather is rain, this also applies to hearing-based checks. The weather extinguishes open flames. In the case of sleet, the ground becomes slippery for the rest of the encounter, requiring all creatures to succeed on a DC 10 Dexterity (Acrobatics) check to avoid falling prone the first time they attempt to move on it.}",
            "Monster {A random monster, attracted by the sounds of battle, enters the battlefield, attacking combatants at random. The monster(s) are selected by the GM and should be of a challenge rating equal to half the party's level.}",
            "Touch of Favor {Whether due to luck or to divine favor, one random combatant gains advantage on his next attack roll and automatically scores a critical hit if the attack roll is successful. Every combatant must roll 1d20, with the highest rolling combatant gaining this benefit. If there is a tie, all combatants in the tie gain the benefit.}",
            "Collapse {There is a major structural failure nearby. If outside, a 30-foot-tall tree falls in a random direction, affecting a 5-foot-wide, 30-foot-long area. If inside, the ceiling collapses at a random location in a 15-foot-wide radius bury zone. Those under the falling items take 22 (4d10) bludgeoning damage (or half that with a DC 15 Dexterity save). The area underneath the collapsed section then becomes filled with rubble, and is treated as difficult terrain.}",
            "Pit {A 10-foot radius section of flooring or ground gives way. Those on the area may make a DC 15 Dexterity save to avoid falling in. Those who fall in take 4d6 bludgeoning damage (2d6 falling damage and 2d6 from debris), and are now prone in a 30-foot hole.}",
            "Press {The flow of combat shifts the entire battle in a random direction. Move all combatants 1d6x5 feet in a random direction. Nobody gains an opportunity attack. If a character’s destination square, or one en-route, is blocked, he must make a DC 15 Dexterity save or fall prone.}",
            "Extreme Favor {For this round only, critical hits are scored on a natural die roll of 19 or 20, and rolls of 1 do not mean an automatic miss.}",
            "Vermin {The battle disturbs some small vermin living in the area. A swarm of insects, rats, or other appropriate vermin appears in a random location and begins to move randomly across the battlefield 1d6×5 feet in a random direction each round. Rats cause difficult terrain in a 10'x10' area; insects or bats cause disadvantage on ranged attacks and Wisdom (Perception) checks in the same area.}",
            "Dust Devil {A small whirlwind of dust moves across the battlefield randomly. A 10-foot × 10-foot area defines the dust cloud, and it moves 1d6×5 feet in a random direction each round. Those caught in the cloud must make a DC 12 C onstitution save or be blinded for 1 round.}",
            "Arcane Flash {A burst of random residual spell energy, perhaps left by a long dead archmage or deity, causes magical powers to fluctuate. The next spell cast by any combatant on the battlefield automatically creates a Wild Magic Surge as per the sorcerous origin.}",
            "Trap {A random combatant sets off a hitherto undiscovered trap. All combatants roll 1d20; the highest rolling combatant sets the trap off. The GM selects a trap of setback severity from the core rulebooks}",
            "Fumble {A random combatant fumbles. All combatants roll 1d20; the highest rolling combatant is the one who fumbles. If there is a tie, both combatants fumble. Roll 1d6 on the fumble table below. See the next page for fumble descriptions.}",
            "Fatigue {This battle is more grueling than most. All combatants must make a DC 15 Constitution save or gain one level of exhaustion until the end of the combat encounter.}",
            "I’m Getting Better! {A combatant who has been downed is not as badly injured as it appeared at first. All downed (dead or dying) combatants roll 1d20. The highest rolling combatant recovers; it was only a flesh wound! He is prone, but actually has 50% of his normal hit point total. If there is a tie, all combatants in the tie recover in this manner.}",
            "Fatal Mistake {A random combatant makes a dangerous mistake and receives a critical hit from the nearest opponent able to do so (either rnaged or melee). All combatants roll 1d20; the highest rolling combatant is the one hit (both in a tie). The hit is automatic. If no combatant is in a position to hit the combatant in question, he fumbles instead (see #16, above).}",
            "The flagstones beneath the combatants’ feet give way in whole or in part,  plunging them into a yet unexplored part of the dungeon or creating a number of \"stepping stones\" that must be navigated during the battle.",
            "An inexplicable migration of dungeon critters spills onto the battlefield.  migrants could be simple dungeon vermin such as giant centipedes and beetles or more fearsome creatures like oozes, monstrous humanoids, or titanic worms.",
            "A mighty blow shatters a crumbling dungeon wall to reveal an unexpected . Hidden in the niche beyond might be a forgotten hoard of treasure, the restless undead forms of entombed prisoners, or a slumbering magical/mechanic construct that stirs to life.",
            "Another running battle fights its way onto the scene. These two new opposing  could be another band of adventurers fighting more of the dungeon’s residents, two rival humanoid tribes engaged in a blood feud, or a subterranean predator pursuing its prey.",
            "Several of the combatants inexplicably disappear into thin air. After several  minutes, they reappear unharmed but bewildered. Once the fight is over, the surviving fighters who vanished tell a strange tale of being spirited away by powerful supernatural entities who forced them to perform bizarre tasks or recount being strapped down while weird, grey-skinned figures enacted uncomfortable scientific tests upon them.",
            "One of the party’s monstrous opponents stares intently at a member and screams out, \"Father?!\"Is this as cunning ploy or the PC’s shameful past coming back to haunt him?",
            "Both sides find themselves abruptly immobilized in mid-conflict. As they  helplessly, a pair of beings walks onto the battlefield, deep in conversation. They pay scant interest to the combatants as they engage in a philosophical debate about the nature of good and evil. The debaters might be a duo of mortal wizards, an angel and a demon, or a pair of godlings wandering the material world. After they walk off the battlefield, the fighters can move once again.",
            "The magical energies wielded by both sides’ spells combine to produce unnatural meteorological effects. A rain of fish pelts the combatants, a windstorm buffets the battlefield, or a severe snowfall covers the warring parties. Further spells cast during the battle intensify the bizarre weather.",
            "A schism erupts within the opponent’s ranks. This mutiny might be caused by rival factions deciding this to be the perfect moment to eliminate their opposite numbers, troops pressed into service rebelling against their masters, or the result of a hidden benefactor’s magical influence to rescue the party from an overwhelming force.",
            "A chance blow releases something best left contained. A club smashes a backpack filled with potions, creating unpredictable results when the volatile substances are mixed; a flask of oil shatters, drenching its owner in combustible liquid; or a lucky blow breaches the ancient brass bottle the party carries, freeing the powerful and angry efreeti trapped within!",
            "A torrent of water rushes into the area, threatening all sides with drowning. The flood might be the result of a ruptured dam somewhere else in the dungeon, a flash flood in the lands above, or a malfunctioning magical item that taps into the Elemental Plane of Water.",
            "The bodies of slain combatants rise as undead creatures and attack both sides. This abrupt animation might be the result of a bored deity or a lurking necromancer, or powered by a mystical artifact carried unwittingly by one of the combatants.",
            "Other intelligent residents of the dungeon turn up to watch the battle. They stand on the sidelines howling encouragement and insults while placing wagers with one another regarding the outcome. If the party is victorious and wins a prestigious spectator large sums of gold, they might gain an unexpected benefactor within the dungeon.",
            "The corpses of dead opponents attract the mindless monsters that serve as the dungeon’s cleaning crew. These beasts pay no notice to the livelier combatants, choosing to concentrate their attentions on the easy pickings that litter the battlefield. The battle becomes increasingly difficult as the fighters must navigate around or over flesh-eating oozes, puddings, or other scavenging monsters.",
            "The opposing side stops fighting and parleys for a cease of hostilities so they might observe their daily religious ceremony. If the PCs rebuff the request and continue to attack, their opponents’ god takes an interest in the battle and divinely assists his/her/its worshipers against their heretical opponents.",
            "A brazier, lamp, or torch is knocked over, setting alight inflammable materials on or next to the battlefield. Depending on the ignited material, the killing field might turn into a raging inferno or merely become occluded by thick smoke. Intelligent opponents might flee the field, but those inspired by zealotry or defending their lairs fight more ferociously to keep the PCs from escaping or to slay their opponents swiftly so they can extinguish the blaze.",
            "The party’s opponents are revealed to be entirely different creatures than the PCs believed them to be. The fearsome orcs are actually bandits wearing costumes as part of their criminal scheming; the skeletons are all living humanoids that drank from a pool which turned their skin and organs invisible; or a giant lizard is truly a dragon that lost its wings to an enchanted blade.",
            "Time slips, throwing chronological order askew. The battle may \"reset\"to the beginning, causing slain creatures to return to life, accelerate or decelerate the actions of one side, or change the order in which the combatants act. This effect might be the result of magical phenomenon or an unexpected glitch in the time-space continuum. All parties are affected by it and no explanation may ever be discovered for the time slip.",
            "The opposing side transforms into different creatures. Perhaps the party was fighting lycanthropes who suddenly change form or the enemy possesses magical items that polymorph them into unexpected creatures. In extreme cases, an unknown participant, perhaps a chaos demon or mischievous godling, shape-changes both sides into one another’s guises.",
            "The battlefield changes dramatically. Walls suddenly appear, the combatants are teleported to a new location, or they are thrown onto a different world or plane. Unbeknownst to either side, their fight activated a slumbering magical item or a contingency spell that chose the particular moment of their battle to take effect."
        ]
    },
    {
        "id": "fumble",
        "title": "Fumble",
        "roll": [
            "1. Prone. The combatant slips or trips and falls prone.",
            "2. Disarmed. The combatant drops her weapon. If she is not holding a weapon, she drops any other item held in her hand(s). If she is not holding any items, she becomes entangled (see below) instead.",
            "3. Entangled. The combatant gets caught up in foliage, furniture, curtains, or even his own backpack. He gains the restrained condition for one round.",
            "4. Vulnerable. The combatant makes a tactical mistake and places herself in a vulnerable position. All attacks against her gain advantage until the beginning of her next round.",
            "5. Disoriented. A random blow, or a moment of confusion, effectively stuns the combatant for one round.",
            "6. Blinded. Whether from blood in his eyes, or a helm falling down over his face - perhaps even a bright light - the combatant is temporarily blinded for one round."
        ]
    }
]