// classes.js
//
// Random Deep Class: a whole character class, blended out of the traditional
// ones the way a compass blends its points.
//
// Two traditions are rolled and then mixed: north and west give northwest, and
// the mix table granulates further, so a class can come out as three parts the
// first and one part the second, or as a core that only shows its second
// bearing under pressure. A third bearing is chance-gated, which is where
// north north west comes from.
//
// Every other property of a class is a table too: hit die, primary abilities,
// saves, armour, weapons, skills, kit, the resource it spends and how that
// resource comes back. Then all twenty levels roll, tier by tier, with the
// branch levels (3, 6, 10, 14) drawing on the subclass tables and the
// improvement levels (4, 8, 12, 16, 19) offering an alternative to taking an
// ability score increase. Eight tangents are chance-gated on top of that.

top.classes = [
  /* ------------------------------------------------------------------
   * The tradition it is taught in: one of these six is picked per class
   * ---------------------------------------------------------------- */
  {
    title: "d10 Tradition - a martial hall",
    id: "d10traditionhall_classes",
    roll: [
      "A drill yard behind a barracks, where the form is taught before the reason.",
      "A duelling school that takes fees from nobles and talent from anywhere.",
      "A mercenary company that trains its own and loses half of them.",
      "A city watch training house, practical, unromantic and extremely effective.",
      "A veterans' hall where the teaching is done over drinks and rarely on purpose.",
      "A tourney circuit, where reputation is the curriculum.",
      "An armoury whose smiths teach the use of what they make.",
      "A garrison on a frontier that has forgotten which war it is fighting.",
      "A ship's deck, where the whole art is footing and timing.",
      "A hall that trains (d4): 1. one student a generation; 2. anyone who survives the door; 3. only the children of members; 4. nobody, any more",
    ],
  },
  {
    title: "d10 Tradition - a wilderness lodge",
    id: "d10traditionlodge_classes",
    roll: [
      "A hunting lodge that has kept the same three rules for four hundred years.",
      "A herders' circuit, taught while walking, over a season.",
      "A ranger station on a border nobody official recognises.",
      "A grove where the teaching is done by being left alone in it.",
      "A trapline inherited from a master who is still owed for it.",
      "A fishing fleet whose reading of weather is indistinguishable from prophecy.",
      "A mountain refuge where the lesson is mostly not dying.",
      "A caravan road, and the teachers are whoever else is walking it.",
      "A burnt-out forest being replanted by people who learn as they go.",
      "A lodge that has (d4): 1. one surviving member; 2. no fixed place; 3. two rival branches; 4. outlived the wilderness it studied",
    ],
  },
  {
    title: "d10 Tradition - a temple or order",
    id: "d10traditiontemple_classes",
    roll: [
      "A cathedral school with a library, a hierarchy and an opinion on everything.",
      "A wandering order that owns nothing and is welcome nowhere twice.",
      "A hospice where the discipline was worked out at bedsides.",
      "A militant order with a rule book, a uniform and a long grudge.",
      "A shrine on a road, tended by whoever is passing, teaching by inscription.",
      "A heresy, taught quietly, and rather more coherent than the orthodoxy.",
      "An oracle's household, where the training is in listening.",
      "A funerary guild that teaches the living out of long practice with the dead.",
      "A reformed order, forgiven on paper and watched in practice.",
      "An order whose god is (d4): 1. dead; 2. silent; 3. new; 4. disputed",
    ],
  },
  {
    title: "d10 Tradition - a college of arts",
    id: "d10traditioncollege_classes",
    roll: [
      "A chartered university with a tower, a rivalry and terrible plumbing.",
      "A single master and three apprentices in a rented workshop.",
      "A correspondence course conducted entirely by letter, and it works.",
      "A library that teaches by permitting access and nothing else.",
      "A guild laboratory where the syllabus is whatever pays this year.",
      "A salon of amateurs whose results embarrass the professionals.",
      "An academy that was closed by decree, and never quite stopped.",
      "A theatre company that teaches performance first and power second.",
      "A cartographers' house whose graduates all end up somewhere strange.",
      "A college that admits students on the basis of (d4): 1. a test; 2. a debt; 3. a dream; 4. who their parents were",
    ],
  },
  {
    title: "d10 Tradition - the wrong side of the law",
    id: "d10traditionoutfit_classes",
    roll: [
      "A thieves' outfit with a training ladder more rigorous than most guilds.",
      "A smuggling crew that teaches nerve, timing and how to be boring on demand.",
      "A prison, where the syllabus is decided by who is in this year.",
      "A gambling house whose regulars taught each other reading people.",
      "A fence's back room, where the whole art is knowing what things are worth.",
      "A crew of wreckers on a bad coast, and the trade is older than the law here.",
      "A forgers' workshop with standards a mint would recognise.",
      "A street, plainly: no teacher, high fees, excellent retention.",
      "A cult of thieves who believe the taking is a rite.",
      "An outfit that is (d4): 1. respectable now; 2. one arrest from ending; 3. run by a child; 4. quietly the local government",
    ],
  },
  {
    title: "d10 Tradition - no tradition at all",
    id: "d10traditionnone_classes",
    roll: [
      "Self-taught out of one stolen book and a great deal of nerve.",
      "Learned from a dying stranger over eleven days.",
      "Copied by watching an enemy, badly at first, and then not badly.",
      "Bargained for, in one transaction, and the price is still being paid.",
      "Inherited whole from a parent who never explained any of it.",
      "Discovered by accident and reverse-engineered ever since.",
      "Given in a dream, incompletely, and the gaps are being guessed at.",
      "Assembled from three incompatible schools that all disown the result.",
      "Taught by a creature that is not a person and does not teach as one.",
      "Nobody taught it. It arrived (d4): 1. after a death; 2. after a fever; 3. after a fall; 4. and has never explained itself",
    ],
  },

  /* ------------------------------------------------------------------
   * The bearing: the blend that gives the class its shape
   * ---------------------------------------------------------------- */
  {
    title: "d20 First bearing - the core tradition",
    id: "d20firstbearing_classes",
    roll: [
      "Fighter: the discipline of standing in the way and not moving.",
      "Barbarian: a body used as a resource, spent hard and recovered slowly.",
      "Rogue: precision, preparation and an unreasonable amount of patience.",
      "Ranger: the craft of a place, learned until the place is an ally.",
      "Monk: a body trained as an instrument rather than a weapon.",
      "Paladin: a promise held so tightly it becomes a power.",
      "Cleric: borrowed authority, exercised on someone else's behalf.",
      "Druid: a bargain with something older and slower than a person.",
      "Wizard: notes, method, and a refusal to accept that magic is mysterious.",
      "Sorcerer: a bloodline or an accident, running whether or not it is wanted.",
      "Warlock: a contract, and the other party keeps the original.",
      "Bard: performance as a craft, and craft as a lever on the world.",
      "Artificer: the conviction that magic is a manufacturing problem.",
      "Alchemist: the same conviction, applied to bodies and to weather.",
      "Assassin: the study of how one carefully chosen death changes a map.",
      "Knight: an institution wearing a person, with all that follows.",
      "Skald: memory as a weapon: what is sung is what happened.",
      "Shaman: a negotiator standing between two crowds, only one of which is alive.",
      "Witch: local, practical, feared by neighbours who use her anyway.",
      "Necromancer: an argument with the fact of endings, conducted at length.",
    ],
  },
  {
    title: "d20 Second bearing - what it leans toward",
    id: "d20secondbearing_classes",
    roll: [
      "toward the Fighter: everything is a stance and a tempo underneath.",
      "toward the Barbarian: it will spend the body before it spends anything else.",
      "toward the Rogue: it would rather solve a problem before the problem notices.",
      "toward the Ranger: it reads ground, weather and tracks as fluently as speech.",
      "toward the Monk: its discipline is physical, and its restraint is the point.",
      "toward the Paladin: it is bound by something stated aloud and witnessed.",
      "toward the Cleric: it acts with borrowed authority and is answerable for it.",
      "toward the Druid: its loyalties do not stop at the edge of people.",
      "toward the Wizard: it wants to write down how it works, and often does.",
      "toward the Sorcerer: it does not entirely control what it can do.",
      "toward the Warlock: something is owed, and the terms are specific.",
      "toward the Bard: it works on people, and it works in public.",
      "toward the Artificer: it carries gear that does half of the work.",
      "toward the Alchemist: it prepares in advance and improvises with chemistry.",
      "toward the Assassin: it plans for one decisive moment and wastes nothing.",
      "toward the Knight: it fights for a name, and the name is not its own.",
      "toward the Skald: it remembers out loud, and being remembered by it matters.",
      "toward the Shaman: it deals with the dead as a matter of ordinary business.",
      "toward the Witch: its power is local, tied to a place, a plant, or a promise.",
      "toward the Necromancer: it treats death as a procedure rather than an end.",
    ],
  },
  {
    title: "d12 How the two mix",
    id: "d12mix_classes",
    roll: [
      "An even halving. Both traditions get equal say and neither is a subclass of the other.",
      "Three parts the first, one part the second: a core that has picked up a habit.",
      "One part the first, three parts the second: the second bearing is really running things.",
      "The first in public, the second in private, and both are honest.",
      "The second only surfaces under pressure, and surprises everyone including its owner.",
      "The first is what was taught. The second is what was learned.",
      "They alternate: the class does one thing until it fails, then the other, by design.",
      "The second is a translation of the first, using different tools for identical ends.",
      "They are in tension, and the class works because of the tension, not despite it.",
      "The first is the body of it, the second is the vocabulary it explains itself in.",
      "The second was grafted on late, and the seam still shows in the level progression.",
      "The mix is uneven by (d4): 1. day and night; 2. indoors and out; 3. alone and in company; 4. peace and war",
    ],
  },
  {
    title: "d20 Class name - first half",
    id: "d20namefirst_classes",
    roll: [
      "Ashen",
      "Iron",
      "Hollow",
      "Quiet",
      "Salt",
      "Gilded",
      "Thorn",
      "Winter",
      "Low",
      "Hallowed",
      "Tidewise",
      "Nine-Fold",
      "Bone",
      "Lamplit",
      "Wandering",
      "Grave",
      "Bright",
      "Broken",
      "Twice-Sworn",
      "Undersung",
    ],
  },
  {
    title: "d20 Class name - second half",
    id: "d20namesecond_classes",
    roll: [
      "Warden",
      "Blade",
      "Cantor",
      "Reckoner",
      "Hand",
      "Marshal",
      "Adept",
      "Keeper",
      "Advocate",
      "Harrower",
      "Steward",
      "Mender",
      "Vagrant",
      "Sentinel",
      "Chandler",
      "Herald",
      "Binder",
      "Kindler",
      "Sable",
      "Reveller",
    ],
  },

  /* ------------------------------------------------------------------
   * The chassis: the mechanical furniture of a class
   * ---------------------------------------------------------------- */
  {
    title: "d8 Hit die",
    id: "d8hitdie_classes",
    roll: [
      "d6, and the class knows it: nothing about it expects to be hit.",
      "d6, unwisely, because the tradition insists on being in the middle of things.",
      "d8, the honest middle, with no apologies.",
      "d8, but it recovers hit dice on a short rest instead of a long one.",
      "d10, and armour it is not always allowed to wear.",
      "d10, and it spends its own hit points as fuel more often than it should.",
      "d12, and it is genuinely built to be the thing that gets hit.",
      "d12, and the catch is (d4): 1. it heals at half rate; 2. it cannot be healed by others; 3. it drops to d8 indoors; 4. temporary hit points never stack for it",
    ],
  },
  {
    title: "d12 Primary abilities",
    id: "d12abilities_classes",
    roll: [
      "Strength and Constitution. It solves problems by outlasting them.",
      "Dexterity and Wisdom. It arrives early and reads the room.",
      "Constitution and Charisma. It is the wall, and the wall talks.",
      "Intelligence and Dexterity. Everything it does was planned twice.",
      "Wisdom and Constitution. Patience is a stat here.",
      "Charisma and Dexterity. Presence first, footwork underneath.",
      "Strength and Charisma. It leads from the front and expects to be followed.",
      "Intelligence and Wisdom. It is right, and it is also correct, which are different.",
      "Dexterity and Constitution. It is very hard to remove from a fight.",
      "Wisdom and Charisma. Two kinds of authority, used in turn.",
      "Intelligence and Charisma. It argues with the world and wins on procedure.",
      "One ability governs everything it does, and that ability is (d4): 1. Strength; 2. Dexterity; 3. Wisdom; 4. Charisma",
    ],
  },
  {
    title: "d10 Saving throws",
    id: "d10saves_classes",
    roll: [
      "Strength and Constitution: it braces well and thinks about it later.",
      "Dexterity and Intelligence: it is quick, and it is hard to fool.",
      "Constitution and Wisdom: the two that keep concentration alive.",
      "Wisdom and Charisma: the pair that fear and possession break against.",
      "Intelligence and Charisma: a scholar's defence and a performer's nerve.",
      "Dexterity and Charisma: it dodges, and then it explains.",
      "Strength and Wisdom: an old-fashioned pairing, and a good one.",
      "Constitution and Charisma: it holds the line and holds the room.",
      "Three saves at low levels, dropping to two at level 5 as the tradition narrows.",
      "Two saves, plus advantage against (d4): 1. poison; 2. being charmed; 3. being moved; 4. anything a superior ordered",
    ],
  },
  {
    title: "d12 Armour and shields",
    id: "d12armour_classes",
    roll: [
      "Light armour only, and it prefers none at all.",
      "Light and medium, no shields: both hands are always doing something.",
      "All armour and shields, and the tradition treats the shield as the weapon.",
      "Medium armour, shields, and a rule against wearing metal.",
      "No armour, and a defence that improves as long as it wears none.",
      "Heavy armour, worn slowly and taken off even more slowly.",
      "Whatever it is wearing when it starts, and it may not change mid-adventure.",
      "Armour it made itself, which counts as one grade higher for this class only.",
      "Light armour, and a shield it is trained to give away in a crisis.",
      "All armour, but the tradition considers wearing it in town an insult.",
      "Armour proficiency arrives late: none at level 1, light at 3, medium at 6.",
      "Its protection is (d4): 1. a worn talisman; 2. a stance; 3. a companion; 4. a promise from someone else",
    ],
  },
  {
    title: "d12 Weapons and tools",
    id: "d12weapons_classes",
    roll: [
      "Simple weapons, and one martial weapon it must name at level 1 and keep.",
      "All martial weapons, and it is expected to be able to use anything to hand.",
      "Simple weapons plus one artisan's tool, which matters more than the weapons.",
      "Two weapons only, forever: the pair the tradition was built around.",
      "Whatever the enemy was carrying: it trains on captured arms by principle.",
      "Improvised weapons count as martial weapons for it, which is the whole trick.",
      "Ranged weapons only. Closing to melee is a failure state in this tradition.",
      "Thieves' tools, a musical instrument and a knife, in that order of importance.",
      "Alchemist's supplies and herbalism kit, and its weapons are consumables.",
      "One weapon it made, which cannot be replaced without a rite.",
      "Weapons are secondary: its proficiencies are three tools and a vehicle.",
      "It is proficient with (d4): 1. everything, badly; 2. one thing, superbly; 3. nothing, and does not need to be; 4. whatever it last saw used well",
    ],
  },
  {
    title: "d12 Skills",
    id: "d12skills_classes",
    roll: [
      "Choose three from Athletics, Insight, Intimidation, Perception, Survival.",
      "Choose three from Acrobatics, Deception, Sleight of Hand, Stealth, Investigation.",
      "Choose two from Arcana, History, Nature, Religion, and one from anything.",
      "Choose four from any list, and it starts with expertise in one of them.",
      "Choose two, and gain a third at level 6 chosen by what it has actually been doing.",
      "Choose two from Medicine, Nature, Survival, Animal Handling, Perception.",
      "Choose three from Performance, Persuasion, Deception, Insight, History.",
      "Two skills, plus proficiency in any one tool it has watched being used for a week.",
      "Choose three, and it has disadvantage on one skill it is forbidden to train.",
      "Choose two, plus a language nobody nearby speaks.",
      "Every skill at half proficiency, and two at full: a generalist with two edges.",
      "Choose (d4): 1. two; 2. three; 3. four; 4. one, with expertise",
    ],
  },
  {
    title: "d12 Starting kit",
    id: "d12kit_classes",
    roll: [
      "A weapon, a bedroll, a tradition's badge, and fifteen gold in mixed coin.",
      "Everything on a strap: this class never puts its pack down.",
      "A tool kit worth more than everything else it owns combined.",
      "Hand-me-downs from a predecessor, including one item that does not fit.",
      "Nothing but what it is wearing, and a letter of introduction.",
      "A uniform it is entitled to wear and a receipt for it that is not paid off.",
      "A book, blank except for the first eleven pages, in someone else's hand.",
      "A sealed package it has been told not to open until level 3.",
      "A holy symbol, a set of dice and a decent coat.",
      "A pack animal, elderly, opinionated, and included in the class features.",
      "Its master's kit, taken without permission, with the master's name still on it.",
      "One item that matters and (d4): 1. a debt; 2. a map; 3. a scar; 4. a witness",
    ],
  },
  {
    title: "d16 The resource it spends",
    id: "d16resource_classes",
    roll: [
      "A pool of dice that shrink a size each time they are spent in a day.",
      "Charges on a physical object, and the object can be taken away.",
      "Spell slots, but they are shared with the whole party by agreement.",
      "Breath: counted, held, and the count is short.",
      "Its own hit points, and nothing else, which shapes every decision it makes.",
      "Favours owed to it, tracked as a number, spendable and renewable socially.",
      "Prepared components ground in advance: no preparation, no power.",
      "Names it has learned, each usable once until the owner is met again.",
      "Momentum, gained by acting first and lost entirely by hesitating.",
      "Marks it puts on the ground or on people, and it can only hold a few at once.",
      "Time: its features cost minutes of a day it never gets back.",
      "A tally of promises kept, and a broken promise empties the pool.",
      "Heat that builds as it fights, useful and eventually dangerous.",
      "Its companion's willingness, which is not infinite and is not commanded.",
      "Concentration, but on things other than spells: on people, doors and lies.",
      "Something it can spend only (d4): 1. once a day; 2. once a scene; 3. while bleeding; 4. when witnessed",
    ],
  },
  {
    title: "d12 How the resource returns",
    id: "d12recovery_classes",
    roll: [
      "A short rest, fully, which makes this class an engine on a long day.",
      "A long rest, and not a moment sooner.",
      "By eating a proper meal, sat down, with company.",
      "By sleeping somewhere it has slept before.",
      "By spending an hour on maintenance: kit, notes, prayers, whetstone.",
      "By being paid, thanked or formally acknowledged.",
      "By reaching a place it has never been.",
      "One point back for each enemy it downs, and no other way.",
      "By singing, telling or writing the day down for someone else.",
      "By touching running water, standing stone or open sky, depending on the tradition.",
      "It refills on its own at dawn, and it cannot be hurried.",
      "It returns when the class (d4): 1. forgives someone; 2. keeps a promise; 3. bleeds; 4. gives something away",
    ],
  },

  /* ------------------------------------------------------------------
   * The twenty levels. Tier one: the class is being assembled
   * ---------------------------------------------------------------- */
  {
    title: "Level 1",
    id: "d12level01_classes",
    roll: [
      "The core trick, usable proficiency-bonus times a day, and everything later is built on it.",
      "A reaction that trades your own movement for somebody else's safety.",
      "Two fighting or working styles, and you must declare which is loaded each dawn.",
      "A pool of dice equal to your level, spent to add to a roll after seeing it.",
      "You always know one thing about a place before entering it, chosen from a short list.",
      "A companion, animal or otherwise, that acts on your turn and shares your fate.",
      "Cantrip-scale magic, thematically narrow, and usable while doing something else.",
      "You can take one action per fight that ordinary training would not permit.",
      "A ritual you can perform in ten minutes that does one small, specific, useful thing.",
      "You mark one creature at the start of a fight, and everything you do to it is a little better.",
      "Rerolls: you get proficiency-bonus of them a day, and you must keep the second result.",
      "You start with (d4): 1. a debt; 2. a patron; 3. an enemy; 4. a rule you cannot break",
    ],
  },
  {
    title: "Level 2",
    id: "d12level02_classes",
    roll: [
      "The class resource formally arrives, with a name and a spending rule.",
      "A second gear: once per rest, act as though you had rested.",
      "You gain a stance or oath you can enter and leave, with a cost to changing it.",
      "You can now spend the level 1 feature on other people instead of yourself.",
      "Half your movement becomes free of terrain, opportunity attacks, or noise: pick one.",
      "Two additional uses of the core trick, and one new way of applying it.",
      "You can prepare a small number of contingencies during a rest and trigger them later.",
      "You gain a written or sung record that lets you recall one exact detail per day.",
      "Your first real magic, or your first real tool, depending on the bearing.",
      "You can take a short rest in ten minutes, once a day, and so can anyone with you.",
      "You learn to fail usefully: on a failed check you gain a point of the class resource.",
      "You gain (d4): 1. a second attack of a limited kind; 2. a defensive reaction; 3. a bonus action dash; 4. an extra prepared option",
    ],
  },
  {
    title: "Level 3 - the branch",
    id: "d12level03_classes",
    roll: [
      "The subclass arrives, and it grants one feature now and one at 6, 10 and 14.",
      "The subclass arrives as a choice made for you by circumstance, not by the player.",
      "Two subclass features at once, and no further ones until level 10.",
      "The subclass is a person: a patron, teacher or rival who grants abilities.",
      "The subclass is a place, and its features work at full strength only there.",
      "The subclass is an object, and losing it suspends the features until it is recovered.",
      "The subclass is a promise, and breaking it swaps you to a different subclass.",
      "The subclass is chosen now and can be changed once, ever, at a real cost.",
      "The branch grants a resource of its own, tracked separately from the class pool.",
      "The branch grants a signature action usable once per fight, and it is loud.",
      "The branch grants proficiencies and social standing rather than combat power.",
      "The branch is decided by (d4): 1. a test; 2. a vote; 3. a dream; 4. whoever pays for the training",
    ],
  },
  {
    title: "Level 4 - improvement",
    id: "d10level04_classes",
    roll: [
      "Ability Score Improvement, or take a feat, as usual.",
      "Ability Score Improvement, or gain a second use of your level 1 feature.",
      "Ability Score Improvement, or take a permanent -1 to a save for +2 to a favoured ability.",
      "Ability Score Improvement, or learn a skill at expertise instead.",
      "Ability Score Improvement, or gain a small at-will magical effect fitting the second bearing.",
      "Ability Score Improvement, or take on an additional oath for an additional feature.",
      "Ability Score Improvement, or gain a companion, follower or apprentice.",
      "Ability Score Improvement, or make one of your daily features recharge on a short rest.",
      "Ability Score Improvement, or gain resistance to one damage type your tradition has fought.",
      "Ability Score Improvement, or (d4): 1. a language and a contact; 2. a tool expertise; 3. a mount; 4. a second stance",
    ],
  },
  {
    title: "Level 5 - the step up",
    id: "d12level05_classes",
    roll: [
      "Extra Attack. The plainest version, and it changes the whole class.",
      "Third-tier magic, or the equivalent scale of effect for a non-caster.",
      "Your core trick now affects everyone within reach instead of one target.",
      "You act twice in the first round of every fight, and once thereafter.",
      "Your damage or effect scales with proficiency bonus from here on.",
      "You can now use the class resource as a reaction as well as an action.",
      "You gain the ability to move somewhere else on the map without crossing the space between.",
      "Enemies you mark are visible to your allies too, and your allies benefit from the mark.",
      "You can hold a second concentration effect, with a save to keep both.",
      "One thing you could do once per day is now at will, in a weakened form.",
      "You can take a third action on any turn where you have already taken damage.",
      "The step up is (d4): 1. an extra attack; 2. an extra spell tier; 3. an aura; 4. a second resource pool",
    ],
  },

  /* ------------------------------------------------------------------
   * Tier two: the class becomes itself
   * ---------------------------------------------------------------- */
  {
    title: "Level 6 - the branch deepens",
    id: "d10level06_classes",
    roll: [
      "A second subclass feature, extending the first rather than adding to it.",
      "An aura of ten feet that does one thing your subclass cares about.",
      "The subclass grants a companion, servant, construct or spirit.",
      "The subclass feature now works while you are unconscious.",
      "You gain the subclass's signature resistance or immunity.",
      "The subclass lets you break one rule of the class chassis: armour, weapons or saves.",
      "You may lend a subclass feature to an ally for an hour, losing it for that time.",
      "The subclass gives you standing: a title, a key, an office and its obligations.",
      "The branch's power increases when your two bearings are in agreement, and only then.",
      "The subclass feature is (d4): 1. always on; 2. once per rest; 3. once per day and enormous; 4. on a trigger you do not control",
    ],
  },
  {
    title: "Level 7 - refinement",
    id: "d10level07_classes",
    roll: [
      "Evasion, or its equivalent for whichever save this class actually lives on.",
      "Your movement stops provoking anything, from anyone, ever.",
      "You can use the class resource on an ally's roll from any distance you can see.",
      "You gain advantage on the first check of any kind you make in a new place.",
      "Your marks, oaths or contracts now persist through your own death for one round.",
      "You may hold one prepared reaction between turns without spending your reaction.",
      "You add half your proficiency bonus to everything you are not proficient in.",
      "You can now do the thing your tradition forbade at level 1, at a price.",
      "One creature type has become entirely readable to you: intent, health and next move.",
      "You gain (d4): 1. a second reaction each round; 2. a free disengage; 3. blindsight at short range; 4. a rerolled save each rest",
    ],
  },
  {
    title: "Level 8 - improvement",
    id: "d10level08_classes",
    roll: [
      "Ability Score Improvement, or take a feat.",
      "Ability Score Improvement, or make your subclass feature recharge on a short rest.",
      "Ability Score Improvement, or gain a permanent follower who can use one of your features.",
      "Ability Score Improvement, or extend every aura you have by ten feet.",
      "Ability Score Improvement, or gain a second signature weapon, tool or focus.",
      "Ability Score Improvement, or convert one daily feature into a per-fight feature.",
      "Ability Score Improvement, or gain expertise in two skills your bearings share.",
      "Ability Score Improvement, or take a curse in exchange for an eighth-level feature now.",
      "Ability Score Improvement, or gain the ability to teach one of your features to another.",
      "Ability Score Improvement, or (d4): 1. a keep; 2. a contract; 3. a companion; 4. an immunity",
    ],
  },
  {
    title: "Level 9 - reach",
    id: "d10level09_classes",
    roll: [
      "Your effects reach a second target within thirty feet at no extra cost.",
      "You can spend an hour to know the answer to one question about the region.",
      "Your class resource can now be spent to negate a hit entirely, once per rest.",
      "You gain fifth-tier magic, or an effect of comparable scale.",
      "You can act in the surprise round always, and so can one ally you touch.",
      "Your reputation now does work: one social encounter a day resolves in your favour.",
      "You can maintain one long-term project (a ward, a hunt, a case) with daily upkeep.",
      "You may split your movement, attacks and reactions across two turns of initiative.",
      "You can borrow a feature from an ally for a minute, once per long rest, with consent.",
      "Reach means (d4): 1. distance; 2. duration; 3. number of targets; 4. how far back in time you can look",
    ],
  },
  {
    title: "Level 10 - the branch again",
    id: "d10level10_classes",
    roll: [
      "The third subclass feature: the branch's real argument, finally stated.",
      "The subclass aura doubles and now affects enemies as well as allies.",
      "Your subclass companion, construct or spirit gains a mind of its own and opinions.",
      "You can invoke the subclass once per day for an effect that ends a scene.",
      "The subclass grants a permanent physical change, and it is visible.",
      "You gain the subclass's capstone early, at half strength, and it grows at 14.",
      "The branch feature now triggers on an ally's action instead of your own.",
      "The subclass grants a place: a shrine, a workshop, a lair, a room that is yours.",
      "You may swap one subclass feature for one from a rival branch, permanently.",
      "The feature costs (d4): 1. nothing; 2. hit points; 3. a memory; 4. an hour of the next day",
    ],
  },

  /* ------------------------------------------------------------------
   * Tier three: the class is a power in the world
   * ---------------------------------------------------------------- */
  {
    title: "Level 11 - the second step up",
    id: "d10level11_classes",
    roll: [
      "A third attack, or sixth-tier magic, or the equivalent leap for this chassis.",
      "Your core trick from level 1 becomes at will, and it is still good.",
      "You gain a second, larger pool of the class resource that only refills weekly.",
      "One of your features now affects a whole battlefield rather than a radius.",
      "You can spend a full round to make one automatic success at anything possible.",
      "Your presence imposes a rule on the area: an effect that shapes how the scene works.",
      "You can undo one of your own actions per day, rewinding a single turn.",
      "You may hold two stances, oaths or preparations at once.",
      "Allies within earshot use your proficiency bonus instead of theirs for one roll a rest.",
      "The leap is (d4): 1. offensive; 2. defensive; 3. social; 4. logistical, and the party notices most",
    ],
  },
  {
    title: "Level 12 - improvement",
    id: "d10level12_classes",
    roll: [
      "Ability Score Improvement, or take a feat.",
      "Ability Score Improvement, or raise one ability above 20 to a maximum of 22.",
      "Ability Score Improvement, or gain a permanent magical effect on your person.",
      "Ability Score Improvement, or gain an apprentice who levels alongside you.",
      "Ability Score Improvement, or make a weekly feature into a daily one.",
      "Ability Score Improvement, or gain immunity to a condition that has nearly killed you.",
      "Ability Score Improvement, or bind a spirit, servant or contract to your service.",
      "Ability Score Improvement, or trade a level 1 feature for a level 12 one.",
      "Ability Score Improvement, or gain a stronghold and the duties that come with it.",
      "Ability Score Improvement, or (d4): 1. flight, briefly; 2. a second reaction; 3. truesight; 4. one extra prepared contingency",
    ],
  },
  {
    title: "Level 13 - mastery begins",
    id: "d10level13_classes",
    roll: [
      "Seventh-tier magic, or the martial equivalent: one action that decides an encounter.",
      "You can perform your class's central ritual in one round instead of ten minutes.",
      "You always act first, in every initiative, unless you choose otherwise.",
      "Your class resource can be spent to give an ally a full turn.",
      "Once a day, ignore one rule of your own class chassis for a minute.",
      "You can create a lasting effect in the world that persists without your presence.",
      "You gain a second body, mirror, echo or stand-in that acts on alternating turns.",
      "You may declare one enemy your business, and no ally of yours can be forced to fight it.",
      "You learn the true name of something, and can use it once a season.",
      "Mastery shows as (d4): 1. speed; 2. certainty; 3. reach; 4. a complete absence of effort",
    ],
  },
  {
    title: "Level 14 - the branch closes",
    id: "d10level14_classes",
    roll: [
      "The final subclass feature: the branch's promise, kept.",
      "Your subclass companion becomes independent and can be sent away to act alone.",
      "The subclass's daily feature becomes twice a day, and the second use is free.",
      "The branch grants an ability that works once and cannot be recovered.",
      "You may extend your subclass's benefit to everyone who shares your tradition.",
      "The subclass now defends you from the thing it warned you about at level 3.",
      "You gain the office, rank or title the branch has been training you toward.",
      "The branch's feature can be spent to cancel an enemy feature of equal scale.",
      "The subclass closes with a cost: the feature is enormous and it takes something.",
      "It ends with (d4): 1. a transformation; 2. an inheritance; 3. a release from your oath; 4. a new oath",
    ],
  },
  {
    title: "Level 15 - the long game",
    id: "d10level15_classes",
    roll: [
      "Eighth-tier magic, or an equivalent once-a-day decisive act.",
      "You no longer need to sleep, eat or breathe: pick two.",
      "Your resource pool refills entirely when you first drop below half hit points.",
      "You can prepare a plan during a rest that lets the whole party act out of turn once.",
      "You become immune to being surprised, frightened, charmed or moved: pick two.",
      "Your marks persist for a week, and the marked cannot hide from you anywhere.",
      "You can spend a day to permanently improve one ally's feature.",
      "You gain a lair action in any place you have slept three nights.",
      "Your death is now a delay rather than an ending, once, and it costs a level of exhaustion.",
      "The long game is played against (d4): 1. an institution; 2. a person; 3. a place; 4. the class's own tradition",
    ],
  },
  {
    title: "Level 16 - improvement",
    id: "d10level16_classes",
    roll: [
      "Ability Score Improvement, or take a feat.",
      "Ability Score Improvement, or raise two abilities above 20 to a maximum of 22.",
      "Ability Score Improvement, or gain a permanent version of a once-a-day feature.",
      "Ability Score Improvement, or take on an apprentice who inherits your class on your death.",
      "Ability Score Improvement, or gain an aura that suppresses one school or style of power.",
      "Ability Score Improvement, or gain the ability to grant your level 1 feature to others.",
      "Ability Score Improvement, or bind your class resource to a place instead of yourself.",
      "Ability Score Improvement, or exchange a subclass feature for one from your second bearing.",
      "Ability Score Improvement, or gain a second reaction and a second bonus action each round.",
      "Ability Score Improvement, or (d4): 1. a domain; 2. a legend; 3. an heir; 4. an ending you get to choose",
    ],
  },

  /* ------------------------------------------------------------------
   * Tier four: the class is near legendary
   * ---------------------------------------------------------------- */
  {
    title: "Level 17 - the third step up",
    id: "d10level17_classes",
    roll: [
      "Ninth-tier magic, or one action a day that no ordinary rule constrains.",
      "A fourth attack, or the equivalent multiplication of whatever this class does.",
      "Your aura now covers everywhere you can see.",
      "You can spend the class resource to make an effect permanent, once ever per effect.",
      "You may take a legendary action once per round on somebody else's turn.",
      "You can be in two places at once for one minute a day.",
      "Your class resource can be spent to grant an ally one of your features permanently.",
      "You gain a second, private initiative count that only you and the DM know.",
      "You can suspend a single ongoing effect in the world indefinitely, holding it yourself.",
      "The step up is felt by (d4): 1. your enemies; 2. your allies; 3. the region; 4. your tradition, which changes",
    ],
  },
  {
    title: "Level 18 - near-legend",
    id: "d10level18_classes",
    roll: [
      "Your signature feature no longer requires the resource at all.",
      "You gain resistance to all damage while your class resource is not empty.",
      "You can act normally at 0 hit points until the end of your next turn.",
      "You may spend an hour to bring a place, an order or a bloodline back from ruin.",
      "You gain a permanent, visible manifestation of your two bearings, and it acts for you.",
      "Once a day you may declare an outcome for a non-combat scene, and it is so.",
      "Your presence counts as your tradition's holy site, workshop or hall wherever you stand.",
      "You are no longer bound by one limitation of your species, tradition or oath.",
      "You can teach your entire class to a willing student in a year and a day.",
      "The near-legend is that you (d4): 1. cannot be killed here; 2. always keep your word; 3. never lose; 4. are already dead",
    ],
  },
  {
    title: "Level 19 - improvement",
    id: "d10level19_classes",
    roll: [
      "Ability Score Improvement, or take a feat.",
      "Ability Score Improvement, or take an epic boon fitting your first bearing.",
      "Ability Score Improvement, or take an epic boon fitting your second bearing.",
      "Ability Score Improvement, or gain a nineteenth-level version of your level 1 feature.",
      "Ability Score Improvement, or make your capstone arrive now, at half strength.",
      "Ability Score Improvement, or hand a feature permanently to each of your companions.",
      "Ability Score Improvement, or bind your class resource so it never empties again.",
      "Ability Score Improvement, or gain a second subclass at level 3 strength.",
      "Ability Score Improvement, or trade every improvement you took for one enormous feature.",
      "Ability Score Improvement, or (d4): 1. an heir; 2. a resurrection; 3. a domain; 4. a name that outlives you",
    ],
  },
  {
    title: "Level 20 - capstone",
    id: "d12level20_classes",
    roll: [
      "Your class resource refills at the start of every fight, in full, forever.",
      "Once a day, take a whole extra turn immediately after your own.",
      "Your two bearings fuse: every feature of one may be used through the other.",
      "You cannot be killed by anything that is not the thing named in your oath.",
      "You may spend your capstone to undo one event of the campaign, once, and then it is gone.",
      "Everything you mark, name or swear against dies on schedule, and you set the schedule.",
      "Your presence makes your tradition true in a radius: its rules govern the area.",
      "You gain a second life: on death, return at dawn somewhere you were happy.",
      "One ability score becomes 24, and one save becomes automatic.",
      "You can grant a level 1 version of your class to anyone, permanently, once a year.",
      "You become the tradition: new members of it gain features from your example.",
      "The capstone costs (d4): 1. nothing; 2. your name; 3. your second bearing; 4. everything, eventually",
    ],
  },

  /* ------------------------------------------------------------------
   * Leaf tables: consulted by the gated tangents below
   * ---------------------------------------------------------------- */
  {
    title: "d20 The third bearing",
    id: "d20thirdbearing_classes",
    roll: [
      "a further quarter turn toward the Fighter, showing only in how it holds ground.",
      "a further quarter turn toward the Barbarian, showing only when it is hurt.",
      "a further quarter turn toward the Rogue, showing only in what it does not announce.",
      "a further quarter turn toward the Ranger, showing only outdoors.",
      "a further quarter turn toward the Monk, showing only in what it refuses.",
      "a further quarter turn toward the Paladin, showing only when it has given its word.",
      "a further quarter turn toward the Cleric, showing only when someone else is dying.",
      "a further quarter turn toward the Druid, showing only in whose side it takes.",
      "a further quarter turn toward the Wizard, showing only in its notes.",
      "a further quarter turn toward the Sorcerer, showing only when it is startled.",
      "a further quarter turn toward the Warlock, showing only when the debt is called.",
      "a further quarter turn toward the Bard, showing only in front of an audience.",
      "a further quarter turn toward the Artificer, showing only in its kit.",
      "a further quarter turn toward the Alchemist, showing only in preparation.",
      "a further quarter turn toward the Assassin, showing only once per campaign.",
      "a further quarter turn toward the Knight, showing only when it is representing someone.",
      "a further quarter turn toward the Skald, showing only in how it tells the story after.",
      "a further quarter turn toward the Shaman, showing only near the recently dead.",
      "a further quarter turn toward the Witch, showing only at home.",
      "a further quarter turn toward the Necromancer, showing only when something ends.",
    ],
  },
  {
    title: "d10 What the third bearing is called",
    id: "d10thirdname_classes",
    roll: [
      "The tradition names it properly, the way a compass names north north west.",
      "It has no name, and members argue about that at every gathering.",
      "It is named after the first person to do it, who did not survive it.",
      "It is named for a place, and the place has since been renamed.",
      "It is called the minor bearing, and is considered slightly embarrassing.",
      "It is called the drift, and elders insist it will correct itself.",
      "It takes the name of the second bearing with a diminutive, which annoys everyone.",
      "It is called by its effect rather than its origin, which suits it.",
      "It has three names, one per rival school, and all three are in use.",
      "It is called (d4): 1. the third hand; 2. the long way round; 3. the second oath; 4. the fault",
    ],
  },
  {
    title: "d12 The subclass branches",
    id: "d12branches_classes",
    roll: [
      "Three branches: one that fights, one that mends, one that investigates.",
      "Two branches only, and choosing one makes an enemy of everyone in the other.",
      "Four branches named after the seasons, and each is strongest in its own.",
      "Three branches named for tools: the hammer, the key and the lamp.",
      "Branches named after the tradition's three founders, who did not get on.",
      "Two branches: the orthodox one, and the one that actually works.",
      "Three branches, and members are expected to pass through all of them in turn.",
      "Branches by locality: the coast branch, the hill branch, the city branch.",
      "One branch, which is unusual enough that it defines the class.",
      "Five branches, and the fifth is only ever taught to one student at a time.",
      "Branches named for what they refuse: the Unarmed, the Unsworn, the Unseen.",
      "The branches are (d4): 1. hereditary; 2. bought; 3. assigned; 4. discovered too late to change",
    ],
  },
  {
    title: "d12 The taboo",
    id: "d12taboo_classes",
    roll: [
      "It may not use its class features while wearing another tradition's colours.",
      "It may not accept payment for using its central feature.",
      "It may not lie about what it is, even by omission, even to save its life.",
      "It may not enter a place it has not been invited into, and this includes ruins.",
      "It may not use its power on a sleeping or unaware target.",
      "It may not eat with an enemy it intends to fight.",
      "It may not carry more than it can run with.",
      "It may not teach any part of its craft to anyone outside the tradition.",
      "It may not spend its resource twice in one hour without paying hit points for the second.",
      "It may not use its name in a place where the name is not already known.",
      "It may not refuse a request for help made three times.",
      "Breaking the taboo costs it (d4): 1. the feature for a day; 2. a level of exhaustion; 3. its subclass; 4. nothing, yet",
    ],
  },
  {
    title: "d12 The signature item",
    id: "d12signature_classes",
    roll: [
      "A weapon issued at level 1 that grows one property per tier.",
      "A tool kit that counts as a spellcasting focus and a holy symbol at once.",
      "A written book that must be updated nightly or the class loses a feature.",
      "A mask worn to work, and the class is a different person while it is on.",
      "A token given by the teacher, returnable on demand, and demands do happen.",
      "An instrument, and its condition tracks the character's own.",
      "A key that opens one thing per tier, chosen when the tier is reached.",
      "A garment that must be repaired and never replaced.",
      "A brand, tattoo or scar that is the item, and cannot be lost or stolen.",
      "A companion animal counted as equipment by the tradition, which the animal resents.",
      "A ledger of debts owed and owing, and the numbers are the class's power.",
      "It is (d4): 1. irreplaceable; 2. cheap and replaceable; 3. shared with another member; 4. not actually theirs",
    ],
  },
  {
    title: "d12 The rival tradition",
    id: "d12rival_classes",
    roll: [
      "The parent school this one broke away from, which wants its notes back.",
      "A newer school teaching the same thing faster and worse.",
      "The other half of the split, teaching the same craft with the bearings reversed.",
      "A guild that has had the practice outlawed in three cities.",
      "A temple that considers the whole tradition a heresy, and is being reasonable about it.",
      "A single practitioner who is better than the entire school and knows it.",
      "An institution that hires this tradition's graduates and denies the tradition exists.",
      "A rival that is not hostile, just cheaper, and it is winning.",
      "The tradition's own alumni association, which has become a political faction.",
      "A school in another country doing this by coincidence, and neither knows of the other.",
      "The class's own second bearing, taught pure, by people who resent the mixing.",
      "The rivalry is currently (d4): 1. violent; 2. legal; 3. social; 4. entirely one-sided",
    ],
  },
  {
    title: "d12 The cost of the bearing",
    id: "d12cost_classes",
    roll: [
      "The two bearings pull apart under stress: on a natural 1, one feature is unusable for a minute.",
      "It ages faster than it should, a year for every two.",
      "It cannot benefit from the same magic twice in a day.",
      "Sleep is unreliable: a long rest works only in a place matching one of the bearings.",
      "Its second bearing has its own agenda and occasionally acts first.",
      "Every level taken in this class costs a memory of the year before it.",
      "Its features are visible to anyone trained in either parent tradition.",
      "Both parent traditions consider it a defector, and both are correct.",
      "It cannot multiclass out: whatever it takes elsewhere is absorbed into this class.",
      "Healing from the second bearing's tradition does not work on it.",
      "It is not recognised anywhere: no guild fee, no licence, no legal standing.",
      "The cost is paid (d4): 1. by the character; 2. by the teacher; 3. by whoever it swore to; 4. later, and all at once",
    ],
  },
  {
    title: "d12 The tradition's secret",
    id: "d12secret_classes",
    roll: [
      "The founder stole the whole method from a tradition that no longer exists.",
      "The class only works because of a bargain nobody current has read.",
      "The second bearing was added to hide what the first bearing really did.",
      "Every member is being quietly counted by something, and the count matters.",
      "The capstone has never been reached by anyone, and the text of it is a guess.",
      "The tradition was designed to produce one specific person, once, and it succeeded.",
      "It is a cover: the real curriculum is taught to one student in ten.",
      "The taboo exists to prevent a discovery, not a sin.",
      "The teaching is being subtly altered each generation by someone outside it.",
      "Two thirds of the recorded history is invented, and the invented part is better.",
      "The class works on the dead as well as the living, and always has.",
      "The secret is known to (d4): 1. nobody; 2. one elder; 3. the rival tradition only; 4. every student, unspoken",
    ],
  },
  {
    title: "d10 How it is regarded",
    id: "d10regard_classes",
    roll: [
      "Respected, in the way a useful and slightly unpleasant necessity is respected.",
      "Fashionable this decade, which the older members find humiliating.",
      "Feared, on a reputation earned two generations ago by someone else.",
      "Unknown outside three valleys, and famous within them.",
      "Assumed to be a joke until it is seen working.",
      "Regulated: licensed practitioners only, and licences are political.",
      "Banned, and practised anyway, with a nod and a fee.",
      "Confused with the rival tradition constantly, to everyone's irritation.",
      "Sought after by armies and refused by temples.",
      "It is regarded as (d4): 1. dangerous; 2. dying out; 3. cheating; 4. the future",
    ],
  },
  {
    title: "d10 Multiclassing into it",
    id: "d10multiclass_classes",
    roll: [
      "Requires 13 in both primary abilities, which is a real barrier for this pair.",
      "Requires an oath sworn in front of a member, and members are rare.",
      "Requires giving up one feature of the class you are coming from.",
      "Requires a year of study, and levels do not arrive until it is finished.",
      "Is forbidden outright: the tradition takes beginners or nobody.",
      "Is easy going in and impossible coming out.",
      "Requires the permission of your second bearing's tradition, which will refuse.",
      "Requires that you already hold levels in one of its two parent classes.",
      "Requires a sponsor who is answerable for everything you do afterwards.",
      "Requires (d4): 1. a fee; 2. a death; 3. a secret; 4. nothing at all, which worries people",
    ],
  },

  /* ------------------------------------------------------------------
   * The gated tangents (sub_rolls entries). percent_to is the chance the
   * whole block appears at all; the "type" gates then pick a variant whose
   * own main_rolls decide which leaf tables get consulted.
   * ---------------------------------------------------------------- */
  {
    title: "The subclass branches",
    singular: "Branch",
    id: "gatebranches_classes",
    roll_type: "type",
    number: "1d1",
    percent_to: "75",
    percent_of: "100",
    roll: [
      {
        title: "The branches are formal, named and taught",
        main_rolls: ["classes/d12branches_classes", "classes/d10regard_classes"],
        sub_rolls: [],
      },
      {
        title: "The branches are a matter of who taught you",
        main_rolls: ["classes/d12branches_classes", "classes/d12rival_classes"],
        sub_rolls: [],
      },
      {
        title: "The branches are contested, and choosing is political",
        main_rolls: [
          "classes/d12branches_classes",
          "classes/d12rival_classes",
          "classes/d10regard_classes",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "A third bearing",
    singular: "Bearing",
    id: "gatethird_classes",
    roll_type: "type",
    number: "1d1",
    percent_to: "35",
    percent_of: "100",
    roll: [
      {
        title: "A quarter turn further, the way north north west sits off north west",
        main_rolls: [
          "classes/d20thirdbearing_classes",
          "classes/d10thirdname_classes",
        ],
        sub_rolls: [],
      },
      {
        title: "A third tradition grafted on by one teacher, against the rules",
        main_rolls: [
          "classes/d20thirdbearing_classes",
          "classes/d10thirdname_classes",
          "classes/d12rival_classes",
        ],
        sub_rolls: [],
      },
      {
        title: "A third bearing that only this character has, and cannot pass on",
        main_rolls: [
          "classes/d20thirdbearing_classes",
          "classes/d10thirdname_classes",
          "classes/d12cost_classes",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "The tradition forbids something",
    singular: "Taboo",
    id: "gatetaboo_classes",
    roll_type: "type",
    number: "1d1",
    percent_to: "40",
    percent_of: "100",
    roll: [
      {
        title: "A rule of the school, enforced by the school",
        main_rolls: ["classes/d12taboo_classes", "classes/d10regard_classes"],
        sub_rolls: [],
      },
      {
        title: "A rule of the power itself, enforced by consequences",
        main_rolls: ["classes/d12taboo_classes", "classes/d12cost_classes"],
        sub_rolls: [],
      },
      {
        title: "A rule that exists to hide something",
        main_rolls: ["classes/d12taboo_classes", "classes/d12secret_classes"],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "There is a signature item",
    singular: "Item",
    id: "gatesignature_classes",
    roll_type: "type",
    number: "1d1",
    percent_to: "30",
    percent_of: "100",
    roll: [
      {
        title: "Issued on joining, and accounted for",
        main_rolls: ["classes/d12signature_classes", "classes/d12kit_classes"],
        sub_rolls: [],
      },
      {
        title: "Made by the student as the final part of training",
        main_rolls: [
          "classes/d12signature_classes",
          "classes/d12taboo_classes",
        ],
        sub_rolls: [],
      },
      {
        title: "Not issued at all: it was taken, inherited or found",
        main_rolls: [
          "classes/d12signature_classes",
          "classes/d12secret_classes",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "There is a rival tradition",
    singular: "Rival",
    id: "gaterival_classes",
    roll_type: "type",
    number: "1d1",
    percent_to: "28",
    percent_of: "100",
    roll: [
      {
        title: "A schism, and both halves still use the same name",
        main_rolls: ["classes/d12rival_classes", "classes/d10regard_classes"],
        sub_rolls: [],
      },
      {
        title: "An outside school that wants this one closed",
        main_rolls: ["classes/d12rival_classes", "classes/d12taboo_classes"],
        sub_rolls: [],
      },
      {
        title: "A rivalry the class inherits whether it wants to or not",
        main_rolls: ["classes/d12rival_classes", "classes/d12cost_classes"],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "The bearings cost something",
    singular: "Cost",
    id: "gatecost_classes",
    roll_type: "type",
    number: "1d1",
    percent_to: "25",
    percent_of: "100",
    roll: [
      {
        title: "A price the tradition is honest about",
        main_rolls: ["classes/d12cost_classes", "classes/d10regard_classes"],
        sub_rolls: [],
      },
      {
        title: "A price discovered around the fifth level, by everyone, alone",
        main_rolls: ["classes/d12cost_classes", "classes/d12taboo_classes"],
        sub_rolls: [],
      },
      {
        title: "A price the tradition denies exists",
        main_rolls: ["classes/d12cost_classes", "classes/d12secret_classes"],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "Multiclassing",
    singular: "Rule",
    id: "gatemulticlass_classes",
    roll_type: "type",
    number: "1d1",
    percent_to: "22",
    percent_of: "100",
    roll: [
      {
        title: "The tradition has a written rule about newcomers",
        main_rolls: [
          "classes/d10multiclass_classes",
          "classes/d12abilities_classes",
        ],
        sub_rolls: [],
      },
      {
        title: "The rule is social rather than mechanical",
        main_rolls: [
          "classes/d10multiclass_classes",
          "classes/d10regard_classes",
        ],
        sub_rolls: [],
      },
      {
        title: "The rule exists because somebody once did it badly",
        main_rolls: [
          "classes/d10multiclass_classes",
          "classes/d12cost_classes",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "The tradition has a secret",
    singular: "Secret",
    id: "gatesecret_classes",
    roll_type: "type",
    number: "1d1",
    percent_to: "15",
    percent_of: "100",
    roll: [
      {
        title: "Kept by the elders, and the students suspect",
        main_rolls: ["classes/d12secret_classes", "classes/d10regard_classes"],
        sub_rolls: [],
      },
      {
        title: "Kept by the power itself, and nobody living knows",
        main_rolls: ["classes/d12secret_classes", "classes/d12cost_classes"],
        sub_rolls: [],
      },
      {
        title: "Not kept at all any more: the rival tradition published it",
        main_rolls: ["classes/d12secret_classes", "classes/d12rival_classes"],
        sub_rolls: [],
      },
    ],
  },
];
