// food.js
//


top.food = [



{"title": "D6 Size", "id":"d6size_exoticfruitsandvegetables", "roll":[
"Tiny – this fruit could be easily flicked away",
"Small – Two or three of these fruit can be held in one hand",
"Normal – this fruit can be held but not concealed in one hand",
"Big – this fruit requires two hands to be lifted",
"Gigantic – a child could easily climb into this fruit",
"Enormous – this fruit is man-sized or larger",   ]},
 {"title": "D8 Grows", "id":"d8grows_exoticfruitsandvegetables", "roll":[
"In the upper reaches of the tree tops",
"In the lower reaches of the tree tops",
"Hanging from branches below the treetops",
"Along the trunk",
"At the base of the tree",
"As part of the roots",
"In a bush",
"On a vine on the ground",   ]},
 {"title": "D20 Shape", "id":"d20shape_exoticfruitsandvegetables", "roll":[
"Spheroid",
"Oblong",
"Spheroid and hastate",
"Spheroid and flat",
"Oblong and flat",
"Long and thick",
"Oblong and hastate",
"Flagon-shaped",
"Star-shaped",
"Rhomboid",
"Pyriform",
"Composed of many smaller spheres",
"Clavate",
"Composed of several larger spheres",
"Pod-shaped",
"Long and thin",
"Hook-shaped",
"Twisted",
"Cone-shaped",
"Blocky",   ]},
 {"title": "D4 Skin Colour", "id":"d4skincolour_exoticfruitsandvegetables", "roll":[
"very light (d10): 1. Grey; 2. Pink; 3. Red; 4. Brown; 5. Orange; 6. Yellow; 7. Green; 8. Cyan; 9. Blue; 10. Violet",
"light (d10): 1. Grey; 2. Pink; 3. Red; 4. Brown; 5. Orange; 6. Yellow; 7. Green; 8. Cyan; 9. Blue; 10. Violet",
"dark (d10): 1. Grey; 2. Pink; 3. Red; 4. Brown; 5. Orange; 6. Yellow; 7. Green; 8. Cyan; 9. Blue; 10. Violet",
"very dark (d10): 1. Grey; 2. Pink; 3. Red; 4. Brown; 5. Orange; 6. Yellow; 7. Green; 8. Cyan; 9. Blue; 10. Violet",   ]},
 {"title": "D20 Skin Texture", "id":"d20skintexture_exoticfruitsandvegetables", "roll":[
"Smooth and matte",
"Smooth and shiny",
"Light, thin, and short fur",
"Short, thick fur",
"Long, thin fur",
"Long, thick fur",
"Sticky",
"Oily",
"Barky",
"Lined",
"Spiky",
"Silky",
"Crackled",
"Saggy",
"Rubbery",
"Abrasive",
"Bumpy",
"Cratery",
"Foamy",
"Metallic",   ]},
 {"title": "D10 Skin Pattern", "id":"d10skinpattern_exoticfruitsandvegetables", "roll":[
"Spots",
"Stripes",
"Spirals",
"Waves",
"Crackles",
"Blots",
"Fractals",
"Streaks",
"Meanders",
"None",   ]},
 {"title": "D4 Skin Pattern Colour", "id":"d4skinpatterncolour_exoticfruitsandvegetables", "roll":[
"very light (d10): 1. Grey; 2. Pink; 3. Red; 4. Brown; 5. Orange; 6. Yellow; 7. Green; 8. Cyan; 9. Blue; 10. Violet",
"light (d10): 1. Grey; 2. Pink; 3. Red; 4. Brown; 5. Orange; 6. Yellow; 7. Green; 8. Cyan; 9. Blue; 10. Violet",
"dark (d10): 1. Grey; 2. Pink; 3. Red; 4. Brown; 5. Orange; 6. Yellow; 7. Green; 8. Cyan; 9. Blue; 10. Violet",
"very dark (d10): 1. Grey; 2. Pink; 3. Red; 4. Brown; 5. Orange; 6. Yellow; 7. Green; 8. Cyan; 9. Blue; 10. Violet",   ]},
 {"title": "D6 Skin Thickness", "id":"d6skinthickness_exoticfruitsandvegetables", "roll":[
"Barely Existent",
"Noticeable",
"Like two or three sheets of paper",
"Thick as cardboard",
"Thick as a finger",
"Thick as an arm",   ]},
 {"title": "D4 Flesh Colour", "id":"d4fleshcolour_exoticfruitsandvegetables", "roll":[
"very light (d10): 1. Grey; 2. Pink; 3. Red; 4. Brown; 5. Orange; 6. Yellow; 7. Green; 8. Cyan; 9. Blue; 10. Violet",
"light (d10): 1. Grey; 2. Pink; 3. Red; 4. Brown; 5. Orange; 6. Yellow; 7. Green; 8. Cyan; 9. Blue; 10. Violet",
"dark (d10): 1. Grey; 2. Pink; 3. Red; 4. Brown; 5. Orange; 6. Yellow; 7. Green; 8. Cyan; 9. Blue; 10. Violet",
"very dark (d10): 1. Grey; 2. Pink; 3. Red; 4. Brown; 5. Orange; 6. Yellow; 7. Green; 8. Cyan; 9. Blue; 10. Violet",   ]},
 {"title": "D20 Consistency", "id":"d20consistency_exoticfruitsandvegetables", "roll":[
"Rock hard",
"Gooey",
"Almost liquid",
"Soft",
"Fleshy",
"Very firm",
"Pasty",
"Gritty",
"Fluffy",
"Buttery",
"Chewy",
"Stringy",
"Layered",
"Segmented",
"Bubbly",
"Starchy",
"Shroomy",
"Gelatinous",
"Crunchy",
"Crystallized",   ]},
{"title": "D6 Taste Base", "id":"d6tastebase_exoticfruitsandvegetables", "roll":[
"Sweet",
"Salty",
"Spicy",
"Sour",
"Bitter",
"Umami",   ]},
{"title": "D20 Taste Addition", "id":"d20tasteaddition_exoticfruitsandvegetables", "roll":[
"Refreshing",
"Sparkling",
"Heavy",
"Creamy",
"Sharp",
"Dusty",
"Burnt",
"Earthy",
"Fermented",
"Greasy",
"Malty",
"Nutty",
"Roasted",
"Smoked",
"Sweet",
"Salty",
"Sour",
"Spicy",
"Bitter",
"Umami",   ]},
{"title": "D8 Seeds", "id":"d8seeds_exoticfruitsandvegetables", "roll":[
"One big core",
"Several small seeds in the core",
"Small seeds throughout the flesh",
"Sticky pollen",
"Small seeds on the outside",
"Underneath the skin",
"On the stem",
"None",   ]},
{"title": "D4 Seed Colour", "id":"d4seedcolour_exoticfruitsandvegetables", "roll":[
"very light (d10): 1. Grey; 2. Pink; 3. Red; 4. Brown; 5. Orange; 6. Yellow; 7. Green; 8. Cyan; 9. Blue; 10. Violet",
"light (d10): 1. Grey; 2. Pink; 3. Red; 4. Brown; 5. Orange; 6. Yellow; 7. Green; 8. Cyan; 9. Blue; 10. Violet",
"dark (d10): 1. Grey; 2. Pink; 3. Red; 4. Brown; 5. Orange; 6. Yellow; 7. Green; 8. Cyan; 9. Blue; 10. Violet",
"very dark (d10): 1. Grey; 2. Pink; 3. Red; 4. Brown; 5. Orange; 6. Yellow; 7. Green; 8. Cyan; 9. Blue; 10. Violet",   ]},
{"title": "D10 Climate", "id":"d10climate_exoticfruitsandvegetables", "roll":[
"Well below freezing",
"Extremely Cold",
"Cold",
"Cool",
"Fresh",
"Warm",
"Very warm",
"Hot",
"Prohibitively hot",
"Volcanically hot",   ]},
{"title": "D60 Special Detail", "id":"d60specialdetail_exoticfruitsandvegetables", "roll":[
"The skin pattern is fluorescent",
"The flesh is fluorescent",
"The seeds are fluorescent",
"Eating it numbs the mouth",
"Several of them appear on a vine",
"It can be used as a firestarter",
"It rapidly shrivels up in the sunlight",
"It cools down the area around it",
"It emits a low hum",
"The colours and patterns on its skin seem to be shifting",
"It is abnormally nutritional",
"It has some form of basic sentience",
"It floats in the air",
"It is extremely difficult to open",
"It is extremely difficult to harvest",
"It spins constantly",
"It is covered in a strange glaze",
"It is extremely rare and prohibitively expensive",
"It is a staple product in alchemy",
"It has powerful healing properties",
"It tastes different with each bite",
"It tastes different with each meal",
"It tastes different to each person",
"It cannot be grown in the wild",
"It grows under water",
"It is a sacred food",
"It is the sole/primary food source of the locals",
"It is charged with electricity",
"It comes in pairs of two",
"It comes in groups of three",
"It never spoils or takes a very, very long time to spoil",
"It is highly poisonous if unprepared",
"It is a powerful hallucinogen",
"It is a famous for being the substance of an alcoholic beverage",
"It absorbs their air around it",
"It cannot be eaten by mortals",
"It cannot be eaten by immortals",
"It's flesh is identical to animal flesh",
"It's a significant explosive hazard",
"It provides temporary powers",
"It provides permanent powers",
"It can be used to induce a century-long sleep",
"It is a very effective painkiller",
"It is loaded with arcane energy",
"It requires gigantic amounts of water",
"It is rumoured to have many mystical properties, but is actually mundane",
"It is or can be distilled into a potency agent",
"It has a very strong stench",
"It is invisible to all but certain people",
"It is invisible to certain people",
"It is treasured by faeries, dryads or other magical creatures",
"It only grows deep underground",
"It grows in the clouds",
"It grows on sentient trees",
"It can be made into a very rich and sought-after colour",
"Eating it is forbidden",
"Eating it is painful",
"It takes several years or decades to ripen",
"It is in some supernatural way “pure”",
"It can alter your personality",   ]},



 {"title": "d12 Tonight, in a witch's hovel, we dine on...", "id":"d12tonightinawitchshovelwedineon_witcheshovel", "roll":[
"Stewed.",
"Roasted.",
"Skewered.",
"Charred.",
"Smoked.",
"Grilled.",
"Sauteed.",
"Battered.",
"Salted.",
"Peppered.",
"Pickled.",
"Fried.",   ]},
 {"title": "d20 ...", "id":"d20_witcheshovel", "roll":[
"Songbird.",
"Catfish.",
"Turtle.",
"Lizard.",
"Eel.",
"Goat.",
"Snake.",
"Rat.",
"Frog.",
"Bat.",
"Newt.",
"Rabbit.",
"Cat.",
"Dog.",
"Knight.",
"Maiden.",
"Thief.",
"Peasant.",
"Dwarf.",
"Halfling.",   ]},
 {"title": "d20 ...with...", "id":"d20with_witcheshovel", "roll":[
"Dumplings.",
"Red cabbage.",
"Green cabbage.",
"Chickpeas.",
"Leeks.",
"Lentils.",
"Broccoli.",
"Peas.",
"Cauliflower.",
"Red beans.",
"String beans.",
"White beans.",
"Black beans.",
"Turnips.",
"Asparagus.",
"Sprouts.",
"Tomatoes.",
"Asparagus.",
"Potatoes.",
"Yams.",   ]},
 {"title": "d20 ...and...", "id":"d20and_witcheshovel", "roll":[
"Carrots.",
"Apples.",
"Cherries.",
"Wild berries.",
"Raspberries.",
"Elder berries.",
"Beets.",
"Squash.",
"Radishes.",
"Pumpkin.",
"Sweet onions.",
"Red onions.",
"Green onions",
"Purple mushrooms.",
"Cave mushrooms.",
"Wild mushrooms.",
"Toadstools.",
"Hot peppers.",
"Fire peppers.",
"Garlic.",   ]},
 {"title": "d20 On the side, there are some...", "id":"d20onthesidetherearesome_witcheshovel", "roll":[
"Rum cakes.",
"Honey cakes.",
"Oat cakes.",
"Lemon cakes.",
"Chocolate cakes.",
"Pumpkin pies.",
"Candied fruits.",
"Chocolate candies.",
"Mice.",
"Leeches.",
"Maggots.",
"Beetles",
"Crickets.",
"Toads.",
"Earthworms.",
"Wriggling tentacles.",
"Assorted cheeses.",
"Little fingers and toes.",
"Unidentifiable brains.",
"Mysterious sausages.",   ]},
 {"title": "d20 To wash it down, we have some...", "id":"d20towashitdownwehavesome_witcheshovel", "roll":[
"Pumpkin juice.",
"White tea.",
"Green tea.",
"Red tea.",
"Black tea.",
"Herbal tea.",
"Floral tea.",
"Homebrew ale.",
"Skunky ale.",
"Pale ale.",
"Dark ale.",
"Sour wine.",
"Sweet wine.",
"White wine.",
"Red wine.",
"Blood wine.",
"Brandy.",
"Whisky.",
"Rum.",
"Black liquid served out of a human skull.",   ]},
 {"title": "d12 ...that leaves you feeling...", "id":"d12thatleavesyoufeeling_witcheshovel", "roll":[
"Refreshed.",
"Peaceful.",
"Anxious.",
"Carefree.",
"Very sleepy.",
"A little light-headed.",
"Somewhat nostalgic.",
"Somewhat melancholy.",
"Somewhat edgy.",
"A little paranoid.",
"Rather dizzy.",
"Rather amorous.",   ]},


{"title": "d12 Tonight, in an undead feasthall, we dine on...", "id":"d12tonightinanundeadfeasthallwedineon_undeadfeast", "roll":[
"Stewed.",
"Roasted.",
"Cold.",
"Boiled.",
"Baked.",
"Blackened.",
"Aged.",
"Worm-infested.",
"Fly-covered.",
"Pickled.",
"Rotted.",
"Decaying.",   ]},
{"title": "d20 ...", "id":"d20_undeadfeast", "roll":[
"Rabbit.",
"Chicken.",
"Duck.",
"Mutton.",
"Pork.",
"Beef.",
"Pheasant.",
"Goose.",
"Trout.",
"Clams.",
"Pork sausage.",
"Duck sausage.",
"Knight.",
"Maiden.",
"Thief.",
"Priest.",
"Mage.",
"Peasant.",
"Dwarf.",
"Halfling.",   ]},
{"title": "d20 ...with...", "id":"d20with_undeadfeast", "roll":[
"Mushy cabbage.",
"Weepy cabbage.",
"Rubbery leeks.",
"Lentils.",
"Peas.",
"Red beans.",
"Black beans.",
"White beans.",
"Turnip mash.",
"Sliced turnips.",
"Rotten potatoes.",
"Cave mushrooms.",
"Black mushrooms.",
"Sweet onions.",
"Red onions.",
"Carrots.",
"Parsnips.",
"Cauliflower.",
"Radishes.",
"Beets.",   ]},
{"title": "d12 ...and...", "id":"d12and_undeadfeast", "roll":[
"Wormy apples.",
"Moldy cherries.",
"Over-ripe tomatoes.",
"Moldy berries.",
"Crumbling cake.",
"Stale bread.",
"Hard biscuits.",
"Moldy biscuits.",
"Bloody gravy.",
"Thin gravy.",
"Moldy cheese.",
"Stinky cheese.",   ]},
{"title": "d12 On the side, there are some...", "id":"d12onthesidetherearesome_undeadfeast", "roll":[
"Mice.",
"Leeches.",
"Maggots.",
"Fish bones.",
"Finger bones.",
"Spare ribs.",
"Stale cakes.",
"Moldy cakes.",
"Rotten eggs.",
"Pieces of brain.",
"Whole brains.",
"Mysterious sausages.",   ]},
{"title": "d12 To wash it down, we have some...", "id":"d12towashitdownwehavesome_undeadfeast", "roll":[
"Still water.",
"White ale.",
"Black ale.",
"Porter.",
"Mead.",
"White wine.",
"Red wine.",
"Blood wine.",
"Brandy.",
"Whisky.",
"Rum.",
"Blood served out of a humanoid skull.",   ]},



{"title": "d12 Tonight, in an orkish camp, we dine on...", "id":"d12tonightinanorkishcampwedineon_orkishcamp", "roll":[
"Stewed.",
"Roasted.",
"Skewered.",
"Raw.",
"Smoked.",
"Grilled.",
"Roasted.",
"Flame-broiled.",
"Charred.",
"Blackened.",
"Spoiled.",
"Rotted.",   ]},
{"title": "d20 ...", "id":"d20_orkishcamp", "roll":[
"Songbird.",
"Mutton.",
"Pork.",
"Horse.",
"Rabbit.",
"Wild beast.",
"Lizard.",
"Snake.",
"Wolf.",
"Bear.",
"Cat.",
"Dog.",
"Manflesh.",
"Maiden.",
"Soldier.",
"Nomad.",
"Farmfolk.",
"Bandit.",
"Dwarf.",
"Halfling.",   ]},
{"title": "d10 ...with...", "id":"d10with_orkishcamp", "roll":[
"Soft potatoes.",
"Hard potatoes.",
"White beans.",
"Red beans.",
"Black beans.",
"Corn mash.",
"Bitter cabbage.",
"Weepy cabbage.",
"Onions.",
"Turnips.",   ]},
{"title": "d10 ...and...", "id":"d10and_orkishcamp", "roll":[
"Stale bread.",
"Crusty biscuits.",
"Hard tack.",
"Moldy bread.",
"Moldy biscuits.",
"Black mushrooms.",
"Bloody gravy.",
"Thick gravy.",
"Thin gravy.",
"Moldy fruit.",   ]},
{"title": "d12 On the side, there are some...", "id":"d12onthesidetherearesome_orkishcamp", "roll":[
"Roasted rats.",
"Raw rat tails.",
"Maggots.",
"Rabbit bones.",
"Old fish.",
"Dried fish.",
"Bitter roots.",
"Chewy roots.",
"Stale cakes.",
"Human fingers.",
"Frogs or toads.",
"Pig's feet.",   ]},
{"title": "d12 To wash it down, we have some...", "id":"d12towashitdownwehavesome_orkishcamp", "roll":[
"Foul ale.",
"Skunky ale.",
"Stolen ale.",
"Strong ale.",
"Black ale.",
"Rich porter.",
"Stolen wine.",
"Sour wine.",
"Strong wine.",
"Pigs' blood.",
"Man blood.",
"Stolen whisky.",   ]},


 {"title": "d10 Tonight, in a goblin hideout, we dine on...", "id":"d10tonightinagoblinhideoutwedineon_goblinhideout", "roll":[
"Stewed.",
"Toasted.",
"Skewered.",
"Raw.",
"Smoked.",
"Grilled.",
"Seared.",
"Flame-broiled.",
"Charred.",
"Blackened.",   ]},
 {"title": "d10 ...", "id":"d10_goblinhideout", "roll":[
"Rabbit.",
"Duck.",
"Pork.",
"Cave fish.",
"Trout.",
"Clams.",
"Bat.",
"Rat.",
"Sausage.",
"Mystery meat.",   ]},
 {"title": "d12 ...with...", "id":"d12with_goblinhideout", "roll":[
"Potatoes.",
"Red cabbage.",
"White cabbage.",
"Leeks.",
"Lentils.",
"Rhubarb.",
"Peas.",
"Sliced turnips.",
"Turnip mash.",
"Parsnips.",
"Red onions.",
"Yellow onions.",   ]},
 {"title": "d12 ...and...", "id":"d12and_goblinhideout", "roll":[
"Stale bread.",
"Crusty biscuits.",
"Hard tack.",
"Wild mushrooms.",
"Sliced mushrooms.",
"Black mushrooms.",
"Purple mushrooms.",
"Cave mushrooms.",
"Truffles.",
"Yellow mold.",
"Blue mold.",
"Green mold.",   ]},
 {"title": "d12 On the side, there are some...", "id":"d12onthesidetherearesome_goblinhideout", "roll":[
"Mice.",
"Toad legs.",
"Crickets.",
"Earthworms.",
"Snails.",
"Stale cakes.",
"Pixie cakes.",
"Pig's feet.",
"Rat tails.",
"Lizards.",
"Snakes.",
"Bitter roots.",   ]},
 {"title": "d8 To wash it down, we have some...", "id":"d8towashitdownwehavesome_goblinhideout", "roll":[
"Foul ale.",
"Skunky ale.",
"Stolen ale.",
"Sour wine.",
"Strong wine.",
"Bitter tea.",
"Black tea.",
"Stolen whisky.",   ]},


 {"title": "d12 Tonight, among swampfolk, we dine on...", "id":"d12tonightamongswampfolkwedineon_swampfolk", "roll":[
"Stewed.",
"Roasted.",
"Skewered.",
"Charred.",
"Smoked.",
"Grilled.",
"Sauteed.",
"Battered.",
"Salted.",
"Peppered.",
"Pickled.",
"Fried.",   ]},
 {"title": "d20 ...", "id":"d20_swampfolk", "roll":[
"Bass.",
"Catfish.",
"Crayfish.",
"Crocodile.",
"Eel.",
"Prawns.",
"Snake.",
"Swamp rat.",
"Frog.",
"Gar.",
"Duck.",
"Pelican.",
"Sunfish.",
"Baby eel.",
"Lizard.",
"Boar.",
"Turtle.",
"Clams.",
"Oysters.",
"Carp.",   ]},
 {"title": "d12 ...with...", "id":"d12with_swampfolk", "roll":[
"Potatoes.",
"Red cabbage.",
"Leeks.",
"Chickpeas.",
"Corn.",
"String beans.",
"Red beans.",
"White beans.",
"Black beans.",
"Leafy greens.",
"Bitter greens.",
"Chopped tomatoes.",   ]},
 {"title": "d10 ...and...", "id":"d10and_swampfolk", "roll":[
"Sweet onions.",
"Green onions.",
"Mushrooms.",
"Sweet peppers.",
"Hot peppers.",
"Fire peppers.",
"Lemon.",
"Tomato sauce.",
"Pecans.",
"Mixed berries.",   ]},
 {"title": "d12 On the side, there is some...", "id":"d12onthesidethereissome_swampfolk", "roll":[
"Crusty bread.",
"Honey cake.",
"Corn bread.",
"Oat cake.",
"Rum cake.",
"Fluffy biscuit.",
"Hard biscuit.",
"Crocodile sausage.",
"Dried fish.",
"Bacon.",
"Fried egg.",
"Turtle soup.",   ]},
 {"title": "d10 To wash it down, we have some...", "id":"d10towashitdownwehavesome_swampfolk", "roll":[
"Black tea.",
"Sweet tea.",
"Pale ale.",
"Skunky ale.",
"Strong wine.",
"Sweet wine.",
"Absinthe.",
"Spiced rum.",
"Rum punch.",
"Whisky.",   ]},



{"title": "d10 Tonight, at a seaside cafe, we dine on...", "id":"d10tonightataseasidecafewedineon_seasidecafe", "roll":[
"Stewed.",
"Breaded.",
"Fried.",
"Battered.",
"Baked.",
"Brined.",
"Seared.",
"Peppered.",
"Salted.",
"Smoked.",   ]},
 {"title": "d20 ...", "id":"d20_seasidecafe", "roll":[
"Clams.",
"Crab.",
"Lobster.",
"Mussels.",
"Oysters.",
"Squid.",
"Shrimp.",
"Prawns.",
"Chicken.",
"Lamb.",
"Mutton.",
"Steak.",
"Beef.",
"Veal.",
"Scallops.",
"Artichokes.",
"Eggplant.",
"Sweet sausage.",
"Mild sausage.",
"Spicy sausage.",   ]},
 {"title": "d10 ...with...", "id":"d10with_seasidecafe", "roll":[
"Golden potatoes.",
"Red potatoes.",
"Long, thin pasta.",
"Short, broad pasta.",
"Curly pasta.",
"Spiral pasta.",
"Red beans.",
"White beans.",
"Garbanzo beans.",
"Rice.",   ]},
 {"title": "d12 ...and...", "id":"d12and_seasidecafe", "roll":[
"Asparagus.",
"Broccoli.",
"Capers.",
"Scallions.",
"Small, sweet tomatoes.",
"Tomato wedges.",
"Black olives.",
"Green olives.",
"Red olives.",
"Peas.",
"Carrots.",
"Arugula.",   ]},
 {"title": "d12 ...dressed with...", "id":"d12dressedwith_seasidecafe", "roll":[
"Olive oil and basil.",
"Olive oil and oregano.",
"Olive oil and garlic.",
"Olive oil and lemon juice.",
"Olive oil and pungent cheese.",
"Olive oil and vinegar.",
"White wine sauce.",
"Red wine sauce.",
"Creamy cheese sauce.",
"Butter sage sauce.",
"Tomato sauce with basil.",
"Tomato sauce with garlic.",   ]},
 {"title": "d8 On the side, there is...", "id":"d8onthesidethereis_seasidecafe", "roll":[
"Fresh bread.",
"Crusty bread.",
"Buttered bread.",
"Garlic bread.",
"A plate of olives.",
"A plate of almonds.",
"A plate of pistachios.",
"A plate of cheeses.",   ]},
 {"title": "d10 To wash it down, we have some...", "id":"d10towashitdownwehavesome_seasidecafe", "roll":[
"Mediocre ale.",
"Strong coffee.",
"Coffee with milk.",
"Sour wine.",
"Sweet wine.",
"White wine.",
"Rosé.",
"Red wine.",
"Strong wine.",
"Brandy.",   ]},


{"title": "d8 Tonight, in the mages' academy dining hall, we dine on...", "id":"d8tonightinthemagesacademydininghallwedineon_magesacademy", "roll":[
"Stewed.",
"Roasted.",
"Fried.",
"Baked.",
"Grilled.",
"Seared.",
"Salted.",
"Candied.",   ]},
 {"title": "d12 ...", "id":"d12_magesacademy", "roll":[
"Rabbit.",
"Pheasant.",
"Duck.",
"Bat.",
"Pork.",
"Beef.",
"Goose.",
"Trout.",
"Oysters.",
"Blood sausage.",
"Pork sausage.",
"Meat pie.",   ]},
 {"title": "d20 ...with...", "id":"d20with_magesacademy", "roll":[
"Dumplings.",
"Sweet cabbage.",
"Caramelized onions.",
"Pumpkin.",
"Butternut squash.",
"Peas.",
"Kidney beans.",
"String beans.",
"Pudding.",
"Asparagus.",
"Sprouts.",
"Potatoes.",
"Mushrooms.",
"Toadstools.",
"Squash.",
"White beans.",
"Red onions.",
"Spinach.",
"Cucumber.",
"Pickles.",   ]},
 {"title": "d12 ...and...", "id":"d12and_magesacademy", "roll":[
"Carrots.",
"Apples.",
"Cherries.",
"Tomatoes.",
"Pears.",
"Strawberries.",
"Pumpkin seeds.",
"Walnuts.",
"Pecans.",
"Almonds.",
"Parsley.",
"Turnips.",   ]},
 {"title": "d12 On the side, there is some...", "id":"d12onthesidethereissome_magesacademy", "roll":[
"Elvish bread.",
"Chocolate molded into the shape of frogs.",
"Cinnamon bread.",
"Pumpkin bread.",
"Chocolate candy.",
"Caramel candy.",
"Cheese cake.",
"Rum cake.",
"Sugar cake.",
"Fruit tart.",
"Pumpkin pie.",
"Blueberry pie.",   ]},
 {"title": "d12 To wash it down, we have some...", "id":"d12towashitdownwehavesome_magesacademy", "roll":[
"Pumpkin juice.",
"Buttery ale.",
"Root beer.",
"Ginger beer",
"Fizzy ale.",
"Chocolate stout.",
"Coffee stout.",
"Apple cider.",
"Pear cider.",
"Sweet tea.",
"Herbal tea.",
"Hot cocoa.",   ]},



{"title": "d10 Tonight, among islanders, we dine on...", "id":"d10tonightamongislanderswedineon_islanders", "roll":[
"Stewed.",
"Breaded.",
"Fried.",
"Battered.",
"Baked.",
"Brined.",
"Seared.",
"Peppered.",
"Salted.",
"Pickled.",   ]},
 {"title": "d20 ...", "id":"d20_islanders", "roll":[
"Clams.",
"Crab.",
"Anchovies.",
"Scallops.",
"Mussels.",
"Sea bass.",
"Skate.",
"Cuttlefish.",
"Flounder.",
"Grouper.",
"Marlin.",
"Shrimp.",
"Sardines.",
"Tuna.",
"Snapper.",
"Lobster.",
"Monkfish.",
"Shark.",
"Seabird.",
"Pork.",   ]},
 {"title": "d10 ...with...", "id":"d10with_islanders", "roll":[
"Wild rice.",
"White rice.",
"Brown rice.",
"Yams.",
"Lentils.",
"Red beans.",
"Black beans.",
"White beans.",
"Plantains.",
"Coconut.",   ]},
 {"title": "d10 ...and...", "id":"d10and_islanders", "roll":[
"Carrots.",
"Mixed nuts.",
"Sweet cabbage.",
"Leafy greens.",
"Dill weed.",
"Lemongrass.",
"Peas.",
"Parsley.",
"Green onions.",
"Yellow onions.",   ]},
 {"title": "d12 On the side, there is some...", "id":"d12onthesidethereissome_islanders", "roll":[
"Coconut cake.",
"Pineapple cake.",
"Banana bread.",
"Honeydew.",
"Pineapple.",
"Papaya.",
"Cantaloupe.",
"Starfruit.",
"Bacon.",
"Fried egg.",
"Ham.",
"Turtle soup.",   ]},
 {"title": "d10 To wash it down, we have some...", "id":"d10towashitdownwehavesome_islanders", "roll":[
"Sun tea.",
"Sweet tea.",
"Pale ale.",
"Skunky ale.",
"Strong wine.",
"Sweet wine.",
"Dry rum.",
"Spiced rum.",
"Rum punch.",
"Coconut water.",   ]},




{"title": "d10 Tonight, among easterlings, we dine on...", "id":"d10tonightamongeasterlingswedineon_easterlings", "roll":[
"Stewed.",
"Roasted.",
"Fried.",
"Boiled.",
"Baked.",
"Grilled.",
"Seared.",
"Steamed.",
"Salted.",
"Pickled.",   ]},
 {"title": "d12 ...", "id":"d12_easterlings", "roll":[
"Rabbit.",
"Chicken.",
"Duck.",
"Pork.",
"Beef.",
"Trout.",
"Catfish.",
"Eel.",
"Squid.",
"Crab.",
"Pork sausage.",
"Duck sausage.",   ]},
 {"title": "d12 ...with...", "id":"d12with_easterlings", "roll":[
"Dumplings.",
"Egg noodles.",
"Rice noodles.",
"Long noodles.",
"Sticky rice.",
"Long-grain rice.",
"Yellow rice.",
"Soybeans.",
"Lentils.",
"String beans.",
"Red beans.",
"Mushrooms.",   ]},
 {"title": "d12 ...and...", "id":"d12and_easterlings", "roll":[
"Carrots.",
"Cabbage.",
"Onions.",
"Water chestnuts.",
"Leeks.",
"Lentils.",
"Broccoli.",
"Peas.",
"Sprouts.",
"Sweet peppers.",
"Hot peppers.",
"Oranges.",   ]},
 {"title": "d10 ...doused with...", "id":"d10dousedwith_easterlings", "roll":[
"Soy sauce.",
"Sweet-and-sour sauce.",
"Spicy vinegar.",
"Hot mustard.",
"Sweet mustard.",
"Pepper oil.",
"Peanut oil.",
"Ginger.",
"Spicy curry.",
"Hot curry.",   ]},
 {"title": "d20 On the side, there is some...", "id":"d20onthesidethereissome_easterlings", "roll":[
"Raw tuna.",
"Raw skate.",
"Raw trout.",
"Raw herring.",
"Raw horse.",
"Dog meat.",
"Pickled cabbage.",
"Pickled onion.",
"Pickled radish.",
"Pickled cucumber.",
"Pickled fish.",
"Honey bee larva.",
"Fried grasshopper.",
"Red bean paste.",
"Sticky bread.",
"Fresh baked bread.",
"Crispy fried dough.",
"Fried egg.",
"Balut.",
"Bird's nest soup.",   ]},
 {"title": "d10 To wash it down, we have some...", "id":"d10towashitdownwehavesome_easterlings", "roll":[
"Water.",
"White tea.",
"Green tea.",
"Red tea.",
"Black tea.",
"Herbal tea.",
"Floral tea.",
"Bitter wine.",
"Rice wine.",
"Fire-water.",   ]},




 {"title": "d8 Tonight, among desert nomads, we dine on...", "id":"d8tonightamongdesertnomadswedineon_nomads", "roll":[
"Fried.",
"Roasted.",
"Sun-cured.",
"Smoked.",
"Sun-baked.",
"Toasted.",
"Seared.",
"Salted.",   ]},
 {"title": "d12 ...", "id":"d12_nomads", "roll":[
"Goat.",
"Mutton.",
"Camel.",
"Horse.",
"Hare.",
"Antelope.",
"Lizard.",
"Snake.",
"Rattlesnake.",
"Buzzard.",
"Toad.",
"Beetles.",   ]},
 {"title": "d10 ...with...", "id":"d10with_nomads", "roll":[
"Chickpeas.",
"White beans.",
"Red beans.",
"Black beans.",
"Lentils.",
"Corn mash.",
"Couscous.",
"Crisp bread.",
"Flat bread.",
"Dry crackers.",   ]},
 {"title": "d12 ...and...", "id":"d12and_nomads", "roll":[
"Wild mushrooms.",
"Almond butter.",
"Cashew butter.",
"Goat cheese.",
"Camel's milk cheese.",
"Onions.",
"Sweet peppers.",
"Hot peppers.",
"Lemons.",
"Oranges.",
"Green olives.",
"Red olives.",   ]},
 {"title": "d12 On the side, there are some...", "id":"d12onthesidetherearesome_nomads", "roll":[
"Almonds.",
"Cashews.",
"Pistachios.",
"Pine nuts.",
"Sunflower seeds.",
"Melon seeds.",
"Dried figs.",
"Dried berries.",
"Raisins.",
"Prunes.",
"Sun-dried tomatoes.",
"Dried root vegetables.",   ]},
 {"title": "d12 To wash it down, we have some...", "id":"d12towashitdownwehavesome_nomads", "roll":[
"Skunky beer.",
"Cornmeal ale.",
"Golden ale.",
"Oatmeal stout.",
"Honeyed mead.",
"Honeyed wine.",
"Sour wine.",
"Strong wine.",
"Tea.",
"Water.",
"Fermented mare's milk.",
"Fermented camel's milk.",   ]},


{"title": "d12 Tonight, among jungle dwellers, we dine on...", "id":"d12tonightamongjungledwellerswedineon_dajd", "roll":[
"Stewed.",
"Roasted.",
"Skewered.",
"Charred.",
"Smoked.",
"Grilled.",
"Sauteed.",
"Toasted.",
"Salted.",
"Peppered.",
"Pickled.",
"Fried.",   ]},
{"title": "d12 ...", "id":"d12_dajd", "roll":[
"Frog.",
"Carp.",
"Crocodile.",
"Lizard.",
"Goat.",
"Songbird.",
"Waterfowl.",
"Turtle.",
"Panther.",
"Monkey.",
"Snake.",
"Boar.",   ]},
{"title": "d12 ...with...", "id":"d12with_dajd", "roll":[
"Casava.",
"Taro.",
"Lettuce.",
"Avocado.",
"Onions.",
"White beans.",
"Red beans.",
"Leafy greens.",
"Bitter greens.",
"Hot peppers.",
"Coconut.",
"Yams.",   ]},
{"title": "d6 ...and...", "id":"d6and_dajd", "roll":[
"Banana.",
"Mango.",
"Guava.",
"Figs.",
"Mixed nuts.",
"Mixed berries.",   ]},
{"title": "d8 On the side, there are some...", "id":"d8onthesidetherearesome_dajd", "roll":[
"Cockroaches.",
"Beetles.",
"Oysters.",
"Slugs.",
"Snails.",
"Clams.",
"Crayfish.",
"Grubs.",   ]},
{"title": "d10 To wash it down, we have some...", "id":"d10towashitdownwehavesome_dajd", "roll":[
"Skunky beer.",
"Golden ale.",
"Sour wine.",
"Honeyed wine.",
"Floral tea.",
"Red tea.",
"Coffee.",
"Cocoa.",
"Water.",
"Goat's milk.",   ]},



{"title": "d10 Tonight, at a mining town pub, we dine on...", "id":"d10tonightataminingtownpubwedineon", "roll":[
"Stewed.",
"Roasted.",
"Fried.",
"Smoked.",
"Baked.",
"Brined.",
"Seared.",
"Peppered.",
"Salted.",
"Pickled.",   ]},
 {"title": "d10 ...", "id":"d10mt", "roll":[
"Goat.",
"Chicken.",
"Blackbird.",
"Mutton.",
"Lamb.",
"Ram.",
"Ewe.",
"Pork.",
"Sausage.",
"Bacon.",   ]},
 {"title": "d12 ...with...", "id":"d12mtwith", "roll":[
"Golden potatoes.",
"Red potatoes.",
"Beets.",
"Leeks.",
"Lentils.",
"Red beans.",
"Black beans.",
"White beans.",
"Turnip mash.",
"Diced turnips.",
"White onions.",
"Yellow onions.",   ]},
 {"title": "d10 ...and...", "id":"d10mtand", "roll":[
"Carrots.",
"Red cabbage.",
"Green cabbage.",
"Purple cabbage.",
"Mushrooms.",
"Pine nuts.",
"Raisins.",
"Parsley.",
"Radishes.",
"Peas.",   ]},
 {"title": "d10 On the side, there is some...", "id":"d10mtonthesidethereissome", "roll":[
"Hard tack.",
"Fresh bread.",
"Crusty bread.",
"Rye bread.",
"Oat bread.",
"Pumpernickel bread.",
"Sharp cheese.",
"Stinky cheese.",
"Goat cheese.",
"Sheep's milk cheese.",   ]},
 {"title": "d10 To wash it down, we have some...", "id":"d10mttowashitdownwehavesome", "roll":[
"Bitter ale.",
"Wheat ale.",
"Black ale.",
"Stout.",
"Porter.",
"Mead.",
"Strong wine.",
"Red wine.",
"Brandy.",
"Whisky.",   ]},



 {"title": "d10 Tonight, at a hunters' lodge, we dine on...", "id":"d10tonightatahunterslodgewedineon", "roll":[
"Stewed.",
"Roasted.",
"Skewered.",
"Braised.",
"Smoked.",
"Grilled.",
"Seared.",
"Flame-broiled.",
"Salted.",
"Peppered.",   ]},
 {"title": "d20 ...", "id":"d20hl", "roll":[
"Rabbit.",
"Quail.",
"Duck.",
"Swan.",
"Boar.",
"Aurochs.",
"Pheasant.",
"Goose.",
"Trout.",
"Pike.",
"Clams.",
"Bear.",
"Venison.",
"Hare.",
"Beaver.",
"Wolf.",
"Squirrel.",
"Otter.",
"Hind.",
"Mockingbird.",   ]},
 {"title": "d12 ...with...", "id":"d12hlwith", "roll":[
"Potatoes.",
"Red cabbage.",
"White cabbage.",
"Leeks.",
"Lentils.",
"Rhubarb.",
"Peas.",
"Turnips.",
"Parsnips.",
"String beans.",
"Chives.",
"Onions.",   ]},
 {"title": "d12 ...and...", "id":"d12hland", "roll":[
"Carrots.",
"Apples.",
"Cherries.",
"Wild mushrooms.",
"Sliced mushrooms.",
"Black mushrooms.",
"Truffles.",
"Rosemary.",
"Sage.",
"Parsley.",
"Pine nuts.",
"Raisins.",   ]},
 {"title": "d12 On the side, there is some...", "id":"d12hlonthesidethereissome", "roll":[
"Rye bread.",
"Wheat bread.",
"Crusty bread.",
"Sesame bread.",
"Oat cake.",
"Pumpernickel bread.",
"Hard tack.",
"Dry flatbread.",
"Honey cake.",
"Deer sausage.",
"Boar's feet.",
"Sow's ear.",   ]},
 {"title": "d10 To wash it down, we have some...", "id":"d10hltowashitdownwehavesome", "roll":[
"Dark ale.",
"Pale ale.",
"Lager.",
"Stout.",
"Strong wine.",
"Sweet wine.",
"White wine.",
"Red wine.",
"Tea.",
"Whisky.",   ]},



{"title": "d8 Tonight, in an elvish dwelling, we dine on...", "id":"d8tonightinanelvishdwellingwedineon", "roll":[
"Stewed.",
"Roasted.",
"Boiled.",
"Simmered.",
"Smoked.",
"Baked.",
"Marinated.",
"Peppered.",   ]},
 {"title": "d12 ...", "id":"d12el", "roll":[
"Boar.",
"Rabbit.",
"Pheasant.",
"Goose.",
"Trout.",
"Pike.",
"Clams.",
"Chestnuts.",
"Wild rice.",
"Leafy greens.",
"White beans.",
"Red beans.",   ]},
 {"title": "d12 ...with...", "id":"d12elwith", "roll":[
"Green cabbage.",
"Sweet cabbage.",
"Wild arugula.",
"Wild rhubarb.",
"Sugarsnap peas.",
"Wild carrots.",
"Wild parsnips.",
"String beans.",
"Green onions.",
"Sweet onions.",
"Wild mushrooms.",
"Cave mushrooms.",   ]},
 {"title": "d12 ...and...", "id":"d12eland", "roll":[
"Apples.",
"Pears.",
"Lemons.",
"Rose petals.",
"Dandelions.",
"Flower petals.",
"Elder petals.",
"Red berries.",
"Black berries.",
"Blueberries.",
"Grapes.",
"Plums.",   ]},
 {"title": "d8 On the side, there is some...", "id":"d8elonthesidethereissome", "roll":[
"Crispy bread.",
"Fluffy bread.",
"Oat cake.",
"Honey cake.",
"Oat cake.",
"Flatbread.",
"Assorted fruit.",
"Assorted cheese.",   ]},
 {"title": "d12 To wash it down, we have some...", "id":"d12eltowashitdownwehavesome", "roll":[
"Spring water.",
"Sweet water.",
"Floral tea.",
"Strong tea.",
"Sweet wine.",
"Honey wine.",
"White wine.",
"Rosé.",
"Red wine.",
"Dark wine.",
"Ancient wine.",
"Young wine.",   ]},
 {"title": "d8 ...that leaves you feeling...", "id":"d8elthatleavesyoufeeling", "roll":[
"Refreshed.",
"Peaceful.",
"Content.",
"Carefree.",
"A little sleepy.",
"A little light-headed.",
"Rather nostalgic.",
"Rather melancholy.",   ]},



{"title": "d12 Tonight, in a dwarvish alehouse, we dine on...", "id":"d12tonightinadwarvishalehousewedineon", "roll":[
"Stewed.",
"Flame-roasted.",
"Glazed and skewered.",
"Braised.",
"Smoked.",
"Battered and fried.",
"Glazed and seared.",
"Flame-broiled.",
"Salted and grilled.",
"Peppered and grilled.",
"Stone oven-roasted.",
"Stone oven-baked.",   ]},
{"title": "d12 ...", "id":"d12dwarven", "roll":[
"Rabbit.",
"Duck.",
"Goose.",
"Boar.",
"Pork.",
"Ox.",
"Trout.",
"Salmon.",
"Venison.",
"Mutton.",
"Steak.",
"Pheasant.",   ]},
{"title": "d10 ...with...", "id":"d10dwwith", "roll":[
"Red potatoes.",
"Golden potatoes.",
"Red cabbage.",
"White cabbage.",
"Green cabbage.",
"Peas.",
"Sliced turnips.",
"Turnip mash.",
"White onions.",
"Red onions.",   ]},
{"title": "d10 ...and...", "id":"d10dwand", "roll":[
"Carrots.",
"Apples.",
"Cherries.",
"Cave mushrooms.",
"Purple mushrooms.",
"Wild mushrooms.",
"Truffles.",
"Thick gravy.",
"Rich gravy.",
"Garlic.",   ]},
{"title": "d12 On the side, there is some...", "id":"d12dwonthesidethereissome", "roll":[
"Rye bread.",
"Wheat bread.",
"Crusty bread.",
"Honey cake.",
"Oat cake.",
"Poppyseed cake.",
"Hard biscuit.",
"Fluffy biscuit.",
"Pork sausage.",
"Deer sausage.",
"Bacon.",
"Ham.",   ]},
{"title": "d12 To wash it down, we have some...", "id":"d12dwtowashitdownwehavesome", "roll":[
"Black ale.",
"Pale ale.",
"Brown ale.",
"Red ale.",
"White ale.",
"Wheat ale.",
"Pilsner.",
"Lager.",
"Chocolate stout.",
"Coffee stout.",
"Black porter.",
"Brown porter.",   ]},
{"title": "d12 ...that is just a bit...", "id":"d12dwthatisjustabit", "roll":[
"Too dark in color.",
"Too light in color.",
"Too strong in flavor.",
"Too mild in flavor.",
"Too foamy.",
"Too fizzy.",
"Too flat.",
"Too bitter.",
"On the nutty side.",
"On the floral side.",
"On the sweet side.",
"Chewy.",   ]},



 {"title": "d10 Tonight, at a dockside tavern, we dine on...", "id":"d10tonightatadocksidetavernwedineon", "roll":[
"Stewed.",
"Breaded.",
"Fried.",
"Battered.",
"Baked.",
"Brined.",
"Seared.",
"Peppered.",
"Salted.",
"Pickled.",   ]},
 {"title": "d20 ...", "id":"d20dock", "roll":[
"Clams.",
"Crab.",
"Herring.",
"Lobster.",
"Mussels.",
"Oysters.",
"Salmon.",
"Smelt.",
"Haddock.",
"Mackerel.",
"Squid.",
"Shrimp.",
"Prawns.",
"Tuna.",
"Halibut.",
"Cod.",
"Sea bass.",
"Goose.",
"Chicken.",
"Mutton.",   ]},
 {"title": "d10 ...with...", "id":"d10dockwith", "roll":[
"Golden potatoes.",
"Red potatoes.",
"Beets.",
"Leeks.",
"Lentils.",
"Red beans.",
"Black beans.",
"Turnip mash.",
"Diced turnips.",
"Wild rice.",   ]},
 {"title": "d12 ...and...", "id":"d12dockand", "roll":[
"Carrots.",
"Red cabbage.",
"Green cabbage.",
"Purple cabbage.",
"Dill weed.",
"Lemongrass.",
"Lemon wedges.",
"Parsley.",
"Radishes.",
"Peas.",
"Green onions.",
"Yellow onions.",   ]},
 {"title": "d8 On the side, there is some...", "id":"d8onthesidethereissome", "roll":[
"Sourdough bread.",
"Fresh bread.",
"Crusty bread.",
"Sweet bread.",
"Sesame bread.",
"Oat bread.",
"Pumpernickel bread.",
"Beer bread.",   ]},
 {"title": "d10 To wash it down, we have some...", "id":"d10docktowashitdownwehavesome", "roll":[
"Bitter ale.",
"Wheat ale.",
"Steam beer.",
"Porter.",
"Mead.",
"Sour wine.",
"Red wine.",
"Tea.",
"Spiced rum.",
"Dry rum.",   ]},



{"title": "d10 Tonight, at a country inn, we dine on...", "id":"d10tonightatacountryinnwedineon", "roll":[
"Stewed.",
"Roasted.",
"Fried.",
"Boiled.",
"Baked.",
"Grilled.",
"Seared.",
"Steamed.",
"Salted.",
"Pickled.",   ]},
{"title": "d12 ...", "id":"d12ci", "roll":[
"Rabbit.",
"Chicken.",
"Duck.",
"Mutton.",
"Pork.",
"Beef.",
"Pheasant.",
"Goose.",
"Trout.",
"Clams.",
"Pork sausage.",
"Duck sausage.",   ]},
{"title": "d20 ...with...", "id":"d20withci", "roll":[
"Dumplings.",
"Red cabbage.",
"White cabbage.",
"Shredded cabbage.",
"Leeks.",
"Lentils.",
"Broccoli.",
"Peas.",
"Cauliflower.",
"Kidney beans.",
"String beans.",
"White beans.",
"Turnip mash.",
"Sliced turnips.",
"Asparagus.",
"Sprouts.",
"Sweet peppers.",
"Red potatoes.",
"Golden potatoes.",
"Yams.",   ]},
{"title": "d12 ...and...", "id":"d12andci", "roll":[
"Carrots.",
"Apples.",
"Cherries.",
"Tomatoes.",
"Blueberries.",
"Strawberries.",
"Beets.",
"Mushrooms.",
"Radishes.",
"Squash.",
"Sweet onions.",
"Red onions.",   ]},
{"title": "d12 On the side, there is some...", "id":"d12onthesidethereissomeci", "roll":[
"Corn bread.",
"Corn mash.",
"Fresh bread.",
"Crusty bread.",
"Sesame bread.",
"Oat bread.",
"Pumpernickel bread.",
"Pretzel bread.",
"Fried egg.",
"Bacon.",
"Sharp cheese.",
"Soft cheese.",   ]},
{"title": "d10 To wash it down, we have some...", "id":"d10towashitdownwehavesomeci", "roll":[
"Water.",
"Wheat ale.",
"Porter.",
"Mead.",
"White wine.",
"Red wine.",
"Sweet wine.",
"Milk.",
"Coffee.",
"Brandy.",   ]},


 {"title": "d10 Tonight, around the campfire, we dine on...", "id":"d10tonightaroundthecampfirewedineon", "roll":[
"Stewed.",
"Roasted.",
"Skewered.",
"Boiled.",
"Smoked.",
"Grilled.",
"Seared.",
"Flame-broiled.",
"Salted.",
"Peppered.",   ]},
 {"title": "d10 ...", "id":"d10cf", "roll":[
"Rabbit.",
"Duck.",
"Pork.",
"Fish.",
"Venison.",
"Deer.",
"Squirrel.",
"Pheasant.",
"Mutton.",
"Lamb.",   ]},
 {"title": "d8 ...with...", "id":"d8cfwith", "roll":[
"Potatoes.",
"Lentils.",
"White beans.",
"Red beans.",
"Black beans.",
"Peas.",
"Turnips.",
"Onions.",   ]},
 {"title": "d12 ...and...", "id":"d12cfand", "roll":[
"Carrots.",
"Raisins.",
"Dried cherries.",
"Wild mushrooms.",
"Sliced mushrooms.",
"Rosemary.",
"Pine nuts.",
"Cashews.",
"Almonds.",
"Olives.",
"Dried berries.",
"Sunflower seeds.",   ]},
 {"title": "d6 On the side, there is some...", "id":"d6cfonthesidethereissome", "roll":[
"Rye bread.",
"Hard tack.",
"Crusty bread.",
"Sesame bread.",
"Hard cheese.",
"Sharp cheese.",   ]},
 {"title": "d6 To wash it down, we have some...", "id":"d6cftowashitdownwehavesome", "roll":[
"Water.",
"Watery ale.",
"Strong ale.",
"White wine",
"Red wine.",
"Tea.",   ]},


 {"title": "d12 This morning, at a traveler's inn, we break our fast on...", "id":"d12thismorningatatravelersinnwebreakourfaston", "roll":[
"Scrambled eggs.",
"Fried eggs.",
"Boiled eggs.",
"Poached eggs.",
"Smoked ham.",
"Honey ham.",
"Hard cheese.",
"Soft cheese.",
"Hot porridge.",
"Cold porridge.",
"Thin porridge.",
"Warm gruel.",   ]},
 {"title": "d10 ...with...", "id":"d10tiwith", "roll":[
"Soggy bacon.",
"Chewy bacon.",
"Crispy bacon.",
"Thick-cut bacon.",
"Sweet sausage.",
"Mild sausage.",
"Spicy sausage.",
"Hot sausage.",
"Sour yogurt.",
"Sweetened yogurt.",   ]},
 {"title": "d8 ...and...", "id":"d8tiand", "roll":[
"Fried potatoes.",
"Boiled potatoes.",
"Tomatoes.",
"Mushrooms.",
"Sweet peppers.",
"Spinach.",
"Sweet onions.",
"Red onions.",   ]},
 {"title": "d12 On the side, there is some...", "id":"d12tionthesidethereissome", "roll":[
"Corn bread.",
"Corn mash.",
"Fresh bread.",
"Crusty bread.",
"Dry toast.",
"Buttered toast.",
"Pumpernickel bread.",
"Pretzel bread.",
"Fried egg.",
"Extra bacon.",
"Sharp cheese.",
"Pungent cheese.",   ]},
 {"title": "d6 ...and there are some...", "id":"d6tiandtherearesome", "roll":[
"Apples.",
"Cherries.",
"Blueberries.",
"Strawberries.",
"Pears.",
"Blackberries.",   ]},
 {"title": "d10 To wash it down, we have some...", "id":"d10titowashitdownwehavesome", "roll":[
"Water.",
"Brown ale.",
"Red ale.",
"Porter.",
"Stout.",
"Spiced wine.",
"Red wine.",
"Milk.",
"Coffee.",
"Tea.",   ]},


 {"title": "d12 This morning, at a city cafe, we break our fast on...", "id":"d12thismorningatacitycafewebreakourfaston", "roll":[
"Scrambled eggs.",
"Fried eggs.",
"Boiled eggs.",
"Poached eggs.",
"Hard cheese.",
"Soft cheese.",
"A cinnamon roll.",
"A sticky bun.",
"A sweet roll.",
"A croissant.",
"A chocolate croissant.",
"An almond croissant.",   ]},
 {"title": "d6 ...with...", "id":"d6withcc", "roll":[
"Crispy bacon.",
"Thick-cut bacon.",
"Mild sausage.",
"Spicy sausage.",
"Sour yogurt.",
"Sweetened yogurt.",   ]},
 {"title": "d6 ...and...", "id":"d6andcc", "roll":[
"Tomatoes.",
"Mushrooms.",
"Sweet peppers.",
"Spinach.",
"Green onions.",
"Red onions.",   ]},
 {"title": "d6 On the side, there is some...", "id":"d6onthesidethereissomecc", "roll":[
"Fresh bread.",
"Buttered toast.",
"Pumpernickel bread.",
"Pretzel bread.",
"Sharp cheese.",
"Pungent cheese.",   ]},
 {"title": "d6 ...and there are some...", "id":"d6andtherearesomecc", "roll":[
"Apples.",
"Cherries.",
"Blueberries.",
"Strawberries.",
"Pears.",
"Blackberries.",   ]},
 {"title": "d8 To wash it down, we have some...", "id":"d8towashitdownwehavesomecc", "roll":[
"Water.",
"Brown ale.",
"Red ale.",
"Porter.",
"Stout.",
"Spiced wine.",
"Orange juice.",
"Apple juice.",   ]},
 {"title": "d6 ...and a cup of...", "id":"d6andacupofcc", "roll":[
"Green tea.",
"Black tea.",
"Light-roasted coffee.",
"Dark-roasted coffee.",
"Strong coffee.",
"Weak coffee.",   ]},
 {"title": "d8 ...with...", "id":"d8withcc", "roll":[
"Milk.",
"Sugar.",
"Cream.",
"Milk and sugar.",
"Cream and sugar.",
"Honey.",
"Cinnamon.",
"Nothing added.",   ]},


{"title": "d6 Varieties This dish is...", "id":"d6varietiesthisdishis", "roll":[
"Exotic / Unusual (roll again and choose something outlandish/rare).",
"Fruits.",
"Meats.",
"Savories: These include cheese, nuts and seeds.",
"Seafood: This includes shellfish and ocean plants.",
"Vegetables.",   ]},
{"title": "d4 Flavor This dish is...", "id":"d4flavorthisdishis", "roll":[
"Sweet.",
"Spicy.",
"Sour.",
"Savory.",   ]},
{"title": "d10 Preparation This dish is...", "id":"d10preparationthisdishis", "roll":[
"Baked.",
"Boiled.",
"Broiled.",
"Fried.",
"Grilled.",
"Poached.",
"Roasted.",
"Sauteed.",
"Seared.",
"Steamed.",   ]},
{"title": "d4 Presentation This dish is served on or with...", "id":"d4presentationthisdishisservedonorwith", "roll":[
"Bread.",
"Leaf/Skewer.",
"Pastry.",
"Rice.",   ]},
{"title": "d8 Beverages Enjoy this dish with...", "id":"d8beveragesenjoythisdishwith", "roll":[
"Cider.",
"Juice.",
"Mead.",
"Milk / Kefir.",
"Tea / Coffee / Chocolate.",
"Wine.",
"Beer.",
"Spirits / Cocktails.",   ]},
{"title": "d6 Sweet flavors The dish is flavored with...", "id":"d6sweetflavorsthedishisflavoredwith", "roll":[
"Sugar.",
"Molasses.",
"Honey.",
"Glaze (roll on fruits table).",
"Jam (roll on fruits table).",
"Pixie parts.",   ]},
{"title": "d12 Spicy flavors The dish is flavored with...", "id":"d12spicyflavorsthedishisflavoredwith", "roll":[
"Curry.",
"Cumin.",
"Black pepper.",
"Red pepper.",
"Chili powder.",
"Cinnamon.",
"Green chili pepper.",
"Ghost chili pepper.",
"Paprika.",
"Sriracha.",
"Red dragon oil.",
"Flecks of salamander.",   ]},
{"title": "d4 Sour flavors The dish is flavored with...", "id":"d4sourflavorsthedishisflavoredwith", "roll":[
"Yogurt.",
"Sour cream.",
"Sour fruit juice (roll d6 on fruits table).",
"Vinegar (d4): 1. white wine 2. red wine 3. fruits 4. digester juice",   ]},
{"title": "d20 Fruits The dish is made with...", "id":"d20fruitsthedishismadewith", "roll":[
"Lemon.",
"Lime.",
"Grapes.",
"Apple.",
"Orange.",
"Cherry.",
"Pear.",
"Plum.",
"Peach.",
"Mango.",
"Coconut.",
"Banana.",
"Papaya.",
"Blueberries.",
"Raspberries.",
"Blackberries.",
"Watermelon.",
"Cantaloupe.",
"Honeydew.",
"Dryad melons.",   ]},
{"title": "d20 Vegetables The dish is made with...", "id":"d20vegetablesthedishismadewith", "roll":[
"Asparagus.",
"Arugula.",
"Broccoli.",
"Carrots.",
"Cucumber.",
"Cauliflower.",
"Beans (d4): 1. black; 2. red; 3. string; 4. white.",
"Peppers (d4): 1. bell; 2. chili; 3. hot; 4. sweet.",
"Onion (d4): 1. green; 2. red; 3. sweet; 4. yellow.",
"Corn.",
"Parsnips.",
"Cabbage (d4): 1. green; 2. red; 3. purple; 4. white.",
"Turnips.",
"Radishes.",
"Beets.",
"Peas.",
"Spinach.",
"Sprouts.",
"Lettuce (d4): 1. butter; 2. iceberg; 3. romaine; 4. weedy.",
"Squash (d4): 1. butternut; 2. pumpkin; 3. summer; 4. zucchini.",   ]},
{"title": "d20 Savories The dish is made with...", "id":"d20savoriesthedishismadewith", "roll":[
"White cheese.",
"Sharp cheese.",
"Mild cheese.",
"Stinky cheese.",
"Pungent cheese.",
"Blue cheese.",
"Yellow cheese.",
"Goat cheese.",
"Sheep's milk cheese.",
"Sunflower seeds.",
"Pumpkin seeds.",
"Poppy seeds.",
"Soybeans.",
"Pine nuts.",
"Almonds.",
"Pecans.",
"Hickory nuts.",
"Peanuts.",
"Pistachios.",
"Walnuts.",   ]},
{"title": "d20 Common seafood The dish is made with...", "id":"d20commonseafoodthedishismadewith", "roll":[
"Clams.",
"Crab.",
"Herring.",
"Lobster.",
"Mussels.",
"Oysters.",
"Salmon.",
"Smelt.",
"Haddock.",
"Mackerel.",
"Squid.",
"Shrimp.",
"Prawns.",
"Tuna.",
"Halibut.",
"Cod.",
"Sardines.",
"Anchovies.",
"Scallops.",
"Sea bass.",   ]},
{"title": "d20 Unusual seafood Unusual but tasty, the dish is made with...", "id":"d20unusualseafoodunusualbuttastythedishismadewith", "roll":[
"Skate.",
"Cuttlefish.",
"Flounder.",
"Grouper.",
"Marlin.",
"Snapper.",
"Monkfish.",
"Shark.",
"Swordfish.",
"Electric eel.",
"Dolphin.",
"Whale.",
"Seal.",
"Walrus.",
"Sea cucumber.",
"Starfish.",
"Jellyfish.",
"Kraken suckers.",
"Mermaid fin.",
"Aberrant tentacles.",   ]},
{"title": "d20 Common meats The dish is made with...", "id":"d20commonmeatsthedishismadewith", "roll":[
"Beef.",
"Pork.",
"Mutton.",
"Chicken.",
"Turkey.",
"Duck.",
"Goose.",
"Venison.",
"Horse.",
"Ox.",
"Lamb.",
"Veal.",
"Pheasant.",
"Quail.",
"Rabbit.",
"Boar.",
"Goat.",
"Pigeon.",
"Sausage (roll 1d12 to determine base meat)",
"Roll twice and combine the meats",   ]},
{"title": "d20 Uncommon meats Unusual but tasty, the dish is made with...", "id":"d20uncommonmeatsunusualbuttastythedishismadewith", "roll":[
"Squirrel.",
"Gopher.",
"Cat.",
"Dog.",
"Bear.",
"Wolf.",
"Crocodile.",
"Lizard.",
"Snake.",
"Rat.",
"Panther.",
"Beaver.",
"Bat.",
"Beetles.",
"Crickets.",
"Maggots.",
"Frog.",
"Turtle.",
"Lion.",
"Antelope.",   ]},
{"title": "d20 Weird meats Surprisingly tasty, the dish is made with...", "id":"d20weirdmeatssurprisinglytastythedishismadewith", "roll":[
"Giant spider.",
"Ghoulflesh.",
"Rump of the satyr.",
"Centipede.",
"Medusa hair.",
"Manticore.",
"Dragonflesh (not usually from a real dragon, but a wyvern or drake).",
"Displacer beast.",
"Hellhound.",
"Aberrant eyes.",
"Gelatinous cube.",
"Halfling",
"Tarrasque testicles.",
"Devil's tongue.",
"Demon lips.",
"Otyugh feet.",
"Stirge wings.",
"Owlbear (the cheek is the best, the best places serve it plated with the beak intact).",
"Umber hulk.",
"Virgin priestess.",   ]},
{"title": "d12 Bread The bread portion of the dish is...", "id":"d12breadthebreadportionofthedishis", "roll":[
"Sourdough baguette.",
"Whole-grain baguette.",
"Bread bowl.",
"Crusty roll.",
"Soft roll.",
"Pumpernickel roll.",
"Sesame seed bun.",
"Tortilla.",
"Pita.",
"Flat bread.",
"Mini pizza.",
"Hot pocket.",   ]},


 {"title": "d10 This wine was made in...", "id":"d10thiswinewasmadein", "roll":[
"A traditional coastal region known for its wines.",
"A mild, mountain valley known for its wines.",
"A region with a growing community of winemakers.",
"A foreign land that has been making wines for centuries.",
"A region where settlers have begun making wine as their ancestors had.",
"A secluded monastery.",
"A chain of islands far across the sea.",
"The basement of a little country inn.",
"The basement of a little country chapel or shrine.",
"The household of an elvish lord.",   ]},
 {"title": "d10 The wine is...", "id":"d10thewineis", "roll":[
"A pale white.",
"A bubbly white.",
"A goldish white.",
"A pale rosé.",
"A rich rosé.",
"A delicate red.",
"A thick red.",
"A deep red.",
"A robust red.",
"A reddish purple.",   ]},
 {"title": "d20 The wine smells of...", "id":"d20thewinesmellsof", "roll":[
"Springtime breezes.",
"Wildflowers.",
"Honey.",
"Roses.",
"Cherry blossoms.",
"Lilacs.",
"Lilies.",
"Wildflowers.",
"Morning dew.",
"Rain-covered flower petals.",
"Orange blossoms.",
"Young grapes.",
"Ripe grapes.",
"Cherries.",
"Tangerines.",
"Apple blossoms.",
"Ripe grapes.",
"Lemongrass.",
"Peach blossoms.",
"Hydrangeas.",   ]},
 {"title": "d20 The wine's flavor has notes of...", "id":"d20thewinesflavorhasnotesof", "roll":[
"Apple.",
"Blueberry.",
"Butter.",
"Citrus.",
"Cherry.",
"Chocolate.",
"Cloves.",
"Ginger.",
"Lemon.",
"Oak.",
"Peach.",
"Pear.",
"Pepper.",
"Pine.",
"Plum.",
"Raspberry.",
"Spices.",
"Smokiness.",
"Strawberry.",
"Tangerine.",   ]},
 {"title": "d10 The wine is served in...", "id":"d10thewineisservedin", "roll":[
"A glass goblet.",
"A glass flute.",
"A glass mug.",
"A glass cup.",
"A tin cup.",
"A brass goblet.",
"A steel mug.",
"A gilded flute.",
"A silver goblet.",
"A bucket.",   ]},
 {"title": "d10 The wine is best when enjoyed...", "id":"d10thewineisbestwhenenjoyed", "roll":[
"Iced.",
"Chilled.",
"Cold.",
"After it has had a few minutes to breathe.",
"After it has had a few hours to breathe.",
"Lightly spiced.",
"Warmed.",
"Hot.",
"Honeyed.",
"Heavily spiced and boiled.",   ]},
 {"title": "d10 The wine makes a great pairing with...", "id":"d10thewinemakesagreatpairingwith", "roll":[
"Oysters or fish.",
"Lobster or crab.",
"Chicken or turkey.",
"Pork chops or bacon.",
"Steak or veal.",
"Mutton or lamb.",
"Sausage.",
"A soft cheese.",
"A hard cheese.",
"A stinky cheese.",   ]},
 {"title": "d10 There is a tale that this type of wine was...", "id":"d10thereisatalethatthistypeofwinewas", "roll":[
"A gift from a god or goddess to an ancient people.",
"Drunk at a famed wedding feast.",
"Drunk at the funeral of a legendary king or queen.",
"Consumed by a legendary warrior before slaying a dragon.",
"Consumed by a legendary priest or priestess prior to making a dark prophecy.",
"Consumed by a legendary witch or wizard before he or she mysteriously disappeared.",
"Consumed by a legendary thief before stealing a celebrated gem.",
"Consumed by a legendary knight before leading a host to victory against impossible odds.",
"Consumed by a famous pair of lovers as they poisoned themselves.",
"First produced by a now-extinct, ancient race or clan.",   ]},


// end of food

];
