top.blades = [
    {
        title: "(Planescape) The Client and/or the Mark",
        id: "sigil_client_mark",
        roll: [
            "Academic / scholar",
            "Advocate / judge",
            "Alchemist / doctor",
            "Artificer / inventor",
            "Bureaucrat",
            "Child / lightchild or parent",
            "Clergy / cultist",
            "Clerk / scribe",
            "Collector",
            "Crime boss / gang leader",
            "Criminal / grifter",
            "Dealer / supplier / fence",
            "Entertainer / artist",
            "Exemplar or proxy",
            "Faction high-up",
            "Factol or visiting dignitary",
            "Factotum",
            "Financier / proprietor",
            "Harmonium patrolfolk",
            "Laborer / tradesfolk",
            "Harmonium officer",
            "Mercenary / thug",
            "Newly arrived Clueless",
            "Merchant / trader",
            "Sect high-up",
            "Sect member",
            "Spy / informant",
            "Tout / courier / guide",
        ],
    },
    {
        title: "The Client's Problem",
        id: "client_problem",
        roll: [
            "Cursed",
            "Extorted",
            "Framed",
            "Geas",
            "Imprisoned",
            "Injured",
            "Killed",
            "Lost artifact",
            "Lost heirloom",
            "Lost kip",
            "Lost magic item or treasure",
            "Lost memory",
            "Lost money",
            "Lost reputation",
            "Magically bound to something/somewhere bad",
            "Missing loved one",
            "Mistaken identity",
            "Shut out from somewhere/something",
            "Threatened",
        ],
    },
    {
        title: "(Planescape) The pressure is...",
        id: "sigil_pressure",
        roll: [
            "City Courts can't help",
            "City Courts won't help",
            "Fear of reprisals",
            "Harmonium bought off",
            "Harmonium refuses to help",
            "It's personal",
            "No one else believes the Client",
            "No solid proof",
            "Running out of money",
            "Running out of time",
            "The Client knows one of the Crew",
            "The Mark knows one of the Crew",
            "Someone else has a related score",
            "Someone of power will get involved soon -->blades/sigil_client_mark",
            "Roll on The Twist and make it a known quantity during the Score -->blades/sigil_twist",
        ],
    },
    {
        title: "The Mark’s Angle (What’s known)",
        id: "mark_known",
        roll: [
            "Amoral",
            "Entitled",
            "Evil",
            "Greedy",
            "Hard-nosed",
            "It's best for all involved",
            "It's just business",
            "Self-righteous",
            "Visionary",
            "Roll on The Mark’s Weakness -->blades/mark_weakness",
            "Roll on The Mark’s Vulnerability -->blades/mark_vulnerability",
        ],
    },
    {
        title: "The Mark’s Power (What you know or find out)",
        id: "mark_power",
        roll: [
            "Attractive",
            "Connected",
            "Contingency magic",
            "Divine favor",
            "Font of power",
            "Immunity",
            "Magic artifact",
            "Powerful",
            "Scary",
            "Smart",
            "Sociopath",
            "Special nature* (Such as a lich who cannot be destroyed without destroying their phylactery; a spirit naga that can only be destroyed via the wish spell; etc.)",
            "Spellcaster",
            "Tough",
            "Wealthy",
        ],
    },
    {
        title: "The Mark’s Weakness",
        id: "mark_weakness",
        roll: [
            "Addiction",
            "Arrogant",
            "Fearful",
            "Guilty conscience",
            "Loyal",
            "Needy",
            "Obsessed",
            "Phony",
            "Supernatural need*",
            "Supernatural restriction**",
            "Tyrannical",
            
        ],
    },
    {
        title: "The Mark’s Vulnerability",
        id: "mark_vulnerability",
        roll: [
            "Criminal",
            "Debt",
            "Enemies",
            "Family",
            "Love",
            "Reputation",
            "Secret dream",
            "Superiors",
            "Supernatural vulnerability*",
            "Time",
            "Someone else of importance -->blades/sigil_client_mark",
            
        ],
    },
    {
        title: "(Planescape) The Twist",
        id: "sigil_twist",
        roll: [
            "A criminal faction's already watching",
            "Close relation of a Crew members is helping the Mark",
            "Close relation of the Client is helping the Mark",
            "Death or disappearance of the Mark",
            "It's much worse than you think...",
            "It's personal",
            "Secret vulnerability",
            "Significant collateral damage",
            "The Client is the Mark!",
            "The Client will silence the Crew afterwards",
            "The Harmonium are already watching",
            "The Mark already has a way out",
            "The Mark is actually a mole with protection",
            "The Mark is terrified of someone/something else",
            "The Mark offers a deal",
            "The Mark's not really the bad guy",
            "Turnabout",
            "Unexpected hostage(s)",
            "Unforeseen innocent bystander",
            "The job puts the Crew on the radar of a formerly neutral/uninvolved faction",
            "An occultist has foreseen this job and warned the parties involved",
            "Someone’s a doppelganger!",
            "A rogue spirit/elemental/fiend is on the scene",
            "The job is a trap laid by one of your rival factions",
            "The job furthers the goals of a neutral or rival faction",
            "The job requires travel to another Plane",
            "The job furthers the goals of an allied faction",
            "The job puts the Crew at odds with one of their allied factions",
            "The job furthers or interferes with the agenda of Sigil’s major 15 Factions",
            
        ],
    },
    {
        title: "Who Else is in Play",
        id: "who_else",
        roll: [
            "Dupe",
            "Enforcer",
            "Hostage(s)",
            "Innocent",
            "Inspector",
            "Loose end",
            "Vizier",
            "Wildcard",
            "Toady",
            "Incompetent goons",
            "Turncoat",
            "Lieutenant",
            "Hidden power* (powerful creature that exerts influence over the Mark (or even the Client), such as a dominating vampire, a hag that holds a bargain over a key NPC, a mind flayer or other psionic creature, and so on)",
            "The doppelganger",
            "Usurper",
        ],
    },
    {
        title: "(Planescape) Minor Complication",
        id: "score_complications_minor",
        roll: [
            "Roll on The Twist -->blades/sigil_twist", 
            "Evidence left behind (+1 Heat)", 
            "Reinforcements arrive!", 
            "Tick a clock for an existing obstacle (minor 1 tick; standard 2 ticks)", 
            "Create a new clock representing a new obstacle (optionally: minor - fill in 1 tick; standard - fill in 2 ticks)", 
            "There’s magic afoot", 
            "The guardians are supernaturally enhanced", 
            "Ammo running low", 
            "Time’s a-ticking", 
            "Gotta grease some palms", 
            "Now you’re being watched", 
            "Traps", 
        ]
    },
    {
        title: "(Planescape) Major Complications",
        id: "score_complications_major",
        roll: [
            "Make it a big deal",
            "+2 Heat",
            "You’re surrounded!",
            "Fill in 3 ticks",
            "Create the new clock and fill in 3 ticks",
            "There’s a magical barrier or alarm",
            "The guardians are supernatural creatures themselves!",
            "Your out of ammo/your ammo is compromised",
            "Time’s running out!",
            "Either a big payout or a future favor",
            "Your source, client, contact, or purveyor has leaked",
            "Deadly traps",
        ]
    },
    {
        title: "Minor Location Complications",
        id: "location_complications_minor",
        roll: [
            "Witnesses on the scene (+1 Heat)",
            "The target evades you; now it’s a chase!",
            "A fire breaks out!",
            "Poor lighting/the lights go on (whichever is worse for you)",
            "You get tripped up",
            "Your path is obstructed",
            "Passersby slow you down",
            "You make more noise than you planned",
            "You trigger a snare or obstructing trap",
            "Oops! You fall down.",
            "Your separated from the Crew temporarily",
            "Roll on Who Else is in Play -->blades/who_else",
        ]
    },
    {
        title: "Major Location Complications",
        id: "location_complications_major",
        roll: [
            "+2 Heat",
            "They escape out of sight",
            "It’s a conflagration!",
            "The lights go out!",
            "You end up on your ass",
            "The path is blocked",
            "Passersby get entangled with you",
            "You set off the alarm",
            "You trigger a swinging blade, poisoned needle, or deadly trap",
            "Oh shit! This fall is going to HURT",
            "You are stuck!",
            "Make them a big deal",
            
        ]
    },
    {
        title: "Minor Personal Complications",
        id: "personal_complications_minor",
        roll: [
            "Disarmed!",
            "Lose status with a faction",
            "Your concentration is shaken",
            "You fumble the thing",
            "Somebody tries to get involved, to your detriment",
            "Mildly poisoned, drunk, intoxicated, or exhausted",
            "Twinges of your vice",
            "Misinterpreted intent",
            "Your mood or the target’s shifts for the worse",
            "You look suspicious",
        ]
    },
    {
        title: "Major Personal Complications",
        id: "personal_complications_major",
        roll: [
            "Weapon, armor, or tool broken!",
            "Lose status with a faction or two",
            "One of your senses is damaged",
            "You break the thing",
            "Someone unexpectedly tries to be the hero and mucks things up bad",
            "Major intoxication, drugged, or Harm",
            "Your contacts or vice purveyor is put under suspicion",
            "“No, no! You got the wrong guy!”",
            "Somebody’s gonna hold a grudge",
            "They know exactly who and what you are!",
        ]
    }
]