// achievements.js
//
// Achievement Unlocked: a sardonic award for something the party did, with a
// prize attached.
//
// The category is picked from nine tables, so the kind of joke changes per
// roll. Each entry is a complete achievement rather than composed halves,
// because comedy needs specificity. Four facets always follow, then the prize,
// which is itself a pick between eight payout shapes, so a legendary
// achievement can still pay out in novelty socks. Nine tangents are
// chance-gated on top of that, from a 60% audience reaction down to a 6%
// first-ever ceremony.
//
// House style: the humour is bureaucratic indifference, not gore. Keep it dry.

top.achievements = [
  /* ------------------------------------------------------------------
   * Categories: one of these nine is picked per roll
   * ---------------------------------------------------------------- */
  {
    title: "d16 Achievement, combat",
    id: "d16combat_achievements",
    roll: [
      "OVERKILL: Reduced a threat to a fine mist. The threat was already surrendering.",
      "TACTICAL WITHDRAWAL: Ran away first, fastest, and with the map.",
      "WRONG TOOL: Killed something with an implement designed for baking.",
      "PACIFIST RUN (VOIDED): Made it eleven minutes.",
      "COUNTERPOINT: Won an argument by ending the other participant.",
      "FIRST BLOOD (YOURS): Injured yourself before the fight began.",
      "GROUP PROJECT: Contributed nothing to a victory and claimed all of it.",
      "DEFENSIVE POSTURE: Blocked a blow with a body part not rated for blocking.",
      "ONE HIT WONDER: Ended a fight in one strike, then explained it for an hour.",
      "CROWD CONTROL: Made a room of hostiles stop fighting, out of secondhand embarrassment.",
      "STRUCTURAL SOLUTION: Resolved an encounter by removing the floor.",
      "CLOSE ENOUGH: Missed everything you aimed at and hit something better.",
      "REMATCH DENIED: Defeated an enemy so thoroughly it filed a complaint.",
      "SHIELD OPTIONAL: Went a whole fight holding your shield the wrong way round.",
      "LAST WORD: Delivered a line so poor the enemy paused. That pause was fatal.",
      "PROPORTIONATE RESPONSE: Escalated a disagreement about a chair into a siege.",
    ],
  },
  {
    title: "d16 Achievement, self-inflicted",
    id: "d16selfinflicted_achievements",
    roll: [
      "STRUCTURAL ENGINEER: Discovered that load-bearing was a suggestion. It was not.",
      "TASTE TESTER: Drank an unlabelled liquid on a dare from yourself.",
      "PERCUSSIVE MAINTENANCE: Fixed a mechanism by hitting it. Broke a different one.",
      "GRAVITY CHECK: Confirmed it still works, at length, in front of witnesses.",
      "CURIOSITY: Pressed the button. The button was clearly marked.",
      "SPEEDRUN: Reached the bottom of a staircase in record time and no control.",
      "TRAP APPRECIATION: Triggered the same trap twice, deliberately, to be sure.",
      "SELF SERVICE: Picked a lock that was on your side of the door.",
      "FLAMMABLE: Learned which of your possessions were, all at once.",
      "DEPTH PERCEPTION: Stepped confidently into a hole you had already mapped.",
      "HANDS ON: Touched the glowing thing. Everyone told you. Everyone.",
      "READ THE ROOM (FAILED): Told a joke at a funeral. Twice.",
      "OWN GOAL: Set off your own alarm during your own burglary.",
      "REDUNDANCY: Carried three of something useless and none of the antidote.",
      "LESSON LEARNED (PENDING): Repeated the exact mistake within the hour.",
      "IMPROVISED CLIMBING: Trusted a knot you tied yourself. Briefly.",
    ],
  },
  {
    title: "d14 Achievement, social",
    id: "d14social_achievements",
    roll: [
      "DIPLOMATIC IMMUNITY (REVOKED): Insulted a monarch in their own language, badly.",
      "NETWORKING: Made an enemy of someone who did not know you existed this morning.",
      "CROWD PLEASER: Cleared a tavern in under a minute without violence.",
      "HONEST BROKER: Told the truth at the worst possible moment and were believed.",
      "PUBLIC SPEAKING: Addressed a crowd. The crowd left. You continued.",
      "REFERENCES AVAILABLE: Were vouched for by someone currently imprisoned.",
      "SMALL TALK: Discussed the weather with something that controls it.",
      "MISTAKEN IDENTITY: Were arrested for a crime committed by someone you admire.",
      "PATRON OF THE ARTS: Commissioned a portrait. It is unkind and accurate.",
      "GUEST OF HONOUR: Attended a banquet held to celebrate your death.",
      "TERMS ACCEPTED: Agreed to something in a language you do not speak.",
      "MEDIATOR: Ended a dispute by giving both sides a new, shared enemy: you.",
      "REPUTATION MANAGEMENT: Spread a rumour about yourself that turned out to be true.",
      "SEATING ARRANGEMENT: Started a feud between two families over a chair.",
    ],
  },
  {
    title: "d14 Achievement, exploration",
    id: "d14exploration_achievements",
    roll: [
      "CARTOGRAPHY: Drew a map. The map is wrong. Someone is using it.",
      "FIRST FOOTPRINT: Entered a place sealed for a reason, and left the door open.",
      "SCENIC ROUTE: Took nine days to travel a distance of two.",
      "LANDMARK: Named a geographical feature after yourself, out loud, alone.",
      "SHORTCUT: Found one. It was longer. You have not admitted this.",
      "THRESHOLD: Crossed a border that appears on no map, and felt it.",
      "DEEP DIVE: Went down past the light. Came back with less than you took.",
      "ORIENTEERING: Arrived exactly where you meant to, entirely by accident.",
      "TOURIST: Visited a ruin, took a souvenir, apologised to nobody.",
      "RETURN TRIP: Went back somewhere everyone advised against. Twice.",
      "UNCHARTED: Reached a place with no name. Gave it a bad one.",
      "SUMMIT: Climbed something tall to see something disappointing.",
      "TIDE TABLE: Learned the tide's schedule the expensive way.",
      "TRESPASSING: Were somewhere so private it had no locks, only expectations.",
    ],
  },
  {
    title: "d14 Achievement, trade and craft",
    id: "d14trade_achievements",
    roll: [
      "MASTER CRAFTSMAN (DISPUTED): Made something functional on purpose, allegedly.",
      "MARKET FORCES: Sold something above its worth to someone who knew its worth.",
      "QUALITY CONTROL: Produced nine identical items. All nine failed identically.",
      "APPRAISAL: Valued a treasure correctly and were ignored.",
      "SUPPLY CHAIN: Cornered the local market in something nobody wanted.",
      "REPAIR WORK: Fixed an heirloom so well the family became suspicious.",
      "HAGGLING: Talked a price below the seller's cost. They agreed. Consider why.",
      "INVENTORY: Carried something for three months before learning what it was.",
      "SUNK COST: Spent a fortune finishing a project you had stopped believing in.",
      "COTTAGE INDUSTRY: Accidentally founded a trade that will outlive you.",
      "RECEIPTS: Kept documentation that later saved your life. Filing matters.",
      "COMMISSIONED: Built exactly what was asked for. It was the wrong request.",
      "COUNTERFEIT: Made a forgery better than the original. The original was withdrawn.",
      "LIQUIDATION: Sold everything you owned in one afternoon, for reasons.",
    ],
  },
  {
    title: "d14 Achievement, survival",
    id: "d14survival_achievements",
    roll: [
      "STILL HERE: Survived something with a survival rate expressed in decimals.",
      "RATIONS: Ate something you would not name to a friend.",
      "EXPOSURE: Spent a night outdoors that changed your opinion of indoors.",
      "FIELD MEDICINE: Treated a wound with materials from a kitchen.",
      "SECOND WIND: Kept going past the point where stopping was reasonable.",
      "SLEEP SCHEDULE: Went four days without. Made four days of decisions.",
      "SHELTER: Improvised one from materials that were, until recently, an enemy.",
      "WATER FOUND: Located drinking water by following something that also wanted it.",
      "PAIN TOLERANCE: Walked on it. It was broken. You walked on it.",
      "ESCAPE ARTIST: Left a locked room in a way the room did not survive.",
      "COLD OPEN: Woke somewhere with no memory of arriving and made it work.",
      "TRIAGE: Chose who to save. Are still choosing, nightly.",
      "LAST RATION: Gave away your final food, regretted it at once, did it anyway.",
      "BREATH CONTROL: Held it considerably longer than the situation required.",
    ],
  },
  {
    title: "d14 Achievement, animals",
    id: "d14animals_achievements",
    roll: [
      "ANIMAL HANDLING: Were handled by an animal.",
      "BEEKEEPER: Learned the hive's opinion of you. It was unanimous.",
      "GOOD DOG: Were adopted by something with too many teeth for the word pet.",
      "HORSE WHISPERER (ONE WAY): The horse does not whisper back. The horse judges.",
      "APEX PREDATOR: Were briefly considered food and talked your way out.",
      "MIGRATION: Followed birds somewhere. They knew where. You did not.",
      "NAMING RIGHTS: Named a wild animal. It now expects things.",
      "PEST CONTROL: Removed an infestation and inherited its territory.",
      "LIVESTOCK: Transported an animal that did not consent to being transported.",
      "SPECIES BARRIER: Held a conversation. Only one of you knew it was one.",
      "NESTING: Found something valuable in a nest. The nest wants it back.",
      "MOUNTED: Rode something not designed to be ridden. Once.",
      "SWARM: Were briefly the most interesting thing in a field, to everything in it.",
      "LOYALTY: Were defended by an animal you had been rude to.",
    ],
  },
  {
    title: "d14 Achievement, food and drink",
    id: "d14food_achievements",
    roll: [
      "PICKY EATER: Refused a meal offered in good faith by something with too many arms.",
      "SOMMELIER: Identified a vintage by taste. It was not wine.",
      "IRON STOMACH: Ate the whole thing. The whole thing.",
      "HOST: Cooked for a party. Three attended. Two were invited.",
      "SEASONING: Improved a dish with something found rather than bought.",
      "TAB: Ran up a bill somewhere with no coin economy. They accepted something else.",
      "BREAKFAST: Ate a proper one before a day that did not deserve it.",
      "FERMENTATION: Made alcohol by accident and drank it on purpose.",
      "TABLE MANNERS: Offended an entire culture with your elbows.",
      "LAST SUPPER (PREMATURE): Ate the emergency provisions on day one.",
      "SHARED PLATE: Ate from a communal pot with someone trying to kill you. Both survived.",
      "RECIPE: Reproduced a dish from memory for someone who missed home.",
      "GARNISH: Were served something still moving and complimented the presentation.",
      "SOBRIETY: Stayed sober at an event where that was the strange choice.",
    ],
  },
  {
    title: "d16 Achievement, unclassifiable",
    id: "d16unclassifiable_achievements",
    roll: [
      "PAPERWORK: Completed a form correctly on the first attempt. Somewhere, a clerk wept.",
      "COINCIDENCE: Right place, right time, fourth time running. This is now a pattern.",
      "WITNESS: Saw something with no explanation and did not mention it. Wise.",
      "PUNCTUALITY: Arrived on time to an appointment nobody else survived to keep.",
      "SPARE KEY: Kept something useless for years until the one day it mattered.",
      "UNDERSTUDY: Were mistaken for someone important and did the job better.",
      "ARCHIVE: Read the entire boring document. It contained the answer.",
      "SYMMETRY: Did the same thing twice, years apart, in one spot, for opposite reasons.",
      "ROUNDING ERROR: Survived on a technicality a scholar is still arguing about.",
      "UNPROMPTED: Apologised to someone who never knew you had wronged them.",
      "PATIENCE: Waited. That was the whole solution. You waited.",
      "SIDE QUEST: Helped a stranger with something small. It mattered more than the errand.",
      "INHERITANCE: Received something from a will you had no business being in.",
      "LOOSE THREAD: Left something unfinished that will return in exactly one year.",
      "NO NOTES: Executed a plan exactly as written. Nobody believes you.",
      "OFF SCRIPT: Did the one thing nobody had prepared a response for.",
    ],
  },

  /* ------------------------------------------------------------------
   * The facets that always follow
   * ---------------------------------------------------------------- */
  {
    title: "d20 The committee notes",
    id: "d20commentary_achievements",
    roll: [
      "Congratulations. That was not the intended solution.",
      "Recorded for posterity, and for the entertainment of the recording department.",
      "The committee watched this happen and chose not to intervene.",
      "This was added to the list last week. You are the reason it was added.",
      "Statistically, you should not be reading this.",
      "Somewhere a scholar is updating a chart and swearing.",
      "Well done, technically.",
      "This has been filed under unforced.",
      "Several people had money on this. None of them are pleased.",
      "The rules do not forbid it. That is the strongest thing that can be said.",
      "Your file has been moved to a different, thicker drawer.",
      "A note has been added to your record. The note is one word long.",
      "This achievement was retired for being too easy. It has been reinstated.",
      "You may tell people about this. They may not react as you hope.",
      "Two separate departments claim responsibility for allowing it.",
      "There is no ceremony for this one. There was, once.",
      "Nobody asked you to. That is precisely the point.",
      "The previous holder sends their regards and their condolences.",
      "Filed under achievements that raise more questions than they answer.",
      "This is fine. Everything is proceeding as poorly as anticipated.",
    ],
  },
  {
    title: "d16 Tier",
    id: "d16tier_achievements",
    roll: [
      "Bronze. The most honest of the metals.",
      "Silver. Respectable, and quietly resented.",
      "Gold, which here means the paint is thicker.",
      "Iron. Awarded for effort rather than outcome.",
      "Wood. There is no lower tier. There was, and it was removed.",
      "Participation. Awarded regardless, and it stings.",
      "Provisional. Upgradeable if you do it again on purpose.",
      "Honorary. You did not do this. Someone decided you would have.",
      "Concerning. A tier introduced specifically for behaviour of this kind.",
      "Platinum, allegedly. Nobody has seen the metal.",
      "Unranked. The scale does not extend in this direction.",
      "Classified. Even you are not told the tier.",
      "Bronze, with a small asterisk that is doing considerable work.",
      "Legendary, in the sense that nobody believes it.",
      "Ceremonial. Comes with a certificate and no rights whatsoever.",
      "Under review. Assume gold and prepare for wood.",
    ],
  },
  {
    title: "d12 Rarity",
    id: "d12rarity_achievements",
    roll: [
      "0.03% of contestants have earned this.",
      "Earned by four people. Two posthumously.",
      "More common than anyone is comfortable with: 31%.",
      "You are the seventeenth. The first sixteen formed a society.",
      "Rarity uncalculated. Nobody thought to measure it.",
      "One in nine hundred, and the other 899 did it deliberately.",
      "Awarded eleven times this week alone. It has been a strange week.",
      "Unique so far, which is a sentence with an expiry date.",
      "0.5%, and rising sharply since you were seen doing it.",
      "Common among a demographic you will not enjoy being grouped with.",
      "Rare. Genuinely, provably rare. Enjoy this sentence.",
      "Statistically impossible, according to a scholar being difficult about it.",
    ],
  },
  {
    title: "d16 Conditions",
    id: "d16conditions_achievements",
    roll: [
      "Non-transferable. Void if you say the word obviously.",
      "Cannot be earned twice. Attempts will be logged and mocked.",
      "Rescinded if you explain it unprompted more than three times.",
      "Valid in all territories except the one where you earned it.",
      "Comes with a certificate. The certificate is not waterproof.",
      "The prize is final. The achievement is not.",
      "Subject to review by a committee that has never convened.",
      "Terms may change. You will not be notified.",
      "Not valid for wagering, though people will try.",
      "Bragging rights included. Bragging results not guaranteed.",
      "Redeemable within a year. The year started some time ago.",
      "Void where prohibited, which is more places than you would guess.",
      "Any resemblance to competence is coincidental.",
      "The prize may not be exchanged, returned, or reasoned with.",
      "One per person, one per lifetime, one per version of you.",
      "By accepting, you agree to do it again if asked nicely.",
    ],
  },

  /* ------------------------------------------------------------------
   * Prize payouts, reached through the prize gate below
   * ---------------------------------------------------------------- */
  {
    title: "d16 The prize",
    id: "d16junk_achievements",
    roll: [
      "A commemorative spoon. Not silver. Not close.",
      "Three coins from a kingdom that no longer honours them.",
      "A sack of buttons. Forty-one buttons. Someone counted.",
      "A certificate, damp.",
      "A single boot. The right one. It fits.",
      "A bag of assorted teeth, professionally cleaned.",
      "A map to somewhere you have already been.",
      "A lightly used hat with someone else's name inside it.",
      "A jar of something that was, until recently, a liquid.",
      "A key. No lock, no note, no hint.",
      "Half a chess set. The boring half.",
      "A stick. An unusually good stick, admittedly.",
      "A voucher for a service that no longer exists.",
      "A small flag on a stick, for waving. There is no occasion.",
      "Someone else's laundry, folded with real care.",
      "A rock. It is a nice rock. That is the entire prize.",
    ],
  },
  {
    title: "d16 The prize",
    id: "d16practical_achievements",
    roll: [
      "A waterskin always as full as you need, within reason, and it decides what is reasonable.",
      "Boots that never blister and never look new.",
      "A rope that unties on command and refuses to be used for hanging.",
      "A tinderbox that works when wet, sullenly.",
      "A blanket that keeps exactly one person warm, and picks.",
      "A knife that stays sharp and dulls in the presence of children.",
      "A lantern that burns for nine hours and then, firmly, does not.",
      "A satchel that will not be pickpocketed. It bites.",
      "A whetstone that improves any blade slightly and any argument enormously.",
      "A cloak that sheds rain and holds smells forever, including the good ones.",
      "A compass that points to whichever direction is safest rather than north.",
      "A purse that keeps its coins quiet.",
      "One sealed dose of medicine, which you will end up using on someone else.",
      "A folding shovel of very serious quality.",
      "Letters of introduction to nine people, six of whom are alive.",
      "A pot that never burns food, which is a small miracle and a real one.",
    ],
  },
  {
    title: "d14 The prize",
    id: "d14absurd_achievements",
    roll: [
      "A hat that makes you fluent in one language per week. It picks the language.",
      "A door knocker that, held to any wall, becomes a door. Once a week. It remembers abuse.",
      "A whistle that summons a horse. Not the same horse. Not always a horse.",
      "A bell that ends any argument within earshot for one minute exactly.",
      "A glove that makes one hand fireproof. It will not say which until tested.",
      "A ribbon that ties two people's luck together for a day. Consent is not required, and should be.",
      "A mirror that shows you asleep. Useful, once you work out why.",
      "A coin that always lands the way the flipper needs. It keeps a tally.",
      "Spectacles that reveal what a room was previously used for.",
      "A flute that makes any lie sound like a joke, defusing it.",
      "A signet that opens any door you have been genuinely invited through, from anywhere.",
      "A cup that turns poison into a strong but survivable drink.",
      "A pillow granting one night of real rest each month. It chooses the night.",
      "A pen that writes only true statements, which makes it useless for correspondence.",
    ],
  },
  {
    title: "d14 The prize",
    id: "d14cursed_achievements",
    roll: [
      "A ring of considerable power that cannot be removed while anyone is watching.",
      "A sword that is excellent and hums the same four notes forever.",
      "A purse that refills overnight with slightly less than it held.",
      "A cloak of warmth that makes its wearer unbearably honest.",
      "A helm granting perfect direction and perfect nightmares of the route.",
      "Boots that never tire and never quite stop, twitching at rest.",
      "A book holding the answer to one question. It asks a question first.",
      "A knife that never dulls and never cuts what its owner most wants cut.",
      "Something genuinely wonderful that belonged to someone who is coming for it.",
      "A brooch that makes you memorable to everyone, including those you were avoiding.",
      "A drum that summons help. Help arrives. Help expects payment.",
      "A lamp showing the truth of a room, and of its holder, aloud.",
      "A key that opens anything and locks one thing behind you forever, chosen at random.",
      "A prize with no downside at all, which is the problem, and the committee is timing how long it takes you to relax.",
    ],
  },
  {
    title: "d14 The prize",
    id: "d14consumable_achievements",
    roll: [
      "Three doses of something that heals wounds and one that does not, unlabelled.",
      "A single vial of courage. Real, chemical, temporary courage.",
      "A hot meal appearing once a day for a month, at an hour you do not choose.",
      "Two doses of an antidote to a poison you have not yet encountered.",
      "A candle that burns one hour and holds a room's occupants to the truth.",
      "Seeds that grow fast, edible, and only in bad soil.",
      "A flask that removes fatigue and returns it later, all at once, with interest.",
      "One night of dreamless sleep, transferable, in a small stoppered bottle.",
      "A powder making any water drinkable and any drink regrettable.",
      "Nine days of rations that taste of home. Your home. Nobody asked.",
      "A tonic that heals a scar and removes the memory attached to it.",
      "One use of a word that makes any animal stop, listen and consider.",
      "A salve that closes wounds and leaves the patient briefly fluent in its maker's tongue.",
      "A single match that lights anything, including things that should not be lit.",
    ],
  },
  {
    title: "d14 The prize",
    id: "d14cosmetic_achievements",
    roll: [
      "A tattoo that appears overnight, tasteful, and cannot be explained.",
      "Your eyes now catch the light. Just that. People notice.",
      "A permanent faint smell of woodsmoke and citrus. Universally well received.",
      "Your shadow now stands slightly straighter than you do.",
      "A scar rearranged into something that reads as deliberate.",
      "Hair that stays exactly as it was on your best day, forever.",
      "A voice that carries in large rooms and softens in small ones.",
      "Clothes that no longer stain, though they still wear out.",
      "A small glow at the fingertips when you are genuinely pleased.",
      "Your reflection is a half-second slower and slightly kinder.",
      "Birds land near you. Only pleasant ones. There is no benefit.",
      "A title stitched into the lining of everything you own, by nobody.",
      "A ceremonial sash of no rank whatsoever, in a colour that suits you enormously.",
      "You are now impossible to depict accurately, in any medium, including memory.",
    ],
  },
  {
    title: "d12 The prize",
    id: "d12livestock_achievements",
    roll: [
      "A goat. Papers included. The papers are for a different goat.",
      "A crow that knows nine words, three of which are your full name.",
      "A dog of no particular breed and considerable opinion.",
      "A cat that arrived with the prize and refuses to be part of it.",
      "A donkey that will not be sold, given away or abandoned. It finds its way back.",
      "A small pig with an unerring sense for buried things.",
      "A hawk on loan, with a schedule and a supervisor who checks.",
      "A tortoise older than the achievement. It has seen worse recipients.",
      "A pony faster than it looks, which knows exactly how much faster.",
      "Bees. A working hive. Yours now. Congratulations, apparently.",
      "A rat, remarkably clean, apparently trained, by whom is not disclosed.",
      "Something in a covered basket that has not moved and is definitely alive.",
    ],
  },

  /* ------------------------------------------------------------------
   * Tangent leaves
   * ---------------------------------------------------------------- */
  {
    title: "d16 The room reacts",
    id: "d16audience_achievements",
    roll: [
      "Scattered applause, and one person booing with real commitment.",
      "Silence, then a single voice asking someone to explain it.",
      "Genuine cheering, which is somehow worse.",
      "A small child is now imitating you. Their guardian is unhappy.",
      "Someone is already retelling it, incorrectly, at volume.",
      "A bard is taking notes. This will not be flattering.",
      "Two witnesses disagree about what happened and have stopped speaking.",
      "The crowd has moved on. It was, in fairness, a long day.",
      "Polite applause of the kind reserved for near misses.",
      "One person is weeping. They will not say why.",
      "A wager is being settled loudly nearby, in your favour, without your involvement.",
      "Nobody saw it. You will have to describe it forever.",
      "Someone sketched it. The sketch is unkind.",
      "An audience member has asked you to do it again. They are serious.",
      "It is being discussed in a language you do not speak, with gestures you understand.",
      "A stranger nodded at you once, slowly, and left. That is all.",
    ],
  },
  {
    title: "d14 Standing",
    id: "d14leaderboard_achievements",
    roll: [
      "You are the fourth to earn this. Two posthumously.",
      "First place, in a category of one.",
      "Ninth. The top eight are all the same person.",
      "You have displaced someone who will hear about it by evening.",
      "Currently tied. The tiebreaker is unspecified and probably physical.",
      "You have entered the top hundred. The list goes to ninety-nine.",
      "Your position is being contested by someone with better documentation.",
      "Second. First is unbeatable and has been dead a while.",
      "You are the only living holder. This is presented as good news.",
      "The board has been updated. Nobody reads the board.",
      "Ranked highly in a region you have never visited.",
      "Your name is now the answer to a trivia question in three taverns.",
      "You knocked a local hero down a place. They were gracious. Their friends were not.",
      "The rankings are alphabetical. You have been advised to change your name.",
    ],
  },
  {
    title: "d16 Sponsorship",
    id: "d16sponsor_achievements",
    roll: [
      "Sponsored by a maker of rope, who is delighted and would like a testimonial.",
      "Sponsored by a temple that would rather not be named in the same breath.",
      "Sponsored by a brewery. The prize arrives with samples.",
      "Sponsored by a family estate, as part of an ongoing feud.",
      "Sponsored by a guild of locksmiths, who are watching you now.",
      "Sponsored by a cartographer who wants the route, in detail, tonight.",
      "Sponsored by an inn that will charge you nothing and mention it constantly.",
      "Sponsored by a physician, which is being taken as a comment.",
      "Sponsored by a syndicate that has not explained itself and will not.",
      "Sponsored by an eccentric who collects people rather than objects.",
      "Sponsored by a rival, publicly and expensively, to make a point.",
      "Sponsored by a mining concern. There is a shovel involved.",
      "Sponsored by a school that would like you to address its students. Decline.",
      "Sponsorship withdrawn. The plaque was already made.",
      "Sponsored anonymously, generously, and with unsettling accuracy about your needs.",
      "Sponsored by a company of mercenaries who now consider you an asset.",
    ],
  },
  {
    title: "d16 A title comes with it",
    id: "d16title_achievements",
    roll: [
      "You are now to be addressed as The Undersigned.",
      "The title is The Reasonable One. It is not meant kindly.",
      "You are Keeper of a Door. There is one door. It is fine.",
      "The title is First Of The New Problem.",
      "You are now, formally, A Person Of Interest.",
      "The title is Twice Advised. Everyone will ask. Do not explain.",
      "You are The Exception, which sounds better than it is.",
      "The title is Warden Of Nothing In Particular.",
      "You are The Precedent, and lawyers will find you.",
      "The title is Least Likely, awarded annually and retroactively.",
      "You are Hand Of The Committee, which carries duties nobody has listed.",
      "The title is Still Standing, and it must be used in full.",
      "You are The Reliable Witness. This will be tested.",
      "The title translates poorly. Locally it means Lucky Idiot.",
      "You are Custodian Of The Record, which is a box of loose paper.",
      "The title comes with a hat. The hat is the whole title, really.",
    ],
  },
  {
    title: "d12 The next tier",
    id: "d12nexttier_achievements",
    roll: [
      "The next tier requires doing it again, sober.",
      "Next tier: do it in front of someone whose opinion you value.",
      "The next tier is locked behind an achievement that is itself locked.",
      "Next tier requires a witness of rank. Rank is unspecified.",
      "The next tier has been earned once. The holder will not discuss the method.",
      "Next tier: do it without the equipment. Any of it.",
      "The next tier requires doing it twice within an hour, in different places.",
      "Next tier: teach someone else to do it, and let them.",
      "The next tier is seasonal. You have eleven months to wait.",
      "Next tier requires doing it wrong on purpose, convincingly.",
      "There is no next tier. This is the ceiling. Enjoy the view.",
      "The next tier exists. Its requirements are sealed, which is the requirement.",
    ],
  },
  {
    title: "d12 Somebody else",
    id: "d12simultaneous_achievements",
    roll: [
      "Someone three regions away earned this in the same hour. You will meet.",
      "A rival earned it first by an argued margin. The argument continues.",
      "Two people earned it simultaneously. The committee split the prize badly.",
      "Your own companion earned it beside you and has not stopped mentioning it.",
      "Someone earned it accidentally while you earned it deliberately. Guess who is celebrated.",
      "A child earned this last month. This is in the record, publicly.",
      "An enemy earned it the same day, which complicates the anecdote.",
      "Someone earned it and declined the prize. That is now the talking point.",
      "The simultaneous holder is unreachable and possibly fictional.",
      "A stranger earned it so much more impressively that yours is a footnote.",
      "You both earned it. One prize was made. It is being decided.",
      "Someone earned it decades ago and the record was lost, until now, inconveniently.",
    ],
  },
  {
    title: "d12 Under dispute",
    id: "d12contested_achievements",
    roll: [
      "Under review. A witness has offered a less flattering account.",
      "Contested by someone who was not present and is very confident.",
      "Suspended pending an explanation you cannot give.",
      "A scholar has questioned whether it counts. The scholar is technically right.",
      "Disputed on a technicality involving footwear.",
      "Someone has filed a formal objection. It runs to nine pages.",
      "The committee is split. The deciding vote is on holiday.",
      "Revoked, then reinstated, then revoked. Currently reinstated.",
      "Your account and the record disagree on one crucial detail.",
      "It stands, with an annotation that will follow it forever.",
      "A rival claims you were assisted. You were. It should not matter.",
      "Under appeal by someone who wants it awarded to their late relative.",
    ],
  },
  {
    title: "d12 About the prize",
    id: "d12prizeproblem_achievements",
    roll: [
      "It arrived early, before the achievement, which nobody will discuss.",
      "It is addressed to someone else. The name is close to yours.",
      "It is too large to carry and cannot be left.",
      "It is warm, and it should not be.",
      "It came with a second, smaller prize nobody will explain.",
      "It is claimed by a previous recipient who was told it had been destroyed.",
      "It does not fit through any door in this building.",
      "It is fine. The delivery method involved a hole in the roof.",
      "It hums when put down and stops when picked up.",
      "It was clearly used. Recently. Hard.",
      "It is in a locked case, and the key is a separate achievement.",
      "It is exactly what you wanted, which nobody could have known.",
    ],
  },
  {
    title: "d12 The ceremony",
    id: "d12ceremony_achievements",
    roll: [
      "A ceremony is scheduled. Attendance is mandatory and unpaid.",
      "There will be a plaque. Your name is spelled wrong and will not be corrected.",
      "A minor official will read a speech written for a different occasion.",
      "The ceremony is in nine months, in a city that may not exist by then.",
      "There is a parade. It is small. It is entirely for you. It is excruciating.",
      "A statue has been commissioned. The sculptor has never seen you.",
      "The ceremony was held already, without you, and went well.",
      "You will be given the key to a town. The town has no locks.",
      "A song is being written. You have no approval rights.",
      "A banquet, and one speech, and the speech is yours, unprepared.",
      "The ceremony involves a hat, a bell and an apology, in that order.",
      "There is no ceremony. There is a letter. The letter is genuinely moving.",
    ],
  },
  {
    title: "d12 Word gets around",
    id: "d12notoriety_achievements",
    roll: [
      "Your name is now known in circles you have never entered.",
      "Three people have claimed to be you this month.",
      "A tavern has named a drink after you. It is not good.",
      "Children in one town play a game based on what you did.",
      "Someone is writing an account of it. They have not asked you anything.",
      "You are recognised now, occasionally, at the worst moments.",
      "A bounty has been posted. Not for capture. For an interview.",
      "Your name appears twice in a ledger you have never seen.",
      "An academic has cited you. The citation is a footnote and a slight.",
      "Somewhere a rival has your description pinned to a wall.",
      "You are an example now, used to warn and to encourage, depending.",
      "Nothing has changed. Everyone forgot within a week. It is a relief.",
    ],
  },
  {
    title: "d16 Prize, in brief",
    id: "d16briefprize_achievements",
    roll: [
      "Prize: a spoon.",
      "Prize: coins that no longer spend.",
      "Prize: boots that never blister.",
      "Prize: a rope with opinions.",
      "Prize: a goat.",
      "Prize: something cursed and genuinely useful.",
      "Prize: a hat of modest power.",
      "Prize: three doses of something.",
      "Prize: a title nobody wanted.",
      "Prize: a rock. A nice one.",
      "Prize: a lantern with a strict schedule.",
      "Prize: a bird that knows your name.",
      "Prize: withheld pending review.",
      "Prize: already spent, somehow.",
      "Prize: a certificate, damp.",
      "Prize: genuinely excellent, and someone is coming for it.",
    ],
  },

  /* ------------------------------------------------------------------
   * The prize gate: always fires, but picks one of eight payout shapes.
   * Practical appears twice, so the odds run roughly junk 1 in 8,
   * practical 1 in 4, cursed 1 in 8.
   * ---------------------------------------------------------------- */
  {
    title: "Prize awarded",
    singular: "Payout",
    id: "gateprize_achievements",
    roll_type: "type",
    number: "1d1",
    percent_to: "100",
    percent_of: "100",
    roll: [
      {
        title: "Junk, frankly",
        main_rolls: ["achievements/d16junk_achievements"],
        sub_rolls: [],
      },
      {
        title: "Something genuinely useful",
        main_rolls: ["achievements/d16practical_achievements"],
        sub_rolls: [],
      },
      {
        title: "Something quietly excellent",
        main_rolls: ["achievements/d16practical_achievements"],
        sub_rolls: [],
      },
      {
        title: "Absurd, and stronger than it looks",
        main_rolls: ["achievements/d14absurd_achievements"],
        sub_rolls: [],
      },
      {
        title: "Cursed, technically",
        main_rolls: ["achievements/d14cursed_achievements"],
        sub_rolls: [],
      },
      {
        title: "Consumable",
        main_rolls: ["achievements/d14consumable_achievements"],
        sub_rolls: [],
      },
      {
        title: "Cosmetic only",
        main_rolls: ["achievements/d14cosmetic_achievements"],
        sub_rolls: [],
      },
      {
        title: "Livestock",
        main_rolls: ["achievements/d12livestock_achievements"],
        sub_rolls: [],
      },
    ],
  },

  /* ------------------------------------------------------------------
   * Chance-gated tangents
   * ---------------------------------------------------------------- */
  {
    title: "Audience",
    singular: "Reaction",
    id: "gateaudience_achievements",
    roll_type: "amount",
    number: "1d1",
    percent_to: "60",
    percent_of: "100",
    rolls: ["achievements/d16audience_achievements"],
  },
  {
    title: "Leaderboard",
    singular: "Position",
    id: "gateleaderboard_achievements",
    roll_type: "amount",
    number: "1d1",
    percent_to: "35",
    percent_of: "100",
    rolls: ["achievements/d14leaderboard_achievements"],
  },
  {
    title: "Sponsor",
    singular: "Backing",
    id: "gatesponsor_achievements",
    roll_type: "amount",
    number: "1d1",
    percent_to: "30",
    percent_of: "100",
    rolls: ["achievements/d16sponsor_achievements"],
  },
  {
    title: "Title granted",
    singular: "Style",
    id: "gatetitle_achievements",
    roll_type: "amount",
    number: "1d1",
    percent_to: "25",
    percent_of: "100",
    rolls: ["achievements/d16title_achievements"],
  },
  {
    title: "There is a next tier",
    singular: "Requirement",
    id: "gatenexttier_achievements",
    roll_type: "amount",
    number: "1d1",
    percent_to: "20",
    percent_of: "100",
    rolls: ["achievements/d12nexttier_achievements"],
  },
  {
    title: "You were not alone",
    singular: "Claimant",
    id: "gatesimultaneous_achievements",
    roll_type: "amount",
    number: "1d1",
    percent_to: "15",
    percent_of: "100",
    rolls: ["achievements/d12simultaneous_achievements"],
  },
  {
    title: "Contested",
    singular: "Objection",
    id: "gatecontested_achievements",
    roll_type: "amount",
    number: "1d1",
    percent_to: "12",
    percent_of: "100",
    rolls: ["achievements/d12contested_achievements"],
  },
  {
    title: "The prize is a problem",
    singular: "Complication",
    id: "gateprizeproblem_achievements",
    roll_type: "amount",
    number: "1d1",
    percent_to: "10",
    percent_of: "100",
    rolls: ["achievements/d12prizeproblem_achievements"],
  },
  {
    title: "First ever recorded",
    singular: "Consequence",
    id: "gatefirstever_achievements",
    roll_type: "type",
    number: "1d1",
    percent_to: "6",
    percent_of: "100",
    roll: [
      {
        title: "There will be a ceremony",
        main_rolls: [
          "achievements/d12ceremony_achievements",
          "achievements/d12notoriety_achievements",
        ],
        sub_rolls: [],
      },
      {
        title: "It is being kept quiet",
        main_rolls: ["achievements/d12notoriety_achievements"],
        sub_rolls: [],
      },
    ],
  },

  /* ------------------------------------------------------------------
   * The sweep: a session's worth at a glance, one line each
   * ---------------------------------------------------------------- */
  {
    title: "Achievements unlocked",
    singular: "Award",
    id: "gatesweep_achievements",
    roll_type: "type",
    number: "1d4",
    percent_to: "100",
    percent_of: "100",
    roll: [
      {
        title: "Combat",
        main_rolls: [
          "achievements/d16combat_achievements",
          "achievements/d16briefprize_achievements",
        ],
        sub_rolls: [],
      },
      {
        title: "Self-inflicted",
        main_rolls: [
          "achievements/d16selfinflicted_achievements",
          "achievements/d16briefprize_achievements",
        ],
        sub_rolls: [],
      },
      {
        title: "Social",
        main_rolls: [
          "achievements/d14social_achievements",
          "achievements/d16briefprize_achievements",
        ],
        sub_rolls: [],
      },
      {
        title: "Exploration",
        main_rolls: [
          "achievements/d14exploration_achievements",
          "achievements/d16briefprize_achievements",
        ],
        sub_rolls: [],
      },
      {
        title: "Trade and craft",
        main_rolls: [
          "achievements/d14trade_achievements",
          "achievements/d16briefprize_achievements",
        ],
        sub_rolls: [],
      },
      {
        title: "Survival",
        main_rolls: [
          "achievements/d14survival_achievements",
          "achievements/d16briefprize_achievements",
        ],
        sub_rolls: [],
      },
      {
        title: "Animals",
        main_rolls: [
          "achievements/d14animals_achievements",
          "achievements/d16briefprize_achievements",
        ],
        sub_rolls: [],
      },
      {
        title: "Food and drink",
        main_rolls: [
          "achievements/d14food_achievements",
          "achievements/d16briefprize_achievements",
        ],
        sub_rolls: [],
      },
      {
        title: "Unclassifiable",
        main_rolls: [
          "achievements/d16unclassifiable_achievements",
          "achievements/d16briefprize_achievements",
        ],
        sub_rolls: [],
      },
    ],
  },
];
