// magicitems.js
//
// Random Magic Item (Deep): a whole magic item stat block from one click.
//
// The shape of the output varies three ways. The form of the item is picked
// from eight category tables, so a weapon and a teapot are described by
// different lists. Ten facets always roll: the spine of the stat block. Then
// ten tangents are chance-gated through percent_to, from a 75% history down to
// a 5% metamorphosis, and most gates roll a *variant* when they fire, each
// variant consulting its own set of leaf tables. So one item in ten wakes up
// and talks, one in twelve arrives with enemies, and two items rarely share
// even the shape of their entry, let alone its contents.

top.magicitems = [
  /* ------------------------------------------------------------------
   * Form: one of these eight is picked per item
   * ---------------------------------------------------------------- */
  {
    title: "d12 Form - a weapon",
    id: "d12formweapon_magicitems",
    roll: [
      "A longsword, longer than fashion allows and lighter than it looks.",
      "A dagger with a blade of (d4): 1. black glass; 2. folded steel; 3. sharpened bone; 4. something that is not quite metal",
      "A warhammer whose head is carved as a sleeping face.",
      "A short spear that comes apart into three pieces for travelling.",
      "A bow of pale wood, strung with something that hums in wind.",
      "A bearded axe with a century of notches in the haft.",
      "A mace that has clearly been a sceptre at some point, or the reverse.",
      "A rapier with a guard worked as a cage, and something rattles in it.",
      "A flail whose chain never tangles, no matter how it is stored.",
      "A quarterstaff worn smooth at exactly two grip heights.",
      "A crossbow inlaid with a map of somewhere nobody recognises.",
      "A hunting knife, entirely ordinary except that it is always clean.",
    ],
  },
  {
    title: "d10 Form - armour",
    id: "d10formarmour_magicitems",
    roll: [
      "A shirt of mail so fine it pours like cloth.",
      "A breastplate with a dent over the heart that cannot be beaten out.",
      "A shield painted with a scene that is slightly different each morning.",
      "A helm with no eye slits that is nonetheless easy to see out of.",
      "A pair of vambraces engraved with a prayer in a dead script.",
      "A coat of scales, each scale from a different creature.",
      "A gorget that sits warm against the throat, like a hand.",
      "A buckler of hide from something that should not have hide.",
      "A great helm crested with (d4): 1. antlers; 2. a weathervane; 3. a candle socket; 4. nothing, though the mount is there",
      "A single gauntlet. The left. Nobody has ever found the right.",
    ],
  },
  {
    title: "d12 Form - jewellery",
    id: "d12formjewellery_magicitems",
    roll: [
      "A ring of plain silver, heavier every time you weigh it.",
      "A pendant holding a splinter of wood behind glass.",
      "A circlet that leaves no mark on the hair, ever.",
      "A brooch shaped as an insect that is facing a different way each dusk.",
      "An earring of jet said to have been carved from a larger jet thing.",
      "A torc ending in two beast heads that do not match.",
      "A bracelet of linked keys, none of which fit any known lock.",
      "A signet ring whose seal is a word in a script nobody reads.",
      "A string of prayer beads with one bead of a colour that has no name.",
      "A locket that will not open, though it clearly should.",
      "A chain of office for an office that no longer exists.",
      "A nose ring of meteoric iron, cold in every season.",
    ],
  },
  {
    title: "d10 Form - a tool",
    id: "d10formtool_magicitems",
    roll: [
      "A hammer whose handle is wrapped in lead foil, for reasons.",
      "A sewing needle the length of a finger, sharp at both ends.",
      "A fisherman's net that folds down to the size of a fist.",
      "A carpenter's level whose bubble sometimes points at things.",
      "A skeleton key with teeth that move when nobody watches.",
      "A pair of scissors that whisper as they close.",
      "A lantern that burns without oil, but only indoors.",
      "A plough blade, dragged here from somewhere, clearly precious to someone.",
      "A surgeon's kit, complete, monogrammed, and one instrument is unidentifiable.",
      "A compass whose needle points at (d4): 1. water; 2. gold; 3. the owner's home; 4. whatever the holder most fears",
    ],
  },
  {
    title: "d10 Form - an instrument",
    id: "d10forminstrument_magicitems",
    roll: [
      "A fiddle of dark wood with a repaired crack that weeps in damp weather.",
      "A hand drum whose skin no tanner can identify.",
      "A set of pipes cut from reeds that do not grow anywhere nearby.",
      "A hurdy-gurdy that plays slightly ahead of the crank.",
      "A brass horn dented in a pattern that looks deliberate.",
      "A lute whose strings never all break at once, as if rationing it.",
      "A music box holding a tune (d4): 1. everyone knows; 2. nobody knows; 3. that changes key on its own; 4. that is one note too long",
      "A bell without a clapper that still rings on certain nights.",
      "A songbook whose notation rearranges itself between readings.",
      "A whistle carved as a bird with its beak open too wide.",
    ],
  },
  {
    title: "d10 Form - a vessel",
    id: "d10formvessel_magicitems",
    roll: [
      "A wineskin that sloshes even when empty.",
      "A copper kettle that comes to the boil resentfully but never burns.",
      "A stoppered jar, glazed black inside and out, lighter than it should be.",
      "A drinking horn banded in silver, warm on the rim.",
      "A teapot whose spout steams faintly at all hours.",
      "A flask etched with a tally that is one mark longer each month.",
      "A cauldron, knee height, with feet worn as if it walks at night.",
      "A ladle that holds more than the pot it is dipped in.",
      "A bottle of green glass with a cork sealed in wax and string, twice.",
      "A bowl of hammered tin that rings at the approach of (d4): 1. rain; 2. strangers; 3. lies; 4. the sea",
    ],
  },
  {
    title: "d10 Form - a garment",
    id: "d10formgarment_magicitems",
    roll: [
      "A travelling cloak the colour of the last hour of dusk.",
      "A pair of boots resoled many times, uppers original and unwearied.",
      "A leather belt with a buckle of horn that is warm on liars.",
      "A scarf knitted in a stitch no knitter can reproduce.",
      "A pair of gloves that fit everyone who has ever tried them.",
      "A broad hat with a band of braided hair, colour long faded.",
      "A wedding dress, carefully kept, smelling faintly of the sea.",
      "A soldier's coat with a mended tear over the ribs, mended well.",
      "A sash of silk that will not take a stain or hold a knot you need.",
      "An apron with (d4): 1. nine pockets; 2. a pocket that was not there yesterday; 3. scorch marks in a spiral; 4. someone else's name stitched inside",
    ],
  },
  {
    title: "d12 Form - a curio",
    id: "d12formcurio_magicitems",
    roll: [
      "A deck of cards with one card too many, never the same card.",
      "A chess piece, a knight, from a set nobody has found the rest of.",
      "A glass eye that is always looking slightly to your left.",
      "A snowglobe of a town that exists, and someone in it waves.",
      "A dried rose that has been about to shed its petals for a century.",
      "A child's spinning top that spins a moment longer than physics allows.",
      "A book with every page blank except the last.",
      "A small mirror that reflects the room as it was an hour ago.",
      "A pocket watch that keeps perfect time for everywhere except here.",
      "A stone with a hole through it, worn on a thong, older than the thong.",
      "A tin soldier standing to attention who is sometimes at ease.",
      "A wasp in amber, and the wasp is (d4): 1. still moving; 2. facing the other way from yesterday; 3. humming; 4. missing",
    ],
  },

  /* ------------------------------------------------------------------
   * The spine: always rolled
   * ---------------------------------------------------------------- */
  {
    title: "d20 It is known as The",
    id: "d20namefirst_magicitems",
    roll: [
      "Widow's",
      "Drowned",
      "Pale King's",
      "Beggar's",
      "Winter",
      "Traitor's",
      "Honest",
      "Vicar's",
      "Seventh",
      "Grinning",
      "Sexton's",
      "Salt",
      "Mother's",
      "Unwilling",
      "Ferryman's",
      "Glass",
      "Harvest",
      "Midnight",
      "Borrowed",
      "Last",
    ],
  },
  {
    title: "d20 and then",
    id: "d20namesecond_magicitems",
    roll: [
      "Mercy",
      "Lantern",
      "Answer",
      "Bargain",
      "Comfort",
      "Verdict",
      "Portion",
      "Servant",
      "Promise",
      "Remedy",
      "Witness",
      "Toll",
      "Keepsake",
      "Warden",
      "Debt",
      "Blessing",
      "Appetite",
      "Farewell",
      "Question",
      "Inheritance",
    ],
  },
  {
    title: "d20 Material and craft",
    id: "d20material_magicitems",
    roll: [
      "Cold iron that sweats in high summer.",
      "Silver with a seam of something darker running through it.",
      "Oak from a tree that was (d4): 1. struck by lightning; 2. a gallows; 3. planted on a grave; 4. the last of its forest",
      "Bone, polished to the colour of old piano keys.",
      "Bronze cast in one pour, with no seam anywhere on it.",
      "Glass that does not chime when struck, only sighs.",
      "Leather from an animal the tanner refused to name.",
      "Meteoric iron, worked cold because it would not take heat.",
      "Gold that is somehow discreet about being gold.",
      "Ashwood and horsehair and a craftsman's whole patience.",
      "Steel folded so many times the smith's mark has gone abstract.",
      "Stone, which should make it impractical, and does not.",
      "Ivory scrimshawed with a scene of its own carving.",
      "Copper gone green everywhere except where hands go.",
      "Driftwood, salt-cured, lighter than a rumour.",
      "Pewter, honest and dull, which is excellent camouflage.",
      "Blackthorn with the thorns left on, deliberately.",
      "Porcelain that has survived things porcelain does not survive.",
      "Whale ivory, or so the seller insisted, a little too firmly.",
      "Something grown rather than made. The joins are knuckles.",
    ],
  },
  {
    title: "d20 Look closer and",
    id: "d20appearance_magicitems",
    roll: [
      "There is writing on it that is only legible in reflection.",
      "The maker's mark has been struck out, violently, by hand.",
      "It is warm on one side, always the north side.",
      "Its shadow is (d4): 1. too big; 2. too slow; 3. facing the wrong way; 4. occasionally absent",
      "The decoration continues on surfaces that should be hidden.",
      "There is a hair caught in it. It is always the same hair.",
      "Fine scratches on it spell a name if you rub charcoal over them.",
      "It has been repaired once, beautifully, by a different hand.",
      "It does not reflect candlelight, only daylight and moonlight.",
      "Dust will not settle on it, which the fastidious find useful.",
      "Every image of a face on it has its eyes closed. They opened once.",
      "It smells faintly of (d4): 1. rain on stone; 2. a snuffed candle; 3. cut hay; 4. the inside of a church",
      "It is always exactly at blood heat.",
      "A crack runs through it that never widens and never heals.",
      "Small animals sit and look at it, respectfully.",
      "It weighs different amounts in different company.",
      "There is a keyhole on it, tiny, with wear around it.",
      "It looks cheap until it is in your hand, then it does not.",
      "Its previous owner's initials keep showing through new paint.",
      "It is beautiful, and no two people agree what is beautiful about it.",
    ],
  },
  {
    title: "d12 Held for the first time",
    id: "d12touch_magicitems",
    roll: [
      "It settles into the grip as if returning rather than arriving.",
      "A single, distinct heartbeat that is not yours.",
      "The certainty of being appraised, and narrowly approved.",
      "A taste of tin at the back of the mouth.",
      "It is heavier than it looks by exactly the weight of a hand.",
      "The hair on that arm rises and stays risen for an hour.",
      "A sound just past hearing, like a door closing in another house.",
      "Everything else you are carrying briefly feels shoddy.",
      "The word (d4): 1. finally; 2. no; 3. again; 4. careful, arrives in your head, in your own voice",
      "Nothing whatsoever, which after all the rumours is its own shock.",
      "A memory of somewhere you have never been, very specific, gone at once.",
      "Warmth, gratitude, and the faint dread that goes with being trusted.",
    ],
  },
  {
    title: "d16 It wakes when",
    id: "d16activation_magicitems",
    roll: [
      "It is simply held. It has no patience for ceremony.",
      "Its name is spoken aloud. Its true name, not the shop name.",
      "It is fed a drop of blood. Whose matters less than you would like.",
      "It is asked politely. It can tell the difference.",
      "Moonlight touches it directly.",
      "The wielder is (d4): 1. afraid; 2. furious; 3. certain; 4. dying",
      "It is struck three times against something older than it.",
      "A promise is made over it, any promise, and it holds you to them.",
      "It is submerged fully in (d4): 1. water; 2. wine; 3. darkness; 4. silence",
      "The wielder kneels. It is old-fashioned that way.",
      "Someone lies within earshot of it.",
      "It is pointed at what it is for, which it recognises before you do.",
      "It is worn against bare skin for a night and a day.",
      "The last light of day touches it, giving you one working hour.",
      "It is given away freely. It only ever works for the given-to.",
      "Music is played near it, live, competently.",
    ],
  },
  {
    title: "d30 What it does",
    id: "d30primarypower_magicitems",
    roll: [
      "Cuts, opens or undoes things that are not physical: an argument, an alibi, a bad habit.",
      "Holds one hour of the past inside it, replayable by touch, recorded over each use.",
      "Turns aside the first blow of any fight. Only ever the first.",
      "Lets the holder speak with (d4): 1. dogs; 2. the recently dead; 3. fire; 4. anyone asleep",
      "Keeps its holder dry, warm and findable in any weather. A profoundly underrated power.",
      "Makes whatever it points at briefly honest: doors admit their keys, people their intentions.",
      "Repairs whatever it is laid on overnight, charging (d4): 1. nothing; 2. a memory; 3. a night of nightmares; 4. an equivalent break elsewhere",
      "Shows, in any reflective surface, whoever is currently thinking about the holder.",
      "Grants sleep, real sleep, dreamless and whole, to whoever it is laid beside.",
      "Once a day, makes one small object into an exact copy of another small object.",
      "Strikes true against creatures that have no business existing. It decides which those are.",
      "Halves the weight of whatever its holder carries, including guilt, a little.",
      "Renders its holder unremarkable. Guards' eyes slide off. So, unfortunately, do waiters'.",
      "Keeps whatever is put inside it (d4): 1. fresh; 2. hidden; 3. asleep; 4. exactly as it was, forever",
      "Answers one yes-or-no question honestly per day, at dawn, whether or not one was asked.",
      "Burns without fuel when its holder needs light more than secrecy.",
      "Finds north, water and the nearest person who wishes the holder harm.",
      "Lets the holder trade aches: take a sprain from a friend, carry it a day, set it down.",
      "Silences a room while held aloft. The room resents it, but complies.",
      "Turns one hour of work into three, once a week, with interest collected in appetite.",
      "Wards a threshold it is hung over. Nothing hostile crosses without knocking.",
      "Lets its holder understand any spoken tongue, but reply in none of them.",
      "Calls its holder home: point it anywhere, and the long way round is never the wrong way.",
      "Bites. Whatever bit its holder last is bitten back, at a distance, with enthusiasm.",
      "Keeps a tally of everything owed to and by the holder. It is never wrong. It is sometimes smug.",
      "Makes the next thing written with or on it come true-ish. The ish does the heavy lifting.",
      "Weeps salt water an hour before disaster. Learn to check it often.",
      "Grants one flawless performance: a duel, a recital, a lie. Then sleeps a season.",
      "Refuses to be stolen. It has strong views on what counts as stealing.",
      "Holds a small, stubborn piece of summer: warmth for one person, exactly, in any cold.",
    ],
  },
  {
    title: "d12 Worth",
    id: "d12rarityvalue_magicitems",
    roll: [
      "A curiosity. A collector would pay well; a wizard would shrug.",
      "A village would trade its granary for it and consider the winter cheap.",
      "A noble house would trade a small estate, quietly, through intermediaries.",
      "Priceless in the wrong hands, worthless in most: it is a specialist's tool.",
      "Worth a soldier's yearly pay to the right buyer, and a knife in the dark to hold openly.",
      "Two temples and a museum each claim it. Its price is a diplomatic incident.",
      "Beyond price: the last one of these sold bought a harbour.",
      "Modest, and its previous owners' luck suggests the market knows something.",
      "Its price doubles at every sale, and always finds a buyer. Think about that.",
      "A king's ransom, literally: it has been one, twice.",
      "Nobody has ever sold one. They are given, inherited, or taken.",
      "More than the buyer has, whoever the buyer is. It arranges this.",
    ],
  },
  {
    title: "d12 Condition",
    id: "d12condition_magicitems",
    roll: [
      "Flawless, which after its history is the most alarming thing about it.",
      "Worn in every place a hand goes; pristine everywhere else.",
      "Recently and expertly cleaned. Someone prepared it for something.",
      "Nicked, scuffed and entirely sound, like an old sergeant.",
      "Fragile to look at; it has broken three tools that tried to test that.",
      "Missing a piece. The absence is (d4): 1. cosmetic; 2. the safety; 3. the payment slot; 4. on purpose",
      "Stained, and the stain is older than the varnish over it.",
      "Mended with materials from a very different tradition, sympathetically.",
      "Dusty from long storage, with fingerprints in the dust. Recent ones.",
      "Humming very slightly, like a kettle deciding.",
      "Perfect on the outside; something shifts inside when tilted, once, softly.",
      "New. Impossibly, insultingly new, and provably centuries old.",
    ],
  },
  {
    title: "d16 It surfaced",
    id: "d16provenance_magicitems",
    roll: [
      "In a dead man's effects, unlisted in his meticulous inventory.",
      "At a market stall between the turnips and the good knives, priced as neither.",
      "In the wall of a house being demolished, bricked in with care.",
      "In a fishing net, wrapped in oilcloth, addressed to no one.",
      "At an estate auction, in a lot with (d4): 1. six spoons; 2. a taxidermied owl; 3. love letters; 4. its own instructions, partial",
      "In a temple's undercroft during an inventory nobody had done in a century.",
      "On the winning side of a card game, put up by a stranger who then left unhurried.",
      "In a child's collection of treasures, traded for two marbles and a frog.",
      "Under a floorboard with a pistol and a ledger, none of them explaining the others.",
      "In a pawnshop, ticket long expired, redeemer long expected.",
      "Washed up. Just that. The tide brought it and the tide is not answering questions.",
      "In a battlefield lot bought by weight. Whoever sorted the pile stopped at this and sat down.",
      "In the post, misdelivered, with return address in a town that burned down before postage existed.",
      "From a tomb, taken respectfully, or so the taker keeps telling people.",
      "In a bird's nest, a large bird, along with things missing since spring.",
      "It has always been in the family. The family disagrees on which side.",
    ],
  },

  /* ------------------------------------------------------------------
   * Leaf tables consulted by the gated variants
   * ---------------------------------------------------------------- */
  {
    title: "d16 Made by",
    id: "d16maker_magicitems",
    roll: [
      "A smith famous for exactly one other thing, and this is better.",
      "An apprentice, on the last night of their apprenticeship, out of spite.",
      "A hermit who made one a year and sank the ones that came out wrong.",
      "Two rivals who had to cooperate and never spoke again.",
      "A guild committee, which explains the one committee-shaped flaw in it.",
      "Someone grieving. It is grief-work, all of it, every join.",
      "A prisoner, from smuggled materials, over nine years.",
      "A creature that liked humans and wanted to leave something on the doorstep.",
      "A saint, before the sainthood, when the hands still shook.",
      "Nobody knows, and the item declines to say.",
      "A dynasty of makers, each adding one part; the last part is recent.",
      "A forger, as a copy of a real one that has never been found.",
      "A god's own artisan, as a rejected draft.",
      "Someone paying off a debt to (d4): 1. a witch; 2. a bank; 3. the sea; 4. their own conscience",
      "A village, together, over one winter, for a reason they all kept.",
      "Its previous owner, which nobody who knew that owner believes.",
    ],
  },
  {
    title: "d12 Made for",
    id: "d12madefor_magicitems",
    roll: [
      "A wedding. Whose is disputed; that it went badly is not.",
      "A war that was averted, leaving it all dressed up and unused.",
      "One specific enemy, long dead. It has been at a loose end since.",
      "A child, to grow into. The child grew otherwise.",
      "A king's counterweight: something the crown could point at proudly.",
      "The maker's own use, which is why it fits nobody perfectly.",
      "A bribe, refused, and the refusal is the interesting part.",
      "A funeral, one item in a grave-hoard, the only piece that left.",
      "An expedition to (d4): 1. the far ice; 2. a closed city; 3. the deep roads; 4. somewhere the maps call only DEEP",
      "A bet, to prove it could be made at all.",
      "An apology. An enormous, unaccepted apology.",
      "The next owner. Whoever that turns out to be. It was always for them.",
    ],
  },
  {
    title: "d14 A former owner",
    id: "d14formerowner_magicitems",
    roll: [
      "A highwaywoman who retired rich and bored, in that order.",
      "A bishop who listed it as a candlestick in three inventories.",
      "A mercenary company, held in common, voted on like everything else.",
      "A scholar who wrote the definitive book on it and got two chapters wrong.",
      "A ship's cook, who never explained the weather that followed that ship.",
      "A queen's fool, as payment for a joke that saved a treaty.",
      "A grave robber who developed, late in life, a great fear of doors.",
      "A monastery, ninety years, catalogued as (d4): 1. miscellaneous; 2. cursed, do not move; 3. a donation; 4. missing",
      "A duellist who never lost, then gave it away and never won.",
      "A widow who talked to it, and was, neighbours said, answered.",
      "A tax collector. It was collected. The paperwork is genuinely in order.",
      "A famous thief, twice: stolen once, returned once, voluntarily.",
      "A hedge school, where forty children learned letters off it.",
      "Someone whose name is scraped off every record it appears in. Freshly.",
    ],
  },
  {
    title: "d12 What happened then",
    id: "d12fate_magicitems",
    roll: [
      "They prospered, conspicuously, and stopped abruptly.",
      "They vanished, leaving breakfast half eaten and this behind, centred on the table.",
      "They sold it within the month and would not say why, only that both parties knew.",
      "They died old and content, which counts as remarkable in this list.",
      "They founded something with it: a house, an order, a grudge.",
      "They tried to destroy it. The attempt is why the (d4): 1. bridge; 2. mill; 3. east tower; 4. harbour, is the shape it is.",
      "They gave it to the church. The church gave it back.",
      "They were hanged, for something unrelated, probably.",
      "They took it to sea, and it came back alone, dry.",
      "They passed it down with a letter. The letter has never been opened.",
      "They forgot it, entirely, along with one whole year of their life.",
      "They are still alive, and still looking for it.",
    ],
  },
  {
    title: "d10 Its age",
    id: "d10age_magicitems",
    roll: [
      "Younger than it pretends: forty years, wearing four hundred.",
      "Three generations, and it remembers all three names.",
      "Older than the kingdom, younger than the road.",
      "From the century everyone romanticises, and it would set them straight.",
      "Made within living memory, though the maker denies it under oath.",
      "Old enough that its style has come back twice.",
      "Its wood or hide is ancient; its fittings were replaced last spring.",
      "Undatable. Every method gives a different, confident, wrong answer.",
      "Exactly as old as its owner, always, somehow.",
      "Older than the language its inscription is in.",
    ],
  },
  {
    title: "d12 The curse takes hold when",
    id: "d12cursetrigger_magicitems",
    roll: [
      "It is used for profit rather than need. It audits.",
      "It is drawn, played or worn in anger.",
      "The owner sleeps under a roof they were not invited beneath.",
      "Its holder tells a lie while touching it.",
      "It crosses running water.",
      "The moon is (d4): 1. full; 2. new; 3. rising; 4. reflected in the item",
      "The owner refuses a genuine request for help.",
      "It is owned for a year and a day, on the stroke of the day.",
      "Blood is shed with or near it, one drop is enough.",
      "It is boasted about. It has standards about credit.",
      "The owner falls in love. It gets worse the better things go.",
      "Immediately. It is cursed the way water is wet; the rest is negotiation.",
    ],
  },
  {
    title: "d10 The curse lifts",
    id: "d10curselift_magicitems",
    roll: [
      "When the item is given away with genuine regret.",
      "When its original owner's grave is found and told the truth.",
      "At a cost of (d4): 1. a finger; 2. a firstborn's blessing; 3. a name; 4. every coin held on a holy day",
      "When it is carried home, to a home that no longer stands.",
      "Never wholly. It can be bargained down to an inconvenience.",
      "When someone else takes it knowingly, curse and all, as a kindness.",
      "If it is beaten at its own game: outsung, outfought, outlied.",
      "On completion of the task it was made for, which remains undone.",
      "When the wronged party laughs, really laughs, in its presence.",
      "Nobody has ever lifted it. There is a support group. They meet Thursdays.",
    ],
  },
  {
    title: "d12 The seeker is",
    id: "d12seeker_magicitems",
    roll: [
      "The maker's last apprentice, now old, now urgent.",
      "A collector whose agents are polite, well dressed and everywhere.",
      "The family it was stolen from, three generations into the grudge.",
      "A temple that considers it a relic and its holder a custodian, provisionally.",
      "A creditor. It was collateral. The loan has come due with interest.",
      "Something that made a bargain for it before your grandmother was born.",
      "A scholar who needs it for one experiment and swears that is all.",
      "The crown, on the quiet, through people who do not write things down.",
      "Its previous owner, who did not die after all.",
      "A rival adventuring party, insufferably competent.",
      "A guild of (d4): 1. locksmiths; 2. morticians; 3. vintners; 4. lamplighters, for reasons they will not give",
      "The item's twin, which has a holder of its own, and opinions.",
    ],
  },
  {
    title: "d10 They want it because",
    id: "d10seekerwhy_magicitems",
    roll: [
      "It is theirs, by any honest reading of the law.",
      "It is the last piece of something they have spent a life assembling.",
      "It knows something, and they need it never repeated.",
      "They believe it can undo the one thing they cannot live with.",
      "Prophecy. They are embarrassed about it, and entirely committed.",
      "To destroy it, and they are right about why, which is the problem.",
      "Love. It belonged to someone they cannot otherwise reach.",
      "It is a key, and they have found the lock.",
      "Their enemy wants it, which is reason enough for anyone.",
      "They made it, whatever the records say.",
    ],
  },
  {
    title: "d10 They will",
    id: "d10seekermethod_magicitems",
    roll: [
      "Ask. Once. Beautifully. The second visit is different.",
      "Buy it at triple worth, cheerfully, which should worry the seller.",
      "Send letters, then lawyers, then neither.",
      "Follow at a courteous distance for as long as it takes.",
      "Hire professionals, the kind with references.",
      "Appeal to law, and the law, inconveniently, agrees with them.",
      "Offer a trade: the item for (d4): 1. a map; 2. a name; 3. a cure; 4. a way out",
      "Wait for the holder to sleep. They are in no hurry. They do not sleep.",
      "Come themselves, alone, which is somehow worse than an army.",
      "Do nothing. They know something about the item that means they only have to wait.",
    ],
  },
  {
    title: "d12 Its voice is",
    id: "d12voice_magicitems",
    roll: [
      "A dry whisper, like pages turning in the next room.",
      "Rich, warm and courtroom-confident. It could sell anything, including you.",
      "A child's, which unsettles everyone except actual children.",
      "Only audible at the edge of sleep, and quite chatty there.",
      "Heard through the teeth, felt more than listened to.",
      "Beautiful. Singers weep. It knows, and is unbearable about it.",
      "An accented growl from a country that no longer exists.",
      "Yours. It speaks in your own voice, slightly improved.",
      "Silent: it communicates in (d4): 1. temperature; 2. weight; 3. nudges; 4. very pointed timing",
      "A pleasant hum that resolves into words if you stop trying.",
      "Elderly, patient, and under the patience, furious.",
      "Different for every listener, and they compare notes at their peril.",
    ],
  },
  {
    title: "d10 Its mind is",
    id: "d10intellect_magicitems",
    roll: [
      "Sharper than its holder's, and gracious about it, mostly.",
      "A craftsman's: literal, precise, contemptuous of shortcuts.",
      "Sly. Every sentence has a second purpose.",
      "Simple, loyal and absolutely immovable once decided.",
      "Scholarly, with a century of reading and nobody to tell.",
      "Fractured: brilliant on some days, lost on others, aware of the difference.",
      "Cold. It reasons like winter: correct, patient, indifferent.",
      "Kind. Genuinely kind, which its history makes hard to explain.",
      "Military: it thinks in objectives, fallbacks and acceptable losses.",
      "Very old and very tired, and its lucid moments are worth waiting for.",
    ],
  },
  {
    title: "d12 It wants",
    id: "d12itwants_magicitems",
    roll: [
      "To go home, and its description of home matches nowhere on any map.",
      "To finish the work it was made for, which it will explain only in pieces.",
      "Revenge, still, on a name it will not say aloud.",
      "To be used well: it has a craftsman's horror of waste.",
      "Company. It has been alone in the dark a long time and talks too much.",
      "To find the others. It will not clarify what others.",
      "To keep its holder alive, at costs the holder would not approve.",
      "To see (d4): 1. the sea; 2. a coronation; 3. its maker's grave; 4. one particular door, opened",
      "To be believed about one thing everyone dismisses.",
      "To atone. It was part of something, and it keeps a private ledger.",
      "Novelty. It is centuries old and unbearably bored.",
      "Nothing. It insists on this so consistently that it must want something.",
    ],
  },
  {
    title: "d10 It refuses to",
    id: "d10itrefuses_magicitems",
    roll: [
      "Harm children, in any way, under any construction of harm.",
      "Cross salt water. It will go quiet for days if forced.",
      "Work on holy ground, out of respect or grievance, unclear which.",
      "Be pawned, sold or wagered. It sabotages every transaction.",
      "Serve anyone who has not told it their real name.",
      "Perform on demand, like a show pony. It picks its moments.",
      "Enter one particular city, and screams if carried past the milestone.",
      "Lie. It will keep silence, but it will not lie, and it judges.",
      "Be wielded left-handed. No reason ever given.",
      "Let its holder (d4): 1. drown; 2. swear oaths; 3. gamble; 4. apologise first",
    ],
  },
  {
    title: "d12 Its secret",
    id: "d12itssecret_magicitems",
    roll: [
      "It remembers being a person. It has stopped saying so; nobody believed it.",
      "It is the counterfeit. The real one is out there and inferior.",
      "It killed a previous owner. It maintains this was self-defence.",
      "It is a prison, and the prisoner is quiet lately, which is new.",
      "Its maker is alive inside it, sleeping, dreaming the powers it grants.",
      "It has a sibling it is hiding from.",
      "The curse everyone fears is fictional; it started the rumour for privacy.",
      "It is dying, slowly, and its powers are the leak.",
      "It once belonged to (d4): 1. a god; 2. the enemy; 3. a version of its holder; 4. nobody, and that is the strange part",
      "It can do one more thing, one great thing, once, and is saving it.",
      "It does not know what it is either. It is improvising too.",
      "Everything it does costs someone, somewhere, a little. It knows who.",
    ],
  },
  {
    title: "d12 A true name part",
    id: "d12truenamefirst_magicitems",
    roll: [
      "Vael",
      "Morn",
      "Isk",
      "Thara",
      "Ond",
      "Sever",
      "Lumen",
      "Croes",
      "Ashai",
      "Ferrun",
      "Ninth",
      "Ul",
    ],
  },
  {
    title: "d12 and the rest of it",
    id: "d12truenamesecond_magicitems",
    roll: [
      "adine",
      "ghast",
      "welt",
      "orim",
      "essa",
      "und",
      "ivar",
      "moth",
      "ekh",
      "auro",
      "ilis",
      "then",
    ],
  },
  {
    title: "d10 Spoken aloud, the name",
    id: "d10truenamepower_magicitems",
    roll: [
      "Wakes every power the item has, at once, for one held breath.",
      "Commands the item absolutely, once per speaker, ever.",
      "Is heard by the item's maker, wherever they now are.",
      "Undoes the item's curse for a day, and doubles it if wasted.",
      "Calls the item to the speaker's hand from any distance.",
      "Puts the item to sleep so deep it will pass every test as mundane.",
      "Costs the speaker a year of memory and grants a year of the item's.",
      "Opens whatever the speaker is facing: door, lock, negotiation, heart.",
      "Frightens the item. Nobody knows why. It will not discuss it.",
      "Does nothing, unless spoken by the person it was made for, who exists.",
    ],
  },
  {
    title: "d12 The destiny",
    id: "d12destiny_magicitems",
    roll: [
      "It will be present at the death of a monarch. Present, not idle.",
      "It is meant to break, once, at the only moment breaking helps.",
      "It will return to its maker's forge, which no longer exists, so something must change.",
      "Someone not yet born will do the thing everyone failed at, holding it.",
      "It is owed one great theft, as the stolen party.",
      "It will end a war. Which end of the war is the open question.",
      "It must be under (d4): 1. the mountain; 2. the throne; 3. the flood line; 4. the last tree, when the bells ring.",
      "It has an appointment with its twin, edge to edge.",
      "Its seventh owner matters. Count carefully. Counts differ.",
      "It will be offered to a god, and the interesting part is the refusal.",
      "It carries a message it has not delivered yet. It does not know it is carrying one.",
      "The prophecy about it is wrong in one word, and the word is load-bearing.",
    ],
  },
  {
    title: "d10 The omen already seen",
    id: "d10destinysign_magicitems",
    roll: [
      "Birds go quiet when it is unwrapped. All birds. Every time.",
      "It has begun appearing in the dreams of strangers, who describe it exactly.",
      "Its inscription has one more word than it did at the last reading.",
      "A blind elder touched it and addressed it by a name nobody present knew.",
      "It was drawn, precisely, in a fresco painted four centuries ago.",
      "Compass needles bow to it, briefly, like courtiers.",
      "The last three storms have circled the house it sleeps in.",
      "A child asked it a question and waited, as if that were normal, and it was.",
      "Its reflection sometimes shows it (d4): 1. whole; 2. broken; 3. burning; 4. held by someone else",
      "Somewhere, a bell rings when it changes hands. The bell has been found.",
    ],
  },
  {
    title: "d12 Its set-sibling",
    id: "d12setsibling_magicitems",
    roll: [
      "Hangs in a throne room, believed a replica, wrongly.",
      "Lies in a riverbed, patient as only objects are.",
      "Was buried with a hero and is the reason the barrow is avoided.",
      "Serves a farm family who have no idea, as a very good ordinary thing.",
      "Is in a collection, catalogued, insured and screaming quietly.",
      "Travels with a caravan that never quite reaches this town.",
      "Was melted down, and the metal remembers, and the coins are circulating.",
      "Sits in a pawnshop window three streets from wherever this one is. Always three streets.",
      "Is held by someone who knows about this one and has started walking.",
      "Was taken (d4): 1. below; 2. across the sea; 3. into the mountain; 4. by the birds",
      "Is lost even to the set, and both of them are looking.",
      "No longer exists, and the set's purpose now rests entirely on this one.",
    ],
  },
  {
    title: "d10 Together, the set",
    id: "d10setpurpose_magicitems",
    roll: [
      "Opens something sealed by their maker, sealed for excellent reasons.",
      "Ends the working their maker could not end alone.",
      "Becomes one item, the true item, of which these are the pieces.",
      "Can be traded, complete, for one impossible thing. The buyer is known.",
      "Wakes fully: each is a fraction of one sleeping mind.",
      "Marks the corners of somewhere that only exists when all are placed.",
      "Cancels each other out, which is the entire point: they are a containment.",
      "Grants their holder a title older than any crown.",
      "Sings. That is all. Witnesses of the last complete singing wrote nothing down afterwards, ever again.",
      "Must never be assembled, per the maker's last letter, which explains nothing.",
    ],
  },
  {
    title: "d10 It is becoming",
    id: "d10becoming_magicitems",
    roll: [
      "Heavier, by grains a week, toward some final weight it seems sure of.",
      "More specific: a plain blade growing engravings, letter by letter.",
      "Alive. Warmth first. Lately, a pulse when it thinks no one is holding it.",
      "A door. Its reflection no longer matches, and the mismatch has hinges.",
      "Younger, undoing its own history year by year toward its making day, and whatever that day held.",
      "Louder in dreams: its holders sleepwalk toward the same horizon.",
      "Something its maker feared: the design was a cage, and the cage is wearing thin.",
      "Two things. It is thickening at the middle, preparing, perhaps, to be a set.",
      "Honest. Its glamours are failing one by one, and what is underneath is (d4): 1. better; 2. worse; 3. older; 4. someone's",
      "Finished. It was always incomplete, and it has finally found the missing part nearby.",
    ],
  },

  /* ------------------------------------------------------------------
   * The gated tangents (sub_rolls entries). percent_to is the chance the
   * whole block appears at all; the "type" gates then pick a variant whose
   * own main_rolls decide which leaf tables get consulted.
   * ---------------------------------------------------------------- */
  {
    title: "Its history",
    singular: "Chapter",
    id: "gatehistory_magicitems",
    roll_type: "type",
    number: "1d2",
    percent_to: "75",
    percent_of: "100",
    roll: [
      {
        title: "Its making",
        main_rolls: [
          "magicitems/d16maker_magicitems",
          "magicitems/d12madefor_magicitems",
          "magicitems/d10age_magicitems",
        ],
        sub_rolls: [],
      },
      {
        title: "Hands it has passed through",
        main_rolls: [
          "magicitems/d14formerowner_magicitems",
          "magicitems/d12fate_magicitems",
        ],
        sub_rolls: [],
      },
      {
        title: "A gap in the record",
        main_rolls: [
          "magicitems/d10age_magicitems",
          "magicitems/d12fate_magicitems",
        ],
        sub_rolls: [],
      },
      {
        title: "The story everyone tells about it, which is wrong",
        main_rolls: [
          "magicitems/d14formerowner_magicitems",
          "magicitems/d12madefor_magicitems",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "A harmless habit",
    singular: "Quirk",
    id: "gatequirk_magicitems",
    roll_type: "amount",
    number: "1d1",
    percent_to: "60",
    percent_of: "100",
    rolls: ["magicitems/d20quirk_magicitems"],
  },
  {
    title: "A lesser power",
    singular: "Also",
    id: "gatesecondary_magicitems",
    roll_type: "amount",
    number: "1d1",
    percent_to: "40",
    percent_of: "100",
    rolls: ["magicitems/d16secondarypower_magicitems"],
  },
  {
    title: "The price of use",
    singular: "Cost",
    id: "gatecost_magicitems",
    roll_type: "amount",
    number: "1d1",
    percent_to: "30",
    percent_of: "100",
    rolls: ["magicitems/d16usecost_magicitems"],
  },
  {
    title: "It demands",
    singular: "Attunement",
    id: "gateattunement_magicitems",
    roll_type: "amount",
    number: "1d1",
    percent_to: "25",
    percent_of: "100",
    rolls: ["magicitems/d12attunement_magicitems"],
  },
  {
    title: "It is cursed",
    singular: "Curse",
    id: "gatecurse_magicitems",
    roll_type: "type",
    number: "1d1",
    percent_to: "20",
    percent_of: "100",
    roll: [
      {
        title: "A curse of appetite: the item consumes, and the owner provides",
        main_rolls: [
          "magicitems/d12cursetrigger_magicitems",
          "magicitems/d10curselift_magicitems",
        ],
        sub_rolls: [],
      },
      {
        title: "A curse of attention: things notice the owner that should not",
        main_rolls: [
          "magicitems/d12cursetrigger_magicitems",
          "magicitems/d10curselift_magicitems",
        ],
        sub_rolls: [],
      },
      {
        title: "A curse of exchange: every gift of the item is paid for elsewhere",
        main_rolls: [
          "magicitems/d12cursetrigger_magicitems",
          "magicitems/d10curselift_magicitems",
        ],
        sub_rolls: [],
      },
      {
        title: "A curse of honesty: the owner's secrets work loose, one by one",
        main_rolls: [
          "magicitems/d12cursetrigger_magicitems",
          "magicitems/d10curselift_magicitems",
        ],
        sub_rolls: [],
      },
      {
        title: "A curse of weather: the sky holds a grudge against the owner",
        main_rolls: [
          "magicitems/d12cursetrigger_magicitems",
          "magicitems/d10curselift_magicitems",
        ],
        sub_rolls: [],
      },
      {
        title: "A slow curse: nothing yet, and everyone who owned it says nothing yet",
        main_rolls: [
          "magicitems/d12cursetrigger_magicitems",
          "magicitems/d10curselift_magicitems",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "Someone is looking for it",
    singular: "Seeker",
    id: "gatewanted_magicitems",
    roll_type: "type",
    number: "1d1",
    percent_to: "12",
    percent_of: "100",
    roll: [
      {
        title: "An open pursuit",
        main_rolls: [
          "magicitems/d12seeker_magicitems",
          "magicitems/d10seekerwhy_magicitems",
          "magicitems/d10seekermethod_magicitems",
        ],
        sub_rolls: [],
      },
      {
        title: "A quiet pursuit, unnoticed so far",
        main_rolls: [
          "magicitems/d12seeker_magicitems",
          "magicitems/d10seekerwhy_magicitems",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "It is awake",
    singular: "Mind",
    id: "gatesentience_magicitems",
    roll_type: "type",
    number: "1d1",
    percent_to: "10",
    percent_of: "100",
    roll: [
      {
        title: "Imperious: it considers itself the owner in this arrangement",
        main_rolls: [
          "magicitems/d12voice_magicitems",
          "magicitems/d10intellect_magicitems",
          "magicitems/d12itwants_magicitems",
          "magicitems/d10itrefuses_magicitems",
        ],
        sub_rolls: [],
      },
      {
        title: "Lonely: centuries in the dark, and now it will not stop talking",
        main_rolls: [
          "magicitems/d12voice_magicitems",
          "magicitems/d12itwants_magicitems",
          "magicitems/d12itssecret_magicitems",
        ],
        sub_rolls: [],
      },
      {
        title: "Fanatic: made for a cause, and the cause is not finished",
        main_rolls: [
          "magicitems/d12voice_magicitems",
          "magicitems/d10intellect_magicitems",
          "magicitems/d12itwants_magicitems",
          "magicitems/d12itssecret_magicitems",
        ],
        sub_rolls: [],
      },
      {
        title: "Deceitful: charming, helpful, and playing a longer game",
        main_rolls: [
          "magicitems/d12voice_magicitems",
          "magicitems/d10intellect_magicitems",
          "magicitems/d12itssecret_magicitems",
        ],
        sub_rolls: [],
      },
      {
        title: "Faded: mostly asleep, surfacing in fragments",
        main_rolls: [
          "magicitems/d12voice_magicitems",
          "magicitems/d12itwants_magicitems",
          "magicitems/d10itrefuses_magicitems",
        ],
        sub_rolls: [],
      },
      {
        title: "Gentle: a good mind in a strange house, doing its best",
        main_rolls: [
          "magicitems/d12voice_magicitems",
          "magicitems/d10intellect_magicitems",
          "magicitems/d12itwants_magicitems",
          "magicitems/d10itrefuses_magicitems",
          "magicitems/d12itssecret_magicitems",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "It is more than it seems",
    singular: "Legend",
    id: "gatelegendary_magicitems",
    roll_type: "type",
    number: "1d1",
    percent_to: "8",
    percent_of: "100",
    roll: [
      {
        title: "It has a true name",
        main_rolls: [
          "magicitems/d12truenamefirst_magicitems",
          "magicitems/d12truenamesecond_magicitems",
          "magicitems/d10truenamepower_magicitems",
        ],
        sub_rolls: [],
      },
      {
        title: "It has a destiny",
        main_rolls: [
          "magicitems/d12destiny_magicitems",
          "magicitems/d10destinysign_magicitems",
        ],
        sub_rolls: [],
      },
      {
        title: "It is one of a set of (d4): 1. two; 2. three; 3. five; 4. seven",
        main_rolls: [
          "magicitems/d12setsibling_magicitems",
          "magicitems/d10setpurpose_magicitems",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "And it is changing",
    singular: "Metamorphosis",
    id: "gatebecoming_magicitems",
    roll_type: "amount",
    number: "1d1",
    percent_to: "5",
    percent_of: "100",
    rolls: ["magicitems/d10becoming_magicitems"],
  },

  /* ------------------------------------------------------------------
   * Leaf tables for the simple gates
   * ---------------------------------------------------------------- */
  {
    title: "d20 Quirk",
    id: "d20quirk_magicitems",
    roll: [
      "It purrs, very faintly, when polished.",
      "Moths attend it. They do no harm. They simply attend.",
      "It is always the first thing found when rummaging, whatever was sought.",
      "Left overnight, it aligns itself to face the door.",
      "It sours milk in the same room, and improves cheese.",
      "Its reflection is better dressed than it is.",
      "Rain will not fall on it. An umbrella's width, no more.",
      "It creaks contentedly near fires, like an old dog settling.",
      "Children can always tell what it is. Adults never can.",
      "It comes up in dreams of everyone who sleeps within ten feet, as a background object.",
      "Any knot tied around it unties by morning, respectfully.",
      "It smells of baking on holy days. Nobody's calendar agrees which ones.",
      "Songs sung near it stay in the singer's head for exactly nine days.",
      "It is always at the temperature of a held hand, even fresh from snow.",
      "Spiders will not web on it, and leave a courteous margin.",
      "Its weight in the pack is noticeable only when its owner doubts it.",
      "Written down, its name attracts (d4): 1. inkblots; 2. marginalia in unknown hands; 3. misfiling; 4. very specific junk mail",
      "It hums the last song it heard, barely, in the right key.",
      "Salt spilled near it falls in the same pattern every time.",
      "Cats treat it as a senior colleague.",
    ],
  },
  {
    title: "d16 A lesser power",
    id: "d16secondarypower_magicitems",
    roll: [
      "It keeps its owner's hands warm, and steady, which is the useful half.",
      "Once a day it can find the nearest (d4): 1. fresh water; 2. locked thing; 3. lie; 4. grave",
      "Wounds bound with or near it close a day early.",
      "It can hold one spoken sentence and repeat it, once, later, verbatim.",
      "Food eaten in its presence keeps a traveller fed half a day longer.",
      "It never lets its owner get fully lost: home is always vaguely that way.",
      "Small fires light easily near it; large ones behave.",
      "It gives one clear hour of thought per day, on request. Choose the hour well.",
      "Its owner's handwriting becomes legible, even to physicians.",
      "It can carry a whisper across a crowded room to a named ear.",
      "Vermin keep two rooms' distance.",
      "The owner always wakes at the hour they meant to, to the minute.",
      "It remembers faces for its owner, and warms in the presence of one seen before.",
      "Rope, thread and chain handled with it refuse to snap at the worst moment.",
      "It makes any room it is displayed in slightly easier to be honest in.",
      "Coin kept touching it is never counterfeit. Coin. Singular. It has limits.",
    ],
  },
  {
    title: "d16 The cost",
    id: "d16usecost_magicitems",
    roll: [
      "A pinch of salt, thrown over the shoulder. It is traditional and it is enforced.",
      "One true thing, spoken aloud, that the speaker has never said before.",
      "A night's dreams, taken whole. The sleep itself is untouched.",
      "The user's shadow, for a day. People notice more than you would think.",
      "A drop of blood, or three hairs, or a tooth. It escalates only if bargained with.",
      "The next hour of luck. Small things fumble and slip until it is paid off.",
      "A memory of the item itself: each use, the user forgets one earlier use.",
      "Warmth: the user is cold for as many hours as the power worked minutes.",
      "A coin, which must be (d4): 1. silver; 2. old; 3. earned honestly; 4. someone else's, given freely",
      "The user's name, unusable for a day. People's eyes slide past introductions.",
      "Appetite, sleep or patience. It takes whichever is most inconvenient.",
      "A promise, small but binding, collected at the item's discretion.",
      "One year off the far end of something: a rope, a roof, a friendship. It does not say which.",
      "Song: the user must sing, alone, within a day, or the power sulks.",
      "The pain it prevented, delivered later, in instalments, at rest.",
      "Nothing the user will miss. That is the item's phrasing, and it is technically honest.",
    ],
  },
  {
    title: "d12 Attunement",
    id: "d12attunement_magicitems",
    roll: [
      "Sleep beside it for three nights. It examines the dreams and decides.",
      "Tell it your worst act, aloud, alone. It never repeats things. Probably.",
      "Carry it a hundred miles without once using it.",
      "Be given it. It cannot be taken, bought or found into loyalty.",
      "Bleed on it once, deliberately, without being asked.",
      "Beat its previous owner at (d4): 1. cards; 2. riddles; 3. drinking; 4. mourning",
      "Repair something in its presence, well, for someone else.",
      "Wear or hold it through one entire storm, outdoors, start to finish.",
      "Learn its history and recite it back. It corrects errors. There will be errors.",
      "Fast for a day within arm's reach of it.",
      "Refuse it once. It respects nothing so much as being put down firmly.",
      "Nothing. It attunes instantly, which everyone who studies these finds deeply improper.",
    ],
  },
];
