// scrolls.js
//
// Random Scroll: one click gives a whole readable object, not just a spell name.
//
// The form is picked from six category tables, so a vellum roll and a line of
// knotted cord are described by different lists. Twelve facets always roll: the
// hand, the ink, the script, the casing, the condition, the working itself, what
// reading it asks for, what happens mid-reading, what is left afterwards, its
// worth and where it came from. Then ten tangents are chance-gated through
// percent_to, from a 70% margin note down to a 6% "this is not a spell at all",
// and each gate rolls a variant that consults its own leaf tables, so two
// scrolls rarely share the shape of their entry.

top.scrolls = [
  /* ------------------------------------------------------------------
   * Form: one of these six is picked per scroll
   * ---------------------------------------------------------------- */
  {
    title: "d12 Form - a parchment roll",
    id: "d12formparchment_scrolls",
    roll: [
      "A single sheet of calfskin vellum, rolled tight and tied with a boot lace.",
      "Three sheets stitched end to end, the stitching finer than the writing.",
      "A long roll wound on two rods of black wood, read by turning both.",
      "Sheepskin, greasy to the touch, the flesh side left deliberately rough.",
      "A scrap torn from something larger, the tear old and the edge softened by handling.",
      "Vellum so thin the words show through backwards from the other side.",
      "A roll that has been stored the wrong way so long it will not lie flat.",
      "Goatskin cut in a long spiral from one hide, so the text winds inward.",
      "A sheet with a stitched repair across the middle, right through a line of text.",
      "Parchment scraped and reused, the ghost of a tax record under the spell.",
      "A sheet with the maker's hair still caught in the surface, one strand, white.",
      "A roll that smells faintly of (d4): 1. woodsmoke; 2. the sea; 3. lamp oil; 4. a sickroom",
    ],
  },
  {
    title: "d10 Form - a folded document",
    id: "d10formfolded_scrolls",
    roll: [
      "A letter folded in eight, addressed to nobody, the spell written where the greeting belongs.",
      "A folio lifted out of a book, its stitch holes still open along one edge.",
      "A map, and the working is written on the back across the empty ocean.",
      "A pamphlet of four leaves, badly printed, the spell hand-corrected throughout.",
      "A ledger page, the columns of figures crossed out and written over.",
      "A folded paper bird that has to be undone to be read, and refolds itself badly.",
      "A ship's chart folded to pocket size, salt-stiff at every crease.",
      "A playbill for a performance that was cancelled, the spell in the cast list.",
      "A legal writ with the seals still attached, the working hidden in the clauses.",
      "A page folded so many times it opens in a set order, and the wrong order (d4): 1. skips a line; 2. spoils the working; 3. reads as a different spell; 4. tears it",
    ],
  },
  {
    title: "d10 Form - not written on paper",
    id: "d10formnotpaper_scrolls",
    roll: [
      "A sheet of tin foil, the words punched through rather than inked.",
      "A strip of thin copper, rolled and slotted into a lead tube like a curse tablet.",
      "A silk banner as long as an arm, meant to be read while it hangs.",
      "A clay tablet, still slightly damp somehow, the marks pressed and not scratched.",
      "A length of birch bark peeled in one piece, curling at both ends.",
      "A cord of forty knots, and the knots are the text.",
      "A wax tablet in a wooden frame, the words cut deep enough to survive being smoothed.",
      "A flat slab of shale, scratched, cold, and heavier than any scroll should be.",
      "A sheet of pressed and dried leaves, the veins arranged into letters.",
      "A strip of tanned skin that is (d4): 1. not any animal; 2. clearly human; 3. tattooed, then taken; 4. still faintly warm",
    ],
  },
  {
    title: "d10 Form - worn or carried",
    id: "d10formworn_scrolls",
    roll: [
      "A tattoo across a forearm, and the arm is no longer attached to anyone.",
      "A prayer flag, weathered pale, the working legible only in raking light.",
      "A sash embroidered with the words, front and back, in two colours of thread.",
      "A pilgrim's ribbon wound round a hat, unwound to be read.",
      "The lining of a coat, written on before the coat was ever sewn.",
      "A bandage, laundered and reused, the ink surviving every wash.",
      "A shroud strip, cut narrow, from a burial that somebody interrupted.",
      "A belt of woven horsehair with the script worked into the pattern.",
      "A pair of gloves, one word to a finger, read by making the gestures.",
      "A veil of gauze, and reading it means (d4): 1. wearing it; 2. holding it to the light; 3. burning it; 4. looking through it at someone",
    ],
  },
  {
    title: "d10 Form - the case comes first",
    id: "d10formcase_scrolls",
    roll: [
      "A bone tube capped at both ends with wax, the scroll inside almost an afterthought.",
      "A brass cylinder engraved with a warning in a language nobody at the table reads.",
      "A leather case moulded to fit a scroll thicker than the one it holds.",
      "A lacquered box lined with red felt, the felt worn in the shape of two scrolls.",
      "A hollowed walking stick, the scroll drawn out of the handle end.",
      "A glass tube sealed at both ends, and the scroll cannot be removed unbroken.",
      "A reliquary with a saint's name on it and no saint inside.",
      "A quiver of six tubes, five empty, one heavy.",
      "A sealed jar of oil, the scroll suspended in it and perfectly legible.",
      "An iron case, welded shut, with a slot cut for reading (d4): 1. one line at a time; 2. by lamplight only; 3. from the wrong end; 4. by someone with smaller hands",
    ],
  },
  {
    title: "d12 Form - written in haste",
    id: "d12formhaste_scrolls",
    roll: [
      "A scrawl on the back of a tavern bill, the total still legible underneath.",
      "Chalk on a slate, smudged at one corner and never repaired.",
      "A shirt cuff, torn off at the seam and written on in something dark.",
      "A page from a prayer book, the spell squeezed into the margins all round.",
      "A wanted poster, the face crossed out, the working over the reward.",
      "Charcoal on a plank, pried off a wall and carried away whole.",
      "A supply manifest with the spell continuing down the quantity column.",
      "The flyleaf of a stolen novel, the story's last page missing.",
      "A love letter, unfinished, the working starting mid-sentence.",
      "A field bandage wrapper, written on while the writer was clearly bleeding.",
      "A gambling marker for a debt of nine silver, the spell on the reverse.",
      "A child's copybook page, the alphabet above and the working below, in (d4): 1. the same hand; 2. two hands; 3. a hand that gets steadier; 4. a hand that gets worse",
    ],
  },

  /* ------------------------------------------------------------------
   * The spine: these always roll
   * ---------------------------------------------------------------- */
  {
    title: "d20 The hand",
    id: "d20hand_scrolls",
    roll: [
      "A clerk's hand, beautiful and bored, every letter identical.",
      "A scholar's hand, cramped, abbreviating everything it can.",
      "A shaking hand that steadies halfway down and shakes again at the end.",
      "Left-handed, smeared along every line, and the writer did not care.",
      "A trained hand copying a script it does not understand, letter by letter.",
      "Enormous letters, six words to the sheet, as if for failing eyes.",
      "Tiny and cramped, and requiring a lens that is not included.",
      "A hand that starts formal and degenerates into notes to itself.",
      "Two hands taking turns, one confident, one learning.",
      "A hand that never lifts: the whole working is one unbroken line.",
      "Printed letters, deliberately anonymous, the way ransom notes are printed.",
      "A drunk's hand, sloping downhill, blotted at three points.",
      "A dying hand, the last four words pressed hard enough to score the surface.",
      "A hand that writes right to left, so the working is read in a mirror.",
      "Calligraphy so ornate the words are decoration first and instructions second.",
      "A hand identical to the reader's own, which is not a comfort.",
      "A hurried hand that abandons vowels entirely after the first paragraph.",
      "A hand that has been corrected throughout by a second, harsher hand.",
      "A hand that presses so lightly the text fades in warm rooms.",
      "A hand that is (d4): 1. familiar; 2. your teacher's; 3. changing as you read; 4. not a hand at all",
    ],
  },
  {
    title: "d20 The ink",
    id: "d20ink_scrolls",
    roll: [
      "Oak gall ink, browned with age, biting slightly into the surface.",
      "Lamp black, matte and dead flat, the cheapest ink there is.",
      "Iron ink that has eaten through the sheet at every heavy stroke.",
      "Silver, tarnished black except where a thumb has polished it.",
      "Gold leaf on the first letter only, and then plain ink forever after.",
      "Cinnabar red, expensive, and used for the whole text like a boast.",
      "Cuttlefish brown, and the writing smells of low tide in damp weather.",
      "Blood, dried to brown, and not enough of it to have been fatal.",
      "Blood, and far too much of it for the writer to have walked away.",
      "Ink mixed with ash, gritty under the fingertip.",
      "Something luminous that is only readable in the dark.",
      "Ink that is faintly warm, always, whatever the weather.",
      "A green that no local dyer can match or name.",
      "Ink that has separated with age into two colours, one over the other.",
      "White ink on a dark ground, and the sheet was dyed for the purpose.",
      "No ink at all: the letters are scorched in with a hot wire.",
      "No ink at all: the letters are pricked through, and read by light behind.",
      "Ink that beads and refuses the surface, so every letter sits proud of it.",
      "Ink that is drying still, after however many years this thing has existed.",
      "Ink that (d4): 1. runs uphill if the sheet is tilted; 2. is one word short; 3. tastes of iron; 4. is not there in the mornings",
    ],
  },
  {
    title: "d12 The script",
    id: "d12script_scrolls",
    roll: [
      "Common trade script, plain and disappointingly readable.",
      "A liturgical script, formal, three centuries out of fashion.",
      "A cipher, and the key is not with the scroll.",
      "A cipher, and the key is written along the very edge of the same sheet.",
      "A shorthand invented by one person for their own use.",
      "Notation rather than words: the working is scored like music.",
      "Diagrams and arrows, with words only at the joins.",
      "A dead script that only temple archivists still read.",
      "Two scripts interleaved line by line, and both are needed.",
      "Pictograms, and reading them aloud is impossible, which is rather the point.",
      "A script that reads correctly in any language the reader knows, which unsettles most readers.",
      "A script that changes as it is read, settling into (d4): 1. the reader's mother tongue; 2. their teacher's; 3. a language they have never heard; 4. nothing at all, at the last line",
    ],
  },
  {
    title: "d12 How it is kept",
    id: "d12keeping_scrolls",
    roll: [
      "Loose, unprotected, and honestly lucky to have survived.",
      "Tied with a ribbon that has been retied many times, badly.",
      "Sealed with wax bearing a sigil nobody present recognises.",
      "Sealed with wax that has been broken and carefully reset.",
      "Bound with a strip of lead, stamped along its length.",
      "Wrapped in oilcloth, then in linen, then in a scrap of blanket.",
      "Pinned shut with a thorn that grows nowhere near here.",
      "Kept flat between two boards and strapped, the way maps are carried.",
      "Rolled inside another, larger, entirely blank scroll.",
      "In a case worth more than the working inside it.",
      "Chained to its case, and the chain is longer than the reader expects.",
      "Kept with (d4): 1. a dried flower; 2. a lock of hair; 3. a receipt; 4. one small key",
    ],
  },
  {
    title: "d12 Condition",
    id: "d12condition_scrolls",
    roll: [
      "Immaculate, which suggests it has never once been used.",
      "Well handled and well cared for: the mark of a working caster.",
      "Water damaged along one edge, three words lost, none of them critical.",
      "Water damaged through the middle, and one word is now a guess.",
      "Scorched at one corner, as if snatched out of a fire in a hurry.",
      "Chewed at the bottom edge by something with very small teeth.",
      "Mouldy, and the mould has grown in a line that follows the text.",
      "Brittle enough that unrolling it fully is a real decision.",
      "Repaired, expertly, by someone who knew what they were repairing.",
      "Repaired badly, with a patch that covers part of the working.",
      "Stained with a hand print, in the writer's own ink, near the last line.",
      "Perfect except that it is (d4): 1. cold; 2. damp; 3. shorter than its case; 4. warm on one side",
    ],
  },
  {
    title: "d30 The working",
    id: "d30working_scrolls",
    roll: [
      "It opens any one lock, once, and the lock remembers being opened.",
      "It puts every living thing within a stone's throw to sleep, the reader included if they finish the last word.",
      "It calls a wind strong enough to move a small ship, or flatten a market stall.",
      "It heals one wound completely and leaves the scar somewhere else on the body.",
      "It shows the reader the place the scroll was written, as it is right now.",
      "It makes one lie sound true for as long as the speaker keeps talking.",
      "It stops a single heart for a count of ten. Whose is up to the reader.",
      "It preserves food, water, or a corpse for a year and a day.",
      "It summons the writer's servant, who is patient, competent and long overdue for release.",
      "It renders a door, a wall, or a person impassable until dawn.",
      "It answers one question truthfully, in a voice everyone nearby can hear.",
      "It carries the reader and what they hold to the last place they slept safely.",
      "It sets a fire that burns without fuel until it is spoken to.",
      "It makes the reader unmemorable for a day: real, present, and impossible to describe afterwards.",
      "It mends one broken object perfectly, including things that were broken for good reason.",
      "It turns aside one blow, whichever blow the reader is least ready for.",
      "It calls rain over a farm's width of ground, and cannot be told when to stop.",
      "It shows every hidden thing in a room, including the ones the party brought in.",
      "It binds two people to feel each other's pain until one says the other's true name.",
      "It lets the reader breathe and speak underwater until the tide turns.",
      "It makes a written contract magically binding, whatever the contract says.",
      "It raises a rough wall of packed earth wherever the reader points.",
      "It quiets one thing forever: a ghost, a bell, a rumour, a witness.",
      "It shows the reader their own death, badly lit and out of order.",
      "It makes one creature obey one instruction, provided the instruction is short.",
      "It puts out every flame within a bowshot, including the sun's reflection on water.",
      "It takes a memory out of a willing head and fixes it into an object.",
      "It walks the reader through a wall, once, and the wall must be less than a foot thick.",
      "It curses whoever the reader names: mildly, permanently and pettily.",
      "It does exactly what the title claims, except that the effect (d4): 1. lasts an hour; 2. lasts a year; 3. lands on the wrong target; 4. happens twice",
    ],
  },
  {
    title: "d12 Reading it asks for",
    id: "d12requires_scrolls",
    roll: [
      "Nothing but a voice. Anyone who can read the script can fire it.",
      "Training: an untrained reader gets sound, a nosebleed and nothing else.",
      "Being spoken aloud, all of it, without stopping for breath in the wrong place.",
      "Silence around the reader: a single interruption spoils the working.",
      "Daylight, direct, on the sheet itself.",
      "Darkness, complete, so the reader must already know the words.",
      "Two voices at once, in step.",
      "Blood, a drop, offered at the mark left for it.",
      "Standing in running water, or rain, or a downpour of anything.",
      "The reader's own name written at the foot before the working will take.",
      "Being burned as it is read, so the last line is spoken to ash.",
      "That the reader (d4): 1. has not eaten today; 2. is not lying about why they want it; 3. is bleeding already; 4. is alone",
    ],
  },
  {
    title: "d16 As it is read",
    id: "d16asread_scrolls",
    roll: [
      "The letters lift off the sheet and go out like sparks, one by one.",
      "The reader's voice is not their own from the third line onward.",
      "Everything within arm's reach cools until the reader can see their breath.",
      "The ink runs upward off the top edge and is gone.",
      "A second voice reads along, half a beat behind, from nowhere in the room.",
      "Every dog, bird and rat nearby goes silent, and stays silent afterwards.",
      "The reader's hands go numb from the fingertips inward.",
      "Candles bend toward the sheet as though it were drawing air.",
      "The sheet grows heavy, and by the last line it takes two hands.",
      "The words come out in the wrong order and arrive in the right one anyway.",
      "Someone else in the room remembers the words as though they wrote them.",
      "It smells suddenly of the room it was written in: smoke, damp, tallow.",
      "The reader ages a night's worth of tiredness in eight seconds.",
      "Nothing at all happens until the very last syllable, which is worse.",
      "The reader weeps, without feeling anything to weep about.",
      "Something in the reader's pack (d4): 1. gets warm; 2. answers; 3. goes missing; 4. is suddenly one item heavier",
    ],
  },
  {
    title: "d10 What is left afterwards",
    id: "d10afterwards_scrolls",
    roll: [
      "A blank sheet: perfectly good material, and worth keeping.",
      "Ash, and only ash, and not much of it.",
      "The sheet survives with the working faded to a legible ghost, unusable but copyable.",
      "The words remain and the power does not: it can be studied but never fired again.",
      "It reverses itself into a different, weaker spell, permanently.",
      "It crumbles to powder over the next hour, slowly enough to be watched.",
      "Nothing is left, and the case it came from is warm for a day.",
      "The sheet is intact, and one word has vanished from it.",
      "It can be read again exactly once, and there is no way to know that until then.",
      "The sheet is blank and (d4): 1. slowly refilling; 2. warm; 3. in someone else's handwriting now; 4. worth more empty",
    ],
  },
  {
    title: "d12 What it is worth",
    id: "d12worth_scrolls",
    roll: [
      "A few silver: any hedge-scribe could copy it in an afternoon.",
      "A week's wages, and most of that is the vellum.",
      "Twenty gold to the right buyer, five to the wrong one.",
      "More than the party has, which is why the seller is nervous.",
      "Nothing in coin. It is valuable to one household, and priceless there.",
      "Whatever a desperate person happens to be holding at the time.",
      "The price of a horse, and every scribe in town quotes that same figure, which is suspicious.",
      "Enough that carrying it openly is a decision rather than an oversight.",
      "Worthless as a spell and valuable as evidence.",
      "A fortune, if it is genuine, and nobody local can say whether it is.",
      "One favour from someone who does not give favours.",
      "It is worth (d4): 1. a title; 2. a pardon; 3. a life; 4. exactly what the last owner paid, which was too much",
    ],
  },
  {
    title: "d16 Where it came from",
    id: "d16provenance_scrolls",
    roll: [
      "Copied in a temple scriptorium, one of forty made that winter.",
      "Written by a court wizard for a patron who never collected it.",
      "Cut out of a larger grimoire, and that grimoire is still out there missing a page.",
      "Made by a student as an examination piece, and it passed.",
      "Made by a student as an examination piece, and it did not.",
      "Looted from a battlefield chaplain's satchel, along with letters nobody delivered.",
      "Bought legitimately, with a receipt, from a shop that has since burned down.",
      "Found walled into a chimney breast during a repair.",
      "Won at cards by someone who did not know what they were winning.",
      "Traded out of a caravan from far enough away that the script is foreign here.",
      "Recovered from a wreck, dry, inside a case that should not have stayed dry.",
      "Written by a prisoner, in a cell, with materials someone risked a great deal to supply.",
      "Inherited, with instructions attached that the heir chose to ignore.",
      "Taken from a body that the party did not put there.",
      "Made yesterday. The ink proves it, and nobody can say by whom.",
      "Nobody knows, and the last three owners all (d4): 1. died well; 2. died badly; 3. vanished; 4. got exactly what they wanted",
    ],
  },

  /* ------------------------------------------------------------------
   * Leaf tables: consulted by the gated tangents below
   * ---------------------------------------------------------------- */
  {
    title: "d12 The note in the margin",
    id: "d12marginnote_scrolls",
    roll: [
      "Do not read this indoors.",
      "Third line is wrong. I have not fixed it.",
      "Works. Costs more than it says.",
      "It asked me a question. Do not answer.",
      "For Anwen, when she is old enough.",
      "Twice is too many times.",
      "The last word is not a word. Say it anyway.",
      "I am sorry.",
      "Burn it after, or it comes back for the sheet.",
      "Cheaper than the funeral would have been.",
      "If your hands go cold, stop.",
      "A tally of readings, and the last mark is (d4): 1. today's date; 2. unfinished; 3. in a different hand; 4. in blood",
    ],
  },
  {
    title: "d10 Who wrote in the margin",
    id: "d10annotator_scrolls",
    roll: [
      "The original writer, years later, in a shakier version of the same hand.",
      "A tutor correcting a student, without kindness.",
      "A student correcting a tutor, and being right.",
      "A previous owner keeping accounts of every use.",
      "A censor, striking out one passage in heavy black.",
      "A child, in chalk, with a drawing of a dog.",
      "Someone who clearly could not read the script, copying its shapes.",
      "A rival, adding one line of pure spite.",
      "A translator, giving up two thirds of the way through.",
      "Whoever it was, they wrote it (d4): 1. very recently; 2. left-handed; 3. underwater, apparently; 4. in a hurry",
    ],
  },
  {
    title: "d12 The flaw",
    id: "d12flaw_scrolls",
    roll: [
      "One word is copied from a similar spell and does not belong here.",
      "A whole line is missing, and the gap is invisible unless the lines are counted.",
      "The order of two paragraphs was reversed at binding.",
      "It was copied from a copy, and the drift has compounded three times over.",
      "The final formula was never finished: it simply stops.",
      "The measure of the offering is given in a unit nobody uses now.",
      "A correction was made in the wrong place, and the original was scraped away.",
      "It works, but for a target one step to the left of the one named.",
      "The writer left out the closing entirely, on purpose, and did not say why.",
      "There is a second working buried in the first, and firing one fires both.",
      "The text is correct and the diagram is not.",
      "The flaw only shows when it is read (d4): 1. aloud; 2. in cold weather; 3. by its owner; 4. for the second time",
    ],
  },
  {
    title: "d12 When it goes wrong",
    id: "d12misfire_scrolls",
    roll: [
      "It fires at the reader instead, at half strength, which is plenty.",
      "It fires at whoever the reader was last thinking about.",
      "It works perfectly, and then works again, uninvited, at dusk.",
      "It works, and something small and unrelated in the room stops working forever.",
      "It does nothing until the reader next sleeps, and then does everything.",
      "It fires backwards: the effect undoes itself and takes a real thing with it.",
      "It fires at the correct target, in the correct way, a mile off.",
      "The sound of it carries a great distance, to exactly the wrong ears.",
      "It leaves a door open that was not there before: small, and low to the ground.",
      "The reader loses a memory of their own choosing, except they do not get to choose.",
      "It works, and the reader cannot speak until sunrise.",
      "It half fires, and the other half is (d4): 1. still waiting; 2. in the sheet; 3. in the reader; 4. following the party",
    ],
  },
  {
    title: "d12 The hidden text",
    id: "d12hiddentext_scrolls",
    roll: [
      "An earlier working, scraped off, still legible from the wrong angle.",
      "A confession, signed and dated, damaging to a family still in power.",
      "A map, drawn in the spaces between the lines.",
      "A list of names with all but two struck through.",
      "A second spell, weaker, safer, and a great deal more useful day to day.",
      "The writer's real name, hidden in the initial letters of each line.",
      "Instructions for undoing the working, written by someone who regretted it.",
      "A page of a diary with nothing to do with magic at all, and heartbreaking.",
      "A debt record naming a lender who should have died two centuries ago.",
      "A drawing of the reader. Not someone similar. The reader.",
      "A warning, in plain trade script, that the working is a lie.",
      "Confirmation that this sheet is (d4): 1. the second of three; 2. stolen; 3. a forgery; 4. the original, and every other copy is wrong",
    ],
  },
  {
    title: "d10 How the hidden text shows",
    id: "d10revealed_scrolls",
    roll: [
      "Held to a candle, from behind.",
      "Only while the sheet is damp, and it fades again as it dries.",
      "Under moonlight, and never under lamplight.",
      "When the primary working is fired, in the moment the ink lifts.",
      "When the sheet is cold enough to frost.",
      "Rubbed with charcoal dust, the way a coin is taken.",
      "When read by someone who cannot read the main script.",
      "Only in a mirror, and only in one particular mirror.",
      "After the sheet has been folded along its original creases.",
      "When it is (d4): 1. bled on; 2. read aloud badly; 3. left out overnight; 4. shown to a child",
    ],
  },
  {
    title: "d12 The set it belongs to",
    id: "d12set_scrolls",
    roll: [
      "One of three. Read out of order, they undo each other.",
      "One of seven, numbered, and this is the fifth.",
      "A pair: this is the question, and somewhere there is the answer.",
      "The last of a set, and the others were destroyed on purpose.",
      "One of a dozen made for a ritual that needs all twelve readers at once.",
      "A matched set with a book, and the scroll is the index.",
      "One of two identical copies, and only one of them works.",
      "The first of a set that was never finished.",
      "Part of a set split deliberately between three heirs who do not speak.",
      "One of a guild set, and this one is signed out to a dead member.",
      "Half a working: the other half is not a scroll at all.",
      "The rest of the set is (d4): 1. in a vault nearby; 2. burned; 3. on a ship; 4. held by the person selling this one",
    ],
  },
  {
    title: "d10 The ward on it",
    id: "d10ward_scrolls",
    roll: [
      "The seal blisters the fingers of anyone but the named owner.",
      "Opening it without the phrase releases a small, mean, unavoidable curse.",
      "It shrieks, once, loudly enough to be heard across a courtyard.",
      "The case fills with a corrosive vapour if it is forced.",
      "Anyone who reads it without permission forgets the working immediately afterwards.",
      "The ink lifts and blinds an unauthorised reader for an hour.",
      "It marks the thief: a stain on the palm that no washing shifts for a month.",
      "It tells its owner, wherever they are, the moment it is unrolled.",
      "There is a needle in the case, dosed with something old.",
      "It destroys itself if opened by (d4): 1. anyone not named on it; 2. anyone lying; 3. anyone armed; 4. the third reader",
    ],
  },
  {
    title: "d12 The curse on it",
    id: "d12curse_scrolls",
    roll: [
      "The reader's own handwriting changes, permanently, into the writer's.",
      "Every scroll the reader touches afterwards is one word harder to read.",
      "The reader cannot write a lie ever again, in any hand, on any surface.",
      "Whatever the reader reads aloud from now on is heard by one other person, far away.",
      "The reader dreams the writing of it nightly, including the parts they would rather not see.",
      "The reader's name fades out of every document that ever bore it, slowly.",
      "The working can never be used to help the reader themselves.",
      "A tally appears on the reader's forearm and counts something down.",
      "The reader will one day be asked to write the next copy, and will not be able to refuse.",
      "Ink stains one finger black and spreads a knuckle a year.",
      "The reader is now the scroll's owner in the eyes of everyone hunting it.",
      "The curse takes hold only if the reader (d4): 1. profits by it; 2. tells anyone; 3. reads it twice; 4. survives the week",
    ],
  },
  {
    title: "d12 Who wants it",
    id: "d12seeker_scrolls",
    roll: [
      "The scriptorium it was copied in, which keeps very good records.",
      "The heir of the patron who commissioned it and never received it.",
      "A collector with no scruples and a great deal of money.",
      "The writer, who is not dead, and has been looking for a long time.",
      "A guild that treats unlicensed copies as a capital matter.",
      "The family named in the confession hidden inside it.",
      "A temple that wants it destroyed rather than owned.",
      "The thief it was stolen from, who is more sympathetic than expected.",
      "Whatever the working summoned last time, still owed a service.",
      "A rival caster who needs it for the set they are assembling.",
      "A city clerk pursuing it as evidence in a case forty years cold.",
      "Someone who is (d4): 1. one day behind; 2. already here; 3. paying others to look; 4. asking politely, for now",
    ],
  },
  {
    title: "d10 How close they are",
    id: "d10howclose_scrolls",
    roll: [
      "They do not know it has surfaced. Yet.",
      "They know the region, not the town.",
      "They are asking in the town, and paying for answers.",
      "They passed through two days ago and left a description.",
      "They are in the building, and have not recognised anyone yet.",
      "They have already spoken to the party, pleasantly, about something else.",
      "They have someone watching the party's inn.",
      "They sent a letter instead of coming. It is polite and quite frightening.",
      "They are dead, and their instructions are being carried out anyway.",
      "They will arrive (d4): 1. tonight; 2. at the worst moment; 3. after it is used; 4. with help",
    ],
  },
  {
    title: "d12 How it reacts",
    id: "d12reacts_scrolls",
    roll: [
      "It warms when the right reader picks it up, and chills for anyone else.",
      "It unrolls itself a hand's width when the working would be useful.",
      "It rolls itself shut when the reader is about to make a mistake.",
      "It rustles when it is being talked about.",
      "It refuses to be read while a particular person is in the room.",
      "It moves in the pack, always ending up on top.",
      "It writes one new word overnight, once a month.",
      "It underlines a line of its own text when it wants that line used.",
      "It goes limp and heavy when a lie is told over it.",
      "It shivers before rain, before violence, or before both.",
      "It will not burn, and has clearly been tried.",
      "It answers questions by (d4): 1. curling; 2. one word appearing; 3. going cold; 4. showing the hidden text",
    ],
  },
  {
    title: "d10 What it wants",
    id: "d10itwants_scrolls",
    roll: [
      "To be read. Constantly. By anyone.",
      "To be copied, so that there are more of it.",
      "To be returned to the shelf it was taken from.",
      "To reach one specific person, whose name it will not spell out.",
      "To be destroyed properly, which takes a particular place and a rite.",
      "To be kept dry, kept quiet, and left alone.",
      "To finish the work it was made for, whatever that was.",
      "To stop the other scrolls in its set from being used.",
      "To be read once more, and then never again.",
      "To be (d4): 1. forgiven; 2. believed; 3. corrected; 4. buried with someone",
    ],
  },
  {
    title: "d12 What it actually is",
    id: "d12actuallyis_scrolls",
    roll: [
      "A forgery: convincing, well aged, and completely inert.",
      "A contract, and reading it aloud signs it.",
      "A deed to a property nobody has been able to find.",
      "A summons: reading it brings the reader before something that issues summonses.",
      "A recipe, and the working is one step in something much larger.",
      "A message, disguised as a spell so that literate people would carry it carefully.",
      "A key, and the words are the shape of it, not the sound.",
      "A test, laid by someone who is watching who passes and who does not.",
      "A trap, aimed at one specific person, and the party got in the way.",
      "A prayer, and the effect is not the caster's doing at all.",
      "A map, and the working is only there to make it worth stealing.",
      "A confession that someone (d4): 1. was hanged for; 2. was pardoned for; 3. was paid to write; 4. still denies",
    ],
  },
  {
    title: "d10 The warning on it",
    id: "d10warning_scrolls",
    roll: [
      "Do not read this while anyone you love is in the room.",
      "The cost is not paid at the time. Remember that.",
      "Two readers have died. Both were competent.",
      "It works better than it should. Ask why before you use it.",
      "The target is not always the one you name.",
      "Never read this on holy ground.",
      "Do not let it be copied. I mean this.",
      "It is not finished. I could not finish it.",
      "Whoever reads this owes what I owed.",
      "Read it (d4): 1. only once; 2. only in daylight; 3. only if you must; 4. and then run",
    ],
  },

  /* ------------------------------------------------------------------
   * The gated tangents (sub_rolls entries). percent_to is the chance the
   * whole block appears at all; the "type" gates then pick a variant whose
   * own main_rolls decide which leaf tables get consulted.
   * ---------------------------------------------------------------- */
  {
    title: "Written in the margins",
    singular: "Note",
    id: "gatemargin_scrolls",
    roll_type: "type",
    number: "1d2",
    percent_to: "70",
    percent_of: "100",
    roll: [
      {
        title: "A working note, left by someone who used it",
        main_rolls: [
          "scrolls/d12marginnote_scrolls",
          "scrolls/d10annotator_scrolls",
        ],
        sub_rolls: [],
      },
      {
        title: "A correction, and the correction may itself be wrong",
        main_rolls: [
          "scrolls/d12marginnote_scrolls",
          "scrolls/d12flaw_scrolls",
        ],
        sub_rolls: [],
      },
      {
        title: "A warning to whoever came next",
        main_rolls: [
          "scrolls/d10warning_scrolls",
          "scrolls/d10annotator_scrolls",
        ],
        sub_rolls: [],
      },
      {
        title: "Something personal, with nothing to do with the spell",
        main_rolls: [
          "scrolls/d12marginnote_scrolls",
          "scrolls/d10annotator_scrolls",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "It is not a clean copy",
    singular: "Fault",
    id: "gateflaw_scrolls",
    roll_type: "type",
    number: "1d1",
    percent_to: "35",
    percent_of: "100",
    roll: [
      {
        title: "A copyist's error, faithfully reproduced ever since",
        main_rolls: ["scrolls/d12flaw_scrolls", "scrolls/d12misfire_scrolls"],
        sub_rolls: [],
      },
      {
        title: "Damage has taken part of the working",
        main_rolls: ["scrolls/d12flaw_scrolls", "scrolls/d12misfire_scrolls"],
        sub_rolls: [],
      },
      {
        title: "It was written wrong on purpose",
        main_rolls: [
          "scrolls/d12flaw_scrolls",
          "scrolls/d10annotator_scrolls",
          "scrolls/d12misfire_scrolls",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "There is a warning on it",
    singular: "Warning",
    id: "gatewarning_scrolls",
    roll_type: "type",
    number: "1d1",
    percent_to: "30",
    percent_of: "100",
    roll: [
      {
        title: "Written across the head of the sheet, before the working begins",
        main_rolls: ["scrolls/d10warning_scrolls"],
        sub_rolls: [],
      },
      {
        title: "Added later, by a frightened hand",
        main_rolls: [
          "scrolls/d10warning_scrolls",
          "scrolls/d10annotator_scrolls",
        ],
        sub_rolls: [],
      },
      {
        title: "Cut into the case, so it is read before the scroll is",
        main_rolls: ["scrolls/d10warning_scrolls", "scrolls/d10ward_scrolls"],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "It is part of a set",
    singular: "Sheet",
    id: "gateset_scrolls",
    roll_type: "type",
    number: "1d1",
    percent_to: "25",
    percent_of: "100",
    roll: [
      {
        title: "Numbered, and the number is not one",
        main_rolls: ["scrolls/d12set_scrolls", "scrolls/d16provenance_scrolls"],
        sub_rolls: [],
      },
      {
        title: "Split between people who will not co-operate",
        main_rolls: ["scrolls/d12set_scrolls", "scrolls/d12seeker_scrolls"],
        sub_rolls: [],
      },
      {
        title: "The set is incomplete, and something is wrong because of it",
        main_rolls: ["scrolls/d12set_scrolls", "scrolls/d12misfire_scrolls"],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "Something else is written on it",
    singular: "Layer",
    id: "gatehidden_scrolls",
    roll_type: "type",
    number: "1d1",
    percent_to: "20",
    percent_of: "100",
    roll: [
      {
        title: "Under the working, from an earlier life of the sheet",
        main_rolls: [
          "scrolls/d12hiddentext_scrolls",
          "scrolls/d10revealed_scrolls",
        ],
        sub_rolls: [],
      },
      {
        title: "Hidden in the working itself, by design",
        main_rolls: [
          "scrolls/d12hiddentext_scrolls",
          "scrolls/d10revealed_scrolls",
          "scrolls/d16provenance_scrolls",
        ],
        sub_rolls: [],
      },
      {
        title: "Added after, by someone who wanted it found eventually",
        main_rolls: [
          "scrolls/d12hiddentext_scrolls",
          "scrolls/d10revealed_scrolls",
          "scrolls/d10annotator_scrolls",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "It is warded",
    singular: "Ward",
    id: "gateward_scrolls",
    roll_type: "type",
    number: "1d1",
    percent_to: "18",
    percent_of: "100",
    roll: [
      {
        title: "Locked to an owner",
        main_rolls: ["scrolls/d10ward_scrolls", "scrolls/d12seeker_scrolls"],
        sub_rolls: [],
      },
      {
        title: "Trapped, plainly and meanly",
        main_rolls: ["scrolls/d10ward_scrolls", "scrolls/d12misfire_scrolls"],
        sub_rolls: [],
      },
      {
        title: "Warded to protect the reader, not the scroll",
        main_rolls: ["scrolls/d10ward_scrolls", "scrolls/d10warning_scrolls"],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "There is a curse in the reading",
    singular: "Curse",
    id: "gatecurse_scrolls",
    roll_type: "type",
    number: "1d1",
    percent_to: "15",
    percent_of: "100",
    roll: [
      {
        title: "Laid by the writer, deliberately",
        main_rolls: ["scrolls/d12curse_scrolls", "scrolls/d16provenance_scrolls"],
        sub_rolls: [],
      },
      {
        title: "An accident of a bad copy",
        main_rolls: ["scrolls/d12curse_scrolls", "scrolls/d12flaw_scrolls"],
        sub_rolls: [],
      },
      {
        title: "Not a curse exactly: a price nobody mentioned",
        main_rolls: ["scrolls/d12curse_scrolls", "scrolls/d10warning_scrolls"],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "Somebody wants it",
    singular: "Interest",
    id: "gatewanted_scrolls",
    roll_type: "type",
    number: "1d1",
    percent_to: "12",
    percent_of: "100",
    roll: [
      {
        title: "They want it back, and consider it theirs",
        main_rolls: ["scrolls/d12seeker_scrolls", "scrolls/d10howclose_scrolls"],
        sub_rolls: [],
      },
      {
        title: "They want it destroyed",
        main_rolls: [
          "scrolls/d12seeker_scrolls",
          "scrolls/d10howclose_scrolls",
          "scrolls/d10warning_scrolls",
        ],
        sub_rolls: [],
      },
      {
        title: "They want whoever reads it, not the sheet",
        main_rolls: [
          "scrolls/d12seeker_scrolls",
          "scrolls/d10howclose_scrolls",
          "scrolls/d12curse_scrolls",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "The sheet is awake",
    singular: "Sign",
    id: "gateawake_scrolls",
    roll_type: "type",
    number: "1d1",
    percent_to: "9",
    percent_of: "100",
    roll: [
      {
        title: "Attentive: it notices readers, and prefers some of them",
        main_rolls: ["scrolls/d12reacts_scrolls", "scrolls/d10itwants_scrolls"],
        sub_rolls: [],
      },
      {
        title: "Reluctant: it does not want to be used, and says so",
        main_rolls: [
          "scrolls/d12reacts_scrolls",
          "scrolls/d10itwants_scrolls",
          "scrolls/d10warning_scrolls",
        ],
        sub_rolls: [],
      },
      {
        title: "Eager: it would like to be read far more often than is wise",
        main_rolls: [
          "scrolls/d12reacts_scrolls",
          "scrolls/d10itwants_scrolls",
          "scrolls/d12curse_scrolls",
        ],
        sub_rolls: [],
      },
      {
        title: "Faded: something of the writer is left in it, and not much",
        main_rolls: [
          "scrolls/d12reacts_scrolls",
          "scrolls/d10itwants_scrolls",
          "scrolls/d16provenance_scrolls",
        ],
        sub_rolls: [],
      },
    ],
  },
  {
    title: "It is not what it claims",
    singular: "Truth",
    id: "gatetruth_scrolls",
    roll_type: "type",
    number: "1d1",
    percent_to: "6",
    percent_of: "100",
    roll: [
      {
        title: "The working is a cover for the real document",
        main_rolls: [
          "scrolls/d12actuallyis_scrolls",
          "scrolls/d12hiddentext_scrolls",
        ],
        sub_rolls: [],
      },
      {
        title: "It is inert, and someone went to great trouble to hide that",
        main_rolls: [
          "scrolls/d12actuallyis_scrolls",
          "scrolls/d16provenance_scrolls",
        ],
        sub_rolls: [],
      },
      {
        title: "It does something, but not the thing written at the top",
        main_rolls: [
          "scrolls/d12actuallyis_scrolls",
          "scrolls/d12misfire_scrolls",
        ],
        sub_rolls: [],
      },
    ],
  },
];
