// settlements.js
//

top.settlements = [
    {
        title: "d100 Verb",
        id: "d100verb_tavernnames",
        roll: [
            "Drowning",
            "Hanging",
            "Belching",
            "Running",
            "Walking",
            "Hunting",
            "Fighting",
            "Swinging",
            "Breaking",
            "Working",
            "Fermenting",
            "Flowering",
            "Worrying",
            "Following",
            "Flowing",
            "Complaining",
            "Standing",
            "Joking",
            "Laughing",
            "Panting",
            "Boarding",
            "Lounging",
            "Cutting",
            "Singing",
            "Staring",
            "Goading",
            "Disappointing",
            "Faltering",
            "Binding",
            "Winding",
            "Sundering",
            "Longing",
            "Fumbling",
            "Bumbling",
            "Stumbling",
            "Pining",
            "Whining",
            "Flying",
            "Hoarding",
            "Whoring",
            "Warring",
            "Winking",
            "Skittering",
            "Slithering",
            "Snoring",
            "Snorting",
            "Playing",
            "Practicing",
            "Grappling",
            "Burning",
            "Flaming",
            "Freezing",
            "Poisoning",
            "Burying",
            "Throwing",
            "Sparking",
            "Steaming",
            "Smiting",
            "Chittering",
            "Chattering",
            "Mumbling",
            "Grating",
            "Plowing",
            "Biting",
            "Howling",
            "Roaring",
            "Shouting",
            "Pouring",
            "Squeaking",
            "Stinging",
            "Charging",
            "Bleating",
            "Stabbing",
            "Goring",
            "Poking",
            "Swallowing",
            "Sucking",
            "Drinking",
            "Sneaking",
            "Hiding",
            "Slashing",
            "Limping",
            "Tripping",
            "Shifting",
            "Sliding",
            "Blinding",
            "Piercing",
            "Bludgeoning",
            "Crushing",
            "Hopping",
            "Thundering",
            "Hushing",
            "Crying",
            "Wailing",
            "Mourning",
            "Darkening",
            "Piling",
            "Digging",
            "Flinging",
        ],
    },
    {
        title: "d100 Adjective",
        id: "d100adjective_tavernnames",
        roll: [
            "Quiet",
            "Jolly",
            "Good",
            "Crooked",
            "White",
            "Gray",
            "Blackened",
            "Harried",
            "Crimson",
            "Silver",
            "Golden",
            "Disturbed",
            "Filthy",
            "Ugly",
            "Bastard",
            "Faltering",
            "Glorious",
            "Beautiful",
            "Handsome",
            "Wrinkled",
            "Unhappy",
            "Intelligent",
            "Lovely",
            "Ignorant",
            "Senile",
            "Sour",
            "Sweet",
            "Lonely",
            "Green",
            "Blind",
            "Hungry",
            "Worried",
            "Educated",
            "Stupid",
            "Emboldened",
            "Honorary",
            "Stinky",
            "Bottomless",
            "Greasy",
            "Sloppy",
            "Stylish",
            "Distressed",
            "Harrowed",
            "Tormented",
            "Mortified",
            "Lopsided",
            "Broken",
            "Moldy",
            "Gooey",
            "Fermented",
            "Blighted",
            "Ornate",
            "Drowned",
            "Murdered",
            "Widowed",
            "Hanged",
            "Angry",
            "Lusty",
            "Haunted",
            "Strong",
            "Withered",
            "Comely",
            "Pious",
            "Penitent",
            "Patient",
            "Drunk",
            "Worthy",
            "Wealthy",
            "Loathsome",
            "Weak",
            "Miniscule",
            "Miniature",
            "Enormous",
            "Enlarged",
            "Engorged",
            "Lecherous",
            "Despicable",
            "Lewd",
            "Portly",
            "Violent",
            "Bumbling",
            "Faulty",
            "Pristine",
            "Cleanly",
            "Cracked",
            "Splintered",
            "Jeweled",
            "Superior",
            "Flawless",
            "Common",
            "Exquisite",
            "Elegant",
            "Fine",
            "Dull",
            "Brittle",
            "Fragile",
            "Effeminate",
            "Masculine",
            "Supine",
        ],
    },
    {
        title: "d100 Noun 1",
        id: "d100noun1a_tavernnames",
        roll: [
            "Horseman",
            "Maiden",
            "Mage",
            "Bachelor",
            "King",
            "Magistrate",
            "Warchief",
            "Warrior",
            "Mare",
            "Wolf",
            "Fox",
            "Lion",
            "Lamb",
            "Warden",
            "Mule",
            "Assassin",
            "Swordsman",
            "Lady",
            "Knight",
            "Soldier",
            "Wizard",
            "Warlock",
            "Ranger",
            "Bard",
            "Druid",
            "Monk",
            "Paladin",
            "Sorcerer",
            "Rogue",
            "Cleric",
            "Bear",
            "Goblin",
            "Kobold",
            "Gnome",
            "Halfling",
            "Dwarf",
            "Fool",
            "Virgin",
            "Horde",
            "Squire",
            "Eagle",
            "Rooster",
            "Piglet",
            "Thief",
            "Priest",
            "Friar",
            "Blacksmith",
            "Guard",
            "Stag",
            "Hag",
            "Devil",
            "Angel",
            "Serpent",
            "Snake",
            "Rat",
            "Mouse",
            "Bandit",
            "Chieftain",
            "Griffon",
            "Dragon",
            "Lizard",
            "Pony",
            "Baron",
            "Heifer",
            "Bull",
            "Hound",
            "Goat",
            "Toad",
            "Stallion",
            "Monster",
            "Vermin",
            "Beholder",
            "Monkey",
            "Elephant",
            "Boar",
            "Beagle",
            "Bat",
            "Demon",
            "Imp",
            "Sprite",
            "Fey",
            "Spirit",
            "Bitch",
            "Starling",
            "Minotaur",
            "Barbarian",
            "Prophet",
            "Merchant",
            "Cobbler",
            "Unicorn",
            "Ogre",
            "Nymph",
            "Butcher",
            "Captain",
            "Angler",
            "Lover",
            "Mason",
            "Tinker",
            "Whale",
        ],
    },
    {
        title: "d100 Noun 1B",
        id: "d100noun1b_tavernnames",
        roll: [
            "Horseman",
            "Maiden",
            "Mage",
            "Bachelor",
            "King",
            "Magistrate",
            "Warchief",
            "Warrior",
            "Mare",
            "Wolf",
            "Fox",
            "Lion",
            "Lamb",
            "Warden",
            "Mule",
            "Assassin",
            "Swordsman",
            "Lady",
            "Knight",
            "Soldier",
            "Wizard",
            "Warlock",
            "Ranger",
            "Bard",
            "Druid",
            "Monk",
            "Paladin",
            "Sorcerer",
            "Rogue",
            "Cleric",
            "Bear",
            "Goblin",
            "Kobold",
            "Gnome",
            "Halfling",
            "Dwarf",
            "Fool",
            "Virgin",
            "Horde",
            "Squire",
            "Eagle",
            "Rooster",
            "Piglet",
            "Thief",
            "Priest",
            "Friar",
            "Blacksmith",
            "Guard",
            "Stag",
            "Hag",
            "Devil",
            "Angel",
            "Serpent",
            "Snake",
            "Rat",
            "Mouse",
            "Bandit",
            "Chieftain",
            "Griffon",
            "Dragon",
            "Lizard",
            "Pony",
            "Baron",
            "Heifer",
            "Bull",
            "Hound",
            "Goat",
            "Toad",
            "Stallion",
            "Monster",
            "Vermin",
            "Beholder",
            "Monkey",
            "Elephant",
            "Boar",
            "Beagle",
            "Bat",
            "Demon",
            "Imp",
            "Sprite",
            "Fey",
            "Spirit",
            "Bitch",
            "Starling",
            "Minotaur",
            "Barbarian",
            "Prophet",
            "Merchant",
            "Cobbler",
            "Unicorn",
            "Ogre",
            "Nymph",
            "Butcher",
            "Captain",
            "Angler",
            "Lover",
            "Mason",
            "Tinker",
            "Whale",
        ],
    },
    {
        title: "d100 Noun 2",
        id: "d100noun2_tavernnames",
        roll: [
            "Saddle",
            "Guild",
            "Fangs",
            "Man",
            "Pardon",
            "Pleasure",
            "Belt",
            "Staff",
            "Shield",
            "Prince",
            "Master",
            "Servant",
            "Meal",
            "Prince",
            "Favor",
            "Love",
            "Word",
            "Scribe",
            "Apprentice",
            "Acolyte",
            "Dress",
            "Goddess",
            "God",
            "Gold",
            "Purse",
            "Trap",
            "King",
            "Son",
            "Sister",
            "Mother",
            "Daughter",
            "Cry",
            "Shout",
            "Cupboard",
            "Pantry",
            "Queen",
            "Wealth",
            "Star",
            "Void",
            "Woman",
            "Man",
            "Whore",
            "Butcher",
            "Anvil",
            "Tome",
            "Sacrifice",
            "Armor",
            "Cup",
            "Pot",
            "Stove",
            "Stool",
            "Princess",
            "Chain",
            "Sword",
            "Pork",
            "Grain",
            "Tooth",
            "Lance",
            "Axe",
            "Scabbard",
            "Knife",
            "Dagger",
            "Spear",
            "Bow",
            "Crossbow",
            "Quarterstaff",
            "Staff",
            "Fire",
            "Ice",
            "Wind",
            "Earth",
            "Water",
            "Stone",
            "Ladle",
            "Monastery",
            "Chalice",
            "Goblet",
            "Dungeon",
            "Lust",
            "Lantern",
            "Bone",
            "Life",
            "Stone",
            "Mistress",
            "Mind",
            "Treasure",
            "Barter",
            "Armorer",
            "Butler",
            "Page",
            "Tome",
            "Feather",
            "Shadow",
            "Friend",
            "Labyrinth",
            "Mountain",
            "Hope",
            "Boot",
            "Gauntlet",
        ],
    },

    {
        title: "d50 The shop sells...",
        id: "d50theshopsells_shops",
        roll: [
            "Weapons",
            "Armor",
            "Magical items",
            "Fresh food",
            "Cured food",
            "Livestock",
            "Slaves",
            "Services",
            "Mostly junk",
            "Artwork",
            "Jewellery",
            "Gems and Ores",
            "Mining tools",
            "Household goods",
            "Farming tools",
            "Animal feed",
            "Crafting tools",
            "Ales and Liqueur",
            "Items of interest from a previous generation",
            "Items of interest from a far-away land",
            "Clothing",
            "Gnomish Gadgets",
            "Potions",
            "Poisons",
            "Alchemical Supplies",
            "Magical Supplies",
            "Musical instruments",
            "Fabrics",
            "A little bit of everything",
            "Spices",
            "Hunting Tools",
            "Herbs",
            "Remedies and tonics",
            "Books",
            "Dolls",
            "Toys",
            "Exotic Animals",
            "Furs and Pelts",
            "Illicit Goods",
            "Cheeses",
            "Meats",
            "Pack animals",
            "Building supplies",
            "Fruits and vegetables",
            "Supplies for a local guild",
            "Leather goods",
            "Good crafted from rare metals",
            "Beauty and hygiene supplies",
            "Magical creatures",
            "Wagon wheels",
        ],
    },
    {
        title: "d10 The shop's type is...",
        id: "d10theshopstypeis_shops",
        roll: [
            "A building in a merchant district",
            "Attached to the merchant's home",
            "A wagon pulled by a horse or ox team",
            "Under a tent",
            "In an open bazaar on a rug",
            "In a stall in a bazaar",
            "In the back room of another shop",
            "A merchant caravan",
            "In a place only accessibly by magic",
            "A franchise. The shop can be found in multiple places",
        ],
    },
    {
        title: "d12 The shop is owned by...",
        id: "d12theshopisownedby_shops",
        roll: [
            "A beady-eyed accountant",
            "A guild leader",
            "A noble",
            "An obsessive-compulsive gnome",
            "A greedy dwarf",
            "A former soldier",
            "A farmer's wife",
            "A snobby high-elf",
            "A forgetful halfling",
            "An oppressive brute",
            "An old crone",
            "A lazy half-orc",
        ],
    },
    {
        title: "d6 The shop's condition is...",
        id: "d6theshopsconditionis_shops",
        roll: [
            "Brand new. Everything has a place, and is in its place",
            "Well maintained. It is cleaned regularly",
            "Average. A little dusty",
            "Unkempt. Bugs and rodents scurry away from your footsteps",
            "Dark. There is no natural light. Only a candle or two light the shop",
            "Decrepit. The building should be condemned",
        ],
    },
    {
        title: "d6 The condition of the merchandise is...",
        id: "d6theconditionofthemerchandiseis_shops",
        roll: [
            "Pristine. Kept in the best possible condition",
            "Cleaned regularly",
            "Mixed. Some items look new, while some look like they have been there a long time",
            "Dusty and dirty",
            "Falling apart",
            "Ancient",
        ],
    },
    {
        title: "d6 The shop gets its supplies from...",
        id: "d6theshopgetsitssuppliesfrom_shops",
        roll: [
            "They are crafted or attained by the merchant himself",
            "They are crafted or attained by the merchant's apprentices",
            "The merchant's business partner",
            "They are crafted elsewhere in bulk, and sold in the shop",
            "They are purchased from other people in town and resold",
            "No one knows, and no one asks",
        ],
    },
    {
        title: "d8 The items are priced...",
        id: "d8theitemsarepriced_shops",
        roll: [
            "Fairly",
            "Below value",
            "Above value",
            "Exorbitantly",
            "Everything is for barter",
            '"Other" means of payment are encouraged',
            "Based on the merchant's mood",
            "Based on how much the merchant thinks the customer needs it.",
        ],
    },
    {
        title: "d5 The shop's size is...",
        id: "d5theshopssizeis_shops",
        roll: [
            "Giant. Multiple rooms",
            "Large. One big room",
            "Average. One room big enough to hold what is needed",
            "Small. The room feels cluttered",
            "Tiny. The merchant practically operates out of a pack",
        ],
    },
    {
        title: "d4 How busy is the shop...",
        id: "d4howbusyistheshop_shops",
        roll: [
            "It's one of the most popular places to visit",
            "A few people mill in and out of the shop",
            "Not very busy. You are the only people there",
            "It rarely sees a customer",
        ],
    },
    {
        title: "d50 Something interesting you find...",
        id: "d50somethinginterestingyoufind_shops",
        roll: [
            "The shopkeeper lives in a room attached to the shop",
            "There is a secret room in the back to sell illicit wares",
            "The shopkeeper does not seem to belong there",
            "One of the items does not seem to belong there",
            "A bell rings every time someone enters the shop",
            "The shopkeeper is unusually friendly",
            "The shopkeeper does not seem to want any business",
            "Some items are oddly magical (or non-magical)",
            "You feel an unseen presence watching you",
            "Magical barriers prevent people from handling the merchandise",
            "A goblin is handling some of the wares",
            "A ogre is leashed to one of the walls",
            "A couple dogs keep an eye on you, while chewing on a bone",
            "A cat follows you around the shop",
            "A goat seems to be keeping guard outside the shop",
            "A rats nest is forming in a secluded corner",
            "A talking bird insists on yelling obscenities at you",
            "Many items are being packed for sale",
            "A new shipment has just arrived, and is being stocked",
            "You hear noises from the roof or room above the shop",
            "The floor is cracked",
            "The merchant is cleaning up an item that was ruined on the shop floor",
            "The shopkeeper is arguing with an employee",
            "A monkey follows you and tries to hand merchandise to you",
            "Footprints lead directly into a wall",
            "A raven tries to steal items from your bag",
            "The merchant's young children are trying unsuccessfully at a hard sale",
            "The merchant does not speak common",
            "Items change when you're not looking",
            "Music is playing throughout the shop",
            "The merchant can tell a story behind everything he sells",
            "Some of the items appear stolen",
            "The shop is only open at night",
            "The shop is closed for the day",
            "An unusual item is for sale with a dark backstory",
            "A couple of thugs are holding up the merchant",
            "One of the customers is trying to shoplift",
            "The shop has a strong odor of mildew",
            "The shop is owned by a friend or former party member",
            "A ghost is browsing the merchandise",
            "The shopkeeper is fast asleep",
            "The shopkeeper has a pungent and offensive smell",
            "The shopkeeper is a forceful salesman",
            "A legendary weapon is on display, but not for sale",
            "Murals line the walls",
            "The merchant insists he is from an ancient line of powerful merchants",
            "The merchant dresses much better than expected",
            "The merchant looks like a beggar",
            "Constables or the local guard are interviewing everyone in the shop",
            "The shopkeeper just died",
        ],
    },

    {
        title: "d8 The marketplace is located in...",
        id: "d8themarketplaceislocatedin",
        roll: [
            "A wide, rectangular plaza.",
            "A large, circular or elliptical plaza.",
            "A large plaza with a polygonal shape (d4): 1. perfect square; 2. trapezoid; 3. triangle; 4. pentagon.",
            "An intersection of two wide roads.",
            "A sprawling maze of small alleyways.",
            "A sprawling maze of tunnels beneath the city streets.",
            "A huge pavilion with a solid roof overhead.",
            "A disorganized series of large tents.",
        ],
    },
    {
        title: "d10 Vendor stalls, carts, and booths are mostly organized by...",
        id: "d10vendorstallscartsandboothsaremostlyorganizedby",
        roll: [
            "Type of merchandise.",
            "Nation of origin of the merchandise.",
            "Race or ethnicity of the merchants.",
            "Nothing; the place is a big disorganized mess.",
            "Religious or political affiliation of the merchants.",
            "Raw materials and commodities on one half of the market, finished products on the other half.",
            "Imported goods on one half of the market, local goods on the other half.",
            "An intricate and archaic system put down in an ancient civic or religious document.",
            "The social class to which the vendor caters.",
            "Order of arrival at the marketplace on any given day.",
        ],
    },

    {
        title: "d50 Settlement name (part 1)...",
        id: "d50settlementnamepart1",
        roll: [
            "Stone.",
            "Water.",
            "Leaf.",
            "Ice.",
            "Flame.",
            "Sol.",
            "Storm.",
            "Earth.",
            "Gleam.",
            "Star.",
            "Art.",
            "War.",
            "Heart.",
            "Hard.",
            "Fall.",
            "Rock.",
            "Doom.",
            "Oak.",
            "Tear.",
            "Raven.",
            "Badger.",
            "Snake.",
            "Lion.",
            "Hell.",
            "Rage.",
            "Brine.",
            "Rat.",
            "Buck.",
            "Lily.",
            "Core.",
            "Stench.",
            "Mage.",
            "God.",
            "Soil.",
            "Pure.",
            "Mal.",
            "Cam.",
            "Fen.",
            "Clear.",
            "Split.",
            "Founder's.",
            "Heir.",
            "Fair.",
            "Spin.",
            "Lord's.",
            "King's.",
            "Servant's.",
            "Demon's.",
            "Snow.",
            "Land's.",
        ],
    },
    {
        title: "d50 Settlement name (part 2)...",
        id: "d50settlementnamepart2",
        roll: [
            "crest.",
            "bridge.",
            "run.",
            "catch.",
            "blade.",
            "haven.",
            "rise.",
            "more.",
            "light.",
            "main.",
            "blaze.",
            "place.",
            "tear.",
            "fold.",
            "rest.",
            "host.",
            "craft.",
            "lair.",
            "hollow.",
            "vale.",
            "hammer.",
            "pike.",
            "rail.",
            "spike.",
            "ring.",
            "henge.",
            "coil.",
            "spring.",
            "jaw.",
            "mark.",
            "hail.",
            "loch.",
            "child.",
            "keep.",
            "fort.",
            "brook.",
            "forth.",
            "melt.",
            "borourgh.",
            "ford.",
            "crawl.",
            "moral.",
            "combe.",
            "glen.",
            "garden.",
            "wish.",
            "fellow.",
            "ridge.",
            "ward.",
            "town.",
        ],
    },
    {
        title: "d6 Population size...",
        id: "d6populationsize",
        roll: [
            "50 people (hamlet).",
            "100 people (small village).",
            "250 people (village).",
            "1'000 people (small town).",
            "5'000 people (town).",
            "25'000 people (city).",
        ],
    },
    {
        title: "d100 Main inhabitants are...",
        id: "d100maininhabitantsare",
        roll: [
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Humans",
            "Wood Elves",
            "Wood Elves",
            "Wood Elves",
            "Wood Elves",
            "Wood Elves",
            "High Elves",
            "High Elves",
            "High Elves",
            "High Elves",
            "High Elves",
            "High Elves",
            "High Elves",
            "High Elves",
            "High Elves",
            "Eladrin",
            "Eladrin",
            "Half-Elves",
            "Half-Elves",
            "Drow",
            "Drow",
            "Mountain Dwarves",
            "Mountain Dwarves",
            "Mountain Dwarves",
            "Mountain Dwarves",
            "Mountain Dwarves",
            "Mountain Dwarves",
            "Mountain Dwarves",
            "Mountain Dwarves",
            "Mountain Dwarves",
            "Mountain Dwarves",
            "Hill Dwarves",
            "Hill Dwarves",
            "Hill Dwarves",
            "Hill Dwarves",
            "Hill Dwarves",
            "Lightfoot Halflings",
            "Lightfoot Halflings",
            "Lightfoot Halflings",
            "Stout Halflings",
            "Stout Halflings",
            "Rock Gnomes",
            "Rock Gnomes",
            "Forest Gnomes",
            "Forest Gnomes",
            "Deep Gnomes",
            "Dragonborn",
            "Dragonborn",
            "Dragonborn",
            "Dragonborn",
            "Dragonborn",
            "Orcs and Half-Orcs",
            "Orcs and Half-Orcs",
            "Orcs and Half-Orcs",
            "Tieflings and Fiends",
            "Tieflings and Fiends",
            "Aarakocra",
            "Aarakocra",
            "Genasi and Elementals",
            "Genasi and Elementals",
            "Shifters and Lycanthropes",
            "Shifters and Lycanthropes",
            "Goliaths and Giants",
            "Changelings and Doppelgangers",
            "Warforged and Construcst",
            "Aasimar and Celestials",
        ],
    },
    {
        title: "d20 The settlement's atmosphere is...",
        id: "d20thesettlementsatmosphereis",
        roll: [
            "Calm.",
            "Quaint.",
            "Peaceful.",
            "Vaguely unsettling.",
            "Decidedly sinister.",
            "Tense.",
            "Violent.",
            "Fearful.",
            "Bustling.",
            "Tumultuous.",
            "Chaotic.",
            "Pleasant.",
            "Dark.",
            "Heavy.",
            "Stifling.",
            "Relaxing.",
            "Freeing.",
            "Spiritual.",
            "Apathetic.",
            "Grief-stricken.",
        ],
    },
    {
        title: "d100 A prominent feature of the settlement is...",
        id: "d100aprominentfeatureofthesettlementis",
        roll: [
            "Its beautiful parks.",
            "Its majestic orchards.",
            "A notable library.",
            "A powerful guild.",
            "The smell of baked bread.",
            "The sounds of blacksmiths working.",
            "The abundance of game in the surrounding land.",
            "The extensive farmland surrounding it.",
            "Its exotic goods.",
            "The slums.",
            "Its criminal syndicate.",
            "Its high-class brothels.",
            "Its ban on prostitution.",
            "That it is protected by thick stone walls.",
            "That it stands atop a floating mote of earth.",
            "Its visible magic wards, which repel monsters.",
            "That it is constantly besieged.",
            "That it is ruled by a tyrant.",
            "The law is enforced harshly.",
            "The lack of government; anarchy reigns.",
            "A large temple.",
            "A gated cemetery larger than is warranted.",
            "A system of tunnels beneath the settlement.",
            "A planar gate.",
            "A powerful curse.",
            "That adventurers are hated by the people.",
            "A mysterious obelisk towers over other buildings.",
            "A famous entertainer inhabits the settlement.",
            "That magic is hated by the people.",
            "Its heavily armed, well-trained guards.",
            "The tamed monster that defends it.",
            "A well-traveled trade route that runs through it.",
            'Its "friendly" barmaids.',
            "The local ale distillery.",
            "A keep of a noble lord.",
            "A tower in which a princess is locked up.",
            "That it's overrun with pests.",
            "That it's in an economic depression.",
            "That it's being extorted by an intelligent monster.",
            "A group of refugees tenting near the settlement.",
            "That it's on the path of a gypsy caravan.",
            "That a traveling carnival often passes through.",
            "The nearby vineyards.",
            "Its history as a battleground.",
            "Its proximity to a monster stronghold.",
            "A wishing well with a local legend.",
            "That it is built in a dead magic zone.",
            "That it is built in a wild magic zone.",
            "That it was the site of a mythic event.",
            "That it was built atop ancient ruins.",
            "A statue honoring some long-dead hero.",
            "An abundance of a particular animal.",
            "A shrine to an evil god.",
            "An affordable periodical carrying news of the realm.",
            "A peaceful cult.",
            "Its wide streets.",
            "Its incredibly beautiful architecture.",
            "Its patronage of the arts.",
            "The nearby academy of magic.",
            "The rare herbs that grow nearby.",
            "The use of glowing crystal as streetlamps.",
            "The settlement's astronomy observatory.",
            "A bridge that spans a wide river.",
            "The fiercely patriotic inhabitants.",
            "A gallows erected in the main square.",
            "A genial ghost.",
            'Its "no-weapons" policy.',
            "A corrupt politician.",
            "Regular raids by a nearby group of bandits.",
            "That it was founded by cannibals, and some continue the tradition.",
            "That it's actually a bandit base.",
            "That all light except sunlight is smothered.",
            "That it was the location of a pirate's unclaimed treasure hoard.",
            "The nearby mines.",
            "A history of assassinations.",
            "Its very progressive attitude.",
            "Its staunch conservative attitude.",
            "Its incompetent buffoon of a leader.",
            "Its paranoia.",
            "Its xenophobia.",
            "Its tolerance of others.",
            "A coven of witches as rulers.",
            "Its predominantly male population.",
            "Its predominantly female population.",
            "Its high concentration of children.",
            "Its noticeable lack of children.",
            "Its connection to the Feywild.",
            "Its connection to the Shadowfell.",
            "Its grimy feel.",
            "The stench of sewage.",
            "A river that divides it.",
            "The undead servants that perform labor.",
            "That it's the center of a manhunt.",
            "A pony mascot with an adorable name.",
            "The overpowering smell of sulfur.",
            "A low hum that permeates the settlement with no known cause.",
            "A thousand-year-old tree in town square.",
            "That it is under the protection of friendly elemental spirits.",
            "The blistering heat of its forges.",
            "Its famous impartiality.",
        ],
    },
    {
        title: "d30 The players should care about the settlement because...",
        id: "d30theplayersshouldcareaboutthesettlementbecause",
        roll: [
            "It has magic item shop(s).",
            "A dungeon was discovered nearby recently.",
            "A powerful wizard lives there.",
            "A NPC the players have met before is there.",
            "Something they want is there.",
            "A thief stole something from them here.",
            "It was mentioned in a letter found on a slain foe.",
            "They are hired by someone in the settlement.",
            "This is the only settlement with which to resupply within leagues.",
            "One of the inhabitants asked for help with a problem.",
            "It is the only save haven from the monster-infested surroundings.",
            "They are implicated in a crime and asked not to leave town.",
            "There are some interesting rumors about their foes.",
            "The players liberated some prisoners who asked to be taken there.",
            "An enemy has called them out.",
            "The rewards on the job board are high.",
            "Things don't quite add up; perhaps investigation is called for.",
            "It keeps getting mentioned wherever they go.",
            "The townspeople greet them like heroes.",
            "They need to take shelter from a severe storm.",
            "They need help that the settlement can provide.",
            "A child/helpless NPC is in danger and needs help.",
            "There are signs of a monster infestation.",
            "A creature whose goals clash with theirs lives there.",
            'A powerful NPC tries to put them under a "geas".',
            "A patron promises them jobs there.",
            "They hear rumors of a hidden magic item nearby.",
            "A strange crime is committed, peripherally involving them.",
            "A local NPC did them a favor, and wants to cash in.",
            "A powerful entity offers them a deal there.",
        ],
    },

    {
        title: "d10 The name of the shop is",
        id: "d10thenameoftheshopis",
        roll: [
            "Old Grindylocks",
            "Enchantments and Curses",
            "Fidgety sams Fidgets",
            "Banshees, Bassilisks, and Beholders",
            "Hextech and other magical things",
            "The Crawling Claw",
            "The Fizzling Fireball",
            "The Wild Magic Surge",
            "Feathers of the Phoenix",
            "Michales Magical Accessories",
        ],
    },
    {
        title: "d20 The Shop Is Located",
        id: "d20theshopislocated",
        roll: [
            "Underground",
            "In the Slums",
            "In the market",
            "In the tavern cellar",
            "In the home of a spellcaster",
            "at the docks",
            "on a ship",
            "Same building as the sorcerers tavern",
            "In the arcane district",
            "In the town square",
            "In an alley inhabited mostly by elves",
            "in an alley inhabited mostly by Dwarves",
            "in an alley inhabited mostly by Gnomes",
            "in an alley inhabited mostly by Tieflings",
            "in an alley inhabited mostly by Goblins",
            "In the noble district",
            "At the entrance of the Colloseum",
            "The shop is the wagon of a traveling merchant",
            "On top of a mountain",
            "at the bottom of a river",
        ],
    },
    {
        title: "d10 The shop sells",
        id: "d10theshopsells",
        roll: [
            "Trinkets and Accessories nothing of great power",
            "Potions and poisons",
            "Lovepotions, Viagra, and other such things",
            "Divinations",
            "Material components for various spells",
            "Spellbooks and Magical Ink",
            "Magical Weapons",
            "Magical Armour",
            "Scrolls",
            "Enchanted animals",
        ],
    },
    {
        title: "d10 The Shop Is Owned By",
        id: "d10theshopisownedby",
        roll: [
            "And incredibly old Human",
            "A Squirrely Gnome",
            "A Forgetsome Halfling",
            "A Greedy and Malicious Goblin",
            "A Rogue wizard",
            "A Fairy",
            "A snobby High Elf",
            "A Wizard who is constantly experinmenting",
            "An efreeti Trying to make a bargain with your soul",
            "A Warrior who knows nothing of magic, but is selling the goods he has acquired over the years",
        ],
    },
    {
        title: "d10 The place looks",
        id: "d10theplacelooks",
        roll: [
            "Suspicious",
            "Pristine",
            "Natural",
            "Worn down",
            "Alive",
            "Incredibly small on the inside compared to how it looks on the outside",
            "Incredibly large on the insdide compared to how it looks on the outside",
            "Charred",
            "Frozen",
            "Gleaming",
        ],
    },
    {
        title: "d10 A characteristic of the items sold here is",
        id: "d10acharacteristicoftheitemssoldhereis",
        roll: [
            "They are all in poor shape",
            "They have unknown effects",
            "They are unstable, and might release magical surges on use",
            "They are expired (for example an expired spell)",
            "They are cursed",
            "They are blessed",
            "The items are all stolen",
            "The items have great histories",
            "The items former owner is still looking for them",
            "The items are ancient",
        ],
    },

    {
        title: "d8 The arena is...",
        id: "d8thearenais",
        roll: [
            "An ancient stone structure used for centuries.",
            "An old stone structure used for generations.",
            "A wondrous construction with grand stands, trap doors, and elevators.",
            "A sturdy wooden structure, recently built.",
            "A crisp stone structure, recently built.",
            "A set of rickety wooden stands around a dirt ring.",
            "A circle of rope surrounded by spectators and a few cages.",
            "An underground pit with spectators leaning over a railing above.",
        ],
    },
    {
        title: "d8 The games are being held...",
        id: "d8thegamesarebeingheld",
        roll: [
            "In honor of the sovereign’s birthday.",
            "In honor of a historical anniversary.",
            "In honor of a recent military victory.",
            "To turn a legitimate profit for the organizers.",
            "To turn a gambling profit for the organizers.",
            "To dispose of prisoners.",
            "Strictly to entertain the masses.",
            "To determine a champion for a dangerous quest or traditional ceremony.",
        ],
    },
    {
        title: "d8 The main event is...",
        id: "d8themaineventis",
        roll: [
            "A battle royale or grand melee.",
            "A reenactment of a historical battle.",
            "A duel between two arena champions.",
            "A duel between a champion and a severe underdog.",
            "Feeding prisoners to beasts.",
            "A battle of man versus beast (d8): 1. bears; 2. chimeras; 3. dragons; 4. giant spiders; 5. lions; 6. owlbears; 7. tigers; 8. wolves.",
            "A chariot race or foot race.",
            "Feats of strength.",
        ],
    },
    {
        title: "d12 The day’s champion wins...",
        id: "d12thedayschampionwins",
        roll: [
            "A heavy purse of silver.",
            "A sizable purse of gold.",
            "An expensive and ornate weapon.",
            "An expensive and ornate piece of armor.",
            "A floral crown and a fine silver chain.",
            "A floral crown and a bejeweled gold belt.",
            "A fine silk cloak and a bejeweled silver chain.",
            "A petition of the sovereign.",
            "A position of honor in the army and a purse of silver.",
            "A position of honor in the sovereign’s guard.",
            "A week of pampering and pleasure and a purse of silver.",
            "A night with one of the nobles’ wives and a purse of gold.",
        ],
    },
    {
        title: "d6 The crowd’s attitude is...",
        id: "d6thecrowdsattitudeis",
        roll: [
            "Rowdy and festive.",
            "Eager and excited.",
            "Relaxed and easy-going.",
            "Hostile and tense.",
            "Disappointed and angry.",
            "Rowdy and rebellious.",
        ],
    },
    {
        title: "d8 The crowd is made up of mostly...",
        id: "d8thecrowdismadeupofmostly",
        roll: [
            "Merchants, nobles, and the well-to-do.",
            "Soldiers, officers, and camp-followers.",
            "Local artisans and shopkeepers.",
            "Local peasants and unskilled workers.",
            "Foreigners and travelers.",
            "Slaves, servants, and laborers.",
            "Sailors, pirates, and knaves.",
            "People of all social strata.",
        ],
    },
    {
        title: "d200 This place is called...",
        id: "d200thisplaceiscalled",
        roll: [
            "Daisies.",
            "The Don.",
            "Blinkers.",
            "The Prude's Suspenders.",
            "Gold’s Dust.",
            "The Velvet Fang.",
            "The Whisper Home.",
            "The Hook.",
            "Over the River.",
            "Slooshes.",
            "The Rapid Rascal.",
            "The Stoat.",
            "The Fidgety Ferret.",
            "Long Shaft.",
            "The Guards.",
            "Chastity’s.",
            "The Mask.",
            "The Red Dress.",
            "Jewels.",
            "Silken Flute.",
            "The Nag’s Head.",
            "Drummers.",
            "Sailors Choice.",
            "Blacksmiths Envy.",
            "The Nagging Wife.",
            "Colins Rubble.",
            "Dron's Beat.",
            "The Wink.",
            "Maggie’s Horn.",
            "The Sun & Cider.",
            "The Oakworm.",
            "Tickle & Feather.",
            "The Mistress.",
            "Madam Zersannies's.",
            "The King's Court.",
            "The Cursed Coin.",
            "Slit.",
            "The Maiden Head.",
            "The Rusty.",
            "The Silken Ferret.",
            "Long Legs.",
            "Elven Whispers.",
            "The Leg.",
            "False Suspenders.",
            "Aunt Fannies Bloomers.",
            "Final Rest.",
            "Cocks Crow.",
            "The Unblinking Eye.",
            "The Bountiful Bosom.",
            "Tuskers.",
            "The Thrusting Gentleman.",
            "Tally Hoes.",
            "Rutting.",
            "Pigs in Blankets.",
            "The Delicate Touch.",
            "Aphrodite’s Wish.",
            "The Dirty Secret.",
            "Long Locks.",
            "Sweat.",
            "Brothel.",
            "Taters.",
            "The Swift Finish.",
            "Cumberlands.",
            "The Missing Sausage.",
            "The Fools Frolic.",
            "Dragons.",
            "The Bushel.",
            "Farmers Oats.",
            "The Raised Brow.",
            "Genies.",
            "The Farfetched Feather.",
            "Junk.",
            "The Connoisseur’s Choice.",
            "Colossus.",
            "The Smooth Ride.",
            "Bucking.",
            "The Great Big Globes.",
            "The Glimmeric.",
            "Loving Embrace.",
            "Chokers Necklace.",
            "The Grand Madame's Emporium of Fine Delicacies, Treats, and the Exotic.",
            "Thug’s Retreat.",
            "Warriors' Return.",
            "Gold Gobblers.",
            "Cackling Croons.",
            "The Warty.",
            "Bessie’s Best.",
            "Corset.",
            "Winkies.",
            "The Shagger.",
            "Port of Call.",
            "The Home Away from Hoes.",
            "Smooth.",
            "The Maiden Fair.",
            "The Bit.",
            "Hosted.",
            "Glamourous Delights",
            "Happily Ever After.",
            "Sultry Stare.",
            "The Full Flush.",
            "The Lighted Candle.",
            "The Red Candle.",
            "The Raised Candle.",
            "The Dancing Flame.",
            "The Candlelight Resort.",
            "The Sweetest Cherry.",
            "Cherry's.",
            "Cherry Pie.",
            "The Velvet Cherry.",
            "The Golden Cherry.",
            "The Silk Curtain.",
            "The Red Curtain.",
            "The Lacy Curtain.",
            "The Welcoming Curtain.",
            "The Satin Curtain.",
            "Satin Dolls.",
            "Sweet Dolls.",
            "Porcelain Dolls.",
            "The Sugar Doll.",
            "Dancers and Dolls.",
            "The Red Door.",
            "The Golden Door.",
            "The Silver Door.",
            "The Maiden's Door.",
            "The Dancers' Door.",
            "Lover's Embrace.",
            "Lady's Embrace.",
            "The Sweetest Embrace.",
            "The Warmest Embrace.",
            "Welcoming Embrace.",
            "The Satin Glove.",
            "Silky Gloves.",
            "Lacy Gloves.",
            "The Lady's Glove.",
            "The Maiden's Glove.",
            "The Shining Heart.",
            "Pink Hearts.",
            "Lacy Hearts.",
            "Sweetheart's",
            "The Maiden's Heart.",
            "The Night House.",
            "The Pink House.",
            "The Porcelain House.",
            "The Welcoming House.",
            "The Cozy House.",
            "The Warmest Lamp.",
            "The Red Lamp.",
            "The Pink Lamp.",
            "The Soft Lamp.",
            "The Lady's Lamp.",
            "The Lady's Kiss.",
            "The Maiden's Kiss.",
            "The Night's Kiss.",
            "Cozy Kisses.",
            "Satin Kisses.",
            "Peach's Place.",
            "The Peach.",
            "The Prettiest Peach.",
            "The Sweetest Peach.",
            "The Golden Peach.",
            "The Silky Purse.",
            "The Satin Purse.",
            "The Lady's Purse.",
            "The Dancer's Purse.",
            "The Pink Purse.",
            "The Maiden's Room.",
            "The Lovers' Room.",
            "The Night Room.",
            "The Warm Room.",
            "The Red Room.",
            "The Silver Slipper.",
            "The Satin Slipper.",
            "The Silk Slipper.",
            "The Red Slipper.",
            "The Dancer's Slipper.",
            "The Lacy Skirt.",
            "The Welcoming Skirt.",
            "The Pink Skirt.",
            "The Dancer's Skirt.",
            "The Lady's Skirt.",
            "The Maiden's Shoe.",
            "The Red Shoe.",
            "Cozy Shoes.",
            "Lovers' Shoes.",
            "Silver Shoes.",
            "Silky Stockings.",
            "The Red Stocking.",
            "The Lacy Stocking.",
            "The Lady's Stocking.",
            "The Softest Stockings.",
            "The Maiden's Veil.",
            "The Lacy Veil.",
            "The Silk Veil.",
            "The Lovers' Veil.",
            "The Veil of Night.",
            "Soft-Lighted Window.",
            "The Shining Window.",
            "The Lighted Window.",
            "The Pink Window.",
            "The Welcoming Window.",
        ],
    },
    {
        title: "d20 The brothel is located...",
        id: "d20thebrothelislocated",
        roll: [
            "In the slums.",
            "In a shantytown.",
            "In a well-to-do residential neighborhood.",
            "In the docks district.",
            "In the riverfront district.",
            "In the barracks district.",
            "In an ally off a foreign bazaar.",
            "In an ally off the main market square.",
            "In the shadow of a temple.",
            "Above a boisterous tavern.",
            "Behind a tavern teeming with criminals.",
            "Adjacent to a tavern full of gamblers.",
            "Underground.",
            "Outside the walls of the city or on the outskirts of a town.",
            "At the base of a wizards’ tower.",
            "In cave that had been a monster’s lair.",
            "Above an inn on a busy trading route.",
            "In the basement of a tavern.",
            "On a street with many other brothels.",
            "In a house in a park, garden, or forest.",
        ],
    },
    {
        title:
            "d10 In addition to the ‘usual’ everyday brothel fare, here you can procure...",
        id: "d10inadditiontotheusualeverydaybrothelfarehereyoucanprocure",
        roll: [
            "Really weird stuff, for those with the most interesting fetishes.",
            "Illegal stuff. If this is found out, the place would be burnt down, and the owners hung. It is clearly kept in great secret.",
            "Performances involving food.",
            "An outlet to live out violent fantasies.",
            "Exotic races.",
            "The most beautiful women and men. Not just a claim, it’s the gods’ honest truth.",
            "An all-inclusive lump-sum deal—all the harlots, food, and drink you can handle!",
            "The sale of mind-altering drugs.",
            "Stuff with exotic/magical ingredients, potions, etc.",
            "Magical delights.",
        ],
    },
    {
        title: "d8 The place is run by...",
        id: "d8theplaceisrunby",
        roll: [
            "A collective of the inmates themselves.",
            "A mean old madam.",
            "A large madam with a no-nonsense attitude.",
            "A warm motherly figure.",
            "A surly brute.",
            "A tyrannical and cruel fellow.",
            "A sultry seductress.",
            "A charming witch.",
        ],
    },
    {
        title: "d12 To eat, the place serves...",
        id: "d12toeattheplaceserves",
        roll: [
            "Simple snacks.",
            "Banquets.",
            "Peasant food.",
            "Food hand-fed to you by a harlot.",
            "Exotic delights.",
            "Spicy treats.",
            "Simple food.",
            "Sweets and delicacies.",
            "Grubby, poorly made meals.",
            "All you can eat buffets.",
            "Simple stew and bread.",
            "Nothing; it satisfies other appetites.",
        ],
    },
    {
        title: "d8 To drink, the place serves...",
        id: "d8todrinktheplaceserves",
        roll: [
            "Ales.",
            "Cocktails",
            "Grog, and nothing but grog.",
            "Cheap wines.",
            "Mead.",
            "The finest wines and champagnes.",
            "Lagers.",
            "Nothing; inebriation is not tolerated.",
        ],
    },
    {
        title: "d10 People talk about this place; they say...",
        id: "d10peopletalkaboutthisplacetheysay",
        roll: [
            "The girls are underpaid and poorly treated.",
            "Nothing really; it’s a neighborhood brothel.",
            "A prominent noble or merchant is a regular.",
            "The goddess of love and fertility blessed this place and all her followers must visit.",
            "The usual stuff; a new girl is making a stir.",
            "Once a month it offers discounted services.",
            "It is secretly the home to a dark cult.",
            "All the inmates there are related.",
            "Nothing much, a popular girl is with child.",
            "You can pay for services with things other than coin (d6): 1. contract work; 2. goods; 3. religious services; 4. high-profile invitations; 5. secrets; 6. stock.",
        ],
    },
    {
        title: "d10 People talk about this place; rumors suggest that recently...",
        id: "d10peopletalkaboutthisplacerumorssuggestthatrecently",
        roll: [
            "A nobleman got one of the girls with child but refuses to acknowledge her or the baby.",
            "Someone slaughtered half of the workers and clients in the night.",
            "A client was stabbed with a letter opener.",
            "A man claiming to be a paragon of the god of love visited the place.",
            "A group of outraged townsfolk has started protesting outside of the brothel, disgusted with what it does.",
            "The oldest patron, who visited the brothel every day for the last fifty years has died. A day of mourning and celebration, along with a lavish funeral is being held for him.",
            "One of the inmates was strangled.",
            "One of the inmates has fallen madly in love with a client, but he or she is married.",
            "A sinkhole has appeared in the basement. No one can see bottom, and the boss worries it might grow and do more damage.",
            "Several clients have caught a disease.",
        ],
    },
    {
        title: "d10 Room Furnishings: This room has...",
        id: "d10roomfurnishingsthisroomhas",
        roll: [
            "A four-poster bed with velvet curtains.",
            "A four-poster bed with lacy curtains.",
            "A soft, leather chaise lounge.",
            "A plush, pink chaise lounge.",
            "A large pile of pillows with soft tassels.",
            "A large pile of pillows with frilly edges.",
            "A table with fruit and wine set upon it.",
            "A table with perfumes and oils set upon it.",
            "A large mirror against one wall.",
            "A large mirror on the ceiling over the bed.",
        ],
    },
    {
        title: "d20 Features: You notice...",
        id: "brotheld20featuresyounotice",
        roll: [
            "The scent of lavender.",
            "The scent of lilac perfume.",
            "The scent of ginger and cinnamon.",
            "The scent of roses.",
            "Scented candles.",
            "The soft red glow from a shaded lamp.",
            "A lamp burning dimly.",
            "A statue of two figures kissing.",
            "A statue of two figures coupling.",
            "A statue of a nude woman bathing.",
            "A painting of several nudes bathing.",
            "A painting of a pair of lovers.",
            "A curtain of beads.",
            "A silky curtain.",
            "A plush carpet beneath your feet.",
            "A thick fur carpet beneath your feet.",
            "The sound of distant, soft music.",
            "The sound of furniture creaking nearby.",
            "A lengthy, shrill scream.",
            "A long moan.",
        ],
    },
    {
        title: "d20 Landmark: You see a/an...",
        id: "d20landmarkyouseeaan",
        roll: [
            "Academy or university.",
            "Ancient ruin.",
            "Arena.",
            "Cemetery.",
            "Civic hall, council hall, or guild hall.",
            "Common or greenway.",
            "Fortress.",
            "Gateway or arch.",
            "Library.",
            "Lighthouse or watchtower.",
            "Marketplace.",
            "Memorial (d4): 1. mausoleum; 2. reflecting pool; 3. large statue; 4. botanical garden.",
            "Monument (d6): 1. colossus; 2. column; 3. obelisk; 4. plaque; 5. statue garden; 6. wall.",
            "Palace.",
            "Parade grounds or drilling yard.",
            "Pier, marina, or traveler's bazaar.",
            "Plaza or public square.",
            "Temple.",
            "Theater.",
            "Stockyards.",
        ],
    },
    {
        title: "d20 This part of the city is the...",
        id: "d20thispartofthecityisthe",
        roll: [
            "Slums.",
            "Residential district, poor.",
            "Residential district, middle class.",
            "Residential district, upper class.",
            "Palace district.",
            "Temple district.",
            "Crafting district.",
            "Docks district.",
            "Riverfront district.",
            "Harbor district.",
            "University district.",
            "Military district.",
            "Market district.",
            "Garden district.",
            "Monument district.",
            "Necropolis.",
            "Theater district.",
            "Civic center.",
            "Ethnic enclave.",
            "Foreign enclave.",
        ],
    },
    {
        title: "d20 The locals call this street...",
        id: "d20thelocalscallthisstreet",
        roll: [
            "(d8): 1. Armory Street; 2. Barricade Street; 3. Knight Street; 4. Moat Street; 5. Pike Street; 6. Rampart Street; 7. Shield Street; 8. Spear Street.",
            "(d6): 1. Arch Street; 2. Bridge Street; 3. Canal Street; 4. Cross Street; 5. Pole Street; 6. River Street.",
            "(d6): 1. Castle Street; 2. House Street; 3. Keep Street; 4. Manor Street; 5. Rock Way; 6. Tower Street.",
            "(d8): 1. Cattle Road; 2. Common Street; 3. Green Street; 4. Greenway Street; 5. Meadow Lane; 6. Orchard Street; 7. Pasture Road; 8. Wildflower Lane.",
            "(d12): 1. Anvil Street; 2. Cooper Street; 3. Forge Street; 4. Hammer Street; 5. Horseshoe Street; 6. Iron Street; 7. Mason Street; 8. Steel Street. 9. Tailor Street; 10. Stone Street; 11. Wright Street; 12. Weaver Street.",
            "(d8): 1. Bluff Street; 2. Cliff Street; 3. Crestline Way; 4. High Street; 5. Highland Way; 6. Hill Street; 7. Hilltop Lane; 8. Ridge Street; 9. Ridgeline Way; 10. Summit Street.",
            "(d8): 1. Devil's Alley; 2. Devil's Lane; 3. Low Street; 4. Magpie Lane; 5. Paupers Street; 6. Penny Lane; 7. Rat's Alley; 8. Serpent's Alley.",
            "Market Street.",
            "(d8): 1. Baker Street; 2. Hook Street; 3. Farm Road; 4. Feather Street; 5. Mill Street; 6. Pork Road; 7. Ranchers Road; 8. Stockyard Street.",
            "(d8): 1. Banner Road; 2. Captains Street; 3. Drum Street; 4. March Street; 5. Parade Street; 6. Triumphant Way; 7. Trumpet Street; 8. Victory Lane.",
            "(d6): 1. King Street; 2. Lords Lane; 3. Monarch Street; 4. Palace Way; 5. Queens Street; 6. Royal Street.",
            "(d6): 1. Circle Street; 2. Borderline Road; 3. Curtain Street; 4. Townline Road; 5. Watch Street; 6. Wall Street.",
            "(d8): 1. Bay Street; 2. Commerce Street; 3. Dockside Way; 4. Harbor Street; 5. Lake Street; 6. Pier Street; 7. Portside Way; 8. Water Street.",
            "(d8): 1. Bayview Street; 2. Castleview Street; 3. Gardenview Street; 4. Greenview Street; 5. Harborview Street; 6. Marketview Street; 7. Riverview Street; 8. Waterview Street.",
            "(d8): 1. North Road; 2. North Street; 3. South Road; 4. South Street; 5. East Road; 6. East Street; 7. West Road; 8. West Street.",
            "(d12): 1. Beech Street; 2. Cedar Street; 3. Cherry Street; 4. Cypress Street; 5. Fir Street; 6. Maple Street; 7. Oak Street; 8. Palm Street; 9. Pine Street; 10. Spruce Street; 11. Walnut Street; 12. Willow Street.",
            "(d8): 1. Northgate Street; 2. Southgate Street; 3. Eastgate Street; 4. Westgate Street; 5. Old Gate Road; 6. Rivergate Street; 7. Watchtower Street; 8. Watergate Street.",
            "(d12): 1. Briar Street; 2. Bush Street; 3. Gardenia Lane; 4. Garden Street; 5. Lilac Street; 6. Lily Way; 7. Petal Street; 8. Poppy Street; 9. Rose Street; 10. Sunflower Lane; 11. Thorny Lane; 12. Violet Street.",
            "(d6): 1. Emerald Way; 2. Jewelers Lane; 3. Golden Lane; 4. Rich Way; 5. Ruby Road; 6. Silver Lane.",
            "(d8): 1. Bath Street; 2. Fountain Street; 3. Old Brick Road; 4. Old Stone Road; 5. Missing Street; 6. Stone Ruin Road; 7. Tumblestone Way; 8. Well Street.",
        ],
    },
    {
        title: "d20 Games, Contests, and Events",
        id: "d20gamescontestsandevents",
        roll: [
            "A group of commoners is playing horse shoes out back.",
            "The party is surprised to find the country darts league in full swing as they enter. The waitresses are used to the chaos and dodge darts easily. The half ogre bouncer is using lawn darts.",
            "a group of Hill Dwarves are in the middle of a drinking contest, and two of them are passed out already. The Prize is a solid platinum stein.",
            "Wet Chainmail contest!",
            "Four large Barbarians are loudly sledging each other during an arm wrestling competition.",
            "A shy teenage girl is reciting bad poetry in a corner. No one is paying the slightest bit of attention to her.",
            "It's trivia night! Those scholars from the School of History and the Arts at the University always win, but tonight, we represent and the School of Alchemy will show those smug book-snobs what it means to be a nerd.",
            "A promoter is working his way around the tables looking for challengers to fight the local champion pugilist.",
            "It's a sausage fest! The place is packed with dwarves eager to devour the all-you-can-eat sausage special.",
            "An over-sized brute is arm-wrestling crushing the hand of everyone in sight.",
            "Some goblins are throwing dice with some animated skeletons at a table in the corner.",
            "A goblin is doing a poor job at cheating at a dice game, while a skeleton is doing an excellent job at cheating.",
            "A 7'2\" red dragonborn with a 5' bastard sword is having a drinking contest with a dwarf. The dragonborn has a 4-pint tankard, and is almost managing to keep pace.",
            "A party sits in the corner booth playing cards. All of them are cheating, except the paladin, who, curiously, is winning.",
            "A mountain of a man in barbarian leathers is arm wrestling a small dragon and winning.",
            "An awakened Roper is winning two games of billiards at once.",
            "A group of drunken pixies is playing hide and seek by hiding behind patrons.",
            "The players have stumbled into a regional card championship being held that night. The buy in is huge, but so is the pot.",
            'A shady looking gnomish inventor is proudly showing off his latest invention. He calls it a "slot machine." ',
            "A grey haired story teller is sitting near the fire holding a contest. He'll give a large purse for a story he hasn't heard yet, but so far no one has won.",
        ],
    },
    {
        title: "d12 Entertainment",
        id: "d12entertainment",
        roll: [
            "The bartender tells elaborate stories about where the stuffed wyrmling dragon on the mantel came from. In reality, he’s a retired wizard and it’s his familiar which grew sick and died. He keeps it as a memento.",
            "A bard is telling a story about the player’s latest act of daring do. He’s embellishing quite a bit. When he recognizes the party he makes a big spectacle.",
            "A bard is telling the story of the player’s latest exploit. It’s an obvious character assassination.",
            "A local bardic group, The Rolling Boulders, are performing, and a large crowd of drunken groupies will not stop screaming.",
            "A beggar offers to sing for a few coppers. You heard him singing to the last table. He's awful.",
            "A sassy fortune teller has set up shop in a corner booth. She informs you that she sees a hangover in your near future.",
            'A stirring rendition of "The Lady and the Faerie Dragon" has the crowd calling for an encore from the minstrels.',
            "The lute-player catches some undergarments from the crowd and drapes them across the ridiculous horned helm he wears.",
            "On stage tonight: The Deep Tones. A quartet of dwarves with long beards and deep voices singing a capella favorites from places without light (or proper music).",
            "On stage tonight: Shaela Windspeaker. An elf-maid singer-songwriter with a bit of a whiny voice who is slowly making her way through her most recent song of protest against the previous and the present centuries of war.",
            "A nervous show-wizard on the small stage is doing tricks with Prestidigitation for the un-amused patrons.",
            "There is a pair of musicians warbling well known drinking songs. They have made an impromptu stage out of several tables. One of them seems to be tilting precariously.",
        ],
    },
    {
        title: "d20 Patrons and Staff",
        id: "d20patronsandstaff",
        roll: [
            "A poor farmer is trying to pay his bar tab with a sack of potatoes and a barrel of pickles.",
            "A sea captain has set up shop at a table and is trying to sell mementos and souvenirs from his latest great voyage of exploration. Birds, exotic coins, tiny mermaids, he has it all. Some of it looks fake though. A tiny bit looks disturbingly real.",
            "A ranger sits alone in a corner, smoking. A hood covers most of his face. At his feet is a sleeping wolfhound. Everyone is giving him a wide berth.",
            "A lone Troll is drinking at the end of the bar and softly crying and singing one country ballad after another.",
            "A stoned magician is fumbling his way through one awful card trick after another.",
            "A mixed group of Elves are drinking bad wine and holding scented handkerchiefs up to their noses to keep out the stench. One has an obsidian bow strapped to her back.",
            "A young woman and gruff man are asking the patrons questions about themselves. When they get to the players, the woman is interested by their adventuring tales. Little do they know, they're talking to the heir apparent and he trusted guard.",
            "Two guards are arguing at a table over who the captain likes more by comparing almost identical spears and claiming to have the better one.",
            "A sad clown is drinking a beer alone.",
            "A handsome young woman is holding court among some of her would-be suitors. Her father interrupts, and she stalks off embarrassed.",
            "Some idiot is having a stag night. His friends are loud and obnoxiously harassing the barmaids.",
            "It's ladies night! And it's not disappointing... A few pretty little things from the weavers' guild are here, a couple of attractive healers from the temple, and the beautiful new town librarian.",
            "A surly old witch is drinking sherry while stroking the fat grey cat sitting on her lap.",
            "The barkeep is a marilith, mixing up four drinks at a time.",
            "The barmaid is a succubus, she makes great tips.",
            "The attendant in the bathroom is a foul-smelling zombie. He offers you a mint crystal.",
            "Behind the bar is a gnomish alchemist with a penchant for mixology experiments.",
            "The toothless mop-hand reminisces with a hobgoblin military has-been over ales about how an otyugh in the loo isn't as bad as the time a carrion crawler was in there.",
            "The barmaid is a doppelganger. When she returns to your table with your drinks she has taken the form of one of your party.",
            "A fat priest is doing an excellent jiggly dance in rhythm with the music. Either that or a gelatinous cube has made it's way onto the dance floor?",
        ],
    },
    {
        title: "d6 Questionable drinks",
        id: "d6questionabledrinks",
        roll: [
            "Tonight's special cocktail: Pixiewine. Each glass of this crisp, floral-scented wine is served with a pixie.",
            "Tonight's special cocktail: Suckerpunch. Each glass of this potent purple-red punch has several small writhing tentacles that reach out of the glass to attach to your face with their suckers. It actually feels kind of nice.",
            "Tonight's special: Bring-Your-Own-Horn. Bring the horn of your favorite beast or monstrous humanoid (any size!), and we'll fill it with cheap ale or wine for 2 cp.",
            "Tonight's special cocktail: Mindbomb. It's made with absinthe and explosive powder.",
            "Tonight's special cocktail: Fireball. Served by wizards of 5th level or higher.",
            "Tonight's special cocktail: Stonebones. A powerful rum cocktail made with powder gorgon horn and basilisk eye. It's only partial paralysis.",
        ],
    },
    {
        title: "d20 Schemes, Mischief, and Trouble",
        id: "d20schemesmischiefandtrouble",
        roll: [
            "A group of highway men are drunkenly, and a little too loudly, discussing the caravan they pillaged outside of town and what to do with their shares.",
            "Adventurers are manhandling a companion turned to stone by a basilisk into the bar. The rouge is trying to pawn him off to the bartender as a hat rack. The bartender is considering it.",
            "The bartender is out of mugs because a wizard is passed out in a corner over a table covered in mugs. His drunken familiar attacks anyone approaching the table preventing the mugs recovery.",
            "A Faerie Dragon is passed out in the rafters. Dangling from one claw is a lacy brassiere.",
            "A fat Gnome is peddling smelly cheese from a wicker basket.",
            "A drunken beholder is getting surly. Or feeling playful, it's hard to tell.",
            "Two smugglers are talking in a booth before they start to argue. They both shoot at each other, one of them dies. Nobody's completely sure who shot first.",
            "A man is sitting alone, speaking relatively normally to the empty seat across from him, before yelling out in anger.",
            "A pair of Ratfolk are being harassed by a few drunken patrons. They're not fighting back.",
            "A child is attempting to set up a prank against a less than favorable character. He's close, but you can see a flaw in his plan that you could solve.",
            "It's ladies night! And this bar is a sausage fest.",
            "A necromancer leads a stumbling-drunk patron out the door.",
            "The bouncer brains an unruly goblin with his morningstar. No one cares because the party is rocking.",
            "A knife splits the bulls eye of the elves' in-progress dart game. The elves draw bows and start shooting the place up.",
            "An illithid is telling fortunes with a deck of tarot cards on an overturned barrel out front. Some say it's cheating because he can read minds, but I say it's cheating because he can eat minds.",
            "An otyugh made a mess in the loo again.",
            "At the darts board, a wood elf is being hustled, and already owes a significant amount of money to the loud group of humans around him.",
            "The tavern is full of groups of tourists, all admiring a single poster on the bulletin board. Soon you realize they're all adventuring parties, and there is only one job left. They all begin to run out the door to be the first to complete it.",
            'A large cow sits in one end, with a wizard muttering "I\'m sure this never happens babe" in its ear.',
            "The taproom is packed from wall to wall. A regal dwarf bedecked with a large chain is standing on the bar buying everyone drinks and preaching to the merit of the Gundar the great god of revelry.",
        ],
    },
    {
        title:
            "d40 You have heard of this tavern before/eaten there before because...",
        id: "d40youhaveheardofthistavernbeforeeatentherebeforebecause",
        roll: [
            "they make a mean kirschtorte",
            "they really know their pierogies",
            "they are the borscht capital of the world",
            "their reputation for gołąbkis is unrivaled",
            "they put bacon on everything",
            "that one smoking hot waitress",
            "they always have horse parking",
            "the carrot porridge is to die for",
            "No one knows where it is so its usually quiet.",
            "It's open later than anything else in town.",
            "No one except adventurers are brave enough to eat at a place built under the lightning rail so the merchants and needy townsfolk stay away.",
            "They buy whatever meat you bring in and cook it fresh.",
            "They ruthlessly drove the other businesses out of town and you were starving.",
            "Tasty desserts. The cheese-pie is to die for!",
            "Beer selection. They have a great selection of ales.",
            "Homebrew beer. They brew their own dragon-stout in-house!",
            "Meat. The proprietor is a hunter who goes into the woods every day to catch and to kill the main roast.",
            "Beastly decor. The walls are covered in furs, antlers, and beast heads.",
            "Fancy decor. The booths are separated by beautiful lace curtains and a pleasant scent of incense permeates the air.",
            "Heroic tales. The proprietor slayed a dragon.",
            "Sad tales. The barkeep is a stunning noblewoman who eloped with the poor sonofabitch who used to own this place before died.",
            "Sex appeal. The barmaids wear low-cut blouses and/or tight skirts.",
            "Friendly service. The barmaids are real friendly.",
            "Gamblers' den. The dice game is high-stakes.",
            "Freakish staff. The bouncer is half-troll.",
            "Bad-ass staff. The bouncer has a dragon tattoo on his face.",
            "High-end wines. Their wines come from some unpronounceable Elvish island.",
            "Magical drinks. The barkeep is an alchemical wizard who serves up love potions, sleeping draughts, and mustache tonics. (Some might argue that a good mustache tonic is all the love potion one needs.)",
            "Entertainment. The barkeep here plays a fine piano.",
            "Decorations, they have trophies from everywhere.",
            "Reviews, some sod with a pen, paper, and those newfangled word things has written a piece on them.",
            "Nobility, the high society types like it.",
            "Admittance is a status symbol.",
            "People, its where you go to find troubleshooters.",
            "Warmth, the walls magically keep out the chill and snow.",
            "The Dwarves built it.",
            "It was once a library and there is a huge selection of books to read.",
            "It was once a temple and the half dead god who was worshiped there still occasionally tries to smite the defilers, sometimes with more success than others.",
            "They accept a generous line of credit",
            "It's an exotic location, and spelljammers sometimes stop by, bringing trinkets from across the planes.",
        ],
    },
    {
        "id": "sigil_clerks_ward",
        "title": "Sigil Clerks Ward",
        "roll": [
            "About 10 magical tomes start flying through the air with a distressed librarian running after them.",
            "A gnome mage gives a magical performance, which goes horribly wrong (illusion turns real).",
            "A girl cries about her missing dog.",
            "A bard offers to sing a ballad for the PCs.",
            "Signers recruiter.",
            "A man/woman who claims to be innocent begs the PCs for help. He/she is chased by the Harmonium.",
            "Random Baatezu (Default Kyton).",
            "Lamp boys.",
            "A troupe of actors ask the PCs to join them in their next performance to earn a bit of coin.",
            "A noble’s sedan procession.",
            "Random Tanari (Default Vrock).",
            "A Taker asks the PCs for all their money, claiming it is his right. He is insistent but avoids combat.",
            "Sensate recruiter.",
            "A group of 3 advocates rushing to the City Court.",
            "A person inviting the PCs to one of the shops.",
            "A Signer attempts to 'will' the PCs out of existence.",
            "Large house for sale (20,000)",
            "3 Abishai plotting to invade Waterdeep and attack farms.",
            "A lecturer on the Lower Planes (probably a yugoloth) rushing to the Festhall.",
            "Poet battle!",
            "Harmonium patrol: 2+1D4 harmoniums",
            "A public debate.",
            "Fire! Fire!",
            "Fated recruiter.",
            "Roll random encounter in random ward.",
            "A wizard begs the PCs to help him release his bond with a demon.",
            "A small girl selling bronze flowers from Mechanus.",
            "A lost petitioner.",
            "Random Angel (Default Deva).",
            "One of the harlots from the Brothel of Slating Intellectual Lusts.",
            "Dabus.",
            "A druid examines some razorvine and shakes his head.",
            "2 Clerks walking to their office.",
            "A group of 3 sensates asks the PCs to let them experience something new.",
            "The PCs notice a trail of blood that leads into an alley.",
            "Harmonium patrol: 2+1D4 harmoniums",
            "A portal opens and something random appears (a giant slug!), causing havoc.",
            "A figure in a dark cloak asks the PCs to deliver a letter to Factol Erin Darkflame Montgomery.",
            "A man attempts to get the PCs to worship the Lady."
        ]
    },
    {
        "id": "sigil_guild_market_ward",
        "title": "Sigil Guild Market Ward",
        "roll": [
            "Rats! A group of 1D6 (min.2) swarms of cranium rats burst out from one of the nearby buildings/stalls.",
            "Dabus.",
            "Random Angel (Default Deva).",
            "A man shouting the latest offers.",
            "A dead ox causes a gridlock.",
            "A man/woman asks the PCs for directions.",
            "A merchant tries to sell the PCs a worthless trinket.",
            "A drinking contest between two planar creatures.",
            "Transcendent Order recruiter.",
            "Merchant in a heated argument with a customer, with someone picking his/her pocket.",
            "A customer pulls a weapon on a merchant.",
            "Random Baatezu (Default Kyton).",
            "A thieft leaps over a cart and 2 harmonium run after him, toppling it. Merchant screams at them.",
            "Pickpocket!",
            "A merchant chasing a thief.",
            "Someone asks the PCs for help in distributing flyers.",
            "Random Tanari (Default Vrock).",
            "2 Harmonium soldiers on patrol.",
            "A group of Githyanki selling their loot from their latest raid.",
            "A Harmonium chasing a debtor.",
            "A slave trader offers to buy the PCs from one of the PCs.",
            "Indep recruiter.",
            "House for sale (10,000 gp).",
            "A customer argues with a merchant while someone steals something from his/her stall.",
            "Roll random encounter in random ward.",
            "Mercykillers arresting a merchant.",
            "2 Harmonium soldiers on patrol.",
            "Merchant in a heated argument with a customer.",
            "A smug-looking elf tries to sell PCs a portal key to a portal in Lady’s Ward (fake), 100 GP.",
            "The PCs see a wizard banish a genie back into a bottle.",
            "3+1D4 Mindflayers and their (1D4) 1: Human 2: Dwarven 3: Elven 4: Halfling Slaves, from the Prime.",
            "Two Ciphers having a martial battle with crowds watching. They are a blur.",
            "Lamp boys.",
            "A pair of Ciphers going to the Great Gymnasium.",
            "A lost petitioner.",
            "Fell, looking for components.",
            "A harlot.",
            "A candlemaker with a cart full of candles. It moves as it passes the PCs.",
            "A Beholder shopping for something. People give him a wide berth."
        ]
    },
    {
        "id": "sigil_hive_ward",
        "title": "Sigil Hive Ward",
        "roll": [
            "A naked man/woman/boy/girl who thinks one of the PCs is food.",
            "A dustman recruiter.",
            "A collector and his wagon.",
            "Dabus.",
            "Random Baatezu (Default Kyton).",
            "A hungry child walks up to the PCs and dies in front of them.",
            "A group of 5 starving children begging for food.",
            "House for sale (5000 GP).",
            "Lamp boys.",
            "A group of 4 Harmonium soldiers walking really fast and standing tightly together.",
            "Xaositect recruiter.",
            "A mad priest/wizard.",
            "An invitation to be experiments at the Weary Spirit Infirmary.",
            "Random Tanari (Default Vrock).",
            "1+1D6 Thugs.",
            "A group of laborers dragging a Tanar’ri cache.",
            "A beggar hoard (10+1D6)",
            "5 Thugs.",
            "A gruesome murder.",
            "Bleak Cabal recruiter.",
            "A woman peddling something unappetizing (boiled rat’s feet).",
            "5 collectors hoping to cash in the PCs as jink (by putting them in the dead book).",
            "A man with 3 bottles of watered-down ale looking to swap them out for some food.",
            "An ooze portal (Dex save DC: 15).",
            "Roll random encounter in random ward.",
            "A murder.",
            "Anarchist recruiter.",
            "Collector being threatened by 2 Harmonium.",
            "3 Thugs.",
            "A man peddling something gross (children’s fingers).",
            "2 thugs fighting.",
            "A collector who has found a Tanar’ri red steel weapon (+1 dmg) (default: longsword).",
            "Random Angel (Default Deva).",
            "A lost petitioner.",
            "A dirty harlot.",
            "6 Thugs and their leader.",
            "Reekwind, the cursed.",
            "A person gets tossed out of a nearby home, maimed and mutilated.",
            "A man/woman crawling on the ground screaming, having lost his/her left arm and leg to Kadyx."
        ]
    },
    {
        "id": "sigil_ladys_ward",
        "title": "Sigil Ladys Ward",
        "roll": [
            "Execution by Wurm!",
            "A thief looking for accomplices for a big heist in the Lady’s Ward.",
            "A newly rich man who has struck gold and is surveying the Lady’s Ward for a place to live.",
            "A noble woman who offers to pay a PC 100gp for her to test her poisoned blade on him/her.",
            "A beggar getting dragged off the streets by the Harmonium.",
            "Guvner recruiter.",
            "Mercykiller recruiter.",
            "Random Angel (Default Deva).",
            "Random Tanari (Default Vrock).",
            "A drug dealer.",
            "A very public attack by assassins on a noble’s sedan.",
            "A street sale on jewellery.",
            "Pair of Mercykillers. Issues stiff warning to PCs, questions them.",
            "Harmonium patrol: Captain plus 3+1D6 harmoniums. Will question PC’s purpose in this ward.",
            "A priest looking for donations.",
            "A noble’s sedan procession.",
            "2 Guvners arguing the state of Sigil’s laws.",
            "A poet.",
            "A grizzled bariaur with a tale to tell of an epic adventure he had in Ysgard.",
            "A prostitute loudly calling after a very embarassed noble man about not paying.",
            "A merchant peddling a random magic item (default: Dragonslayer).",
            "A well-dressed lady looking for a portal.",
            "A Dabus looking for his lost hammer.",
            "A nobleman/noblewoman needs help finding a robber.",
            "Roll random encounter in random ward.",
            "A nobleman/noblewoman needs help assassinating a rival.",
            "A large group of 24 Harmonium + leader doing marching drills.",
            "A mansion for sale (30,000 Gp).",
            "Harmonium recruiter.",
            "A doomguard surveying the ward and exclaiming its eventual demise.",
            "A person who is sick of being in the Harmonium.",
            "Lamp boys.",
            "Random Baatezu (Default Kyton).",
            "An airship (???)",
            "A pair of Mercykillers chasing a criminal.",
            "A pair of Harmonium fighting a fiend resisting arrest, who claims innocence.",
            "A merchant getting hauled out of his streetside stall by Mercykillers.",
            "The Wurm getting taken out for a walk.",
            "The Lady of Pain."
        ]
    },
    {
        "id": "sigil_lower_ward",
        "title": "Sigil Lower Ward",
        "roll": [
            "A priest of Talos from Waterdeep practicing Call Lightning, thinking the smog is a stormcloud.",
            "Dabus.",
            "Lamp boys.",
            "A noble from the Lady’s Ward in a Sedan chair, stops the PCs and complains about the smog.",
            "A Xaositect inviting the PCs to take a dive with him in The Ditch.",
            "5 Wererats out scavenging for skulls for Lothar.",
            "A man/woman looking for someone to free him/her from slavery.",
            "A tiefling hawking her wares (she sells artisan’s tools and gaming sets).",
            "A man auctioneering animals who are clearly dying from the smog.",
            "Drunk foundrymen (2+1D4 of them).",
            "A Godsman conversing with a Dabus on their philosophy.",
            "Harmonium patrol (2 of them).",
            "A Godsmen recruiter.",
            "Githyanki Warrior and Githzerai Monk bumping into each other.",
            "A public execution by the Mercykillers.",
            "A bunch of smog falls onto the street - Con Save DC: 10 or chokes and takes 1D10 damage.",
            "A beggar.",
            "An explosion is heard from the Great Foundry, everyone is silent for a while then resumes daily life.",
            "1D6 Modrons making their way to the Society of the Luminiferous Aether, queries PCs on something.",
            "A woman collapses, dead, due to the smog. She has 2D6 gp on her and a note to her daughter.",
            "A godsmen greets the PCs and makes small talk.",
            "A godsman nods to one of the PCs and presses a small hammer with the name 'Theoden' engraved.",
            "The smog thickens! Con Save DC: 10 or chokes and takes 1D10 damage.",
            "A petitioner (Random).",
            "Random Tanari (Default Vrock).",
            "Roll random encounter in random ward.",
            "Random Baatezu (Default Kyton).",
            "Random Angel (Default Deva).",
            "Harmonium patrol (2D4).",
            "Drunks (2D4).",
            "A Doomguard and Mercykiller arguing.",
            "Doomguard recruiter.",
            "A wererat out looking for skulls for Lothar.",
            "An old dwarf who offers to enchant one of the PC’s weapons.",
            "Doomguard selling a variety of swords to anyone, preaching philosophy at the same time.",
            "A legal slave auction (guarded by 4 Harmonium).",
            "An adventuring party steps into a portal! It remains open for 10 seconds.",
            "Street sale of armor from Godsmen’s forge.",
            "1 Githyanki Knight and 4 Githyanki Warriors questioning people about a missing Githzerai, Dak’kon."
        ]
    },
    // end of settlements
];

