// skills.js
//
// Random Skill: an invented technique, knack or trained art for a character.
//
// The name is rolled from two halves and the rest from eleven independent
// facets, so the pieces recombine rather than repeat. Many results carry an
// inline sub-roll of their own, so even the same entry comes back different.
// The point is that two rolls are almost never alike.

top.skills = [
  {
    title: "The skill is called",
    id: "d20skillnamefirst_skills",
    roll: [
      "Ashfall",
      "Bitterroot",
      "Candleflame",
      "Deadhand",
      "Emberwake",
      "Flintcut",
      "Gravebind",
      "Hollowstep",
      "Ironmoth",
      "Lastlight",
      "Mirrorbreath",
      "Nightfeather",
      "Owlsight",
      "Quietwater",
      "Rusthook",
      "Saltwind",
      "Thornlatch",
      "Underhearth",
      "Widowknot",
      "Yellowsong",
    ],
  },
  {
    title: "and the rest of the name",
    id: "d20skillnamesecond_skills",
    roll: [
      "Stance",
      "Gambit",
      "Working",
      "Cant",
      "Measure",
      "Reckoning",
      "Grip",
      "Turning",
      "Whisper",
      "Ledger",
      "Wager",
      "Vigil",
      "Sleight",
      "Bargain",
      "Traverse",
      "Chord",
      "Suture",
      "Feint",
      "Reading",
      "Undoing",
    ],
  },
  {
    title: "Discipline",
    id: "d16discipline_skills",
    roll: [
      "A martial form, drilled until the body does it without asking.",
      "A craft secret, the kind guilds fine you for teaching.",
      "A scholarly technique, half theory and half stubbornness.",
      "A devotional practice, and it stops working if you stop believing.",
      "A thief knack, learned in the dark and never written down.",
      "A sailor trick, useless more than a mile from open water.",
      "A hedge-witch remedy that predates every temple in the region.",
      "A courtly art, all posture and implication.",
      "A wilderness read, learned from an animal rather than a person.",
      "A gambler method, and mathematically it should not work.",
      "A mourning rite, performed properly only for the dead.",
      "A physician procedure, gruesome and effective.",
      "A drover discipline for handling things larger than yourself.",
      "A siege engineer habit of seeing where a thing will fail.",
      "A cook instinct, which turns out to generalise alarmingly.",
      "A prisoner craft, invented because there was nothing else to do.",
    ],
  },
  {
    title: "What it lets you do",
    id: "d20effect_skills",
    roll: [
      "Read the last strong emotion left in a room.",
      "Land a blow that arrives a half-second before you move.",
      "Convince one object that it is a different object, briefly.",
      "Hear the name a person was called as a child.",
      "Undo a knot, lock or binding by understanding how it was made.",
      "Borrow a memory from someone and hold it for an hour.",
      "Find the exact spot where a structure wants to break.",
      "Walk on a surface that should not hold you, as long as you keep talking.",
      "Tell precisely how long ago something died.",
      "Copy a stranger handwriting after seeing one line of it.",
      "Calm any animal by matching its breathing.",
      "Know which of several people in a room is lying, but not about what.",
      "Repair something (d4): 1. quickly and badly; 2. slowly and beautifully; 3. so it is stronger than new; 4. so it looks whole but is not",
      "Make yourself forgettable, so witnesses disagree about you afterwards.",
      "Guess a stranger trade, home region and worst habit from their hands.",
      "Push a small amount of pain from yourself into an object.",
      "Sense running water, buried metal or open air through solid stone.",
      "Speak for one minute in a language you have only heard, not learned.",
      "Fall any distance and land badly rather than fatally.",
      "Persuade a fire to burn (d4): 1. slower; 2. hotter; 3. quietly; 4. in a colour it should not",
    ],
  },
  {
    title: "How it is performed",
    id: "d20performance_skills",
    roll: [
      "A precise sequence of breaths, counted under your breath.",
      "A short phrase said backwards.",
      "Drawing a shape in the air with two fingers.",
      "Tapping a rhythm against your own sternum.",
      "Holding an object that belonged to someone dead.",
      "A full second of absolute stillness, which is harder than it sounds.",
      "Humming a note and holding it until it hurts.",
      "Chewing something bitter and refusing to spit it out.",
      "Making and holding eye contact without blinking.",
      "Writing the intent down, then destroying the paper.",
      "Pressing a scar, old wound or tattoo.",
      "Turning a ring, coin or knife exactly three times.",
      "Naming aloud something you have lost.",
      "A single step taken in the wrong direction first.",
      "Cutting yourself just enough to concentrate the mind.",
      "Whistling a tune you were taught but never understood.",
      "Kneeling, which is inconvenient and non-negotiable.",
      "Pouring out a measure of drink for nobody in particular.",
      "Closing one eye and keeping it closed throughout.",
      "Saying the true name of the thing, which you must already know.",
    ],
  },
  {
    title: "What it costs",
    id: "d16cost_skills",
    roll: [
      "Nothing at all, which worries people who understand it.",
      "A day of appetite. Food tastes of paper afterwards.",
      "A memory, chosen at random, gone for good.",
      "Your voice for (d6): 1. a minute; 2. an hour; 3. until dawn; 4. a day; 5. three days; 6. as long as it takes",
      "A small amount of blood, and it must be your own.",
      "Sleep. You will not get any tonight.",
      "One thing you own must be given away before nightfall.",
      "A year of your life, though it is a long life and you can spare a few.",
      "Warmth. You will be cold for hours no matter what you do.",
      "The ability to lie until the next sunrise.",
      "A truth, spoken aloud to whoever is nearest.",
      "Physical exhaustion out of all proportion to the effort.",
      "Your sense of (d4): 1. smell; 2. taste; 3. balance; 4. direction, for a day",
      "Silence for an hour afterwards, or it comes undone.",
      "Someone else luck, which they will notice eventually.",
      "Nothing yet. The bill is being kept somewhere.",
    ],
  },
  {
    title: "Drawback",
    id: "d20drawback_skills",
    roll: [
      "It works twice as well on people you like, which is a problem.",
      "It is loud, in a way only animals and children can hear.",
      "It leaves a mark that fades over a week.",
      "It fails completely if anyone is watching and knows what it is.",
      "It is illegal in three cities you would rather not name.",
      "Something notices every time you use it.",
      "It works, then works again an hour later without being asked.",
      "You cannot use it twice on the same person, ever.",
      "It gets harder each time until you stop for a month.",
      "Water ruins it. Rain counts.",
      "It makes you tell the truth for a while afterwards.",
      "The effect is real, but you can never remember doing it.",
      "It offends the devout, who are numerous and organised.",
      "It only works when you are (d4): 1. hungry; 2. frightened; 3. injured; 4. entirely calm",
      "It stopped working once, for a month, and nobody knows why.",
      "Iron nearby weakens it. Cold iron stops it dead.",
      "It attracts the attention of anyone else who knows the skill.",
      "It ages the tool, garment or weapon you use it through.",
      "You must never explain it to anyone, or it leaves you.",
      "It is slightly wrong every seventh time, and you cannot count reliably.",
    ],
  },
  {
    title: "Reach",
    id: "d10reach_skills",
    roll: [
      "Touch only, skin to skin.",
      "Arm length, no further.",
      "As far as you can throw a stone.",
      "Whatever you can see clearly.",
      "Anything within the sound of your voice.",
      "The room you are standing in, walls included.",
      "One named person, wherever they are, if you have met.",
      "Whatever is currently touching the ground you are touching.",
      "Only yourself, which is more limiting than it sounds.",
      "Line of sight, but it weakens with every yard.",
    ],
  },
  {
    title: "How long it lasts",
    id: "d10duration_skills",
    roll: [
      "An instant. Blink and it has already happened.",
      "As long as you hold your breath.",
      "A count of ten, no matter how fast you count.",
      "Until you speak.",
      "One hour, precisely, and it ends mid-sentence if it has to.",
      "Until the next sunrise or sunset, whichever comes first.",
      "Until someone says your name aloud.",
      "Three days, whether you want it or not.",
      "Permanently, but only ever once per subject.",
      "As long as you keep paying the cost, and not a moment longer.",
    ],
  },
  {
    title: "Where it came from",
    id: "d16origin_skills",
    roll: [
      "Taught by a parent who refused to say where they learned it.",
      "Copied from a book that has since burned.",
      "Worked out alone, over years, from first principles.",
      "Traded for, and the other party got the better of the deal.",
      "Won in a wager against someone who should not have gambled.",
      "Inherited with a house, along with the debts.",
      "Learned in a prison, from a cellmate who did not survive.",
      "Given freely by a stranger who then walked into the sea.",
      "Beaten into you by a teacher you still have nightmares about.",
      "Discovered by accident while trying to do something else.",
      "Remembered from a dream you had for nine nights running.",
      "Reconstructed from a single surviving fragment of a tradition.",
      "Bought at auction as a curiosity, with instructions attached.",
      "Extracted from a dying enemy who thought it was a mercy.",
      "Passed down a family line that ends with you.",
      "It arrived one morning, fully formed, and you have never questioned it.",
    ],
  },
  {
    title: "The tell",
    id: "d20tell_skills",
    roll: [
      "Your breath fogs, whatever the weather.",
      "Nearby candles lean towards you.",
      "The smell of cut grass, out of nowhere.",
      "Your shadow lags a moment behind you.",
      "Dogs stop barking within earshot.",
      "A faint taste of copper for everyone in the room.",
      "Your eyes lose their colour for a few seconds.",
      "Dust in the air stops moving.",
      "A sound like a distant door closing.",
      "The temperature drops by a few degrees.",
      "Small objects nearby turn to face you.",
      "Your voice briefly sounds like someone else.",
      "Insects go quiet, then very loud.",
      "Ink runs, milk turns, and bread goes stale a day early.",
      "Everyone present feels watched from above.",
      "A smell of (d4): 1. wet stone; 2. burnt sugar; 3. old paper; 4. the sea",
      "Nothing whatsoever, which is itself unnerving to those who know.",
      "The nearest mirror shows the room a half-second late.",
      "Your hands shake for a full minute afterwards.",
      "Somebody nearby says a word they did not intend to say.",
    ],
  },
  {
    title: "How good you are at it",
    id: "d12mastery_skills",
    roll: [
      "Barely. It has worked three times and failed nine.",
      "Reliably on a good day, in good conditions, unobserved.",
      "Well enough to teach it badly.",
      "Well enough that you have stopped thinking about it.",
      "Better than the person who taught you, which caused trouble.",
      "The best in the city, though the competition is two people.",
      "Competent, but you have never used it under real pressure.",
      "You are the only living practitioner, as far as you know.",
      "You were excellent. Something happened. You are relearning.",
      "Good enough to sell, and you have.",
      "So natural you assumed everyone could do it until recently.",
      "Uneven: brilliant in (d4): 1. a crowd; 2. a fight; 3. silence; 4. the dark, and poor otherwise",
    ],
  },
  {
    title: "One more thing",
    id: "d20quirk_skills",
    roll: [
      "Someone is looking for whoever can do this. They are not friendly.",
      "There is a wrong way to do it that nobody has told you about.",
      "It has a second use you have not discovered.",
      "A rival practitioner believes you stole it from them.",
      "It runs in families, and you have found a cousin you did not know about.",
      "A temple has opinions about it, all of them bad.",
      "It works on the dead, which you learned by accident.",
      "You have written down half of it, and lost that half.",
      "It cannot be performed in the place it was invented.",
      "There is a song about it, and the song is a set of instructions.",
      "Using it near another practitioner makes both versions stronger.",
      "A noble house pays well for demonstrations and asks no questions.",
      "It is slowly changing you in a way you have not noticed.",
      "The last person to master it disappeared, and left a note for you.",
      "It fails on the (d4): 1. first; 2. last; 3. shortest; 4. longest day of the year",
      "You are one component short of a much greater version of it.",
      "Children can learn it in a week. Adults take a decade.",
      "It is worth a great deal of money to exactly one buyer.",
      "Something in the wilderness does it better, and knows you exist.",
      "There is nothing else. It is a useful thing you can do.",
    ],
  },
];
