// srd items
//
//


top.srd_items = [


  {"title": "Adamantine Armor", "id":"adamantinearmor_items",  "description":"Armor (medium or heavy, but not hide), uncommon", "text":"This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any critical hit against you becomes a normal hit." },
  {"title": "Ammunition, +1, +2, or +3", "id":"ammunition+1+2or+3_items",  "description":"Weapon (any ammunition), uncommon (+1), rare (+2), or very rare (+3)", "text":"You have a bonus to attack and damage rolls made with this piece of magic ammunition. The bonus is determined by the rarity of the ammunition. Once it hits a target, the ammunition is no longer magical." },
  {"title": "Amulet of Health", "id":"amuletofhealth_items",  "description":"Wondrous item, rare (requires attunement)", "text":"Your Constitution score is 19 while you wear this amulet. It has no effect on you if your Constitution is already 19 or higher." },
  {"title": "Amulet of Proof against Detection and Location", "id":"amuletofproofagainstdetectionandlocation_items",  "description":"Wondrous item, uncommon (requires attunement)", "text":"While wearing this amulet, you are hidden from divination magic. You can’t be targeted by such magic or perceived through magical scrying sensors." },
  {"title": "Amulet of the Planes", "id":"amuletoftheplanes_items",  "description":"Wondrous item, very rare (requires attunement)", "text":"While wearing this amulet, you can use an action to name a location that you are familiar with on another plane of existence. Then make a DC 15 Intelligence check. On a successful check, you cast the plane shift spell. On a failure, you and each creature and object within 15 feet of you travel to a random destination. Roll a d100. On a 1–60, you travel to a random location on the plane you named. On a 61–100, you travel to a randomly determined plane of existence." },
  {"title": "Animated Shield", "id":"animatedshield_items",  "description":"Armor (shield), very rare (requires attunement)", "text":"While holding this shield, you can speak its command word as a bonus action to cause it to animate. The shield leaps into the air and hovers in your space to protect you as if you were wielding it, leaving your hands free. The shield remains animated for 1 minute, until you use a bonus action to end this effect, or until you are incapacitated or die, at which point the shield falls to the ground or into your hand if you have one free." },

  {"title": "Apparatus of the Crab", "id":"apparatusofthecrab_items",  "description":"Wondrous item, legendary", "text":"This item first appears to be a Large sealed iron barrel weighing 500 pounds. The barrel has a hidden catch, which can be found with a successful DC 20 Intelligence (Investigation) check. Releasing the catch unlocks a hatch at one end of the barrel, allowing two Medium or smaller creatures to crawl inside. Ten levers are set in a row at the far end, each in a neutral position, able to move either up or down. When certain levers are used, the apparatus transforms to resemble a giant lobster.<br>The apparatus of the Crab is a Large object with the following statistics:<br><b>Armor Class:</b> 20<br><b>Hit Points:</b> 200<br><b>Speed:</b> 30 ft., swim 30 ft. (or 0 ft. for both if the legs<br>and tail aren’t extended)<br><b>Damage Immunities</b>: poison, psychic<br>To be used as a vehicle, the apparatus requires one pilot. While the apparatus’s hatch is closed, the compartment is airtight and watertight. The compartment holds enough air for 10 hours of breathing, divided by the number of breathing creatures inside.<br>The apparatus floats on water. It can also go underwater to a depth of 900 feet. Below that, the vehicle takes 2d6 bludgeoning damage per minute from pressure.<br>A creature in the compartment can use an action to move as many as two of the apparatus’s levers up or down. After each use, a lever goes back to its neutral position. Each lever, from left to right, functions as shown in the Apparatus of the Crab Levers table.<br>Apparatus of the Crab Levers:<br>[table]" },
  {"title": "Armor, +1, +2, or +3", "id":"armor+1+2or+3_items",  "description":"Armor (light, medium, or heavy), rare (+1), very rare (+2), or legendary (+3)", "text":"You have a bonus to AC while wearing this armor. The bonus is determined by its rarity." },
  {"title": "Armor of Invulnerability", "id":"armorofinvulnerability_items",  "description":"Armor (plate), legendary (requires attunement)", "text":"You have resistance to nonmagical damage while you wear this armor. Additionally, you can use an action to make yourself immune to nonmagical damage for 10 minutes or until you are no longer wearing the armor. Once this special action is used, it can’t be used again until the next dawn." },
  {"title": "Armor of Resistance", "id":"armorofresistance_items",  "description":"Armor (light, medium, or heavy), rare (requires attunement)", "text":"You have resistance to one type of damage while you wear this armor. The GM chooses the type or determines it randomly from the options below.<br>[table]" },
   




]
