// srd items
//
//

top.srd_items = [
  {
    id: "adamantinearmor_items",
    title: "Adamantine Armor",
    name: "Adamantine Armor",
    type: "Armor (medium or heavy, but not hide)",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 150",
    description: "Armor (medium or heavy, but not hide). Uncommon",
    text: "Source: DMG 150",
  },
  {
    id: "alchemyjug_items",
    title: "Alchemy Jug",
    name: "Alchemy Jug",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 150",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 150",
  },
  {
    id: "ammunition+1+2or+3_items",
    title: "Ammunition, +1, +2, or +3",
    name: "Ammunition, +1, +2, or +3",
    type: "Weapon (any ammunition)",
    rarity: "Uncommon (+1), rare (+2), or very rare (+3)",
    attunement: "no",
    page: "dmg 150",
    description:
      "Weapon (any ammunition). Uncommon (+1), rare (+2), or very rare (+3)",
    text: "Source: DMG 150",
  },
  {
    id: "amuletofhealth_items",
    title: "Amulet of Health",
    name: "Amulet of Health",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 150",
    description: "Wondrous Item. Rare. requires attunement",
    text: "Source: DMG 150",
  },
  {
    id: "amuletofproofagainstdetectionandlocation_items",
    title: "Amulet of Proof Against Detection and Location",
    name: "Amulet of Proof Against Detection and Location",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 150",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 150",
  },
  {
    id: "amuletoftheplanes_items",
    title: "Amulet of the Planes",
    name: "Amulet of the Planes",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 150",
    description: "Wondrous Item. Very Rare. requires attunement",
    text: "Source: DMG 150",
  },
  {
    id: "animatedshield_items",
    title: "Animated Shield",
    name: "Animated Shield",
    type: "Armor (shield)",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 151",
    description: "Armor (shield). Very Rare. requires attunement",
    text: "Source: DMG 151",
  },
  {
    id: "apparatusofkwalish_items",
    title: "Apparatus of Kwalish",
    name: "Apparatus of Kwalish",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "no",
    page: "dmg 151",
    description: "Wondrous Item. Legendary",
    text: "Source: DMG 151",
  },
  {
    id: "armorofinvulnerability_items",
    title: "Armor of Invulnerability",
    name: "Armor of Invulnerability",
    type: "Armor (plate)",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 152",
    description: "Armor (plate). Legendary. requires attunement",
    text: "Source: DMG 152",
  },
  {
    id: "armorofresistance_items",
    title: "Armor of Resistance",
    name: "Armor of Resistance",
    type: "Armor",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 152",
    description: "Armor. Rare. requires attunement",
    text: "Source: DMG 152",
  },
  {
    id: "armorofvulnerability_items",
    title: "Armor of Vulnerability",
    name: "Armor of Vulnerability",
    type: "Armor (plate)",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 152",
    description: "Armor (plate). Rare. requires attunement",
    text: "Source: DMG 152",
  },
  {
    id: "armor+1+2or+3_items",
    title: "Armor, +1, +2, or +3",
    name: "Armor, +1, +2, or +3",
    type: "Armor (light, medium, or heavy)",
    rarity: "Rare (+1), very rare (+2), or legendary (+3)",
    attunement: "no",
    page: "dmg 152",
    description:
      "Armor (light, medium, or heavy). Rare (+1), very rare (+2), or legendary (+3)",
    text: "Source: DMG 152",
  },
  {
    id: "arrowofslaying_items",
    title: "Arrow of Slaying",
    name: "Arrow of Slaying",
    type: "Weapon (arrow)",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 152",
    description: "Weapon (arrow). Very Rare",
    text: "Source: DMG 152",
  },
  {
    id: "arrowcatchingshield_items",
    title: "Arrow-catching Shield",
    name: "Arrow-catching Shield",
    type: "Armor (shield)",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 152",
    description: "Armor (shield). Rare. requires attunement",
    text: "Source: DMG 152",
  },
  {
    id: "bagofbeans_items",
    title: "Bag of Beans",
    name: "Bag of Beans",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 152",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 152",
  },
  {
    id: "bagofdevouring_items",
    title: "Bag of Devouring",
    name: "Bag of Devouring",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 153",
    description: "Wondrous Item. Very Rare",
    text: "Source: DMG 153",
  },
  {
    id: "bagofholding_items",
    title: "Bag of Holding",
    name: "Bag of Holding",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 153",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 153",
  },
  {
    id: "bagoftricks_items",
    title: "Bag of Tricks",
    name: "Bag of Tricks",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 154",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 154",
  },
  {
    id: "beadofforce_items",
    title: "Bead of Force",
    name: "Bead of Force",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 154",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 154",
  },
  {
    id: "beltofcloudgiantstrength_items",
    title: "Belt of Cloud Giant Strength",
    name: "Belt of Cloud Giant Strength",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 155",
    description: "Wondrous Item. Legendary. requires attunement",
    text: "Source: DMG 155",
  },
  {
    id: "beltofdwarvenkind_items",
    title: "Belt of Dwarvenkind",
    name: "Belt of Dwarvenkind",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 155",
    description: "Wondrous Item. Rare. requires attunement",
    text: "Source: DMG 155",
  },
  {
    id: "beltoffiregiantstrength_items",
    title: "Belt of Fire Giant Strength",
    name: "Belt of Fire Giant Strength",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 155",
    description: "Wondrous Item. Very Rare. requires attunement",
    text: "Source: DMG 155",
  },
  {
    id: "beltoffrostgiantstrength_items",
    title: "Belt of Frost Giant Strength",
    name: "Belt of Frost Giant Strength",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 155",
    description: "Wondrous Item. Very Rare. requires attunement",
    text: "Source: DMG 155",
  },
  {
    id: "beltofhillgiantstrength_items",
    title: "Belt of Hill Giant Strength",
    name: "Belt of Hill Giant Strength",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 155",
    description: "Wondrous Item. Rare. requires attunement",
    text: "Source: DMG 155",
  },
  {
    id: "beltofstonegiantstrength_items",
    title: "Belt of Stone Giant Strength",
    name: "Belt of Stone Giant Strength",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 155",
    description: "Wondrous Item. Very Rare. requires attunement",
    text: "Source: DMG 155",
  },
  {
    id: "beltofstormgiantstrength_items",
    title: "Belt of Storm Giant Strength",
    name: "Belt of Storm Giant Strength",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 155",
    description: "Wondrous Item. Legendary. requires attunement",
    text: "Source: DMG 155",
  },
  {
    id: "berserkeraxe_items",
    title: "Berserker Axe",
    name: "Berserker Axe",
    type: "Weapon (any axe)",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 155",
    description: "Weapon (any axe). Rare. requires attunement",
    text: "Source: DMG 155",
  },
  {
    id: "bootsofelvenkind_items",
    title: "Boots of Elvenkind",
    name: "Boots of Elvenkind",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 155",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 155",
  },
  {
    id: "bootsoflevitation_items",
    title: "Boots of Levitation",
    name: "Boots of Levitation",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 155",
    description: "Wondrous Item. Rare. requires attunement",
    text: "Source: DMG 155",
  },
  {
    id: "bootsofspeed_items",
    title: "Boots of Speed",
    name: "Boots of Speed",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 155",
    description: "Wondrous Item. Rare. requires attunement",
    text: "Source: DMG 155",
  },
  {
    id: "bootsofstridingandspringing_items",
    title: "Boots of Striding and Springing",
    name: "Boots of Striding and Springing",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 156",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 156",
  },
  {
    id: "bootsofthewinterlands_items",
    title: "Boots of the Winterlands",
    name: "Boots of the Winterlands",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 156",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 156",
  },
  {
    id: "bowlofcommandingwaterelementals_items",
    title: "Bowl of Commanding Water Elementals",
    name: "Bowl of Commanding Water Elementals",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 156",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 156",
  },
  {
    id: "bracersofarchery_items",
    title: "Bracers of Archery",
    name: "Bracers of Archery",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 156",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 156",
  },
  {
    id: "bracersofdefense_items",
    title: "Bracers of Defense",
    name: "Bracers of Defense",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 156",
    description: "Wondrous Item. Rare. requires attunement",
    text: "Source: DMG 156",
  },
  {
    id: "brazierofcommandingfireelementals_items",
    title: "Brazier of Commanding Fire Elementals",
    name: "Brazier of Commanding Fire Elementals",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 156",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 156",
  },
  {
    id: "broochofshielding_items",
    title: "Brooch of Shielding",
    name: "Brooch of Shielding",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 156",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 156",
  },
  {
    id: "broomofflying_items",
    title: "Broom of Flying",
    name: "Broom of Flying",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 156",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 156",
  },
  {
    id: "candleofinvocation_items",
    title: "Candle of Invocation",
    name: "Candle of Invocation",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 157",
    description: "Wondrous Item. Very Rare. requires attunement",
    text: "Source: DMG 157",
  },
  {
    id: "capofwaterbreathing_items",
    title: "Cap of Water Breathing",
    name: "Cap of Water Breathing",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 157",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 157",
  },
  {
    id: "capeofthemountebank_items",
    title: "Cape of the Mountebank",
    name: "Cape of the Mountebank",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 157",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 157",
  },
  {
    id: "carpetofflying_items",
    title: "Carpet of Flying",
    name: "Carpet of Flying",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 157",
    description: "Wondrous Item. Very Rare",
    text: "Source: DMG 157",
  },
  {
    id: "censerofcontrollingairelementals_items",
    title: "Censer of Controlling Air Elementals",
    name: "Censer of Controlling Air Elementals",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 158",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 158",
  },
  {
    id: "chimeofopening_items",
    title: "Chime of Opening",
    name: "Chime of Opening",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 158",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 158",
  },
  {
    id: "circletofblasting_items",
    title: "Circlet of Blasting",
    name: "Circlet of Blasting",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 158",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 158",
  },
  {
    id: "cloakofarachnida_items",
    title: "Cloak of Arachnida",
    name: "Cloak of Arachnida",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 158",
    description: "Wondrous Item. Very Rare. requires attunement",
    text: "Source: DMG 158",
  },
  {
    id: "cloakofdisplacement_items",
    title: "Cloak of Displacement",
    name: "Cloak of Displacement",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 158",
    description: "Wondrous Item. Rare. requires attunement",
    text: "Source: DMG 158",
  },
  {
    id: "cloakofelvenkind_items",
    title: "Cloak of Elvenkind",
    name: "Cloak of Elvenkind",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 158",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 158",
  },
  {
    id: "cloakofinvisibility_items",
    title: "Cloak of Invisibility",
    name: "Cloak of Invisibility",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 158",
    description: "Wondrous Item. Legendary. requires attunement",
    text: "Source: DMG 158",
  },
  {
    id: "cloakofprotection_items",
    title: "Cloak of Protection",
    name: "Cloak of Protection",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 159",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 159",
  },
  {
    id: "cloakofthebat_items",
    title: "Cloak of the Bat",
    name: "Cloak of the Bat",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 159",
    description: "Wondrous Item. Rare. requires attunement",
    text: "Source: DMG 159",
  },
  {
    id: "cloakofthemantaray_items",
    title: "Cloak of the Manta Ray",
    name: "Cloak of the Manta Ray",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 159",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 159",
  },
  {
    id: "crystalball_items",
    title: "Crystal Ball",
    name: "Crystal Ball",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 159",
    description: "Wondrous Item. Very Rare. requires attunement",
    text: "Source: DMG 159",
  },
  {
    id: "crystalballofmindreading_items",
    title: "Crystal Ball of Mind Reading",
    name: "Crystal Ball of Mind Reading",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 159",
    description: "Wondrous Item. Legendary. requires attunement",
    text: "Source: DMG 159",
  },
  {
    id: "crystalballoftelepathy_items",
    title: "Crystal Ball of Telepathy",
    name: "Crystal Ball of Telepathy",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 159",
    description: "Wondrous Item. Legendary. requires attunement",
    text: "Source: DMG 159",
  },
  {
    id: "crystalballoftrueseeing_items",
    title: "Crystal Ball of True Seeing",
    name: "Crystal Ball of True Seeing",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 159",
    description: "Wondrous Item. Legendary. requires attunement",
    text: "Source: DMG 159",
  },
  {
    id: "cubeofforce_items",
    title: "Cube of Force",
    name: "Cube of Force",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 159",
    description: "Wondrous Item. Rare. requires attunement",
    text: "Source: DMG 159",
  },
  {
    id: "cubicgate_items",
    title: "Cubic Gate",
    name: "Cubic Gate",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "no",
    page: "dmg 160",
    description: "Wondrous Item. Legendary",
    text: "Source: DMG 160",
  },
  {
    id: "daernsinstantfortress_items",
    title: "Daern's Instant Fortress",
    name: "Daern's Instant Fortress",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 160",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 160",
  },
  {
    id: "daggerofvenom_items",
    title: "Dagger of Venom",
    name: "Dagger of Venom",
    type: "Weapon (dagger)",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 161",
    description: "Weapon (dagger). Rare",
    text: "Source: DMG 161",
  },
  {
    id: "dancingsword_items",
    title: "Dancing Sword",
    name: "Dancing Sword",
    type: "Weapon (any sword)",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 161",
    description: "Weapon (any sword). Very Rare. requires attunement",
    text: "Source: DMG 161",
  },
  {
    id: "decanterofendlesswater_items",
    title: "Decanter of Endless Water",
    name: "Decanter of Endless Water",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 161",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 161",
  },
  {
    id: "deckofillusions_items",
    title: "Deck of Illusions",
    name: "Deck of Illusions",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 161",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 161",
  },
  {
    id: "deckofmanythings_items",
    title: "Deck of Many Things",
    name: "Deck of Many Things",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "no",
    page: "dmg 162",
    description: "Wondrous Item. Legendary",
    text: "Source: DMG 162",
  },
  {
    id: "defender_items",
    title: "Defender",
    name: "Defender",
    type: "Weapon (any sword)",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 164",
    description: "Weapon (any sword). Legendary. requires attunement",
    text: "Source: DMG 164",
  },
  {
    id: "demonarmor_items",
    title: "Demon Armor",
    name: "Demon Armor",
    type: "Armor (plate)",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 165",
    description: "Armor (plate). Very Rare. requires attunement",
    text: "Source: DMG 165",
  },
  {
    id: "dimensionalshackles_items",
    title: "Dimensional Shackles",
    name: "Dimensional Shackles",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 165",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 165",
  },
  {
    id: "dragonscalemail_items",
    title: "Dragon Scale Mail",
    name: "Dragon Scale Mail",
    type: "Armor (scale mail)",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 165",
    description: "Armor (scale mail). Very Rare. requires attunement",
    text: "Source: DMG 165",
  },
  {
    id: "dragonslayer_items",
    title: "Dragon Slayer",
    name: "Dragon Slayer",
    type: "Weapon (any sword)",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 166",
    description: "Weapon (any sword). Rare",
    text: "Source: DMG 166",
  },
  {
    id: "driftglobe_items",
    title: "Driftglobe",
    name: "Driftglobe",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 166",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 166",
  },
  {
    id: "dustofdisappearance_items",
    title: "Dust of Disappearance",
    name: "Dust of Disappearance",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 166",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 166",
  },
  {
    id: "dustofdryness_items",
    title: "Dust of Dryness",
    name: "Dust of Dryness",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 166",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 166",
  },
  {
    id: "dustofsneezingandchoking_items",
    title: "Dust of Sneezing and Choking",
    name: "Dust of Sneezing and Choking",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 166",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 166",
  },
  {
    id: "dwarvenplate_items",
    title: "Dwarven Plate",
    name: "Dwarven Plate",
    type: "Armor (plate)",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 167",
    description: "Armor (plate). Very Rare",
    text: "Source: DMG 167",
  },
  {
    id: "dwarventhrower_items",
    title: "Dwarven Thrower",
    name: "Dwarven Thrower",
    type: "Weapon (warhammer)",
    rarity: "Very Rare",
    attunement: "requires attunement by a dwarf",
    page: "dmg 167",
    description:
      "Weapon (warhammer). Very Rare. requires attunement by a dwarf",
    text: "Source: DMG 167",
  },
  {
    id: "efreetibottle_items",
    title: "Efreeti Bottle",
    name: "Efreeti Bottle",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 167",
    description: "Wondrous Item. Very Rare",
    text: "Source: DMG 167",
  },
  {
    id: "efreetichain_items",
    title: "Efreeti Chain",
    name: "Efreeti Chain",
    type: "Armor (chain mail)",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 167",
    description: "Armor (chain mail). Legendary. requires attunement",
    text: "Source: DMG 167",
  },
  {
    id: "elementalgem_items",
    title: "Elemental Gem",
    name: "Elemental Gem",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 167",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 167",
  },
  {
    id: "elixirofhealth_items",
    title: "Elixir of Health",
    name: "Elixir of Health",
    type: "Potion",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 168",
    description: "Potion. Rare",
    text: "Source: DMG 168",
  },
  {
    id: "elvenchain_items",
    title: "Elven Chain",
    name: "Elven Chain",
    type: "Armor (chain shirt)",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 168",
    description: "Armor (chain shirt). Rare",
    text: "Source: DMG 168",
  },
  {
    id: "eversmokingbottle_items",
    title: "Eversmoking Bottle",
    name: "Eversmoking Bottle",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 168",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 168",
  },
  {
    id: "eyesofcharming_items",
    title: "Eyes of Charming",
    name: "Eyes of Charming",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 168",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 168",
  },
  {
    id: "eyesofminuteseeing_items",
    title: "Eyes of Minute Seeing",
    name: "Eyes of Minute Seeing",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 168",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 168",
  },
  {
    id: "eyesoftheeagle_items",
    title: "Eyes of the Eagle",
    name: "Eyes of the Eagle",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 168",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 168",
  },
  {
    id: "figurineofwondrouspowerbronzegriffon_items",
    title: "Figurine of Wondrous Power, Bronze Griffon",
    name: "Figurine of Wondrous Power, Bronze Griffon",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 169",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 169",
  },
  {
    id: "figurineofwondrouspowerebonyfly_items",
    title: "Figurine of Wondrous Power, Ebony Fly",
    name: "Figurine of Wondrous Power, Ebony Fly",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 169",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 169",
  },
  {
    id: "figurineofwondrouspowergoldenlions_items",
    title: "Figurine of Wondrous Power, Golden Lions",
    name: "Figurine of Wondrous Power, Golden Lions",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 169",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 169",
  },
  {
    id: "figurineofwondrouspowerivorygoats_items",
    title: "Figurine of Wondrous Power, Ivory Goats",
    name: "Figurine of Wondrous Power, Ivory Goats",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 169",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 169",
  },
  {
    id: "figurineofwondrouspowermarbleelephant_items",
    title: "Figurine of Wondrous Power, Marble Elephant",
    name: "Figurine of Wondrous Power, Marble Elephant",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 170",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 170",
  },
  {
    id: "figurineofwondrouspowerobsidiansteed_items",
    title: "Figurine of Wondrous Power, Obsidian Steed",
    name: "Figurine of Wondrous Power, Obsidian Steed",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 170",
    description: "Wondrous Item. Very Rare",
    text: "Source: DMG 170",
  },
  {
    id: "figurineofwondrouspoweronyxdog_items",
    title: "Figurine of Wondrous Power, Onyx Dog",
    name: "Figurine of Wondrous Power, Onyx Dog",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 170",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 170",
  },
  {
    id: "figurineofwondrouspowerserpentineowl_items",
    title: "Figurine of Wondrous Power, Serpentine Owl",
    name: "Figurine of Wondrous Power, Serpentine Owl",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 170",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 170",
  },
  {
    id: "figurineofwondrouspowersilverraven_items",
    title: "Figurine of Wondrous Power, Silver Raven",
    name: "Figurine of Wondrous Power, Silver Raven",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 170",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 170",
  },
  {
    id: "flametongue_items",
    title: "Flame Tongue",
    name: "Flame Tongue",
    type: "Weapon (any sword)",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 170",
    description: "Weapon (any sword). Rare. requires attunement",
    text: "Source: DMG 170",
  },
  {
    id: "foldingboat_items",
    title: "Folding Boat",
    name: "Folding Boat",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 170",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 170",
  },
  {
    id: "frostbrand_items",
    title: "Frost Brand",
    name: "Frost Brand",
    type: "Weapon (any sword)",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 171",
    description: "Weapon (any sword). Very Rare. requires attunement",
    text: "Source: DMG 171",
  },
  {
    id: "gauntletsofogrepower_items",
    title: "Gauntlets of Ogre Power",
    name: "Gauntlets of Ogre Power",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 171",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 171",
  },
  {
    id: "gemofbrightness_items",
    title: "Gem of Brightness",
    name: "Gem of Brightness",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 171",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 171",
  },
  {
    id: "gemofseeing_items",
    title: "Gem of Seeing",
    name: "Gem of Seeing",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 172",
    description: "Wondrous Item. Rare. requires attunement",
    text: "Source: DMG 172",
  },
  {
    id: "giantslayer_items",
    title: "Giant Slayer",
    name: "Giant Slayer",
    type: "Weapon (any axe or sword)",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 172",
    description: "Weapon (any axe or sword). Rare",
    text: "Source: DMG 172",
  },
  {
    id: "glamouredstuddedleather_items",
    title: "Glamoured Studded Leather",
    name: "Glamoured Studded Leather",
    type: "Armor (studded leather)",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 172",
    description: "Armor (studded leather). Rare",
    text: "Source: DMG 172",
  },
  {
    id: "glovesofmissilesnaring_items",
    title: "Gloves of Missile Snaring",
    name: "Gloves of Missile Snaring",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 172",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 172",
  },
  {
    id: "glovesofswimmingandclimbing_items",
    title: "Gloves of Swimming and Climbing",
    name: "Gloves of Swimming and Climbing",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 172",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 172",
  },
  {
    id: "glovesofthievery_items",
    title: "Gloves of Thievery",
    name: "Gloves of Thievery",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 172",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 172",
  },
  {
    id: "gogglesofnight_items",
    title: "Goggles of Night",
    name: "Goggles of Night",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 172",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 172",
  },
  {
    id: "hammerofthunderbolts_items",
    title: "Hammer of Thunderbolts",
    name: "Hammer of Thunderbolts",
    type: "Weapon (maul)",
    rarity: "Legendary",
    attunement: "no",
    page: "dmg 173",
    description: "Weapon (maul). Legendary",
    text: "Source: DMG 173",
  },
  {
    id: "hatofdisguise_items",
    title: "Hat of Disguise",
    name: "Hat of Disguise",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 173",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 173",
  },
  {
    id: "headbandofintellect_items",
    title: "Headband of Intellect",
    name: "Headband of Intellect",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 173",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 173",
  },
  {
    id: "helmofbrilliance_items",
    title: "Helm of Brilliance",
    name: "Helm of Brilliance",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 173",
    description: "Wondrous Item. Very Rare. requires attunement",
    text: "Source: DMG 173",
  },
  {
    id: "helmofcomprehendinglanguages_items",
    title: "Helm of Comprehending Languages",
    name: "Helm of Comprehending Languages",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 173",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 173",
  },
  {
    id: "helmoftelepathy_items",
    title: "Helm of Telepathy",
    name: "Helm of Telepathy",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 174",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 174",
  },
  {
    id: "helmofteleportation_items",
    title: "Helm of Teleportation",
    name: "Helm of Teleportation",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 174",
    description: "Wondrous Item. Rare. requires attunement",
    text: "Source: DMG 174",
  },
  {
    id: "hewardshandyhaversack_items",
    title: "Heward's Handy Haversack",
    name: "Heward's Handy Haversack",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 174",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 174",
  },
  {
    id: "holyavenger_items",
    title: "Holy Avenger",
    name: "Holy Avenger",
    type: "Weapon (any sword)",
    rarity: "Legendary",
    attunement: "requires attunement by a paladin",
    page: "dmg 174",
    description:
      "Weapon (any sword). Legendary. requires attunement by a paladin",
    text: "Source: DMG 174",
  },
  {
    id: "hornofblasting_items",
    title: "Horn of Blasting",
    name: "Horn of Blasting",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 174",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 174",
  },
  {
    id: "hornofvalhallabrass_items",
    title: "Horn of Valhalla, Brass",
    name: "Horn of Valhalla, Brass",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 175",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 175",
  },
  {
    id: "hornofvalhallabronze_items",
    title: "Horn of Valhalla, Bronze",
    name: "Horn of Valhalla, Bronze",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 175",
    description: "Wondrous Item. Very Rare",
    text: "Source: DMG 175",
  },
  {
    id: "hornofvalhallairon_items",
    title: "Horn of Valhalla, Iron",
    name: "Horn of Valhalla, Iron",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "no",
    page: "dmg 175",
    description: "Wondrous Item. Legendary",
    text: "Source: DMG 175",
  },
  {
    id: "hornofvalhallasilver_items",
    title: "Horn of Valhalla, Silver",
    name: "Horn of Valhalla, Silver",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 175",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 175",
  },
  {
    id: "horseshoesofspeed_items",
    title: "Horseshoes of Speed",
    name: "Horseshoes of Speed",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 175",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 175",
  },
  {
    id: "horseshoesofazephyr_items",
    title: "Horseshoes of a Zephyr",
    name: "Horseshoes of a Zephyr",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 175",
    description: "Wondrous Item. Very Rare",
    text: "Source: DMG 175",
  },
  {
    id: "immovablerod_items",
    title: "Immovable Rod",
    name: "Immovable Rod",
    type: "Rod",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 175",
    description: "Rod. Uncommon",
    text: "Source: DMG 175",
  },
  {
    id: "instrumentofthebardsanstruthharp_items",
    title: "Instrument of the Bards, Anstruth Harp",
    name: "Instrument of the Bards, Anstruth Harp",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "requires attunement by a bard",
    page: "dmg 176",
    description: "Wondrous Item. Very Rare. requires attunement by a bard",
    text: "Source: DMG 176",
  },
  {
    id: "instrumentofthebardscanaithmandolin_items",
    title: "Instrument of the Bards, Canaith Mandolin",
    name: "Instrument of the Bards, Canaith Mandolin",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement by a bard",
    page: "dmg 176",
    description: "Wondrous Item. Rare. requires attunement by a bard",
    text: "Source: DMG 176",
  },
  {
    id: "instrumentofthebardsclilyre_items",
    title: "Instrument of the Bards, Cli Lyre",
    name: "Instrument of the Bards, Cli Lyre",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement by a bard",
    page: "dmg 176",
    description: "Wondrous Item. Rare. requires attunement by a bard",
    text: "Source: DMG 176",
  },
  {
    id: "instrumentofthebardsdosslute_items",
    title: "Instrument of the Bards, Doss Lute",
    name: "Instrument of the Bards, Doss Lute",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement by a bard",
    page: "dmg 176",
    description: "Wondrous Item. Uncommon. requires attunement by a bard",
    text: "Source: DMG 176",
  },
  {
    id: "instrumentofthebardsfochlucanbandore_items",
    title: "Instrument of the Bards, Fochlucan Bandore",
    name: "Instrument of the Bards, Fochlucan Bandore",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement by a bard",
    page: "dmg 176",
    description: "Wondrous Item. Uncommon. requires attunement by a bard",
    text: "Source: DMG 176",
  },
  {
    id: "instrumentofthebardsmacfuirmidhcittern_items",
    title: "Instrument of the Bards, Mac-Fuirmidh Cittern",
    name: "Instrument of the Bards, Mac-Fuirmidh Cittern",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement by a bard",
    page: "dmg 176",
    description: "Wondrous Item. Uncommon. requires attunement by a bard",
    text: "Source: DMG 176",
  },
  {
    id: "instrumentofthebardsollamhharp_items",
    title: "Instrument of the Bards, Ollamh Harp",
    name: "Instrument of the Bards, Ollamh Harp",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "requires attunement by a bard",
    page: "dmg 176",
    description: "Wondrous Item. Legendary. requires attunement by a bard",
    text: "Source: DMG 176",
  },
  {
    id: "iounstoneabsorption_items",
    title: "Ioun Stone, Absorption",
    name: "Ioun Stone, Absorption",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "requires attunement by a bard",
    page: "dmg 176",
    description: "Wondrous Item. Very Rare. requires attunement by a bard",
    text: "Source: DMG 176",
  },
  {
    id: "iounstoneagility_items",
    title: "Ioun Stone, Agility",
    name: "Ioun Stone, Agility",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 176",
    description: "Wondrous Item. Very Rare. requires attunement",
    text: "Source: DMG 176",
  },
  {
    id: "iounstoneawareness_items",
    title: "Ioun Stone, Awareness",
    name: "Ioun Stone, Awareness",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 176",
    description: "Wondrous Item. Rare. requires attunement",
    text: "Source: DMG 176",
  },
  {
    id: "iounstonefortitude_items",
    title: "Ioun Stone, Fortitude",
    name: "Ioun Stone, Fortitude",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 176",
    description: "Wondrous Item. Very Rare. requires attunement",
    text: "Source: DMG 176",
  },
  {
    id: "iounstonegreaterabsorption_items",
    title: "Ioun Stone, Greater Absorption",
    name: "Ioun Stone, Greater Absorption",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 176",
    description: "Wondrous Item. Legendary. requires attunement",
    text: "Source: DMG 176",
  },
  {
    id: "iounstoneinsight_items",
    title: "Ioun Stone, Insight",
    name: "Ioun Stone, Insight",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 176",
    description: "Wondrous Item. Very Rare. requires attunement",
    text: "Source: DMG 176",
  },
  {
    id: "iounstoneintellect_items",
    title: "Ioun Stone, Intellect",
    name: "Ioun Stone, Intellect",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 176",
    description: "Wondrous Item. Very Rare. requires attunement",
    text: "Source: DMG 176",
  },
  {
    id: "iounstoneleadership_items",
    title: "Ioun Stone, Leadership",
    name: "Ioun Stone, Leadership",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 176",
    description: "Wondrous Item. Very Rare. requires attunement",
    text: "Source: DMG 176",
  },
  {
    id: "iounstonemastery_items",
    title: "Ioun Stone, Mastery",
    name: "Ioun Stone, Mastery",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 176",
    description: "Wondrous Item. Legendary. requires attunement",
    text: "Source: DMG 176",
  },
  {
    id: "iounstoneprotection_items",
    title: "Ioun Stone, Protection",
    name: "Ioun Stone, Protection",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 176",
    description: "Wondrous Item. Rare. requires attunement",
    text: "Source: DMG 176",
  },
  {
    id: "iounstoneregeneration_items",
    title: "Ioun Stone, Regeneration",
    name: "Ioun Stone, Regeneration",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 176",
    description: "Wondrous Item. Legendary. requires attunement",
    text: "Source: DMG 176",
  },
  {
    id: "iounstonereserve_items",
    title: "Ioun Stone, Reserve",
    name: "Ioun Stone, Reserve",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 176",
    description: "Wondrous Item. Rare. requires attunement",
    text: "Source: DMG 176",
  },
  {
    id: "iounstonestrength_items",
    title: "Ioun Stone, Strength",
    name: "Ioun Stone, Strength",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 176",
    description: "Wondrous Item. Very Rare. requires attunement",
    text: "Source: DMG 176",
  },
  {
    id: "iounstonesustenance_items",
    title: "Ioun Stone, Sustenance",
    name: "Ioun Stone, Sustenance",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 176",
    description: "Wondrous Item. Rare. requires attunement",
    text: "Source: DMG 176",
  },
  {
    id: "ironbandsofbilarro_items",
    title: "Iron Bands of Bilarro",
    name: "Iron Bands of Bilarro",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 177",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 177",
  },
  {
    id: "ironflask_items",
    title: "Iron Flask",
    name: "Iron Flask",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "no",
    page: "dmg 178",
    description: "Wondrous Item. Legendary",
    text: "Source: DMG 178",
  },
  {
    id: "javelinoflightning_items",
    title: "Javelin of Lightning",
    name: "Javelin of Lightning",
    type: "Weapon (javelin)",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 178",
    description: "Weapon (javelin). Uncommon",
    text: "Source: DMG 178",
  },
  {
    id: "keoghtomsointment_items",
    title: "Keoghtom's Ointment",
    name: "Keoghtom's Ointment",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 179",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 179",
  },
  {
    id: "lanternofrevealing_items",
    title: "Lantern of Revealing",
    name: "Lantern of Revealing",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 179",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 179",
  },
  {
    id: "luckblade_items",
    title: "Luck Blade",
    name: "Luck Blade",
    type: "Weapon (any sword)",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 179",
    description: "Weapon (any sword). Legendary. requires attunement",
    text: "Source: DMG 179",
  },
  {
    id: "maceofdisruption_items",
    title: "Mace of Disruption",
    name: "Mace of Disruption",
    type: "Weapon (mace)",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 179",
    description: "Weapon (mace). Rare. requires attunement",
    text: "Source: DMG 179",
  },
  {
    id: "maceofsmiting_items",
    title: "Mace of Smiting",
    name: "Mace of Smiting",
    type: "Weapon (mace)",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 179",
    description: "Weapon (mace). Rare",
    text: "Source: DMG 179",
  },
  {
    id: "maceofterror_items",
    title: "Mace of Terror",
    name: "Mace of Terror",
    type: "Weapon (mace)",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 180",
    description: "Weapon (mace). Rare. requires attunement",
    text: "Source: DMG 180",
  },
  {
    id: "mantleofspellresistance_items",
    title: "Mantle of Spell Resistance",
    name: "Mantle of Spell Resistance",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 180",
    description: "Wondrous Item. Rare. requires attunement",
    text: "Source: DMG 180",
  },
  {
    id: "manualofbodilyhealth_items",
    title: "Manual of Bodily Health",
    name: "Manual of Bodily Health",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 180",
    description: "Wondrous Item. Very Rare",
    text: "Source: DMG 180",
  },
  {
    id: "manualofgainfulexercise_items",
    title: "Manual of Gainful Exercise",
    name: "Manual of Gainful Exercise",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 180",
    description: "Wondrous Item. Very Rare",
    text: "Source: DMG 180",
  },
  {
    id: "manualofgolems_items",
    title: "Manual of Golems",
    name: "Manual of Golems",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 180",
    description: "Wondrous Item. Very Rare",
    text: "Source: DMG 180",
  },
  {
    id: "manualofquicknessofaction_items",
    title: "Manual of Quickness of Action",
    name: "Manual of Quickness of Action",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 181",
    description: "Wondrous Item. Very Rare",
    text: "Source: DMG 181",
  },
  {
    id: "marinersarmor_items",
    title: "Mariner's Armor",
    name: "Mariner's Armor",
    type: "Armor",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 181",
    description: "Armor. Uncommon",
    text: "Source: DMG 181",
  },
  {
    id: "medallionofthoughts_items",
    title: "Medallion of Thoughts",
    name: "Medallion of Thoughts",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 181",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 181",
  },
  {
    id: "mirroroflifetrapping_items",
    title: "Mirror of Life Trapping",
    name: "Mirror of Life Trapping",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 181",
    description: "Wondrous Item. Very Rare",
    text: "Source: DMG 181",
  },
  {
    id: "mithralarmor_items",
    title: "Mithral Armor",
    name: "Mithral Armor",
    type: "Armor (medium or heavy, but not hide)",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 182",
    description: "Armor (medium or heavy, but not hide). Uncommon",
    text: "Source: DMG 182",
  },
  {
    id: "necklaceofadaptation_items",
    title: "Necklace of Adaptation",
    name: "Necklace of Adaptation",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 182",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 182",
  },
  {
    id: "necklaceoffireballs_items",
    title: "Necklace of Fireballs",
    name: "Necklace of Fireballs",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 182",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 182",
  },
  {
    id: "necklaceofprayerbeads_items",
    title: "Necklace of Prayer Beads",
    name: "Necklace of Prayer Beads",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement by a cleric, druid, or paladin",
    page: "dmg 182",
    description:
      "Wondrous Item. Rare. requires attunement by a cleric, druid, or paladin",
    text: "Source: DMG 182",
  },
  {
    id: "ninelivesstealer_items",
    title: "Nine Lives Stealer",
    name: "Nine Lives Stealer",
    type: "Weapon (any sword)",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 183",
    description: "Weapon (any sword). Very Rare. requires attunement",
    text: "Source: DMG 183",
  },
  {
    id: "nolzursmarvelouspigments_items",
    title: "Nolzur's Marvelous Pigments",
    name: "Nolzur's Marvelous Pigments",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 183",
    description: "Wondrous Item. Very Rare",
    text: "Source: DMG 183",
  },
  {
    id: "oathbow_items",
    title: "Oathbow",
    name: "Oathbow",
    type: "Weapon (longbow)",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 183",
    description: "Weapon (longbow). Very Rare. requires attunement",
    text: "Source: DMG 183",
  },
  {
    id: "oilofetherealness_items",
    title: "Oil of Etherealness",
    name: "Oil of Etherealness",
    type: "Potion",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 183",
    description: "Potion. Rare",
    text: "Source: DMG 183",
  },
  {
    id: "oilofsharpness_items",
    title: "Oil of Sharpness",
    name: "Oil of Sharpness",
    type: "Potion",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 184",
    description: "Potion. Very Rare",
    text: "Source: DMG 184",
  },
  {
    id: "oilofslipperiness_items",
    title: "Oil of Slipperiness",
    name: "Oil of Slipperiness",
    type: "Potion",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 184",
    description: "Potion. Uncommon",
    text: "Source: DMG 184",
  },
  {
    id: "pearlofpower_items",
    title: "Pearl of Power",
    name: "Pearl of Power",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement by a spellcaster",
    page: "dmg 184",
    description:
      "Wondrous Item. Uncommon. requires attunement by a spellcaster",
    text: "Source: DMG 184",
  },
  {
    id: "periaptofhealth_items",
    title: "Periapt of Health",
    name: "Periapt of Health",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 184",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 184",
  },
  {
    id: "periaptofproofagainstpoison_items",
    title: "Periapt of Proof Against Poison",
    name: "Periapt of Proof Against Poison",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 184",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 184",
  },
  {
    id: "periaptofwoundclosure_items",
    title: "Periapt of Wound Closure",
    name: "Periapt of Wound Closure",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 184",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 184",
  },
  {
    id: "philteroflove_items",
    title: "Philter of Love",
    name: "Philter of Love",
    type: "Potion",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 184",
    description: "Potion. Uncommon",
    text: "Source: DMG 184",
  },
  {
    id: "pipesofhaunting_items",
    title: "Pipes of Haunting",
    name: "Pipes of Haunting",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 185",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 185",
  },
  {
    id: "pipesofthesewers_items",
    title: "Pipes of the Sewers",
    name: "Pipes of the Sewers",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 185",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 185",
  },
  {
    id: "platearmorofetherealness_items",
    title: "Plate Armor of Etherealness",
    name: "Plate Armor of Etherealness",
    type: "Armor (plate)",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 185",
    description: "Armor (plate). Legendary. requires attunement",
    text: "Source: DMG 185",
  },
  {
    id: "portablehole_items",
    title: "Portable Hole",
    name: "Portable Hole",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 185",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 185",
  },
  {
    id: "potionofanimalfriendship_items",
    title: "Potion of Animal Friendship",
    name: "Potion of Animal Friendship",
    type: "Potion",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 187",
    description: "Potion. Uncommon",
    text: "Source: DMG 187",
  },
  {
    id: "potionofclairvoyance_items",
    title: "Potion of Clairvoyance",
    name: "Potion of Clairvoyance",
    type: "Potion",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 187",
    description: "Potion. Rare",
    text: "Source: DMG 187",
  },
  {
    id: "potionofclimbing_items",
    title: "Potion of Climbing",
    name: "Potion of Climbing",
    type: "Potion",
    rarity: "Common",
    attunement: "no",
    page: "dmg 187",
    description: "Potion. Common",
    text: "Source: DMG 187",
  },
  {
    id: "potionofcloudgiantstrength_items",
    title: "Potion of Cloud Giant Strength",
    name: "Potion of Cloud Giant Strength",
    type: "Potion",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 187",
    description: "Potion. Very Rare",
    text: "Source: DMG 187",
  },
  {
    id: "potionofdiminution_items",
    title: "Potion of Diminution",
    name: "Potion of Diminution",
    type: "Potion",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 187",
    description: "Potion. Rare",
    text: "Source: DMG 187",
  },
  {
    id: "potionoffirebreath_items",
    title: "Potion of Fire Breath",
    name: "Potion of Fire Breath",
    type: "Potion",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 187",
    description: "Potion. Uncommon",
    text: "Source: DMG 187",
  },
  {
    id: "potionoffiregiantstrength_items",
    title: "Potion of Fire Giant Strength",
    name: "Potion of Fire Giant Strength",
    type: "Potion",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 187",
    description: "Potion. Rare",
    text: "Source: DMG 187",
  },
  {
    id: "potionofflying_items",
    title: "Potion of Flying",
    name: "Potion of Flying",
    type: "Potion",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 187",
    description: "Potion. Very Rare",
    text: "Source: DMG 187",
  },
  {
    id: "potionoffrostgiantstrength_items",
    title: "Potion of Frost Giant Strength",
    name: "Potion of Frost Giant Strength",
    type: "Potion",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 187",
    description: "Potion. Rare",
    text: "Source: DMG 187",
  },
  {
    id: "potionofgaseousform_items",
    title: "Potion of Gaseous Form",
    name: "Potion of Gaseous Form",
    type: "Potion",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 187",
    description: "Potion. Rare",
    text: "Source: DMG 187",
  },
  {
    id: "potionofgreaterhealing_items",
    title: "Potion of Greater Healing",
    name: "Potion of Greater Healing",
    type: "Potion",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 187",
    description: "Potion. Uncommon",
    text: "Source: DMG 187",
  },
  {
    id: "potionofgrowth_items",
    title: "Potion of Growth",
    name: "Potion of Growth",
    type: "Potion",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 187",
    description: "Potion. Uncommon",
    text: "Source: DMG 187",
  },
  {
    id: "potionofhealing_items",
    title: "Potion of Healing",
    name: "Potion of Healing",
    type: "Potion",
    rarity: "Common",
    attunement: "no",
    page: "dmg 187",
    description: "Potion. Common",
    text: "Source: DMG 187",
  },
  {
    id: "potionofheroism_items",
    title: "Potion of Heroism",
    name: "Potion of Heroism",
    type: "Potion",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 188",
    description: "Potion. Rare",
    text: "Source: DMG 188",
  },
  {
    id: "potionofhillgiantstrength_items",
    title: "Potion of Hill Giant Strength",
    name: "Potion of Hill Giant Strength",
    type: "Potion",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 187",
    description: "Potion. Uncommon",
    text: "Source: DMG 187",
  },
  {
    id: "potionofinvisibility_items",
    title: "Potion of Invisibility",
    name: "Potion of Invisibility",
    type: "Potion",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 188",
    description: "Potion. Very Rare",
    text: "Source: DMG 188",
  },
  {
    id: "potionofinvulnerability_items",
    title: "Potion of Invulnerability",
    name: "Potion of Invulnerability",
    type: "Potion",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 188",
    description: "Potion. Rare",
    text: "Source: DMG 188",
  },
  {
    id: "potionoflongevity_items",
    title: "Potion of Longevity",
    name: "Potion of Longevity",
    type: "Potion",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 188",
    description: "Potion. Very Rare",
    text: "Source: DMG 188",
  },
  {
    id: "potionofmindreading_items",
    title: "Potion of Mind Reading",
    name: "Potion of Mind Reading",
    type: "Potion",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 188",
    description: "Potion. Rare",
    text: "Source: DMG 188",
  },
  {
    id: "potionofpoison_items",
    title: "Potion of Poison",
    name: "Potion of Poison",
    type: "Potion",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 188",
    description: "Potion. Uncommon",
    text: "Source: DMG 188",
  },
  {
    id: "potionofresistance_items",
    title: "Potion of Resistance",
    name: "Potion of Resistance",
    type: "Potion",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 188",
    description: "Potion. Uncommon",
    text: "Source: DMG 188",
  },
  {
    id: "potionofspeed_items",
    title: "Potion of Speed",
    name: "Potion of Speed",
    type: "Potion",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 188",
    description: "Potion. Very Rare",
    text: "Source: DMG 188",
  },
  {
    id: "potionofstonegiantstrength_items",
    title: "Potion of Stone Giant Strength",
    name: "Potion of Stone Giant Strength",
    type: "Potion",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 187",
    description: "Potion. Rare",
    text: "Source: DMG 187",
  },
  {
    id: "potionofstormgiantstrength_items",
    title: "Potion of Storm Giant Strength",
    name: "Potion of Storm Giant Strength",
    type: "Potion",
    rarity: "Legendary",
    attunement: "no",
    page: "dmg 187",
    description: "Potion. Legendary",
    text: "Source: DMG 187",
  },
  {
    id: "potionofsuperiorhealing_items",
    title: "Potion of Superior Healing",
    name: "Potion of Superior Healing",
    type: "Potion",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 187",
    description: "Potion. Rare",
    text: "Source: DMG 187",
  },
  {
    id: "potionofsupremehealing_items",
    title: "Potion of Supreme Healing",
    name: "Potion of Supreme Healing",
    type: "Potion",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 187",
    description: "Potion. Very Rare",
    text: "Source: DMG 187",
  },
  {
    id: "potionofvitality_items",
    title: "Potion of Vitality",
    name: "Potion of Vitality",
    type: "Potion",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 188",
    description: "Potion. Very Rare",
    text: "Source: DMG 188",
  },
  {
    id: "potionofwaterbreathing_items",
    title: "Potion of Water Breathing",
    name: "Potion of Water Breathing",
    type: "Potion",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 188",
    description: "Potion. Uncommon",
    text: "Source: DMG 188",
  },
  {
    id: "quaalsfeathertoken_items",
    title: "Quaal's Feather Token",
    name: "Quaal's Feather Token",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 188",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 188",
  },
  {
    id: "quiverofehlonna_items",
    title: "Quiver of Ehlonna",
    name: "Quiver of Ehlonna",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 189",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 189",
  },
  {
    id: "ringofairelementalcommand_items",
    title: "Ring of Air Elemental Command",
    name: "Ring of Air Elemental Command",
    type: "Ring",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 190",
    description: "Ring. Legendary. requires attunement",
    text: "Source: DMG 190",
  },
  {
    id: "ringofanimalinfluence_items",
    title: "Ring of Animal Influence",
    name: "Ring of Animal Influence",
    type: "Ring",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 189",
    description: "Ring. Rare",
    text: "Source: DMG 189",
  },
  {
    id: "ringofdjinnisummoning_items",
    title: "Ring of Djinni Summoning",
    name: "Ring of Djinni Summoning",
    type: "Ring",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 190",
    description: "Ring. Legendary. requires attunement",
    text: "Source: DMG 190",
  },
  {
    id: "ringofearthelementalcommand_items",
    title: "Ring of Earth Elemental Command",
    name: "Ring of Earth Elemental Command",
    type: "Ring",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 190",
    description: "Ring. Legendary. requires attunement",
    text: "Source: DMG 190",
  },
  {
    id: "ringofevasion_items",
    title: "Ring of Evasion",
    name: "Ring of Evasion",
    type: "Ring",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 191",
    description: "Ring. Rare. requires attunement",
    text: "Source: DMG 191",
  },
  {
    id: "ringoffeatherfalling_items",
    title: "Ring of Feather Falling",
    name: "Ring of Feather Falling",
    type: "Ring",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 191",
    description: "Ring. Rare. requires attunement",
    text: "Source: DMG 191",
  },
  {
    id: "ringoffireelementalcommand_items",
    title: "Ring of Fire Elemental Command",
    name: "Ring of Fire Elemental Command",
    type: "Ring",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 190",
    description: "Ring. Legendary. requires attunement",
    text: "Source: DMG 190",
  },
  {
    id: "ringoffreeaction_items",
    title: "Ring of Free Action",
    name: "Ring of Free Action",
    type: "Ring",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 191",
    description: "Ring. Rare. requires attunement",
    text: "Source: DMG 191",
  },
  {
    id: "ringofinvisibility_items",
    title: "Ring of Invisibility",
    name: "Ring of Invisibility",
    type: "Ring",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 191",
    description: "Ring. Legendary. requires attunement",
    text: "Source: DMG 191",
  },
  {
    id: "ringofjumping_items",
    title: "Ring of Jumping",
    name: "Ring of Jumping",
    type: "Ring",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 191",
    description: "Ring. Uncommon. requires attunement",
    text: "Source: DMG 191",
  },
  {
    id: "ringofmindshielding_items",
    title: "Ring of Mind Shielding",
    name: "Ring of Mind Shielding",
    type: "Ring",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 191",
    description: "Ring. Uncommon. requires attunement",
    text: "Source: DMG 191",
  },
  {
    id: "ringofprotection_items",
    title: "Ring of Protection",
    name: "Ring of Protection",
    type: "Ring",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 191",
    description: "Ring. Rare. requires attunement",
    text: "Source: DMG 191",
  },
  {
    id: "ringofregeneration_items",
    title: "Ring of Regeneration",
    name: "Ring of Regeneration",
    type: "Ring",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 191",
    description: "Ring. Very Rare. requires attunement",
    text: "Source: DMG 191",
  },
  {
    id: "ringofresistance_items",
    title: "Ring of Resistance",
    name: "Ring of Resistance",
    type: "Ring",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 192",
    description: "Ring. Rare. requires attunement",
    text: "Source: DMG 192",
  },
  {
    id: "ringofshootingstars_items",
    title: "Ring of Shooting Stars",
    name: "Ring of Shooting Stars",
    type: "Ring",
    rarity: "Very Rare",
    attunement: "requires attunement outdoors at night",
    page: "dmg 192",
    description: "Ring. Very Rare. requires attunement outdoors at night",
    text: "Source: DMG 192",
  },
  {
    id: "ringofspellstoring_items",
    title: "Ring of Spell Storing",
    name: "Ring of Spell Storing",
    type: "Ring",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 192",
    description: "Ring. Rare. requires attunement",
    text: "Source: DMG 192",
  },
  {
    id: "ringofspellturning_items",
    title: "Ring of Spell Turning",
    name: "Ring of Spell Turning",
    type: "Ring",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 193",
    description: "Ring. Legendary. requires attunement",
    text: "Source: DMG 193",
  },
  {
    id: "ringofswimming_items",
    title: "Ring of Swimming",
    name: "Ring of Swimming",
    type: "Ring",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 193",
    description: "Ring. Uncommon",
    text: "Source: DMG 193",
  },
  {
    id: "ringoftelekinesis_items",
    title: "Ring of Telekinesis",
    name: "Ring of Telekinesis",
    type: "Ring",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 193",
    description: "Ring. Very Rare. requires attunement",
    text: "Source: DMG 193",
  },
  {
    id: "ringofthreewishes_items",
    title: "Ring of Three Wishes",
    name: "Ring of Three Wishes",
    type: "Ring",
    rarity: "Legendary",
    attunement: "no",
    page: "dmg 193",
    description: "Ring. Legendary",
    text: "Source: DMG 193",
  },
  {
    id: "ringofwarmth_items",
    title: "Ring of Warmth",
    name: "Ring of Warmth",
    type: "Ring",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 193",
    description: "Ring. Uncommon. requires attunement",
    text: "Source: DMG 193",
  },
  {
    id: "ringofwaterelementalcommand_items",
    title: "Ring of Water Elemental Command",
    name: "Ring of Water Elemental Command",
    type: "Ring",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 190",
    description: "Ring. Legendary. requires attunement",
    text: "Source: DMG 190",
  },
  {
    id: "ringofwaterwalking_items",
    title: "Ring of Water Walking",
    name: "Ring of Water Walking",
    type: "Ring",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 193",
    description: "Ring. Uncommon",
    text: "Source: DMG 193",
  },
  {
    id: "ringofxrayvision_items",
    title: "Ring of X-ray Vision",
    name: "Ring of X-ray Vision",
    type: "Ring",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 193",
    description: "Ring. Rare. requires attunement",
    text: "Source: DMG 193",
  },
  {
    id: "ringoftheram_items",
    title: "Ring of the Ram",
    name: "Ring of the Ram",
    type: "Ring",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 193",
    description: "Ring. Rare. requires attunement",
    text: "Source: DMG 193",
  },
  {
    id: "robeofeyes_items",
    title: "Robe of Eyes",
    name: "Robe of Eyes",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 193",
    description: "Wondrous Item. Rare. requires attunement",
    text: "Source: DMG 193",
  },
  {
    id: "robeofscintillatingcolors_items",
    title: "Robe of Scintillating Colors",
    name: "Robe of Scintillating Colors",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 194",
    description: "Wondrous Item. Very Rare. requires attunement",
    text: "Source: DMG 194",
  },
  {
    id: "robeofstars_items",
    title: "Robe of Stars",
    name: "Robe of Stars",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 194",
    description: "Wondrous Item. Very Rare. requires attunement",
    text: "Source: DMG 194",
  },
  {
    id: "robeofusefulitems_items",
    title: "Robe of Useful Items",
    name: "Robe of Useful Items",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 195",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 195",
  },
  {
    id: "robeofthearchmagi_items",
    title: "Robe of the Archmagi",
    name: "Robe of the Archmagi",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "requires attunement by a sorcerer, warlock, or wizard",
    page: "dmg 194",
    description:
      "Wondrous Item. Legendary. requires attunement by a sorcerer, warlock, or wizard",
    text: "Source: DMG 194",
  },
  {
    id: "rodofabsorption_items",
    title: "Rod of Absorption",
    name: "Rod of Absorption",
    type: "Rod",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 195",
    description: "Rod. Very Rare. requires attunement",
    text: "Source: DMG 195",
  },
  {
    id: "rodofalertness_items",
    title: "Rod of Alertness",
    name: "Rod of Alertness",
    type: "Rod",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 196",
    description: "Rod. Very Rare. requires attunement",
    text: "Source: DMG 196",
  },
  {
    id: "rodoflordlymight_items",
    title: "Rod of Lordly Might",
    name: "Rod of Lordly Might",
    type: "Rod",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 196",
    description: "Rod. Legendary. requires attunement",
    text: "Source: DMG 196",
  },
  {
    id: "rodofresurrection_items",
    title: "Rod of Resurrection",
    name: "Rod of Resurrection",
    type: "Rod",
    rarity: "Legendary",
    attunement: "requires attunement by a cleric, druid or paladin",
    page: "dmg 197",
    description:
      "Rod. Legendary. requires attunement by a cleric, druid or paladin",
    text: "Source: DMG 197",
  },
  {
    id: "rodofrulership_items",
    title: "Rod of Rulership",
    name: "Rod of Rulership",
    type: "Rod",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 197",
    description: "Rod. Rare. requires attunement",
    text: "Source: DMG 197",
  },
  {
    id: "rodofsecurity_items",
    title: "Rod of Security",
    name: "Rod of Security",
    type: "Rod",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 197",
    description: "Rod. Very Rare",
    text: "Source: DMG 197",
  },
  {
    id: "rodofthepactkeeper+1+2or+3_items",
    title: "Rod of the Pact Keeper, +1, +2, or +3",
    name: "Rod of the Pact Keeper, +1, +2, or +3",
    type: "Rod",
    rarity: "Uncommon (+1), rare (+2), or very rare (+3)",
    attunement: "requires attunement by a warlock",
    page: "dmg 197",
    description:
      "Rod. Uncommon (+1), rare (+2), or very rare (+3). requires attunement by a warlock",
    text: "Source: DMG 197",
  },
  {
    id: "ropeofclimbing_items",
    title: "Rope of Climbing",
    name: "Rope of Climbing",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 197",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 197",
  },
  {
    id: "ropeofentanglement_items",
    title: "Rope of Entanglement",
    name: "Rope of Entanglement",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 197",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 197",
  },
  {
    id: "saddleofthecavalier_items",
    title: "Saddle of the Cavalier",
    name: "Saddle of the Cavalier",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 199",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 199",
  },
  {
    id: "scarabofprotection_items",
    title: "Scarab of Protection",
    name: "Scarab of Protection",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 199",
    description: "Wondrous Item. Legendary. requires attunement",
    text: "Source: DMG 199",
  },
  {
    id: "scimitarofspeed_items",
    title: "Scimitar of Speed",
    name: "Scimitar of Speed",
    type: "Weapon (scimitar)",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 199",
    description: "Weapon (scimitar). Very Rare. requires attunement",
    text: "Source: DMG 199",
  },
  {
    id: "scrollofprotection_items",
    title: "Scroll of Protection",
    name: "Scroll of Protection",
    type: "Scroll",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 199",
    description: "Scroll. Rare",
    text: "Source: DMG 199",
  },
  {
    id: "sendingstones_items",
    title: "Sending Stones",
    name: "Sending Stones",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 199",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 199",
  },
  {
    id: "sentinelshield_items",
    title: "Sentinel Shield",
    name: "Sentinel Shield",
    type: "Armor (shield)",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 199",
    description: "Armor (shield). Uncommon",
    text: "Source: DMG 199",
  },
  {
    id: "shieldofmissileattraction_items",
    title: "Shield of Missile Attraction",
    name: "Shield of Missile Attraction",
    type: "Armor (shield)",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 200",
    description: "Armor (shield). Rare. requires attunement",
    text: "Source: DMG 200",
  },
  {
    id: "shield+1+2or+3_items",
    title: "Shield, +1, +2, or +3",
    name: "Shield, +1, +2, or +3",
    type: "Armor (shield)",
    rarity: "Uncommon (+1), rare (+2), or very rare (+3)",
    attunement: "no",
    page: "dmg 200",
    description: "Armor (shield). Uncommon (+1), rare (+2), or very rare (+3)",
    text: "Source: DMG 200",
  },
  {
    id: "slippersofspiderclimbing_items",
    title: "Slippers of Spider Climbing",
    name: "Slippers of Spider Climbing",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 200",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 200",
  },
  {
    id: "sovereignglue_items",
    title: "Sovereign Glue",
    name: "Sovereign Glue",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "no",
    page: "dmg 200",
    description: "Wondrous Item. Legendary",
    text: "Source: DMG 200",
  },
  {
    id: "spellscroll1stlevel_items",
    title: "Spell Scroll, 1st Level",
    name: "Spell Scroll, 1st Level",
    type: "Scroll",
    rarity: "Common",
    attunement: "no",
    page: "dmg 200",
    description: "Scroll. Common",
    text: "Source: DMG 200",
  },
  {
    id: "spellscroll2ndlevel_items",
    title: "Spell Scroll, 2nd Level",
    name: "Spell Scroll, 2nd Level",
    type: "Scroll",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 200",
    description: "Scroll. Uncommon",
    text: "Source: DMG 200",
  },
  {
    id: "spellscroll3rdlevel_items",
    title: "Spell Scroll, 3rd Level",
    name: "Spell Scroll, 3rd Level",
    type: "Scroll",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 200",
    description: "Scroll. Uncommon",
    text: "Source: DMG 200",
  },
  {
    id: "spellscroll4thlevel_items",
    title: "Spell Scroll, 4th Level",
    name: "Spell Scroll, 4th Level",
    type: "Scroll",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 200",
    description: "Scroll. Rare",
    text: "Source: DMG 200",
  },
  {
    id: "spellscroll5thlevel_items",
    title: "Spell Scroll, 5th Level",
    name: "Spell Scroll, 5th Level",
    type: "Scroll",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 200",
    description: "Scroll. Rare",
    text: "Source: DMG 200",
  },
  {
    id: "spellscroll6thlevel_items",
    title: "Spell Scroll, 6th Level",
    name: "Spell Scroll, 6th Level",
    type: "Scroll",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 200",
    description: "Scroll. Very Rare",
    text: "Source: DMG 200",
  },
  {
    id: "spellscroll7thlevel_items",
    title: "Spell Scroll, 7th Level",
    name: "Spell Scroll, 7th Level",
    type: "Scroll",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 200",
    description: "Scroll. Very Rare",
    text: "Source: DMG 200",
  },
  {
    id: "spellscroll8thlevel_items",
    title: "Spell Scroll, 8th Level",
    name: "Spell Scroll, 8th Level",
    type: "Scroll",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 200",
    description: "Scroll. Very Rare",
    text: "Source: DMG 200",
  },
  {
    id: "spellscroll9thlevel_items",
    title: "Spell Scroll, 9th Level",
    name: "Spell Scroll, 9th Level",
    type: "Scroll",
    rarity: "Legendary",
    attunement: "no",
    page: "dmg 200",
    description: "Scroll. Legendary",
    text: "Source: DMG 200",
  },
  {
    id: "spellscrollcantrip_items",
    title: "Spell Scroll, Cantrip",
    name: "Spell Scroll, Cantrip",
    type: "Scroll",
    rarity: "Common",
    attunement: "no",
    page: "dmg 200",
    description: "Scroll. Common",
    text: "Source: DMG 200",
  },
  {
    id: "spellguardshield_items",
    title: "Spellguard Shield",
    name: "Spellguard Shield",
    type: "Armor",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 201",
    description: "Armor. Very Rare. requires attunement",
    text: "Source: DMG 201",
  },
  {
    id: "sphereofannihilation_items",
    title: "Sphere of Annihilation",
    name: "Sphere of Annihilation",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "no",
    page: "dmg 201",
    description: "Wondrous Item. Legendary",
    text: "Source: DMG 201",
  },
  {
    id: "staffofcharming_items",
    title: "Staff of Charming",
    name: "Staff of Charming",
    type: "Staff",
    rarity: "Rare",
    attunement:
      "requires attunement by a bard, cleric, druid, sorcerer, warlock, or wizard",
    page: "dmg 201",
    description:
      "Staff. Rare. requires attunement by a bard, cleric, druid, sorcerer, warlock, or wizard",
    text: "Source: DMG 201",
  },
  {
    id: "staffoffire_items",
    title: "Staff of Fire",
    name: "Staff of Fire",
    type: "Staff",
    rarity: "Very Rare",
    attunement: "requires attunement by a druid, sorcerer, warlock, or wizard",
    page: "dmg 201",
    description:
      "Staff. Very Rare. requires attunement by a druid, sorcerer, warlock, or wizard",
    text: "Source: DMG 201",
  },
  {
    id: "staffoffrost_items",
    title: "Staff of Frost",
    name: "Staff of Frost",
    type: "Staff",
    rarity: "Very Rare",
    attunement: "requires attunement by a druid, sorcerer, warlock, or wizard",
    page: "dmg 202",
    description:
      "Staff. Very Rare. requires attunement by a druid, sorcerer, warlock, or wizard",
    text: "Source: DMG 202",
  },
  {
    id: "staffofhealing_items",
    title: "Staff of Healing",
    name: "Staff of Healing",
    type: "Staff",
    rarity: "Rare",
    attunement: "requires attunement by a bard, cleric, or druid",
    page: "dmg 202",
    description: "Staff. Rare. requires attunement by a bard, cleric, or druid",
    text: "Source: DMG 202",
  },
  {
    id: "staffofpower_items",
    title: "Staff of Power",
    name: "Staff of Power",
    type: "Staff",
    rarity: "Very Rare",
    attunement: "requires attunement by a sorcerer, warlock, or wizard",
    page: "dmg 202",
    description:
      "Staff. Very Rare. requires attunement by a sorcerer, warlock, or wizard",
    text: "Source: DMG 202",
  },
  {
    id: "staffofstriking_items",
    title: "Staff of Striking",
    name: "Staff of Striking",
    type: "Staff",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 203",
    description: "Staff. Very Rare. requires attunement",
    text: "Source: DMG 203",
  },
  {
    id: "staffofswarminginsects_items",
    title: "Staff of Swarming Insects",
    name: "Staff of Swarming Insects",
    type: "Staff",
    rarity: "Rare",
    attunement:
      "requires attunement by a bard, cleric, druid, sorcerer, warlock, or wizard",
    page: "dmg 203",
    description:
      "Staff. Rare. requires attunement by a bard, cleric, druid, sorcerer, warlock, or wizard",
    text: "Source: DMG 203",
  },
  {
    id: "staffofthunderandlightning_items",
    title: "Staff of Thunder and Lightning",
    name: "Staff of Thunder and Lightning",
    type: "Staff",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 204",
    description: "Staff. Very Rare. requires attunement",
    text: "Source: DMG 204",
  },
  {
    id: "staffofwithering_items",
    title: "Staff of Withering",
    name: "Staff of Withering",
    type: "Staff",
    rarity: "Rare",
    attunement: "requires attunement by a cleric, druid, or wizard",
    page: "dmg 205",
    description:
      "Staff. Rare. requires attunement by a cleric, druid, or wizard",
    text: "Source: DMG 205",
  },
  {
    id: "staffoftheadder_items",
    title: "Staff of the Adder",
    name: "Staff of the Adder",
    type: "Staff",
    rarity: "Uncommon",
    attunement: "requires attunement by a cleric, druid, or warlock",
    page: "dmg 203",
    description:
      "Staff. Uncommon. requires attunement by a cleric, druid, or warlock",
    text: "Source: DMG 203",
  },
  {
    id: "staffofthemagi_items",
    title: "Staff of the Magi",
    name: "Staff of the Magi",
    type: "Staff",
    rarity: "Legendary",
    attunement: "requires attunement by a sorcerer, warlock, or wizard",
    page: "dmg 203",
    description:
      "Staff. Legendary. requires attunement by a sorcerer, warlock, or wizard",
    text: "Source: DMG 203",
  },
  {
    id: "staffofthepython_items",
    title: "Staff of the Python",
    name: "Staff of the Python",
    type: "Staff",
    rarity: "Uncommon",
    attunement: "requires attunement by a cleric, druid, or warlock",
    page: "dmg 204",
    description:
      "Staff. Uncommon. requires attunement by a cleric, druid, or warlock",
    text: "Source: DMG 204",
  },
  {
    id: "staffofthewoodlands_items",
    title: "Staff of the Woodlands",
    name: "Staff of the Woodlands",
    type: "Staff",
    rarity: "Rare",
    attunement: "requires attunement by a druid",
    page: "dmg 204",
    description: "Staff. Rare. requires attunement by a druid",
    text: "Source: DMG 204",
  },
  {
    id: "stoneofcontrollingearthelementals_items",
    title: "Stone of Controlling Earth Elementals",
    name: "Stone of Controlling Earth Elementals",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 205",
    description: "Wondrous Item. Rare",
    text: "Source: DMG 205",
  },
  {
    id: "stoneofgoodluck_items",
    title: "Stone of Good Luck",
    name: "Stone of Good Luck",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 205",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 205",
  },
  {
    id: "sunblade_items",
    title: "Sun Blade",
    name: "Sun Blade",
    type: "Weapon (longsword)",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 205",
    description: "Weapon (longsword). Rare. requires attunement",
    text: "Source: DMG 205",
  },
  {
    id: "swordofanswering_items",
    title: "Sword of Answering",
    name: "Sword of Answering",
    type: "Weapon (longsword)",
    rarity: "Legendary",
    attunement:
      "requires attunement by a creature with the same alignment as the sword",
    page: "dmg 206",
    description:
      "Weapon (longsword). Legendary. requires attunement by a creature with the same alignment as the sword",
    text: "Source: DMG 206",
  },
  {
    id: "swordoflifestealing_items",
    title: "Sword of Life Stealing",
    name: "Sword of Life Stealing",
    type: "Weapon (any sword)",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 206",
    description: "Weapon (any sword). Rare. requires attunement",
    text: "Source: DMG 206",
  },
  {
    id: "swordofsharpness_items",
    title: "Sword of Sharpness",
    name: "Sword of Sharpness",
    type: "Weapon (any sword that deals slashing damage)",
    rarity: "Very Rare",
    attunement: "requires attunement",
    page: "dmg 206",
    description:
      "Weapon (any sword that deals slashing damage). Very Rare. requires attunement",
    text: "Source: DMG 206",
  },
  {
    id: "swordofvengeance_items",
    title: "Sword of Vengeance",
    name: "Sword of Vengeance",
    type: "Weapon (any sword)",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 206",
    description: "Weapon (any sword). Uncommon. requires attunement",
    text: "Source: DMG 206",
  },
  {
    id: "swordofwounding_items",
    title: "Sword of Wounding",
    name: "Sword of Wounding",
    type: "Weapon (any sword)",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 207",
    description: "Weapon (any sword). Rare. requires attunement",
    text: "Source: DMG 207",
  },
  {
    id: "talismanofpuregood_items",
    title: "Talisman of Pure Good",
    name: "Talisman of Pure Good",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "requires attunement by a creature of good alignment",
    page: "dmg 207",
    description:
      "Wondrous Item. Legendary. requires attunement by a creature of good alignment",
    text: "Source: DMG 207",
  },
  {
    id: "talismanofultimateevil_items",
    title: "Talisman of Ultimate Evil",
    name: "Talisman of Ultimate Evil",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "requires attunement by a creature of evil alignment",
    page: "dmg 207",
    description:
      "Wondrous Item. Legendary. requires attunement by a creature of evil alignment",
    text: "Source: DMG 207",
  },
  {
    id: "talismanofthesphere_items",
    title: "Talisman of the Sphere",
    name: "Talisman of the Sphere",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 207",
    description: "Wondrous Item. Legendary. requires attunement",
    text: "Source: DMG 207",
  },
  {
    id: "tentaclerod_items",
    title: "Tentacle Rod",
    name: "Tentacle Rod",
    type: "Rod",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 208",
    description: "Rod. Rare. requires attunement",
    text: "Source: DMG 208",
  },
  {
    id: "tomeofclearthought_items",
    title: "Tome of Clear Thought",
    name: "Tome of Clear Thought",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 208",
    description: "Wondrous Item. Very Rare",
    text: "Source: DMG 208",
  },
  {
    id: "tomeofleadershipandinfluence_items",
    title: "Tome of Leadership and Influence",
    name: "Tome of Leadership and Influence",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 208",
    description: "Wondrous Item. Very Rare",
    text: "Source: DMG 208",
  },
  {
    id: "tomeofunderstanding_items",
    title: "Tome of Understanding",
    name: "Tome of Understanding",
    type: "Wondrous Item",
    rarity: "Very Rare",
    attunement: "no",
    page: "dmg 209",
    description: "Wondrous Item. Very Rare",
    text: "Source: DMG 209",
  },
  {
    id: "tomeofthestilledtongue_items",
    title: "Tome of the Stilled Tongue",
    name: "Tome of the Stilled Tongue",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "requires attunement by a wizard",
    page: "dmg 208",
    description: "Wondrous Item. Legendary. requires attunement by a wizard",
    text: "Source: DMG 208",
  },
  {
    id: "tridentoffishcommand_items",
    title: "Trident of Fish Command",
    name: "Trident of Fish Command",
    type: "Weapon (trident)",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 209",
    description: "Weapon (trident). Uncommon. requires attunement",
    text: "Source: DMG 209",
  },
  {
    id: "universalsolvent_items",
    title: "Universal Solvent",
    name: "Universal Solvent",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "no",
    page: "dmg 209",
    description: "Wondrous Item. Legendary",
    text: "Source: DMG 209",
  },
  {
    id: "viciousweapon_items",
    title: "Vicious Weapon",
    name: "Vicious Weapon",
    type: "Weapon",
    rarity: "Rare",
    attunement: "no",
    page: "dmg 209",
    description: "Weapon. Rare",
    text: "Source: DMG 209",
  },
  {
    id: "vorpalsword_items",
    title: "Vorpal Sword",
    name: "Vorpal Sword",
    type: "Weapon (any sword that deals slashing damage)",
    rarity: "Legendary",
    attunement: "requires attunement",
    page: "dmg 209",
    description:
      "Weapon (any sword that deals slashing damage). Legendary. requires attunement",
    text: "Source: DMG 209",
  },
  {
    id: "wandofbinding_items",
    title: "Wand of Binding",
    name: "Wand of Binding",
    type: "Wand",
    rarity: "Rare",
    attunement: "requires attunement by a spellcaster",
    page: "dmg 209",
    description: "Wand. Rare. requires attunement by a spellcaster",
    text: "Source: DMG 209",
  },
  {
    id: "wandofenemydetection_items",
    title: "Wand of Enemy Detection",
    name: "Wand of Enemy Detection",
    type: "Wand",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 210",
    description: "Wand. Rare. requires attunement",
    text: "Source: DMG 210",
  },
  {
    id: "wandoffear_items",
    title: "Wand of Fear",
    name: "Wand of Fear",
    type: "Wand",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 210",
    description: "Wand. Rare. requires attunement",
    text: "Source: DMG 210",
  },
  {
    id: "wandoffireballs_items",
    title: "Wand of Fireballs",
    name: "Wand of Fireballs",
    type: "Wand",
    rarity: "Rare",
    attunement: "requires attunement by a spellcaster",
    page: "dmg 210",
    description: "Wand. Rare. requires attunement by a spellcaster",
    text: "Source: DMG 210",
  },
  {
    id: "wandoflightningbolts_items",
    title: "Wand of Lightning Bolts",
    name: "Wand of Lightning Bolts",
    type: "Wand",
    rarity: "Rare",
    attunement: "requires attunement by a spellcaster",
    page: "dmg 211",
    description: "Wand. Rare. requires attunement by a spellcaster",
    text: "Source: DMG 211",
  },
  {
    id: "wandofmagicdetection_items",
    title: "Wand of Magic Detection",
    name: "Wand of Magic Detection",
    type: "Wand",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 211",
    description: "Wand. Uncommon",
    text: "Source: DMG 211",
  },
  {
    id: "wandofmagicmissiles_items",
    title: "Wand of Magic Missiles",
    name: "Wand of Magic Missiles",
    type: "Wand",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 211",
    description: "Wand. Uncommon",
    text: "Source: DMG 211",
  },
  {
    id: "wandofparalysis_items",
    title: "Wand of Paralysis",
    name: "Wand of Paralysis",
    type: "Wand",
    rarity: "Rare",
    attunement: "requires attunement by a spellcaster",
    page: "dmg 211",
    description: "Wand. Rare. requires attunement by a spellcaster",
    text: "Source: DMG 211",
  },
  {
    id: "wandofpolymorph_items",
    title: "Wand of Polymorph",
    name: "Wand of Polymorph",
    type: "Wand",
    rarity: "Very Rare",
    attunement: "requires attunement by a spellcaster",
    page: "dmg 211",
    description: "Wand. Very Rare. requires attunement by a spellcaster",
    text: "Source: DMG 211",
  },
  {
    id: "wandofsecrets_items",
    title: "Wand of Secrets",
    name: "Wand of Secrets",
    type: "Wand",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 211",
    description: "Wand. Uncommon",
    text: "Source: DMG 211",
  },
  {
    id: "wandofweb_items",
    title: "Wand of Web",
    name: "Wand of Web",
    type: "Wand",
    rarity: "Uncommon",
    attunement: "requires attunement by a spellcaster",
    page: "dmg 212",
    description: "Wand. Uncommon. requires attunement by a spellcaster",
    text: "Source: DMG 212",
  },
  {
    id: "wandofwonder_items",
    title: "Wand of Wonder",
    name: "Wand of Wonder",
    type: "Wand",
    rarity: "Rare",
    attunement: "requires attunement by a spellcaster",
    page: "dmg 212",
    description: "Wand. Rare. requires attunement by a spellcaster",
    text: "Source: DMG 212",
  },
  {
    id: "wandofthewarmage+1+2or+3_items",
    title: "Wand of the War Mage, +1, +2, or +3",
    name: "Wand of the War Mage, +1, +2, or +3",
    type: "Wand",
    rarity: "Uncommon (+1), rare (+2), or very rare (+3)",
    attunement: "requires attunement by a spellcaster",
    page: "dmg 212",
    description:
      "Wand. Uncommon (+1), rare (+2), or very rare (+3). requires attunement by a spellcaster",
    text: "Source: DMG 212",
  },
  {
    id: "weaponofwarning_items",
    title: "Weapon of Warning",
    name: "Weapon of Warning",
    type: "Weapon",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 213",
    description: "Weapon. Uncommon. requires attunement",
    text: "Source: DMG 213",
  },
  {
    id: "weapon+1+2or+3_items",
    title: "Weapon, +1, +2, or +3",
    name: "Weapon, +1, +2, or +3",
    type: "Weapon",
    rarity: "Uncommon (+1), rare (+2), or very rare (+3)",
    attunement: "no",
    page: "dmg 213",
    description: "Weapon. Uncommon (+1), rare (+2), or very rare (+3)",
    text: "Source: DMG 213",
  },
  {
    id: "wellofmanyworlds_items",
    title: "Well of Many Worlds",
    name: "Well of Many Worlds",
    type: "Wondrous Item",
    rarity: "Legendary",
    attunement: "no",
    page: "dmg 213",
    description: "Wondrous Item. Legendary",
    text: "Source: DMG 213",
  },
  {
    id: "windfan_items",
    title: "Wind Fan",
    name: "Wind Fan",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "no",
    page: "dmg 213",
    description: "Wondrous Item. Uncommon",
    text: "Source: DMG 213",
  },
  {
    id: "wingedboots_items",
    title: "Winged Boots",
    name: "Winged Boots",
    type: "Wondrous Item",
    rarity: "Uncommon",
    attunement: "requires attunement",
    page: "dmg 214",
    description: "Wondrous Item. Uncommon. requires attunement",
    text: "Source: DMG 214",
  },
  {
    id: "wingsofflying_items",
    title: "Wings of Flying",
    name: "Wings of Flying",
    type: "Wondrous Item",
    rarity: "Rare",
    attunement: "requires attunement",
    page: "dmg 214",
    description: "Wondrous Item. Rare. requires attunement",
    text: "Source: DMG 214",
  },
];
