// wilderness.js
//


top.wilderness = [

// beginning of wilderness



 {"title": "d6 Foliage The plant life is...", "id":"d6foliagetheplantlifeis", "roll":[
"green, waving grass, several feet high.",
"Short tight grass clumps intermingled with shrubbery.",
"Yellowish grass that grows low to the ground, with the occasional tree growing by itself.",
"Sparce, with only clumps of dark green and brown scrub brush every few yards.",
"Groves of trees growing every few hundred yards among tall grasses, as if nature(or someone) is trying to seed a forest.",
"Briar patches and mildly poisonous plants that have choked out most of the other plant life.",   ]},
 {"title": "d20 Perception fodder You notice...", "id":"d20perceptionfodderyounotice", "roll":[
"the sun becomes obscured by the clouds.",
"a well used animal trail.",
"a hawk flying high overhead.",
"the croaking of frogs at a nearby water source.",
"small mammals playing/fighting loudly that suddenly grow silent and disappear as you approach.",
"a light breeze blows, carrying the scent of wood smoke.",
"a strong wind gusts, carrying the sound of thunder and scent of approaching rain.",
"the faint thumping of drums in the distance.",
"a plume of smoke on the horizon.",
"the buzzing and singing of insects hidden in the foliage.",
"the scent of death and decay.",
"a sickly sweet smelling flowered bush.",
"a sudden gust of wind brings a strange smell, but it fades quickly as the wind dies down.",
"the faint rattling of a serpent's tail nearby.",
"the chirping of a flock of small birds that takes the air when you approach.",
"a trail of fresh blood.",
"a mound of loose earth, as if something was recently buried.",
"a swarm of insects buzzing loudly around a dead animal.",
"a faint rumbling in the ground that stops after a moment or two.",
"a nearby boulder covered with a swarm of ants. A busy day in the anthill, indeed.",   ]},
 {"title": "d20 Interesting locations You come across...", "id":"d20interestinglocationsyoucomeacross", "roll":[
"several standing stones on top of a hill and arranged in a strange design.",
"an ancient monolith constructed of a material not found native in the area.",
"a rushing stream that snakes its way across the plains.",
"a large watering hole used by numerous forms of wildlife.",
"a rocky cave opening jutting out of the ground.",
"a group of indigenous nomads, stopping for a time before continuing their journey.",
"a village of settlers from a nearby civilization.",
"a series of sink holes that drop several hundred feet into the earth.",
"the ruins of a long abandoned military outpost/fort.",
"a lone tree with several skeletons dangling from nooses.",
"a makeshift quarry dug into the ground where large chunks of stone have been cut out and chiseled into statues.",
"a lone gravestone. Large, but sunken into the ground. The engraving is in a language not spoken in this region.",
"a low swampy area, full of foul smelling water and brightly colored flowers.",
"a huge boulder sitting alone in a field. Into the sides are scrawled all kinds of glyphs, most partially worn away by time.",
"a tall hill or cliff, standing several hundred feet higher than the surrounding terrain. You can see for miles from the top.",
"a stone well, recently used by a group of herdsmen, their livestock having left tracks nearby.",
"a forgotten stone tower, collapsing from the ravages of time.",
"a fairy ring, several feet in diameter, with a statue of two elves dancing in the center.",
"a large Elven hunting lodge, a fine roof and floor with no walls. Some elven hunters meditate inside while the rest hunt in the plains.",
"a religious shrine in disrepair. It bears a map of all points on a long forgotten pilgrimage.",   ]},
 {"title": "d8 What are the standing stones used for?", "id":"d8whatarethestandingstonesusedfor?", "roll":[
"Druidic conclave meetings.",
"Pagan sacrifices or rituals.",
"necromantic summonings.",
"devil summonings.",
"political gathering of tribes.",
"seasonal feasting.",
"duels of honor, often to the death.",
"religious rites and offerings to a deity.",   ]},
 {"title": "d8 What's up with the monolith?", "id":"d8whatsupwiththemonolith?", "roll":[
"Pulses of magic emanate from it, felt by any magic sensitive creatures (including players) nearby, drawing them to touch it.",
"It casts a shadow the doesn't move with the sun. At night, the \"shadow\" is actually brighter than the ground.",
"Its surface is covered in strange runes that shift about when inspected, inducing a headache.",
"Magic does not work in its immediate vicinity, and acts strangely while cast within line of sight.",
"The pieces of the monolith can be shifted and turned in a number of ways, yet it somehow always seems to look the same.",
"A faint, very deep, humming can be heard emanating from inside it. Almost so low as to be a vibration, rather than a sound. Induces nausea if one is exposed for too long.",
"Wildlife that approach within twenty feet of it seem to simply tip over and die, as demonstrated by the ring of old and new corpses surrounding it. Humanoids seem to be unaffected.",
"Certain objects and colors seem to glow with an unnatural brilliance when near the monolith. (Treat the effect as a black light. White items, and other brightly colored things, glow strangely)",   ]},
 {"title": "d8 What lives in the rocky cave?", "id":"d8whatlivesintherockycave?", "roll":[
"a slightly unhinged hermit.",
"a pack of wolves.",
"a minotaur, the entrance to its labyrinth camouflaged as a cave.",
"a tribe of troglodytes.",
"an exiled Deep Gnome.",
"a feral child, raised by local fauna.",
"a retired trapper, living out his final days.",
"Nothing near the surface, but the cave goes deep. Very deep....",   ]},
 {"title": "d6. Who are the nomads?", "id":"d6whoarethenomads?", "roll":[
"a tribe of centaurs, wary of outsiders.",
"a family of gypsies, heading for a nearby town or city.",
"Livestock herders, on their way to new grazing land as the season changes.",
"a caravan of traveling merchants, making the very long, but very profitable, journey to a far off land.",
"a small band of doppelgangers, posing as a hunting party.",
"a village of halflings, driven from their home.",   ]},
 {"title": "d6 What's under the sink holes?", "id":"d6whatsunderthesinkholes?", "roll":[
"an abandoned mine.",
"the ruins of a village, swallowed by the earth.",
"an ancient temple to a pagan deity.",
"an underground river, flowing into the deep.",
"an ankheg colony.",
"a massive cave network.",   ]},
 {"title": "d6 What is in/under the lone tree?", "id":"d6whatisinunderthelonetree?", "roll":[
"a group of will-o-wisps.",
"a vain banshee.",
"a green hag, ready to strike a bargain.",
"a transplanted colony of pixies and sprites, hoping to seed a new forest.",
"a grumpy giant badger.",
"a swarm of giant wolf spiders.",   ]},
 {"title": "d12 Wildlife Encounters(neutral) You encounter...", "id":"d12wildlifeencountersneutralyouencounter", "roll":[
"a large cat apathetically watching you, well camouflaged against its native terrain.",
"several large snakes that slither off into the brush when you get too close.",
"a herd of bison, grazing lazily.",
"a family of ground rodents that watch you curiously from the safety of their burrow entrances.",
"a pack of coyotes out for a meal.",
"wild hogs rooting in the ground.",
"a herd of elephants/woolly mammoth.",
"a fat, ambling bear.",
"a herd of wild horses stampeding across the plains.",
"a flock of ground fowl, loudly protesting as you approach their nesting area.",
"a lone crow watching as you pass by. It hops after you a few steps at time to get a better look and then flies away, cawwing loudly.",
"a rhinoceros, taking a dust bath.",   ]},
 {"title": "d12 Enemy Encounters You come upon/are beset by (challenge rating ~2-6)", "id":"d12enemyencountersyoucomeuponarebesetbychallengerating~2-6", "roll":[
"a bandit raiding party.",
"an ankheg ambushing you from below!",
"a small flock of cockatrice(s?).",
"a hobgoblin patrol.",
"a trio of motionless scarecrows near an abandoned cottage.",
"a wandering ogre.",
"a hungry Manticore.",
"same as #4 plus a Hobgoblin captain.",
"a raging bull elephant.",
"a burrowing Bullette.",
"a soaring Chimera.",
"a shambling cyclops.",   ]},
 {"title": "d12 Friendly encounters You cross paths with", "id":"d12friendlyencountersyoucrosspathswith", "roll":[
"an explorer, heading out into the unknown wilds.",
"a surveyor, marking landmarks and distances on a map in the wake of an explorer.",
"a miner, coming back to civilization with many valuables and oddities to sell.",
"an artist, pursuing their inspiration in the wilderness.",
"a grizzled old veteran, looking for their final battle.",
"an elderly druid, preparing a ritual to perform during an upcoming astral event (solstice, equinox, eclipse, etc).",
"a nomadic tribe of centaurs traveling across the plains.",
"an acolyte of a nature deity, undergoing a pilgrimage.",
"a noble and their entourage, returning from a big game hunt.",
"a tribal warrior, returning to their village from a successful hunt.",
"a bounty hunter, tracking a fugitive.",
"a revenant, tirelessly making its way back to civilization to exact its ultimate revenge.",   ]},



{"title": "d12 Interesting Location: You find...", "id":"d12interestinglocationyoufind", "roll":[
"A cavern in a canyon wall.",
"A hole under a large boulder.",
"A large burrow.",
"A small cave next to a dry river bed.",
"A peculiar tent.",
"Some nomads’ camp.",
"An abandoned stone house.",
"An abandoned campsite.",
"An entrance to a rocky cave.",
"Ancient ruins.",
"A wide-mouthed cave.",
"An old tomb.",
]},
{"title": "d12 Distinguishing Landmark: You see...", "id":"d12distinguishinglandmarkyousee", "roll":[
"An oasis with a fruit tree.",
"An oasis with a palm tree and some desert flowers.",
"An unusually large, prickly desert plant.",
"A pair of prickly plants from the same root.",
"A patch of desert flowers in the shade of a boulder.",
"A rocky bluff.",
"A boulder shaped like a face.",
"A pair of identical boulders, side by side.",
"A boulder sitting atop a larger boulder.",
"A small, rocky canyon with a trickle of water.",
"A deep, rocky canyon with a trickle of water.",
"A dry river bed.",
]},
{"title": "d20 Feature: You notice...", "id":"d20featureyounotice", "roll":[
"A buzzard circles overhead.",
"A vulture screams.",
"A scorpion scuttles away.",
"A large beetle scuttles away.",
"A toad hops behind a rock.",
"A lizard crawls under a rock.",
"A jackal barks.",
"A snake slithers away.",
"A butterfly flutters by.",
"A rattlesnake sounds.",
"An unusual bird chirps.",
"A gentle breeze blows.",
"The wind blows harder.",
"The wind kicks up dust.",
"Small lose stones tumble down a slope.",
"A hint of moisture on the ground.",
"A prickly plant with brightly colored fruit.",
"A strange desert flower.",
"A small palm tree.",
"Several small prickly plants.",
]},
{"title": "d12 Encounters: You come upon...", "id":"d12encountersyoucomeupon", "roll":[
"A poisonous snake.",
"A giant spider.",
"A pack of jackals.",
"A giant lizard.",
"A ghost.",
"A pair of gnolls.",
"A pair of bandits.",
"A strange hermit.",
"A lost traveler.",
"A poor nomad.",
"A sandstorm.",
"A mirage of an oasis.",
]},
{"title": "d10 What’s in the cave/cavern?", "id":"d10whatsinthecavecavern", "roll":[
"A swarm of beetles.",
"Lots of bats.",
"Many spider webs.",
"A troll's stash.",
"An ogre's lair.",
"Some gnolls’ hideout.",
"Bare rock.",
"Mummified remains.",
"Some bandits’ hideout.",
"A reclusive sorcerer.",
]},
{"title": "d6 What’s in the hole/burrow?", "id":"d6whatsintheholeburrow", "roll":[
"A snake.",
"A spider.",
"Beetles.",
"Scorpions.",
"A toad.",
"A lizard.",
]},
{"title": "d6 Who lives in the peculiar tent?", "id":"d6wholivesinthepeculiartent", "roll":[
"A merchant of exotic goods.",
"A misanthropic shapeshifter.",
"An eccentric monk.",
"A nomadic herder.",
"A nomadic warrior.",
"An outcast elf.",
]},
{"title": "d6 Who lived in the stone house?", "id":"d6wholivedinthestonehouse", "roll":[
"A strange hermit.",
"A reclusive scholar.",
"An eccentric healer.",
"A poor goatherder.",
"A horse trader.",
"A mining prospector.",
]},
{"title": "d6 Who resides in the stone house now?", "id":"d6whoresidesinthestonehousenow", "roll":[
"Poisonous snakes.",
"An ogre.",
"A pair of orcs.",
"A mad sorcerer.",
"A paranoid shapeshifter.",
"Restless ghosts.",
]},
{"title": "d10 Who built the ancient ruins?", "id":"d10whobuilttheancientruins", "roll":[
"A tribe of lizardfolk.",
"A high elf prince.",
"A fiendish cult.",
"A dragon cult.",
"A death cult.",
"Elementalist monks.",
"A long-dead emperor.",
"A forgotten king.",
"An evil queen.",
"A dark sorcerer.",
]},
{"title": "d10 Who lives in the ancient ruins now?", "id":"d10wholivesintheancientruinsnow", "roll":[
"A treasure hunter.",
"A wasteland druid.",
"Poisonous snakes.",
"Cursed mummies.",
"Restless ghosts.",
"An orkish war band.",
"A tribe of kobolds.",
"A territorial griffon.",
"A pair of manticores.",
"A dragon.",
]},
{"title": "d10 Interesting Location: You find...", "id":"d10interestinglocationyoufind", "roll":[
"A cavern in a canyon wall.",
"A hole under a large boulder.",
"A large burrow.",
"A small cave in a volcanic rock formation.",
"A peculiar tent.",
"Some nomads’ camp.",
"A large pit that periodically belches fire and smoke.",
"An abandoned campsite.",
"An entrance to a rocky cave.",
"Ancient ruins.",
]},
{"title": "d12 Distinguishing Landmark: You see...", "id":"d12distinguishinglandmarkyousee", "roll":[
"An oasis with only a puddle of water.",
"Several holes, emitting fire and smoke.",
"An unusually large, prickly desert plant.",
"A pair of prickly plants from the same root",
"A patch of coarse grass in the shade of a boulder.",
"A rocky bluff.",
"A boulder shaped like a face.",
"A pair of identical boulders, side by side.",
"A boulder sitting atop a larger boulder.",
"A small, dry, rocky canyon.",
"A deep, dry, rocky canyon.",
"A solid bed of rock, formed from a lava flow.",
]},
{"title": "d20 Feature: You notice...", "id":"d20featureyounotice", "roll":[
"A buzzard circles overhead.",
"A vulture screams.",
"A scorpion scuttles away.",
"A large beetle scuttles away.",
"A lizard crawls under a rock.",
"A jackal barks.",
"A snake slithers away.",
"A swarm of locusts buzz past.",
"A rattlesnake sounds.",
"An unusual bird chirps.",
"A gentle breeze blows.",
"The wind blows harder.",
"The wind kicks up dust.",
"Small lose stones tumble down a slope.",
"A prickly plant with scorch marks.",
"A strange desert flower.",
"A dead palm tree.",
"Several small prickly plants.",
"The smell of sulfur in the air.",
"The smell of ash and smoke.",
]},
{"title": "d12 Encounters: You come upon...", "id":"d12encountersyoucomeupon", "roll":[
"A flame snake.",
"A swarm of scorpions.",
"A pack of jackals.",
"A giant centipede.",
"A ghost.",
"A pair of azers.",
"A pair of salamanders.",
"A pair of bandits.",
"A strange hermit.",
"A lost traveler.",
"A dust storm.",
"A sudden eruption of flame from the ground.",
]},
{"title": "d10 What’s in the cave/cavern?", "id":"d10whatsinthecavecavern", "roll":[
"A swarm of beetles.",
"Lots of bats.",
"Many spider webs.",
"A troll's stash.",
"An ogre's lair.",
"Some gnolls’ hideout.",
"Bare rock.",
"Mummified remains.",
"Some bandits’ hideout.",
"A reclusive sorcerer.",
]},
{"title": "d6 What’s in the hole/burrow?", "id":"d6whatsintheholeburrow", "roll":[
"A snake.",
"Dry bones.",
"Beetles.",
"Scorpions.",
"A centipede.",
"A flameskull.",
]},
{"title": "d6 Who lives in the peculiar tent?", "id":"d6wholivesinthepeculiartent", "roll":[
"A merchant of exotic goods.",
"A misanthropic shapeshifter.",
"A reclusive monk.",
"A refugee far from home.",
"A dragonborn warrior.",
"A nomadic sorcerer.",
]},
{"title": "d6 What is in the large pit?", "id":"d6whatisinthelargepit", "roll":[
"Several flame snakes.",
"A salamander raider.",
"An azer scout.",
"A fire giant.",
"A phoenix.",
"Scorched bones.",
]},
{"title": "d10 Who built the ancient ruins?", "id":"d10whobuilttheancientruins", "roll":[
"A clan of fire giants.",
"A high elf prince.",
"A fiendish cult.",
"A dragon cult.",
"An elemental cult.",
"Elementalist monks.",
"A long-dead emperor.",
"An ambitious djinn prince.",
"A wicked efreet lord.",
"A dark sorcerer.",
]},
{"title": "d10 Who lives in the ancient ruins now?", "id":"d10wholivesintheancientruinsnow", "roll":[
"A clan of fire giants.",
"A master martial artist.",
"An exiled efreet.",
"Cursed mummies.",
"Restless ghosts.",
"A salamander war band.",
"A clan of dragonborn refugees.",
"A territorial griffon.",
"A pair of manticores.",
"A dragon.",
]},
{"title": "d12 Interesting Location: You find...", "id":"d12interestinglocationyoufind", "roll":[
"A cavern in a canyon wall.",
"A hole under a large boulder.",
"A large burrow.",
"A small cave next to a dry river bed.",
"A pair of graves.",
"A peculiar tent.",
"Some nomads’ camp.",
"An abandoned stone house.",
"An abandoned campsite.",
"An entrance to a rocky cave.",
"An ancient tomb.",
"Ancient ruins.",
]},
{"title": "d12 Distinguishing Landmark: You see...", "id":"d12distinguishinglandmarkyousee", "roll":[
"An oasis with a tree bearing rotten fruit.",
"An oasis with foul-smelling water.",
"An unusually large, prickly desert plant.",
"A pair of prickly plants from the same root.",
"A patch of coarse grass next to a boulder, shrouded in a strange mist.",
"A rocky bluff.",
"A boulder shaped like a skull.",
"A pair of identical boulders, side by side.",
"A boulder sitting atop a larger boulder.",
"A small, rocky canyon with a trickle of foul water.",
"A deep, rocky canyon with a trickle of foul water.",
"A dry river bed.",
]},
{"title": "d20 Feature: You notice...", "id":"d20featureyounotice", "roll":[
"A buzzard circles overhead.",
"A vulture screams.",
"A flock of crows scatter.",
"A large beetle scuttles away.",
"A raven croaks.",
"A crow caws.",
"A rat scurries away.",
"A swarm of beetles crawl past.",
"A ghostly presence flees.",
"A ghostly presence watches curiously.",
"A beast howls mournfully in the distance.",
"An eerie silence.",
"The wind kicks up dust.",
"The breeze stops.",
"The wind moans eerily.",
"Small lose stones tumble down a slope.",
"A dead palm tree.",
"A distant scream.",
"The smell of rotting flesh.",
"The smell of decay.",
]},
{"title": "d12 Encounters: You come upon...", "id":"d12encountersyoucomeupon", "roll":[
"A giant spider.",
"A pack of wolves.",
"An animated skeleton.",
"A malevolent ghost.",
"A restless ghost.",
"A pair of ghouls.",
"A pair of bandits.",
"A strange hermit.",
"A lost traveler.",
"A destitute nomad.",
"A dust storm.",
"A thick, cold fog.",
]},
{"title": "d10 What’s in the cave/cavern?", "id":"d10whatsinthecavecavern", "roll":[
"A swarm of beetles.",
"Lots of bats.",
"Many spider webs.",
"A wight’s stash.",
"A ghoul’s lair.",
"Several skeletons.",
"Bare rock.",
"Mummified remains.",
"Some bandits’ hideout.",
"A creepy hermit.",
]},
{"title": "d6 What’s in the hole/burrow?", "id":"d6whatsintheholeburrow", "roll":[
"A snake.",
"A spider.",
"Beetles.",
"Scorpions.",
"A severed limb.",
"Dry bones.",
]},
{"title": "d6 Who lives in the peculiar tent?", "id":"d6wholivesinthepeculiartent", "roll":[
"A merchant of exotic goods.",
"A misanthropic shapeshifter.",
"An eccentric shadow monk.",
"A nomadic herder.",
"A nomadic warrior.",
"An outcast elf.",
]},
{"title": "d6 Who lived in the stone house?", "id":"d6wholivedinthestonehouse", "roll":[
"A strange hermit.",
"A reclusive scholar.",
"An eccentric healer.",
"A poor goatherder.",
"Someone who left no trace.",
"A member of an ancient clan.",
]},
{"title": "d6 Who resides in the stone house now?", "id":"d6whoresidesinthestonehousenow", "roll":[
"A death hound.",
"A handful of zombies.",
"A paranoid shapeshifter.",
"A mad necromancer.",
"A malevolent ghost.",
"Restless ghosts.",
]},
{"title": "d10 Who built the ancient ruins?", "id":"d10whobuilttheancientruins", "roll":[
"A clan of shadowfolk.",
"A dark elf queen.",
"A fiendish cult.",
"A dragon cult.",
"A death cult.",
"Shadow monks.",
"A long-dead emperor.",
"A forgotten king.",
"An ambitious lich.",
"A dark sorcerer.",
]},
{"title": "d10 Who lives in the ancient ruins now?", "id":"d10wholivesintheancientruinsnow", "roll":[
"A brilliant necromancer.",
"Starved ghouls.",
"Undead guardians.",
"Cursed mummies.",
"Restless ghosts.",
"A shadowfolk war band.",
"An aberrant presence.",
"A pack of death hounds.",
"A pair of manticores.",
"A dracolich.",
]},
{"title": "d10 Who is in the ancient tomb?", "id":"d10whoisintheancienttomb", "roll":[
"The remains of an ancient king.",
"The remains of an ancient queen.",
"The remains of an ancient sorcerer.",
"A powerful mummy.",
"An ancient demilich.",
"The remains of ancient monks.",
"Twisted humanoid bones.",
"Malevolent ghosts.",
"Zombie warriors.",
"Huge, disorganized piles of bones.",
]},
{"title": "d10 Who is in the grave?", "id":"d10whoisinthegrave", "roll":[
"The corpse of a young maiden.",
"The bones of a child.",
"The bones of an old man.",
"The bones of an old woman.",
"A fallen adventurer, hastily buried.",
"A dismembered corpse.",
"Twisted humanoid bones.",
"A pile of bones.",
"A hateful mummy.",
"An empty coffin",
]},
{"title": "d12 Interesting Location: You find...", "id":"d12interestinglocationyoufind", "roll":[
"A cavern behind a waterfall.",
"A small cave in the bank of a creek.",
"An entrance to a rocky cave.",
"A hole under a large tree.",
"A large burrow.",
"A peculiar cottage.",
"A woodsman's cabin.",
"An abandoned cabin.",
"An abandoned campsite.",
"A sacred grove.",
"A grave with an illegible headstone.",
"Ancient ruins.",
]},
{"title": "d20 Distinguishing Landmark: You see...", "id":"d20distinguishinglandmarkyousee", "roll":[
"A fruit tree.",
"A large, hollow tree.",
"A pair of trees from the same root.",
"A tree growing over a boulder.",
"A clearing with wildflowers.",
"A grassy clearing.",
"A moss-covered boulder.",
"A thicket of brambles.",
"A babbling brook.",
"A brook in a deep ravine.",
"A brook, with gentle rapids.",
"A dry creekbed.",
"A small pool at a creek's bend.",
"A patch of mushrooms.",
"An enormous mushroom.",
"A large, hollow log.",
"A large, rotting log.",
"A tree felled by lightning.",
"An old gnarled tree.",
"The stump of an enormous tree.",
]},
{"title": "d20 Feature: You notice...", "id":"d20featureyounotice", "roll":[
"A flock of birds scatter.",
"A hawk cries.",
"A woodpecker drumming.",
"An owl hoots.",
"Birds chirping.",
"A chipmunk scurrying.",
"A deer dashes away.",
"A deer watches curiously.",
"A squirrel leaps from one tree to another.",
"A wolf howls.",
"Butterflies fluttering about.",
"Squirrels chittering.",
"An eerie silence.",
"The breeze stops.",
"The wind blows harder.",
"A twig snaps.",
"Brightly, colored berries.",
"Leaves rustling.",
"The scent of flowers.",
"The smell of decay.",
]},
{"title": "d20 Dominant Species: Many of the trees are...", "id":"d20dominantspeciesmanyofthetreesare", "roll":[
"Apple or pear trees.",
"Ashes.",
"Birches.",
"Beeches.",
"Cedars or junipers.",
"Cherry or plum trees.",
"Chestnut or hazel trees.",
"Cypresses.",
"Elms.",
"Firs.",
"Hawthorns or hemlocks.",
"Hickory or walnut trees.",
"Linden or lime trees.",
"Maples.",
"Oaks.",
"Pines.",
"Poplars.",
"Spruces.",
"Willows.",
"Yew or holly trees.",
]},
{"title": "d12 What’s in the cave/cavern?", "id":"d12whatsinthecavecavern", "roll":[
"A bear’s lair.",
"Lots of bats.",
"Many spider webs.",
"A troll's stash.",
"An ogre's lair.",
"Some goblins' hideout.",
"Some abandoned mining equipment.",
"Bare rock.",
"A potable spring.",
"Unidentifiable remains.",
"Some outlaws’ hideout.",
"A strange hermit.",
]},
{"title": "d20 Encounters: You come upon...", "id":"d20encountersyoucomeupon", "roll":[
"A large bear.",
"A bear cub.",
"A giant spider.",
"Several giant spiders.",
"A pack of wolves.",
"A lone wolf.",
"A hunting cat.",
"A wailing ghost.",
"A malevolent ghost.",
"A pair of goblin scouts.",
"A goblin patrol.",
"An ogre.",
"A pair of outlaws.",
"A beggarly bandit.",
"An old witch.",
"A curious herbalist.",
"A lost child.",
"A woodcutter busy with the day’s work.",
"An intrepid hunter.",
"An elvish ranger.",
]},
{"title": "d6 Who lives in the peculiar cottage?", "id":"d6wholivesinthepeculiarcottage", "roll":[
"A lonely old woman.",
"A reclusive shapeshifter.",
"An eccentric healer.",
"A beautiful witch.",
"A horrible witch.",
"An outcast dwarf.",
]},
{"title": "d6 Who lived in the abandoned cabin?", "id":"d6wholivedintheabandonedcabin", "roll":[
"A lonely old woman.",
"A reclusive scholar.",
"an eccentric healer.",
"A poor woodcutter.",
"A fur trader.",
"A dwarf prospector.",
]},
{"title": "d6 Who resides in the abandoned cabin now?", "id":"d6whoresidesintheabandonedcabinnow", "roll":[
"An owlbear.",
"An ogre.",
"A troll.",
"A mad witch.",
"A paranoid shapeshifter.",
"Restless ghosts.",
]},
{"title": "d10 Who built the ancient ruins?", "id":"d10whobuilttheancientruins", "roll":[
"Dwarvish miners.",
"A wood elf king.",
"A high elf prince.",
"A dragon cult.",
"A death cult.",
"Shadow monks.",
"A long-dead emperor.",
"A forgotten king.",
"An evil queen.",
"A dark sorcerer.",
]},
{"title": "d10 Who lives in the ancient ruins now?", "id":"d10wholivesintheancientruinsnow", "roll":[
"A dwarf prospector.",
"A wood elf druid.",
"Poisonous snakes.",
"Giant spiders.",
"Hungry zombies.",
"Restless ghosts.",
"A handful of ogres.",
"Some irritable trolls.",
"A pair of manticores.",
"A dragon.",
]},
{"title": "d6 What’s in the hole/burrow?", "id":"d6whatsintheholeburrow", "roll":[
"A snake.",
"A spider.",
"A badger.",
"Earthworms.",
"A centipede.",
"Unusual fungus.",
]},
{"title": "d12 Interesting Location: You find...", "id":"d12interestinglocationyoufind", "roll":[
"A cavern behind a waterfall.",
"A house under a large tree.",
"A large burrow with a door.",
"A small cave in the bank of a creek.",
"A peculiar cottage.",
"A house up in a tree.",
"A well-maintained cottage.",
"A ring of mushrooms.",
"An entrance to a rocky cave.",
"Ancient ruins.",
"A reflecting pool between colonnades.",
"The statue of a goddess on a beautiful marble fountain.",
]},
{"title": "d20 Distinguishing Landmark: You see...", "id":"d20distinguishinglandmarkyousee", "roll":[
"A lush fruit tree.",
"A large, hollow tree.",
"A pair of trees from the same root.",
"A tree growing over a boulder.",
"A clearing with wildflowers.",
"A grassy clearing.",
"A moss-covered boulder.",
"A thicket of flowering bushes.",
"A babbling brook.",
"A brook in a deep ravine.",
"A brook, with gentle rapids.",
"A creek with flowers on its bank.",
"A small pool at a creek's bend.",
"A patch of mushrooms.",
"An enormous mushroom.",
"A large, hollow log.",
"A large, rotting log.",
"A tree felled by lightning.",
"An old gnarled tree.",
"The stump of an enormous tree.",
]},
{"title": "d20 Feature: You notice...", "id":"d20featureyounotice", "roll":[
"A flock of birds scatter.",
"A hawk cries.",
"A woodpecker drumming.",
"An owl hoots.",
"Birds chirping.",
"A chipmunk scurrying.",
"A deer dashes away.",
"A deer watches curiously.",
"A squirrel leaps from one tree to another.",
"A wolf howls.",
"Butterflies fluttering about.",
"Squirrels chittering.",
"Distant music from a harp.",
"Distant music from a flute.",
"A warm breeze blows.",
"A twig snaps.",
"Brightly, colored berries.",
"Leaves rustling.",
"The scent of flowers.",
"Pixies dancing in the distance.",
]},
{"title": "d12 What’s in the cave/cavern?", "id":"d12whatsinthecavecavern", "roll":[
"A bear’s lair.",
"Lots of bats.",
"Many spider webs.",
"A troll's stash.",
"An ogre's lair.",
"Some goblins' hideout.",
"Fragrant mushrooms.",
"A lingering ghost.",
"Some lizardfolk’s lair.",
"The remnant’s of a satyr’s feasting.",
"A mysterious chest.",
"A reflecting pool between a pair of beautiful stone colonnades.",
]},
{"title": "d20 Encounters: You come upon...", "id":"d20encountersyoucomeupon", "roll":[
"A large bear.",
"A bear wearing a collar.",
"A giant spider.",
"A talking spider.",
"An enormous anthill.",
"A pack of wolves.",
"A talking wolf.",
"A displacer beast.",
"A moaning ghost.",
"A mischievous ghost.",
"A pair of goblin scouts.",
"A hobgoblin beasthunter.",
"Several tiny faeries.",
"A dozen or more pixies.",
"A protective sprite.",
"A dancing satyr.",
"An old witch.",
"A lost child.",
"A high elf sage.",
"A wood elf wanderer.",
]},
{"title": "d6 Who lives in the burrow/under the tree?", "id":"d6wholivesintheburrowunderthetree", "roll":[
"Intelligent rabbits.",
"A giant talking spider.",
"A talking badger.",
"A gnomish illusionist.",
"A gnomish prankster.",
"A suspicious sprite.",
]},
{"title": "d8 Who lives up in the tree?", "id":"d8wholivesupinthetree", "roll":[
"A giant owl.",
"A talking raven.",
"A wood elf ranger.",
"A high elf sentinel.",
"A band of friendly pixies.",
"Several nervous sprites.",
"A swarm of sentient butterflies.",
"It’s not a tree; it’s a treant.",
]},
{"title": "d6 Who lives in the peculiar/well-maintained cottage?", "id":"d6wholivesinthepeculiarwellmaintainedcottage", "roll":[
"A lonely old gnome.",
"A reclusive shapeshifter.",
"A gnomish healer.",
"A beautiful witch.",
"A horrible witch.",
"An outcast dwarf.",
]},
{"title": "d10 Who built the ancient ruins?", "id":"d10whobuilttheancientruins", "roll":[
"A great goblin king.",
"A wood elf king.",
"A high elf prince.",
"A dragon cult.",
"The god of wine himself.",
"A lizardfolk tribe.",
"A long-dead emperor.",
"A forgotten king.",
"An evil queen.",
"A dark sorcerer.",
]},
{"title": "d12 Who lives in the ancient ruins now?", "id":"d12wholivesintheancientruinsnow", "roll":[
"A high elf guardian.",
"A wood elf druid.",
"A pack of blink dogs.",
"Giant spiders.",
"Restless ghosts.",
"A wicked satyr.",
"Hundreds of pixies.",
"Some wary centaurs.",
"A cloistered dryad.",
"A displacer beast.",
"A pair of manticores.",
"A dragon.",
]},
{"title": "d10 Interesting Location: You find...", "id":"d10interestinglocationyoufind", "roll":[
"Ancient burial mounds.",
"A hole under a large tree.",
"A large burrow.",
"A peculiar cottage.",
"A forgotten cemetery.",
"A pair of graves.",
"An abandoned cabin.",
"An abandoned campsite.",
"An entrance to a rocky cave.",
"Ancient ruins.",
]},
{"title": "d20 Distinguishing Landmark: You see...", "id":"d20distinguishinglandmarkyousee", "roll":[
"A tree with rotten fruit all around its base.",
"A large, hollow tree.",
"A pair of trees from the same root.",
"A tree growing over a boulder.",
"A clearing with bare ground.",
"A clearing with an old grave marker.",
"A boulder marked with several notches.",
"A thicket of dry brambles.",
"A slow, silent stream.",
"A stream flowing quietly through a ravine.",
"A stream with barren banks.",
"A dry creekbed.",
"A foul smelling pond.",
"A patch of mushrooms.",
"The decaying carcass of a large animal.",
"A large, hollow log.",
"A large, rotting log.",
"A tree felled by lightning.",
"An old gnarled tree.",
"The stump of an enormous tree.",
]},
{"title": "d20 Feature: You notice...", "id":"d20featureyounotice", "roll":[
"A flock of crows scatter.",
"A vulture screams.",
"A raven croaks.",
"An owl hoots.",
"A crow caws.",
"A rat scurrying.",
"A ghostly presence flees.",
"A ghostly presence watches curiously.",
"A bats take to wing from a tree.",
"A wolf howls.",
"A large moth flutters about.",
"Rats squeaking.",
"An eerie silence.",
"The breeze stops.",
"The wind blows harder.",
"A twig snaps.",
"The wind moans eerily.",
"A distant scream.",
"The scent of rotting flesh.",
"The smell of decay.",
]},
{"title": "d20 Encounters: You come upon...", "id":"d20encountersyoucomeupon", "roll":[
"An animated skeleton.",
"A pair of skeletal warriors.",
"A giant spider.",
"A swarm of spiders.",
"A pack of wolves.",
"A savage werewolf.",
"A giant bat.",
"A swarm of bats.",
"A shadow panther.",
"A malevolent ghost.",
"A restless ghost.",
"A hungry ghoul.",
"An animated hatchet.",
"A pair of zombies.",
"A slobbering zombie.",
"A pair of graverobbers.",
"An anxious necromancer.",
"An old witch.",
"A lost child.",
"A gravedigger.",
]},
{"title": "d12 What’s in the cave/cavern?", "id":"d12whatsinthecavecavern", "roll":[
"Several skeletons.",
"Lots of bats.",
"Many spider webs.",
"A wight’s stash.",
"A ghoul’s lair.",
"A ghostly presence.",
"The hideout of a killer on the run.",
"Bare rock.",
"Unidentifiable remains.",
"An abandoned cookfire.",
"Some outlaws’ hideout.",
"A creepy hermit.",
]},
{"title": "d12 Who is in the ancient burial mound?", "id":"d12whoisintheancientburialmound", "roll":[
"The remains of an ancient war chief.",
"The remains of a tribal shaman.",
"The remains of an ancient war chief.",
"A barrow-wight.",
"An ancient demilich.",
"The remains of ancient monks.",
"Twisted humanoid bones.",
"Malevolent ghosts.",
"Zombie warriors.",
"A skeletal hound.",
"An ancient vampire.",
"Huge, disorganized piles of bones.",
]},
{"title": "d10 Who is in the grave?", "id":"d10whoisinthegrave", "roll":[
"The corpse of a young maiden.",
"The corpse of a child.",
"The corpse of an old man.",
"The corpse of an old woman.",
"A fallen adventurer, hastily buried.",
"A dismembered corpse.",
"Twisted humanoid bones.",
"A pile of bones.",
"A newly-made vampire.",
"An empty coffin.",
]},
{"title": "d10 Who built the ancient ruins?", "id":"d10whobuilttheancientruins", "roll":[
"Dwarvish miners.",
"A wood elf king.",
"An ancient elf.",
"A demonic cult.",
"A death cult.",
"Shadow monks.",
"A long-dead emperor.",
"A forgotten king.",
"An evil queen.",
"A dark sorcerer.",
]},
{"title": "d12 Who resides in the ancient ruins now?", "id":"d12whoresidesintheancientruinsnow", "roll":[
"A brilliant necromancer.",
"Starved ghouls.",
"Undead guardians.",
"Giant spiders.",
"So many zombies.",
"Restless ghosts.",
"A vengeful wight.",
"A mad wraith.",
"A cursed mummy.",
"An aberrant presence.",
"A pair of manticores.",
"A dracolich.",
]},
{"title": "d8 What’s in the hole/burrow?", "id":"d8whatsintheholeburrow", "roll":[
"A snake.",
"A spider.",
"Slimy mold.",
"Maggots.",
"A severed limb.",
"Unusual fungus.",
"A decomposing body.",
"Cold, dry bones.",
]},
{"title": "d6 Who lives in the peculiar cottage?", "id":"d6wholivesinthepeculiarcottage", "roll":[
"A lonely old woman.",
"A reclusive shapeshifter.",
"An eccentric healer.",
"A beautiful witch.",
"A horrible witch.",
"A cranky old priest.",
]},
{"title": "d6 Who lived in the abandoned cabin?", "id":"d6wholivedintheabandonedcabin", "roll":[
"A lonely old woman.",
"A reclusive scholar.",
"An eccentric healer.",
"A poor woodcutter.",
"A fur trader.",
"A dwarf prospector.",
]},
{"title": "d6 Who resides in the abandoned cabin now?", "id":"d6whoresidesintheabandonedcabinnow", "roll":[
"A death hound.",
"A handful of zombies.",
"A paranoid shapeshifter.",
"A mad witch.",
"A malevolent ghost.",
"Restless ghosts.",
]},
{"title": "d12 Interesting Location: You find...", "id":"d12interestinglocationyoufind", "roll":[
"A cavern behind a waterfall.",
"The wreck of a riverboat.",
"A cave behind a curtain of tangled of vines.",
"A hole beneath a large tree.",
"A large, damp burrow.",
"A primitive village.",
"A stilt house.",
"A recently vacated campsite.",
"A hastily abandoned campsite.",
"A ruined ancient stone house overgrown with vines.",
"A ruined ancient temple.",
"Ruins of an ancient city.",
]},
{"title": "d20 Distinguishing Landmark: You see...", "id":"d20distinguishinglandmarkyousee", "roll":[
"A tree bearing large, yellow fruit.",
"A tree bearing small, red fruit.",
"A large, hollow tree.",
"A pair of trees from the same root.",
"A tree growing over a boulder.",
"A thicket of brambles.",
"A wide, shallow pool at a river bend.",
"A wide, shallow river with a single large tree growing in its main channel.",
"A moss-covered boulder in the midst of a gently flowing river.",
"Several gentle rapids.",
"A pair of dangerous rapids.",
"A large, gnarled log half-buried in mud.",
"A tree felled by lightning.",
"A colony of colorful mushrooms.",
"An enormous mushroom.",
"A large rock with a mossy overhang.",
"A large, hollow log.",
"A large, rotting log.",
"An old tree with an oddly shaped knot.",
"The stump of an enormous tree.",
]},
{"title": "d20 Feature: You notice...", "id":"d20featureyounotice", "roll":[
"A flock of birds scatter.",
"A woodpecker drumming.",
"A bird singing sweetly.",
"A brightly colored bird flies away.",
"Birds chirping.",
"A monkey drops a fruit or nut from above.",
"A monkey leaps from one tree to another.",
"Large dragonflies buzzing about.",
"Cicadas chirping loudly.",
"Butterflies fluttering about.",
"A centipede scuttles beneath a rock.",
"An eerie silence.",
"Rain falls lightly.",
"The heat and humidity increase.",
"The sound of leaves rustling above.",
"A vine gently swaying.",
"A small snake slithers off.",
"Brightly, colored berries.",
"The scent of flowers.",
"The smell of decay.",
]},
{"title": "d20 Encounters: You come upon...", "id":"d20encountersyoucomeupon", "roll":[
"Torrential rains.",
"A place where you sink into the mud.",
"A predatory plant with grasping vines.",
"A large jungle cat.",
"A small hunting cat.",
"A giant spider.",
"Several giant spiders.",
"A troop of protective apes.",
"A lone great ape.",
"A rare flightless bird.",
"A malevolent ghost.",
"A pair of lizardfolk hunters.",
"A lizardfolk shaman.",
"A yuan-ti patrol.",
"An ogre.",
"A pair of primitive scouts.",
"A skilled primitive hunter.",
"An old witch.",
"A curious herbalist.",
"A ruthless big-game hunter.",
]},
{"title": "d12 Flower Color: The flowers are...", "id":"d12flowercolortheflowersare", "roll":[
"Deep crimson.",
"Blood red.",
"Iridescent orange.",
"Pale yellow.",
"Brilliant yellow.",
"Dark bluish purple.",
"Pale purple.",
"Dark purple.",
"Magenta.",
"Shockingly pink.",
"Pale pink.",
"White.",
]},
{"title": "d10 Flower Shape: The petals are...", "id":"d10flowershapethepetalsare", "roll":[
"Radiating in a spiraling pattern.",
"Radiating from a hemispherical center.",
"Radiating from a conical center.",
"Radiating in a narrow stalk in the center.",
"Paired and curling back from the center.",
"Triangular and flat.",
"Triangular and curled.",
"Ellipsoidal and flat.",
"Ellipsoidal and curled.",
"The largest petals you’ve ever seen.",
]},
{"title": "d4 What kind of riverboat was it?", "id":"d4whatkindofriverboatwasit", "roll":[
"A fisherman's raft.",
"An eeler’s canoe.",
"A beasthunter's dugout.",
"A treasure seeker's keelboat.",
]},
{"title": "d12 What’s in the cave/cavern?", "id":"d12whatsinthecavecavern", "roll":[
"A manticore’s lair.",
"Lots of bats.",
"Many spider webs.",
"A medusa’s stash.",
"An rage drake’s lair.",
"A band of kobolds.",
"Some abandoned mining equipment.",
"Bare rock.",
"A potable spring.",
"Unidentifiable remains.",
"Some treasure hunters’ hideout.",
"A strange hermit.",
]},
{"title": "d8 Who lives in the stilt house?", "id":"d8wholivesinthestilthouse", "roll":[
"A lonely old woman.",
"A reclusive shapeshifter.",
"An eccentric healer.",
"A beautiful witch.",
"A horrible witch.",
"An outcast wood elf.",
"A horrifying medusa.",
"A scheming hag.",
]},
{"title": "d8 Who camped here?", "id":"d8whocampedhere", "roll":[
"A lizardfolk hunting party.",
"A band of wandering elves.",
"A primitive hunting party.",
"A primitive war band.",
"A band of yuan-ti raiders.",
"An extraordinary beasthunter.",
"A brave explorer and naturalist.",
"An ambitious treasure hunter.",
]},
{"title": "d10 Who built the ancient ruins?", "id":"d10whobuilttheancientruins", "roll":[
"A lizardfolk chieftain.",
"An aberrant cult.",
"A snake cult.",
"A dragon cult.",
"A death cult.",
"Shadow monks.",
"A long-dead emperor.",
"A forgotten king.",
"An evil queen.",
"A dark sorcerer.",
]},
{"title": "d12 Who resides in the ruins now?", "id":"d12whoresidesintheruinsnow", "roll":[
"An owlbear.",
"An isolated snake cult.",
"A paranoid shapeshifter.",
"Restless ghosts.",
"Poisonous snakes.",
"Giant spiders.",
"Hungry zombies.",
"Wraiths and shadows.",
"A handful of ogres.",
"A band of lizardfolk warriors.",
"A pair of manticores.",
"A dragon.",
]},
{"title": "d6 What’s in the hole/burrow?", "id":"d6whatsintheholeburrow", "roll":[
"A poisonous snake.",
"A spider.",
"A poisonous frog.",
"A swarm of earthworms.",
"A giant centipede.",
"Unusual fungus.",
]},
{"title": "d6 What’s up in the tree?", "id":"d6whatsupinthetree", "roll":[
"A constrictor snake.",
"A giant spider.",
"A swarm of bats.",
"A swarm of locusts.",
"An aggressive ape.",
"A lizardfolk hunter.",
]},
{"title": "d20 Interesting Location: You find...", "id":"d20interestinglocationyoufind", "roll":[
"A cavern behind a waterfall.",
"A small cave in the crook of a rock wall.",
"An entrance to a rocky cave.",
"A hole under a sheer cliff face.",
"A dark tunnel leading under the mountain.",
"A tunnel in a cliff face.",
"A tunnel leading into an abandoned mine.",
"A peculiar cabin.",
"A cozy little cabin.",
"An abandoned cabin.",
"An abandoned campsite.",
"A poorly marked grave or tomb.",
"An active mining camp.",
"An isolated monastery.",
"A strategically located watchtower.",
"A remote temple.",
"An ancient temple.",
"An abandoned watchtower.",
"A ruined monastery.",
"An enormous bird’s nest.",
]},
{"title": "d20 Distinguishing Landmark: You see...", "id":"d20distinguishinglandmarkyousee", "roll":[
"A trickle of water flowing down a rock wall.",
"A small mountain lake of cold, fresh water.",
"A swiftly flowing small stream.",
"A natural bridge between two cliff faces.",
"A narrow gorge with walls close enough to climb between.",
"A deep gorge with no bottom in sight.",
"A set of deliberately stacked stones.",
"A large boulder eroded by the wind into the shape of a near-perfect sphere.",
"A group of stones arranged in a circle.",
"A boulder shaped to resemble a face.",
"A pair of narrow needle-like peaks.",
"A chimney-like column of rock.",
"A large boulder split in half like an egg.",
"A damp rock wall, covered in moss.",
"The fossilized bones of a great beast visible in a rock wall .",
"A thicket of hardy mountain shrubs growing atop a boulder.",
"A copse of scrawny trees.",
"A gorge where the wind whistles.",
"A gorge with a near perfect echo.",
"A rocky shoulder beneath a snowcap.",
]},
{"title": "d20 Feature: You notice...", "id":"d20featureyounotice", "roll":[
"A cache of abandoned, decrepit mining equipment.",
"Some old dry bones.",
"A small fossilized leaf.",
"Evidence of a recent encampment.",
"An enormous spider web.",
"An incredible view.",
"The clatter of rocks falling.",
"Loose stones underfoot.",
"An unstable rock wall.",
"A distant sound—a scream, hammers at work, footsteps, or drums.",
"The name of a previous traveler carved into a boulder.",
"An ancient rune carved in a rock wall.",
"A scrawny tree growing with its roots spread over a small boulder.",
"The distant cry of a beast—an eagle, a goat, a mountain lion, or a wolf.",
"The wind whips up to a treacherous speed.",
"Snow flurries begin to fall.",
"The sound of birds chirping.",
"A flock of birds takes flight.",
"An old firepit.",
"Several puddles of cold water.",
]},
{"title": "d20 What’s in the cave/cavern/tunnel?", "id":"d20whatsinthecavecaverntunnel", "roll":[
"A mountain lion’s den.",
"Lots of bats.",
"Many spider webs.",
"A troll's stash.",
"An ogre's lair.",
"Some goblins' hideout.",
"Some abandoned mining equipment.",
"Bare rock.",
"A potable spring.",
"Unidentifiable remains.",
"Some outlaws’ hideout.",
"An orc war band.",
"A hungry ettin.",
"A band of dwarvish refugees.",
"A griffon’s nest.",
"A manticore’s den.",
"A basilisk’s lair.",
"A wyvern’s nest.",
"A clan of stone giants.",
"A sleeping dragon.",
]},
{"title": "d6 Who lives or lived in the cabin?", "id":"d6wholivesorlivedinthecabin", "roll":[
"A fugitive from justice.",
"A stubborn miner.",
"A dwarvish prospector.",
"A dwarvish war veteran.",
"A gnomish wizard.",
"A mystic sage.",
]},
{"title": "d8 Who resides in the abandoned cabin now?", "id":"d8whoresidesintheabandonedcabinnow", "roll":[
"An owlbear.",
"An ogre.",
"A troll.",
"A mad witch.",
"A reclusive shapeshifter.",
"Restless ghosts.",
"An outcast orc.",
"A strange hermit.",
]},
{"title": "d6 Who camped here?", "id":"d6whocampedhere", "roll":[
"A party of orc scouts.",
"A goblin raiding party.",
"Some miners or prospectors.",
"A pair of wandering elves.",
"Some refugees or fugitives.",
"Someone whose purposes are unclear.",
]},
{"title": "d4 Who is/was digging in this mine?", "id":"d4whoiswasdigginginthismine", "roll":[
"Greedy dwarves.",
"Ambitious humans.",
"Tricky goblins.",
"Industrious kobolds.",
]},
{"title": "d6 For what were the miners digging?", "id":"d6forwhatweretheminersdigging", "roll":[
"Copper.",
"Gems.",
"Gold.",
"Iron.",
"Silver.",
"A rare metal (d4): 1. adamantine; 2. electrum; 3. mithral; 4. platinum.",
]},
{"title": "d20 What lives in the abandoned mine/ancient ruin now?", "id":"d20whatlivesintheabandonedmineancientruinnow", "roll":[
"Carrion crawler.",
"Cloaker.",
"Darkmantle.",
"Dwarves.",
"Fungi.",
"Kobolds.",
"Ghosts.",
"Mimics.",
"Myconids.",
"Ogres.",
"Ooze.",
"Orcs.",
"Otyugh.",
"Piercer.",
"Roper.",
"Rust monster.",
"Stirges.",
"Trolls.",
"Umber hulk.",
"Wraiths.",
]},
{"title": "d6 Who built this monastery?", "id":"d6whobuiltthismonastery", "roll":[
"An order of elementalist monks.",
"An order of mystics.",
"An extremely secretive order of monks.",
"An order of shadow monks.",
"An order of warrior monks.",
"An unknown order of monks.",
]},
{"title": "d6 The temple was built to honor...", "id":"d6thetemplewasbuilttohonor", "roll":[
"The sun god.",
"The god of the heavens.",
"The moon goddess.",
"The storm god.",
"The earth mother goddess.",
"A long-forgotten god.",
]},
{"title": "d6 What built the nest?", "id":"d6whatbuiltthenest", "roll":[
"A giant eagle.",
"A giant owl.",
"A clan of harpies.",
"A griffon.",
"A roc.",
"A wyvern.",
]},
{"title": "d6 What built the watchtower?", "id":"d6whatbuiltthewatchtower", "roll":[
"An expansive empire.",
"A nearby kingdom.",
"An occupying army.",
"Elvish warriors from a past age.",
"A clan of orcs.",
"A goblin kingdom.",
]},
{"title": "d8 Who holds the watchtower now?", "id":"d8whoholdsthewatchtowernow", "roll":[
"A disciplined military company.",
"A rowdy mercenary troop.",
"A band of desperate outlaws.",
"A handful of dwarves.",
"A clan of orcs.",
"A goblin war party.",
"Several harpies.",
"Ghostly warriors.",
]},
{"title": "d20 Encounters: You come upon...", "id":"d20encountersyoucomeupon", "roll":[
"A lost prospector.",
"A solemn warrior.",
"An angry wraith.",
"A malevolent ghost.",
"Some bandits.",
"A seasoned mountaineer.",
"A paranoid shapeshifter.",
"An ancient vampire.",
"Several homeless dwarves.",
"An eccentric witch.",
"A contemplative monk.",
"A mountain lion.",
"A pair of harpies.",
"A flock of ravens.",
"Several orc raiders.",
"A hunting peryton.",
"A mated pair of manticores.",
"A trio of monstrous trolls.",
"A clan of stone giants at rest.",
"A roc tearing apart some prey.",
]},
{"title": "d8 Hazards/Obstacles: You run into...", "id":"d8hazardsobstaclesyouruninto", "roll":[
"A perilous rockslide.",
"An icy rime across the path or road.",
"A tumbling boulder.",
"Loose rocks that make for poor footing.",
"A large boulder blocking the way.",
"A place where the path has fallen away leaving a narrow ledge on which to walk.",
"A place where the path or road slopes steeply down toward a cliff edge.",
"A sudden storm bringing heavy snow.",
]},
{"title": "d10 Roll Odor", "id":"d10rollodor", "roll":[
"No odor",
"Uncomfortable sulfur smell. After some exposure it causes players eyes to water",
"Death and decay of corpses lost in the swamp",
"Earthy musk",
"Feet from a soldier who has been marching all day",
"Compost pile",
"Wet dog",
"Odorless gas. Players will begin to get headaches if over exposed",
"Spoiled meat",
"Metallic scent that you can also taste in the back of your throat",
]},
{"title": "d10 Roll Perception Fodder", "id":"d10rollperceptionfodder", "roll":[
"Lights moving in the distance. They vanish as players get near",
"The trees are all dead. Their features almost resemble faces...",
"Large sections of waist deep water. Considered difficult terrain",
"Several trees have large claw marks carved into them",
"Canine foot prints that slowly change into human prints",
"A single tree producing apples white as snow. None of them fall to the ground and they are all untouched by other creatures",
"The rotting corpse of a spider the size of a house. No sign of death",
"Small spiderwebs that are face level. DC 14 Perception or walk into them",
"Several humanoid skeletons. Their bones are scattered and look gnawed on",
"A small graveyard. None of the graves are marked and several look as if they were dug up recently",
]},
{"title": "d10 Roll Friendly Critters", "id":"d10rollfriendlycritters", "roll":[
"Clouds of insects buzzing around",
"A murder of crows that remain relatively silent. If players get too close they explode into a roar of cawing and fly around the players madly",
"Large beetles that enjoy resting atop players heads",
"Crawling Claws that skitter away when they get spotted",
"Spiders the size of your fist. They catch birds and bats in their webs",
"Large millipedes crawling in and out of fallen logs",
"Toads that look unusually large",
"Very large brown snakes that look to be branches until disturbed",
"2-3 human children clothed in rags. They speak no languages and flee the party",
"A very lost and confused looking treant. It appears as the swamp is slowly claiming him",
]},
{"title": "d10 Roll Wild Monsters", "id":"d10rollwildmonsters", "roll":[
"Pack of ghouls led by a ghast",
"Pack of jackal led by a jackalwere",
"Several vine blights that lie in wait",
"Gnolls and their leader. Traps are set all through the swamp",
"Otyugh that sees the players as a new meal",
"Several vampire spawn that stalk the players. They strike at night when the party sleeps",
"Group of ghosts. They just want some new company in the swamp",
"Zombies that lie beneath the water. They try to drown whoever gets too close",
"A few Will o wisps. They will attempt to split the party and take them down one by one.",
"Undead treants. Use Zombie template",
]},
{"title": "d10 Roll Boss Monsters", "id":"d10rollbossmonsters", "roll":[
"Coven of hags that has been watching the players since they entered. Haunts their dreams if they sleep in swamp",
"Banshee and her group of ghosts. They are looking for new friends",
"A Spider the size of a house. Has a small spider army following him",
"One or several wraiths. They have a small army of the damned at their command",
"A beholder guarding a graveyard. One of the graves leads to a small dungeon",
"A very weathered looking vampire. He is moving a large coffin with the help of vampire spawns",
"Medusa that is looking to add more statues to her collection. The party is a good start",
"Pack of Lycanthropes that have been terrorizing the nearby farmers/villages",
"A wizard from a nearby town and the flesh golems he is making in the swamp. He isn't thrilled you found him",
"Lich who is working on relocating his lair to here. A castle looks to be under construction",
]},



// end of wilderness

];
