// monsters.js
//


top.monsters = [

{   "title": "Faeriefolk",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d12 The faerie is...",   "roll": [
"A capricious nymph.",
"An apprehensive nymph.",
"A playful nymph.",
"A nervous pixie.",
"A cheerful pixie.",
"A carefree pixie.",
"A wrathful sprite.",
"A curious sprite.",
"A surly sprite.",
"A drunken satyr.",
"A satyr bully.",
"A sharp-witted satyr."    ] },
{  "title": "d20 Hair: The faerie has...",   "roll": [
"Black hair.",
"Copper hair.",
"Golden blonde hair.",
"Platinum blonde hair.",
"Silver-white hair.",
"Dark brown hair.",
"Reddish-brown.",
"Fiery red hair.",
"Light brown hair.",
"Auburn hair.",
"Black hair with a brown streak.",
"Dark brown hair with an auburn streak.",
"Brown hair with a blonde streak.",
"Bright white hair.",
"Silver-blonde hair.",
"Whitish blonde hair.",
"Golden hair with a pink streak.",
"Golden hair with a green streak.",
"Black hair with a blue streak.",
"Black hair with a white streak."    ] },
{  "title": "d20 Eyes: The faerie has...",   "roll": [
"Pale golden eyes.",
"Bright golden eyes.",
"Dark green eyes.",
"Brilliant green eyes.",
"Bright blue eyes.",
"Dark blue eyes.",
"Blue eyes with golden flecks.",
"Green eyes with golden flecks.",
"Pale green eyes.",
"Golden brown eyes.",
"Dark brown eyes.",
"Hazel eyes.",
"Whitish blue eyes.",
"Pale blue eyes.",
"Lilac eyes.",
"Pale violet eyes.",
"Bright violet eyes.",
"Deep red eyes.",
"Pale pink eyes.",
"Silver eyes."    ] },
{  "title": "d12 Mannerisms: The faerie has...",   "roll": [
"A likable grin.",
"A delicate laugh.",
"A playful laugh.",
"A laugh that goes on too long.",
"An amused smirk.",
"A humorless visage.",
"A habit of sighing.",
"A touch of sorrow in his or her voice.",
"A habit of pacing.",
"A habit of scratching the back of the neck.",
"A habit of winking.",
"A seductive sway of the hips."    ] },
{  "title": "d12 The faerie is looking for...",   "roll": [
"An unnatural creature that has taken up residence in the forest.",
"Ways to cause mischief for travelers.",
"Worthy visitors of a secret grove.",
"Amusement in frightening travelers.",
"Someone to listen to a new song.",
"A heart to break.",
"Love and war.",
"Love and mischief.",
"Mischief and mayhem.",
"The answer to a riddle.",
"A dance partner.",
"A drinking partner."    ] },
{  "title": "d12 The faerie carries...",   "roll": [
"An delicate wreath of flowers.",
"A gem glowing with moonlight or starlight.",
"A finely-crafted bow or knife.",
"A vial containing a potent potion.",
"Several magical mushrooms.",
"A variety of herbs commonly used in potion making.",
"A message from a faerie king or queen.",
"A token from a past love.",
"A string instrument (d4): 1. fiddle; 2. harp; 3. lute; 4. lyre.",
"A wind instrument (d4): 1. flute; 2. horn; 3. ocarina; 4. panpipes.",
"A piece of sweet cake.",
"A jug of wine."    ] }    ] },

{   "title": "Goblin Gang",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d10 The goblins’ primary “business” involves...",   "roll": [
"Raiding villages and farms.",
"Burglarizing storehouses and shops.",
"Harassing anyone who passes through their territory.",
"Robbing caravans carrying gems, precious metals, and exotic goods.",
"Holding up traders’ ships or wagons.",
"Smuggling drugs (d4): 1. smokeleaf; 2. a hallucinogenic mushroom; (3) sleepysalt (a downer); 4. sharpsugar (an upper).",
"Smuggling living things (d4): 1. exotic beasts; 2. foreign harlots; 3. fugitives; 4. slaves.",
"Serving as muscle for evildoers.",
"Mining and crafting.",
"Pranks and hijinks."    ] },
{  "title": "d10 The goblin gang’s symbol is...",   "roll": [
"A skull.",
"An arrow.",
"A dagger.",
"The moon.",
"A star.",
"A snake.",
"A spider.",
"A rat.",
"A wolf.",
"A bat."    ] },
{  "title": "d6 The goblins’ lair is located...",   "roll": [
"In a dark and haunted forest.",
"In an enchanted forest.",
"Along a mountain pass.",
"High in the mountains.",
"Beneath a bustling city.",
"Near a quiet farm village."    ] },
{  "title": "d6 The goblins’ lair is...",   "roll": [
"A series of natural caverns.",
"An abandoned mine.",
"A mine in which the goblins are actively digging.",
"An underground fortress.",
"A semi-organized military encampment.",
"A crude encampment."    ] },
{  "title": "d20 The goblins are particularly fond of picking on...",   "roll": [
"Fishermen and sailors.",
"Beggars and drunks.",
"Merchants and moneychangers.",
"Young noblemen.",
"Young noblewomen.",
"Old noblewomen.",
"Gamblers and thieves.",
"Priests and monks.",
"Priestesses.",
"Constables and sheriffs.",
"Castle or town guards.",
"Cooks and scullery maids.",
"Barkeeps and barmaids.",
"Harlots and madames.",
"Circus performers.",
"Foreign travelers and peasant girls.",
"Young children.",
"Miners and prospectors.",
"Elves and rangers.",
"Dwarves and gnomes."    ] },
{  "title": "d10 The goblins’ are currently planning a raid on...",   "roll": [
"The residence of the leader or a senior gang member.",
"An artisan's shop or guildhall.",
"A merchant's office.",
"A tavern or inn.",
"A brothel.",
"A warehouse or shipyard.",
"A temple complex or shrine.",
"The town hall.",
"A shantytown",
"The residence of a wealthy individual or prominent citizen."    ] },
{  "title": "d10 The goblins’ boss is...",   "roll": [
"An egotistical goblin warrior.",
"A charismatic goblin rogue.",
"A mysterious goblin shaman.",
"A talented goblin thief.",
"A well-known goblin war hero.",
"A ruthless goblin hexer.",
"A cunning gobliness.",
"A brutal hobgoblin war priest.",
"A brilliant hobgoblin warlord.",
"A calculating bugbear assassin."    ] },
{  "title": "d6 The goblins’ goals include (boss and rank-and-file members could have different goals)...",   "roll": [
"Disruption of the region’s politics.",
"Disruption of the region’s trade.",
"Revenge against a specific organization.",
"Revenge against a rival goblin gang.",
"Spreading chaos and destruction.",
"Possession of a powerful artifact."    ] },
{  "title": "d12 The goblins typically fight with...",   "roll": [
"Swarm tactics.",
"Hit-and-run tactics.",
"Ambush tactics.",
"Choreographed maneuvers.",
"Unpredictable maneuvers.",
"Lots of smiles and jokes.",
"Lots of fancy footwork.",
"Lots of screaming and shouting.",
"Kicking and stomping.",
"Lots of head-butting.",
"Lots of biting and scratching.",
"Laying traps."    ] },
{  "title": "d6 As enforcers or extra muscle, the goblins sometimes hire...",   "roll": [
"Hobgoblin mercenaries.",
"Bugbear thugs.",
"Ogre savages.",
"Orc berserkers.",
"Trolls.",
"Other goblin gangs."    ] },
{  "title": "d6 As guardians or pets, the goblins sometimes keep...",   "roll": [
"Wolves.",
"Wargs.",
"Giant spiders.",
"Boars.",
"Giant bats.",
"Dire rats."    ] }    ] },

{   "title": "- Individual Goblin",   "use": "Use the tables to roll randomly",   "rolls": [
{  "title": "d12 The goblin is particularly skilled at...",   "roll": [
"Being sneaky.",
"Not being seen.",
"Tracking foes.",
"Building traps.",
"Avoiding traps.",
"Repairing traps.",
"Foraging for food and water.",
"Wrangling beasts.",
"Digging tunnels.",
"Crafting arms and armor.",
"Crushing skulls.",
"Cutting throats."    ] },
{  "title": "d12 The goblin wields...",   "roll": [
"A rusty sword.",
"A finely-made sword",
"A spiked club.",
"A wicked looking axe.",
"A spear decorated with feathers.",
"Several polished daggers.",
"A large, serrated dagger.",
"A pair of curved daggers.",
"A cracked wooden shield.",
"A shield, emblazoned with the gangs’ symbol.",
"Arrows fletched with crow feathers.",
"Arrows fletched with hawk feathers."    ] },
{  "title": "d12 The goblin wears...",   "roll": [
"Armor with greasy stains.",
"Patched leather armor.",
"Piecemeal chain armor.",
"A leather helm.",
"A large skull as a helm.",
"A wolf-face helm.",
"A lanyard of severed ears.",
"A big hoop earring.",
"A shiny silver belt.",
"A wolf skin.",
"A black cloak with a hood.",
"A large belt purse."    ] },
{  "title": "d12 The goblin’s face has...",   "roll": [
"Blue warpaint.",
"An eyepatch.",
"Burn scars.",
"Only one ear.",
"No front teeth.",
"An unusual tattoo on the forehead.",
"Stitches closing a wound on the jaw.",
"A topknot above it.",
"Several muddy smudges.",
"A boil oozing pus.",
"A wisp of a mustache.",
"Amazing sideburns."    ] },
{  "title": "d8 The goblin has...",   "roll": [
"An unsettling stare.",
"A lean and hungry look.",
"A maniacal laugh.",
"A mad cackling laugh.",
"A high-pitched twittering laugh.",
"A tendency to snicker at everything.",
"A nervous twitch.",
"A difficult time standing still."    ] }    ] },

{   "title": "Lizardfolk",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d8 Coloring: The lizardolk's scales are...",   "roll": [
"Mottled green and brown.",
"Dull and green.",
"Shiny and green.",
"Green with black stripes.",
"Black and grey.",
"Brown with black stripes.",
"Mottled black and brown.",
"Brown and grey."    ] },
{  "title": "d8 Mannerism: The lizardfolk has...",   "roll": [
"An unsavory habit of licking its lips.",
"Shifty eyes.",
"A nervous, hissing laugh.",
"Eyes that never blink.",
"A tongue that protrudes when it speaks.",
"A crest atop its head.",
"Two ridges starting above the brow and running down its head and neck.",
"Sagging folds of skin on its throat."    ] },
{  "title": "d10 Profession: The lizardfolk is...",   "roll": [
"A savvy hunter.",
"A deadly tracker.",
"A skilled scout.",
"A savage berserker.",
"A dim-witted brute.",
"A celebrated warrior.",
"A powerful shaman.",
"An eerie mystic.",
"A scaly shapeshifter.",
"A cold-blooded killer."    ] },
{  "title": "d6 Goal: The lizardfolk is looking for...",   "roll": [
"New waters for fishing and hunting.",
"The tracks of an intruder in the region.",
"The lair of a troublesome beast.",
"Safe nesting grounds.",
"Decent arms and armor.",
"Fresh meat."    ] },
{  "title": "d12 Possessions: The lizardfolk carries...",   "roll": [
"A scimitar and a wooden shield.",
"A scimitar and a short bow.",
"A spear and a blowgun.",
"A curved dagger and a blowgun.",
"A curved dagger with feathers on the hilt.",
"A handaxe and a shortbow.",
"An oversized club.",
"A wooden club and a wooden shield.",
"A milky white gem fastened about the neck.",
"A string of trophies fastened about the neck (d4): 1. ears; 2. finger bones; 3. scalps; 4. teeth.",
"A gnarled wooden staff.",
"A string of beads made from a variety of materials (d8): 1. bone; 2. clay; 3. copper; 4. silver; 5. stone; 6. teeth; 7. tin; 8. wood."    ] }    ] },

{   "title": "Lycanthropes",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d12 The beastshifter transforms into...",   "roll": [
"A grizzly bear.",
"A black bear.",
"A wild boar.",
"A oversized black rat.",
"A large brown rat.",
"A lanky grey rat.",
"A fierce tiger.",
"A grey wolf.",
"A mottled brown and grey wolf.",
"A reddish brown wolf.",
"A dark brown or black wolf.",
"A white wolf."    ] },
{  "title": "d6 The beastshifter transforms involuntarily...",   "roll": [
"Whenever it is in moonlight.",
"On nights when a full moon occurs.",
"On nights when the moon is half full or more.",
"Whenever the leader of its pack or clan transforms.",
"Whenever it becomes enraged.",
"Never; it is in complete control of its power."    ] },
{  "title": "d8 While transformed, the beastshifter behaves...",   "roll": [
"Mostly as a normal beast of its type.",
"As an unusually intelligent version of the beast of its type.",
"More like a human than a beast.",
"As a skilled hunter.",
"As a cautious predator.",
"As a savage predator.",
"As a frightened beast.",
"Violently, spreading blood and chaos."    ] },
{  "title": "d8 The beastshifter lives...",   "roll": [
"Alone among humans, hiding its powers.",
"Alone among humans who know and accept its powers.",
"Alone as an outcast from human society.",
"Among other beastshifters integrated into human society.",
"Among other beastshifters as outcasts from human society.",
"Among other beastshifters, hiding their powers from society.",
"Among other beastshifters, apart from human society.",
"Alone as an outcast from its pack or clan."    ] },
{  "title": "d12 The beastshifter makes its home...",   "roll": [
"In a cave.",
"In a swamp.",
"On a vast plain.",
"In a forest.",
"In a cottage in the woods.",
"Hidden in the mountains.",
"In a quiet village.",
"Just outside a quiet village.",
"Down a dark alley in the city.",
"In the city sewers.",
"On a quiet residential street in the city.",
"In or near a castle or palace."    ] },
{  "title": "d8 The beastshifter has a tendency to...",   "roll": [
"Lose its temper easily.",
"Speak in low growls (or squeaks), making it difficult for others to understand when excited.",
"Recoil from touching anything made of silver.",
"Get nervous in moonlight.",
"Lick its lips hungrily all the time.",
"Fidget or pace when in indoor spaces.",
"Daydream about hunting in its beast form.",
"Sniff people upon meeting them."    ] },
{  "title": "d8 In humanoid form, the beastshifter fights with...",   "roll": [
"Hit-and-run tactics.",
"Making a mad charge.",
"Kicking and stomping.",
"Sharp claws.",
"Sharp teeth.",
"Lots of taunts and jeers.",
"Lots of screaming and shouting.",
"Lots of head-butting."    ] },
{  "title": "d12 In humanoid form, the beastshifter presents itself as...",   "roll": [
"A farmer or herder.",
"A miner or fisher.",
"A beggar or urchin.",
"A noble or knight.",
"A barkeep or barmaid.",
"A barbarian or gladiator.",
"An herbalist or healer.",
"A soldier or sell-sword.",
"A hunter or assassin.",
"A thief or bandit.",
"A smuggler or con artist.",
"A sailor or pirate."    ] },
{  "title": "d12 In humanoid form, the beastshifter’s face has...",   "roll": [
"Unsightly nose and ear hair.",
"A garish earring.",
"An empty eye socket.",
"A grisly scar.",
"A grim look.",
"Sad puppy-dog eyes.",
"A nervous grin.",
"An toothy grin.",
"A frame of long, beautiful long hair.",
"Ferocious sideburns.",
"An unruly beard.",
"An intimidating mustache."    ] },
{  "title": "d20 The beastshifter’s favorite prey are...",   "roll": [
"Foreigners and travelers.",
"Beggars and drunks.",
"Young men.",
"Young women.",
"Old women.",
"Old noblewomen.",
"Priests and monks.",
"Priestesses.",
"Harlots and madames.",
"Farmwives and peasant girls.",
"Young children.",
"Rabbits and hares.",
"Squirrels and chipmunks.",
"Pheasants and other gamefowl.",
"Ducks and other waterfowl.",
"Mice and rats.",
"Pigeons and doves.",
"Sheep and goats.",
"Chickens and turkeys.",
"Dogs and cats."    ] }    ] },

{  "title": "- Lycanthrope Packs",   "use": "Use the tables to roll randomly",   "rolls": [
{  "title": "d8 The pack is...",   "roll": [
"A band of exiles and outcasts.",
"A roving band of outlaws and thieves.",
"A nomadic warrior clan.",
"A band of sought-after mercenaries.",
"An integral part of the local thieves’ or assassins’ guild.",
"A mercenary company in the service of a local lord or city watch.",
"A wild bunch of hunters and killers.",
"An ancient clan of warrior-hunters."    ] },
{  "title": "d12 The pack’s leader is...",   "roll": [
"A dangerous megalomaniac.",
"A charismatic demagogue.",
"A mysterious foreigner.",
"A talented thief.",
"An outcast from a prominent family.",
"A ruthless killer.",
"A femme fatale.",
"A former arena champion.",
"A disgraced knight.",
"A brutish thug.",
"A de-frocked priest.",
"A well-known fugitive."    ] },
{  "title": "d6 The pack’s attitude toward their leader is...",   "roll": [
"Friendly and loyal.",
"Respectful and business-like.",
"Cautious and uncertain.",
"Terrified and tight-lipped.",
"Disappointed and disrespectful.",
"Agitated and restless."    ] },
{  "title": "d6 The pack’s goals include...",   "roll": [
"Becoming the region’s dominant predators.",
"Revenge against a rival band of lycanthropes or outlaws.",
"Revenge against the region’s elite.",
"Rebellion against the region’s elite.",
"A quiet and peaceful existence.",
"Violence to slake their bloodlust."    ] }    ] },

{   "title": "- Uncommon Lycanthropes",   "use": "Use the tables to roll randomly",   "rolls": [
{  "title": "d20 The beastshifter transforms into...",   "roll": [
"A badger.",
"A bat.",
"A cat.",
"A crocodile.",
"A dog.",
"A dolphin.",
"A fox.",
"A hyena.",
"A jackal.",
"A jaguar.",
"A leopard.",
"A lion.",
"An owl.",
"A panther.",
"A raven.",
"A seal.",
"A serpent.",
"A shark.",
"A spider.",
"A swine."    ] }    ] },

{   "title": "Orkish Clans",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d12 The orcs are...",   "roll": [
"Nomadic hunters, following game.",
"Raiders displaced from their native lands.",
"In exile from their native lands.",
"In the service of a sovereign warlord.",
"A loose confederacy of tribes and families related by blood.",
"Degenerate survivors from a broken army.",
"Disorganizes; a clan of competing warriors.",
"A tight-knit war band.",
"Bent on sowing chaos and mayhem.",
"Raiders after supplies and slaves.",
"Marching to war under the leadership of a great chief.",
"On an errand for an evil wizard or other powerful being."    ] },
{  "title": "d12 The orcs value...",   "roll": [
"Bravery.",
"Strength.",
"Wisdom.",
"Virility.",
"Honoring the gods.",
"Honoring their ancestors.",
"Battle-scars.",
"Survival.",
"Kill counts.",
"Scalps.",
"Steel.",
"Meat."    ] },
{  "title": "d4 The orcs’ iconography features...",   "roll": [
"Symbols of death and destruction (d10): 1. bats; 2. blood; 3. bones; 4. corpses; 5. crows; 6. flames; 7. ghosts; 8. scorpions; 9. skulls; 10. vultures.",
"Symbols of the heavens (d6): 1. clouds; 2. lightning; 3. moon; 4. snow; 5. stars; 6. sun.",
"Symbols of strength and weaponry (d6): 1. arrows; 2. axes; 3. fists; 4. spears; 5. stones; 6. swords.",
"A great beast (d8): 1. bears; 2. boars; 3. eagles; 4. horses; 5. lions; 6. owls; 7. snakes; 8. wolves."    ] },
{  "title": "d10 The orcs’ chief is...",   "roll": [
"A well-respected chief.",
"A charismatic warlord.",
"A mysterious shaman.",
"A descendent of an honored hero.",
"A ruthless killer.",
"A brutish thug.",
"An impatient young warrior.",
"A wise old chief.",
"A celebrated war hero.",
"A prolific lover."    ] },
{  "title": "d12 The orcs’ favorite meat comes from...",   "roll": [
"Dwarves and halflings.",
"Beggars and thieves.",
"Merchants and caravan guards.",
"Noblemen.",
"Noblewomen.",
"Priests and priestesses.",
"Slaves.",
"Circusfolk and minstrels.",
"Foreign travelers.",
"Peasant women.",
"Young children.",
"Elves and pixies."    ] },
{  "title": "d8 The orcs fear...",   "roll": [
"Men armored in steel.",
"Human women.",
"Spellcasters.",
"Members of a particular race (d4): 1. dwarves; 2. elves; 3. goblinoids; 4. reptilian humanoids.",
"A particular natural phenomenon (d6): 1. blizzards; 2. earthquakes; 3. floods; 4. thunderstorms; 5. volcanoes; 6. typhoons.",
"The gods.",
"Aberrant evils.",
"Dragons."    ] },
{  "title": "d10 The orcs are notorious for...",   "roll": [
"Never leaving survivors.",
"Feeding prisoners to wild beasts.",
"Tattooing or branding prisoners.",
"Scalping enemies.",
"Flaying enemies.",
"Raiding and burning villages.",
"Plundering merchant caravans.",
"Eating prisoners raw.",
"Claiming prisoners as slaves.",
"Taking prisoners as wives, concubines, or catamites."    ] },
{  "title": "d12 The orcs are known for...",   "roll": [
"Screaming and shouting during battle.",
"Convening with ghosts and spirits.",
"Ritual animal sacrifice under the new moon.",
"Ritual humanoid sacrifice deep within the earth.",
"Ritualistic blood-letting.",
"Ritualistic sexual acts under the full moon.",
"Eating unusually-prepared meats.",
"Prolific amounts of drinking.",
"Never cutting their hair.",
"Shaving their heads and bodies.",
"Wearing long top-knots or braids.",
"Bathing and perfuming their bodies."    ] },
{  "title": "d6 The orcs’ attitude is...",   "roll": [
"Rowdy and festive.",
"Joyful and eager to fight.",
"Relaxed and carefree.",
"Frightened and suspicious.",
"Hostile and suspicious.",
"Hostile and eager to fight."    ] },
{  "title": "d6 The orcs’ goals include (chief and lower-ranking members could have different goals)...",   "roll": [
"Upheaval of the region’s politics.",
"Disruption of the region’s trade.",
"Revenge against another civilization.",
"Revenge against a rival orkish clan.",
"Spreading chaos and destruction.",
"Possession of a powerful artifact."    ] },
{  "title": "d8 The orcs typically fight with...",   "roll": [
"Hit-and-run tactics.",
"Ambush tactics.",
"Unpredictable maneuvers.",
"Lots of screaming and shouting.",
"Kicking and stomping.",
"Lots of head-butting.",
"Lots of biting and scratching.",
"Frequent breaks for (d4): 1. eating; 2. looting corpses; 3. re-forming ranks; 4. arguing among themselves."    ] },
{  "title": "d6 As guardians or pets, the orcs sometimes keep...",   "roll": [
"Boars.",
"Dire rats.",
"Giant lizards.",
"Ogres.",
"Wargs.",
"Wolves."    ] },
{  "title": "d10 As slaves, the orcs keep...",   "roll": [
"Dwarves.",
"Gnomes.",
"Goblins.",
"Halflings.",
"Humans.",
"Kobolds.",
"Undead servitors.",
"Nothing; the orcs eat any captives they take.",
"Nothing; the orcs leave no survivors.",
"Nothing; the orcs believe in freedom for all beings."    ] },
{  "title": "d12 Most of the orcs are wielding...",   "roll": [
"Spears and large hunting knives.",
"Spears and javelins.",
"Exotic, curved blades and several bolas.",
"Huge, curved blades.",
"Exotic, curved blades and blowguns.",
"Pikes and shortswords.",
"Pikes and short bows.",
"Battleaxes and throwing axes.",
"Battleaxes and longbows.",
"Longswords and longbows.",
"Jagged greatswords and shortbows.",
"Greataxes and javelins."    ] }    ] },

{  "title": "- Individual Orcs",   "use": "Use the tables to roll randomly",   "rolls": [
{  "title": "d8 Appearance: The orc has...",   "roll": [
"Pale green skin.",
"Yellowish green skin.",
"Dirty brown skin.",
"Reddish brown skin.",
"Grey skin.",
"A tall frame.",
"A thick-set frame.",
"Bug eyes."    ] },
{  "title": "d6 Tattoo: The orc has...",   "roll": [
"A bone tattoo.",
"A dragon tattoo.",
"A skull tattoo.",
"A spear tattoo.",
"A spiderweb tattoo.",
"A tattoo of thorns."    ] },
{  "title": "d8 Role: The orc is...",   "roll": [
"A ferocious berserker.",
"A rage-filled killer.",
"A persistent hunter.",
"A fearless scout.",
"A masterful strategist.",
"A mighty leader.",
"A grim mystic (d4): 1. bone shaman; 2. blood shaman; 3. earth shaman; 4. moon shaman.",
"An eager warrior."    ] },
{  "title": "d8 Skill: Even among orcs, the orc is particularly good at...",   "roll": [
"Tracking creatures by scent.",
"Identifying and following the tracks of creatures.",
"Running down prey.",
"Decapitating foes.",
"Impaling foes.",
"Roping captives.",
"Breaking slaves.",
"Handling savage beasts."    ] },
{  "title": "d8 Armor: The orc is armored in...",   "roll": [
"Nothing.",
"Tattered leather.",
"Blood-stained leather.",
"Boiled leather.",
"The hides of scaly beasts.",
"The hides of furry beasts.",
"The hides of exotic beasts.",
"A helm and breastplate taken from a fallen enemy."    ] },
{  "title": "d8 Weapon: The orc is wielding...",   "roll": [
"A spear.",
"A scimitar.",
"A falchion..",
"A pike.",
"A battleaxe.",
"A greatsword.",
"A greataxe.",
"A longbow."    ] },
{  "title": "d6 Motivation: The orc is looking for...",   "roll": [
"A good meal, fresh if possible.",
"A hearty meal, spoiled is not a problem.",
"A throat to cut or a head to bash.",
"A chance to prove itself in combat.",
"A place to rest and to sharpen weapons.",
"A strong drink."    ] }    ] },

{  "title": "Snake Cultists",  "use": "These are tables for generating an interesting snake cultists to serve as foe or foil to your PCs, from slithering assassins to mad, venom-spitting zealots.",   "rolls": [
{  "title": "d10 Profession: The cultist is...",   "roll": [
"A cunning warrior.",
"A battle-tested soldier.",
"A stealthy assassin.",
"A fanatical priest or priestess.",
"A newly initiated acolyte.",
"A charismatic preacher.",
"A foolish zealot.",
"A raving madman or madwoman.",
"A scaly shapeshifter.",
"An enthusiastic poisonmaker.",    ] },
{  "title": "d12 Scaly Obsession: The cultist is particularly fond of or fearful of...",   "roll": [
"Cobras and asps.",
"Rattlers and sidewinders.",
"Pythons and boas.",
"Sea snakes.",
"Black dragons.",
"Green dragons.",
"Female medusas.",
"Male medusas.",
"Giant snakes.",
"Yuan-ti malisons.",
"Yuan-ti abominations.",
"Yuan-ti halfbloods.",    ] },
{  "title": "d10 Distinguishing Feature: The cultist has...",   "roll": [
"A bandaged thumb.",
"A tattoo on the face.",
"A tear at the knee of his or her robe.",
"A forked tongue.",
"A nervous twitch.",
"Almost no nose.",
"An unsettling laugh.",
"A large scar on the throat.",
"A profuse amount of sweat soaking through his or her robes.",
"A hissing lisp when he or she speaks.",    ] },
{  "title": "d6 Goal: The cultist is looking to...",   "roll": [
"Recruit new members to the cult.",
"Warn outsiders away from the cult.",
"Collect captives for human sacrifice.",
"Lead travelers into a trap near the cult's shrine or temple.",
"Escape from the clutches of the cult's leadership.",
"Slip some poison into someone’s drink.",    ] },
{  "title": "d8 Possessions: The cultist carries or wears...",   "roll": [
"Several eggs stolen from a snake’s nest.",
"A necklace or bracelet of snake fangs.",
"Snakeskin armor or boots.",
"A book of prayers and curses.",
"A sharp, ceremonial dagger.",
"A scimitar and a set of lightweight, supple armor.",
"A constrictor snake fashioned like a scarf about the shoulders.",
"Several doses of a deadly poison.",    ] },    ], },

{   "title": "Treefolk",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d8 The treeperson is...",   "roll": [
"A dryad enchantress.",
"A dryad protector.",
"A dryad witch.",
"A dryad oracle.",
"A treant loreseeker.",
"A treant guardian.",
"A treant lorekeeper.",
"A treant elder."    ] },
{  "title": "d12 Appearance: The treeperson could be described as...",   "roll": [
"Tall.",
"Very tall.",
"Slender.",
"Sturdy.",
"Unwavering.",
"Bent.",
"Gnarled.",
"Knotty.",
"Weathered.",
"Moss-covered.",
"Withered.",
"Stumpy."    ] },
{  "title": "d20 Features: The treeperson's bark and leaves are reminiscent of...",   "roll": [
"An apple or pear tree.",
"An ash.",
"A birch.",
"A beech.",
"A cedar or juniper.",
"A cherry or plum tree.",
"A chestnut or hazel tree.",
"A cypress.",
"An elm.",
"An fir.",
"A hawthorn or hemlock.",
"A hickory or walnut tree.",
"A linden or lime tree.",
"A maple.",
"An oak.",
"A pine.",
"A poplar.",
"A spruce.",
"A willow.",
"A yew or holly tree."    ] },
{  "title": "d10 Personality: The treeperson is...",   "roll": [
"Sappy.",
"Soft-spoken.",
"Rooted.",
"Dry.",
"Patient.",
"Green.",
"Flowery.",
"Steady.",
"Prickly.",
"Thorny."    ] },
{  "title": "d8 The treeperson is looking to...",   "roll": [
"Drive away intruders.",
"Warn intruders of dangers ahead.",
"Find a spot where a rare flower grows.",
"Nurture an ancient grove back to health.",
"Protect the oldest tree in the forest.",
"Eliminate any threats to the forest.",
"Plant trees where others been felled.",
"Talk after centuries of silence."    ] },
{  "title": "d6 The treeperson carries...",   "roll": [
"A magic acorn, nut, or other seed.",
"A clipping of ancient wood.",
"A rare moss with healing properties.",
"A deathly poison mushroom.",
"A sapling from an ancient tree.",
"A cudgel made from the wood of a legendary tree."    ] }    ] },

{   "title": "Restless Undead",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d20 The person was...",   "roll": [
"A farmer or herder.",
"A miner or fisher.",
"A slave or servant.",
"A laborer or unskilled worker.",
"A beggar or urchin.",
"A noble or knight.",
"An artist or craftsman.",
"A merchant or shopkeeper.",
"A barkeep or barmaid.",
"A barbarian or gladiator.",
"A minstrel or singer.",
"A priest or monk.",
"An herbalist or healer.",
"A soldier or sell-sword.",
"A cultist or preacher",
"A hunter or assassin.",
"A thief or bandit.",
"A smuggler or con artist.",
"A sailor or pirate.",
"An alchemist or seer."    ] },
{  "title": "d20 The person died from...",   "roll": [
"Hanging or strangulation.",
"Beheading.",
"A stab wound or beating.",
"Blunt trauma or being crushed.",
"Drowning.",
"A plague.",
"A gastrointestinal illness.",
"A respiratory illness.",
"An infected wound.",
"Poisoning.",
"Falling from a great height.",
"A horse or wagon accident.",
"A venereal disease.",
"An allergic reaction.",
"Shock.",
"A heart attack or stroke.",
"Liver failure.",
"Old age.",
"Natural causes.",
"Unknown causes or under mysterious circumstances."    ] },
{  "title": "d12 The person's spirit lingers...",   "roll": [
"To seek vengeance.",
"To pine for lost love.",
"To bemoan lost treasure.",
"Out of pure hatred of the living.",
"Out of jealousy of the living.",
"To covet the belongings of a specific individual.",
"To provide protection to a specific someone.",
"To warn a specific someone against danger.",
"To warn everyone against a specific danger.",
"To torment a specific someone.",
"To torment members of a specific group.",
"To torment anyone who crosses its path."    ] },
{  "title": "d12 The person's spirit can move on if...",   "roll": [
"Someone helps it achieve it's goal.",
"It saves the life of at least one other person.",
"It achieves its goal on its own.",
"It is destroyed.",
"It is driven from its current location.",
"It is given evidence of events that happened after the person's death.",
"It is made aware of the circumstances of the person's death.",
"It is forced to visit the location of the person's death.",
"It is given the opportunity to speak to a loved one.",
"It sufficiently satisfies its lust for blood.",
"It sufficiently satisfies its lust for human touch.",
"The Hells freeze over."    ] },
{  "title": "d6 The spirit’s initial reaction when it encounters living creatures is...",   "roll": [
"Hostile and aggressive.",
"Hostile and suspicious.",
"Nervous and frightened.",
"Mostly indifferent.",
"Completely indifferent.",
"Curious but suspicious.",
"Curious and playful.",
"Desperate and aggressive."    ] }    ] },

{   "title": "- Corporeal Undead",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d10 The person's spirit is...",   "roll": [
"Occupying its original body, showing no signs of decay.",
"Occupying its original body, showing some signs of decay.",
"Occupying its original body, badly decomposed.",
"Occupying its original body, only bare bones remain.",
"Occupying the corpse of someone else.",
"Occupying the living body of a stranger.",
"Occupying the living body of someone the person new.",
"Occupying the living body of a beast.",
"Occupying part of its original body (skull or hand).",
"Occupying part of someone else’s corpse (skull or hand)."    ] },
{  "title": "d6 The creature moves...",   "roll": [
"With a shambling gait.",
"With an awkward limp.",
"Lurching unpredictably.",
"With more of shimmy than a walk.",
"Taking slow, steady steps.",
"With surprising quickness and agility."    ] },
{  "title": "d12 The creature has...",   "roll": [
"A tattered shirt.",
"A missing arm, leg, or finger.",
"Only one eye.",
"A club foot.",
"Long-scraggly hair.",
"Chattering teeth.",
"Large crude stitches in its side.",
"An awful hunchback.",
"Incredibly long fingernails.",
"Drool on its chin.",
"Buck teeth.",
"A creepy mustache."    ] }    ] },

{   "title": "- Incorporeal Undead",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d10 The spirit is...",   "roll": [
"Incorporeal, invisible, and incapable of affecting its material surroundings.",
"Incorporeal, invisible, and capable of moving small objects.",
"Incorporeal, invisible, but capable of making itself seen.",
"Incorporeal, invisible, and hidden within an inanimate object (d4): 1. chest; 2. drawer; 3. kettle; 4. wardrobe.",
"Incorporeal, visible, but incapable of affecting it's material surroundings.",
"Incorporeal, visible, and capable of significant mischief and harm.",
"Incorporeal, extraordinarily beautiful, and capable of mischief and harm.",
"Incorporeal, wretched and slimy, and capable of mischief and harm.",
"Incorporeal, glowing blue or green, and capable of mischief and harm.",
"Incorporeal, visible, but in an unrecognizable form (d6): 1. mist or fog; 2. animal shape; 3. floating skull; 4. faint glow; 5. pool of shadows; 6. spectral hand."    ] },
{  "title": "d6 The spirit moves...",   "roll": [
"By creeping, oozelike, across the ground.",
"Smoothly, gliding above the grond.",
"Taking slow, fluid steps.",
"Lightly, rarely touching the ground.",
"Much quicker than you expect it to.",
"By teleporting in a swirl of shadows."    ] },
{  "title": "d10 The spirit appears to be...",   "roll": [
"Severely bloated.",
"Moaning in anguish.",
"Snarling at you.",
"Breathing heavily.",
"Cowering in fear.",
"Poised to strike.",
"Gently bobbing up and down.",
"Wind-blown and haggard.",
"Fidgeting nervously.",
"Oozing ectoplasm."    ] }    ] },

{   "title": "Vampires",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d12 In life, the vampire was...",   "roll": [
"An alchemist or pyromancer.",
"An assassin or poisonmaker.",
"A barkeep or barmaid.",
"A con artist or gambler.",
"A harlot or madame.",
"A hunter or woodsman.",
"A knight or sell-sword.",
"A lord or lady.",
"A priest or monk.",
"A sailor or pirate.",
"A seer or mystic.",
"A thief or smuggler."    ] },
{  "title": "d12 Often, the vampire poses as...",   "roll": [
"A powerful noble.",
"An eccentric scholar.",
"A mysterious foreigner.",
"A talented artist.",
"A polite shopkeeper.",
"A creepy peddler.",
"A femme fatale.",
"A charming rogue.",
"A friendly barkeep or barmaid.",
"A charismatic entertainer.",
"A religious fanatic.",
"A veteran soldier."    ] },
{  "title": "d12 In addition to draining blood, the vampire is fond of...",   "roll": [
"Shooting prey with an arrow or bolt from range.",
"Impaling prey.",
"Gutting or eviscerating prey.",
"Flaying prey.",
"Beheading prey.",
"Strangling prey.",
"Hanging prey.",
"Burying prey alive.",
"Drowning prey.",
"Throwing prey off a roof.",
"Severely beating prey.",
"Dismembering prey."    ] },
{  "title": "d8 The vampire’s goals include...",   "roll": [
"Procreating.",
"Corrupting and influencing the politics of the city or region.",
"Domination of the city or region’s politics.",
"Revenge against a rival vampire.",
"Revenge against a living person, family, or organization.",
"Seeking hedonistic pleasure.",
"Uncovering ancient secrets of death and undeath.",
"Enslaving the living to create an easy source of food for vampires."    ] },
{  "title": "d10 The vampire’s base of operations is...",   "roll": [
"A beautiful manor house.",
"A run-down castle.",
"An ancient fortress.",
"A quaint house on a quiet street.",
"A tavern.",
"A brothel.",
"An unpleasant underground lair.",
"A crypt in a graveyard.",
"A crypt beneath a temple.",
"The vampire is a transient."    ] },
{  "title": "d6 The vampire prefers to hunt...",   "roll": [
"Just before sunrise.",
"Just after sunset.",
"In the early evening.",
"Well into the night.",
"The toll of midnight.",
"After midnight."    ] },
{  "title": "d20 The vampire’s favorite prey are...",   "roll": [
"Fishermen and sailors.",
"Beggars and thieves.",
"Merchants and moneychangers.",
"Young noblemen.",
"Young noblewomen.",
"Old noblewomen.",
"Gamblers and drunks.",
"Priests and monks.",
"Priestesses.",
"Serving girls.",
"Slaves.",
"Barmaids.",
"Harlots and madames.",
"Circus performers.",
"Foreign travelers.",
"Farmwives.",
"Peasant girls.",
"Inquisitive children.",
"Young children.",
"Elves and the fey."    ] },
{  "title": "d12 The vampire refuses to feed on...",   "roll": [
"Ugly women.",
"Beautiful women.",
"Pregnant women.",
"Shy children.",
"Bold children.",
"Anyone with blue eyes.",
"Anyone with green eyes.",
"Anyone with blonde hair.",
"Anyone with red hair.",
"Anyone who is blind, deaf, or lame.",
"Big burly men.",
"Dwarves and underground dwellers."    ] },
{  "title": "d6 The vampire can shapeshift to take the form of...",   "roll": [
"A tiny bat.",
"A swarm of bats.",
"A cloud of mist.",
"A swirl of shadows.",
"A wolf.",
"A giant bat."    ] },
{  "title": "d8 Even among vampires, the vampire is quite good at...",   "roll": [
"Charming humanoids.",
"Frightening humanoids.",
"Draining blood quickly.",
"Sniffing out living creatures.",
"Traveling overland quickly.",
"Disguising its true nature.",
"Negotiations.",
"Climbing."    ] },
{  "title": "d6 The vampire’s gravedirt is from...",   "roll": [
"A faraway land.",
"A local cemetery or temple.",
"A country village or manor.",
"A well-known castle or fortress.",
"A battlefield.",
"A remote forest or mountain."    ] },
{  "title": "d10 The vampire’s associates include...",   "roll": [
"Less powerful vampires.",
"Skeletons, zombies, and other undead thralls.",
"Living thralls on which to feed.",
"Living thralls who provide pleasurable diversions.",
"Hundreds of bats.",
"Rats and maggots.",
"A pack of vicious wolves.",
"Members of a death cult.",
"The local nobility.",
"The local band of outlaws or assassins’ guild."    ] },
{  "title": "d12 Even among vampires, the vampire is especially...",   "roll": [
"Agile.",
"Attractive.",
"Charming.",
"Cruel.",
"Domineering.",
"Intimidating.",
"Quick.",
"Sadistic.",
"Sleazy.",
"Smooth.",
"Sneaky.",
"Witty."    ] },
{  "title": "d10 The vampire often wears...",   "roll": [
"Shiny leather boots.",
"A black cape with a hood.",
"A black cape with a high collar.",
"A wide-brimmed hat.",
"A cap pulled low.",
"A low-cut shirt.",
"Tight-fitting clothes.",
"A family signet ring.",
"An unusual brooch or necklace.",
"A waxy mustache."    ] },
{  "title": "d12 The vampire is unusually fond of or particular regarding...",   "roll": [
"Horticulture and floral arrangements.",
"Fashion trends.",
"Arms and armor maintenance.",
"Small animals.",
"Horses.",
"High quality fabrics and leathers.",
"Foreign music.",
"Theater troupes and dancers.",
"Social status.",
"Personal hygiene.",
"Hair styles.",
"Dental hygiene."    ] },
{  "title": "d8 The vampire is particularly afraid of or takes special care to avoid...",   "roll": [
"Hallowed places.",
"Densely populated areas.",
"Sunlight.",
"Running water.",
"Sharp wooden objects.",
"Garlic.",
"Silver objects.",
"Relics of the gods."    ] }    ] },


{  "title": "Witches",  "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d20 The witch is...",   "roll": [
"A femme fatale.",
"The wife of a farmer, fisherman, or miner.",
"The wife of a soldier.",
"An old seamstress or weaver.",
"A peasant girl.",
"A noble woman.",
"A slave or servant.",
"An attractive shopkeeper.",
"A stern barmaid.",
"An old fortune teller.",
"A talented dancer or singer.",
"A heretical priestess.",
"An herbalist or healer.",
"A skilled hunter.",
"A very young girl",
"The daughter of a thief.",
"The daughter of a sailor.",
"An old crone.",
"An old widow.",
"An attractive young widow."    ] },
{  "title": "d10 The witch learned her craft from...",   "roll": [
"A fellow witch who kidnapped her as a young girl.",
"A fellow witch who aided her in a time of need.",
"A neighbor.",
"Her mother.",
"Her older sister.",
"Her grandmother.",
"Books of forbidden lore.",
"Communication with the spirits of the dead.",
"Consorting with a fiend.",
"Participating in bacchanalian fey orgies."    ] },
{  "title": "d12 The witch specializes in...",   "roll": [
"Charms.",
"Clairvoyance.",
"Communing with the dead.",
"Conjuring evil spirits.",
"Curses.",
"Demonology.",
"Enchantments.",
"Herbalism.",
"Hexes.",
"Poisons.",
"Potions.",
"Prophecies."    ] },
{  "title": "d10 Trade: For coin or barter, the witch will...",   "roll": [
"Read your palm.",
"Gaze into her crystal ball.",
"Contact a dead relative or friend.",
"Place a hex on an enemy.",
"Give you a piece of forbidden magical lore.",
"Enchant an item.",
"Curse an item.",
"Prepare an herbal remedy.",
"Prepare a potion.",
"Give you an old family recipe."    ] },
{  "title": "d12 The witch is seeking...",   "roll": [
"The means to summon a fiend.",
"The means to control a fiend.",
"Eternal youth and beauty.",
"The soul of a specific person.",
"Vengeance against a powerful person.",
"A long lost recipe.",
"Instructions for a powerful ritual.",
"The wand of a legendary witch or wizard.",
"The staff of an ancient witch or wizard.",
"The meaning of a cryptic prophecy.",
"A baby or young child to steal.",
"A baby or young child to eat."    ] },
{  "title": "d8 The witch has uncovered dark secrets. She cannot be killed by...",   "roll": [
"Hanging or strangulation.",
"Drowning.",
"Burning.",
"Disease.",
"Poisoning.",
"The hand of a mortal man.",
"Falling from a great height.",
"Old age."    ] },
{  "title": "d6 The witch prefers to travel by...",   "roll": [
"Flying broomstick.",
"Flying mount (giant owl or hippogriff).",
"Horseback.",
"Walking.",
"Transforming into a beast (d8): 1. bat; 2. cat; 3. fox; 4. horse; 5. owl; 6. rat; 7. raven; 8. wolf.",
"Teleportation."    ] },
{  "title": "d10 The witch’s home is...",   "roll": [
"In a cave.",
"In a swamp.",
"On an island.",
"Beneath a large tree in a forest.",
"In a cottage in the woods.",
"Hidden in the mountains.",
"In a quiet village.",
"Just outside a quiet village.",
"Down a dark alley in the city.",
"In the castle or palace of a lord."    ] },
{  "title": "d12 Distinguishing Feature: The witch has...",   "roll": [
"A large wart on her nose.",
"An oversized, crooked nose.",
"A cute little button nose.",
"A beauty mark on her cheek.",
"A hairy mole on her cheek.",
"A jagged scar on her cheek.",
"An obnoxious cackling laugh.",
"A hideous belting laugh.",
"A nervous twittering laugh.",
"Long straggly hair.",
"Long beautiful hair.",
"Her hair pulled up."    ] },
{  "title": "d10 The witch's brew is percolating in...",   "roll": [
"A delicate ceramic tea kettle.",
"A large cast iron cauldron.",
"A heavy-bottomed iron pot.",
"A thick cast iron vat.",
"A copper tea kettle.",
"A thick copper vat.",
"A heavy steel cook-pot.",
"A blackened steel cauldron.",
"A thick bronze cauldron.",
"A large bronze cook-pot."    ] },
{  "title": "d20 The witch's brew in the cauldron contains...",   "roll": [
"Eye of newt.",
"Toe of frog.",
"Wool of bat.",
"Tongue of dog.",
"Adder's fork.",
"Blind-worm's sting.",
"Lizard's leg.",
"Howlet's wing.",
"Monkey's paw.",
"Pint of blood.",
"Pound of flesh.",
"Cup of mud.",
"Beak of duck.",
"Housecat's tail.",
"Glob of mold.",
"Rusty nail.",
"Garlic bulb.",
"Cob of corn.",
"Stirge's foot.",
"Dryad's thorn."    ] },
{  "title": "d8 The witch is currently brewing...",   "roll": [
"A love potion.",
"A fertility tonic.",
"A magical cure-all.",
"A terrible poison.",
"A component for a summoning ritual.",
"A component for a necromantic ritual.",
"A component for a polymorphing hex.",
"A component for a beguiling charm."    ] }    ] },

{  "title": "- Familiar",  "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d12 The witch’s familiar is...",   "roll": [
"An elemental spirit (d8): 1. air; 2. earth; 3. fire; 4. ice; 5. mud; 6. storm; 7. stone; 8. water.",
"A fey spirit (d4): 1. animated toadstool; 2. pixie; 3. sprite; 4. talking songbird.",
"A fiendish spirit (d4): 1. demon trapped in a book; 2. devil trapped in a gem; 3. imp; 4. quasit.",
"An undead creature (d4): 1. crawling crawl; 2. disembodied voice; 3. floating skull; 4. formless ghost.",
"A bat.",
"A cat.",
"An owl.",
"A snake.",
"A spider.",
"A raven.",
"A rat.",
"A toad."    ] },
{  "title": "d12 The witch’s familiar’s manner is...",   "roll": [
"Calculating.",
"Clever.",
"Coy.",
"Cruel.",
"Gleeful.",
"Grumpy.",
"Insolent.",
"Shy.",
"Skittish.",
"Surly.",
"Suspicious.",
"Talkative."    ] }    ] },


];
