// objects.js
//

top.objects = [

{   "title": "Random Books",   "use": "These are tables for adding some flavorful books to any library, study, or treasure hoard... I've expanded each in-line sub-table to d6, so once I get a cheat sheet made, I can throw a d20 and d6 together to generate a topic for a book in a single toss.",   "rolls": [
{  "title": "d20 The book's subject is...",   "roll": [
"Alchemy and potions (d6): 1. healing tonics; 2. metallurgy; 3. pyromancy; 4. poisoncraft; 5. potionmaking; 6. recipes.",
"Art and architecture (d6): 1. fortresses and palaces; 2. painting; 3. sketching; 4. sculpture; 5. stonemasonry; 6. temples and tombs.",
"Astronomy and astrology (d6): 1. comets; 2. constellations; 3. moon; 4. sun; 5. stars; 6. strange phenomena.",
"Beast lore (d6): 1. domestic beasts; 2. habits; 3. handling; 4. husbandry; 5. poisonous beasts; 6. regional bestiary.",
"Demonology (d6): 1. conjurings; 2. exorcisms; 3. fiendish bargains; 4. fiendish bestiary; 5. fiendish realms; 6. fiendish symbols.",
"Divination (d6): 1. anthropomancy; 2. crystal gazing; 3. oneiromancy; 4. palm reading; 5. tarot cards; 6. tea leaves.",
"Healing arts (d6): 1. alchemical remedies; 2. anatomy; 3. herbal remedies; 4. prayers; 5. rituals; 6. surgery.",
"Herb lore (d6): 1. healing herbs; 2. mushrooms; 3. poisons; 4. roots; 5. trees; 6. wildflowers.",
"History (d6): 1. ancient; 2. cultural; 3. economic; 4. military; 5. political; 6. regional.",
"Languages (d6): 1. ancient; 2. forbidden; 3. exotic; 4. grammar and punctuation; 5. translations; 6. traveler's phrases.",
"Literary fiction (d6): 1. adventure; 2. fairy tales, 3. folk tales, 4. murder mystery; 5. romance; 6. satire.",
"Mining and mineralogy (d6): 1. gems; 2. metals; 3. mining sties; 4. strategy; 5. rocks; 6. smithing.",
"Music and songs (d6): 1. heroic ballads; 2. love ballads; 3. bawdy tunes; 4. dirges and laments; 5. hymns; 6. musical theory.",
"Necromancy (d6): 1. animation; 2. corpses; 3. lichdom; 4. spirits and souls; 5. undead bestiary; 6. vampirism.",
"Plays (d6): 1. comedy; 2. drama; 3. history; 4. romance; 5. satire; 6. tragedy.",
"Poetry and music (d6): 1. ballads; 2. bawdy songs; 3. epic poetry; 4. hymns; 5. love poetry; 6. lyric poetry.",
"Prophecies and omens (d6): 1. apocalypse; 2. astronomical events; 3. birds; 4. dreams; 5. visions; 6. weather.",
"Theology (d6): 1. afterlife; 2. rituals and practices; 3. saints and martyrs; 5. sacred symbols; 6. sacred texts.",
"True magic (d6): 1. elementalism; 2. enchantment; 3. illusions; 4. summoning; 5. teleportation and travel; 6. warding.",
"Travel and trade (d6): 1. ancient ruins; 2. exotic travelogue; 3. economics and taxation; 4. foreign cultures; 5. regional landmarks and terrain; 6. trade routes."    ] },
{  "title": "d10 The book's condition is...",   "roll": [
"Worn and tattered.",
"Poor. An ink stain obscures a fair amount of the pages.",
"Accidentally damaged. Various water damage around the edges but readable.",
"Vandalized. It appears that a good dozen pages have been ripped out.",
"Deliberately damaged. Towards the middle there is a section hollowed out. In this hiding place, you find (d6): 1. a locket; 2. a knife; 3. a small hammer; 4. a small scroll; 5. a vial of mysterious liquid; 6. a ring.",
"Badly damaged. A lot of the ink has run through water damage and it is nearly illegible.",
"Ancient. The pages crumble as they turn.",
"Strange. The pages are blank?",
"Good, but used. There are handwritten notes in the margins of the pages.",
"Pristine. You can smell the ink drying."    ] },
{  "title": "d12 The book's cover is...",   "roll": [
"Missing. The pages are bound with string woven through holes near the spine.",
"Stained leather. Some sign of wear.",
"Wooden. The title is carved into the spine.",
"Paperback.",
"Animal hide. The fur is still on.",
"Stone. Iron rings hold it together.",
"Cast Iron. Hinges keep it bound.",
"Leather with gemstones embedded in it.",
"Leather with the title branded on it.",
"Leather with gilding on the spine.",
"Torn off. It's kept together by a leather belt.",
"Tree Bark. Dried vine binds it."    ] },
{  "title": "d10 The book is...",   "roll": [
"A standalone volume, the author's only published work.",
"A standalone volume, the author's only surviving work.",
"A standalone volume, written by a prolific but obscure author.",
"A standalone volume, written by a well-known author.",
"The sequel to a book by the same author.",
"A part of a series with 3-9 books.",
"A single volume of a larger work with 4-15 volumes.",
"An edition of a regularly published book with multiple authors.",
"A collection of works by the same author.",
"An anthology of works by several authors."    ] }    ] },

{   "title": "Random Coins",   "use": "Use these tables to quickly generate interesting coins from pickpocket attempts or treasure hordes. Make those 200 GP interesting in their own right. ",   "rolls": [
{  "title": "D10 Material",   "roll": [
"Gold",
"Silver",
"Copper",
"Brass",
"Obsidian",
"Wood",
"Ivory",
"Ceramic",
"Bone",
"Carved clam/oyster shells"    ] },
{  "title": "D10 Size and Shape",   "roll": [
"Thin coins 1 inch across",
"Fat Coins almost 2 inches across",
"Tiny Coins less than 1/2 inch across",
"Square Coins that don't fit a common measure",
"Rectangular chits 2 inches long",
"Fat Coins about 1 inch across",
"Eight sided coins 1 inch across",
"Round coins with a 1/2 inch hole in the center",
"Crescent shaped coins with dull points",
"Tiny coins with irregular edges"    ] },
{  "title": "D10 Markings",   "roll": [
"A face",
"A flag",
"A geometric pattern",
"A slogan",
"A numerical value",
"A line for splitting",
"A crown",
"A city",
"A ship",
"A crest"    ] },
{  "title": "D10 The coins value is defined as...",   "roll": [
"It's weight of metal",
"A barrel of water",
"One mile of tolls on the king's road",
"One deer hide",
"It's weight in gold",
"Two of a smaller coin",
"A day's wages for a soldier",
"A bushel of wheat",
"An hour of air in an underwater kingdom",
"A yard of common cloth"    ] },
{  "title": "D10 Age",   "roll": [
"Newly minted",
"Current",
"Current, but out of circulation",
"Old",
"Old and corroded",
"Ancient",
"Ancient, and concreted together with other coins",
"Current, but from another plane",
"Old, and from a distant land",
"Ancient, and from a long forgotten empire"    ] },
{  "title": "D10 The coin is valuable for other reasons because...",   "roll": [
"it is highly valued by collectors.",
"it was only minted during a short time frame.",
"it depicts a famous symbol.",
"it isn't.",
"it is from the reign of the last king.",
"it was minted by a long dead people.",
"it is common in the realm.",
"it is the only remaining trace of a lost empire.",
"it was minted in a distant land.",
"it is made from a material rare in this area."    ] },
{  "title": "D10 A mixed hoard of coins contains...",   "roll": [
"Identical copies of the same coin, all minted in the same place.",
"Coins of various sizes, made of the same metal, and with similar markings, likely minted in the same place.",
"Coins of various shapes, made of different metals, and with similar markings, likely minted in the same place.",
"Mostly identical copies of the same coin with a handful of others mixed in.",
"Mostly coins with similar markings, with a few foreign coins mixed in.",
"A mixed bag of coins from all over the world.",
"A box of rare coins from far away along with many common coins of the realm.",
"A set of chits with a value in coins redeemable on their face mixed among the coins.",
"A pile of coins corroded over time into one large mass.",
"A charred bag of soot stained coins."    ] }    ] },

{   "title": "Fisherfolk",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d10 The fisherman fishes in...",   "roll": [
"A quiet creek.",
"A wide river.",
"A small pond.",
"A large lake.",
"A swamp.",
"A marsh.",
"A protected bay.",
"A natural harbor.",
"A narrow channel.",
"The open ocean."    ] },
{  "title": "d6 The fisherman typically fishes from...",   "roll": [
"A sandy or rocky beach.",
"An embankment, sandbar, or levee.",
"A pier or bridge.",
"His/her own boat.",
"A boat owned by someone else.",
"Wherever the fish can be reached."    ] },
{  "title": "d8 The fisherman uses...",   "roll": [
"A rod and reel with a baited hook.",
"A rod and reel with a lure.",
"Baited lines.",
"Baited traps.",
"Nets.",
"Baited lines and nets.",
"Baited lines and baited traps.",
"An unusual technique (d4): 1. harpoon; 2. spear; 3. bare hands; 4. trained beast."    ] },
{  "title": "d6 The fisherman prefers to fish...",   "roll": [
"Alone, in silence.",
"Alone, while whistling or humming.",
"Alone, but within earshot of other fishermen.",
"With a trusted partner.",
"With an apprentice fisherman.",
"With an experienced fisherman."    ] },
{  "title": "d8 The fisherman is seeking...",   "roll": [
"A new apprentice.",
"The answer to a riddle.",
"To tell the tale of the one that got away.",
"Rumors of new locations to fish.",
"Revenge against a rival.",
"Assistance repairing a boat, net, or some other fishing gear.",
"Fishing companions.",
"Drinking companions."    ] },
{  "title": "d8 Tattoo: The fisherman has...",   "roll": [
"An anchor tattoo.",
"A pair of crossed bones tattoo.",
"A fish tattoo.",
"An octopus tattoo.",
"A whale tattoo.",
"A lobster tattoo.",
"A mermaid tattoo.",
"A dragon tattoo."    ] },
{  "title": "d10 Distinguishing feature: The fisherman has...",   "roll": [
"A wooden pipe.",
"Rotten teeth.",
"A gold tooth.",
"A terrible scar on the forearm.",
"A handkerchief tied atop the head.",
"Wild eyes.",
"A trimmed black beard.",
"A long, hooked nose.",
"An open shirt and a very hairy chest.",
"Long mutton chop sideburns."    ] }    ] },

{   "title": "- Fishing Boat",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d6 The boat is...",   "roll": [
"A flat raft.",
"A pontoon raft.",
"A canoe.",
"A coracle.",
"A drifter.",
"A buss."    ] },
{  "title": "d4 The boat can...",   "roll": [
"Easily be operated by one person.",
"Be operated by one person, but some flaw or damage has made handling difficult.",
"Be operated by two people, but it can be handled by one with difficulty.",
"Be operated by three or more people, but it can be handled by two with difficulty."    ] },
{  "title": "d6 Presently, the boat is...",   "roll": [
"Laden with the latest catch.",
"Well-stocked with bait and gear and ready to go.",
"In tip-top shape.",
"In need of repair.",
"Barely staying afloat.",
"Resting beneath the waves."    ] },
{  "title": "d10 The boat’s hull markings feature...",   "roll": [
"A ghost.",
"A mermaid.",
"A shark.",
"A pelican.",
"A whale.",
"An octopus.",
"A swordfish.",
"A crab.",
"A sea turtle.",
"A big tuna."    ] }    ] },

{   "title": "- Cold Ocean Fishing",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d10 Near-shore catch: You haul in...",   "roll": [
"A clam.",
"A crab.",
"A herring.",
"A lobster.",
"A mussel.",
"An oyster.",
"A prawn.",
"A salmon.",
"A smelt.",
"A rare catch (see below)."    ] },
{  "title": "d10 Deep-sea catch: You haul in...",   "roll": [
"A crab.",
"A cod.",
"A haddock.",
"A halibut.",
"A mackerel.",
"A oyster.",
"A shrimp.",
"A squid.",
"A tuna.",
"A rare catch (see below)."    ] },
{  "title": "d6 Rare catch: You haul in...",   "roll": [
"A piece of junk (d4): 1. tangle of seaweed; 2. torn net; 3. rotten wood; 4. old boot.",
"An abalone.",
"A monkfish.",
"An octopus.",
"A sea bass.",
"A giant squid (fights, attacks)."    ] }    ] },

{   "title": "- Warm Ocean Fishing",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d8 Near-shore catch: You haul in...",   "roll": [
"An anchovy.",
"A clam.",
"A crab.",
"A mussel.",
"A scallop.",
"A sea bass.",
"A skate.",
"A rare catch (see below)."    ] },
{  "title": "d10 Deep-sea catch: You haul in...",   "roll": [
"A cuttlefish.",
"A flounder.",
"A grouper.",
"A marlin.",
"A sardine.",
"A scallop.",
"A shrimp.",
"A snapper.",
"A tuna.",
"A rare catch (see below)."    ] },
{  "title": "d8 Rare catch: You haul in...",   "roll": [
"A piece of junk (d4): 1. tangle of seaweed; 2. torn net; 3. rotten wood; 4. old boot.",
"An abalone.",
"A barracuda (fights, attacks).",
"A lobster.",
"A monkfish.",
"An octopus (attacks).",
"A reef shark (fights, attacks).",
"A swordfish (fights)."    ] }    ] },

{   "title": "- Freshwater Fishing",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d10 Cold-water catch: You haul in...",   "roll": [
"A bass (fights).",
"A carp.",
"An eel.",
"An oyster.",
"A perch.",
"A salmon.",
"A smelt.",
"A sturgeon.",
"A trout.",
"A walleye"    ] },
{  "title": "d10 Warm-water catch: You haul in...",   "roll": [
"A carp.",
"A catfish (fights).",
"An eel.",
"An oyster.",
"A perch.",
"A prawn.",
"A quipper (fights, attacks).",
"A salmon.",
"A tilapia.",
"A trout"    ] },
{  "title": "d6 Swamp-water catch: You haul in...",   "roll": [
"A bass (fights).",
"A catfish (fights).",
"A crayfish.",
"A crocodile (fights, attacks).",
"An eel (fights).",
"A prawn."    ] }    ] },

{   "title": "Legendary Weapons",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d8 The weapon is...",   "roll": [
"A longsword.",
"A shortsword.",
"A greatsword.",
"A spear.",
"A scythe.",
"A dagger.",
"A battleaxe.",
"A greataxe."    ] },
{  "title": "d12 The blade is made of...",   "roll": [
"Obsidian.",
"Diamond.",
"Simple steel, forged to perfection.",
"Steel cooled in demon's blood.",
"Steel cooled in dragon's blood.",
"Adamantium.",
"Dragon fang.",
"An elemental substance (d4): 1. flame; 2. ice; 3. lightning; 4. wind.",
"Stone.",
"Glass.",
"Enchanted wood.",
"Bone."    ] },
{  "title": "d10 The shaft is made of...",   "roll": [
"Polished elm.",
"Bone.",
"Gold.",
"Rough Oak.",
"Iron.",
"Bronze.",
"Silver.",
"Blackened steel.",
"Ancient oak.",
"The weapon is made of one piece, the shaft is the same as the blade."    ] },
{  "title": "d10 The maker was...",   "roll": [
"A dwarf.",
"A tiefling.",
"A human.",
"An elf.",
"A dragonborn.",
"A god.",
"An orc.",
"A hobgoblin.",
"A half-elf.",
"A fiend."    ] },
{  "title": "d10 Who was...",   "roll": [
"A blacksmith.",
"A weaponsmith.",
"An armorer.",
"A king.",
"A magician.",
"A hero.",
"A priest.",
"An adventurer.",
"A warrior.",
"A hunter."    ] },
{  "title": "d10 The weapon is famous because...",   "roll": [
"It slew a mighty beast.",
"It was used to lead a great army.",
"It killed kings.",
"Its owner stood, alone, against an army, and won.",
"Its owner was a paragon of virtue.",
"It killed a god.",
"It killed a great demon.",
"It has slain hundreds of thousands.",
"It slew a dragon.",
"It contains the soul of an ancient hero or villain."    ] },
{  "title": "d10 Other interesting things include...",   "roll": [
"A jewel where the shaft meets the blade (d4): 1. diamond; 2. emerald; 3. ruby; 4. sapphire.",
"Its maker was killed to stop him from making a better weapon.",
"It has fine metal work along the blade (even if the blade is made of an elemental substance).",
"It cannot be sheathed without tasting blood.",
"It was tempered in an icy lake.",
"It was forged in a volcano.",
"It is decorated with symbols where the shaft meets the blade.",
"It was cooled in a full moons light.",
"It can only be wielded by the pure of heart.",
"It can only be wielded by the just."    ] }    ] },

{   "title": "Magic Wand Generator",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d8 The wand's tip is...",   "roll": [
"An orb of lightning.",
"A shard of crystal.",
"A burning flame.",
"An orb of obsidian.",
"A jagged flint tip.",
"An orb of glass and wind.",
"Not there, this item is a rod with no tip.",
"A metal cap (d4): 1. brass; 2. copper; 3. gold; 4. iron; 5. platinum; 6. silver."    ] },
{  "title": "d8 The wand's shaft is...",   "roll": [
"Elm, grown in moonlight.",
"The horn of a unicorn.",
"An iron bar.",
"Oak, strong and firm.",
"Stone, cool beneath your fingers.",
"Silver, glinting.",
"Adamantium.",
"Not there, this is an orb not a wand."    ] },
{  "title": "d8. The wand is also decorated with...",   "roll": [
"Mystic runes, that cause pain to look upon.",
"Small, shining gemstones.",
"Intricate metal work.",
"A carved stone eye.",
"A swirling of wind that surronds the object.",
"An always glowing light.",
"Large rough-cut gemstones.",
"Runes that are warm to the touch."    ] },
{  "title": "d6 The creator of this object was...",   "roll": [
"A god.",
"An elf.",
"A dwarf.",
"A human.",
"A half-elf.",
"A tiefling."    ] },
{  "title": "d8 Who...",   "roll": [
"Was banished for the object's creation.",
"Was revered for the object's creation.",
"Was killed for the object's creation.",
"Was insane.",
"Went insane.",
"Was a beacon of goodness.",
"Was a force of evil.",
"Had no magical talent."    ] }    ] },

{  "title": "Random Magical Device Mishaps",   "use": "Stored spell mishaps may not render the device inoperable, merely discharged. But the stored spell must be replaced. If you have sufficient understanding of the device, you can spend one hour repairing it after a stored spell mishap has occurred. You must be able to cast the stored spell (or an appropriate replacement for it) and expend a spell slot of appropriate level in order to do so (DM's discretion). I would use this table for random scroll-scribing mishaps. \n Alchemical Mishaps do not render the device inoperable. However, no one can attempt to operate the device again until its alchemical component has been replaced with the appropriate alchemical item or potion. Results 13-20 on the Alchemical Mishaps table do significant damage to the device, rendering it inoperable. If you have sufficient understanding of the device, you can spend one hour (or longer) repairing it after a damaging alchemical mishap has occurred. You might need appropriate tools, need to use an appropriate alchemical item or potion, need to expend a spell slot, or replace mechanical parts.\n A mechanical mishap renders the device inoperable until it is repaired. Repairing the device takes one hour (or longer). You might need appropriate tools, need access to special materials, or need to expend a spell slot.",   "rolls": [
{  "title": "d6 Magical Device Mishaps",   "roll": [
"Nothing happens. You're not sure why. Any further attempts to use the device for the next 24 hours automatically fail, and you trigger a device mishap. (Re-roll on this table if you roll a 1 again on subsequent attempts.)",
"Roll on Stored Spell Mishaps table.",
"Roll on Alchemical Mishaps table.",
"Roll on Mechanical Mishaps table.",
"Roll on Stored Spell Mishaps and Mechanical Mishaps tables.",
"Roll on Alchemical Mishaps and Mechanical Mishaps tables."    ] },
{  "title": "d20 Stored Spell Mishaps",   "roll": [
"Befuddled. Your head spins, and you have trouble making sense of your surroundings. You take 1d6 psychic damage, and you have disadvantage on all Intelligence ability checks until you complete a long rest.",
"Clouded Mind. You have trouble thinking clearly. You have disadvantage on Intelligence and Wisdom saving throws until you complete a long rest.",
"Explosive boom. The stored spell explodes with a loud bang. You take 1d6 thunder damage, and you are deafened for 1 hour.",
"Explosive flash. The stored spell explodes in a bright flash. You take 1d6 radiant damage, and you are blinded for 1 hour.",
"Fiery burst. The stored spell explodes in a fiery burst. You take 2d6 fire damage.",
"Forceful burst. The stored spell explodes in a burst of force. You take 2d6 force damage.",
"Icy burst. The stored spell explodes in a burst of frost. You take 2d6 cold damage.",
"Life drain. The stored spell sizzles with necrotic energy. You take 1d6 necrotic damage, and you cannot regain hit points until you complete a long rest.",
"Mad twitching. You twitch erratically. You have disadvantage on Dexterity and Charisma saving throws until you complete a long rest.",
"Magical illness. You feel sick to your stomach. You are poisoned for 1 hour, and you have disadvantage on Constitution and Strength saving throws until you complete a long rest.",
"Operator spell hazard. The stored spell targets you.",
"Bystander spell hazard. The stored spell targets a random creature within 30 ft. of you, other than yourself.",
"Spell burst hazard. The stored spell targets the you and 2d4 creatures within 30 ft. of you.",
"Empowered spell hazard. The stored spell targets targets a random creature within 30 ft. of you. Any damage the stored spell deals is doubled.",
"Extended spell hazard. The stored spell targets a random creature within 30 ft. of you. The duration of the spell's effect is doubled.",
"Operator surge hazard. The stored spell targets you. Roll again on this table, using a d10.",
"Bystander surge hazard. The stored spell targets a random creature within 30 ft. of you, other than yourself. Roll again on this table, using a d10. Apply that effect the creature targeted by the spell.",
"Spell burst surge hazard. The stored spell targets you and 2d4 creatures within 30 ft. of you. Roll again on this table, using a d10. Apply that effect to each creature targeted by the spell.",
"Double trouble operator hazard. Roll 2d4 times on this table using a d10. Apply each effect to yourself.",
"Double trouble bystander hazard. Roll 2d4 times on this table using a d10. Apply each effect to a random creature within 30 ft. of you, other than yourself."    ] },
{  "title": "d20 Alchemical Mishaps",   "roll": [
"Befuddled. Your head spins, and you have trouble making sense of your surroundings. You take 1d6 psychic damage, and you have disadvantage on all Intelligence ability checks until you finish a long rest.",
"Deathly ill. You take ill, teetering uncomfortably close to death. You take 1d6 necrotic damage, and you cannot regain hit points until you finish a long rest.",
"Disoriented. You have trouble thinking clearly. You have disadvantage on Intelligence and Wisdom saving throws until you finish a long rest.",
"Nausea. You feel sick to your stomach. You have disadvantage on Constitution and Strength saving throws until you finish a long rest.",
"Dizziness. You feel light-headed and unsteady on your feet. You have disadvantage on all Dexterity ability checks until you finish a long rest.",
"Upset Stomach. You feel very queasy. You have disadvantage on all Strength ability checks until you finish a long rest.",
"Poison exposure. You are exposed to toxins. You take 1d6 poison damage, and you are poisoned for 1 hour.",
"Headache. You develop a splitting headache. You have disadvantage on all Intelligence ability checks until you finish a long rest.",
"Skin irritation. Your skin breaks out in an unsightly rash. You have disadvantage on all Charisma ability checks until you finish a long rest.",
"Coughing fits. You suffer fits of violent coughing. You have disadvantage on Dexterity and Charisma saving throws until you finish a long rest.",
"Euphoria. You feel giddy and content. You have disadvantage on all Wisdom ability checks until you finish a long rest.",
"Extreme Nausea. You feel so sick you can barely stay on your feet. You take 1d6 poison damage. You have disadvantage on all Strength ability checks until you finish a long rest.",
"Chills. You catch chills and shake uncontrollable. You take 1d6 cold damage. You have disadvantage on all Dexterity ability checks until you finish a long rest.",
"Accidental fire. You are burned as your reagents catch fire. You take 2d6 fire damage.",
"Uncontrollable fire. Your reagents catch fire and begin to spread to the vicinity. You take 3d6 acid damage, and each creature within 10 feet of you takes 1d6 fire damage. Flammable objects within 10 feet of you catch fire.",
"Acid spill. You are splashed with a caustic substance. You take 2d6 acid damage.",
"Large acid spill. A vat of acid bubbles over violently, corroding everything in the vicinity. You take 3d6 acid damage, and each creature within 10 feet of you takes 1d6 acid damage. Objects within 10 feet of you that cannot withstand corrosion take 1d6 acid damage.",
"Explosive boom. Your reagents explode with a loud bang. You take 1d6 thunder damage, and you are deafened for 1 hour.",
"Explosive flash. Your reagents explode in a bright flash. You take 1d6 radiant damage, and you are blinded for 1 hour.",
"Massive explosion. Your reagents explode in spectacular fashion. You take 2d6 thunder damage, 2d6 radiant damage, and you are blinded and deafened for 1 hour. Additionally, each creature within 15 feet of you takes 1d6 thunder damage and 1d6 radiant damage. Flammable objects within 15 feet of you catch fire."    ] },
{  "title": "d8 Mechanical Mishaps",   "roll": [
"Jammed gears. A bit of debris has lodged itself between two gears.",
"Broken gear teeth. One or more teeth have broken off a gear. The gear must be mended or replaced.",
"Broken belt. A serpentine belt linking several shafts has broken and must be mended or replaced.",
"Rust. Several moving parts have rusted and must be cleaned and oiled.",
"Small fire. The oil that lubricates several parts has caught fire.",
"Broken shaft. A shaft has snapped in two and must be mended or replaced.",
"Slipped spring. A spring pops free of its proper location in the device. The spring must be replaced.",
"Loose screw. A screw or bolt has come off, causing two parts that were firmly attached to come apart. The screw or bolt must be replaced."    ] }    ] },

{   "title": "The One-Minute Pantheon",   "use": "Suggested Method I:\n\nRoll 1d12 to determine the number of deities in the pantheon.\n    Roll 1d12 for each deity to determine the deity’s type. If the same number comes up twice, keep it, but choose different aspects.\n    Roll for features for each deity in the pantheon and give him/her a name.\n    Establish a few relationships among the deities: love, hatred, rivalry, friendship, parentage, etc.\n\nSuggested Method II:\n\n    Choose the deities and features you like from the lists.\n    Add some deities or features of your own.\n    Name the deities.\n    Establish a few relationships among the deities: love, hatred, rivalry, friendship, parentage, etc.",   "rolls": [
{  "title": "d12 Number of Deity's in your Pantheon…",   "roll": [
"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"    ] }    ] },

{  "title": "- Select Deities",   "use": "For the number of deities in the previous step, roll this item that amount of times.",   "rolls": [
{  "title": "d12 Your deity is…",   "roll": [
"God of the Sun/Sky",
"Earth Mother/Goddess",
"God of Craft/Knowledge",
"God of Darkness/Secrets",
"God of Death/Evil",
"God of the Harvest/Seasons",
"Goddess of Love/Fertility",
"Goddess of Moon/Magic",
"Goddess of Hunt/Woodlands",
"God of Storms/Seas",
"The Trickster/Messenger God",
"The War/Tyrant God"    ] }    ] },

{  "title": "- God of the Sun/Sky",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d6 This god of the sun and/or sky is often called...",   "roll": [
"The Father of the Heavens.",
"The Master of the Skies.",
"The King of the Wind and Sky.",
"The Keeper of the Sun's Flame.",
"The Lord of Light.",
"The Burning Man."    ] },
{  "title": "d6 He holds dominion over...",   "roll": [
"The sun and light.",
"The sun and stars.",
"The winds and clouds.",
"Light and fire.",
"Fire and power.",
"The air elementals and fire elementals."    ] },
{  "title": "d6 His followers must...",   "roll": [
"Always keep a lamp burning.",
"Ritualistically burn or brand themselves.",
"Pray at sunrise and sunset.",
"Read his sacred texts in the daylight hours daily.",
"Keep a sundial at their homes as part of a shrine.",
"Humbly cover themselves from ever allowing direct sunlight to reach their skin."    ] }    ] },

{   "title": "- Earth Mother/Goddess",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d6 This earth and/or mother goddess is often called...",   "roll": [
"The Mother of All Things.",
"The Keeper of Life and Death.",
"The Earth-Mother.",
"The Protector of Life.",
"The Defender of her Children.",
"The Queen of the Earth."    ] },
{  "title": "d6 She holds dominion over...",   "roll": [
"The earth and harvest.",
"The earth and trees.",
"Maidens and healers.",
"Family and childbirth.",
"The hearth and home.",
"Wives and mothers."    ] },
{  "title": "d6 Her followers must...",   "roll": [
"Have a shrine dedicated to her at home.",
"Ritualistically bury their dead in the earth.",
"Pray prostrate on the ground daily.",
"Always use salt to season their food.",
"Grow something in or at their home.",
"Take care of their own mothers as they age."    ] }    ] },

{  "title": "- God of Craft/Knowledge",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d6 This god of crafting and/or knowledge is often called...",   "roll": [
"The Forger of Mountains.",
"The Lord of Craft.",
"The Maker of Metal.",
"The Master of Wisdom.",
"The Keeper of Knowledge.",
"The Great Smith."    ] },
{  "title": "d6 He holds dominion over...",   "roll": [
"Forges and fire.",
"Artisans and craftsmen.",
"Knowledge and skill.",
"Knowledge and wisdom.",
"Armorers and blacksmiths.",
"Metal and flame."    ] },
{  "title": "d6 His followers must...",   "roll": [
"Build or craft something with their hands.",
"Ritualistically burn their dead.",
"Engage in vigorous scholarly debates.",
"Read something new every day.",
"Collect, melt-down, and re-forge any discarded metal objects.",
"Maintain a shrine with candles and a small stone or metal figurine dedicated to the god in their home."    ] }    ] },

{   "title": "- God of Darkness/Secrets",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d6 This god of darkness and/or secrets is often called...",   "roll": [
"The Lord of Darkness.",
"The Serpent in the Shadows.",
"The Finder of Secrets.",
"The Watchful Eye.",
"The Spider in the Gloom.",
"The Keeper of Mysteries."    ] },
{  "title": "d6 He holds dominion over...",   "roll": [
"Darkness and poison.",
"Shadows and spies.",
"Secrets and treachery.",
"Ancient lore and mysteries.",
"Assassins and thieves.",
"Spiders and snakes."    ] },
{  "title": "d6 His followers must...",   "roll": [
"Never speak of their true devotion to nonbelievers.",
"Ritualistically cut out their tongues if they betray a secret.",
"Pray every night while in utter darkness.",
"Keep a journal of secrets in a hidden location.",
"Learn a set of secret gestures to recognize a fellow believer.",
"Avoid direct sunlight."    ] }    ] },

{  "title": "- God of Death/Evil",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d6 This god of death and/or evil is often called...",   "roll": [
"The Harbinger of Death.",
"Death's Companion.",
"The Lord of Torment.",
"The Bringer of Pain.",
"The King of Cruelty.",
"The Collector of Souls."    ] },
{  "title": "d6 He holds dominion over...",   "roll": [
"Necromancers and assassins.",
"Death and pain.",
"Cruelty and torture.",
"Death and cruelty.",
"Ghosts and graveyards.",
"Torment and discord."    ] },
{  "title": "d6 His followers must...",   "roll": [
"Commit murder at least once in their lives.",
"Ritualistically eat their dead.",
"Participate in painful rituals of human sacrifice.",
"Pray in a cemetery, tomb, or place touched by death weekly.",
"Read his sacred texts in a crypt or place touched by death.",
"Keep a shrine in their home that contains the bones of someone they knew."    ] }    ] },

{  "title": "- Goddess of Love/Fertility",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d6 This goddess of love and/or fertility is often called...",   "roll": [
"The Bearer of Children.",
"The Fair Maiden.",
"The Mistress of Seduction.",
"The Giver of Love.",
"The Queen of Beauty.",
"The Bearer of Fruit."    ] },
{  "title": "d6 She holds dominion over...",   "roll": [
"Marriage and children.",
"Love and music.",
"Love and beauty.",
"Seduction and manipulation.",
"Music and dance.",
"Lovers and poets."    ] },
{  "title": "d6 Her followers must...",   "roll": [
"Participate in ritualistic sexual orgies.",
"Procreate to the fullest extent they can.",
"Publicly display their affections for loved ones.",
"Keep a secret journal of romantic exploits.",
"Eat sacred fruits on specified feast days.",
"Be subject of a ceremony that welcomes them into adulthood."    ] }    ] },

{  "title": "- Goddess of Moon/Magic",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d6 This goddess of the moon and/or magic is often called...",   "roll": [
"The Lady of the Moon.",
"The Moon-Witch.",
"The Mistress of Starlight.",
"The Maiden of Magic.",
"The Lady of Light and Shadow.",
"The Queen of Night."    ] },
{  "title": "d6 She holds dominion over...",   "roll": [
"The moon and the stars.",
"The moon and the night.",
"Magic and light.",
"Witches and wizards.",
"Magic and the night.",
"Astrologers and seers."    ] },
{  "title": "d6 Her followers must...",   "roll": [
"Hold an all-night prayer vigil when the moon is full.",
"Read her sacred texts by moonlight once a month.",
"Engage in vigorous debates of mysticism and magic.",
"Keep a journal of magical secrets and lore.",
"Learn to read ancient runes.",
"Never take a meal during daylight hours."    ] }    ] },

{  "title": "- Goddess of the Hunt/Woodlands",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d6 This goddess the hunt and/or woodlands is often called...",   "roll": [
"The Great Huntress.",
"The Lady of the Hunt.",
"The Maiden of the Woods.",
"The Keeper of the Ancient Grove.",
"The Spirit of the Forest.",
"The Princess of Predators."    ] },
{  "title": "d6 She holds dominion over...",   "roll": [
"Hunters and woodsmen.",
"Beasts and the wilderness.",
"Forests and trees.",
"Forests and woodland creatures.",
"Druids and rangers.",
"Elves and the fey."    ] },
{  "title": "d6 Her followers must...",   "roll": [
"Pray beneath a tree every day.",
"Read her sacred texts in a grove of trees once a week.",
"Participate in an annual hunting festival.",
"Prepare burnt offerings of beasts slain on a hunt.",
"Never harm a living tree.",
"Plant a new tree wherever another has fallen."    ] }    ] },

{  "title": "- God of the Storm/Seas",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d6 This god is of storms and/or seas often called...",   "roll": [
"The Lord of Thunder and Lightning.",
"The Storm-Bringer.",
"The Master of the Seas.",
"The Taker of Ships.",
"The Prince of Wind and Water.",
"The King Beneath the Waves."    ] },
{  "title": "d6 He holds dominion over...",   "roll": [
"The sea and storms.",
"The sea and ships.",
"Sailors and pirates.",
"Storms and strength.",
"Merchants and traders.",
"Fish and fowl."    ] },
{  "title": "d6 His followers must...",   "roll": [
"Splash saltwater on themselves when praying daily.",
"Give their dead a burial at sea.",
"Kneel outside to offer a short prayer whenever it rains.",
"Keep a journal of storms and strange meteorological phenomena.",
"Collect rainwater to use in sacred rituals.",
"Always offer shelter from storms to anyone who needs it."    ] }    ] },

{  "title": "- The Trickster Messenger God",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d8 This trickster and/or messenger god is often called...",   "roll": [
"The Maker of Mischief.",
"The Knife-Sharp Wit.",
"The Messenger of the Gods.",
"The Swift Strider.",
"The Lucky Traveler.",
"The Wandering Rogue.",
"The Giver of Wine.",
"The Wild Wanderer."    ] },
{  "title": "d6 He holds dominion over...",   "roll": [
"Mischief and pranks.",
"Trickery and cruel jokes.",
"Rogues and thieves.",
"Travelers and wanderers.",
"Wine and festivals.",
"Roads and winds."    ] },
{  "title": "d6 His followers must...",   "roll": [
"Drink enormous amounts of wine at festivals.",
"Participate in pranks and subversive activities.",
"Pray at the beginning and end of any journey.",
"Make a pilgrimage to a holy place at least once.",
"Always offer food and drink to travelers.",
"Reserve one day of the week for merriment and leisure."    ] }    ] },

{  "title": "- The War/Tyrant God",   "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d6 This war/tyrant god is often called...",   "roll": [
"The Lord of Battle.",
"The Bringer of Blood.",
"The Unyielding Tyrant.",
"The Harbinger of Doom.",
"The War-Maker.",
"The Prince of Sword and Spear."    ] },
{  "title": "d6 He holds dominion over...",   "roll": [
"Soldiers and gladiators.",
"Violence and slaughter.",
"Tyranny and domination.",
"Strength and glory.",
"Barbarians and mercenaries.",
"Battle and victory."    ] },
{  "title": "d6 His followers must...",   "roll": [
"Ritualistically scar themselves.",
"Fight with a military company or war clan at least once.",
"Read his sacred texts and train with weapons daily.",
"Spend the night in prayer on the eve of battle.",
"Anoint their weapons and armor with sacred oil.",
"Say a prayer when washing blood from their weapons."    ] }    ] },

{  "title": "- Relationships",   "use": "Roll these tables as often as you like to build a webs of relationships among the deities and with their followers.",   "rolls": [
{  "title": "d10 Intrapantheon relationships: [This deity] is the _____ of [that deity].",   "roll": [
"father/mother",
"sister/brother",
"son/daughter",
"husband/wife",
"spurned lover",
"close ally",
"sometimes ally",
"false ally",
"oft-times rival",
"bitter enemy"    ] },
{  "title": "d6 The gods are...",   "roll": [
"Gods, you heretic half-wit.",
"Mortals who aquired great power.",
"Children of a now dead Pantheon.",
"Devils who staged a successful coup.",
"Fake, and their priests are frauds or misguided.",
"Creatures from a distant plane never heard of."    ] },
{  "title": "d6 The gods relationship with their followers...",   "roll": [
"Is good. The god attempts to protect and provide for them.",
"Is harsh. The god demands great sacrifices from their people.",
"Is parasitic. The god feeds on worship and/or sacrifices.",
"Is benevolent, but distant. The god provides his clerics power but provides little direction.",
"Is strained. The followers have done something to offend their god recently.",
"Must be Crazy. The god has done something recently that befuddles his/her followers."    ] }    ] },

{  "title": "Random Pickpocket Loot",   "use": "Use these tables for quick inspiration or roll them up randomly.",   "rolls": [
{  "title": "d10 On a successful pickpocket check, the thief finds...",   "roll": [
"A scrap of paper or parchment with an unintelligible note scribbled on it.",
"A scrap of paper or parchment with a list of mundane items or tasks written on it.",
"Some lint or a bit of thread.",
"An errant button or broken piece of something.",
"An old or well-worn key (roll on the key table).",
"An new or little-used key (roll on the key table).",
"A clean handkerchief (roll on the handkerchief table).",
"A soiled handkerchief (roll on the handkerchief table).",
"A score (roll on the score table).",
"A score (roll on the score table) and roll again on this table using a d8."    ] },
{  "title": "d6 The key is...",   "roll": [
"A small brass key.",
"A large brass key.",
"A thin brass key.",
"A heavy iron key.",
"A spindly iron key.",
"Made of an unusual material."    ] },
{  "title": "d6 The handkerchief is...",   "roll": [
"A fine silk handkerchief.",
"A simple cotton handkerchief.",
"A lacy handkerchief.",
"A threadbare handkerchief.",
"A striped handkerchief.",
"A spotted handkerchief."    ] },
{  "title": "d12 The thief scores...",   "roll": [
"2d4 cp.",
"3d6 cp.",
"1d6 sp.",
"1d6 sp plus 1d10 cp.",
"2d6 sp.",
"2d6 sp plus 1d10 cp.",
"1d4 gp.",
"1d4 gp plus 1d10 sp.",
"2d4 gp plus 1d10 sp.",
"A gem or small piece of jewelery worth 5d10 gp.",
"A gem or small piece of jewelery worth 10d10 gp.",
"1d6 gp and roll again on this table."    ] }    ] },

{  "title": "Traps",   "use": "This post should add some helpful insight on what to throw at the adventuring party that doesn’t always check for those pesky tripwires. Since arcane traps and mechanical traps are so different I made two sets of tables for each of them.",   "rolls": [
{  "title": "d10 Roll Mechanical Source",   "roll": [
"Trip wire",
"Pressure plate",
"Opening a door",
"Lifting the lid on a chest",
"Grabbing a certain rung of a ladder",
"Removing an object from it’s resting place",
"Touching anything in the room, including the floor",
"Breaking the beam of a light source",
"Disturbing a source of water in the room",
"Pulling on a suspicious looking rope hanging from the ceiling"    ] },
{  "title": "d10 Roll Mechanical Triggered",   "roll": [
"Gears can be heard grinding from inside the walls",
"A low boom is heard that echoes out through the dungeon",
"A high pitched whirring can be heard",
"Various ticking sounds are heard",
"A quick release of steam followed by a bang",
"A low rumbling that shakes the room for a moment",
"A single click",
"The sound of chains sliding across stone",
"A thumping sound that starts slow and begins picking up speed",
"Nothing. Silence"    ] },
{  "title": "d10 Roll Mechanical Trap",   "roll": [
"The floor opens downward into a 40 foot pit",
"From unseen slits in the wall, poisoned needles fly out",
"A wall opens revealing a golem to ambush the party",
"A large log swings down from the ceiling",
"The parts of the dungeon begin collapsing, blocking off areas",
"Vents on the ceiling begin emptying noxious fumes into the room",
"A large blade swings horizontally across the room attempting to decapitate",
"The room begins filling with water after the doors slam shut",
"The walls slowly begin closing inwards",
"A large rolling boulder drops from the ceiling towards the party"    ] },
{  "title": "d10 Roll Arcane Source",   "roll": [
"An arcane rune on the floor",
"Arcane markings around a door frame",
"A pillar that has a low hum to it",
"A jeweled eye that scans the room",
"Stone statue that has glowing red eyes",
"A mysterious green fog that rolls around the base of the room",
"A very dimly lit candle that could be extinguished with the faintest breath",
"A phrase scrawled on the wall that activates when said out loud",
"Failing to cast any spell on a dull crystal floating in the center of the room",
"Lighting a rather inviting looking torch in the center of the room"    ] },
{  "title": "d10 Roll Arcane Triggered",   "roll": [
"A low hum is heard",
"A very unnatural light begins glowing brightly from an unknown source",
"Any runes in the room begin glowing a bright red",
"The room suddenly drops drastically in temperature",
"The room gets uncomfortably hot",
"A soft hiss is heard",
"A fizzling sound is heard",
"A high pitched hum rings out",
"A crackling of energy is heard through the room",
"Silence"    ] },
{  "title": "d10 Roll Arcane Trap",   "roll": [
"Sleep is cast on the room",
"Victim must resist being petrified",
"A fireball explodes throughout the room",
"All surfaces of the room begin to become too hot to touch (Effectively heat metal)",
"Fumes begin materializing as if stinking cloud was cast",
"A wall of lightning races towards the victim and any others in its way",
"All people in the room have blindness cast on them",
"The victim is sent to the astral plane for one minute",
"Everything in the room begins to levitate, no save",
"The spell Confusion is cast on everyone"    ] },
{  "title": "d10 Roll Indirect Trap",   "roll": [
"A torch is lit in another room, alerting enemies",
"A door in another room closes, hiding a secret passage",
"Chests in the dungeon lock up",
"A dangerous enemy is freed that could normally be avoided",
"All other traps that have already been triggered get reset",
"All lights are extinguished",
"Golems begin patrolling the dungeon",
"All doors in the dungeon lock themselves",
"An alarm bell begins ringing alerting all enemies of the party",
"Another more sinister trap is set in another room"    ] },
{  "title": "d10 Roll Optional Fun",   "roll": [
"Trap was never reset. Nothing dangerous happens",
"The trap does multiple things, roll twice on the effect table",
"Enemies in the room knowingly trigger the trap and then run from it",
"Enemies can be overheard talking about how useless the trap is",
"An enemy has a list of traps and how to avoid them",
"There is a dummy trigger, drawing attention away from the real trigger",
"Illusion magic is used to disguise all of the triggers",
"Enemies are foolish enough to be lured into their own traps",
"The trap fails, but not before scaring the pants off the party",
"Delay of ten seconds. Count out loud"    ] }    ] },

{  "title": "Treasure Chests",  "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d12 The chest’s style is",   "roll": [
"Crude",
"Standard",
"Fancy",
"Elven",
"Bejeweled",
"Draconic",
"Dwarven",
"Pretty Princess",
"Pirate",
"Woven",
"Creepy",
"Heavy Duty"    ] },
{  "title": "d12 It's construction material is",   "roll": [
"Old, rotting wood",
"Sturdy oak",
"Diamondwood",
"Iron",
"Steel",
"Bone",
"Obsidian",
"Glass",
"Ice",
"Silver",
"Gold",
"Ebony"    ] },
{  "title": "d12 It has hinges and trim made from",   "roll": [
"Iron",
"Steel",
"Brass",
"Silver",
"Gold",
"Bronze",
"Ebony",
"Leather",
"Wood",
"Mithril",
"Adamantite",
"Dragon Leather"    ] },
{  "title": "d12 The chest's definitive marking is",   "roll": [
"Artistic Scrollwork",
"Tree Pattern",
"Dwarven Runes",
"Elvish Script",
"Lion emblem",
"Carving of a Dragon",
"Decorative skull",
"Glowing Crystals",
"Mystic Sigils",
"Staring Eyes",
"Claw-like feet",
"Bas-relief of a battle"    ] },
{  "title": "d12 Trap Used",   "roll": [
"Poison Dart",
"Arrow",
"Small explosion",
"Alarm",
"Pit trap",
"Boulder Trap",
"Heavy Blade",
"Spears",
"Water fills room",
"Sand fills room",
"Poison gas",
"Random Spell"    ] },
{  "title": "d6 Lock type",   "roll": [
"Padlock",
"Internal mechanism",
"Combination",
"Puzzle Lock",
"Password",
"Hidden lock mechanism"    ] },
{  "title": "d6 Key Location",   "roll": [
"Hidden in same room",
"Plain sight",
"On guardian",
"Another room",
"Held by owner",
"Lost"    ] }    ] },

];
