// plots.js
//

top.plots = [

  {  "title": "Damsel In Distress",  "use": "At every point in an adventurer’s lifetime, there is bound to be a classic “Damsel in Distress” quest. Daughter or son of some wealthy noble or king gets themself captured and it’s up to the latest and greatest local heroes to bring them back. In this scenario, the word ‘damsel’ is replaced by ‘noble’ since this can be either a prince or princess.",   "rolls": [
 {  "title": "d2 The noble’s gender is",   "roll": [
 "male",
 "female",    ] },
 {  "title": "d10 The party",   "roll": [
 "finds a hastily scrawled note that used finger tips as the pen and blood as the ink",
 "experiences a vision of the keep and noble has been reoccurring in your dreams",
 "is shown a missing person notice posted by the noble’s family",
 "stumbles upon the keep by chance while out adventuring",
 "overhears a pair of knights recounting their failure in retreat",
 "is asked to investigate the keep(er) due to suspicious activity",
 "is stopped by woodland creatures who all begin chattering frantically about the situation",
 "hears gossip in the tavern about the noble’s whereabouts",
 "is told about the scenario by a traveling oracle",
 "is captured and taken by the keeper’s henchmen",    ] },
 {  "title": "d10 The noble is being kept in",   "roll": [
 "a large magnificent castle on the mountainside",
 "a cave burrowed into the side of a hill",
 "a pocket dimension that opens only on the full moon",
 "a sunken castle with an enchantment that permits water breathing inside of it",
 "the brig of a ship anchored just off the coast",
 "an abandoned, overgrown temple in the woods",
 "a travelling caravan that is difficult to track down",
 "a crypt hidden beneath a graveyard",
 "a magical prison inside an amulet worn by the keeper",
 "a hidden kingdom under the ground",    ] },
 {  "title": "d10 The noble is being held by",   "roll": [
 "an old witch with imps for henchmen",
 "a vampire lord with thrall for henchmen",
 "a beholder with nothic henchmen",
 "a bandit lord with bandit henchmen",
 "a green dragon with half-dragon henchmen",
 "a powerful wizard with golem henchmen",
 "a medusa with living statues as henchmen",
 "a lich and his skeleton henchmen",
 "a satyr prince and his satyr henchmen",
 "an orc warchief and his orc henchmen",    ] },
 {  "title": "d10 The keeper wants",   "roll": [
 "gold in exchange",
 "the noble as a slave",
 "to make a blood sacrifice to their god",
 "to use the noble as bait to lure in more prey",
 "to sell them to the highest bidder overseas",
 "to spark war between nations",
 "the noble as a suitor for their son/daughter",
 "to fill the void in their life that was caused by a loved one dying",
 "to keep the noble even though taking them happened by accident",
 "to fulfill tradition, it’s nothing personal",    ] },
 {  "title": "d10 The noble in question is",   "roll": [
 "beautiful/handsome beyond expression",
 "ugly as sin",
 "quite overweight",
 "much taller than you expected",
 "much shorted than you expected",
 "very thin and looking under-fed",
 "unusually muscular",
 "missing all of their hair",
 "much older compared to their description",
 "completely naked and [roll again]",    ] },
 {  "title": "d10 The real problem is",   "roll": [
 "the noble wants to stay",
 "the noble insists their family doesn’t really want them to come back",
 "the noble has been placed into a catatonic dream state",
 "the noble dies on the way back home",
 "the noble falls in love with a party member and doesn’t want to leave them",
 "the noble is an illusion and is being kept somewhere else [Roll another location]",
 "there are six nobles who all look similar to the description",
 "the noble is the opposite gender than what you were told",
 "the noble attacks the party in a frenzy and won’t stop until calmed down or knocked unconscious",
 "the noble gets captured again by someone else on the way back [Start over at The damsel is being kept in]",    ] },
 {  "title": "d10 Not until much later the party discovers that",   "roll": [
 "it was the wrong noble. Oops",
 "the noble is a doppleganger looking to infiltrate the family",
 "the family did it as a publicity stunt to gain attention and sympathy",
 "the noble has been getting captured on purpose to escape their family",
 "the family isn’t offering any payment for the noble’s return",
 "someone else is offering more gold for the noble than the family",
 "all members that family the noble belongs to have since died",
 "the noble was likely happier with the keeper",
 "the noble wants to be freed to go where they choose rather than back home",
 "the noble is actually a powerful wizard who invented the whole scenario to see if there is anyone of valor still left in the world",    ] },    ], },

{  "title": "Divination/Visions",  "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d10 Roll The Target",   "roll": [
"Faint. Barely audible, ominous whispers are heard revealing the prophecy",
"Scarring. Thin, painful cuts begin appearing all over the body of the seer, revealing the message",
"Herald. A messenger seen only by the seer begins telling the prophecy",
"Vision. The next few nights the vision comes to the seer in dreams",
"Chanting. Messengers seen by all materialize and begin chanting the prophecy in unison",
"Scribed. The seer loses control of their hands. The hands begin frantically writing the prophecy on the nearest surface. If no writing utensil is available they write it in their own blood",
"Unconscious. The seer collapses and begins to experience the prophecy in a dream",
"Controlled. The seer very calmly begins speaking the prophecy",
"Possessed. The seer’s eyes roll back and they mechanically start reciting",
"Violent. The seer begins convulsing and screaming the prophecy in agony"    ] },
{  "title": "d10 Roll Subject",   "roll": [
"A god",
"Mad wizard",
"A well known ruler",
"An unknown enemy",
"A monstrous beast",
"An arch-demon/arch-fey",
"A Lich",
"Mighty warrior",
"Ancient Dragon",
"A Vampire Lord"    ] },
{  "title": "d10 Roll The subject will…",   "roll": [
"be reborn",
"die",
"gain incredible power",
"destroy the world",
"destroy the seer",
"muster an unstoppable army",
"begin a terrible war",
"seek to eliminate a race of people",
"give birth to a great evil",
"open a gateway to another plane"    ] },
{  "title": "d10 Roll Helped/prevent by…",   "roll": [
"preventing the birth of a child",
"the seer to stand up to the [subject]",
"protecting a child until he becomes a man",
"destroying the subject",
"defeating forces that would want this to succeed/fail",
"summoning something to fight the [subject]",
"ending an influential figures life",
"finding a lost legendary artifact",
"convincing the gods to intervene",
"cannot be avoided, only prepare for the inevitable"    ] },
{  "title": "d10 Roll The seer experiences",   "roll": [
"Infrequent hand/eye twitching",
"Can be heard speaking the prophecy in their sleep",
"Convulsing during rests",
"Is easily frightened",
"Shows unnatural bravery",
"Hears voices that repeat the prophecy",
"Has issues sleeping (5% chance to stay awake all night)",
"Loss of appetite, starts visibly losing weight because of it",
"Recite the prophecy in other tongues unknown to the seer",
"Will experience the prophecy again at inconvenient time"    ] }    ] },

{  "title": "Nightmares",  "use": "Here's a handy toolkit for adding a little more flavor for making players afraid of what goes bump in the night. It's also no fun to run the whole nightmare yourself. Give the player some control during the dream and even let them \"try\" to fight back. ",   "rolls": [
{  "title": "d10 Roll You find yourself in",   "roll": [
"a graveyard, a blood-red moon hangs above",
"the bedroom from your childhood. There is no door to exit the room",
"the room you fell asleep in",
"absolute darkness. In the silence you can hear your own heart beat",
"an open field. Next to you is a dead oak tree with an empty noose swinging in the breeze",
"a dark forest. In the corner of your eye you can see something is following you",
"a dark cave. A low, rhythmic chanting echoes around you",
"a prison cell. The walls are scratched and your fingernails are bloodied",
"a long hallway with a door at the end. The door doesn't get closer as you approach",
"knee deep swamp water. You can feel something touching your leg under the surface"    ] },
{  "title": "d10 Roll In the [Place] you see",   "roll": [
"a boy/girl",
"a young man/woman",
"an elderly man/woman",
"yourself",
"a large dog",
"your parents",
"a shadowy figure",
"a small toy doll, standing upright",
"a large wolf, standing on it's hind legs",
"a large cat"    ] },
{  "title": "d10 Roll The [Figure]",   "roll": [
"has it's eyes and mouth sewn shut",
"is decaying. It's flesh and hair are falling to the ground",
"is wheezing loudly. You can feel your throat drying and it gets harder to breath",
"blood slowly trickles from the corners of it's mouth, then eyes, and finally it appears to be sweating blood",
"its chest bursts open and maggots and worms tumble out, writhing on the floor",
"has it's throat slit. You see the wound open and close slightly with it's breathing",
"has mismatching limbs. It looks to be sewn together using mismatching pieces",
"has the lower body of an arachnid",
"has fingernails that continue to grow. They look sharp",
"is starting to crumble away as if it were made of ash"    ] },
{  "title": "d10 Roll The [Figure]",   "roll": [
"sprints at you",
"begins walking slowly toward you",
"throws it's head back and starts cackling wildly",
"tries to speak, but spiders begin pouring out it's mouth",
"catches fire at it's feet and it quickly spreads up it's body",
"vanishes and reappears inches from your face",
"grows double it's size and begins chasing you",
"grows horrible, black, leathery wings and begins flying towards you",
"begins systematically breaking its fingers while staring you in the eye",
"starts ripping the flesh from it's face"    ] },
{  "title": "d10 Roll You wake up in a cold sweat",   "roll": [
"inches from your face is the [figure]",
"in the darkness you can see the outline of the [figure]",
"the [figure] is sprinting towards you, roll initiative. [Player wakes as soon as the figure reaches them. All spells fail and attacks miss against [figure]]",
"the door to the room opens slowly and the [figure] walks in",
"the party member closest to them is replaced with the [figure]",
"standing over you is the [figure]",
"as you are about to go to sleep you blink and the [figure] is in front of you",
"the [figure] is walking toward you slowly. You cannot move",
"the [figure] is dragging away a party member. It looks up and makes eye contact with you",
"inside of a new nightmare. Take it from the top"    ] }    ] },

{  "title": "- Nightmares Variant",  "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d12 Setting",   "roll": [
"At Sea",
"At Home",
"Surrounded by darkness",
"Surrounded by light",
"World full of gnashing teeth and grasping hands",
"Strange Aeons",
"Arena",
"Tomb",
"Temple",
"Torture Chamber",
"City",
"Unknown country",    ] },
{  "title": "d12 Action you are engaged in:",   "roll": [
"Knitting a hat for an enemy",
"Enjoying a tasty beverage made of the tears of unwashed children",
"Writing a letter to an archfiend",
"Jousting a friend",
"Constructing a golem by removing parts of yourself",
"Building an altar to an unknown god",
"Making candles out of bones",
"Ripping holes in reality with a strange knife",
"Fighting a mirror (and losing)",
"Eating the flesh of your loved ones",
"Slowly morphing into another lifeform",
"Your face is melting and you are trying to hold it together with hands that are also melting",    ] },
{  "title": "d12 Outside forces influencing your actions:",   "roll": [
"Disembodied voices of children",
"A demonic hand is castrating you",
"The air is turning into acid",
"You keep seeing the faces of everyone you love laughing at you",
"A sword keeps piercing your lungs, over and over",
"A feeling of being watched by a being beyond time",
"A vampire is chasing you",
"You are being eaten alive by thousands of tiny bugs",
"The room you are in is getting smaller",
"Gravity keeps increasing",
"A king keeps giving you orders",
"An ancient dragon repeatedly breaks your teeth",    ] },
{  "title": "d12 Cause of nightmare:",   "roll": [
"Bad Food",
"Anxiety",
"Unresolved Grief",
"Apprentice Magician",
"Angered fiend",
"Mischievous god",
"Extra-planar entity trying to communicate",
"Illness",
"You fell asleep in a place sacred to the Fey",
"Hungry Mindflayer",
"Incubus/Succubus",
"Abeloth",    ] },    ], },

{  "title": "Reputations & Rumors",  "use": "These tables are to help you determine what the PC's have heard when they bump into a new group, landmark, or story. The characters didn't live under a rock before they became adventurers, now they can know a bit about the world.",   "rolls": [
{  "title": "d10 Mercenary Band, Positive",   "roll": [
"Spotless, they are a reliable professional",
"Eccentric, they are a capable professional with unusual methods",
"Brave, they won't back down from a fight",
"Reliable, they won't back out when the going gets tough",
"Skilled, they can handle a difficult mission",
"Legendary, they won an impossible battle",
"Lengthy, they are known for many successful past missions",
"Exotic, they are from a far away land",
"Stalwart, they are known for having stood their ground during a dangerous battle",
"Noble, they fought a desperate battle pro bono"    ] },
{  "title": "d10 Mercenary Band, Neutral",   "roll": [
"Neutral, they hold to the letter of the contract",
"Raucous, but reliable in a fight",
"Solved a problem in a nearby city, but charge a large amount for it",
"Professional, they are loyal to the contract",
"Stern, their leader is known to be humorless",
"Unremarkable, they have won some battles and lost some to",
"Safe, they kept looters under control during a tense situation",
"Rigid, they kept to the contract even though they could have helped",
"New, they have yet to prove themselves",
"Enigmatic, they are known as a professional but the exact nature of their missions is unknown"    ] },
{  "title": "d10 Mercenary Band, Negative",   "roll": [
"They caused a serious problem in a nearby city",
"Disgraced, they abandoned a contract when it got to difficult",
"Dangerous, they killed someone they should not have",
"Damaged, most of their troops were lost in a recent battle",
"Fanatical, they believe in an unpopular god for the region and clash with their employer",
"Messy, they destroy the land they pass through with their foraging",
"Unreliable, they lost their last four battles",
"Spineless, they ran from a recent battle",
"Deserters, they took and employers money and disappeared",
"Rebels, they are former army troops fighting against the kingdom now for dubious causes"    ] },
{  "title": "d10 Battle, you were involved",   "roll": [
"You were there! It was awful!",
"You were there! It was glorious!",
"Someone in your family achieved fame there.",
"Someone in your family was killed there.",
"It happened near a town where you were living at the time.",
"You were supposed to have been there.",
"You made a good friend on the eve of battle and are still comrades.",
"You were wounded and left for dead.",
"Foragers sacked your home for supplies before the battle.",
"You hid to avoid being conscripted."    ] },
{  "title": "d10 Battle, Positive",   "roll": [
"It was lead by a famous general, he won handily",
"A great hero rose from the ranks of the common men.",
"A mercenary unit of great renown fought there.",
"It was the last battle ending a brutal war with a victory for the side of good.",
"The battle was so important archons took the field.",
"A small band of heroes joined the battle at the last minute and made the difference.",
"The king finally took the field personally and drove out his enemies.",
"The battle was won by the king's hand picked general, a brave man from exotic lands.",
"The royal battlemages carved the enemy into tiny pieces.",
"The battle was the positive proof of a powerful alliance."    ] },
{  "title": "d10 Battle, Neutral",   "roll": [
"The battle was a draw and the war goes on.",
"Both armies missed each other fumbling around in the dark, only their cavalry actually engaged.",
"A huge portion of the army died but the troops won in the end, the victory was hollow for the few survivors.",
"Much of the army was made up of conscripts.",
"A new pike technique was used there that may become common in the future.",
"A unusual group of allies carried the fight and took most of the glory from the common troops.",
"The king fought under the oldest banner of his house.",
"The battle took place at a legendary fortification.",
"The army had to march far from its home to fight there.",
"The troops came home from the war having seen strange places and practicing strange customs."    ] },
{  "title": "d10 Battle, Negative",   "roll": [
"An old enemy joined the fight.",
"It was a terrible defeat. The kings forces were routed.",
"The king himself was slain with his entire bodyguard unit.",
"The king was captured and publicly executed by the enemy.",
"The enemy debuted a powerful new fighting technique.",
"One side used dangerous monsters captured and trained for war.",
"A dark wizard was leading the enemy forces.",
"On the verge of defeat, one side made a deal with the devils to secure victory at the terrible price.",
"It was a bloody and terrible siege.",
"A legendary enemy appeared for the first time."    ] },
{  "title": "d30 You have heard of this priest before because....",   "roll": [
"they're the highest-ranking priest of their god in the city, something like a bishop.",
"they are quite vocal in their opposition to recent reforms within their church.",
"they are vocal in favor of reforms they feel their church is overdue for.",
"they are known in certain circles to provide healing without asking how the wounds were acquired.",
"they fearlessly run a soup kitchen in an area most charitable organizations avoid.",
"rumors are circulating about unsavory habits involving young parishioners.",
"Drunkenness. He will out-drink you.",
"Toughness. He will punch you in the face if you insult his god.",
"Geniality. He's quick with a joke and a toast, and always makes those around him feel better.",
"Hard-line beliefs. He preaches death to infidels.",
"Tolerance. He regularly dines with adherents of other faiths or those with no faith at all.",
"Pacifism. He always advocates non-violence, even to the point of being beat nearly to death by some thugs.",
"Curiosity. He is well-read and well-versed in many scholarly subjects.",
"Teaching advocacy. He is a gifted teacher and is committed to increasing literacy among members of the lower classes.",
"Preaching. He is a captivating speaker, able to attract and to motivate large crowds.",
"Humorless, they only wear dark colored clothing.",
"Cynical, they don't actually believe what they preach.",
"Dry witted, they are prone to sarcastic replies when not preaching.",
"Cryptic, they often answer a question with a question.",
"Political, they take aim at the establishment in their sermons.",
"Dangerous, they might be starting a cult.",
"False, they have been accused of convincing people to walk into a trap from another religion.",
"Associated with dangerous humanoids whom they send gullible parishioners to as tribute.",
"Drug addled, they claim to see visions while using a pungent smoke.",
"A Prophet, they actually have divine visions.",
"They claim to be a demigod or angel.",
"Poor, his parish has nothing but he perseveres.",
"Retired, he was an adventurer in a prior life.",
"Blessed, he was slain in battle with an enemy but the gods revived him.",
"Smelly, his pipe smoke is extremely pungent."    ] },
{  "title": "d20 You have heard of this mage before because....",   "roll": [
"they are rumored to have taken a demon as a lover.",
"they misspoke and cause an entire town to go barren.",
"they saved an entire garrison using only a minor spell.",
"they angered a cruel baroness by animating her favorite brush.",
"they move every full moon because children go missing.",
"they are hated by every other mage for their good looks.",
"He keeps dangerous minions in his tower.",
"One of his experiments escaped and ran through the streets of the city.",
"A dragon came to visit him last autumn.",
"He keeps a hedge maze to keep away unwanted guests.",
"He breeds war beasts for the kings army.",
"The king has been trying to bring him under his thumb for months.",
"One of his rages burned down half the city.",
"He's actually fond of visitors, but people are still scared of him. No one knows if they actually should be.",
"His automatons purchase all his food in the city on monthly errands.",
"Anyone who enters his tower never comes out",
"He often comes to town to entertain children with his cantrips.",
"He's an expert in divination spells, and will cast them for anyone for a small fee.",
"It's rumored that he curses people without them realizing it.",
"It's rumored that he has magical cures for certain... maladies."    ] },
{  "title": "d20 You have heard of this thief before because he is...",   "roll": [
"Bold. He stole the crown of the Dragon-Emperor right off his head.",
"Audacious. He stole the maidenhood of the king's own daughter.",
"Extraordinary. He single-handedly stole an entire wagon train of spices and silver in the Bleak Wastes.",
"Amorous. He stole the heart of a Southern queen who's been after his head ever since he left her for a fortune teller.",
"Daring. He stole the spellbook of the most powerful elf-witch in the world.",
"Heroic. He crept into the Duke's camp and swapped the Duke's map for a phony that led him to maneuver his host right into the rebels trap.",
"Magnanimous. He slipped in and out of the Pit of Despair six times to bring food and news to the captive prince.",
"Devilish. He climbed the walls of the Black Keep just to steal a kiss from the shadow sorceress as she slept.",
"Handsome. He has the most amazing mustache.",
"Generous. He sells the loot he steals to feed the orphans of the River District.",
"Did something impossible, like stealing a dragons tail.Tale perhaps? The dragon was a bard and the original story is much less epic?",
"Killed a man with a fork.",
"Is the sole survivor from a legendary job.",
"Is the last living man who knows where a great treasure is hidden.",
"Buried a great treasure then killed himself for reasons unknown.",
"Works for the army as a scout.",
"Stole something important, but no one can prove it.",
"On the lam after tricking a devil into selling its soul.",
"Tough. He lost two fingers in a trapped chest, but still managed to snag the goods from inside.",
"Slippery. He's escaped from the world's most inescapable prison. Twice."    ] },
{  "title": "d20 You have heard of this merchant before because",   "roll": [
"they gouge outrageous prices if their customers have no alternatives.",
"they are exceptionally wealthy, surpassing even the local ruler.",
"they have donated gold to noble causes in the past.",
"they are known in certain circles to buy items without asking where they came from",
"they are known to hire ruthless thugs to go after debtors.",
"they are said to have made their first fortune by illegally minting coins.",
"They are reputed to sell illegal magic items.",
"They are well known in the fur trade.",
"They always wear an elaborate headdress.",
"They are up and coming, and seek to eliminate the competition.",
"They own a ship or fleet.",
"They helped found an important company.",
"In distant places their company is actually more powerful than the king.",
"they're often the butt of jokes made in the local tavern.",
"rumor says that it's entirely made up of doppelgangers.",
"of their reputation to having access to highly restricted goods.",
"the local populace invoke they're name as a foul mouthed curse.",
"members are identifiable by their yellow and red armor.",
"of their ruthless efficiency in advancing their mysterious goals.",
"they hold an iron grip on the local cheese market."    ] },
{  "title": "d10 You have heard of this Explorer before because...",   "roll": [
"He published a book of his sojourns in a distant land. The book gained fame for its vivid and outlandish stories. (Which may or may not be true, which might lead to moral dilemma if the party is positioned to expose him as a fraud.)",
"She was a noblewoman who decided to travel to the holy city of a foreign land. Her actions are on the one hand considered improper, yet everyone is eager to hear of her adventures.",
"He and several other adventurers participated in a race to be the first to get to one of the most inhospitable places on the continent. He was the only one to come back alive.",
"He went on an expedition to a far off island years ago, promising to return with a horde of magical metal. He just returned recently, mostly empty handed, and completely disgraced.",
"Had his ships custom built.",
"Published a book about his sojourns claiming a prior explorers book is full of crap.",
"Bumped off a rival in a distant land.",
"Is seeking to launch one last expedition to clean his name from the disgrace of his failed ventures.",
"She became a noblewomen of a distant land through her exploits and has returned home because....?",
"He has be believed dead a dozen times already, but always turns up alive and well."    ] },
{  "title": "d20 You have heard of this Dragon before because...",   "roll": [
"It is a peaceful chatterbox. It can talk the hind leg off a donkey, and generally lets people go with a warning.",
"It is a beautiful chatterbox, talkative and extremely vain.",
"Obsessive Compulsive Hoarder. Its belongings have to be arranged just so.",
"Romantically Predatory. It's always taking humanoid form to seduce impressionable young things.",
"Has a strange hobby like carving wooden puppets or collecting butterflies.",
"Has a unusual horde, like dungeon puzzle doors, and will pay adventures to bring it new pieces for its collection.",
"Is colorblind and mated with the wrong color female dragon.",
"Is an aspiring author of travel guides but keeps frightening the peasants in new and unusual places.",
"Considers itself a naturalist and collects animals, and people, from distant lands.",
"Burned down a windmill that was blocking its view of the ocean.",
"Has the wrong breath weapon for its color.",
"Likes to capture its victims and paint their portrait before eating them.",
"Somehow lost its horde recently and is looking for revenge.",
"Keeps its horde in a pocket plane many thieves have tried to reach.",
"Has a secret bond villain style lair and mustache twirling henchmen.",
"Has some flaw that makes the locals refuse to take its threats seriously.",
"Vicious. This monster defends its territory at all costs.",
"Voracious. This creature's hunger is never stated.",
"Cruel. You'll beg for death long before this creature grants it.",
"Stealthy. This creature can move soundlessly."    ] },
{  "title": "d30 You have heard of this landmark/city before because...",   "roll": [
"It's a barbaric monument to a dead people.",
"It's unmistakable as anything else.",
"It dangerous to go there and extremely spooky.",
"You only see it if you have made a terrible mistake and gone somewhere bad.",
"It's rumored to move around.",
"It's man made, like a ship graveyard.",
"It's naturally occurring, like a mesa.",
"It's less of a landmark and more of a region with a distinct character.",
"It was formed by a great disaster.",
"Travelers come from leagues around to see it.",
"Pilgrims leave trinkets and carvings in/on/at it as they make their way for good luck.",
"It is thought that the tree will endure forever, so lovers carve their initials into it.",
"Children rub the statue's nose for good luck.",
"A famous assassination occurred on this spot.",
"The world grieved when the sorceress who is interred here died.",
"Your elder brother came to this place on his Grand Tour of the realm.",
"It's ugly as sin and doesn't at all fit with the surrounding architecture.",
"They are a major port and trading hub.",
"They are at war with another city.",
"They are the only place an important spice can be grown.",
"It is built around a giant mine.",
"The lord of the city is a dragon.",
"The city was the site of a great magical disaster.",
"The city was the site of a great magical experiment.",
"A great artist makes his home there.",
"It's so far away you've only barely heard its name before.",
"It's caught between two large, aggressive neighbors.",
"It's home to the largest cathedral to <god> in the realm.",
"It suffers a terrible reputation as a wretched hive of scum and villainy.",
"Dark magics seem to gravitate to the region."    ] }    ] },

{  "title": "Strange Places",  "use": "A few tables to generate random strange locations in the form of rumors, stories, or legends.\n\nThe basic structure is supposed to be this:\n\nSOURCE + DESCRIPTOR 1 + PLACE + DESCRIPTOR 2 somewhere AREA. If asked further, people will tell you, that SITUATION + PERSON + ACTION.",   "rolls": [
{  "title": "D10 - SOURCE",   "roll": [
"Rumors speak of a",
"When wanting to scare the children, locals tell an old tale of a",
"In the corner of the taverns sits a group of pale figures, with low voices they’re talking about a",
"Legend speak of a",
"An old man walking around town speaks of a",
"Etched into a stone is the warning of a",
"In the hand of the corpse of a woman along the road is a map with a drawing of a",
"Nailed to a tree is a small note with a warning to all about a",
"Underneath a large stone is an weather-worn diary. The last page is about a",
"Passers-by talk about the disappearance of someone. They mention a"    ] },
{  "title": "D20 - DESCRIPTOR 1",   "roll": [
"haunted",
"cursed",
"dark",
"musty old",
"ruined",
"unfinished",
"hidden",
"foul smelling",
"strange",
"living",
"shapeshifting",
"overgrown",
"ordinary looking",
"enchanted",
"strangely alluring",
"growling",
"singing",
"ever burning",
"hovering",
"damp"    ] },
{  "title": "D100 - PLACE",   "roll": [
"house",
"villa",
"small community of houses",
"estate",
"castle",
"fort",
"fortress",
"underground complex",
"temple",
"monestary",
"graveyard",
"monument",
"statue",
"tree",
"basement",
"mausoleum",
"giant nest",
"water-mill",
"granary",
"workshop",
"barrack",
"mansion",
"warehouse",
"stable",
"kennel",
"sign post",
"deep hole in the ground",
"shop",
"marketplace",
"ship",
"gate",
"tower",
"wall",
"inn",
"tavern",
"hotel",
"quarry",
"mine",
"gate",
"shrine",
"door",
"hatch",
"ladder",
"bridge",
"bedroll",
"tent",
"tree house",
"log cabin",
"hut",
"shed",
"obelisk",
"monolith",
"column",
"city block",
"guard house",
"hospital",
"townhouse",
"hamlet",
"community",
"township",
"dwelling",
"park",
"field",
"property",
"area",
"row of townhouses",
"lodge",
"lumber camp",
"fisherman’s hut",
"sanctuary",
"chapel",
"holy site",
"crossroads",
"small sized town",
"medium sized town",
"large sized town",
"small sized settlement",
"medium sized settlement",
"large sized settlement",
"small sized village",
"medium sized village",
"large sized village",
"compound",
"construction site",
"gravestone",
"tomb",
"cairn",
"mural",
"garden",
"greenhouse",
"observatory",
"museum",
"manor",
"château",
"palace",
"citadel",
"keep",
"stronghold",
"den",
"lair"    ] },
{  "title": "D20 - DESCRIPTOR 2",   "roll": [
"long forgotten",
"long abandoned",
"with the markings of a terrible beast",
"with the markings of a group terrible beasts",
"covered in etchings of dark teachings",
"with a glowing aura of a silvery light",
"said to be owned by an old man or woman",
"said to be the site of a terrible crime",
"said to be the site of a spell going terribly wrong",
"letting off the feeling of a strange presence",
"with the etchings of a dark ritual",
"said to be home to evil spirits",
"said to be corrupted by dark forces",
"said to house something truly abnormal",
"said to hold a cursed item",
"said to be the location of a decadent monthly feast with masked guests",
"said to be a fantastic place to visit",
"said to be a place of madness",
"covered in eldritch symbols",
"said to be place from where no one ever returns"    ] },
{  "title": "D20 - AREA - somewhere",   "roll": [
"within the city wall",
"not far from town",
"near the outpost",
"in the wilderness",
"in the mountains",
"in the forest",
"in the ocean",
"in the swamp",
"in the desert",
"on the great plains",
"along the coast",
"along the road",
"on a magical plane",
"in a nearby cave",
"by the lake",
"below the city",
"below the mountain",
"in the neighboring nation",
"far away",
"unknown"    ] },
{  "title": "D10 - SITUATION - If asked further, people will tell you, that",   "roll": [
"it’s definitely just a myth and you shouldn't worry.",
"people who’ve seen it are not the same.",
"it's makes people mad.",
"it turns people homicidal.",
"it is also said to hold great treasure.",
"people who’ve seen it starts rambling in a strange language.",
"it should be avoided at all cost.",
"a(nother) strange fellow also asked everyone about it not too long ago. Might have a relation as to why",
"a group of adventurers went there a few days ago and haven’t been seen since.",
"the town idiot returned from there and said it’s really isn’t as bad as people say it is. For some reason however,"    ] },
{  "title": "D6 PERSON",   "roll": [
"(d6): 1. X, the captain of the guard; 2. X, an interested archivist; 3. X, a visiting noble; 4. X, a worried local craftsman; 5. X, the parent of a missing girl; 6. X, a traveling merchant",
"(d6): 1. X, the local ruler; 2. X, a priest at a local temple; 3. X, a strange man at the inn; 4. X, a collector of sorts; 5. X, the child; 6. X, the blacksmith",
"(d6): 1. X, a local noble; 2. X, a man at the court of the local lord; 3. X, the gravedigger; 4. X, a local shopkeeper; 5. X, a local beggar; 6. X, a random hobo",
"(d6): 1. X, another adventurer; 2. X, a farm boy at a nearby estate; 3. X, the sheepherder; 4. X, the librarian; 5. X, the biologist; 6. X, a passing traveler",
"(d6): 1. X, a breeder of rare birds; 2. X, a local mason; 3. X, a famous artist; 4. X, a failed local artist; 5. X, an old tinkerer; 6. a hooded stranger",
"(d6): 1. a stranger whose name is always forgotten; 2. a stranger without a name; 3. a stranger who only communicates in writing; 4. a stranger who just leaves a letter on a PC’s pillow; 5. an old friend of a PC; 6. an eerie faceless person"    ] },
{  "title": "D20 ACTION",   "roll": [
"starts crying when asked about the place.",
"asks of the players to travel there with him.",
"asks the players to go explore.",
"asks the players to destroy it.",
"asks the players to collect something from there.",
"asks for a souvenir from there.",
"invites the players to a party, when asked about the place.",
"faints, when asked about the place.",
"suddenly disappears, when asked about the place.",
"starts growling, when asked about the place.",
"calls the guard, when asked about the place.",
"hushes on the players and leads them to his/her home, when asked about the place.",
"tries to kill the players in their sleep.",
"is seen with a map leading there.",
"tries to rally people on the street to go there together for some reason.",
"has covered all the walls of his house with drawings of the place.",
"starts drooling when asked about the place.",
"freezes for a second before completely ignoring the players and walking away, when asked about the place.",
"starts singing and dancing, when asked about the place.",
"says it’s already too late."    ] }    ] },

{  "title": "Treasure Maps",  "use": "Who doesn't love a good treasure map... Shall we go a huntin'?",   "rolls": [
{  "title": "d20 Find the...",   "roll": [
"Big cracked boulder.",
"Lightning-blasted oak tree.",
"Rock shaped like a horse.",
"Stone wall with a piece of volcanic glass .",
"Exact center of the village/town/city.",
"Statue of a famous person.",
"Shipwreck of an infamous pirate ship.",
"Bones of the black dragon.",
"Cavern near the waterfall.",
"Top of the volcano.",
"Exact center of the lake.",
"Abandoned Temple.",
"Old Fort.",
"Old Standing Circle.",
"Road marker leading south.",
"Exact center of the longest bridge.",
"Hangman's scaffold.",
"King's/Queens throne room.",
"Crossroads.",
"Largest tomb in the cemetery."    ] },
{  "title": "d8 Then...",   "roll": [
"Go North for 1-4 miles.",
"Go South for 1-4 miles.",
"Go East for 1-4 miles.",
"Go West for 1-4 miles.",
"Go Northeast for 1-4 miles.",
"Go Northwest for 1-4 miles.",
"Go Southeast for 1-4 miles.",
"Go Southwest for 1-4 miles."    ] },
{  "title": "d20 Until you find the...",   "roll": [
"Mountain shaped like a tooth.",
"Hill shaped like a saddle.",
"Cliffs of red stone.",
"Tiny caves in a white hill.",
"Old fortress ruins.",
"Dried up creek bed.",
"Swift-running river.",
"Waterfall.",
"Abandoned village.",
"Tree with a large hole in it.",
"Toppled statue of a deity.",
"Landslide of shale and gravel.",
"Steep-sided valley with blue flowers.",
"Beach strewn with black seashells.",
"Broken remains of a watchtower.",
"Road marker pointing east.",
"Dilapidated hunter's shack.",
"Crossroads.",
"Hand-cut stairway into the hillside.",
"The canyon with natural stairs leading down."    ] },
{  "title": "d8 Then...",   "roll": [
"Go North for 1-4 miles.",
"Go South for 1-4 miles.",
"Go East for 1-4 miles.",
"Go West for 1-4 miles.",
"Go Northeast for 1-4 miles.",
"Go Northwest for 1-4 miles.",
"Go Southeast for 1-4 miles.",
"Go Southwest for 1-4 miles."    ] },
{  "title": "d20 Until you find the...",   "roll": [
"Rock shaped like a heart.",
"Mountain shaped like a bird's head.",
"Petrified forest.",
"Salt lake.",
"Dried up swampland.",
"Broken bridge.",
"Old abandoned mill.",
"The ruined tower of a famous mage.",
"The ancient cemetery.",
"The mossy limestone cliffs.",
"The old granite quarry.",
"The abandoned campgrounds.",
"The vandalized statue of a former ruler.",
"The crossroads.",
"The road marker pointing West.",
"Shipwreck of a well-known war ship.",
"Minaret.",
"Quicksand.",
"Hills honeycombed with caves.",
"Old King's Forest."    ] },
{  "title": "d8 Then...",   "roll": [
"Go North for 1-4 miles.",
"Go South for 1-4 miles.",
"Go East for 1-4 miles.",
"Go West for 1-4 miles.",
"Go Northeast for 1-4 miles.",
"Go Northwest for 1-4 miles.",
"Go Southeast for 1-4 miles.",
"Go Southwest for 1-4 miles."    ] },
{  "title": "d20 You'll find the treasure...",   "roll": [
"Buried at the foot of a cliff.",
"Buried under a mighty oak tree.",
"Buried under some tower ruins.",
"Buried under a pile of skulls.",
"Buried in the grave of a famous person.",
"Hidden at the top of an old tower.",
"Hidden behind an old painting.",
"Hidden at the bottom of an old rabbit's warren.",
"Hidden in the bole of an ancient elm tree.",
"Hidden in a shipwreck's hold.",
"Guarded by assassins.",
"Guarded by monsters.",
"Guarded by soldiers.",
"Guarded by spirits.",
"Guarded by a big monster.",
"Protected by magical wards.",
"Protected by astral locks.",
"Protected by physical traps.",
"Protected by necromantic curses.",
"Protected by spiritual prayers."    ] }    ] },

{  "title": "Strange Crimes",  "use": "A few tables to generate random strange crimes.\n\nThe basic structure is supposed to be this:\n\nVICTIMTYPE + ORIGIN + VICTIM is believed to have been CRIME + LOCATION + CIRCUMSTANCES. The case is handled by INVESTIGATORS who are INTEREST solving it and WILLINGNESS share details.\n\nSOURCE a connection to CLUE.",   "rolls": [
{  "title": "D20 VICTIMTYPE",   "roll": [
"a group of travelers lead by a",
"a caravan lead by a",
"an adventuring party lead by a",
"a group of pilgrims following a",
"a young",
"an old",
"a down on his luck",
"a common",
"a few",
"a hated",
"another",
"a middleaged",
"the family of a",
"the friend of a",
"a strange",
"a famous",
"a well-liked",
"a simple dressed",
"an extravagantly dressed",
"a commonly dressed"    ] },
{  "title": "D4 ORIGIN",   "roll": [
"local",
"foreign",
"exotic looking",
"unknown"    ] },
{  "title": "D20 VICTIM",   "roll": [
"man",
"woman",
"craftsman",
"guard",
"noble",
"slave",
"servant",
"child",
"lord",
"mage",
"priest",
"merchant",
"thief",
"assassin",
"officer",
"hobo",
"prostitute",
"criminal",
"art collector",
"archivist"    ] },
{  "title": "D20 CRIME Is believed to have been...",   "roll": [
"killed",
"robbed",
"kidnapped",
"extorted",
"blackmailed",
"attacked",
"eaten",
"decapitated",
"mutilated",
"assaulted",
"taken hostage",
"banished to another plane",
"blown up",
"set on fire",
"polymorphed into an ottoman",
"fed to wild animals",
"thrown into a pit",
"tricked",
"cloned",
"shrinked"    ] },
{  "title": "D36 LOCATION (1D6D6)",   "roll": [
"at home",
"in the street in broad daylight",
"in a dark alley",
"in a tavern",
"at a brothel",
"on the outskirts of town",
"in the park",
"in someone’s garden",
"in a temple",
"on the town square",
"out in the woods",
"down by the lake",
"in the swamp",
"in the nearby ruin",
"in a nearby cave",
"by the sewer exit",
"in a guard tower",
"in an abandoned house",
"in an abandoned warehouse",
"in an old mansion",
"in the stable of an old estate",
"in the greenhouse of an old mansion",
"in a crypt",
"in a library",
"at the victims own place of work",
"in the victims own bedroom",
"in a hidden room in the victims own house",
"in the common room of a local guild",
"on a boat on the lake",
"on a quiet mountain road",
"on a track in the woods",
"out by the waterfall",
"in the cathedral",
"in the old church",
"in the catacombs",
"at an undisclosed location"    ] },
{  "title": "D10 CIRCUMSTANCES",   "roll": [
"to no real surprise to the local population.",
"under obviously mysterious circumstances.",
"causing great unrest among the local population.",
"like several similar victims before.",
"without getting any real attention from the local population.",
"and the remnants of dark magic is still draining all light from the spot.",
"and the local population hasn’t spoken a word since.",
"and the town is now under curfew.",
"and people believe it to be politically motivated.",
"as it happens every month."    ] },
{  "title": "D8 INVESTIGATORS The case is being handled by...",   "roll": [
"the city guard",
"royal guard",
"a fearsome crew with obvious scars of battle",
"a strange and quiet group, not known by any of the locals",
"men of the church",
"an old man in a robe and his dog",
"a middleaged woman in a simple uniform with her young male assistant",
"a young man, who won’t disclose his relationship to the victim assisted by his mute brother"    ] },
{  "title": "D6 INTEREST who are... solving it",   "roll": [
"keen on",
"not very interested in",
"doing all they can in",
"letting no one stand in their way of",
"not doing so much for",
"clearly making sure nothing is done in"    ] },
{  "title": "D12 WILLINGNESS and ... share details.",   "roll": [
"are hostile when asked to",
"are in no way willing to",
"are very skeptical to",
"are scared to",
"are clearly not allowed to",
"are, when completely hammered, somewhat willing to",
"skeptical, but somewhat willing to",
"somewhat willing to",
"willing to",
"very willing to",
"way to willing to",
"yelling to everyone trying to"    ] },
{  "title": "D10 SOURCE",   "roll": [
"According to your sources on the local tavern, there’s",
"A less-reputable local paper writes about",
"A scrawny town crier tell passers-by of",
"A group of craftsmen walking by talks about",
"According to the flyers distributed in quite overwhelming numbers around town, there is definitely",
"A man without teeth comes up and whispers to a PC",
"By the gate, A hideously deformed man passes you a note mentioning",
"At the scene of the crime is a verse from a poem, written with intestines laid out in beautiful cursive - it has",
"A note on a players bed speaks of",
"The players heard the victim scream something, when the crime took place, that hinted at"    ] },
{  "title": "D20 CLUE a connection to...",   "roll": [
"a local cult with rather extreme beliefs",
"a lock of strange fur",
"a rumored jealous lover",
"a hot tempered spouse",
"the local child, the one with the strangest eyes",
"markings of something having entered from beyond",
"remnants of the darkest magic",
"revenge",
"lust",
"greed",
"a murky acquaintance from the victim’s past",
"that old tablet covered in obscure symbols",
"the terrible story no one wants to remember",
"an old friend of the PCs",
"a beautiful young woman, who only came to town recently",
"another horrid crime committed not long ago",
"the escaped criminal, rumored to be in hiding nearby",
"markings of a wild animal",
"that deep rumble, that you might hear coming from below the surface of the paved roads from time to time.",
"the nightly activities of one of the PCs, but it’s all so hazy…"    ] }    ] },

{  "title": "Vignettes, encounters, and bits of color",  "use": "Add some local color to various locations",   "rolls": [
{  "title": "D20 Dungeon",   "roll": [
"A rat scuttles past carrying a finger bone with a ring on it.",
"You hear a card game going on in the next room. It sounds like someone is losing their shirt.",
"A sleepy orc pushes the party to one side and says \"otta ma way cur. Yer blocking the way to the mess hall.\"",
"A voice shouts from ahead \"My god! What did you do to the loo?\"",
"Blood drips from a hole in the ceiling and pools on the floor.",
"Your hear the sound of a whip crack from up ahead.",
"You find a room of corpses. One has a hand outstretched towards a glowing gem. A second has stabbed the first in the back with a dagger.",
"A paper boat floats past on an underground stream. If plucked from the water is has a letter written inside.",
"A prisoner in a cage sees the party and yells \"turn back! Runaway!\"",
"Cave paintings cover one of the walls, obviously the work of bored hands.",
"A side corridor has an active trap and deadly trap. A broken treasure chest at the far end spills a few coins.",
"A grate in the wall allows you to see a mimic finish consuming an adventurer and scuttle off.",
"Wind howls mournfully as you cross a rope bridge strewn with arrow riddled adventurers.",
"A hunchbacked orc with his back to you tinkers with something in the wall and complains loudly about always being the one who has to reset the traps.",
"A large man sits near a pile of treasure reading a book. If approached he changes into a wisp of smoke and retreats to a lamp. Any amount of rubbing on the lamp produces only \"Go away! We're closed!\" ",
"A displacer beast and blink dog come thrashing through a cross corridor.",
"A dead man's ghost continues searching for a key to a door. A long dead rouge lies nearby.",
"A grouchy dragon stomps around a vast cave shouting \"Igor! Where's the ledger listing my gold coins?!\"",
"A dusty side corridor holds a tiny, rough made shrine to an unlikely god, and a dusty body with it's hands still clasped in prayer.",
"A hole broken in the brick walls leads to a very, very dark tunnel."    ] },
{  "title": "D20 Idyllic Village",   "roll": [
"A farmer and his son walk past on the road. The man is teaching his son a song.",
"A wood cutter pauses his chopping to wave at you as you pass.",
"A milkman struggles past pulling a horse cart. If questioned he mentions that his horse has taken ill but he's managing.",
"A farm wife sets a pie on a windowsill to cool while you walk by.",
"A gaggle of children discuss plans to nick a pie from a windowsill.",
"A butcher haggles cheerfully with a farmer over the price of a fat cow.",
"A group of women take turns sharing gossip and hoisting buckets from the town well.",
"A celebration is taking place on the town green for two young people, recently married.",
"A farmer is having a yard sale and has piled a small mountain of junk outside his home.",
"A healthy looking dog runs past with a laughing boy in pursuit.",
"A farm wife watches playing children through an open window.",
"A man is helping a peddler fix his broken down wagon on the roadside.",
"A smith pounds furiously on his anvil but stops to smile when his wife brings him some water.",
"A group of old men with long beards sit on a stoop smoking pipes.",
"A baker is returning home from making his rounds delivering bread.",
"The town priest stands outside his church greeting people as they arrive for the service. He invites the PCs to attend.",
"A group of men is mending a broken fence.",
"A fisherman walks past carrying tackle on his way down to the lake.",
"A peddler is selling simple wares to the villagers from his wagon on the town green.",
"A group of dwarves with brightly colored hoods puff pipes on the inn porch and watch the sun set."    ] },
{  "title": "D20 Rotting City",   "roll": [
"A group of dogs chewing on fallen guardsmen after a street battle.",
"A giant spider, seen out of the corner of your eye, pulls a struggling something back into a dark alley.",
"A group of beggars in rags huddle together for warmth against the chill of the winter morning.",
"A man and a women, speaking to a stone carver about what to put on their child's headstone.",
"A burned out drug den with charred corpses outside and city guards keeping gawkers away.",
"A man doling out rations inside a besieged city. Only those able to fight still get full portions.",
"A carriage passing through a rutted street with armed guards and a dangerous looking wizard riding shotgun.",
"A tailor trying hopelessly to impress a noble women with a variety of dresses, all of which she scoffs at.",
"A gang of ruffians scoping out potential victims. They give you a nod of acknowledgement, one predator to another.",
"A strumpet with a face like a raccoon checks you out, then resignedly starts walking towards your party while putting on a fake smile.",
"A group of guards escorts a morose prisoner to the gallows.",
"A group of crows flies away from several bodies hanging at the gallows when people approach.",
"A group of elves pass the party, holding handkerchiefs to their noses.",
"A leper approaches the party and starts begging for alms.",
"The king's guard execute a man in the street for a petty crime.",
"A passing wagon hits a puddle and sprays the party with vile mud.",
"A carriage tramples a club footed beggar who was too slow to move out of the way.",
"A loan shark approaches the party to make an offer.",
"A thick fog rolls in covering the city in damp mist.",
"A church bell sounds mournfully, it's ring swallowed up by the fog."    ] },
{  "title": "D20 Ancient Forest",   "roll": [
"The song of a mocking bird changes mid-tune to an ominous imitation.",
"Elves follow you from a distance but never approach.",
"A green dragon flies overhead.",
"An ancient tree whispers softly to you as you pass.",
"A break in the tree cover lets down a welcome ray of sunshine.",
"Wolves howl in the distance.",
"This part of the forest is gray and quiet. You notice a low fog has come in and the sounds of birds have stopped.",
"A giant dead tree has fallen and blocked the road.",
"A deer bounds across the road with a puma in close pursuit.",
"You've heard tales about a devil living in these woods. You keep seeing movement from the corner of your eye.",
"A druid sits on a stone speaking to the birds.",
"A great shaggy wolfhound approaches the party. He asks if you are lost.",
"The underbrush tappers off and there is nothing left but the trunks of trees and impenetrable leaves overhead.",
"A ground bird is building a nest nearby. A colorful piece of cloth flutters among the twigs.",
"An ancient shrine looms around a corner in the path. It's long abandoned, but the workmanship was once fine.",
"A camped group of travelers in the distance notice the players approach, grab what gear they can and hide.",
"A wolverine feeds on the corpse of a fallen traveler and his horse. It growls if you get too close.",
"A courier wearing the king's livery pauses at the edge of the forest, gathers his courage, and enters down the path.",
"An undertaker lives in a cottage near the entrance to the forest. He makes a point of measuring the players before they depart. He's only concerned with their height from the neck down.",
"The party hears the sounds of a chase in the brush at night. Later, a werewolf approaches the party and demands to know if they have seen the \"would-be hunter\" pass this way."    ] },
{  "title": "D20 Aboard a ship at sea",   "roll": [
"The dolphins riding the bow waves squeak suddenly and flee.",
"A red dawn spooks the sailors.",
"A crossing the equator ceremony. The PCs are \"inducted\" into Neptune's court.",
"A women stares mournfully at the sea. She seems an unlikely passenger.",
"A sailor off duty has a fishing rod cast over the side and a pail of fish beside him.",
"The captain unexpectedly approaches the PCs and demands to know what they are doing in this part of the ship.",
"The wooden creaking of the hulls sounds ominous to the land lubbers.",
"A howling storm can be seen in the distance.",
"The Captain stares with steely eyes into a spyglass then turns to his men with a look of grim resolve.",
"The masts of another ship are visible in the distance.",
"Flotsam from a wreck is seen in the distance. Men cling to bits and pieces. The captain explains there is a reef there, and refuses to approach.",
"An imperial courier approaches the ship in port, and the captain regrets to inform his passengers there has been a change in destination.",
"Pirates approach and greet the Captain as an old friend.",
"The sun rises bright and clear, and the winds pick up, a good omen for the day.",
"Land birds are sighted in the distance where there should be none.",
"At the next stop in port the sailors sing a batch of work songs the bards has never heard before.",
"A storm is sighted coming this way. The Captain sends his first make down to below to \"make sure the cargo doesn't escape.\" ",
"A group of sailors is being flogged at the mast for breaking into the wine supplies.",
"A group of sailors is being flogged at the mast for something the party rouge actually stole.",
"Someone in the party overhears whispers of mutiny."    ] }    ] },

{  "title": "Vignettes II: Dwarves, Elves, Orcs, and Gnomes",  "use": "Add some local color to various locations",   "rolls": [
{  "title": "Dwarf Enclave",   "roll": [
"A merchant loading up his wares for a long trading journey.",
"A brewer rolling a large barrel down the street to a tavern.",
"A group of miners singing a work song with a rhythmic cadence.",
"A smith pounding hot metal at an open air forge.",
"A group of militia practicing formation fighting.",
"A group of militia discussing the weak points on a giant's body.",
"A crier hawking fine mushrooms.",
"A group of unbearded youth's fleeing the scene of a mushroom heist.",
"A group of dwarves comparing beards and ornaments.",
"A dwarf noble passes by with a gigantic mustache, ponderous and regal.",
"A tinker mending pots and pans.",
"A peddler just returned from distant lands is unloading his wagon to set up a stall.",
"A roaring fire surrounding by several dwarves turning meat on spits.",
"A dwarf guiding a party from one of the other races around the community. They receive distrusting stares.",
"A dwarf butcher moving roasts in and out of a smoke house.",
"A shrewish dwarf-wife berating her husband from a window while he chops wood in the yard.",
"A stout dwarf maid dragging a burly dwarf man off behind a building by his beard with a glint of mischief in her eye.",
"A dwarf trapper & the village rat catcher, both dressed in pelts, stomp past hauling a small wagon full of cages.",
"An elf wizard enchanting a sword of the finest dwarf make.",
"Human envoy's from distant lands, decked in gems, awaiting a chance to meet with the leader of the enclave.",    ] },
{  "title": "Elf Enclave",   "roll": [
"A lane, marked with carefully trimmed trees.",
"A single early blooming flower with the snow carefully pushed away.",
"A group of birds, twittering in tune with a druid's flute.",
"A group of border guards who appear as if from nowhere behind the party.",
"A fletcher cutting shafts for new arrows from a well tended grove of saplings.",
"A druid, protected by magic, carefully harvesting honey from well cared for bee hives.",
"A group of weavers, spinning fabric that seems to fade into the background even as it's being woven.",
"An elven cobbler, making fine boots for those with dainty feet.",
"A group of wizards cornering a druid and interrogating him about a plant they've taken an interest in.",
"An elf lord, noble in bearing, who dismisses his retinue so that he may walk through the woods undisturbed for a moment.",
"A neatly stacked pile of bows, arrows, and tanglefoot bags on the edge of a small camp.",
"A large, fine tent, it's fabric nearly invisible against the trees.",
"A rope hanging from the trees, its destination lost in the branches above.",
"A group of youth's skipping their classes. The youngest appears to be in his 80's.",
"An elf maid painting a landscape on fine canvas.",
"An elf carpenter using magic to bend wood into fine bowls and dinner ware.",
"A grand vista of the valley opens up just around a turn in the path. It's breath taking.",
"A dwarf crafting a chest with an intricate lock for an elf wizard who looks on.",
"A group of guards leads an orc prisoner away, bound and gagged.",
"A ranger, bloody and bandaged, limps into the encampment and demands to see the king immediately.",    ] },
{  "title": "Orc Enclave",   "roll": [
"A roaring feast is going on with great bonfires and drums.",
"Two orcs are fist fighting in a pit with mangled knuckles and bloody tusks.",
"An orc smith beats captured armor into new spear points for the troops.",
"A raiding party is returning with a new batch of mewling captives.",
"A young half-orc boy is being banished as his parentage is becoming more apparent.",
"A great tent, made of hide and decorated with skulls, looms over the camp.",
"A group of sweating orcs digs a trench around the camp and places sharpened stakes.",
"A brave trader has set up his wagon on the far side of the camp and it peddling goods to surly orcs.",
"A group of the kings knights have arrived to deliver an ultimatum to the chief.",
"A wrong turn takes you down a confusing path of randomly pitched tents and yurts.",
"A group of hobgoblin emissaries look around at the disorganized camp with obvious scorn.",
"A hill giant, chained and whipped, is being 'trained' for the next raid.",
"A cantankerous orc wife throws his husband out of their tent and pummels him in the street to great guffaws from onlookers.",
"The chief and his retinue pass, they seem like low brow thugs.",
"The chief and his retinue pass, he seems more regal and intelligent than you expected.",
"A group of orc traders has just returned from bartering with a town too strong to rob.",
"An orc wolf master is training pups in a pen.",
"An envoy from a stronger orc band has arrived to collect tribute.",
"A surly old dwarf walks through the camp and demands the chief present himself. The orcs give him a wide berth.",
"You overhear a group of orcs discussing their plan to overthrow the chief and take his place.",    ] },
{  "title": "Gnome Enclave",   "roll": [
"A machine, equal parts steam and brass, goes careening past with a flustered gnome in hot pursuit.",
"A persistent turnip salesman espouses the virtue of his wares and won't let you leave till you buy some.",
"Gnomes, stacked 6 high, are holding up a 7th who is tinkering with the insides of a clock tower.",
"A group of four gnomes discuss the best way to fix a broken wagon wheel.",
"A tiny gnome boy jumps up and grabs your purse. Suddenly frightened, now he won't let go because he's scared of heights.",
"A group of brownies are in town to buy goods from the \"big folk.\" ",
"A fat gnome clerk walks past with an apprentice, overburdened by books and papers, in tow.",
"A gnome running an open air cafeteria is fending off a persistent turnip merchant.",
"Garruck has gotten stuck down the town well and a group of gnomes are standing around debating how to get him out. No rush, he was testing a new potion of water-breathing.",
"Two gnomes are sitting outside a leather worker's shop sewing new pockets into their leather armor.",
"A group of youths with a pilfered pie go running past. You could probably snag it.",
"A baker is hawking the finest breads from the window of his shop.",
"A wagon full of peddlers is off to try their luck selling gizmos to the dwarves.",
"Two gnomish sages are discussing best irrigation practices.",
"A gnome is having an intense conversation with a badger on the side of the street.",
"A gnomish lord goes past on a sedan chair carried by servants. He's on eye level with you.",
"A confused ogre is helping with a local building project. Swears he's a gnome with a growth problem. Could he be telling the truth?",
"You overhear a group of gnomes plotting to build a burrowing machine that will steal all the turnips from the turnip merchant's fields.",
"You see a gaggle of gnomes desperately running towards the elven spice merchant, just arrived from distant lands. Many turnips sit abandoned.",
"A tiny flying machine zips past your ear as you look around the village. It suddenly reverses direction and comes zipping back towards you.",    ] },    ], },

];
