// wilderness.js
//

top.wilderness = [

{  "title": "Desert",  "use": "These are tables for adding quick flavor and encounters to a desert region. You can use these to generate a single desert location for an encounter or to set up a map of a desert region.",   "rolls": [
{  "title": "d12 Interesting Location: You find...",   "roll": [
"A cavern in a canyon wall.",
"A hole under a large boulder.",
"A large burrow.",
"A small cave next to a dry river bed.",
"A peculiar tent.",
"Some nomads’ camp.",
"An abandoned stone house.",
"An abandoned campsite.",
"An entrance to a rocky cave.",
"Ancient ruins.",
"A wide-mouthed cave.",
"An old tomb."    ] },
{  "title": "d12 Distinguishing Landmark: You see...",   "roll": [
"An oasis with a fruit tree.",
"An oasis with a palm tree and some desert flowers.",
"An unusually large, prickly desert plant.",
"A pair of prickly plants from the same root.",
"A patch of desert flowers in the shade of a boulder.",
"A rocky bluff.",
"A boulder shaped like a face.",
"A pair of identical boulders, side by side.",
"A boulder sitting atop a larger boulder.",
"A small, rocky canyon with a trickle of water.",
"A deep, rocky canyon with a trickle of water.",
"A dry river bed."    ] },
{  "title": "d20 Feature: You notice...",   "roll": [
"A buzzard circles overhead.",
"A vulture screams.",
"A scorpion scuttles away.",
"A large beetle scuttles away.",
"A toad hops behind a rock.",
"A lizard crawls under a rock.",
"A jackal barks.",
"A snake slithers away.",
"A butterfly flutters by.",
"A rattlesnake sounds.",
"An unusual bird chirps.",
"A gentle breeze blows.",
"The wind blows harder.",
"The wind kicks up dust.",
"Small lose stones tumble down a slope.",
"A hint of moisture on the ground.",
"A prickly plant with brightly colored fruit.",
"A strange desert flower.",
"A small palm tree.",
"Several small prickly plants."    ] },
{  "title": "d12 Encounters: You come upon...",   "roll": [
"A poisonous snake.",
"A giant spider.",
"A pack of jackals.",
"A giant lizard.",
"A ghost.",
"A pair of gnolls.",
"A pair of bandits.",
"A strange hermit.",
"A lost traveler.",
"A poor nomad.",
"A sandstorm.",
"A mirage of an oasis."    ] },
{  "title": "d10 What’s in the cave/cavern?",   "roll": [
"A swarm of beetles.",
"Lots of bats.",
"Many spider webs.",
"A troll's stash.",
"An ogre's lair.",
"Some gnolls’ hideout.",
"Bare rock.",
"Mummified remains.",
"Some bandits’ hideout.",
"A reclusive sorcerer."    ] },
{  "title": "d6 What’s in the hole/burrow?",   "roll": [
"A snake.",
"A spider.",
"Beetles.",
"Scorpions.",
"A toad.",
"A lizard."    ] },
{  "title": "d6 Who lives in the peculiar tent?",   "roll": [
"A merchant of exotic goods.",
"A misanthropic shapeshifter.",
"An eccentric monk.",
"A nomadic herder.",
"A nomadic warrior.",
"An outcast elf."    ] },
{  "title": "d6 Who lived in the stone house?",   "roll": [
"A strange hermit.",
"A reclusive scholar.",
"An eccentric healer.",
"A poor goatherder.",
"A horse trader.",
"A mining prospector."    ] },
{  "title": "d6 Who resides in the stone house now?",   "roll": [
"Poisonous snakes.",
"An ogre.",
"A pair of orcs.",
"A mad sorcerer.",
"A paranoid shapeshifter.",
"Restless ghosts."    ] },
{  "title": "d10 Who built the ancient ruins?",   "roll": [
"A tribe of lizardfolk.",
"A high elf prince.",
"A fiendish cult.",
"A dragon cult.",
"A death cult.",
"Elementalist monks.",
"A long-dead emperor.",
"A forgotten king.",
"An evil queen.",
"A dark sorcerer."    ] },
{  "title": "d10 Who lives in the ancient ruins now?",   "roll": [
"A treasure hunter.",
"A wasteland druid.",
"Poisonous snakes.",
"Cursed mummies.",
"Restless ghosts.",
"An orkish war band.",
"A tribe of kobolds.",
"A territorial griffon.",
"A pair of manticores.",
"A dragon."    ] }    ] },

{  "title": "Desert: Flame-Scorched",  "use": "Use these tables for inspiration or roll them up randomly. Some of the tables could be rolled more.",   "rolls": [
{  "title": "d10 Interesting Location: You find...",   "roll": [
"A cavern in a canyon wall.",
"A hole under a large boulder.",
"A large burrow.",
"A small cave in a volcanic rock formation.",
"A peculiar tent.",
"Some nomads’ camp.",
"A large pit that periodically belches fire and smoke.",
"An abandoned campsite.",
"An entrance to a rocky cave.",
"Ancient ruins."    ] },
{  "title": "d12 Distinguishing Landmark: You see...",   "roll": [
"An oasis with only a puddle of water.",
"Several holes, emitting fire and smoke.",
"An unusually large, prickly desert plant.",
"A pair of prickly plants from the same root",
"A patch of coarse grass in the shade of a boulder.",
"A rocky bluff.",
"A boulder shaped like a face.",
"A pair of identical boulders, side by side.",
"A boulder sitting atop a larger boulder.",
"A small, dry, rocky canyon.",
"A deep, dry, rocky canyon.",
"A solid bed of rock, formed from a lava flow."    ] },
{  "title": "d20 Feature: You notice...",   "roll": [
"A buzzard circles overhead.",
"A vulture screams.",
"A scorpion scuttles away.",
"A large beetle scuttles away.",
"A lizard crawls under a rock.",
"A jackal barks.",
"A snake slithers away.",
"A swarm of locusts buzz past.",
"A rattlesnake sounds.",
"An unusual bird chirps.",
"A gentle breeze blows.",
"The wind blows harder.",
"The wind kicks up dust.",
"Small lose stones tumble down a slope.",
"A prickly plant with scorch marks.",
"A strange desert flower.",
"A dead palm tree.",
"Several small prickly plants.",
"The smell of sulfur in the air.",
"The smell of ash and smoke."    ] },
{  "title": "d12 Encounters: You come upon...",   "roll": [
"A flame snake.",
"A swarm of scorpions.",
"A pack of jackals.",
"A giant centipede.",
"A ghost.",
"A pair of azers.",
"A pair of salamanders.",
"A pair of bandits.",
"A strange hermit.",
"A lost traveler.",
"A dust storm.",
"A sudden eruption of flame from the ground."    ] },
{  "title": "d10 What’s in the cave/cavern?",   "roll": [
"A swarm of beetles.",
"Lots of bats.",
"Many spider webs.",
"A troll's stash.",
"An ogre's lair.",
"Some gnolls’ hideout.",
"Bare rock.",
"Mummified remains.",
"Some bandits’ hideout.",
"A reclusive sorcerer."    ] },
{  "title": "d6 What’s in the hole/burrow?",   "roll": [
"A snake.",
"Dry bones.",
"Beetles.",
"Scorpions.",
"A centipede.",
"A flameskull."    ] },
{  "title": "d6 Who lives in the peculiar tent?",   "roll": [
"A merchant of exotic goods.",
"A misanthropic shapeshifter.",
"A reclusive monk.",
"A refugee far from home.",
"A dragonborn warrior.",
"A nomadic sorcerer."    ] },
{  "title": "d6 What is in the large pit?",   "roll": [
"Several flame snakes.",
"A salamander raider.",
"An azer scout.",
"A fire giant.",
"A phoenix.",
"Scorched bones."    ] },
{  "title": "d10 Who built the ancient ruins?",   "roll": [
"A clan of fire giants.",
"A high elf prince.",
"A fiendish cult.",
"A dragon cult.",
"An elemental cult.",
"Elementalist monks.",
"A long-dead emperor.",
"An ambitious djinn prince.",
"A wicked efreet lord.",
"A dark sorcerer."    ] },
{  "title": "d10 Who lives in the ancient ruins now?",   "roll": [
"A clan of fire giants.",
"A master martial artist.",
"An exiled efreet.",
"Cursed mummies.",
"Restless ghosts.",
"A salamander war band.",
"A clan of dragonborn refugees.",
"A territorial griffon.",
"A pair of manticores.",
"A dragon."    ] }    ] },

{  "title": "Shadowy Desert",  "use": "These are tables for adding quick flavor and encounters to a bleak, shadowy desert region. You can use these to generate a single wasteland location for an encounter or to set up a map of a shadowy wasteland region.",   "rolls": [
{  "title": "d12 Interesting Location: You find...",   "roll": [
"A cavern in a canyon wall.",
"A hole under a large boulder.",
"A large burrow.",
"A small cave next to a dry river bed.",
"A pair of graves.",
"A peculiar tent.",
"Some nomads’ camp.",
"An abandoned stone house.",
"An abandoned campsite.",
"An entrance to a rocky cave.",
"An ancient tomb.",
"Ancient ruins."    ] },
{  "title": "d12 Distinguishing Landmark: You see...",   "roll": [
"An oasis with a tree bearing rotten fruit.",
"An oasis with foul-smelling water.",
"An unusually large, prickly desert plant.",
"A pair of prickly plants from the same root.",
"A patch of coarse grass next to a boulder, shrouded in a strange mist.",
"A rocky bluff.",
"A boulder shaped like a skull.",
"A pair of identical boulders, side by side.",
"A boulder sitting atop a larger boulder.",
"A small, rocky canyon with a trickle of foul water.",
"A deep, rocky canyon with a trickle of foul water.",
"A dry river bed."    ] },
{  "title": "d20 Feature: You notice...",   "roll": [
"A buzzard circles overhead.",
"A vulture screams.",
"A flock of crows scatter.",
"A large beetle scuttles away.",
"A raven croaks.",
"A crow caws.",
"A rat scurries away.",
"A swarm of beetles crawl past.",
"A ghostly presence flees.",
"A ghostly presence watches curiously.",
"A beast howls mournfully in the distance.",
"An eerie silence.",
"The wind kicks up dust.",
"The breeze stops.",
"The wind moans eerily.",
"Small lose stones tumble down a slope.",
"A dead palm tree.",
"A distant scream.",
"The smell of rotting flesh.",
"The smell of decay."    ] },
{  "title": "d12 Encounters: You come upon...",   "roll": [
"A giant spider.",
"A pack of wolves.",
"An animated skeleton.",
"A malevolent ghost.",
"A restless ghost.",
"A pair of ghouls.",
"A pair of bandits.",
"A strange hermit.",
"A lost traveler.",
"A destitute nomad.",
"A dust storm.",
"A thick, cold fog."    ] },
{  "title": "d10 What’s in the cave/cavern?",   "roll": [
"A swarm of beetles.",
"Lots of bats.",
"Many spider webs.",
"A wight’s stash.",
"A ghoul’s lair.",
"Several skeletons.",
"Bare rock.",
"Mummified remains.",
"Some bandits’ hideout.",
"A creepy hermit."    ] },
{  "title": "d6 What’s in the hole/burrow?",   "roll": [
"A snake.",
"A spider.",
"Beetles.",
"Scorpions.",
"A severed limb.",
"Dry bones."    ] },
{  "title": "d6 Who lives in the peculiar tent?",   "roll": [
"A merchant of exotic goods.",
"A misanthropic shapeshifter.",
"An eccentric shadow monk.",
"A nomadic herder.",
"A nomadic warrior.",
"An outcast elf."    ] },
{  "title": "d6 Who lived in the stone house?",   "roll": [
"A strange hermit.",
"A reclusive scholar.",
"An eccentric healer.",
"A poor goatherder.",
"Someone who left no trace.",
"A member of an ancient clan."    ] },
{  "title": "d6 Who resides in the stone house now?",   "roll": [
"A death hound.",
"A handful of zombies.",
"A paranoid shapeshifter.",
"A mad necromancer.",
"A malevolent ghost.",
"Restless ghosts."    ] },
{  "title": "d10 Who built the ancient ruins?",   "roll": [
"A clan of shadowfolk.",
"A dark elf queen.",
"A fiendish cult.",
"A dragon cult.",
"A death cult.",
"Shadow monks.",
"A long-dead emperor.",
"A forgotten king.",
"An ambitious lich.",
"A dark sorcerer."    ] },
{  "title": "d10 Who lives in the ancient ruins now?",   "roll": [
"A brilliant necromancer.",
"Starved ghouls.",
"Undead guardians.",
"Cursed mummies.",
"Restless ghosts.",
"A shadowfolk war band.",
"An aberrant presence.",
"A pack of death hounds.",
"A pair of manticores.",
"A dracolich."    ] },
{  "title": "d10 Who is in the ancient tomb?",   "roll": [
"The remains of an ancient king.",
"The remains of an ancient queen.",
"The remains of an ancient sorcerer.",
"A powerful mummy.",
"An ancient demilich.",
"The remains of ancient monks.",
"Twisted humanoid bones.",
"Malevolent ghosts.",
"Zombie warriors.",
"Huge, disorganized piles of bones."    ] },
{  "title": "d10 Who is in the grave?",   "roll": [
"The corpse of a young maiden.",
"The bones of a child.",
"The bones of an old man.",
"The bones of an old woman.",
"A fallen adventurer, hastily buried.",
"A dismembered corpse.",
"Twisted humanoid bones.",
"A pile of bones.",
"A hateful mummy.",
"An empty coffin"    ] }    ] },

{  "title": "Forest",  "use": "These are tables for adding quick flavor and encounters to a forested region. You can use these to generate a single forest location for an encounter or to set up a map of a forest region.",   "rolls": [
{  "title": "d12 Interesting Location: You find...",   "roll": [
"A cavern behind a waterfall.",
"A small cave in the bank of a creek.",
"An entrance to a rocky cave.",
"A hole under a large tree.",
"A large burrow.",
"A peculiar cottage.",
"A woodsman's cabin.",
"An abandoned cabin.",
"An abandoned campsite.",
"A sacred grove.",
"A grave with an illegible headstone.",
"Ancient ruins."    ] },
{  "title": "d20 Distinguishing Landmark: You see...",   "roll": [
"A fruit tree.",
"A large, hollow tree.",
"A pair of trees from the same root.",
"A tree growing over a boulder.",
"A clearing with wildflowers.",
"A grassy clearing.",
"A moss-covered boulder.",
"A thicket of brambles.",
"A babbling brook.",
"A brook in a deep ravine.",
"A brook, with gentle rapids.",
"A dry creekbed.",
"A small pool at a creek's bend.",
"A patch of mushrooms.",
"An enormous mushroom.",
"A large, hollow log.",
"A large, rotting log.",
"A tree felled by lightning.",
"An old gnarled tree.",
"The stump of an enormous tree."    ] },
{  "title": "d20 Feature: You notice...",   "roll": [
"A flock of birds scatter.",
"A hawk cries.",
"A woodpecker drumming.",
"An owl hoots.",
"Birds chirping.",
"A chipmunk scurrying.",
"A deer dashes away.",
"A deer watches curiously.",
"A squirrel leaps from one tree to another.",
"A wolf howls.",
"Butterflies fluttering about.",
"Squirrels chittering.",
"An eerie silence.",
"The breeze stops.",
"The wind blows harder.",
"A twig snaps.",
"Brightly, colored berries.",
"Leaves rustling.",
"The scent of flowers.",
"The smell of decay."    ] },
{  "title": "d20 Dominant Species: Many of the trees are...",   "roll": [
"Apple or pear trees.",
"Ashes.",
"Birches.",
"Beeches.",
"Cedars or junipers.",
"Cherry or plum trees.",
"Chestnut or hazel trees.",
"Cypresses.",
"Elms.",
"Firs.",
"Hawthorns or hemlocks.",
"Hickory or walnut trees.",
"Linden or lime trees.",
"Maples.",
"Oaks.",
"Pines.",
"Poplars.",
"Spruces.",
"Willows.",
"Yew or holly trees."    ] },
{  "title": "d12 What’s in the cave/cavern?",   "roll": [
"A bear’s lair.",
"Lots of bats.",
"Many spider webs.",
"A troll's stash.",
"An ogre's lair.",
"Some goblins' hideout.",
"Some abandoned mining equipment.",
"Bare rock.",
"A potable spring.",
"Unidentifiable remains.",
"Some outlaws’ hideout.",
"A strange hermit."    ] },
{  "title": "d20 Encounters: You come upon...",   "roll": [
"A large bear.",
"A bear cub.",
"A giant spider.",
"Several giant spiders.",
"A pack of wolves.",
"A lone wolf.",
"A hunting cat.",
"A wailing ghost.",
"A malevolent ghost.",
"A pair of goblin scouts.",
"A goblin patrol.",
"An ogre.",
"A pair of outlaws.",
"A beggarly bandit.",
"An old witch.",
"A curious herbalist.",
"A lost child.",
"A woodcutter busy with the day’s work.",
"An intrepid hunter.",
"An elvish ranger."    ] },
{  "title": "d6 Who lives in the peculiar cottage?",   "roll": [
"A lonely old woman.",
"A reclusive shapeshifter.",
"An eccentric healer.",
"A beautiful witch.",
"A horrible witch.",
"An outcast dwarf."    ] },
{  "title": "d6 Who lived in the abandoned cabin?",   "roll": [
"A lonely old woman.",
"A reclusive scholar.",
"an eccentric healer.",
"A poor woodcutter.",
"A fur trader.",
"A dwarf prospector."    ] },
{  "title": "d6 Who resides in the abandoned cabin now?",   "roll": [
"An owlbear.",
"An ogre.",
"A troll.",
"A mad witch.",
"A paranoid shapeshifter.",
"Restless ghosts."    ] },
{  "title": "d10 Who built the ancient ruins?",   "roll": [
"Dwarvish miners.",
"A wood elf king.",
"A high elf prince.",
"A dragon cult.",
"A death cult.",
"Shadow monks.",
"A long-dead emperor.",
"A forgotten king.",
"An evil queen.",
"A dark sorcerer."    ] },
{  "title": "d10 Who lives in the ancient ruins now?",   "roll": [
"A dwarf prospector.",
"A wood elf druid.",
"Poisonous snakes.",
"Giant spiders.",
"Hungry zombies.",
"Restless ghosts.",
"A handful of ogres.",
"Some irritable trolls.",
"A pair of manticores.",
"A dragon."    ] },
{  "title": "d6 What’s in the hole/burrow?",   "roll": [
"A snake.",
"A spider.",
"A badger.",
"Earthworms.",
"A centipede.",
"Unusual fungus."    ] }    ] },

{  "title": "Forest, Enchanted",  "use": "These are tables for adding quick flavor and encounters to an enchanted forest. You can use these to generate a single forest location for an encounter or to set up a map of a forest region.",   "rolls": [
{  "title": "d12 Interesting Location: You find...",   "roll": [
"A cavern behind a waterfall.",
"A house under a large tree.",
"A large burrow with a door.",
"A small cave in the bank of a creek.",
"A peculiar cottage.",
"A house up in a tree.",
"A well-maintained cottage.",
"A ring of mushrooms.",
"An entrance to a rocky cave.",
"Ancient ruins.",
"A reflecting pool between colonnades.",
"The statue of a goddess on a beautiful marble fountain."    ] },
{  "title": "d20 Distinguishing Landmark: You see...",   "roll": [
"A lush fruit tree.",
"A large, hollow tree.",
"A pair of trees from the same root.",
"A tree growing over a boulder.",
"A clearing with wildflowers.",
"A grassy clearing.",
"A moss-covered boulder.",
"A thicket of flowering bushes.",
"A babbling brook.",
"A brook in a deep ravine.",
"A brook, with gentle rapids.",
"A creek with flowers on its bank.",
"A small pool at a creek's bend.",
"A patch of mushrooms.",
"An enormous mushroom.",
"A large, hollow log.",
"A large, rotting log.",
"A tree felled by lightning.",
"An old gnarled tree.",
"The stump of an enormous tree."    ] },
{  "title": "d20 Feature: You notice...",   "roll": [
"A flock of birds scatter.",
"A hawk cries.",
"A woodpecker drumming.",
"An owl hoots.",
"Birds chirping.",
"A chipmunk scurrying.",
"A deer dashes away.",
"A deer watches curiously.",
"A squirrel leaps from one tree to another.",
"A wolf howls.",
"Butterflies fluttering about.",
"Squirrels chittering.",
"Distant music from a harp.",
"Distant music from a flute.",
"A warm breeze blows.",
"A twig snaps.",
"Brightly, colored berries.",
"Leaves rustling.",
"The scent of flowers.",
"Pixies dancing in the distance."    ] },
{  "title": "d12 What’s in the cave/cavern?",   "roll": [
"A bear’s lair.",
"Lots of bats.",
"Many spider webs.",
"A troll's stash.",
"An ogre's lair.",
"Some goblins' hideout.",
"Fragrant mushrooms.",
"A lingering ghost.",
"Some lizardfolk’s lair.",
"The remnant’s of a satyr’s feasting.",
"A mysterious chest.",
"A reflecting pool between a pair of beautiful stone colonnades."    ] },
{  "title": "d20 Encounters: You come upon...",   "roll": [
"A large bear.",
"A bear wearing a collar.",
"A giant spider.",
"A talking spider.",
"An enormous anthill.",
"A pack of wolves.",
"A talking wolf.",
"A displacer beast.",
"A moaning ghost.",
"A mischievous ghost.",
"A pair of goblin scouts.",
"A hobgoblin beasthunter.",
"Several tiny faeries.",
"A dozen or more pixies.",
"A protective sprite.",
"A dancing satyr.",
"An old witch.",
"A lost child.",
"A high elf sage.",
"A wood elf wanderer."    ] },
{  "title": "d6 Who lives in the burrow/under the tree?",   "roll": [
"Intelligent rabbits.",
"A giant talking spider.",
"A talking badger.",
"A gnomish illusionist.",
"A gnomish prankster.",
"A suspicious sprite."    ] },
{  "title": "d8 Who lives up in the tree?",   "roll": [
"A giant owl.",
"A talking raven.",
"A wood elf ranger.",
"A high elf sentinel.",
"A band of friendly pixies.",
"Several nervous sprites.",
"A swarm of sentient butterflies.",
"It’s not a tree; it’s a treant."    ] },
{  "title": "d6 Who lives in the peculiar/well-maintained cottage?",   "roll": [
"A lonely old gnome.",
"A reclusive shapeshifter.",
"A gnomish healer.",
"A beautiful witch.",
"A horrible witch.",
"An outcast dwarf."    ] },
{  "title": "d10 Who built the ancient ruins?",   "roll": [
"A great goblin king.",
"A wood elf king.",
"A high elf prince.",
"A dragon cult.",
"The god of wine himself.",
"A lizardfolk tribe.",
"A long-dead emperor.",
"A forgotten king.",
"An evil queen.",
"A dark sorcerer."    ] },
{  "title": "d12 Who lives in the ancient ruins now?",   "roll": [
"A high elf guardian.",
"A wood elf druid.",
"A pack of blink dogs.",
"Giant spiders.",
"Restless ghosts.",
"A wicked satyr.",
"Hundreds of pixies.",
"Some wary centaurs.",
"A cloistered dryad.",
"A displacer beast.",
"A pair of manticores.",
"A dragon."    ] }    ] },

{  "title": "Forest, Haunted",  "use": "These are tables for adding quick flavor and encounters to a haunted forest. You can use these to generate a single forest location for an encounter or to set up a map of a forest region.",   "rolls": [
{  "title": "d10 Interesting Location: You find...",   "roll": [
"Ancient burial mounds.",
"A hole under a large tree.",
"A large burrow.",
"A peculiar cottage.",
"A forgotten cemetery.",
"A pair of graves.",
"An abandoned cabin.",
"An abandoned campsite.",
"An entrance to a rocky cave.",
"Ancient ruins."    ] },
{  "title": "d20 Distinguishing Landmark: You see...",   "roll": [
"A tree with rotten fruit all around its base.",
"A large, hollow tree.",
"A pair of trees from the same root.",
"A tree growing over a boulder.",
"A clearing with bare ground.",
"A clearing with an old grave marker.",
"A boulder marked with several notches.",
"A thicket of dry brambles.",
"A slow, silent stream.",
"A stream flowing quietly through a ravine.",
"A stream with barren banks.",
"A dry creekbed.",
"A foul smelling pond.",
"A patch of mushrooms.",
"The decaying carcass of a large animal.",
"A large, hollow log.",
"A large, rotting log.",
"A tree felled by lightning.",
"An old gnarled tree.",
"The stump of an enormous tree."    ] },
{  "title": "d20 Feature: You notice...",   "roll": [
"A flock of crows scatter.",
"A vulture screams.",
"A raven croaks.",
"An owl hoots.",
"A crow caws.",
"A rat scurrying.",
"A ghostly presence flees.",
"A ghostly presence watches curiously.",
"A bats take to wing from a tree.",
"A wolf howls.",
"A large moth flutters about.",
"Rats squeaking.",
"An eerie silence.",
"The breeze stops.",
"The wind blows harder.",
"A twig snaps.",
"The wind moans eerily.",
"A distant scream.",
"The scent of rotting flesh.",
"The smell of decay."    ] },
{  "title": "d20 Encounters: You come upon...",   "roll": [
"An animated skeleton.",
"A pair of skeletal warriors.",
"A giant spider.",
"A swarm of spiders.",
"A pack of wolves.",
"A savage werewolf.",
"A giant bat.",
"A swarm of bats.",
"A shadow panther.",
"A malevolent ghost.",
"A restless ghost.",
"A hungry ghoul.",
"An animated hatchet.",
"A pair of zombies.",
"A slobbering zombie.",
"A pair of graverobbers.",
"An anxious necromancer.",
"An old witch.",
"A lost child.",
"A gravedigger."    ] },
{  "title": "d12 What’s in the cave/cavern?",   "roll": [
"Several skeletons.",
"Lots of bats.",
"Many spider webs.",
"A wight’s stash.",
"A ghoul’s lair.",
"A ghostly presence.",
"The hideout of a killer on the run.",
"Bare rock.",
"Unidentifiable remains.",
"An abandoned cookfire.",
"Some outlaws’ hideout.",
"A creepy hermit."    ] },
{  "title": "d12 Who is in the ancient burial mound?",   "roll": [
"The remains of an ancient war chief.",
"The remains of a tribal shaman.",
"The remains of an ancient war chief.",
"A barrow-wight.",
"An ancient demilich.",
"The remains of ancient monks.",
"Twisted humanoid bones.",
"Malevolent ghosts.",
"Zombie warriors.",
"A skeletal hound.",
"An ancient vampire.",
"Huge, disorganized piles of bones."    ] },
{  "title": "d10 Who is in the grave?",   "roll": [
"The corpse of a young maiden.",
"The corpse of a child.",
"The corpse of an old man.",
"The corpse of an old woman.",
"A fallen adventurer, hastily buried.",
"A dismembered corpse.",
"Twisted humanoid bones.",
"A pile of bones.",
"A newly-made vampire.",
"An empty coffin."    ] },
{  "title": "d10 Who built the ancient ruins?",   "roll": [
"Dwarvish miners.",
"A wood elf king.",
"An ancient elf.",
"A demonic cult.",
"A death cult.",
"Shadow monks.",
"A long-dead emperor.",
"A forgotten king.",
"An evil queen.",
"A dark sorcerer."    ] },
{  "title": "d12 Who resides in the ancient ruins now?",   "roll": [
"A brilliant necromancer.",
"Starved ghouls.",
"Undead guardians.",
"Giant spiders.",
"So many zombies.",
"Restless ghosts.",
"A vengeful wight.",
"A mad wraith.",
"A cursed mummy.",
"An aberrant presence.",
"A pair of manticores.",
"A dracolich."    ] },
{  "title": "d8 What’s in the hole/burrow?",   "roll": [
"A snake.",
"A spider.",
"Slimy mold.",
"Maggots.",
"A severed limb.",
"Unusual fungus.",
"A decomposing body.",
"Cold, dry bones."    ] },
{  "title": "d6 Who lives in the peculiar cottage?",   "roll": [
"A lonely old woman.",
"A reclusive shapeshifter.",
"An eccentric healer.",
"A beautiful witch.",
"A horrible witch.",
"A cranky old priest."    ] },
{  "title": "d6 Who lived in the abandoned cabin?",   "roll": [
"A lonely old woman.",
"A reclusive scholar.",
"An eccentric healer.",
"A poor woodcutter.",
"A fur trader.",
"A dwarf prospector."    ] },
{  "title": "d6 Who resides in the abandoned cabin now?",   "roll": [
"A death hound.",
"A handful of zombies.",
"A paranoid shapeshifter.",
"A mad witch.",
"A malevolent ghost.",
"Restless ghosts."    ] }    ] },

{  "title": "Jungle",  "use": "These are tables for adding quick flavor and encounters to a jungle region. You can use these to generate a single jungle location for an encounter or to set up a map of a jungle region.",   "rolls": [
{  "title": "d12 Interesting Location: You find...",   "roll": [
"A cavern behind a waterfall.",
"The wreck of a riverboat.",
"A cave behind a curtain of tangled of vines.",
"A hole beneath a large tree.",
"A large, damp burrow.",
"A primitive village.",
"A stilt house.",
"A recently vacated campsite.",
"A hastily abandoned campsite.",
"A ruined ancient stone house overgrown with vines.",
"A ruined ancient temple.",
"Ruins of an ancient city."    ] },
{  "title": "d20 Distinguishing Landmark: You see...",   "roll": [
"A tree bearing large, yellow fruit.",
"A tree bearing small, red fruit.",
"A large, hollow tree.",
"A pair of trees from the same root.",
"A tree growing over a boulder.",
"A thicket of brambles.",
"A wide, shallow pool at a river bend.",
"A wide, shallow river with a single large tree growing in its main channel.",
"A moss-covered boulder in the midst of a gently flowing river.",
"Several gentle rapids.",
"A pair of dangerous rapids.",
"A large, gnarled log half-buried in mud.",
"A tree felled by lightning.",
"A colony of colorful mushrooms.",
"An enormous mushroom.",
"A large rock with a mossy overhang.",
"A large, hollow log.",
"A large, rotting log.",
"An old tree with an oddly shaped knot.",
"The stump of an enormous tree."    ] },
{  "title": "d20 Feature: You notice...",   "roll": [
"A flock of birds scatter.",
"A woodpecker drumming.",
"A bird singing sweetly.",
"A brightly colored bird flies away.",
"Birds chirping.",
"A monkey drops a fruit or nut from above.",
"A monkey leaps from one tree to another.",
"Large dragonflies buzzing about.",
"Cicadas chirping loudly.",
"Butterflies fluttering about.",
"A centipede scuttles beneath a rock.",
"An eerie silence.",
"Rain falls lightly.",
"The heat and humidity increase.",
"The sound of leaves rustling above.",
"A vine gently swaying.",
"A small snake slithers off.",
"Brightly, colored berries.",
"The scent of flowers.",
"The smell of decay."    ] },
{  "title": "d20 Encounters: You come upon...",   "roll": [
"Torrential rains.",
"A place where you sink into the mud.",
"A predatory plant with grasping vines.",
"A large jungle cat.",
"A small hunting cat.",
"A giant spider.",
"Several giant spiders.",
"A troop of protective apes.",
"A lone great ape.",
"A rare flightless bird.",
"A malevolent ghost.",
"A pair of lizardfolk hunters.",
"A lizardfolk shaman.",
"A yuan-ti patrol.",
"An ogre.",
"A pair of primitive scouts.",
"A skilled primitive hunter.",
"An old witch.",
"A curious herbalist.",
"A ruthless big-game hunter."    ] },
{  "title": "d12 Flower Color: The flowers are...",   "roll": [
"Deep crimson.",
"Blood red.",
"Iridescent orange.",
"Pale yellow.",
"Brilliant yellow.",
"Dark bluish purple.",
"Pale purple.",
"Dark purple.",
"Magenta.",
"Shockingly pink.",
"Pale pink.",
"White."    ] },
{  "title": "d10 Flower Shape: The petals are...",   "roll": [
"Radiating in a spiraling pattern.",
"Radiating from a hemispherical center.",
"Radiating from a conical center.",
"Radiating in a narrow stalk in the center.",
"Paired and curling back from the center.",
"Triangular and flat.",
"Triangular and curled.",
"Ellipsoidal and flat.",
"Ellipsoidal and curled.",
"The largest petals you’ve ever seen."    ] },
{  "title": "d4 What kind of riverboat was it?",   "roll": [
"A fisherman's raft.",
"An eeler’s canoe.",
"A beasthunter's dugout.",
"A treasure seeker's keelboat."    ] },
{  "title": "d12 What’s in the cave/cavern?",   "roll": [
"A manticore’s lair.",
"Lots of bats.",
"Many spider webs.",
"A medusa’s stash.",
"An rage drake’s lair.",
"A band of kobolds.",
"Some abandoned mining equipment.",
"Bare rock.",
"A potable spring.",
"Unidentifiable remains.",
"Some treasure hunters’ hideout.",
"A strange hermit."    ] },
{  "title": "d8 Who lives in the stilt house?",   "roll": [
"A lonely old woman.",
"A reclusive shapeshifter.",
"An eccentric healer.",
"A beautiful witch.",
"A horrible witch.",
"An outcast wood elf.",
"A horrifying medusa.",
"A scheming hag."    ] },
{  "title": "d8 Who camped here?",   "roll": [
"A lizardfolk hunting party.",
"A band of wandering elves.",
"A primitive hunting party.",
"A primitive war band.",
"A band of yuan-ti raiders.",
"An extraordinary beasthunter.",
"A brave explorer and naturalist.",
"An ambitious treasure hunter."    ] },
{  "title": "d10 Who built the ancient ruins?",   "roll": [
"A lizardfolk chieftain.",
"An aberrant cult.",
"A snake cult.",
"A dragon cult.",
"A death cult.",
"Shadow monks.",
"A long-dead emperor.",
"A forgotten king.",
"An evil queen.",
"A dark sorcerer."    ] },
{  "title": "d12 Who resides in the ruins now?",   "roll": [
"An owlbear.",
"An isolated snake cult.",
"A paranoid shapeshifter.",
"Restless ghosts.",
"Poisonous snakes.",
"Giant spiders.",
"Hungry zombies.",
"Wraiths and shadows.",
"A handful of ogres.",
"A band of lizardfolk warriors.",
"A pair of manticores.",
"A dragon."    ] },
{  "title": "d6 What’s in the hole/burrow?",   "roll": [
"A poisonous snake.",
"A spider.",
"A poisonous frog.",
"A swarm of earthworms.",
"A giant centipede.",
"Unusual fungus."    ] },
{  "title": "d6 What’s up in the tree?",   "roll": [
"A constrictor snake.",
"A giant spider.",
"A swarm of bats.",
"A swarm of locusts.",
"An aggressive ape.",
"A lizardfolk hunter."    ] }    ] },

{  "title": "Mountains",  "use": "These are tables for adding quick flavor and encounters to a mountainous region. You can use these to generate a single mountain location for an encounter or to set up a map of a range of mountains or a mountain road or pass.",   "rolls": [
{  "title": "d20 Interesting Location: You find...",   "roll": [
"A cavern behind a waterfall.",
"A small cave in the crook of a rock wall.",
"An entrance to a rocky cave.",
"A hole under a sheer cliff face.",
"A dark tunnel leading under the mountain.",
"A tunnel in a cliff face.",
"A tunnel leading into an abandoned mine.",
"A peculiar cabin.",
"A cozy little cabin.",
"An abandoned cabin.",
"An abandoned campsite.",
"A poorly marked grave or tomb.",
"An active mining camp.",
"An isolated monastery.",
"A strategically located watchtower.",
"A remote temple.",
"An ancient temple.",
"An abandoned watchtower.",
"A ruined monastery.",
"An enormous bird’s nest."    ] },
{  "title": "d20 Distinguishing Landmark: You see...",   "roll": [
"A trickle of water flowing down a rock wall.",
"A small mountain lake of cold, fresh water.",
"A swiftly flowing small stream.",
"A natural bridge between two cliff faces.",
"A narrow gorge with walls close enough to climb between.",
"A deep gorge with no bottom in sight.",
"A set of deliberately stacked stones.",
"A large boulder eroded by the wind into the shape of a near-perfect sphere.",
"A group of stones arranged in a circle.",
"A boulder shaped to resemble a face.",
"A pair of narrow needle-like peaks.",
"A chimney-like column of rock.",
"A large boulder split in half like an egg.",
"A damp rock wall, covered in moss.",
"The fossilized bones of a great beast visible in a rock wall .",
"A thicket of hardy mountain shrubs growing atop a boulder.",
"A copse of scrawny trees.",
"A gorge where the wind whistles.",
"A gorge with a near perfect echo.",
"A rocky shoulder beneath a snowcap."    ] },
{  "title": "d20 Feature: You notice...",   "roll": [
"A cache of abandoned, decrepit mining equipment.",
"Some old dry bones.",
"A small fossilized leaf.",
"Evidence of a recent encampment.",
"An enormous spider web.",
"An incredible view.",
"The clatter of rocks falling.",
"Loose stones underfoot.",
"An unstable rock wall.",
"A distant sound—a scream, hammers at work, footsteps, or drums.",
"The name of a previous traveler carved into a boulder.",
"An ancient rune carved in a rock wall.",
"A scrawny tree growing with its roots spread over a small boulder.",
"The distant cry of a beast—an eagle, a goat, a mountain lion, or a wolf.",
"The wind whips up to a treacherous speed.",
"Snow flurries begin to fall.",
"The sound of birds chirping.",
"A flock of birds takes flight.",
"An old firepit.",
"Several puddles of cold water."    ] },
{  "title": "d20 What’s in the cave/cavern/tunnel?",   "roll": [
"A mountain lion’s den.",
"Lots of bats.",
"Many spider webs.",
"A troll's stash.",
"An ogre's lair.",
"Some goblins' hideout.",
"Some abandoned mining equipment.",
"Bare rock.",
"A potable spring.",
"Unidentifiable remains.",
"Some outlaws’ hideout.",
"An orc war band.",
"A hungry ettin.",
"A band of dwarvish refugees.",
"A griffon’s nest.",
"A manticore’s den.",
"A basilisk’s lair.",
"A wyvern’s nest.",
"A clan of stone giants.",
"A sleeping dragon."    ] },
{  "title": "d6 Who lives or lived in the cabin?",   "roll": [
"A fugitive from justice.",
"A stubborn miner.",
"A dwarvish prospector.",
"A dwarvish war veteran.",
"A gnomish wizard.",
"A mystic sage."    ] },
{  "title": "d8 Who resides in the abandoned cabin now?",   "roll": [
"An owlbear.",
"An ogre.",
"A troll.",
"A mad witch.",
"A reclusive shapeshifter.",
"Restless ghosts.",
"An outcast orc.",
"A strange hermit."    ] },
{  "title": "d6 Who camped here?",   "roll": [
"A party of orc scouts.",
"A goblin raiding party.",
"Some miners or prospectors.",
"A pair of wandering elves.",
"Some refugees or fugitives.",
"Someone whose purposes are unclear."    ] },
{  "title": "d4 Who is/was digging in this mine?",   "roll": [
"Greedy dwarves.",
"Ambitious humans.",
"Tricky goblins.",
"Industrious kobolds."    ] },
{  "title": "d6 For what were the miners digging?",   "roll": [
"Copper.",
"Gems.",
"Gold.",
"Iron.",
"Silver.",
"A rare metal (d4): 1. adamantine; 2. electrum; 3. mithral; 4. platinum."    ] },
{  "title": "d20 What lives in the abandoned mine/ancient ruin now?",   "roll": [
"Carrion crawler.",
"Cloaker.",
"Darkmantle.",
"Dwarves.",
"Fungi.",
"Kobolds.",
"Ghosts.",
"Mimics.",
"Myconids.",
"Ogres.",
"Ooze.",
"Orcs.",
"Otyugh.",
"Piercer.",
"Roper.",
"Rust monster.",
"Stirges.",
"Trolls.",
"Umber hulk.",
"Wraiths."    ] },
{  "title": "d6 Who built this monastery?",   "roll": [
"An order of elementalist monks.",
"An order of mystics.",
"An extremely secretive order of monks.",
"An order of shadow monks.",
"An order of warrior monks.",
"An unknown order of monks."    ] },
{  "title": "d6 The temple was built to honor...",   "roll": [
"The sun god.",
"The god of the heavens.",
"The moon goddess.",
"The storm god.",
"The earth mother goddess.",
"A long-forgotten god."    ] },
{  "title": "d6 What built the nest?",   "roll": [
"A giant eagle.",
"A giant owl.",
"A clan of harpies.",
"A griffon.",
"A roc.",
"A wyvern."    ] },
{  "title": "d6 What built the watchtower?",   "roll": [
"An expansive empire.",
"A nearby kingdom.",
"An occupying army.",
"Elvish warriors from a past age.",
"A clan of orcs.",
"A goblin kingdom."    ] },
{  "title": "d8 Who holds the watchtower now?",   "roll": [
"A disciplined military company.",
"A rowdy mercenary troop.",
"A band of desperate outlaws.",
"A handful of dwarves.",
"A clan of orcs.",
"A goblin war party.",
"Several harpies.",
"Ghostly warriors."    ] },
{  "title": "d20 Encounters: You come upon...",   "roll": [
"A lost prospector.",
"A solemn warrior.",
"An angry wraith.",
"A malevolent ghost.",
"Some bandits.",
"A seasoned mountaineer.",
"A paranoid shapeshifter.",
"An ancient vampire.",
"Several homeless dwarves.",
"An eccentric witch.",
"A contemplative monk.",
"A mountain lion.",
"A pair of harpies.",
"A flock of ravens.",
"Several orc raiders.",
"A hunting peryton.",
"A mated pair of manticores.",
"A trio of monstrous trolls.",
"A clan of stone giants at rest.",
"A roc tearing apart some prey."    ] },
{  "title": "d8 Hazards/Obstacles: You run into...",   "roll": [
"A perilous rockslide.",
"An icy rime across the path or road.",
"A tumbling boulder.",
"Loose rocks that make for poor footing.",
"A large boulder blocking the way.",
"A place where the path has fallen away leaving a narrow ledge on which to walk.",
"A place where the path or road slopes steeply down toward a cliff edge.",
"A sudden storm bringing heavy snow."    ] }    ] },

{  "title": "Swamps",  "use": "Hopefully these tables will provide you with the tools and flavor you are looking for to grow your own swamp. Feel free to add to the tables or make suggestions on what else can go into a marsh to make it flavorful and unique! Try to pace all this out as the players make their way into the swamp.",   "rolls": [
{  "title": "d10 Roll Odor",   "roll": [
"No odor",
"Uncomfortable sulfur smell. After some exposure it causes players eyes to water",
"Death and decay of corpses lost in the swamp",
"Earthy musk",
"Feet from a soldier who has been marching all day",
"Compost pile",
"Wet dog",
"Odorless gas. Players will begin to get headaches if over exposed",
"Spoiled meat",
"Metallic scent that you can also taste in the back of your throat"    ] },
{  "title": "d10 Roll Perception Fodder",   "roll": [
"Lights moving in the distance. They vanish as players get near",
"The trees are all dead. Their features almost resemble faces...",
"Large sections of waist deep water. Considered difficult terrain",
"Several trees have large claw marks carved into them",
"Canine foot prints that slowly change into human prints",
"A single tree producing apples white as snow. None of them fall to the ground and they are all untouched by other creatures",
"The rotting corpse of a spider the size of a house. No sign of death",
"Small spiderwebs that are face level. DC 14 Perception or walk into them",
"Several humanoid skeletons. Their bones are scattered and look gnawed on",
"A small graveyard. None of the graves are marked and several look as if they were dug up recently"    ] },
{  "title": "d10 Roll Friendly Critters",   "roll": [
"Clouds of insects buzzing around",
"A murder of crows that remain relatively silent. If players get too close they explode into a roar of cawing and fly around the players madly",
"Large beetles that enjoy resting atop players heads",
"Crawling Claws that skitter away when they get spotted",
"Spiders the size of your fist. They catch birds and bats in their webs",
"Large millipedes crawling in and out of fallen logs",
"Toads that look unusually large",
"Very large brown snakes that look to be branches until disturbed",
"2-3 human children clothed in rags. They speak no languages and flee the party",
"A very lost and confused looking treant. It appears as the swamp is slowly claiming him"    ] },
{  "title": "d10 Roll Wild Monsters",   "roll": [
"Pack of ghouls led by a ghast",
"Pack of jackal led by a jackalwere",
"Several vine blights that lie in wait",
"Gnolls and their leader. Traps are set all through the swamp",
"Otyugh that sees the players as a new meal",
"Several vampire spawn that stalk the players. They strike at night when the party sleeps",
"Group of ghosts. They just want some new company in the swamp",
"Zombies that lie beneath the water. They try to drown whoever gets too close",
"A few Will o wisps. They will attempt to split the party and take them down one by one.",
"Undead treants. Use Zombie template"    ] },
{  "title": "d10 Roll Boss Monsters",   "roll": [
"Coven of hags that has been watching the players since they entered. Haunts their dreams if they sleep in swamp",
"Banshee and her group of ghosts. They are looking for new friends",
"A Spider the size of a house. Has a small spider army following him",
"One or several wraiths. They have a small army of the damned at their command",
"A beholder guarding a graveyard. One of the graves leads to a small dungeon",
"A very weathered looking vampire. He is moving a large coffin with the help of vampire spawns",
"Medusa that is looking to add more statues to her collection. The party is a good start",
"Pack of Lycanthropes that have been terrorizing the nearby farmers/villages",
"A wizard from a nearby town and the flesh golems he is making in the swamp. He isn't thrilled you found him",
"Lich who is working on relocating his lair to here. A castle looks to be under construction"    ] } ] }


];
